CLUSTAL W multiple sequence alignment


Q01757_A1_aad                            VTNRHHAGRLR-EILGAEHADVTVVEIESVL----DEQAAADTDGLLSVKPELALGVRDL
P26046_A1_aad                            IASNQHVERLQREVIGDR--NLCIIRLEPLLASL-AQDSSKF-P--AHNLDDLPLTSQQL
Q9C1G0v1_A1_aad                          IASRRHVPRLQNNLIEKR--QLQILTLESVLSSL-HEQPAH----TSSNLDHLQLNSKQL
P25464_A1_aad                            IASQRHVDRLRAEAVGGQ--HLRIIGLESLFDNL-AQQTQHS-PETSGNLTHLPLNSKQL
P94873_A1_aad                            VTHRHYFERLR-EMLAEACPEVELIDIEDALA---DADANAD-PGADAGNPDLGLGSQQV
P19787_A1_aad                            IASNQHVERLQREVIGDR--NLCIIRLEPLLASL-AQDSSKF-P--AHNLDDLPLTSQQL
P27742_A1_aad                            IASNHLAERLQSEVISDR--ELSIIRLEHCLSAI-DQQPSTF-P--RANLRDPSLTSKQL
Q9C1G0v2_A1_aad                          IASRRHVPRLQNNLIEKR--QLQILTLESVLSSL-HEQPAH----TSSNLDHLQLNSKQL
P27743_A1_aad                            VTNRRHAERLR-EVLGDEHASVHVIEVEAVVAGPHPEQAREN--------PGLALSSRDR
                                         :: .:   **: : :      : :: :*  .      :.               *  :: 

Q01757_A1_aad                            AYLTYTSGTTGVPKGVPKYHDSVVNSITDLSERYDMRRPGTERVALFASYVFEPHLRQTL
P26046_A1_aad                            AYVTYTSGTTGFPKGIFKQHTNVVNSITDLSARYGVAGQHHEAILLFSACVFEPFVRQTL
Q9C1G0v1_A1_aad                          AYVTYTSGTTGFPKGIYKEHTSVVNSITDLSARYGVSGSDDEVILLFSAYVFEPFVRQML
P25464_A1_aad                            AYVTYTSGTTGFPKGIYKEHTSVVNSITDLSARYGVAGEDDEVILVFSAYVFEPFVRQML
P94873_A1_aad                            AYVTYTSGTTGIPKGVPKTHRSVVNAITDLSDRYQMREAGTEHVALFAALVFEPFMRQTL
P19787_A1_aad                            AYVTYTSGTTGFPKGIFKQHTNVVNSITDLSARYGVAGQHHEAILLFSACVFEPFVRQTL
P27742_A1_aad                            AYVTYTSGTTGFPKGILKQHTNVVNSITDLSARYGVTGDHHEAILLFSAYVFEPFVRQML
Q9C1G0v2_A1_aad                          AYVTYTSGTTGFPKGIYKEHTSVVNSITDLSARYGVSGSDDEVILLFSAYVFEPFVRQML
P27743_A1_aad                            AYVTYTSGTTGVPKGVPKYHYSVVNSITDLSERYDMRRPGTERVALFASYVFEPHLRQTL
                                         **:********.***: * * .***:***** ** :     * : :*:: ****.:** *

Q01757_A1_aad                            IALINGQTLVVVPEEVRLDPDRFPAYIEEHGVTYLNATGSVLQHFDLRRRTSLKRLLLVG
P26046_A1_aad                            MALVNGHLLAVINDVEKYDADTLLPFIRRHSITYLNGTASVLQEYDFSDCPSLNRIILVG
Q9C1G0v1_A1_aad                          MALTTGNTLAIINDEDKFDPDILLPFIRRHKVTYLNGTASVVQEYDLTTCPSLKRLVLVG
P25464_A1_aad                            MALTTGNSLAIISDEDKFDPDTLIPFIQKHKVTYIHATSSVLQEYDFGSCPSLKRMILVG
P94873_A1_aad                            IALINSQTLVVVPDDVRLDPLRFPRFVDEHRISYLNGTRSVLQHFDLSQCRSLKRMLLVG
P19787_A1_aad                            MALVNGHLLAVINDVEKYDADTLLPFIRRHSITYLNGTASVLQEYDFSDCPSLNRIILVG
P27742_A1_aad                            MALVNGHLLAMVDDAEKYDAEKLIPFIREHKITYLNGTASVLQEYDFSSCPSLKRLILVG
Q9C1G0v2_A1_aad                          MALTTGNTLAIINDEDKFDPDILLPFIRRHKVTYLNGTASVVQEYDLTTCPSLKRLVLVG
P27743_A1_aad                            IALINEQTLVIVPDDVRLDPDLFPEYIERHGVTYLNATGSVLQHFDLRRCASLKRLLLVG
                                         :** . : *.:: :  : *.  :  :: .* ::*::.* **:*.:*:    **:*::***

Q01757_A1_aad                            EELTAAGLRQLRERFSGRIVNEYAFTEAAFVTAVKKFAPGVTERADRSIGRPVRNVKWYV
P26046_A1_aad                            ENLTEARYLALRQRFKNRILNEYGFTESAFVTALKIFDPE-STRKDTSLGRPVRNVKCYI
Q9C1G0v1_A1_aad                          ENLTEARYKALRRRFKARILSEYGFTESAFVTALNIFDPA-SERTNMSLGRPVRNVKCYI
P25464_A1_aad                            ENLTEPRYEALRQRFKSRILNEYGFTESAFVTALNIFEPT-SQRKDMSLGRPVRNVKCYI
P94873_A1_aad                            EELTPSGLRTLRERFHGRIINEYAFTETAFVTAIKEYPPGDAERNDRSIGRPLRNVKCYI
P19787_A1_aad                            ENLTEARYLALRQRFKNRILNEYGFTESAFVTALKIFDPE-STRKDTSLGRPVRNVKCYI
P27742_A1_aad                            ENLTESRYLALRRHFKNCILNEYGFTESAFVTALNVFEPG-SARNNTSLGRPVRNVKCYI
Q9C1G0v2_A1_aad                          ENLTEARYKALRRRFKARILSEYGFTESAFVTALNIFDPA-SERTNMSLGRPVRNVKCYI
P27743_A1_aad                            EELTASGLRQLREKFAGRVVNEYAFTEAAFVTAVKEFGPGVTERRDRSIGRPLRNVKWYV
                                         *:** .    **.:*   ::.**.***:*****:: : *  : * : *:***:**** *:

Q01757_A1_aad                            LSQDLKRLPVGAIGELYIGGCGVAPGYLNRDDLTAERFLTNPYASEQDRARGTNARIYRT
P26046_A1_aad                            LNPSLKRVPIGATGELHIGGLGISKGYLNRPELTPHRFIPNPFQTDCEKQLGINSLMYKT
Q9C1G0v1_A1_aad                          LDSNLKRLPLGVTGELHIGGLGISRGYMNRDELTRAKFLKNPYQ-DDEKGRGVNGLMYKT
P25464_A1_aad                            LDANLKRVPIGVTGELHIGGLGISRGYMNREELTRQKFLPNPYQTDKERQRGVNSTMYKT
P94873_A1_aad                            VSQNMKQVPIGAIGELYIGGTGVASGYLNRPDLTAERFLDNPFRTPGERAAGRNERIYRT
P19787_A1_aad                            LNPSLKRVPIGATGELHIGGLGISKGYLNRPELTPHRFIPNPFQTDCEKQLGINSLMYKT
P27742_A1_aad                            LNKSLKRVPIGATGELHIGGLGISKGYLNRPDLTPQRFIPNPFQTDHEKELGLNQLMYKT
Q9C1G0v2_A1_aad                          LDSNLKRLPLGVTGELHIGGLGISRGYMNRDELTRAKFLKNPYQ-DDEKGRGVNGLMYKT
P27743_A1_aad                            LSQGLKQLPIGAIGELYIGGCGVAPGYLNRDDLTAERFTANPFQTEEEKARGRNGRLYRT
                                         :. .:*::*:*. ***:*** *:: **:** :**  :*  **:    ::  * *  :*:*

Q01757_A1_aad                            GDLARMLPSGEVEFMGRSDFQLKLNGVRVEPGEIEAQATEYAGVRKCVVIARE---GAGG
P26046_A1_aad                            GDLARWLPNGEVEYLGRADFQIKLRGIRIEPGEIETMLAMYPRVRTSLVVSKKLRNGPEE
Q9C1G0v1_A1_aad                          GDLARWLPNGEVEYLGRADFQIKLRGIRIEPGEIESTLGAYPGIRTSIVVSKKLLSQGEE
P25464_A1_aad                            GDLARWLPSGEVEYLGRADFQIKLRGIRIEPGEIESTLAMYPGIRASIVVSKKLLSQGQE
P94873_A1_aad                            GDLAKFLPDGQIEFMGRSDFQLKLNGVRVEPGEIEARALEFPGVRQCVVVARG---ESVE
P19787_A1_aad                            GDLARWLPNGEVEYLGRADFQIKLRGIRIEPGEIETMLAMYPRVRTSLVVSKKLRNGPEE
P27742_A1_aad                            GDLARWLPNGEIEYLGRADFQIKLRGIRIEPGEIESTLAGYPGVRTSLVVSKRLRHGEKE
Q9C1G0v2_A1_aad                          GDLARWLPNGEVEYLGRADFQIKLRGIRIEPGEIESTLGAYPGIRTSIVVSKKLLSQGEE
P27743_A1_aad                            GDLARVLLNGEVEFMGRADFQLKLNGVRVEPGEIEAQATEFPGVKKCVVVAKE---NATG
                                         ****: * .*::*::**:***:**.*:*:******:    :. :: .:*:::        

Q01757_A1_aad                            GSDRHLVG
P26046_A1_aad                            TTNEHLVG
Q9C1G0v1_A1_aad                          TRQDHLVG
P25464_A1_aad                            TIQDHLVG
P94873_A1_aad                            TGNWRLIG
P19787_A1_aad                            TTNEHLVG
P27742_A1_aad                            TTNEHLVG
Q9C1G0v2_A1_aad                          TRQDHLVG
P27743_A1_aad                            --DRHLVG
                                           : :*:*
