CLUSTAL W multiple sequence alignment


BGC0001125_AIW82284.1_2452_mod3_ala      LTQSQCLKSLPDVDNLRICLDTDWGIIETQSQENPVSEVAPNNLAYIIYTSGSTGKPKGV
Q70LM6_A3_5__ala                         LTQERLLPMLPEHTAQVICLDRDWACMAVQPEANVPNLAAPTNLSYVIYTSGSTGLPKGV
Q6E7J5_A1_ala                            LASESVLDSLPEHQAKIVCLDTIGETITNEGTDNPASQVTPENLAYVIYTSGSTGKPKGV
Q8G983/24744797_A2_7__ala                LTQQTLLSHLSHYSGDRVVLDRDAAIIAQQPKTNPKSQVSSSNSVYVIYTSGSTGKPKGV
Q9S1A9_A2_7__ala                         LTQAKLVEKLGNYPGNLVILEAEARNIALESPENLSLPVSSSNTAYVIYTSGSTGKPKGV
                                         *:.   :  * .     : *:     :  :   *    .:. *  *:******** ****

BGC0001125_AIW82284.1_2452_mod3_ala      AIAHCSPVALVAWALKVFTPQQLAGVLASTSLCFDLSIFEMFVPLSCGGMVIVAENALHL
Q70LM6_A3_5__ala                         AIQHSSVIAFIFWAKTVFSAEEMSGVLASTSICFDLSVYEIFVTLSCGGKVILADNALHL
Q6E7J5_A1_ala                            AIEHHSPVALCYWASQVFTIKELAAVLASTSICFDLSVFEIFVTLSQGGQVILAQNALDL
Q8G983/24744797_A2_7__ala                VIEHRSTVTLLDWARTVFSFDELAGVLASTSVCFDLSVFELFLPLTVGGAVILADNALAL
Q9S1A9_A2_7__ala                         VIEHHSTTTLLNWSKEVFSSEELAGVLGSTSICFDLSVFELFLPLAVGGKIILAQNVLDL
                                         .* * *  ::  *:  **: .:::.**.***:*****::*:*:.*: ** :*:*:*.* *

BGC0001125_AIW82284.1_2452_mod3_ala      PELIAFEQVTLINTVPSAIRELLNGPGLPQSLATVNLAGEPLPLSLVQQLYQRQTIHQVF
Q70LM6_A3_5__ala                         PSLPAAKEVTLINTVPSAAKELVRMNAIPPSVRVVNLAGEPLPNTLAQSLYALGHVQKVF
Q6E7J5_A1_ala                            PNIKS--EITLINTVPSAITELSRINAIPDSVKVINLAGEPFSNQLLQRLYQQENIQSVY
Q8G983/24744797_A2_7__ala                PNLAAATEVTLINTVPTAIAQLLALEAIPQSVRTVNLAGEPLSNSLVQKLYQLPQIERVY
Q9S1A9_A2_7__ala                         PSLSAAKEVTLINTVPTAIAQLLEIEAIPETVQTVNFAGEALSNQLVQKLYQQENIKNVY
                                         *.: :  ::*******:*  :*    .:* :: .:*:***.:.  * * **    :. *:

BGC0001125_AIW82284.1_2452_mod3_ala      NLYGPSETTTYSTFALCNRGDSLAPTIGRAIANTQIYILDALMQPVPIGVRGELYIGGAG
Q70LM6_A3_5__ala                         NLYGPSEDTTYSTYVQVTKGAKTEPTIGRPLANTQAYVLDAKLQPVPLGLPGELYLGGDG
Q6E7J5_A1_ala                            NLYGPSEYTTYTTFTLLKKGTTTQPTIGHPIANTQVYILDSHLQPVPIGVVGELYIGGDG
Q8G983/24744797_A2_7__ala                NLYGPSEDTSYSTFSCIEKGATTQPSIGRPIAHSQVYLLNATHQPVPLGTIGELYMGGAG
Q9S1A9_A2_7__ala                         NLYGPSEDTTYSTFSLVPKKDHGQPSIGRPIANTQVYILDSFKQPVPLGTIGDLYIGGKG
                                         ******* *:*:*:    :     *:**:.:*::* *:*::  ****:*  *:**:** *

BGC0001125_AIW82284.1_2452_mod3_ala      VARGYLNRPELTAEKFIPNPFEN--------SKFHRLYKTGDLARYLPDGNIEYLGRIDN
Q70LM6_A3_5__ala                         LARGYLKRPKMTAERFLPNPFHP--------DPDARMYSTGDLVRYLPDGQLEYLGRIDH
Q6E7J5_A1_ala                            LARGYHNRPELTAEKFIPNPFDN--------STSTRLYKTGDLARYLPDGNIAFIGRIDH
Q8G983/24744797_A2_7__ala                LARGYLHRPELTAEKFIANPFHSPLQKYQGLSPSPKLYKTGDLARYRPDGNLEFLGRSDY
Q9S1A9_A2_7__ala                         LARCYLNQPELTAEKFISNPFSN--------EPKAKLYKTGDLARYLPDGNIDFLGRGDN
                                         :** * ::*::***:*:.***          .   ::*.****.** ***:: ::** * 

BGC0001125_AIW82284.1_2452_mod3_ala      QVKLRGFRIELGEIETAIALHPQLKQAVVSIREDQPGIRRLVA
Q70LM6_A3_5__ala                         QVKIRGYRIELGELEAVLRSHPQIKEAVVVAKEDKLGEKRLVA
Q6E7J5_A1_ala                            QVKIRGFRIEMGEIEAFVSQYPDVKENAVIAQSDPAGGKRLVV
Q8G983/24744797_A2_7__ala                QIKLRGFRIELGEIEVVLENCPGVKQAVVLRREDLVGGAKLVA
Q9S1A9_A2_7__ala                         QVKLRGFRIELGEIEATLGTYPQVKQKVVKVWEDSYRNKRLVA
                                         *:*:**:***:**:*. :   * :*: .*   .*     :**.
