CLUSTAL W multiple sequence alignment


P39581_A1_ala                            AAGLSIDAVGQQIQTVSAEELLENEGGS-VSQDQWVKEHETFYIIYTSGSTGNPKGVQIS
P68878_A1_ala                            TTDESFESLEGEVFTI---EDIKTSQDP-VIFDSQIKDNDTVYTIFTSGSTGEPKGVQIE
P59591_A1_ala                            IGEFPLEVDNVPILDVSQVSAIFEEKTP-YEVTHSVKGDDNYYIIFTSGTTGLPKGVQIS
P68876_A1_ala                            TTDESFESLEGEVFTI---EDIKTSQDP-VIFDSQIKDNDTVYTIFTSGSTGEPKGVQIE
Q53526_A1_ala                            VDDFPIDNLQVPVIQYSQLEEIFKQKLS-YQINHAVKGDDTYYIIFTSGTTGKPKGVQIS
P35854_A1_ala                            VAPLPITVPDVKIIRAPALHQAEQSHAPIHSLQHAVAGDDNYYIIFTSGTTGKPKGVQIS
P0A398_A1_ala                            ISAFPLEQVSTPMINLAQVQEAFAQGNN-YEITHPVKGDDNYYIIFTSGTTGKPKGVQIS
                                             .:      :           .          :  .:. * *:***:** ******.

P39581_A1_ala                            AANLQSFTDWICAD--FPVSGGK-IFLNQAPFSFDLSVMDLYPCLQSGGTLHCVTKDAVN
P68878_A1_ala                            YASLVQFTEWML-E--LNKSGNEQQWLNQAPFSFDLSVMAIYPCLASGGTLNLVDKNMIN
P59591_A1_ala                            HDNLLSFTNWMISDDEFSVPERP-QMLAQPPYSFDLSVMYWAPTLAMGGTLFALPKTVVN
P68876_A1_ala                            YASLVQFTEWML-E--LNKSGNKQQWLNQAPFSFDLSVMAIYPCLASGGTLNLVDKNMIN
Q53526_A1_ala                            HDNLLSFTNWMINAEAFAIPHRP-QMLAQPPYSFDLSVMYWAPTLALGGTLFALPKEITA
P35854_A1_ala                            HDNLLSYVNWNISD--FGLEEGV-VAMSQPPYSFDLSVMDLYPTLVLGGTLKALPKEVTD
P0A398_A1_ala                            HDNLLSFTNWMITDKEFATPSRP-QMLAQPPYSFDLSVMYWAPTLALGGTLFTLPSVITQ
                                           .* .:.:*      :         : *.*:*******   * *  ****  : .    

P39581_A1_ala                            KPKVLFEELKKSGLNVWTSTPSFVQMCLMDPGFSQDLLPHADTFMFCGEVLPVSVAKALL
P68878_A1_ala                            KPKLLNEMLTATPINIWVSTPSFMEMCLLLPTLNEEQYGSLNEFFFCGEILPHRAAKALV
P59591_A1_ala                            DFKKLFATINELPIQVWTSTPSFADMALLSNDFNSETLPQLTHFYFDGEELTVKTAQKLR
P68876_A1_ala                            KPKLLNEMLTATPINIWVSTPSFMEMCLLLPTLNEEQYGSLNEFFFCGEILPHRAAKALV
Q53526_A1_ala                            DFKQLFTTITNYHWCVDINT-FFVDMAMLSDDFNAQQLPHLTHFYFDGEELTVKTAKKLR
P35854_A1_ala                            NFKELFATLPKLGLNEWVSTPSFVEIALLDPNFKQENYPNLTHFLFCGEELVNKTAQALI
P0A398_A1_ala                            DFKQLFAAIFSLPIAIWTSTPSFADMAMLSEYFNSEKMPGITHFYFDGEELTVKTAQKLR
                                         . * *   :         .*  * ::.::   :. :       * * ** *   .*: * 

P39581_A1_ala                            ERFPKAKIFNTYGPTEATVAVTSVEITNDVISRSESLPVGFAKPDMNIFIMDEEGQPLPE
P68878_A1_ala                            NRFPSATIYNTYGPTEATVAVTSIQITQEILDQYPTLPVGVERP----------GARLST
P59591_A1_ala                            QRFPKARIVNAYGPTEATVALSAVAITDEMLETCKRLPIGYTKDDSPTYVIDEEGHKLPN
P68876_A1_ala                            SRFPSATIYNTYGPTEATVAVTSIQITQEILDQYPTLPVGVERL----------GARLST
Q53526_A1_ala                            QRFPQARIVNAYGPTEATVALSALAVTDKMLETCKRLPIGYTKPDSPTFIIDESGHKLAN
P35854_A1_ala                            TRFPKATVYNTYGPTEATVAVTGMAITQAIVDQYPRLPIGYAKPDTNVYVVDEQGEQVSA
P0A398_A1_ala                            ERFPNARIINAYGPTEATVALSAVAVTDEMLATLKRLPIGYTKADSPTFIIDEEGNKLPN
                                          ***.* : *:*********::.: :*: ::     **:*  :           *  :. 

P39581_A1_ala                            GEKGEIVIAGPSVSRGYLGEPELTEKAFFSHEGQWAYRTGDAGFI-QDGQIFCQGRLDFQ
P68878_A1_ala                            TDEGELVIEGQSVSLGYLKNDQKTAEVFNFDDGIRTYHTGDKAKF-ENGQWFIQGRIDFQ
P59591_A1_ala                            GEQGEIIIAGPAVSKGYLNNPEKTAEAFFQFEGLPAYHTGDLGSMTDEGLLLYGGRMDFQ
P68876_A1_ala                            TDDGELVIEGQSVSLGYLKNDQKTAEVFNFDDGIRTYHTGDKAKF-ENGQWFIQGRIDFQ
Q53526_A1_ala                            GQQGEIIVSGPAVSKGYLNNPERTAAAFFEFEGLPAYHTGDLGSMTDEGLLLYGGRMDFQ
P35854_A1_ala                            GTEGELMIVGPSVSKGYLNNPDKTAAAFFKAGNQRGYRSGDLVTMTADGMVFYRGRTDFQ
P0A398_A1_ala                            GEQGEIIVSGPAVSKGYMNNPEKTAEAFFEFEDLPAYHTGDVGTMTDEGLLLYGGRMDFQ
                                           .**::: * :** **: : : *  .*    .   *::**   :  :*  :  ** ***

P39581_A1_ala                            IKLHGYRMELEEIEFHVRQSQYVRSAVVIP-YQPNGTVEYLIA
P68878_A1_ala                            IKLNGYRMELEEIETQLRQSEFVKEAIVVP-VYKNDKVIHLIG
P59591_A1_ala                            IKFNGYRIELEDVSQNLNKSQYVKSAVAVPRYNKDHKVQNLLA
P68876_A1_ala                            IKLNGYRMELEEIETQLRQSEFVKEAIVVP-VYKNDKVIHLIG
Q53526_A1_ala                            IKFNGYRIELEEVSQNLNKSQYIASAVAVPRYNKDHKVQNLLA
P35854_A1_ala                            VKLHGYRIELEDVDHNLNQVSYIKQASTVPRYDKDHKVAQLIA
P0A398_A1_ala                            IKFNGYRIELEDVSQNLNKSRFIESAVAVPRYNKDHKVQNLLA
                                         :*::***:***::. ::.:  :: .* .:*    : .*  *:.
