CLUSTAL W multiple sequence alignment


Q83VS0/81321400_A9_19__ala               LAQTA-TQGLLAD---VSVPVINL-DLSDWQD-----QSV-------QNPQVPGLTSAHL
BGC0001125_AIW82284.1_2452_mod3_ala      LTQSQ-CLKSLPD---VDNLRICLDT--DWGI--IETQSQ-------ENPVSE-VAPNNL
Q83VS1_A1_6__ala                         LAQTA-TQGLLAD---VSVPVINL-DLSVWQD-----ESV-------QNPQVPGLTSAHL
BGC0000464_CDG17982.1_523_mod1_ala       VTQKAIATQMLADGVTRSVPTVLIDDILNHQEPVPEARSIAPPLTDNPDARRLGLTSRHL
Q83VS0_A3_13__ala                        LAQSA-TEALLAD---VSVPVINL-DLGNWQD-----QSV-------QNPQVPGLTSAHL
Q83VS0_A7_17__ala                        LAQTA-TQGLLAD---VSVPVINL-DLSNWQD-----ESV-------QNPQVPGLTSAHL
Q83VS0_A2_12__ala                        LAQTA-TQGLLAD---VSVPVINL-DLSNWQD-----ESV-------QNPQVPGLTSAHL
Q9FDB3_A5_5__ala                         LVQTA-TQRLLAD---TSVPLIHL-DLSDWQD-----ESV-------QNPRVPGLTSAHL
BGC0000464_CDG17980.1_1601_mod2_ala      LTQTT-----LADKLVSTVSTVLLDS----QEPFMAMEAL--PAGD-PDPQTLGLTSHHL
Q83VS1_A5_ala                            LVQAA-TRHLLAG---VSVQAIDLDDQSAWQD-----EPV-------QNPDVEGLSSAHL
Q83VS1_A1_ala                            LAQTA-TQGLLAD---VSVPVINL-DLSVWQD-----ESV-------QNPQVPGLTSAHL
Q83VS1_A5_10__ala                        LVQAA-TRHLLAG---VSVQAIDLDDQSAWQD-----EPV-------QNPDVEGLSSAHL
Q70LM6_A3_5__ala                         LTQER-LLPMLPE---HTAQVICLDR--DWAC--MAVQPE-------ANVPNL-AAPTNL
                                         :.*       *.         : :             ..         :      :. :*

Q83VS0/81321400_A9_19__ala               AYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHTAFDA----SALEKTLFSTSLNFDLAVYE
BGC0001125_AIW82284.1_2452_mod3_ala      AYIIYTSGSTGKPKGVAIAHCSPVALVAWALKVFTP----QQLAGVLASTSLCFDLSIFE
Q83VS1_A1_6__ala                         AYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHTAFDG----SALEKTLFSTSLNFDLAVYE
BGC0000464_CDG17982.1_523_mod1_ala       AYVIYTSGSTGLPKGVTITHRNTVNLLTWAQRTFSA----EELAHTLFATSFNFDLSVYE
Q83VS0_A3_13__ala                        AYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHSAFDAGTATSALEKTLFSTSLNFDLAVYE
Q83VS0_A7_17__ala                        AYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHSAFDA----SALEKTLFSTSLNFDLAVYE
Q83VS0_A2_12__ala                        AYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHSAFDA----SALEKTLFSTSLNFDLAVYE
Q9FDB3_A5_5__ala                         AYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHAAFDAGTNNSALEKTLFSTSLNFDLAVYE
BGC0000464_CDG17980.1_1601_mod2_ala      AYVIYTSGSTGLPKGVAVTHRNTVNFLTWAQRTFQR----DELAQALFATSLNFDISVFE
Q83VS1_A5_ala                            AYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHHAFNG----SALEKTLFSTSLNFDLAVYE
Q83VS1_A1_ala                            AYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHTAFDG----SALEKTLFSTSLNFDLAVYE
Q83VS1_A5_10__ala                        AYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHHAFNG----SALEKTLFSTSLNFDLAVYE
Q70LM6_A3_5__ala                         SYVIYTSGSTGLPKGVAIQHSSVIAFIFWAKTVFSA----EEMSGVLASTSICFDLSVYE
                                         :*:******** **** : * . : :: **  .*      . :  .* :**: **::::*

Q83VS0/81321400_A9_19__ala               CFAPLTSGGSIEVVKNVLELQHG---------------EHDIGLINTVPSALKALLEVNG
BGC0001125_AIW82284.1_2452_mod3_ala      MFVPLSCGGMVIVAENALHLPEL-------------IAFEQVTLINTVPSAIRELLNGPG
Q83VS1_A1_6__ala                         CFAPLTSGGSIEVVKNVLELQHG---------------EHDIGLINTVPSALKALLEVNG
BGC0000464_CDG17982.1_523_mod1_ala       CFVPLISGGTVHLVADALALINTERFTSERFTSERFTSEKAISLINTVPSAIAHLLEADA
Q83VS0_A3_13__ala                        CFAPLTSGGSIEVVKNVLELQNG---------------EHDIGLINTVPSALKALLDVDG
Q83VS0_A7_17__ala                        CFAPLTSGGSIEVVKNVLELQHG---------------EHDIGLINTVPSALKALLDVDG
Q83VS0_A2_12__ala                        CFAPLTSGGSIEVVKNVLELQHG---------------EHDIGLINTVPSALKALLEVNG
Q9FDB3_A5_5__ala                         CFAPLTSGGSIEVVRNVLELQHL---------------DDDIRLINTVPSALKALLETDG
BGC0000464_CDG17980.1_1601_mod2_ala      CFAPLLVGGTVHLMPDILSLVNA-------------ATTPSLSLINTVPSAIVHLIEARA
Q83VS1_A5_ala                            CFAPLTSGGSINVVKNVLELQHG---------------EHDIGLVNTVPSALKALLEING
Q83VS1_A1_ala                            CFAPLTSGGSIEVVKNVLELQHG---------------EHDIGLINTVPSALKALLEVNG
Q83VS1_A5_10__ala                        CFAPLTSGGSINVVKNVLELQHG---------------EHDIGLVNTVPSALKALLEING
Q70LM6_A3_5__ala                         IFVTLSCGGKVILADNALHLPSL-------------PAAKEVTLINTVPSAAKELVRMNA
                                          *..*  ** : :  : * *                     : *:******   *:   .

Q83VS0/81321400_A9_19__ala               LPESVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWVAMDRDDGFAAHI
BGC0001125_AIW82284.1_2452_mod3_ala      LPQSLATVNLAGEPLPLSLVQQLYQRQTIHQVFNLYGPSETTTYSTFALCNRGDSLAPTI
Q83VS1_A1_6__ala                         LPESVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWVAMDREHGFAAHI
BGC0000464_CDG17982.1_523_mod1_ala       IPPTVQTVNLAGEALKPHIVERLFTLSSIQNVCNLYGPSETTTYSTWTRLNRTTGVVTHI
Q83VS0_A3_13__ala                        LPRSVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWVAMDREDGFAAHI
Q83VS0_A7_17__ala                        LPRSVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWVAMDREDGFAAHI
Q83VS0_A2_12__ala                        LPESVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWVAMDREHGFAAHI
Q9FDB3_A5_5__ala                         LPKSVHTVNVAGEALKRSLVEALFEQTGVQRLCNLYGPSETTTYSSWVAMDREDGFAAHI
BGC0000464_CDG17980.1_1601_mod2_ala      VPSCIQTVNLAGEALKAHVVEHLFAHSTVQDVCNLYGPSETTIYSTWTRMKRTTGFHHHI
Q83VS1_A5_ala                            LPESVHTVNVAGEALKRSLVENLFEKTGVQRLCNLYGPSETTTYSSWVAMDREDGFAAHI
Q83VS1_A1_ala                            LPESVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWVAMDREHGFAAHI
Q83VS1_A5_10__ala                        LPESVHTVNVAGEALKRSLVENLFEKTGVQRLCNLYGPSETTTYSSWVAMDREDGFAAHI
Q70LM6_A3_5__ala                         IPPSVRVVNLAGEPLPNTLAQSLYALGHVQKVFNLYGPSEDTTYSTYVQVTKGAKTEPTI
                                         :*  : .**:***.*   :.: *:    :: : ******* * **::.   :       *

Q83VS0/81321400_A9_19__ala               GKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAERFVKDPFSPQPAA
BGC0001125_AIW82284.1_2452_mod3_ala      GRAIANTQIYILDALMQPVPIGVRGELYIGGAGVARGYLNRPELTAEKFIPNPFENSKFH
Q83VS1_A1_6__ala                         GKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAERFLKDPFSQQSAA
BGC0000464_CDG17982.1_523_mod1_ala       GRPIANTQIYILDADKQPVPLGVTGEIYIAGAGVASGYLNRPQLTAERFLSDPFSLEANA
Q83VS0_A3_13__ala                        GKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAERFVKDPFSSQPAA
Q83VS0_A7_17__ala                        GKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAERFVKDPFSSQPAA
Q83VS0_A2_12__ala                        GKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAERFLKDPFSQNPAA
Q9FDB3_A5_5__ala                         GKPVGNTRFYLLDEQQQPVPRGVAGEIYIGGAGVARGYRNRDDLTAERFLKDPFSPQPAA
BGC0000464_CDG17980.1_1601_mod2_ala      GRPIANTQIYILDTQGQPVPLGVIGEIHIAGAGVARGYFNRPELTKARFLTDPFSPEPDA
Q83VS1_A5_ala                            GRPVGNTRFYLLDEQQQLVPRGVPGEIYIGGAGVARGYLNRDDLTAERFLTDPFSLTPGA
Q83VS1_A1_ala                            GKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAERFLKDPFSQQSAA
Q83VS1_A5_10__ala                        GRPVGNTRFYLLDEQQQLVPRGVPGEIYIGGAGVARGYLNRDDLTAERFLTDPFSLTPGA
Q70LM6_A3_5__ala                         GRPLANTQAYVLDAKLQPVPLGLPGELYLGGDGLARGYLKRPKMTAERFLPNPFHPDPDA
                                         *:.:.**: *:**   * ** *: **:::.* *:* ** :* .:*  :*: :**      

Q83VS0/81321400_A9_19__ala               RMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLTRHPAIHEAVVAARED-
BGC0001125_AIW82284.1_2452_mod3_ala      RLYKTGDLARYLPDGNIEYLGRIDNQVKLRGFRIELGEIETAIALHPQLKQAVVSIRED-
Q83VS1_A1_6__ala                         RMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLARHPAIHEAVVAARED-
BGC0000464_CDG17982.1_523_mod1_ala       RMYKTGDLGRWLPDGNIEYLGRNDFQVKLRGFRIELGEIEAQLVQCHGVREAVVLAREEV
Q83VS0_A3_13__ala                        RMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLTKHPAVHEAVVTARED-
Q83VS0_A7_17__ala                        RMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLAKHPAVHEAVVTARED-
Q83VS0_A2_12__ala                        RMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLAKHPAVHEAVVTARED-
Q9FDB3_A5_5__ala                         RMYHTGDLGRYLPDGNIQYLGRNDDQVKIRGFRIELGEIDACLAKHPAVQDAVVTARED-
BGC0000464_CDG17980.1_1601_mod2_ala      RMYKTGDLGRWLPDGNIEYLGRNDFQVKLRGFRIELGEIEAQLMQCHGVRNAVVIARED-
Q83VS1_A5_ala                            RMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDACLAKHPAVHEAVVMARED-
Q83VS1_A1_ala                            RMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLARHPAIHEAVVAARED-
Q83VS1_A5_10__ala                        RMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDACLAKHPAVHEAVVMARED-
Q70LM6_A3_5__ala                         RMYSTGDLVRYLPDGQLEYLGRIDHQVKIRGYRIELGELEAVLRSHPQIKEAVVVAKED-
                                         *:* **** *:****:::**** * ***:**:******::: :     :::***  :*: 

Q83VS0/81321400_A9_19__ala               ---------VPGDKRLVA
BGC0001125_AIW82284.1_2452_mod3_ala      ---------QPGIRRLVA
Q83VS1_A1_6__ala                         ---------VPGDKRLVA
BGC0000464_CDG17982.1_523_mod1_ala       VGKEIAGENRAGQKRLVA
Q83VS0_A3_13__ala                        ---------IPGDKRLVA
Q83VS0_A7_17__ala                        ---------IPGDKRLVA
Q83VS0_A2_12__ala                        ---------IPGDKRLVA
Q9FDB3_A5_5__ala                         ---------VPGDKRLVA
BGC0000464_CDG17980.1_1601_mod2_ala      ---------EPGQKRLVA
Q83VS1_A5_ala                            ---------VPGEIRLVA
Q83VS1_A1_ala                            ---------VPGDKRLVA
Q83VS1_A5_10__ala                        ---------VPGEIRLVA
Q70LM6_A3_5__ala                         ---------KLGEKRLVA
                                                    *  ****
