CLUSTAL W multiple sequence alignment


Q83VS0_A3_13__ala                        -LAQSATEALLADVSVPVINL-D---LGNWQDQSVQNPQVPGLTSAH--LAYLIYTSGST
Q83VS0_A7_17__ala                        -LAQTATQGLLADVSVPVINL-D---LSNWQDESVQNPQVPGLTSAH--LAYLIYTSGST
BGC0000414_BAO84861.1_508_mod1_ala       -ITTQNLTATLPEGTWHALTLD----TTHTGRHPTRRPTNKTVPAN---LAYTIYTSGST
Q83VS1_A1_6__ala                         -LAQTATQGLLADVSVPVINL-D---LSVWQDESVQNPQVPGLTSAH--LAYLIYTSGST
Q83VS0/81321400_A9_19__ala               -LAQTATQGLLADVSVPVINL-D---LSDWQDQSVQNPQVPGLTSAH--LAYLIYTSGST
AHH53507.1_2589_mod3_ala                 LSTSRQIDRLAVEPEIPVLLLDGYEVQAELADRQADEAHAWERAASPERLAYVIYTSGST
Q83VS1_A5_10__ala                        -LVQAATRHLLAGVSVQAIDLDD---QSAWQDEPVQNPDVEGLSSAH--LAYLIYTSGST
BGC0000439_AHH53507.1_2589_mod3_ala      LSTSRQIDRLAVEPEIPVLLLDGYEVQAELADRQADEAHAWERAASPERLAYVIYTSGST
Q50E73_A3_8__ala                         -VTSTDVRTLRTVPRVE---LDDEATRATLVAAPATGPDVKMSASHP---AYVIYTSGST
Q83VS0_A2_12__ala                        -LAQTATQGLLADVSVPVINL-D---LSNWQDESVQNPQVPGLTSAH--LAYLIYTSGST
Q83VS1_A5_ala                            -LVQAATRHLLAGVSVQAIDLDD---QSAWQDEPVQNPDVEGLSSAH--LAYLIYTSGST
Q83VS1_A1_ala                            -LAQTATQGLLADVSVPVINL-D---LSVWQDESVQNPQVPGLTSAH--LAYLIYTSGST
                                           .                 *             .  .     .:     ** *******

Q83VS0_A3_13__ala                        GLPKGVMIEHRNTVNFLTWAHSAFDAGTATSALEKTLFSTSLNFDLAVYECFAPLTSGGS
Q83VS0_A7_17__ala                        GLPKGVMIEHRNTVNFLTWAHSAFDA----SALEKTLFSTSLNFDLAVYECFAPLTSGGS
BGC0000414_BAO84861.1_508_mod1_ala       GRPKGVMIEHRQTTTLLAWAHTTYTP----AQLTNVLASTSICFDLSVFEIFAPLTTGGS
Q83VS1_A1_6__ala                         GLPKGVMIEHRNTVNFLTWAHTAFDG----SALEKTLFSTSLNFDLAVYECFAPLTSGGS
Q83VS0/81321400_A9_19__ala               GLPKGVMIEHRNTVNFLTWAHTAFDA----SALEKTLFSTSLNFDLAVYECFAPLTSGGS
AHH53507.1_2589_mod3_ala                 GRPKGVGVSVHSMANLLEWARAEFGA----DAFGRAVFATSLNFDVSVFELFGPLVSGGT
Q83VS1_A5_10__ala                        GLPKGVMIEHRNTVNFLTWAHHAFNG----SALEKTLFSTSLNFDLAVYECFAPLTSGGS
BGC0000439_AHH53507.1_2589_mod3_ala      GRPKGVGVSVHSMANLLEWARAEFGA----DAFGRAVFATSLNFDVSVFELFGPLVSGGT
Q50E73_A3_8__ala                         GRPKGVVISHGSLANFLAWAREDLGA----ERLRHVVLSTSLSFDVSVVELFAPLSCGGT
Q83VS0_A2_12__ala                        GLPKGVMIEHRNTVNFLTWAHSAFDA----SALEKTLFSTSLNFDLAVYECFAPLTSGGS
Q83VS1_A5_ala                            GLPKGVMIEHRNTVNFLTWAHHAFNG----SALEKTLFSTSLNFDLAVYECFAPLTSGGS
Q83VS1_A1_ala                            GLPKGVMIEHRNTVNFLTWAHTAFDG----SALEKTLFSTSLNFDLAVYECFAPLTSGGS
                                         * **** :.  . ..:* **:           : ..: :**: **::* * *.**  **:

Q83VS0_A3_13__ala                        IEVVK-NVLEL--QNGEHDIGLINTVPSALKALLDVDGLPRSVHTVNVAGEALKQSLVES
Q83VS0_A7_17__ala                        IEVVK-NVLEL--QHGEHDIGLINTVPSALKALLDVDGLPRSVHTVNVAGEALKQSLVES
BGC0000414_BAO84861.1_508_mod1_ala       ITLTHTNALDLL-TPPHPDITLINTVPSIIQELHTHNAIPPTTTTINLAGEPLPPHLVNT
Q83VS1_A1_6__ala                         IEVVK-NVLEL--QHGEHDIGLINTVPSALKALLEVNGLPESVHTVNVAGEALKQSLVES
Q83VS0/81321400_A9_19__ala               IEVVK-NVLEL--QHGEHDIGLINTVPSALKALLEVNGLPESVHTVNVAGEALKQSLVES
AHH53507.1_2589_mod3_ala                 VEIVE-DLIALLDRPSGWSAGLVSAVPSAFSTLLAAGALDASIGQVVLAGEALSSALVDD
Q83VS1_A5_10__ala                        INVVK-NVLEL--QHGEHDIGLVNTVPSALKALLEINGLPESVHTVNVAGEALKRSLVEN
BGC0000439_AHH53507.1_2589_mod3_ala      VEIVE-DLIALLDRPSGWSAGLVSAVPSAFSTLLAAGALDASIGQVVLAGEALSSALVDD
Q50E73_A3_8__ala                         VEIVR-NLLALVDRPGRWSASLVSGVPSAFAQLLEAGLDRADVGMIALAGEALSARDVRR
Q83VS0_A2_12__ala                        IEVVK-NVLEL--QHGEHDIGLINTVPSALKALLEVNGLPESVHTVNVAGEALKQSLVES
Q83VS1_A5_ala                            INVVK-NVLEL--QHGEHDIGLVNTVPSALKALLEINGLPESVHTVNVAGEALKRSLVEN
Q83VS1_A1_ala                            IEVVK-NVLEL--QHGEHDIGLINTVPSALKALLEVNGLPESVHTVNVAGEALKQSLVES
                                         : :.. : : *       .  *:. *** :  *   .        : :***.*    *  

Q83VS0_A3_13__ala                        LFENTGVQRLCNLYGPSETTTYS-SWVAMDREDGFA----AHIGKPVGNTQFYLLDEQQQ
Q83VS0_A7_17__ala                        LFENTGVQRLCNLYGPSETTTYS-SWVAMDREDGFA----AHIGKPVGNTQFYLLDEQQQ
BGC0000414_BAO84861.1_508_mod1_ala       LHNHPHIHTINNLYGPTEDTTYS-THAT-TTPNDPR----TPIGHPLPHTHAHILDHNLN
Q83VS1_A1_6__ala                         LFENTGVQRLCNLYGPSETTTYS-SWVAMDREHGFA----AHIGKPVGNTQFYLLDEQQQ
Q83VS0/81321400_A9_19__ala               LFENTGVQRLCNLYGPSETTTYS-SWVAMDRDDGFA----AHIGKPVGNTQFYLLDEQQQ
AHH53507.1_2589_mod3_ala                 IHRRLPATRVANVYGPTEATVYA-ARYS-DVPHGPAEWPQVPIGRGLPNTRLYVLDRSLA
Q83VS1_A5_10__ala                        LFEKTGVQRLCNLYGPSETTTYS-SWVAMDREDGFA----AHIGRPVGNTRFYLLDEQQQ
BGC0000439_AHH53507.1_2589_mod3_ala      IHRRLPATRVANVYGPTEATVYA-ARYS-DVPHGPAEWPQVPIGRGLPNTRLYVLDRSLA
Q50E73_A3_8__ala                         VRAVLPGARVANFYGPTEATVYATAWYG-DTPMDAA----APMGRPLRNTCVYVLDDGLR
Q83VS0_A2_12__ala                        LFENTGVQRLCNLYGPSETTTYS-SWVAMDREHGFA----AHIGKPVGNTQFYLLDEQQQ
Q83VS1_A5_ala                            LFEKTGVQRLCNLYGPSETTTYS-SWVAMDREDGFA----AHIGRPVGNTRFYLLDEQQQ
Q83VS1_A1_ala                            LFENTGVQRLCNLYGPSETTTYS-SWVAMDREHGFA----AHIGKPVGNTQFYLLDEQQQ
                                         :        : *.***:* *.*: :        .      . :*: : :*  ::**    

Q83VS0_A3_13__ala                        PVPLGVAGEIYIGGAGVARGYLNRDDLTAERFVKDPFSSQPAARMYRTGDLGRYLPDGNI
Q83VS0_A7_17__ala                        PVPLGVAGEIYIGGAGVARGYLNRDDLTAERFVKDPFSSQPAARMYRTGDLGRYLPDGNI
BGC0000414_BAO84861.1_508_mod1_ala       PVPTGTIGELYLTSHRTTRGYHNHPRQTAEHYLPNPHN--PHTRLYRTGDLARWRPDGQL
Q83VS1_A1_6__ala                         PVPLGVAGEIYIGGAGVARGYLNRDDLTAERFLKDPFSQQSAARMYRTGDLGRYLPDGNI
Q83VS0/81321400_A9_19__ala               PVPLGVAGEIYIGGAGVARGYLNRDDLTAERFVKDPFSPQPAARMYRTGDLGRYLPDGNI
AHH53507.1_2589_mod3_ala                 PVPAGVAGELYLAGAGLARGYLGRPGLSAERFVACPFG-EPGTRMYRTGDLARWLPDGNL
Q83VS1_A5_10__ala                        LVPRGVPGEIYIGGAGVARGYLNRDDLTAERFLTDPFSLTPGARMYRTGDLGRYLPDGNI
BGC0000439_AHH53507.1_2589_mod3_ala      PVPAGVAGELYLAGAGLARGYLGRPGLSAERFVACPFG-EPGTRMYRTGDLARWLPDGNL
Q50E73_A3_8__ala                         VVPVGVVGELYVAGVGLARGYLGRVGLTAERFVACPFG-ARGERMYRTGDLVRWRVDGTL
Q83VS0_A2_12__ala                        PVPLGVAGEIYIGGAGVARGYLNRDDLTAERFLKDPFSQNPAARMYRTGDLGRYLPDGNI
Q83VS1_A5_ala                            LVPRGVPGEIYIGGAGVARGYLNRDDLTAERFLTDPFSLTPGARMYRTGDLGRYLPDGNI
Q83VS1_A1_ala                            PVPLGVAGEIYIGGAGVARGYLNRDDLTAERFLKDPFSQQSAARMYRTGDLGRYLPDGNI
                                          ** *. **:*: .   :*** .:   :**:::  *..     *:****** *:  ** :

Q83VS0_A3_13__ala                        EYLGRNDDQVKIRGFRIELGEIDARLTKHPAVHEAVVTAREDIPGDKRLVA
Q83VS0_A7_17__ala                        EYLGRNDDQVKIRGFRIELGEIDARLAKHPAVHEAVVTAREDIPGDKRLVA
BGC0000414_BAO84861.1_508_mod1_ala       DYHGRTDNQIKINGHRIEPAEIETTLLTHPHVQETTITTHT-TPHTTQLIA
Q83VS1_A1_6__ala                         EYLGRNDDQVKIRGFRIELGEIDARLARHPAIHEAVVAAREDVPGDKRLVA
Q83VS0/81321400_A9_19__ala               EYLGRNDDQVKIRGFRIELGEIDARLTRHPAIHEAVVAAREDVPGDKRLVA
AHH53507.1_2589_mod3_ala                 VYVGRIDDQVKVRGFRIEPGEIEGALTDVPGVARAAVVARADSGADRRLVA
Q83VS1_A5_10__ala                        EYLGRNDDQVKIRGFRIELGEIDACLAKHPAVHEAVVMAREDVPGEIRLVA
BGC0000439_AHH53507.1_2589_mod3_ala      VYVGRIDDQVKVRGFRIEPGEIEGALTDVPGVARAAVVARADSGADRRLVA
Q50E73_A3_8__ala                         EFVGRADDQVKVRGFRVELGEVEGAVAAHPDVVRAVVVVREDRPGDHRLVA
Q83VS0_A2_12__ala                        EYLGRNDDQVKIRGFRIELGEIDARLAKHPAVHEAVVTAREDIPGDKRLVA
Q83VS1_A5_ala                            EYLGRNDDQVKIRGFRIELGEIDACLAKHPAVHEAVVMAREDVPGEIRLVA
Q83VS1_A1_ala                            EYLGRNDDQVKIRGFRIELGEIDARLARHPAIHEAVVAAREDVPGDKRLVA
                                          : ** *:*:*:.*.*:* .*::  :   * : .:.: .:       :*:*
