CLUSTAL W multiple sequence alignment


Q01886v2_A2_ala                          PATSRMGALQNISTQMGTEFKIVELEPEFIRSLPLPPKPNHQPMVGLNDDLYVVFTSGST
BGC0001166_AGQ43600.1_1838_mod2_ala      PVTRSIGALQNISTEMGAGLKIIRIEPEFIQGLPPVPRLAHQDMAGLDDDLYVVFTSGST
Q01886v1_A2_ala                          PATSRMGALQNISTQMGTEFKIVELEPEFIRSLPLPPKPNHQPMVGLNDDLYVVFTSGST
                                         *.*  :********:**: :**:.:*****:.**  *:  ** *.**:************

Q01886v2_A2_ala                          GVPKGAVATHQAYATGIYEHAVACGMTSLGAPPRSLQFASYSFDASIGDIFTTLAVGGCL
BGC0001166_AGQ43600.1_1838_mod2_ala      GDPKGAVATHRAFATGIYEHAMACGMTSVGAPPRSLQFASYSFDASIGDIFTTFVASGCL
Q01886v1_A2_ala                          GVPKGAVATHQAYATGIYEHAVACGMTSLGAPPRSLQFASYSFDASIGDIFTTLAVGGCL
                                         * ********:*:********:******:************************:...***

Q01886v2_A2_ala                          CIPREEDRNPAGITTFINRYGVTWAGITPSLALHLDPDAVPTLKALCVAGEPLSMSVVTV
BGC0001166_AGQ43600.1_1838_mod2_ala      CIPREEDRNPVGITAFINRCGVTWAGITPSFVSHLEPDAVPTLKALCVAGEPLSMSVVTA
Q01886v1_A2_ala                          CIPREEDRNPAGITTFINRYGVTWAGITPSLALHLDPDAVPTLKALCVAGEPLSMSVVTV
                                         **********.***:**** **********:. **:***********************.

Q01886v2_A2_ala                          WSKRLNLINMYGPTEATVACIANQVTCTTTTVSDIGRGYRATTWVVQPDNHNSLVPIGAV
BGC0001166_AGQ43600.1_1838_mod2_ala      WSNRLNLINMYGPTEATVACIANRVLCTTTTVGDIGRGYRAATWVVQPDNHNSLVPIGAV
Q01886v1_A2_ala                          WSKRLNLINMYGPTEATVACIANQVTCTTTTVSDIGRGYRATTWVVQPDNHNSLVPIGAV
                                         **:********************:* ******.********:******************

Q01886v2_A2_ala                          GELIIEGSILCRGYLNDPERTAEVFIRSPSWLHDLRPNSTLYKTGDLVRYSADGKIIFIG
BGC0001166_AGQ43600.1_1838_mod2_ala      GELIIEGSILCRGYLNDPERTAEVFIRSPSWLHDLRPNSTLYKTGDLVRYSADGKIIFIG
Q01886v1_A2_ala                          GELIIEGSILCRGYLNDPERTAEVFIRSPSWLHDLRPNSTLYKTGDLVRYSADGKIIFIG
                                         ************************************************************

Q01886v2_A2_ala                          RKDTQVKMNGQRFELGEVEHALQLQLDPSDGPIIVDLLKRTQSGEPDLLIA
BGC0001166_AGQ43600.1_1838_mod2_ala      RKDTQVKMNGQRFELGEVEHALQLQLDPSDGPIIVDLLKRTQSGEPDLLIA
Q01886v1_A2_ala                          RKDTQVKMNGQRFELGEVEHALQLQLDPSDGPIIVDLLKRTQSGEPDLLIA
                                         ***************************************************
