CLUSTAL W multiple sequence alignment


Q93I55_A2_asn                            ---LMQQDVRKQLAYEGVTVLL---DDESSYHQDGSDLAPINDVSHLAYVIYTSGSTGRP
Q70JZ8_A1_asn                            ---LTQRSLLDQLPYDGDVVLL---DEENSYHEEHSNLESDSDAHDLAYMIYTSGSTGNP
Q70JZ9_A2_asn                            ---LMQRDVRKQLAYEGVTVLL---DDEGSYHQDGSDLAPINDASHLAYVIYTSGSTGRP
Q93I54_A1_asn                            ---LTQSHLQKQLELAGTMVFL---DQESSYHEDGSYLEPISSTKDLAYVIYTSGSTGKP
Q9R9I9_A2_asn                            ---LTQSHLQQRLAHEGTIVLL---DDENSYHKERSNLERISNIKDLAYVIYTSGSTGKP
Q6YK41_A1_asn                            ---LTQRSLLDQLPYDGDIVLL---DEENSYHEDHSNLESDSDAHDLAYMIYTSGSTGNP
BGC0001125_AIW82277.1_525_mod1_asn       ---LTQSHLLDILPEEVNRILCLDSDWQAIAHQSTDNVFSQVQPQNLAYIIYTSGSTGEP
BGC0001019_AHB82069.1_1590_mod1_asn      --VTVRSHASAIPAATAQRIFV---DDPSDVGSIAAEPGAGVLPGNLAYLMYTSGSTGRP
Q6YK40_A2_asn                            ---LMQRDVRKQLAYEGVTVLL---DDESSYHQDGSDLAPINDVSHLAYVIYTSGSTGRP
O33743_A1_5__asn                         ---LTQSHLQPNIRFAGSVLYL---DDRSLYEGGSTSFAPESKPDDLAYMIYTSGSTGNP
BGC0000335_AID65222.1_2687_mod1_asn      ARHLNHPALADVKALDVAATLALP-------VEARARTGSAAAPGSLAYVIYTSGSTGMP
Q93I56_A1_asn                            ---LTQRSLLDQLPYDGDVVLL---DEENSYHEEHSNFESDSDAHDLAYMIYTSGSTGNP
Q9R9J0_A2_asn                            ---LMPRDVRQQITYEGVVILL---DEESSYHEEAFNLEPLSNANHLAYVIYTSGSTGKP
O68008_A5_12__asn                        ---LADHKQDLGTLHQEAVELT---GDFSSYPAD--NLEPAGNADSLAYIIYTSGSTGKP
Q70C44_A1_asn                            -GRLDELEL-------GAMTAV---DVCGTLDGDEANLDLPCDPAQPVYCIYTSGSTGSP
Q9R9J1_A1_asn                            ---LAQLDLHKHLTFDADVVLL---DEESSYHEDRSNLEPTCGANDLAYMIYTSGSTGNP
Q9FB27_A1_asn                            ----------------GVTPVALDADRRRIAAHPAGPTGIATTPDAPAYVVYTSGTTGKP
                                                                                        .* :****:** *

Q93I55_A2_asn                            KGVLIEHGGLTNYIWWAKEVYVKG-EKANFPLYSSISFDLTVTSIFTPLVTGNAIIVYD-
Q70JZ8_A1_asn                            KGVLIEHQGLADYIWWAKEVYVRG-EKTNFPLYSSISFDLTVTSIFTPLVTGNTIIVFD-
Q70JZ9_A2_asn                            KGVLIEHRGLTNYIWWAKEVYVKG-EKANFPLYSSISFDLTVTSIFTPLVTGNAIIVYD-
Q93I54_A1_asn                            KGVAIEHQGLTNYIWWARRVYVKG-EKTNFPLYSSIAFDLTITSVFTPLITGNAIIVYG-
Q9R9I9_A2_asn                            KGVLIEHQGLTNYIWWADRVYVKG-EKTTFPLYSSIAFDLTVTSIFTPLISGNAIIVYG-
Q6YK41_A1_asn                            KGVLIEHQGLANYIWWAKEVYVRG-EKTNFPLYSSISFDLTVTSIFTPLVTGNTIIVFD-
BGC0001125_AIW82277.1_525_mod1_asn       KGTMIRHQGVVNYLSWCTQAYAVA-DGCGAPVQSSFAFDATITSIFSPLMVGGQVVLLP-
BGC0001019_AHB82069.1_1590_mod1_asn      KGVMISHEGFADYIRWCLEVYPVT-HGEGTPLHASIAFDATLTSIFPALCAGRTVFVVP-
Q6YK40_A2_asn                            KGVLIEHGGLTNYIWWAKKVYVKG-EKANFPLYPSISFDLTVTSNFTPLVTGNAIIVYD-
O33743_A1_5__asn                         KGAMITHQGLVNYIWWANKVYVQG-EAVDFPLYSSISFDLTVTSIFTPLLSGNTIHVYR-
BGC0000335_AID65222.1_2687_mod1_asn      KGVAITHENLTSYVEWANGHYFADRDAGNFGLYTSLAFDMSVTPVFCSLTRGKTLVLPPP
Q93I56_A1_asn                            KGVLIEHQGLADYIWWAKEVYVRG-EKTNFPLYSSISFDLTVTSIFTPLVTGNTIIVFD-
Q9R9J0_A2_asn                            KGVLIEHRGLSNYIWWAKEVYVKN-EKTNFPLYSSISFDLTVTSIFTPLVTGNTIIVYD-
O68008_A5_12__asn                        KGVMIRQRGLVNYITWADRVYVQG-EQLDFALYSSIAFDLTVTSIFTPLISGNRVIVYR-
Q70C44_A1_asn                            KGVLVRHSGLANYVAWAKRQYVTA-DTTSFAFYSSLSFDLTVTSIYVPLVAGLCVHVYP-
Q9R9J1_A1_asn                            KGVLIEHRGLANYIEWAKEVYVND-EKTNFPLYSSISFDLTVTSIFTPLVTGNTIIVFD-
Q9FB27_A1_asn                            NGVRVPHRGLTNYLTWCTGAYGLD-GGTGTLVHTSISFDLTLTTLFGPLLAGGQVVMLS-
                                         :*. : : .. .*: *.   *          . .*::** ::*. : .*  *  : :   

Q93I55_A2_asn                            -GEDKTALLESIVRDPRVDIIKLTPAHLQVLKEMNIADQM--AVRRMIVGGENLSTRLAR
Q70JZ8_A1_asn                            -GEDKSAVLSEIMRDSRIDMIKLTPAHLHVIKEMNIAGGT--AIRKMIVGGENLSTRLAK
Q70JZ9_A2_asn                            -GEDKTALLESIVRDPRVDIIKLTPAHLQVLKEMNIADQT--AVRRMIVGGENLSTRLAR
Q93I54_A1_asn                            -GENSTALLDSIIQDSRADIIKLTPAHLQLLKEINIPAEC--TIRKFIVGGDNLSTRLAR
Q9R9I9_A2_asn                            -DKDRTTLLSSIIEDSRVDIIKLTPAHLQLLKEMNISPEC--TIRKMIVGGDNLSTRLAQ
Q6YK41_A1_asn                            -GEDKSAVLSEIMRDSRIDMIKLTPAHLHVIKEMNIAGGT--AIRKMIVGGENLSTRLAK
BGC0001125_AIW82277.1_525_mod1_asn       EKQEIEALCDVLRSRRRFSLVKLTPAHLELLNQLLLPEELPESTQALVIGGEAL---LGK
BGC0001019_AHB82069.1_1590_mod1_asn      DEHEIEGLVRALRGRRRYGFVKLTPSHLAMLEDLREGAALHESTGAFILGGEAL-TEAAL
Q6YK40_A2_asn                            -GEDKTALLESIVRDPRVDIIKLTPAHLQVLKEMNIADQT--AVRRMIVGGENLSTRLAR
O33743_A1_5__asn                         -GADKVQVILDIIKDNKVGIIKLTPTHLKLIEHID-GKAS--SIRRFIVGGENLPTKLAK
BGC0000335_AID65222.1_2687_mod1_asn      ELELAEALRWGVRPGSPVDALKLTPSHVTVLRELGLSSS---PVRLAVLGGEAL---TAE
Q93I56_A1_asn                            -GEDKSAVLSEIMRDSRIDMIKLTPAHLHVIKEMNIAGDT--AIRKMIVGGENLSTRLAK
Q9R9J0_A2_asn                            -GEDKTALLSSIVQDQRVDIIKLTPAHLHVLKAMNIANKI--AIRKMIVGGENLSTQLAQ
O68008_A5_12__asn                        HSEDGEPLIRKVFRDQKAGIVKLTPSHLSLVKDMD-ASGS--SIKRLIVGGEDLKTELAK
Q70C44_A1_asn                            EQGDDVPVINRVLDDNQVDVIKLTPSHMLMLRNAALATS---RLKTLIVGGEDLKAAVAY
Q9R9J1_A1_asn                            -GEDKSAVLSTIMQDPRIDIIKLTPAHLHVLKEMKIADGT--TIRKMIVGGENLSTRLAQ
Q9FB27_A1_asn                            ETAGVTGLIAALRSRRDLTLVKLTPTHLDVVNQLLTPDELRGAVRTLVVGGEAV---RAE
                                                :   :        :****:*: ::.               ::**: :    . 

Q93I55_A2_asn                            SIH--EQFEGRIEICNEYGPTETVVGCMIYRYDPAKDRRESVPIGTAAANTSIYVLDENM
Q70JZ8_A1_asn                            SVS--EQFKGRLDIFNEYGPTEAVVGCMIYQFDAERDKREFVPIGTPAANTDIYVADASR
Q70JZ9_A2_asn                            SIH--EQFEGRIEICNEYGPTETVVGCMIYRYDAAKDRRESVPIGTAAANTSIYVLDENM
Q93I54_A1_asn                            SIS--GKFGGKIEIFNEYGPTETVVGCMIYSFDPQNDRRESVPIGTAADNMNIFVLDKSM
Q9R9I9_A2_asn                            NIS--EQFQDQIEIFNEYGPTETVVGCMIYLYDPKKDRQESVPIGTAAANMNIYLLDTGM
Q6YK41_A1_asn                            SVS--EQFKGRLDIFNEYGPTEAVVGCMIYHFDAERDKREFVPIGTPAANTDIYVADASR
BGC0001125_AIW82277.1_525_mod1_asn       TLQFWQQYAPNIRLINEYGPTETVVGCCIYEVTPETSLTEGILIGRPIANTQLYILDQFW
BGC0001019_AHB82069.1_1590_mod1_asn      APW--KERAPHLRIFNEYGPTEAVVGCALNEGWGALPLSGGVSIGRPAADTQLYVLDEDM
Q6YK40_A2_asn                            SIH--EQFEGRIEICNEYGPTETVVGCMIYRYDAAKDRRESVPIGTAAANTSIYVLDENM
O33743_A1_5__asn                         QIY--DHFGENVQIFNEYGPTETVVGCMIYLYDPQTTTQESVPIGVPADNVQLYLLDASM
BGC0000335_AID65222.1_2687_mod1_asn      HVAVLHRLNPDMAVYNEYGPTEITVGCTVERVEPGAAR---VGIGQPIANAQAYVLDAEG
Q93I56_A1_asn                            SVS--EQFKGRLDIFNEYGPTEAVVGCMIYHFDAVRDKREFVPIGTPAANTDIYVADASR
Q9R9J0_A2_asn                            SIH--EQFDGQIEICNEYGPTETVVGCMLYRYDAVKDRRESVPIGTAAANTSIYVLDEDM
O68008_A5_12__asn                        EIT--ERFHHNIEIYNEYGPTETVVGCMIYQYDAGWDRQVSVPIGKPASNVQLYILDERQ
Q70C44_A1_asn                            DIH--QRFRRDVAIYNEYGPTETVVGCAIHRYDPATEREGSVPIGVPIDHTSLHLLDERL
Q9R9J1_A1_asn                            SVS--EQFKGQLDIFNEYGPTEAVVGCMIYRYDTKRDRREFVPIGSPAANTSIYVLDASM
Q9FB27_A1_asn                            SLE--PFRASGTRVVNEYGPSETVVGSVAHVVDAATPRTGPVPIGRPIANTTVHLLDQRR
                                                      : *****:* .**.              : ** .  .   .: *   

Q93I55_A2_asn                            KPAPIGVPGEIYISGAGVARGYLNRPELTAEKFVDDLFE-------PGAKMYKTGDLAKW
Q70JZ8_A1_asn                            NLVPIGVIGEIYISGPGVARGYWNRPDLTAEKFVENPYV-------PGAKMYKSGDLAKR
Q70JZ9_A2_asn                            KPAPIGVPGEIYISGAGVARGYLNRPELTAEKFVDDPFE-------PGAKMYKTGDLAKW
Q93I54_A1_asn                            KPVPAGVPGEIYISGDGIARGYLNRAELTAERFLQHPFV-------PEVKMYRTGDLARR
Q9R9I9_A2_asn                            KPVPIGVPGEMYISGAGVARGYLNRPDLTAEKFVEHPFA-------AGERMYKTGDAARW
Q6YK41_A1_asn                            NLVPFGVIGEIYISGPGVARGYWNRPDLTAEKFVENPYV-------PGAKMYKSGDLAKR
BGC0001125_AIW82277.1_525_mod1_asn       QPVPIGVRGELYIGGAGVARGYLNRPELTAERFIRNPFSN-----DSEARLYKTGDLARY
BGC0001019_AHB82069.1_1590_mod1_asn      RLLPPGVAGELYIGGSCLARGYNGAPAQTAQRFVPNPFADRSPGAAPGSRLYRTGDRARV
Q6YK40_A2_asn                            KPAPIGVPGEIYISGAGVARGYLNRPELTAEKFVDDPFE-------PGAKMYKTGDLAKW
O33743_A1_5__asn                         QPVPVGSLGEMYIAGDGVAKGYFNRPELTKEKFIDNPFR-------PGTKMYRTGDLAKW
BGC0000335_AID65222.1_2687_mod1_asn      ALVRPGVVGELFIGGPGVARGYLGQPAQTSARFIPSSLA------STGGRLYRTGDQARW
Q93I56_A1_asn                            NLVPIGVIGEIYISGPGVARGYWNRPDLTEEKFVENPYV-------PGAKMYKSGDLAKR
Q9R9J0_A2_asn                            KPVPIGVPGEMYISGAGVARGYLNRPELTAEKFVENPFV-------TGERMYKTGDLAKW
O68008_A5_12__asn                        EVQPVGIAGELYISGDGVAKGYLNKPELTSEKFLPNPFL-------PGERMYRTGDLAKM
Q70C44_A1_asn                            QPVAPGEVGQIHIGGAGVAIGYVNKPEITDAQFIDNPFE-------GSGRLYASGDLGRM
Q9R9J1_A1_asn                            NLVPVGVPGEMYIGGAGVARGYWNRPDLTAEKFVHNPFA-------PGTIMYKTGDLAKR
Q9FB27_A1_asn                            RPVPDGVVGELWIGGAGVADGYLGRPELTGERFLPSDYP---P---DGGRVYRTGDLARR
                                              *  *:: *.*  :* ** . .  *  :*:                :* :** .: 

Q93I55_A2_asn                            LADGNIEYAGRIDEQVKIRGYRIELGEIEAALLQEEAIKEAV----VTAREDVH------
Q70JZ8_A1_asn                            LKDGNLVYIGRVDEQVKIRGHRIELGEIEAAMHNAEAVQKAA----VTVKEEED------
Q70JZ9_A2_asn                            LADGNIEYAGRIDEQVKIRGYRIELGEIEAALLQEEAIKEAV----VTAREDVH------
Q93I54_A1_asn                            LPDGNIEYLGRIDHQVKIRGYRIEIGEVESAFFQIPPIQEAL----VTAQET-N------
Q9R9I9_A2_asn                            MPDGHMEYLGRIDHQVKVRGYRIELGEVEAALLLVESVKEAV----VIAVEE-E------
Q6YK41_A1_asn                            LKDGNLLYIGRVDEQVKIRGHRIELGEIEAAMHNAEAVQKAA----VTVKEEED------
BGC0001125_AIW82277.1_525_mod1_asn       RLDGNIEYLGRMDNQVKLRGFRIELGEIEAAIAKYPEVRETV----VIIREDIP------
BGC0001019_AHB82069.1_1590_mod1_asn      LPDGTLEFLGRLDDQVKIRGFRVELGEIAAVLGQHPRVHSAV----AILRGE--------
Q6YK40_A2_asn                            LADGNIEYAGRIDEQVKIRGYRIKLGEIEAALLQKKAIKEAV----VTAREDVH------
O33743_A1_5__asn                         LPDGNMEYAGRMDYQVKIRGHRIEMGEIETRLTQHEAVKEAV----VIVEKDES------
BGC0000335_AID65222.1_2687_mod1_asn      LPDGRLEYLGRGDGQVKLRGHRIELGEIESALLKHERIRATT----VVLHASPE------
Q93I56_A1_asn                            LKDGNLVYIGRVDEQVKIRGHRIELGEIEAAMHNAEAVQKAA----VTVKEEED------
Q9R9J0_A2_asn                            LPDGNIEYLGRMDEQVKIRGFRIELGEIETAMLQAEEIKEAV----VTAREDVH------
O68008_A5_12__asn                        RPDGHIEYLGRIDHQVKIRGYRIELGEIEHQLLRHSDIKEAA----VAAKTDQN------
Q70C44_A1_asn                            RADGKLEFLGRKDSQIKLRGYRIELGEIENVLLGHAALRECIVDTTVAPRRDYD------
Q9R9J1_A1_asn                            LRDGNLIYLGRIDEQVKIRGHRIELGEVEAAMHKVEAVQKAV----VLAREEED------
Q9FB27_A1_asn                            RADGTLEYLGRTDAQVKIRGVRVEPAETEAVLASHPGVGQAV----VVARLDEDPGRSSP
                                           ** : : ** * *:*:** *:: .*    :     :        .             

Q93I55_A2_asn                            --GFKQLCA
Q70JZ8_A1_asn                            --GLKQLCA
Q70JZ9_A2_asn                            --GFKQLCA
Q93I54_A1_asn                            --GETSLCA
Q9R9I9_A2_asn                            --GSNQLCA
Q6YK41_A1_asn                            --GLKQLCA
BGC0001125_AIW82277.1_525_mod1_asn       --SDKRLVA
BGC0001019_AHB82069.1_1590_mod1_asn      -----QLVG
Q6YK40_A2_asn                            --RFKQLCA
O33743_A1_5__asn                         --GQNVLYA
BGC0000335_AID65222.1_2687_mod1_asn      --GQRALVA
Q93I56_A1_asn                            --GLKQLCA
Q9R9J0_A2_asn                            --GLKQLCG
O68008_A5_12__asn                        --NDQVLCA
Q70C44_A1_asn                            --SKSLR--
Q9R9J1_A1_asn                            --GLQQLCA
Q9FB27_A1_asn                            LAGELTLTG
                                                  
