CLUSTAL W multiple sequence alignment


Q9Z4X6_A5_asp                            LTLTAPIPPASYDSRPTSEITDVERRSPWSARHAAYMIYTSGSTGRPKGVVIEHHALATY
Q9Z4X6_A4_asp                            LTLTEPVPVERYTGHSVTAVTDEERRSPWSARHAAYMIYTSGSTGRPKGVVIEHHALATY
Q9Z4X5_A1_7__asp                         LTLREPVPAAAYGHRPTDDVTDAERRTPWSALHAAYMIYTSGSTGRPKGVVIEHHALATY
Q9Z4X5_A1_asp                            LTLREPVPAAAYGHRPTDDVTDAERRTPWSALHAAYMIYTSGSTGRPKGVVIEHHALATY
                                         ***  *:*   *  :..  :** ***:**** ****************************

Q9Z4X6_A5_asp                            LHRARNTYTAMTGVTVLHSPLAFDLTITALWTPLTAGGTVHLTSLEEAEVQPSLIKATPS
Q9Z4X6_A4_asp                            LHRARNTYTAMTGVTVLHSPLAFDLTITALWTPLTSGGTVHLTSLEESDTQPSLIKATPS
Q9Z4X5_A1_7__asp                         LHRARNTYTAMTGVTVLHSPLAFDLTITALWTPLTAGGTVHLTSLEEAEVQPSLIKATPS
Q9Z4X5_A1_asp                            LHRARNTYTAMTGVTVLHSPLAFDLTITALWTPLTAGGTVHLTSLEEAEVQPSLIKATPS
                                         ***********************************:***********::.**********

Q9Z4X6_A5_asp                            HLPLLTTLPETASPSHTLILGGEALHTDHLATWRTQHPGAQIINAYGPTESTVNITDHHV
Q9Z4X6_A4_asp                            HLPLLTTLPETASPSHTLILGGEALHTDHLVTWRTQHPGVQIINAYGPTESTVNITDHHV
Q9Z4X5_A1_7__asp                         HLPLLTNLAATASPSHTLILGGEALHTDQLTDWRTQHPGAQIINAYGPTESTVNITDHRL
Q9Z4X5_A1_asp                            HLPLLTNLAATASPSHTLILGGEALHTDQLTDWRTQHPGAQIINAYGPTESTVNITDHRL
                                         ******.*. ******************:*. *******.******************::

Q9Z4X6_A5_asp                            SEDTPDGPVPIGRPFANTQVYVLDSALRPVAPGVTGELYLAGEQLARGYLGRPALTAERF
Q9Z4X6_A4_asp                            GEDTPDGPVPIGRPFANTQVYVLDSALRPVAPGVTGELYLAGEQLARGYLGRPALTAERF
Q9Z4X5_A1_7__asp                         -DGTEEGPVPIGRPFANTQVYVLDSALRPVAPGTTGELYLAGEQLARGYLGRPALTAERF
Q9Z4X5_A1_asp                            -DGTEEGPVPIGRPFANTQVYVLDSALRPVAPGTTGELYLAGEQLARGYLGRPALTAERF
                                          :.* :***************************.**************************

Q9Z4X6_A5_asp                            TANPHSSTPGARMYRTGDLAHWNHDGHLTYDGRADHQIKLRGHRIEPGEIETTLTAQTGI
Q9Z4X6_A4_asp                            TANPHSSTPGARMYRTGDLAHWNHHGHLTYDGRADHQIKLRGHRIEPGEIEATLTAQTGI
Q9Z4X5_A1_7__asp                         TANPHSSVPGARMYRTGDLAHWNHHGHLTYDGRADHQIKLRGHRIEPGEIETTLTAQTGI
Q9Z4X5_A1_asp                            TANPHSSVPGARMYRTGDLAHWNHHGHLTYDGRADHQIKLRGHRIEPGEIETTLTAQTGI
                                         *******.****************.**************************:********

Q9Z4X6_A5_asp                            TQTTVQLREDTPGDQRLVA
Q9Z4X6_A4_asp                            TQATVQLREDQPGDQRLVA
Q9Z4X5_A1_7__asp                         TQATVQLREDQPGDQRLVA
Q9Z4X5_A1_asp                            TQATVQLREDQPGDQRLVA
                                         **:******* ********
