CLUSTAL W multiple sequence alignment


Q04747_A2_5__asp                         VNERNMTA--IGQYEGIIVSLDDGKWRNESKERPSSISGSRNLAYVIYTSGTTGKPKGVQ
Q70KJ6_A2_5__asp                         VNERNMTA--AAVYKGNTVVMEDGEWQNESADRLETEPGFDQLAYIIYTSGTTGKPKGVQ
O68008_A4_11__asp                        LVKGSVKE--NVAFAGEIVNVADGLIDAKVASNLSASGSADQNAYIIYTSGSTGKPKGVF
O69246_A2_5__asp                         LTEPSHQADLADWYTGRLIDVRKDTLM-ASNKRPHPTTDGASLAYIIYTSGTTGRPKGVQ
                                         : : .        : *  : : ..       ..  .  .  . **:*****:**:**** 

Q04747_A2_5__asp                         IEHRNLTNYVSWFSEEAGLTENDKTVLLSSYAFDLGYTSMFPVLLGGGELHIVQKETYTA
Q70KJ6_A2_5__asp                         LEHRNLINYVTWFSREAGLTEADKSVLLSSYAFDLGYTAIFPILQAGGELHIVPKETYTA
O68008_A4_11__asp                        VRHGNVVNYTTWFMKEAGLTENDKAMLVSSYAFDLGYTSIFSALLSGSELHIARKECYTN
O69246_A2_5__asp                         LEHRNLANYVSWFISEAHLSASDKTMLLSSYAFDLGYTSFFPVLLAGGELHIVPKETYTE
                                         :.* *: **.:**  ** *:  **::*:**********::*. * .*.****. ** ** 

Q04747_A2_5__asp                         PDEIAHYIKEHGITYIKLTPSLFHTIVNTASFAKDANFESLRLIVLGGEKIIPTDVIAFR
Q70KJ6_A2_5__asp                         PDQLGEYIQKNGITYMKLTPSLFHMIVNTARFAAERRFSPLRLVVLGGEKIITSDVRKFH
O68008_A4_11__asp                        AHRALKYIKENGITYIKLTPSLFNIFVNDPGFSAEKPCATLRLVVLGGEMINTRDVETFY
O69246_A2_5__asp                         PEAFTHYIGEQGITYMKLTPSLFHTVVQPQSFALAKGLQSLRLIVLGGEKINPKDVERFH
                                         ..   .** ::****:*******: .*:   *:      .***:***** * . **  * 

Q04747_A2_5__asp                         KMYGHTEFINHYGPTEATIGAIAGRVDLYEPDAFAKRPTIGRPIANAGALVLNEALKLVP
Q70KJ6_A2_5__asp                         DVYAHTDFINHYGPTETTIGAIAGRINMERLDQYEQRPVIGRPIANTGALVLDGAMQLVP
O68008_A4_11__asp                        NQYPDHVVMNHYGPTETTIGSVFKVIDPEHLDSFKECPVIGTPIHNTNAYVLDENMKLLP
O69246_A2_5__asp                         SRYPDTRFINHYGPTETTIGAIAKPVEPDMIGQFAERPTIGRPISGAGALVLDASRRLVP
                                         . * .  .:*******:***::   ::    . : : *.** ** .:.* **:   :*:*

Q04747_A2_5__asp                         PGASGQLYITGQGLARGYLNRPQLTAERFVENPYSPGSLMYKTGDVVRRLSDGTLAFIGR
Q70KJ6_A2_5__asp                         PGASGELYIAGKGLARGYLHRPQLTAEKFLSNPFSPDSLMYKTGDVVRRLPDGTIEFIGR
O68008_A4_11__asp                        EGVYGELCIAGAGVTGGYVNRPDETKEKFIENPFAPHTKMYRTGDLARRLSDGNIELAGR
O69246_A2_5__asp                         AGAAGELYITGSGLARGYVNNRELTAAKFVENPYTPGTFMYRTGDLVRRLPNGEIEFLGR
                                          *. *:* *:* *:: **::. : *  :*:.**::* : **:***:.***.:* : : **

Q04747_A2_5__asp                         ADDQVKIRGYRIEPKEIETVMLSLSGIQEAVVLA-VSEGGLQELCA
Q70KJ6_A2_5__asp                         ADDQVKIRGYRIELKEVETVLLSVNGIQEAVVLA-VSEGGLPELCA
O68008_A4_11__asp                        IDTQVKVRGYRIEPEEIKNRLLAHDDIKEAFIAAREDHKGAKQLCA
O69246_A2_5__asp                         TDDQVKIRGYRIELKEIEEAFNELDDIERAIVLSFTTDSGLDELCA
                                          * ***:****** :*::  :   ..*:.*.: :   . *  :***
