CLUSTAL W multiple sequence alignment


Q70AZ7_A3_bht                            VCTARTRSVVPGDFAGAVLALDEPSAAGPQVSLPRVAARDGAYVIYTSGSTGVPKGVLVT
Q70AZ7_A3_6__bht                         VCTARTRSVVPGDFAGAVLALDEPSAAGPQVSLPRVAARDGAYVIYTSGSTGVPKGVLVT
Q8KLL5_A3_bht                            LCTKATRTAVPDGFAGVVVVLDERSAADPGAALPAVAVGDGAYVIYTSGSTGTPKGVQVT
BGC0000418_AHF20584.1_3410_mod3_bht      VCTAATRAVVPSTFDGEILMLDELPAADPAVVLPPVKATDAAYVIYTSGSTGVPKGVMVT
Q8KLL5_A3_6__bht                         LCTKATRTAVPDGFAGVVVVLDERSAADPGAALPAVAVGDGAYVIYTSGSTGTPKGVQVT
                                         :**  **:.**. * * :: *** .**.* . ** * . *.***********.**** **

Q70AZ7_A3_bht                            HAGLGNLASAQIERFGVTSSSRVLQFAALGFDAAISEVCMALLSGGSIVLADAEHMPPRV
Q70AZ7_A3_6__bht                         HAGLGNLASAQIERFGVTSSSRVLQFAALGFDAAISEVCMALLSGGSIVLADAEHMPPRV
Q8KLL5_A3_bht                            HAGLGNLAGAQIERFGVTSSSRVLQFASLGFDAAISELCMALLSGGTVVLADPDSMPPRV
BGC0000418_AHF20584.1_3410_mod3_bht      HSGLGNLATAHIERLGVTSSSRVLQLSAIGFDAIVSELYMSLLAGATLVLADAETMPPRV
Q8KLL5_A3_6__bht                         HAGLGNLAGAQIERFGVTSSSRVLQFASLGFDAAISELCMALLSGGTVVLADPDSMPPRV
                                         *:****** *:***:**********::::**** :**: *:**:*.::****.: *****

Q70AZ7_A3_bht                            SLGDAVRRWDITHVTVPPSVLAVEDDLPDDL-TLIVAGEACPPALVDRWSPGRRMINGYG
Q70AZ7_A3_6__bht                         SLGDAVRRWDITHVTVPPSVLAVEDDLPDDL-TLIVAGEACPPALVDRWSPGRRMINGYG
Q8KLL5_A3_bht                            SLGDAVRRWRITHVTVPPSVLAVEEDLPDSLETLVVAGEACPPALVDRWSGDRRMINGYG
BGC0000418_AHF20584.1_3410_mod3_bht      TLGDALRRWGITHLTVSPSVLAVEEDLPDTLRGVLTGGEVCTPALVDRWSPGRRFINAYG
Q8KLL5_A3_6__bht                         SLGDAVRRWRITHVTVPPSVLAVEEDLPDSLETLVVAGEACPPALVDRWSGDRRMINGYG
                                         :****:*** ***:**.*******:**** *  ::..**.*.******** .**:**.**

Q70AZ7_A3_bht                            PTETTVCATMSSPLSPGRGAVPIGGPIANMRTYVLDAFLQPVPPGMTGELYVTGVGLARG
Q70AZ7_A3_6__bht                         PTETTVCATMSSPLSPGRGAVPIGGPIANMRTYVLDAFLQPVPPGMTGELYVTGVGLARG
Q8KLL5_A3_bht                            PTETTVCVTMSAPLSPGRDAPPIGRPIANMRAYVLDAFLQPVPPGVAGELYVTGAGLARG
BGC0000418_AHF20584.1_3410_mod3_bht      PTETTICSTMSAPLSPGHEVVPLGGPIRNVKHYILDAYLQPVPPGVTGELYIAGAGLARG
Q8KLL5_A3_6__bht                         PTETTVCVTMSAPLSPGRDAPPIGRPIANMRAYVLDAFLQPVPPGVAGELYVTGAGLARG
                                         *****:* ***:*****: . *:* ** *:: *:***:*******::****::*.*****

Q70AZ7_A3_bht                            YLGRPGLTAERFVADPFSPGGRMYRTGDRARWTGDGELVFAGRVDAQVKVRGYRIEPGEI
Q70AZ7_A3_6__bht                         YLGRPGLTAERFVADPFSPGGRMYRTGDRARWTGDGELVFAGRVDAQVKVRGYRIEPGEI
Q8KLL5_A3_bht                            YLGRPGLTAERFVADPFSSGGRMYRTGDRARWTREGELVFVGRADAQVKVRGYRVEPGEI
BGC0000418_AHF20584.1_3410_mod3_bht      YLGRPGLTAERFVADPFTPGERMYRSGDRFRWDPDGELIFVGRVDAQVKVRGYRVEPAEI
Q8KLL5_A3_6__bht                         YLGRPGLTAERFVADPFSSGGRMYRTGDRARWTREGELVFVGRADAQVKVRGYRVEPGEI
                                         *****************:.* ****:*** **  :***:*.**.**********:**.**

Q70AZ7_A3_bht                            EAVLAEHPGVAQVVVVARQDGPGEKQLVA
Q70AZ7_A3_6__bht                         EAVLAEHPGVAQVVVVARQDGPGEKQLVA
Q8KLL5_A3_bht                            EAVLSDHPGAAQVVIVAREDGPGEKRLVA
BGC0000418_AHF20584.1_3410_mod3_bht      ENVLAEHPGVAQAAVAVHRDGPGDKRLVA
Q8KLL5_A3_6__bht                         EAVLSDHPGAAQVVIVAREDGPGEKRLVA
                                         * **::***.**..:..:.****:*:***
