CLUSTAL W multiple sequence alignment


Q6DNE7_A1_4__cys                         ----LTQTHLKQSLGWPEGIKCWSVDTEELA-EYDPNP-LEPVQ-----TSEDLAYVIYT
CCA29202.1_1497_mod2_cys                 SRAQLERDEIQA-LA---GRYQLLDLDALVS-SEAQAPLASSEQTLPDVHPDDVAYVIFT
Q5MD35_A1_cys                            ----VTEPRLAERLSWPGDVEVVVVADIARG-----VS--RPERR---GSASDLAYCIYT
Q9RFK9_A1_cys                            ----LTESHLAERLSWPASVRVVAIADTARG-----APPRLPAR-----AASDMAYCIYT
Q70P97_A1_cys                            ----LTEPRLAERLSWPEDVEVVVVADIARG-----AA--LPERR---GSVTDLAYCIYT
O68006_A2_cys                            SHDVYDKEHIE---------------------RFSKAP-VDRKV-----DLDDMAYVIFT
Q9KIZ9_A1_cys                            ----LTQPWLDGKLSWPPGIQRLLVSDAGVEGDGDQLP-MMPIQ-----TPSDLAYVIYT
Q9FB18_A2_cys                            ----LTERALLDTLAVPVGVTVLAVDDDAAL-DADGGP-LQSVQ-----NLTDLAYTIFT
Q8GAQ3_A2_4__cys                         ----VTQAALNASLGLPDHLHCLVVASQPQE-IID-TP-LEANV-----SSSDLAYVIFT
CCA29203.1_2085_mod2_cys                 SQAQYDDTEVRTQLG---GRYRLLVIDELLARADEEAP----AQPLPQVDADAVAYVIFT
                                                  :                           .               :** *:*

Q6DNE7_A1_4__cys                         SGSTGLPKGVMIDHRGAINTILDINQRFKVTPSDRVLALAALNFDLSVYDIFGVLGAGGA
CCA29202.1_1497_mod2_cys                 SGSTGKPKGVTISHRGAVNTIDAINSRFKVSSRDSVLALSELSFDLSVYDLFGVLAAGGN
Q5MD35_A1_cys                            SGSTGRPKGVMIEHRAAANTLLDINARFQVGPEDRIFALSSLGFDLSVYDIFGALAAGAA
Q9RFK9_A1_cys                            SGSTGRPKGVKIEHRAAANTILDINERFGVGPADRVFALSSLGFDLSVYDIFGSLAAGAA
Q70P97_A1_cys                            SGSTGRPKGVMIDHRSAANTVQDINSRFQVGPEDRVFALSSLGFDLSVYDIFGALAVGAA
O68006_A2_cys                            SGSTGKPKGVQITHVPQRNTILDINEKFNVTEQDNIMGISSLCFDLSVYDVFGALSSGAS
Q9KIZ9_A1_cys                            SGSTGLPKGVMIDHRGAVNTILDINERFEIGPGDRVLALSSLSFDLSVYDVFGILAAGGT
Q9FB18_A2_cys                            SGSTGEPKGVMIDHLGAANTLECVNRRFGTGPGDAVLAVSSPSFDLAVYDLFGVLAAGGT
Q8GAQ3_A2_4__cys                         SGSTGTPKGVMIDHRGAVNTIQDINQRFDVQPTDRMLAVSALNFDLSVYDIFGLLAAGGT
CCA29203.1_2085_mod2_cys                 SGSTGKPKGVTISHRGALNTIHAVNQRLAVSPTDKVLALSELSFDLSVYDLFGLLAAGGQ
                                         ***** **** * *    **:  :* ::     * ::.::   ***:***:** *. *. 

Q6DNE7_A1_4__cys                         IVMPPPKAAKDPACWRELIIAHEVTLWNSVPALMQMLVEHLLGTSATAVGDLRVVMLSGD
CCA29202.1_1497_mod2_cys                 IVFPIQAETKNPAHWLEFVEKHGITLWNTVPQLAGLLLDEASGSTGRLA-SLRLFLLSGD
Q5MD35_A1_cys                            LVLPETEATRDPARWLRLLRAHRVSVWNSVPTLMEMLVDVAETRGERLPDSLRLVMMSGD
Q9RFK9_A1_cys                            IVLPQPEVTRDPAHWLQVLRQQGVTIWNSVPTLMEMLVDQVEARGELLPETLRLVMLSGD
Q70P97_A1_cys                            FVLPESEATKDPASWLNLLRTHRVSVWNSVPTLMEMLVDVAETRGERLPDSLRLVMMSGD
O68006_A2_cys                            LVIIDDQ--RDVFSLKETAEKERITIWNSVPAIMGMTADVYPD--NELNHHLRLILLSGD
Q9KIZ9_A1_cys                            IVVPDASKLRDPAHWAALIEREKVTVWNSVPALMRMLVEHSEGRPDSLARSLRLSLLSGD
Q9FB18_A2_cys                            VVVPAHDRRRDPGHWAELIRRERVTLWNSVPALGTLLTEYAEALAPDALRTLRAVLLSGD
Q8GAQ3_A2_4__cys                         LVMPTPEAAKDPVHWVELMTTHQVTLWNTVPALMQMLVEYLSEHPDQVTEDLRLALLSGD
CCA29203.1_2085_mod2_cys                 VVFTPPRATKDPSAWLEAIEREQVTLWNTVPQLAGLLVDAMKHGGKTSS-SLRAFMLSGD
                                         .*.      ::          . :::**:** :  :  :            **  ::***

Q6DNE7_A1_4__cys                         WLPVDLPSKIQSLWS-NVQVMSLGGATEASIWSIGYPIEKVGSDWKSIPYGKPLLNQSFY
CCA29202.1_1497_mod2_cys                 WIPTSLPGRIRGQCP-NSLVMSLGGATEGSIWSIWYEIAQVDPSWSSIPYGTAMPNQGMY
Q5MD35_A1_cys                            WIPVTLPDRIRRLARGDIQIISLGGATEGSVWSILHPIGQVPPGARSIPYGRPMLNQRFH
Q9RFK9_A1_cys                            WIPVTLPDRIRRLSR-DIRVISLGGATEASIWSIIHPIGRVDPAARSIPYGRPMLNQRFY
Q70P97_A1_cys                            WIPVTLPDRIRRLARGDIQIISLGGATEGSVWSILHPIGQVEPTARSIPYGRPMLNQRFY
O68006_A2_cys                            WIPLQLPATIKKTFK-NAEVISLGGATEGSIWSIYYPIQKVEEDWKSIPYGKPLANQKIY
Q9KIZ9_A1_cys                            WIPVGLPGELQAIRP-GVSVISLGGATEASIWSIGYPVRNVDPSWASIPYGRPLRNQTFH
Q9FB18_A2_cys                            WIPLGLPDRIRALSAPGATVMSLGGATEASIWSVWYEIGKVHEAWSSIPYGTPMANQRLE
Q8GAQ3_A2_4__cys                         WIPLNLPTQIQSLWP-QGQVVSLGGATEASIWSVYYPITTVEPEWKSIPYGKPLVNQSLH
CCA29203.1_2085_mod2_cys                 WIPTRLPEQLRALAP-NAEVLSMGGATEGSIWSIWYPVETVPAEWTSIPYGVAMPNQKMY
                                         *:*  **  ::        ::*:*****.*:**: : :  *     ***** .: ** : 

Q6DNE7_A1_4__cys                         VLNELMEPRPVWVPGQLYIGGVGLAKGYWKNEHKTQASFITHPVTQEPLYKTGDLGRYLP
CCA29202.1_1497_mod2_cys                 VLDGQLQHCPVGVTGEIYIGGEGVALNYWRAPALSEARFIQHPHLG-RLYRTGDQGRWSR
Q5MD35_A1_cys                            VLDEALSPRPDHVPGELFIGGVGVARGYFGDEVRTAERFIVHPKTRERLYRTGDLGRFLP
Q9RFK9_A1_cys                            VLDEKLAPRPDHVPGDLYIGGVGLAQGYFRDEETTRARFFNHPRTGERLYRTGDLGRFLP
Q70P97_A1_cys                            VLDDALASRPDYVPGELFIGGVGVARGYFRDDVRTAERFIVHPKTNERLYRTGDLGRFLP
O68006_A2_cys                            VLNQNKQLCPVGVEGELYIGGAGVASGYIHDQEKTEHSFIQHQELG-YIYKTGDYGVLKE
Q9KIZ9_A1_cys                            VLDEALEPRPVWVPGQLYIGGVGLALGYWRDEEKTRNSFLVHPETGERLYKTGDLGRYLP
Q9FB18_A2_cys                            VLDEQLRPRPDWVPGELYIGGTGVAKGYWRDPEQTSLRFPVHPGSGQRLYRTGDFARHLP
Q8GAQ3_A2_4__cys                         VLNHNLDPCPNWVPGQLYIGGIGLAQGYWRDEQKTNASFILHPQTGERLYKTGDLARYLP
CCA29203.1_2085_mod2_cys                 VLSPALCHCPVGVTGEIHIGGMGVALGYWRDETLSRARYIEHPTLG-RLYKTGDLGRWSA
                                         **.      *  * *::.*** *:* .*      :   :  *      :*:*** .    

Q6DNE7_A1_4__cys                         DGNIEFLGREDFQVKINGYRVELGEIEVALKQFPGIKEAIV---TAIGE-SQQSKRLVA
CCA29202.1_1497_mod2_cys                 AGHIEFLGRNDFQVKLNGYRVELEEISAKLCQVPGVDSAVVRIHKSKGR-----EHVVA
Q5MD35_A1_cys                            SGDIEFLGRKDFQVKVAGHRIELGEIEAALLRHPALREAVV---AAPGE--RTARRLVA
Q9RFK9_A1_cys                            EGEIEFLGRKDFQVKIAGHRIELGEIEAVLQRHPSIREAVV---AAPGE--RTSRRLVA
Q70P97_A1_cys                            GGDIEFLGRKDFQVKVAGHRIELGEIEAALLRHPALREAVV---AAPGE--RSARRLVA
O68006_A2_cys                            DGYVEFLGRKDSQVKIRGYRVEMGEIENTLVSHQEITKASV---IDYTS-PDGIKNLYA
Q9KIZ9_A1_cys                            DGNIEFMGREDNQIKLRGYRVELGEIEETLKSHPNVRDAVI---VPVGN-DAANKLLLA
Q9FB18_A2_cys                            DGTLEFLGRQDDQVKIGGFRVELGEVEAALGRLPDVAAGAV---IATGD-PRGDRRLVG
Q8GAQ3_A2_4__cys                         DGNSEFLGREDFQVKISGYRIELGEIEATLLGHATVKETVV---AAVGE--LQSKQLVA
CCA29203.1_2085_mod2_cys                 QGYIEFLGRNDFQVKLRGHRVELGEIENALLRHPAIKQSVVLV-KNQGQGGHGAQYLVG
                                          *  **:**:* *:*: *.*:*: *:.  *     :    :             . : .
