CLUSTAL W multiple sequence alignment


Q9FB18_A2_cys                            LTERALLDTLAVPVGVTVLAVDDDA-ALDADGG--PLQSVQ--NLTDLAYTIFTSGSTGE
Q9KIZ9_A1_cys                            LTQPWLDGKLSWPPGIQRLLVSDA--GVEGDGDQLPMMPIQ--TPSDLAYVIYTSGSTGL
Q5MD35_A1_cys                            VTEPRLAERLSWPGDVEVVVVADIARGVS--------RPERRGSASDLAYCIYTSGSTGR
Q70P97_A1_cys                            LTEPRLAERLSWPEDVEVVVVADIARGAA--------LPERRGSVTDLAYCIYTSGSTGR
Q9RFK9_A1_cys                            LTESHLAERLSWPASVRVVAIADTARGAP------PRLPAR--AASDMAYCIYTSGSTGR
O85740_A1_3__cys                         CLESDVPDVGCACVAIDRLA-ADSA---------WPPPPAAEVAADDLAYVIYTSGSTGT
                                           :  :    .    :  :   *               .       *:** *:****** 

Q9FB18_A2_cys                            PKGVMIDHLGAANTLECVNRRFGTGPGDAVLAVSSPSFDLAVYDLFGVLAAGGTVVVPAH
Q9KIZ9_A1_cys                            PKGVMIDHRGAVNTILDINERFEIGPGDRVLALSSLSFDLSVYDVFGILAAGGTIVVPDA
Q5MD35_A1_cys                            PKGVMIEHRAAANTLLDINARFQVGPEDRIFALSSLGFDLSVYDIFGALAAGAALVLPET
Q70P97_A1_cys                            PKGVMIDHRSAANTVQDINSRFQVGPEDRVFALSSLGFDLSVYDIFGALAVGAAFVLPES
Q9RFK9_A1_cys                            PKGVKIEHRAAANTILDINERFGVGPADRVFALSSLGFDLSVYDIFGSLAAGAAIVLPQP
O85740_A1_3__cys                         PKGVMLSHAAVSNTLLDINQRYGVDANDRVLGLAELSFDLSVYDFFGATAAGAQVVLPDP
                                         **** :.* .. **:  :* *:  .. * ::.::. .***:***.**  *.*. .*:*  

Q9FB18_A2_cys                            DRRRDPGHWAELIRRERVTLWNSVPALGTLLTEYAEALAPDALRTLRAVLLSGDWIPLGL
Q9KIZ9_A1_cys                            SKLRDPAHWAALIEREKVTVWNSVPALMRMLVEHSEGRPDSLARSLRLSLLSGDWIPVGL
Q5MD35_A1_cys                            EATRDPARWLRLLRAHRVSVWNSVPTLMEMLVDVAETRGERLPDSLRLVMMSGDWIPVTL
Q70P97_A1_cys                            EATKDPASWLNLLRTHRVSVWNSVPTLMEMLVDVAETRGERLPDSLRLVMMSGDWIPVTL
Q9RFK9_A1_cys                            EVTRDPAHWLQVLRQQGVTIWNSVPTLMEMLVDQVEARGELLPETLRLVMLSGDWIPVTL
O85740_A1_3__cys                         ARGSDPSHWAELLERHAITLWNSVPAQGQMLIDYLESEPQRHLPGPRCVLWSGDWIPVSL
                                             **. *  ::. . :::*****:   :* :  *          *  : ******: *

Q9FB18_A2_cys                            PDRIRALSAPGATVMSLGGATEASIWSVWYEIGKVHEAWSSIPYGTPMANQRLEVLDEQL
Q9KIZ9_A1_cys                            PGELQAI-RPGVSVISLGGATEASIWSIGYPVRNVDPSWASIPYGRPLRNQTFHVLDEAL
Q5MD35_A1_cys                            PDRIRRLARGDIQIISLGGATEGSVWSILHPIGQVPPGARSIPYGRPMLNQRFHVLDEAL
Q70P97_A1_cys                            PDRIRRLARGDIQIISLGGATEGSVWSILHPIGQVEPTARSIPYGRPMLNQRFYVLDDAL
Q9RFK9_A1_cys                            PDRIRRLSR-DIRVISLGGATEASIWSIIHPIGRVDPAARSIPYGRPMLNQRFYVLDEKL
O85740_A1_3__cys                         PTRWWRR-WPDSAAVQPGRRTEAAIWSIEQPIRPQHTELASIPYGRALRGQSVEVLDARG
                                         * .       .   :. *  **.::**:   :        ***** .: .* . ***   

Q9FB18_A2_cys                            RPRPDWVPGELYIGGTGVAKGYWRDPEQTSLRFPVHPGSGQRLYRTGDFARHLPDGTLEF
Q9KIZ9_A1_cys                            EPRPVWVPGQLYIGGVGLALGYWRDEEKTRNSFLVHPETGERLYKTGDLGRYLPDGNIEF
Q5MD35_A1_cys                            SPRPDHVPGELFIGGVGVARGYFGDEVRTAERFIVHPKTRERLYRTGDLGRFLPSGDIEF
Q70P97_A1_cys                            ASRPDYVPGELFIGGVGVARGYFRDDVRTAERFIVHPKTNERLYRTGDLGRFLPGGDIEF
Q9RFK9_A1_cys                            APRPDHVPGDLYIGGVGLAQGYFRDEETTRARFFNHPRTGERLYRTGDLGRFLPEGEIEF
O85740_A1_3__cys                         RRCPPGVRGEIHIGGVGLALGYAGDPQRTAERFVRHPD-GRRLYRTGDLGRYLADGSIEF
                                            *  * *::.***.*:* **  *   *   *  **   .***:***:.*.*. * :**

Q9FB18_A2_cys                            LGRQDDQVKIGGFRVELGEVEAALGRLPDVAAGAVIATGDPRGDRRLVG-
Q9KIZ9_A1_cys                            MGREDNQIKLRGYRVELGEIEETLKSHPNVRDAVIVPVGN-DAANKLLLA
Q5MD35_A1_cys                            LGRKDFQVKVAGHRIELGEIEAALLRHPALREAVVAAPGE-RTARRLVA-
Q70P97_A1_cys                            LGRKDFQVKVAGHRIELGEIEAALLRHPALREAVVAAPGE-RSARRLVA-
Q9RFK9_A1_cys                            LGRKDFQVKIAGHRIELGEIEAVLQRHPSIREAVVAAPGE-RTSRRLVA-
O85740_A1_3__cys                         LGREDDQVKIRGHRIELAELDAALCAHPQVNLAATVVLGE-THERSLAS-
                                         :**:* *:*: *.*:**.*:: .*   * :  ..    *:    . *   
