CLUSTAL W multiple sequence alignment


P25464_A2_cys                            ITDSPHIDRLRSITNNRLPV-IQSDFALQLPP--SPVHPVSNCKPSDLAYIMYTSGTTGN
P27743_A2_cys                            VTNEIHSDRLRSLAETGTP--VLEIELLHLDD-QPAVNPVTETTSTDLAYAIYTSGTTGK
P26046_A2_cys                            IADSCYLPRIKGMAASGTLL-YPSVLPANPDSKWSVSNPSPLSRSTDLAYIIYTSGTTGR
P19787_A2_cys                            IADSCYLPRIKGMAASGTLL-YPSVLPANPDSKWSVSNPSPLSRSTDLAYIIYTSGTTGR
Q9C1G0v2_A2_cys                          IADGPYLERLESIMEGSLPL-IPSDEALRLPP--SPVHPNSNCHSSDLAYVMYTSGTTGL
P27742_A2_cys                            ISDACYLSRIQELAGESVRL-YRSDISTQTDGNWSVSNPAPSSTSTDLAYIIYTSGTTGK
Q9C1G0v1_A2_cys                          IADGPYLERLESIMEGSLPL-IPSDEALRLPP--SPVHPNSNCHSSDLAYVMYTSGTTGL
P94873_A2_cys                            LTDRAYAERLDRVAD-GLPCEVFGVQDLPLEP-YPAANPRSAATSTDLAYAIYTSGTTGR
                                         :::  :  *:  :                     .  :* .   .:**** :******* 

P25464_A2_cys                            PKGVMVEHHGVVNLCVSLCRLFGL-RNTDDEVILSFSNYVFDHFVEQMTDALLNGQTLVV
P27743_A2_cys                            PKAVLVEHRGVVNLQVSLAKLFGLDKAHRDEALLSFSNYIFDHFVEQMTDALLNGQKLVV
P26046_A2_cys                            PKGVTVEHHGVVNLQVSLSKVFGL-RDTDDEVILSFSNYVFDHFVEQMTDAILNGQTLLV
P19787_A2_cys                            PKGVTVEHHGVVNLQVSLSKVFGL-RDTDDEVILSFSNYVFDHFVEQMTDAILNGQTLLV
Q9C1G0v2_A2_cys                          PKGVMVEHHGVVNLAFSLAQIFGL-RDTDDEVILSFSNYIFDHFVEQMTDALLNGQTLVV
P27742_A2_cys                            PKGVMVEHHGVVNLQISLSKTFGL-RDTDDEVILSFSNYVFDHFVEQMTDAILNGQTLVM
Q9C1G0v1_A2_cys                          PKGVMVEHHGVVNLAFSLAQIFGL-RDTDDEVILSFSNYIFDHFVEQMTDALLNGQTLVV
P94873_A2_cys                            PKAVLIEHRGVVNLHTSLERLFDLSRDRGDEAVLSFSNYVFDHFVEQMTDALLSGQTLVM
                                         **.* :**:*****  ** : *.* :   **.:******:***********:*.**.*::

P25464_A2_cys                            LNDEMRGDKERLYRYIETNRVTYLSGTPSVISMYEFDRFRDHLRRVDCVGEAFSEPVFDK
P27743_A2_cys                            LDDSMRTDPGRLCRYMNDEQVTYLSGTPSVLSLYDYSSATS-LTRIDAIGEDFTEPVFAK
P26046_A2_cys                            LNDGMRGDKERLYRYIEKNRVTYLSGTPSVVSMYEFSRFKDHLRRVDCVGEAFSEPVFDK
P19787_A2_cys                            LNDGMRGDKERLYRYIEKNRVTYLSGTPSVVSMYEFSRFKDHLRRVDCVGEAFSEPVFDK
Q9C1G0v2_A2_cys                          LNDEMRGDKERLYKYIEDNKVTYLSGTPSVISMYEFDRFHSHMRRIDCVGEAFSEPVFDK
P27742_A2_cys                            LNDAMRSDKERLYQYIETNRVTYLSGTPSVISMYEFSRFKDHLRRVDCVGEAFSQPVFDQ
Q9C1G0v1_A2_cys                          LNDEMRGDKERLYKYIEDNKVTYLSGTPSVISMYEFDRFHSHMRRIDCVGEAFSEPVFDK
P94873_A2_cys                            LDDSMRSDQQRLYAYMNANAVTYLSGTPSVLSLYEYGSIPS-LKRIDAIGEDFTTPVFDK
                                         *:* ** *  **  *:: : **********:*:*::.   . : *:*.:** *: *** :

P25464_A2_cys                            IRETFPGLIINGYGPTEVSITTHKRPYPFPERRTDKSIGCQLDNSTSYVLNDDMKRVPIG
P27743_A2_cys                            IRGTFPGLIINGYGPTEISITSHKRPYPPDVHRVNKSIGFPVANTKCHVLNKAMKPVPVG
P26046_A2_cys                            IRETFHGLVINGYGPTEVSITTHKRLYPFPERRMDKSIGQQVHNSTSYVLNEDMKRTPIG
P19787_A2_cys                            IRETFHGLVINGYGPTEVSITTHKRLYPFPERRMDKSIGQQVHNSTSYVLNEDMKRTPIG
Q9C1G0v2_A2_cys                          IRETFPGLVINGYGPTEVSITTSKRLYPFPERRTNKSIGSQVSNSKSYVLSDDMKRMPIG
P27742_A2_cys                            IRDTFQGLIINGYGPTEISITTHKRLYPFPERRTDKSIGQQIGNSTSYVLNADMKRVPIG
Q9C1G0v1_A2_cys                          IRETFPGLVINGYGPTEVSITTSKRLYPFPERRTNKSIGSQVSNSKSYVLSDDMKRMPIG
P94873_A2_cys                            IRSSFGGLIINGYGPTEISITSHKRLYLKHEPRLDKSIGHPVANTACYVLNPAMQRVPVG
                                         ** :* **:********:***: ** *     * :****  : *: .:**.  *:  *:*

P25464_A2_cys                            AVGELYLGGDGVARGYHNRPDLTADRFPANPFQTEQERLEGRNARLYKTGDLVRWIHNAN
P27743_A2_cys                            GIGELYIGGIGVTRGYLNREDLTADRFVENPFQTAEERRLGENGRLYKTGDLVRWLPN--
P26046_A2_cys                            AVGELYLGGEGVVRGYHNRADVTAERFIPNPFQSEEDKREGRNSRLYKTGDLVRWIPGSS
P19787_A2_cys                            SVGELYLGGEGVVRGYHNRADVTAERFIPNPFQSEEDKREGRNSRLYKTGDLVRWIPGSS
Q9C1G0v2_A2_cys                          AVGELYLGGDGVARGYHNRPELTAERFPQNPFQTEQEKREGRNGRLYKTGDLVRWIQGSN
P27742_A2_cys                            AVGELYLGGEGVARGYHNRPEVTAERFLRNPFQTDSERQNGRNSRLYRTGDLVRWIPGSN
Q9C1G0v1_A2_cys                          AVGELYLGGDGVARGYHNRPELTAERFPQNPFQTEQEKREGRNGRLYKTGDLVRWIQGSN
P94873_A2_cys                            GMGELYIGGIGVARGYLNRPELTAERFVSNPFQSAGEKALGNNARLYKTGDLVRWLPN--
                                         .:****:** **.*** ** ::**:**  ****:  ::  *.*.***:*******: .  

P25464_A2_cys                            GDGEIEYLGRNDFQVKIRGQRIELGEIEAVLSSYPGIKQSVVLAKDRK------NDGQKY
P27743_A2_cys                            --GEVEYLGRTDLQVKIRGQRVELGEVEAALSSYPGVVRSLVVAREHA-------VGQKY
P26046_A2_cys                            --GEVEYLGRNDFQVKIRGLRIELGEIEAILSSYHGIKQSVVIAKDCR------EGAQKF
P19787_A2_cys                            --GEVEYLGRNDFQVKIRGLRIELGEIEAILSSYHGIKQSVVIAKDCR------EGAQKF
Q9C1G0v2_A2_cys                          --GEVEYLGRNDFQVKIRGQRIELGEIEAVLSSYEGIKQSVVLAKDRK------IDNQKF
P27742_A2_cys                            --GEIEYLGRNDFQVKIRGLRIELGEIEAVMSSHPDIKQSVVIAKSGK------EGDQKF
Q9C1G0v1_A2_cys                          --GEVEYLGRNDFQVKIRGQRIELGEIEAVLSSYEGIKQSVVLAKDRK------IDNQKF
P94873_A2_cys                            --GELEYLGRNDMQVKIRGQRVELGEVEAILASYPGVTRALVLAREYAASAAGGEASQKY
                                           **:*****.*:****** *:****:** ::*: .: :::*:*:.           **:

P25464_A2_cys                            LVG
P27743_A2_cys                            LVG
P26046_A2_cys                            LVG
P19787_A2_cys                            LVG
Q9C1G0v2_A2_cys                          LVG
P27742_A2_cys                            LVG
Q9C1G0v1_A2_cys                          LVG
P94873_A2_cys                            LVA
                                         **.
