CLUSTAL W multiple sequence alignment


CCJ67637.1_2717_mod3_d-ser               VQSATRGLLGEISVPVVDLEQVTWQQALASNPLIAELTPQHQAYVIYTSGSTGKPKGVIN
BGC0000425_AFH75320.1_2651_mod3_d-ser    VQTATRALLGDIAVPVVDLDHAHWQHLPSSNPSVAALTPQHAAYVIYTSGSTGKPKGVIN
CCJ67636.1_2656_mod3_d-ser               VQSATRALLGDVAVPVVDLELVTWQHQSASNPLIAELTPQHQAYVIYTSGSTGKPKGVIN
                                         **:***.***:::******: . **:  :*** :* ***** ******************

CCJ67637.1_2717_mod3_d-ser               EHSAVVNRLLWMQEAYDLDASDTVLQKTPFSFDVSVWEFFWPLFTGARLVMARPGGHKDP
BGC0000425_AFH75320.1_2651_mod3_d-ser    EHSAVVNRLLWMQEEYRLGADDTVLQKTPFSFDVSVWEFFWPLFTGARLVMARPGGHKDP
CCJ67636.1_2656_mod3_d-ser               EHSPVVNRLLCMQDTYRLDSSDALLQKTPFSFDVSVWEFFWPLFTGARLVMARPGGHKDP
                                         ***.****** **: * *.:.*::************************************

CCJ67637.1_2717_mod3_d-ser               EYLCEIIQAERVTTLHFVPSMLDVFLAHGDVSQAAGLVRVMCSGEALPGSVVRRFKQQLP
BGC0000425_AFH75320.1_2651_mod3_d-ser    QYLCDIIEAEQVTTLHFVPSMLDVFLAHGDVSQAAGLVRVMCSGEALPGSVVRRFKQQLP
CCJ67636.1_2656_mod3_d-ser               AYLCEVIQAEHITTVHFVPSMLDVFLAHGDVSQAAGLARVMCSGEALPGSLVRRFKAQLP
                                          ***::*:**::**:**********************.************:***** ***

CCJ67637.1_2717_mod3_d-ser               ASGLFNLYGPTEAAVDVTAWDCAGPITPDNTPIGKPIANTRMYVLDEHLQPVPLGVSGEL
BGC0000425_AFH75320.1_2651_mod3_d-ser    GSQLFNLYGPTEAAVDVTAWDCNAALAPDNTPIGKAIANTRMYVLDAHMQPVPLGVSGEL
CCJ67636.1_2656_mod3_d-ser               GSALFNHYGPTEAAVEVTAWDCNGAVTPDNTPIGKPIGNVRMYVLDAHLQPVPLGVSGEL
                                         .* *** ********:****** ..::********.*.*.****** *:***********

CCJ67637.1_2717_mod3_d-ser               FIGGVQVARGYLNRPQLTAERFFDDPFNPGRMYRTGDVGRFLSDGNIEYLGRNDDQVKIR
BGC0000425_AFH75320.1_2651_mod3_d-ser    YIGGVQVARGYLNRPDLTAERFLKDPFSEGRLYRTGDVGRFLADGNIEYLGRNDDQVKIR
CCJ67636.1_2656_mod3_d-ser               FIGGVQVARGYLNRPELNAERFLKDPYSTGRIYRTGDVARYLPDGNIEYLGRNDDQVKIR
                                         :**************:*.****:.**:. **:******.*:*.*****************

CCJ67637.1_2717_mod3_d-ser               GLRIELGEIQARLGEFSQIKEATVLAREDVPGDKRLVA
BGC0000425_AFH75320.1_2651_mod3_d-ser    GLRIELGEIQARLGEFPQILEATVLAREDVPGDKRLVA
CCJ67636.1_2656_mod3_d-ser               GVRIELGEIQARLGEFPHIQEATVLAREDVPGDKRLVA
                                         *:**************.:* ******************
