CLUSTAL W multiple sequence alignment


CCJ67639.1_2757_mod3_d-val               LSVASIEVPEGARRLDLDTLDLSVEPDHNPALEQSAETAAYIMYTSGSTGTPKGVLVPHR
CCJ67637.1_1654_mod2_d-val               LSVTSIEVPEGARRLDLDTLDLSVEPEHNPALEQLAETAAYIMYTSGSTGTPKGVLVPHR
CCJ67638.1_2717_mod3_d-val               LSVTSIEVPEGARRLDLDTLDLSVEPEHNPALEQLAETAAYIMYTSGSTGTPKGVLVPHR
CCJ67638.1_1653_mod2_d-val               LSVASIEVPEGARRLDLDTLDLSVEPDHNPALEQSAETAAYIMYTSGSTGTPKGVLVPHR
                                         ***:**********************:******* *************************

CCJ67639.1_2757_mod3_d-val               AITRLVINNGYADFNQHDRVAFASNPAFDASTLDVWAPLLNGGAVVVVDQDTLLSQTDFV
CCJ67637.1_1654_mod2_d-val               AITRLVINNGYADFNQHDRVAFASNPAFDASTLDVWAPLLNGGAVVVVDQDTLLSQTDFA
CCJ67638.1_2717_mod3_d-val               AITRLVINNGYADFNQHDRVAFASNPAFDASTLDVWAPLLNGGAVVVVDQDTLLSQTDFA
CCJ67638.1_1653_mod2_d-val               AITRLVINNGYADFNQHDRVAFASNPAFDASTLDVWAPLLNGGAVVVVDQDTLLSQADFA
                                         ********************************************************:**.

CCJ67639.1_2757_mod3_d-val               ALLQQQAVSVLWMTAGLFHQYAEGLLAVFPQLRYLIVGGDVLDPSVIARVLKDGAPQHLL
CCJ67637.1_1654_mod2_d-val               ALLQEQAVSVLWMTAGLFHQYAEGLLAVFPQLRYLIVGGDVLDPSVIARVLKDGAPQHLL
CCJ67638.1_2717_mod3_d-val               ALLQEQAVSVLWMTAGLFHQYAEGLLAVFPQLRYLIVGGDVLDPSVIARVLKDGAPQHLL
CCJ67638.1_1653_mod2_d-val               ALLQEQAVSVLWMTAGLFHQYAEGLLPVFTQLRYLIVGGDVLDPSVIARVLKDGAPQHLL
                                         ****:*********************.**.******************************

CCJ67639.1_2757_mod3_d-val               NGYGPTEATTFSTTHEITRADEGSIPIGRPVGNSRTYVLDARQQPVAVGVTGELYIGGQG
CCJ67637.1_1654_mod2_d-val               NGYGPTEATTFSTTHEITRADEGSIPIGRPVGNSRAYVLDARQQPVPVGVTGELYIGGQG
CCJ67638.1_2717_mod3_d-val               NGYGPTEATTFSTTHEITRADEGSIPIGRPVGNSRAYVLDARQQPVPVGVTGELYIGGQG
CCJ67638.1_1653_mod2_d-val               NGYGPTEATTFSTTHEITRADEGSIPIGRPVGNSRAYVLDARQQPVPVGVTGELYIGGQG
                                         ***********************************:**********.*************

CCJ67639.1_2757_mod3_d-val               VALGYLNRAELTAEKFLADPFNDGALMYRTGDLVAWREDGTLQYQGRNDQQVKIRGFRIE
CCJ67637.1_1654_mod2_d-val               VALGYLNRAELTAQAFLADPFNDGALMYRTGDLVAWREDGTLQYQGRNDQQVKIRGFRIE
CCJ67638.1_2717_mod3_d-val               VALGYLNRAELTAQAFLADPFNDGALMYRTGDLVAWREDGTLQYQGRNDQQVXIRGFRIE
CCJ67638.1_1653_mod2_d-val               VALGYLNRAELTAEKFLADPFNDGALMYRTGDLVAWREDGTLQYQGRNDQQVKIRGFRIE
                                         *************: ************************************* *******

CCJ67639.1_2757_mod3_d-val               LGEIETRLSEHPQVKDAVVLARQDEPGHKRLVA
CCJ67637.1_1654_mod2_d-val               LGEIETRLSEHPQVKDAVVLAREDEPGHKRLVA
CCJ67638.1_2717_mod3_d-val               LGEIETRLSEHPQVKDAVVLAREDEPGHKRLVA
CCJ67638.1_1653_mod2_d-val               LGEIETRLSEHPQVKDAVVLAREDEPGHKRLVA
                                         **********************:**********
