CLUSTAL W multiple sequence alignment


Q83VS0_A11_21__dab                       LTQRDLQKRLPTLTLPLVLLDDDQRNTFTERDDNPVVEALGVRNLAYVIYTSGSTGNPKG
O85168_A3_dab                            MTQRHLQEYLPTLTLPLVLLDDDQRKTFTERDDNPVVEALGVRNLAYVIYTSGSTGNPKG
Q83VS0_A10_20__dab                       LTQRGLQERLPALSMPLVLLDDEHCQGFTECDDNPVVPTLGVRNLAYVIYTSGSTGNPKG
BGC0000425_AFH75322.1_4831_mod5_dab      LTQRPLQDRLPALAIPSVLLDEP----VEGADHNPVVPGLNARHLAYVIYTSGSTGNPKG
O85168_A4_dab                            LTLPGLQDRLPALSMPLVLLDDEQYQGLAECDDNPVVPTLGVRNLAYVIYTSGSTGNPKG
                                         :*   **. **:*::* ****:     .   *.****  *..*:****************

Q83VS0_A11_21__dab                       VMIEHRGLVNYSVDAARLFALSQSDTVLQQNTLNFDLSVEEIFPALLAGATLAPSREIFG
O85168_A3_dab                            VMIEHRGLVNYSVDAARLFDLSPTDTVLQQNTLNFDLSVEEIFPALLAGATLTPSREIFG
Q83VS0_A10_20__dab                       VMIEHRGLVNYSVDAARLFGLSQSDTVLQQNTLNFDLSVEEIFPALLAGATLAPSREIFG
BGC0000425_AFH75322.1_4831_mod5_dab      VMIEHRGLVNYSLDAARLFGLTPQDTVLQQNTLNFDLSVEEIFPALLAGATLAPSRHVFG
O85168_A4_dab                            VMIEHRGLVNYSVDAARLFDLSQSDTVLQQNTLNFDLSVEEIFPALLAGATLAPSREIFG
                                         ************:****** *:  ****************************:***.:**

Q83VS0_A11_21__dab                       SEGTENHGIYPTVLHLTAAHWHTLVAEWHNQPQAAAQRLAEVRLINVTGDALSAQKLKLW
O85168_A3_dab                            SEGTENHGINPTVLHLTAAHWHTLVAEWHKQPQVAEQRLQHVRLINVTGDALSAQKLKLW
Q83VS0_A10_20__dab                       SEGTENHGIYPTVLHLTAAHWHTLVAEWHNQPQAAEQRLAEVRLINVTGDALSAQKLKLW
BGC0000425_AFH75322.1_4831_mod5_dab      TEAARDPAITPTFLHLTAAHWHTLAAEWHHDPQQAQAHLRDVRLINVTGDALSAQKLKLW
O85168_A4_dab                            SEGTETHGIQPTVLHLTTAHWHTLVAEWHNQPQAAEQRLQHVRLINVTGDALSAQKLKLW
                                         :*.:.  .* **.****:******.****::** *  :* .*******************

Q83VS0_A11_21__dab                       DEVRPAHTRLINTYGPTEATVSCTAAYVSHDAIAGSEGSGNATIGKPMANTRIYLLDAHQ
O85168_A3_dab                            DEVRPAHTRLINTYGPTEATVSCTAAYVSHDAAAGSEGSGNATIGKPMANTRIYLLDAHQ
Q83VS0_A10_20__dab                       DEVRPAHTRLINTYGPTEATVSCTAAYVSHDAAAGSEGSGNATIGKPMANTRIYLLDAHQ
BGC0000425_AFH75322.1_4831_mod5_dab      DEARPAHVRLINTYGPTEATVSCTTAYVSYTG----DINGNTTIGKPMANTRIYLLDSRQ
O85168_A4_dab                            DEVRPAHTLLINTYGPTEATVSCTAAYVSYDAAAGSEGSGNATIGKPMANTRIYLLDAHQ
                                         **.****. ***************:****: .    : .**:***************::*

Q83VS0_A11_21__dab                       QPVPYGVAGEIFIGGDGVARGYLNLEEVNAERFLADPFSNSPEARMYKTGDLARYMADGR
O85168_A3_dab                            QPVPYGVAGEIYIGGDGVARGYLNLEEVNAERFLADPFSESPDARMYKTGDLARYMADGR
Q83VS0_A10_20__dab                       QPVPYGVAGEIFIGGDGVARGYLNLEEVNAERFLADPFSNSPDARMYKTGDLARYMADGR
BGC0000425_AFH75322.1_4831_mod5_dab      QPVPLGVAGEIFIGGDGVARGYLNLEQISTERFIADPFSPVPGARMYKTGDLARYLADGS
O85168_A4_dab                            QPVPYGVAGEIYIGGDGVARGYLNLEEVNAERFLADPFSESPDARMYKTGDLARYMADGR
                                         **** ******:**************::.:***:*****  * ************:*** 

Q83VS0_A11_21__dab                       IEYLGRNDFQVKVRGFRIELGEIEARFGNCAGVKEAVVIAREDTPGDKRLVA
O85168_A3_dab                            IEYLGRNDFQVKVRGFRIELGEIEARLGNCTGVKEAVVIAREDNPGDKRLVA
Q83VS0_A10_20__dab                       IEYLGRNDFQVKVRGFRIELGEIEARLGNCKGVKEAVVIAREDNPGEKRLVA
BGC0000425_AFH75322.1_4831_mod5_dab      IEYLGRNDFQVKVRGFRIELGEIESSLGNCAGVKEVAVIAREDRPGEKRLVA
O85168_A4_dab                            IEYLGRNDFQVKVRGFRIELGEIEARLGNCKGVKEAVVIAREDNPGEKRFVA
                                         ************************: :*** ****..****** **:**:**
