CLUSTAL W multiple sequence alignment


Q83VS1_A4_9__dhab|dht                    LSQQSVQQALPVSQVPVIYLDDAGLQDESVDNPQIS-VKPDNLAYVIYTSGSTGLPKGVM
Q9FDB3_A1_dhab|dht                       LSQQSVQPALPVSDVPLIYLDDVDLQDERACNPQVS-VRPSDLAYVIYTSGSTGLPKGVM
Q83VS1_A4_dhab|dht                       LSQQSVQQALPVSQVPVIYLDDAGLQDESVDNPQIS-VKPDNLAYVIYTSGSTGLPKGVM
Q83VS0_A8_18__dhab|dht                   LSQRSVQSTLPASEVPVISLDD-DLQGESVCNPQVP-VKPTNLAYVIYTSGSTGLPKGVM
Q9FDB3_A1_1__dhab|dht                    LSQQSVQPALPVSDVPLIYLDDVDLQDERACNPQVS-VRPSDLAYVIYTSGSTGLPKGVM
Q83VS0_A4_14__dhab|dht                   LSQQSVQQALPVTEVPIISLDDADLQDESVCNPEVAGLTAASLAYVIYTSGSTGLPKGVM
                                         ***:*** :**.::**:* *** .**.* . **::. : . .******************

Q83VS1_A4_9__dhab|dht                    VEHRNVARLFSATEDWFGFNEQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVPQLVSRS
Q9FDB3_A1_dhab|dht                       VEHRNVARLFSATQDWFGFNEQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVPQLVSRS
Q83VS1_A4_dhab|dht                       VEHRNVARLFSATEDWFGFNEQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVPQLVSRS
Q83VS0_A8_18__dhab|dht                   VEHRNVARLFSATEEWFGFNQQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVPQLVSRS
Q9FDB3_A1_1__dhab|dht                    VEHRNVARLFSATQDWFGFNEQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVPQLVSRS
Q83VS0_A4_14__dhab|dht                   VEHRNVARLFSATQDWFGFGEQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVPQLVSRS
                                         *************::****.:***************************************

Q83VS1_A4_9__dhab|dht                    PEDFYTLLCSTAVTVLNQTPSAFRQLITAQGENQQAHSLRQVIFGGEALETAMLKPWYAR
Q9FDB3_A1_dhab|dht                       PEDFYNLLCSAGVTVLNQTPSAFRQLIAAQDDKEQVHSLRQVIFGGEALETAMLKPWYAR
Q83VS1_A4_dhab|dht                       PEDFYTLLCSTAVTVLNQTPSAFRQLITAQGENQQAHSLRQVIFGGEALETAMLKPWYAR
Q83VS0_A8_18__dhab|dht                   PEDFYNLLCSAGVTVLNQTPSAFRQLIAAQAENTQAHSLRQVIFGGEALETAMLKPWYAR
Q9FDB3_A1_1__dhab|dht                    PEDFYNLLCSAGVTVLNQTPSAFRQLIAAQDDKEQVHSLRQVIFGGEALETAMLKPWYAR
Q83VS0_A4_14__dhab|dht                   PQDFHDLLCSAGVTVLNQTPSAFRQLIAAQGENEQAHSLRQVIFGGEALETAMLKPWYAR
                                         *:**: ****:.***************:** :: *.************************

Q83VS1_A4_9__dhab|dht                    NVNAATQLVNMYGITETTVHVTYYPLQPEDAQRVGASPIGTRIPDLQLYLLDTCGEPVPV
Q9FDB3_A1_dhab|dht                       KVNASTQLVNMYGITETTVHVTYYPLQPEDARRVGASPIGKRIPDLQLYLLDAYGHPLPP
Q83VS1_A4_dhab|dht                       NVNAATQLVNMYGITETTVHVTYYPLQPEDAQRVGASPIGTRIPDLQLYLLDTCGEPVPV
Q83VS0_A8_18__dhab|dht                   QANAGTQLVNMYGITETTVHVTYYPLQPEDAQRLGASPIGRRIPDLQLYVLDARGEPVPV
Q9FDB3_A1_1__dhab|dht                    KVNASTQLVNMYGITETTVHVTYYPLQPEDARRVGASPIGKRIPDLQLYLLDAYGHPLPP
Q83VS0_A4_14__dhab|dht                   NVNAGTQLVNMYGITETTVHVTYYPLQADDAQRIGASPIGRRIPDLQLYVLDTHGEPVPV
                                         :.**.**********************.:**:*:****** ********:**: *.*:* 

Q83VS1_A4_9__dhab|dht                    GVVGELYVGGAGVARGYLNREALTAERFIDNPFNTAPGARLYRTGDLGRWLADGTLEYLG
Q9FDB3_A1_dhab|dht                       GAVGELYVGGAGVARGYLNRDELNTTRFLDDPFASAPGARMYRSGDLGRWLPDGSLEYLG
Q83VS1_A4_dhab|dht                       GVVGELYVGGAGVARGYLNREALTAERFIDNPFNTAPGARLYRTGDLGRWLADGTLEYLG
Q83VS0_A8_18__dhab|dht                   GVVGELYVGGAGVARGYLNREALTAERFLDNPFSHTADARMYRTGDLGRWLADGSLEYLG
Q9FDB3_A1_1__dhab|dht                    GAVGELYVGGAGVARGYLNRDELNTTRFLDDPFASAPGARMYRSGDLGRWLPDGSLEYLG
Q83VS0_A4_14__dhab|dht                   GVVGELYVGGAGVARGYLNREALTAERFIDNPFNTAPGARLYRTGDLGRWLADGSLEYLG
                                         *.******************: *.: **:*:**  :..**:**:*******.**:*****

Q83VS1_A4_9__dhab|dht                    RNDEQVKIRGFRIELGEIEARLAEYPDVRDAVVLCREDVPGDKRLVA
Q9FDB3_A1_dhab|dht                       RNDEQVKIRGFRIELGEIEARLSACEGVRDAVVVVREDEPGDQRLVA
Q83VS1_A4_dhab|dht                       RNDEQVKIRGFRIELGEIEARLAEYPDVRDAVVLCREDVPGDKRLVA
Q83VS0_A8_18__dhab|dht                   RNDEQVKIRGFRIELGEIEARLAEYPDVRDAVVLCREDVPGDKRLVA
Q9FDB3_A1_1__dhab|dht                    RNDEQVKIRGFRIELGEIEARLSACEGVRDAVVVVREDEPGDQRLVA
Q83VS0_A4_14__dhab|dht                   RNDEQVKIRGFRIELGEIEAQLCACDGVQDALVLVREDEPGDKRLVA
                                         ********************:*.   .*:**:*: *** ***:****
