CLUSTAL W multiple sequence alignment


Q8KLL4v1_A1_dpg                          VCGAGTAAVVPSGHVLVTMDDAVDGETSLVPVGADDLAYVMYTSGSTGTPKGVAVAHGGV
BGC0000418_AHF20583.1_473_mod1_dpg       VCRAGTA--TPAGYQRILVDDRVSGEASLVPVGANDLAYVMYTSGSTGTPKGVAVSHGGV
Q70AZ8_A1_3__dpg                         LCRESTAGAVPAGHELIDMDRVGEGVAAPVAIGADDLAYVMYTSGSTGKPKGVAVAHGGV
Q7WZ65_A1_dpg                            VCQEATSGVVPPGYQQLLVNDADDGEAALVPIGADDLAYVMYTSGSTGTPKGVAIPHGGV
Q8KLL4v2_A1_dpg                          VCGAGTAAVVPSGHVLVTMDDAVDGETSLVPVGADDLAYVMYTSGSTGTPKGVAVAHGGV
BGC0000419_AIG79242.1_473_mod1_dpg       VCRAGTA--TPSGYQRILVDDRVSGEASLVPVGANDLAYVMYTSGSTGTPKGVAVSHGGV
BGC0001178_AGS77308.1_476_mod1_dpg       MCRKETSGAVPAGHVRITVEDAVEGEVPPVAIGPDDLAYVMYTSGSTGTPKGVAIPHGGV
                                         :*   *:  .*.*:  : ::   .* .. *.:*.:*************.*****:.****

Q8KLL4v1_A1_dpg                          AALAGDPGWGVGAGDTVLMHAPHTFDASLYDLWVPLVSGARVLLAEPGVVDAERLAAHVA
BGC0000418_AHF20583.1_473_mod1_dpg       AALLGYKVWDLHPGDAVLMHAPHTFDPALYEVLVPLVAGARVILAGPGVIDADRLAAHAA
Q70AZ8_A1_3__dpg                         AALAGDPVWEVGAGDAVLMHAPHTFDASLYDVWVPLVSGARVMLAEPGVVDAQRLAAHVA
Q7WZ65_A1_dpg                            AALAGDPGWGVGPGDAVLMHAPHTFDASLYDVWVPLVSGARVMITEPGVVDAERLAGHVA
Q8KLL4v2_A1_dpg                          AALAGDPGWGVGAGDTVLMHAPHTFDASLYDLWVPLVSGARVLLAEPGVVDAERLAAHVA
BGC0000419_AIG79242.1_473_mod1_dpg       AALLGYKVWDLHPGDAVLMHAPHTFDPALYEVLVPLVAGARVILAGPGVIDADRLAAHAA
BGC0001178_AGS77308.1_476_mod1_dpg       AALAGDPGWDVGAGDAVLMHAPHTFDASLYDVWVPLLSGARVLLAEPGVVDAEQLVAHVA
                                         *** *   * : .**:**********.:**:: ***::****::: ***:**::*..*.*

Q8KLL4v1_A1_dpg                          EGLTSVNFTAGQFRALVQESPESFSGLRDVLAGGDVVPLGEVERVRRACPELVVWHTYGP
BGC0000418_AHF20583.1_473_mod1_dpg       EGLTSVNFTAGQFRALVQEKPDCFAGLRYFQTGGDVVPLGAVERVRQACPDLRVLHTYGP
Q70AZ8_A1_3__dpg                         DGLTAVNFTAGQFRALAQESPESFAGLRDVLAGGDVVPLGAVERVRQACPGLRVWHTYGP
Q7WZ65_A1_dpg                            DGLTAVNFTAGHFRALAQESPESFSGLREVAAGGDVVPLDVVERVRRACPRLRVWHTYGP
Q8KLL4v2_A1_dpg                          EGLTSVNFTAGQFRALVQESPESFSGLRDVLAGGDVVPLGEVERVRRACPELVVWHTYGP
BGC0000419_AIG79242.1_473_mod1_dpg       EGLTSVNFTAGQFRALVQEKPDCFAGLRYFQTGGDVVPLGAVERVRQACPDLRVLHTYGP
BGC0001178_AGS77308.1_476_mod1_dpg       DGLTAVNFTAGQFRALAQESPESFSGLRVVAAGGDVVPPGALERVRRACPRLRVLHSYGP
                                         :***:******:****.**.*:.*:*** . :****** . :****:*** * * *:***

Q8KLL4v1_A1_dpg                          TETTLCATWKAIEPSDRLGSVLPIGRPLPGRRLYVLDVFLRPLPPGVEGDLYIAGAGVAH
BGC0000418_AHF20583.1_473_mod1_dpg       TETTFCASWKVIRPGDELGTTLPIGKPHPGRRLYVLDVFLRPLPPGVAGDLYIAGAGVAH
Q70AZ8_A1_3__dpg                         TETTLCATWKKIEPGDRLGSTLPIGRPLPGRRLYVLDVFLRPLPPGVAGDLYIAGAGVAQ
Q7WZ65_A1_dpg                            TETTLCATWKAIEPGDEVGPVLPIGRALPGRRLYVLDAFLRPLPPGIAGDLYLAGAGVAH
Q8KLL4v2_A1_dpg                          TETTLCATWKAIEPSDRLGSVLPIGRPLPGRRLYVLDVFLRPLPPGVEGDLYIAGAGVAH
BGC0000419_AIG79242.1_473_mod1_dpg       TETTFCASWKVIEPGDELGTTLPIGKPHPGRRLYVLDVFLRPLPPGVAGDLYIAGAGVAH
BGC0001178_AGS77308.1_476_mod1_dpg       TETTLCATWKTIEPDDRIGPVLPIGRPLPGRRLYVLDVFLRPLPPGVAGDLYIAGVGLAH
                                         ****:**:** *.*.*.:*..****:. *********.********: ****:**.*:*:

Q8KLL4v1_A1_dpg                          GYLDRPGLTAERFVADPFASGERMYRTGDVAYWTDEGELVYAGRADNQVKIRGYRVEPGE
BGC0000418_AHF20583.1_473_mod1_dpg       GYLGRTALTAERFVADPFASGERMYRTGDLAYWNDEGELVFAGRADTQVKIRGYRVEPGE
Q70AZ8_A1_3__dpg                         GYLGRPALTAERFVADPFAAGERMYRTGDVAYWTGDGELVFAGRADNQVKIRGYRVEPGE
Q7WZ65_A1_dpg                            GYLGRASLTAERFVADPFVAGERMYRTGDLAYWTGEGELVFAGRDDDQVKIRGYRVEPGE
Q8KLL4v2_A1_dpg                          GYLDRPGLTAERFVADPFASGERMYRTGDVAYWTDEGELVYAGRADNQVKIRGYRVEPGE
BGC0000419_AIG79242.1_473_mod1_dpg       GYLGRTALTAERFVADPFASGERMYRTGDLAYWNDEGELVFAGRADTQVKIRGYRVEPGE
BGC0001178_AGS77308.1_476_mod1_dpg       GYLGSPALTGGRFVADPFASGERMYRTGDVAYWTGEGELVFAGRADNQVKIRGYRVEPGE
                                         ***. ..**. *******.:*********:***..:****:*** * *************

Q8KLL4v1_A1_dpg                          IEAVLAERPGVDQAVVVAREGRLIG
BGC0000418_AHF20583.1_473_mod1_dpg       VEAVLADQPGVDQAVVAVRDGRLIG
Q70AZ8_A1_3__dpg                         IETVLAEQPGVDQAVVLARDGRLIG
Q7WZ65_A1_dpg                            VEAVLAGQPGVDQAVVVAREGRLLG
Q8KLL4v2_A1_dpg                          IEAVLAERPGVDQAVVVAREGRLIG
BGC0000419_AIG79242.1_473_mod1_dpg       VEAVLADQPGVDQAVVAVRDGRLIG
BGC0001178_AGS77308.1_476_mod1_dpg       IETVLAEQPGVDQAVVLARDGRLIG
                                         :*:*** :******** .*:***:*
