CLUSTAL W multiple sequence alignment


BGC0000419_AIG79240.1_481_mod1_dpg       VCTQATSGVAPAD-----AIVLDAPETRAAVDAFADTATEFRPSADDLAYVMYTSGSTGL
Q939Y9_A1_7__dpg                         LCTLATSAVAPGN-----AIVLDAPETRVAVRDCA--APEIRPHADDLAYVMYTSGSTGL
Q70AZ6_A1_dpg                            ICTQATEAAVPQNVPQRATIVLDAPPTRAAVDACAGTAPTFRPSAADLAYVMYTSGSTGV
O52821_A1_7__dpg                         LCTQDTSGVVPEN-----AIVLDAPDTRASIEDCADTAPEIRLYAGDLAYVMYTSGSTGL
Q939Y9_A1_dpg                            LCTLATSAVAPGN-----AIVLDAPETRVAVRDCA--APEIRPHADDLAYVMYTSGSTGL
Q70AZ6_A1_7__dpg                         ICTQATEAAVPQNVPQRATIVLDAPPTRAAVDACAGTAPTFRPSAADLAYVMYTSGSTGV
BGC0000418_AHF20585.1_481_mod1_dpg       VCAQATSGVAPED-----AIVLDAPETRVAIDAFAGTATEFRPSADDLAYVMYTSGSTGL
BGC0001178_AGS77310.1_492_mod1_dpg       ICTQATGEGLPGDVAGRATIVLDAPETRAAVEGCAATAPEIRLSAGDLAYVMYTSGSTGV
                                         :*:  *    * :     :****** **.::   *  *. :*  * *************:

BGC0000419_AIG79240.1_481_mod1_dpg       PKGVGIPHGGVAGLAGDRGWQIGPGDGVLMHATHVFDPSLYAMWVPLSTGARVLLTEPGV
Q939Y9_A1_7__dpg                         PKGVAIPHGAVAGLAGDAGWQIGPGDGVLMHATHVFDPSLYAMWVPLVSGARVLLTEPGV
Q70AZ6_A1_dpg                            PKGVAVPHGAVAGLAGDAGWRIGPGDGVLMHATHVFDPSLYEMWVPLATGGRVLVAAPGV
O52821_A1_7__dpg                         PKGVAIPHGAVAGLAGDSGWQIGPDDGVLMHATHVFDPSLYAMWVPLVAGGRVLLTEPGV
Q939Y9_A1_dpg                            PKGVAIPHGAVAGLAGDAGWQIGPGDGVLMHATHVFDPSLYAMWVPLVSGARVLLTEPGV
Q70AZ6_A1_7__dpg                         PKGVAVPHGAVAGLAGDAGWRIGPGDGVLMHATHVFDPSLYEMWVPLATGGRVLVAAPGV
BGC0000418_AHF20585.1_481_mod1_dpg       PKGVGIPHGGVAGLAGDRGWQIGPGDGVLMHATHVFDPSLYAMWVPLSTGARVLLTEPGV
BGC0001178_AGS77310.1_492_mod1_dpg       PKGVAIPHGAVAGLAGDAGWQLGTDDGVLMHATHVFDPSLYEMWVPLVTGGRVLVAEPGV
                                         ****.:***.******* **::*..**************** ***** :*.***:: ***

BGC0000419_AIG79240.1_481_mod1_dpg       LDAAGVRQAVARGANYVHLTAGTFRALAETSPECFDGLVEIGTGGDIVPAQSVENLRRAQ
Q939Y9_A1_7__dpg                         LDAAGVRQAVHRGATFVHLTAGTFRALAETAPECFEGLVEIGTGGDVVPLQSVENLRRAQ
Q70AZ6_A1_dpg                            VDAGGIRQAVARGATAVHLTAGTFRALAEASPDCFAGLREVGTGGDVVPAHTVAHLRRAQ
O52821_A1_7__dpg                         LDAAGVRQAVERGATAVHLTAGSFRALAETSPECFAGLVEIGTGGDVVPAQSVANLRRAQ
Q939Y9_A1_dpg                            LDAAGVRQAVHRGATFVHLTAGTFRALAETAPECFEGLVEIGTGGDVVPLQSVENLRRAQ
Q70AZ6_A1_7__dpg                         VDAGGIRQAVARGATAVHLTAGTFRALAEASPDCFAGLREVGTGGDVVPAHTVAHLRRAQ
BGC0000418_AHF20585.1_481_mod1_dpg       LDAAGVRQAVARGANYVHLTAGTFRALAETSPECFDGLVEIGTGGDIVPAQSVENLRRAQ
BGC0001178_AGS77310.1_492_mod1_dpg       VDAGGIRQAVERGATAVHLTAGTFRALAEASPDCFAGLREIGTGGDVVPAHTVANLRRAQ
                                         :**.*:**** ***. ******:******::*:** ** *:*****:** ::* :*****

BGC0000419_AIG79240.1_481_mod1_dpg       PNLRVRNTYGPTETTLCATWLPIEPGDVVDRELPIGHPMTNRRIYILDAFLRPVAPGVAG
Q939Y9_A1_7__dpg                         PGLRVRNTYGPTETTLCATWLPIEPGEVLGRELPIGHPMTNRRIYLLDAFLRPVPPGVAG
Q70AZ6_A1_dpg                            PQLRVRNTYGPTETTLCATWKPIEPGAQLGPELPIGRPMTNRRIYILDAFLRPVAPGVAG
O52821_A1_7__dpg                         PGLRVRNTYGPTETTLCATWLPIEPGDVIDRELPIGHPMTNRKIYILDAFLRPVPPGVAG
Q939Y9_A1_dpg                            PGLRVRNTYGPTETTLCATWLPIEPGEVLGRELPIGHPMTNRRIYLLDAFLRPVPPGVAG
Q70AZ6_A1_7__dpg                         PQLRVRNTYGPTETTLCATWKPIEPGAQLGPELPIGRPMTNRRIYILDAFLRPVAPGVAG
BGC0000418_AHF20585.1_481_mod1_dpg       PNLRVRNTYGPTETTLCATWLPIEPGDVVDRELPIGHPMTNRRIYILDAFLRPVAPGVAG
BGC0001178_AGS77310.1_492_mod1_dpg       PGVRVRNTYGPTETTLCATWKPIEPGDPLGPELPIGRPMTNRRIYLLDAFLRPVAPGVAG
                                         * :***************** *****  :. *****:*****:**:********.*****

BGC0000419_AIG79240.1_481_mod1_dpg       ELYIAGTGLARGYLDSPGLTSERFVACPFLPGERMYRTGDLARWTRGGEVVFLERADDQV
Q939Y9_A1_7__dpg                         ELYIAGTGLAHGYLKSPGLTAGRFVACPFAAGERMYRTGDRARWTRDGEVVFLGRADDQV
Q70AZ6_A1_dpg                            ELYIAGTGLARGYLSRPDLTAERFVACPFLAGERMYRTGDLARWNRDGEVVFLGRADDQV
O52821_A1_7__dpg                         ELYIAGTGLARGYLDSPGLTADRFVACPFLAGERMYRTGDVARWTRDGEVVFLGRADDQV
Q939Y9_A1_dpg                            ELYIAGTGLAHGYLKSPGLTAGRFVACPFAAGERMYRTGDRARWTRDGEVVFLGRADDQV
Q70AZ6_A1_7__dpg                         ELYIAGTGLARGYLSRPDLTAERFVACPFLAGERMYRTGDLARWNRDGEVVFLGRADDQV
BGC0000418_AHF20585.1_481_mod1_dpg       ELYIAGTGLARGYLDSPGLTSERFVACPFLPGERMYRTGDLARWTRGGEVVFLERADDQV
BGC0001178_AGS77310.1_492_mod1_dpg       EVYIAGTGLARGYLSRPDLTAERFVACPFLAGERMYRTGDLARWNRDGEVVFLGRADDQV
                                         *:********:***. *.**: ******* .********* ***.*.****** ******

BGC0000419_AIG79240.1_481_mod1_dpg       KIRGYRVELGEVESVLAAQPGVVEAVVMAREDQPGEKRLVG
Q939Y9_A1_7__dpg                         KIRGYRVELGEVEAALAAQPGVVEAVVTAREDQPGEKRLVG
Q70AZ6_A1_dpg                            KIRGYRVELAEVEAVLAAQPGVREAVVVAREDRPGERRLVG
O52821_A1_7__dpg                         KIRGYRVELGEVEAVLAAQPGVVEAVVMAREDQPGEKRLVG
Q939Y9_A1_dpg                            KIRGYRVELGEVEAALAAQPGVVEAVVTAREDQPGEKRLVG
Q70AZ6_A1_7__dpg                         KIRGYRVELAEVEAVLAAQPGVREAVVVAREDRPGERRLVG
BGC0000418_AHF20585.1_481_mod1_dpg       KIRGYRVELGEVESVLAAQPGVVEAVVMAREDQPGEKRLVG
BGC0001178_AGS77310.1_492_mod1_dpg       KIRGFRVELAEVEAVLAAQPGVREAVVVAREYQPGERRLVG
                                         ****:****.***:.******* **** *** :***:****
