CLUSTAL W multiple sequence alignment


O33743_A2_6__gln                         LTQRHLQE-LAAYQGEIIDVD--EEAIYTGADTNLDNVA--GKDDLAYVIYTSGSTGNPK
AEU11006.1_2653_mod1_gln                 LTQQRLVESLGKHQARVVHLD--SDWLSISEFSQGNPIAQVQASNLAYVIYTSGSTGQPK
AHZ20774.1_1541_mod2_gln                 LTRSE----LKVNYGETICLDIYKEEIETQFTDNLEITV--FPDNIAYIIFTSGSTGRPK
BGC0000369_AHZ20774.1_1541_mod2_gln      LTRSE----LKVNYGETICLDIYKEEIETQFTDNLEITV--FPDNIAYIIFTSGSTGRPK
                                         **: .    *    .. : :*  .: :      : :  .    .::**:*:******.**

O33743_A2_6__gln                         GVMISHQAICNHMLWMRETFPLTTEDAVLQKTPFSFDASVWEFYLPLITGGQLVLAKPDG
AEU11006.1_2653_mod1_gln                 GVMLSHSNLCNHTFWMQATFPITAKDKVLQKTPFGFDASVWEFYAPLLAGGQLLMAQPGG
AHZ20774.1_1541_mod2_gln                 GVAVSHQALAYHQNWFLENFTVNNHDIVLQKTPFSFDASVWEFWTPLMVGAKLVMAKPGG
BGC0000369_AHZ20774.1_1541_mod2_gln      GVAVSHQALAYHQNWFLENFTVNNHDIVLQKTPFSFDASVWEFWTPLMVGAKLVMAKPGG
                                         ** :**. :. *  *:  .*.:. .* *******.********: **:.*.:*::*:*.*

O33743_A2_6__gln                         HRDIAYMTRLIRDEKITTLQMVPSLLDLVMTDPGWSACTSLQRVFCGGEALTPALVSRFY
AEU11006.1_2653_mod1_gln                 HTDSAYLLRVIAQEQVTTVQLVPSLLQMLLEQGGIETCHSLKHVFCGGEALPVTLQEGLL
AHZ20774.1_1541_mod2_gln                 HQDPAYLVKTIQQENVTLLQLVPSLLEIILGEPKFSQCSSLRLVFSGGEALKKRVWHDFK
BGC0000369_AHZ20774.1_1541_mod2_gln      HQDPAYLVKTIQQENVTLLQLVPSLLEIILGEPKFSQCSSLRLVFSGGEALKKRVWHDFK
                                         * * **: : * :*::* :*:*****:::: :   . * **: **.*****   :   : 

O33743_A2_6__gln                         ETQQAQLINLYGPTETTIDATYWPCPRQQEYSAIPIGKPIDNVRLYVVNASNQLQPVGVA
AEU11006.1_2653_mod1_gln                 SKLNVKLHNLYGPTEACIDATFWNCQQHKYVQVVPIGRPISNTQVYILDQYLQPVPIGVP
AHZ20774.1_1541_mod2_gln                 DNLAIPLINLYGPAETTIDVAVHDCRENENADIIPIGEPVTNTKLYVLNSHLQPVPVGTP
BGC0000369_AHZ20774.1_1541_mod2_gln      DNLAIPLINLYGPAETTIDVAVHDCRENENADIIPIGEPVTNTKLYVLNSHLQPVPVGTP
                                         ..    * *****:*: **.:   * .::  . :***.*: *.::*:::   *  *:*..

O33743_A2_6__gln                         GELCIAGDGLARGYWQREELTKASFVDNPF--EPGGTMYRTGDMVRYLPDGHIEYLGRID
AEU11006.1_2653_mod1_gln                 GELHIGGAGLARGYLNRPELTQEKFIPNPLSGSKGERLYKTGDLARYLPDGNIEYLGRID
AHZ20774.1_1541_mod2_gln                 GELFVSGYQLARGYWNAPGMTGERFLPDPF--VEGERMYRTGDRARYLPDGTIEFLGRAD
BGC0000369_AHZ20774.1_1541_mod2_gln      GELFVSGYQLARGYWNAPGMTGERFLPDPF--VEGERMYRTGDRARYLPDGTIEFLGRAD
                                         *** :.*  ***** :   :*   *: :*:    *  :*:*** .****** **:*** *

O33743_A2_6__gln                         HQVKIRGHRIELGEIEATLLQHEAVKAVVVMARQDGKGQNSLYA
AEU11006.1_2653_mod1_gln                 NQVKIRGFRIELGEIEAVLRQHEGVQTSCVIAREDIPGNKRLVA
AHZ20774.1_1541_mod2_gln                 QQVKIRGFRIETAEIVAALEQQTWVNRAVVKAITTPGKPNRLIA
BGC0000369_AHZ20774.1_1541_mod2_gln      QQVKIRGFRIETAEIVAALEQQTWVNRAVVKAITTPGKPNRLIA
                                         :******.*** .** *.* *:  *:   * *       : * *
