CLUSTAL W multiple sequence alignment


AHZ34233.1_1522_mod2_gln                 LADAATQERFADNTLQLVNLDASTWAAQSAENPVVPGLNADHLAYVIYTSGSTGTPKGVM
BGC0000463_AGM14934.1_2646_mod3_gln      LVDAGSRGRFADSLVPRLDLDQPAWAGQSPDNPQVPGLGARHLAYVIYTSGSTGTPKGVM
AHZ34232.1_2599_mod3_gln                 LVQTATRKLLDEERTLRVDLDNNIWGAQSIDNPQIVGMNPDHLAYVIYTSGSTGTPKGVM
                                         *.::.::  : :.    ::**   *..** :** : *:.. *******************

AHZ34233.1_1522_mod2_gln                 VEHRGLCNLVQWSSQLILPTPEGALLHKTPVSFDASVWELFWPLCAGLRLVLARPDGHRD
BGC0000463_AGM14934.1_2646_mod3_gln      VEHRSLCNLVHWSSRLIAPTVEGALLHKTPVSFDASVWELFWPLCAGLRLVLARPDGQRD
AHZ34232.1_2599_mod3_gln                 VEHRSVGNLVHWSSQVIPLKPETALLHKTPISFDASVWELFWPLCAGLPLVLARPDGHRD
                                         ****.: ***:***::*  . * *******:***************** ********:**

AHZ34233.1_1522_mod2_gln                 PAYLAQLIIERQVSVVQFVPALLQQFLELEESSQCNSLTDIVCGGGELTEALARQVRQRM
BGC0000463_AGM14934.1_2646_mod3_gln      PAYLAALIQRQRVSVVQFVPALLQQFLALEASAACDSLTDIVCGGGELTTALLQQVRERL
AHZ34232.1_2599_mod3_gln                 PAYLMRLIRDQKASVVQFVPALLQQFLELEEISQCTSLTDIVCGGGELTIALAERVRQRL
                                         ****  **  ::.************** **  : * ************* ** .:**:*:

AHZ34233.1_1522_mod2_gln                 PGVRLHNVYGPTETTVDCSVWTLEPQDSVPDSALPIGRPISNTRLYVLDACDQPVPQGVV
BGC0000463_AGM14934.1_2646_mod3_gln      PQVRLHNVYGPTEATVDCSVWTLEPGQALPVSAPPIGRPIANTRLYVLDRNGLPVPRGVV
AHZ34232.1_2599_mod3_gln                 PWARLHNVYGPTETTVDSSAWTLEPHEPVPDSALPIGRPISNTRMYVLDEYDQLVPQGVI
                                         * .**********:***.*.***** :.:* ** ******:***:****  .  **:**:

AHZ34233.1_1522_mod2_gln                 GQLHIGGAGVARGYLNLPHMQAERFIDSPFVAGDRLYRSGDLVRQRADGTLEFLGRNDFQ
BGC0000463_AGM14934.1_2646_mod3_gln      GELHIGGVGVARGYLGLPELDAERFGDSPFVVGERLYRSGDLVRRRADGELEFLGRDDFQ
AHZ34232.1_2599_mod3_gln                 GQLHIGGSGVTRGYLNLPQFQAERFIDSPFVAGDRLYRTGDLVAQRADGNLDFLGRNDDQ
                                         *:***** **:****.**.::**** *****.*:****:**** :**** *:****:* *

AHZ34233.1_1522_mod2_gln                 VKLHGLRIELGEIEARLATHPAIREAAVLLHNE-----RLVA
BGC0000463_AGM14934.1_2646_mod3_gln      VKLHGLRIELGEIEACLASHPAIREVAVLLRGE-----RLVA
AHZ34232.1_2599_mod3_gln                 VKLYGLRIELGEIQACLTRYPGIQQAVVLARDEQPGGQRLVA
                                         ***:*********:* *: :*.*::..** :.*     ****
