CLUSTAL W multiple sequence alignment


BGC0000449_AHF21228.1_12993_mod10_glu    VAYLSLSLPSTVQAVVLD------DE--DVQAQLNVQDASNLIPV-VGPHNLAYMIYTSG
O68006_A4_glu                            -----------CAAGDVDPGEAYTGDIIRIDQTGQ-NDHVENLKHDIKPQHLAYVIYTSG
AHF21228.1_12993_mod10_glu               VAYLSLSLPSTVQAVVLD------DE--DVQAQLNVQDASNLIPV-VGPHNLAYMIYTSG
P27206_A1_glu                            ------LTESKVAAPEAD------AELIDLDQAIE-EGAEESLNADVNARNLAYIIYTSG
Q70KJ7_A1_glu                            ------LTEAGIQAPAAD------AERIDFDEAVQYETAADGVST--QSDRLAYIIYTSG
                                                      *   *       :   .:   : :   : :     . .***:*****

BGC0000449_AHF21228.1_12993_mod10_glu    TTGQPKGVMIEQGSVSNLVDALSERVYSRYEQPLHVAWLSAFVFDASVKQIFASLLLGHT
O68006_A4_glu                            STGKPKGVMIEHHSVNNLVHGLNERIYQHLDAHLNVALVAPYIFDASVKQIFAALLFGHT
AHF21228.1_12993_mod10_glu               TTGQPKGVMIEQGSVSNLVDALSERVYSRYEQPLHVAWLSAFVFDASVKQIFASLLLGHT
P27206_A1_glu                            TTGRPKGVMIEHRQVHHLVESLQQTIYQSPTQTLPMAFLPPFHFDASVKQIFASLLLGQT
Q70KJ7_A1_glu                            TTGRPKGVMIEHRQVHHLVQSLQQEIYQCGEQTLRMALLAPFHFDASVKQIFASLLLGQT
                                         :**:*******: .* :**..*.: :*.     * :* :..: **********:**:*:*

BGC0000449_AHF21228.1_12993_mod10_glu    LHVVSRDVSLNGEQLVAYYRTHRIDLSDGTPAHLHILNENVNVTEAPGV--KHYLIGGEA
O68006_A4_glu                            LCIVPRETAWDAMSLIEYYSKNNINVSDMTPAHLNML-AYVDKTELE-FDVKELIVGGDA
AHF21228.1_12993_mod10_glu               LHVVSRDVSLNGEQLVAYYRTHRIDLSDGTPAHLHILNENVNVTEAPGV--KHYLIGGEA
P27206_A1_glu                            LYIVPKKTVTNGAALTAYYRKNSIEATDGTPAHLQML---AAAGDFEGLKLKHMLIGGEG
Q70KJ7_A1_glu                            LYIVPKTTVTNGSALLDYYRQNRIEATDGTPAHLQMM---VAAGDVSGIELRHMLIGGEG
                                         * :*.: .  :.  *  **  : *: :* *****:::   .   :   .  :. ::**:.

BGC0000449_AHF21228.1_12993_mod10_glu    LSVQLVNGF--LHKWSGYRPVITNVYGPTETTVDATAYTLEDVEALNVLLEKGEHTVSIG
O68006_A4_glu                            LTPDVIGGL--FHKFPNLSCNITNVYGPTECCVDAASHQIESGKV------PQTPSIPIG
AHF21228.1_12993_mod10_glu               LSVQLVNGF--LHKWSGYRPVITNVYGPTETTVDATAYTLEDVEALNVLLEKGEHTVSIG
P27206_A1_glu                            LSSVVADKLLKLFKEAGTAPRLTNVYGPTETCVDASVHPVIPENAV------QSAYVPIG
Q70KJ7_A1_glu                            LSAAVAEQLMALFHQSGRTPRLTNVYGPTETCVDASVHQVSADNGMN----QQAAYVPIG
                                         *:  :   :  :.: ..    :********  ***: : :   :            :.**

BGC0000449_AHF21228.1_12993_mod10_glu    TPIANQSVYILNTQQQLVPIGIVGELYIGGAGVGRGYLNLPQLTAEKFLPNPFALSEAGE
O68006_A4_glu                            RPLLNTSIYIVDKELRPLPVGIAGELCIAGEGVARGYVNRPELTAEKFVDHPFEPGK---
AHF21228.1_12993_mod10_glu               TPIANQSVYILNTQQQLVPIGIVGELYIGGAGVGRGYLNLPQLTAEKFLPNPFALSEAGE
P27206_A1_glu                            KALGNNRLYILDQKGRLQPEGVAGELYIAGDGVGRGYLHLPELTEEKFLQDPFVPGD---
Q70KJ7_A1_glu                            KPLGNARLYILDKHQRLQPDGTAGELYIAGDGVGRGYLNLPDLTAEKFLQDPFNGSG---
                                          .: *  :**:: . :  * * .*** *.* **.***:: *:** ***: .**  .    

BGC0000449_AHF21228.1_12993_mod10_glu    APDAYIHRMYRTGDLARWLPDGSIEYLGRIDHQVKIRGYRIELGEVEAQLLTVDGIQKAV
O68006_A4_glu                            -------KMYKTGDLAMWLPDGQIEFLGRADHQVKIRGYRIELGEVEQQLLTHEKIKEAA
AHF21228.1_12993_mod10_glu               APDAYIHRMYRTGDLARWLPDGSIEYLGRIDHQVKIRGYRIELGEVEAQLLTVDGIQKAV
P27206_A1_glu                            -------RMYRTGDVVRWLPDGTIEYLGREDDQVKVRGYRIELGEIEAVIQQAPDVAKAV
Q70KJ7_A1_glu                            -------RMYRTGDMARWLPDGTIEYIGREDDQVKVRGYRIELGEIETVLRKAPGAAQAV
                                                :**:***:. ***** **::** *.***:*********:*  :       :*.

BGC0000449_AHF21228.1_12993_mod10_glu    VTAWENEDGHKDLCA
O68006_A4_glu                            VIAGKDQNGNSYLCA
AHF21228.1_12993_mod10_glu               VTAWENEDGHKDLCA
P27206_A1_glu                            VLARPDEQGNLEVCA
Q70KJ7_A1_glu                            VLARPDQQGSLDVCA
                                         * *  :::*   :**
