CLUSTAL W multiple sequence alignment


BGC0000398_AFH75328.1_1544_mod2_glu      LVQQSTRHLLQGPGLALLDFDHAAWHHQPGHDPQVPGLNVSHLAYVIYTSGSTGTPKGVM
AFZ61501.1_1515_mod2_glu                 LVHAATRDLPGDVSIPVIDFDHCAWSQAPIGNPLVPGLSVANLAYVMYTSGSTGTPKGVM
                                         **: :**.*  . .:.::****.** : *  :* ****.*::****:*************

BGC0000398_AFH75328.1_1544_mod2_glu      VEHRGLGNLMHWGSQLCPQSGGGTLLQKAPFSFDGSVWELFWPLVTGMRLLLARPGGQRE
AFZ61501.1_1515_mod2_glu                 IEHRGLGNLMHWGSQLCPNAEGGALLQRAPFSFDGSVWELFWPLTNGMRLVLARPDGHRE
                                         :*****************:: **:***:****************..****:****.*:**

BGC0000398_AFH75328.1_1544_mod2_glu      PTYLAQLVVEQQVTMVKFVPAMLLQFLQLEESGQCQSLTDVFCGGGELTEAIARLFRQRL
AFZ61501.1_1515_mod2_glu                 PAYLAQVIREQQISVIKFVPAMLQQFLELEESALCTSLTDVLCGGGELTEALARGVQARL
                                         *:****:: ***::::******* ***:****. * *****:*********:** .: **

BGC0000398_AFH75328.1_1544_mod2_glu      PRARLHNVYGPTEATVDSTAWTLEPGAAIPAVQLPIGRAITNTRLYVLDTHDQPVPRGVS
AFZ61501.1_1515_mod2_glu                 PKVRLHNVYGPTEATVDSSAWTLEPGAPVPALQLPIGRAINNTRLYVLDEHDRPTPMGVS
                                         *:.***************:********.:**:********.******** **:*.* ***

BGC0000398_AFH75328.1_1544_mod2_glu      GQLHIGGVGVARGYLGLAQLQAERFIDSPFVAGDRLYRTGDLVRYGDDGNLEFLGRNDFQ
AFZ61501.1_1515_mod2_glu                 GQLHIGGVGVARGYLGLEQMTAERFIDSPFVDGDRLYRTGDLVRYLPDGNLEFLGRNDFQ
                                         ***************** *: ********** *************  *************

BGC0000398_AFH75328.1_1544_mod2_glu      IKLRGLRLEPGEIEARLASHPAVREVAVLMRSERLVA
AFZ61501.1_1515_mod2_glu                 VKLRGVRLELGEIESRLMAHQALREVAVLIRDERLVA
                                         :****:*** ****:** :* *:******:*.*****
