CLUSTAL W multiple sequence alignment


Q70JX1_A1_glu                            LAQPGLSVSGFSGETLEVSLSALTGETETGAVSEEADSNSLAYIIYTSGSTGTPKGVAVE
P39847_A1_glu                            LTQPGCSAPNFSGETLEVDMTSLECEEVKRHVSASVSDGSLAYVIYTSGSTGQPKGVAVE
O87606_A1_glu                            LTQPGLKAPVFSGKTLEVDMTSLANEESEYHSLHQADSDSLAYVIYTSGSTGQPKGVAVE
P39845_A1_glu                            LTQPGCSAPNFSGETLEVDMTSLASEKAENHEFTPADGGSLAYVIYTSGSTGQPKGVAVE
O30981_A1_5__glu                         LTQPGLKAPVFSGKTLEVDMTALANEESECHSLHQADSDSLAYVIYTSGSTGRPKGVAVE
                                         *:*** ... ***:****.:::*  *         ....****:******** *******

Q70JX1_A1_glu                            HRQAAAFLSGMQGQFPLTEEDVIVLKSSFSFDASIWQLFWWTMSGASVYLLPAGWEKDPV
P39847_A1_glu                            HRQAVSFLTGMQHQFRLSEDDIVMVKTSFSFDASVWQLFWWALSGASAYLLPPGWEKDSA
O87606_A1_glu                            HLQAVSFLTGMQMQFPLEEDDIIMMKTSFSFDASVWQLFWWTLSGASAYLLPSGWEKDPA
P39845_A1_glu                            HRQAVSFLTGMQHQFPLSEDDIVMVKTSFSFDASVWQLFWWSLSGASAYLLPPGWEKDSA
O30981_A1_5__glu                         HRQAVSFLTGMQMQFPLEEDDIIMMKTSFSFDASVWQLFWWTLSGASAYLLPSGWEKDPA
                                         * **.:**:*** ** * *:*::::*:*******:******::****.****.*****..

Q70JX1_A1_glu                            RMIKAFASEKVTTAHFIPAMVNSFLDALETEPAETRTRLGRTLTRVFAGGEALSPLTAAR
P39847_A1_glu                            LIVQAIHQENVTTAHFIPAMLNSFLDQAEIERLSDRT----SLKRVFAGGEPLAPRTAAR
O87606_A1_glu                            LMVKAIREEGVTTAHFIPAMLNSFLDQAEIE--APR-----SLKRVFAGGEPLAPHTAAR
P39845_A1_glu                            LIVQAIHQENVTTAHFIPAMLNSFLDQAEIERLSDRT----SLKRVFAGGEPLAPRTAAR
O30981_A1_5__glu                         LMVKAIREEGVTTAHFIPAMLNSFLDQAEIE--APR-----SLKRVFAGGEPLAPHTAAR
                                          :::*: .* **********:*****  * *    *     :*.*******.*:* ****

Q70JX1_A1_glu                            FADLLPETVLIHGYGPTEATVDAAFYVCDRKRDSGRTRLPIGKPVPGARLYVLDSGGTIQ
P39847_A1_glu                            FASVLPQVSLIHGYGPTEATVDAAFYVLDPERDRDRLRIPIGKPVPGARLYVLDPHLAVQ
O87606_A1_glu                            FASLLPETSLVHGYGPTEATVDAAFYACDPELDKDRLRLPIGKPVPGARLYVLDPHLAVQ
P39845_A1_glu                            FASVLPQVSLIHGYGPTEATVDAAFYVLDPERDRDRLRIPIGKPVPGARLYVLDPHLAVQ
O30981_A1_5__glu                         FASLLPETSLVHGYGPTEATVDAAFYACDPELDKNRLRLPIGKPVPGARLYVLDPHLAVQ
                                         **.:**:. *:***************. * : * .* *:***************.  ::*

Q70JX1_A1_glu                            PAGVAGELYIAGTGVARGYLNRPELTEERFLDDPFYPGERMYQTGDIARWTEDGLVEWLG
P39847_A1_glu                            PSGVAGELYIAGAGVARGYLNRPALTEERFLEDPFYLGERMYKTGDVARWLPDGNVEFLG
O87606_A1_glu                            PVGVAGELYIAGAGVARGYLNRPELTEERFLDDPFYPGERMYKTGDLAHWLPDGQVEFLG
P39845_A1_glu                            PSGVAGELYIAGAGVARGYLNRPALTEERFLEDPFYPGERMYKTGDVARWLPDGNVEFLG
O30981_A1_5__glu                         PVGVAGELYIAGAGVARGYLNRPELTEERFLDDPFYPGERMYKTGDLARWLPDGQVEFLG
                                         * **********:********** *******:**** *****:***:*:*  ** **:**

Q70JX1_A1_glu                            RSDGQVKVRGYRIEPGEIEAAIRRIDGIREAAVTARNEHGETALYA
P39847_A1_glu                            RTDDQVKIRGYRIEPGEIEAALRSIEGVREAAVTVRTDSGEPELCA
O87606_A1_glu                            RLDDQVKIRGYRIEPGECEAALRSIEGVRDAAVTVRTESGEAELCA
P39845_A1_glu                            RTDDQVKIRGYRIEPGEIEAALRSIEGVREAAVTVRTDSGEPELCA
O30981_A1_5__glu                         RLDDQVKIRGYRIEPGEIEAALRSIEGVREAAVTVRTESGEAELCA
                                         * *.***:********* ***:* *:*:*:****.*.: **. * *
