CLUSTAL W multiple sequence alignment


Q50E73_A5_10__gly                        LTTEDISARIPGGS---HVVLDSEQVTGELHDHP----ATSPAGRG--------NPAGPA
EWS95124_9_mod1_gly                      ------------------------------------------------------HSGNPA
BGC0000439_AHH53506.1_5177_mod5_gly      VTTDEWAARFAGWDGP-LVRVDR---------------ADDTRCERGAPPIVPTRPDTAA
AHH53507.1_5197_mod5_gly                 VTTGLLAERVPARENTDVLLLDDPDVAEAVEAEP----AELPPMPV--------AADATA
Q9L8H4_A2_5__gly                         LTDTRTEQHLPADADTRRLALDSAEVRALLADCP----DTDPAEEGVT-----PAPGSAA
BGC0000439_AHH53507.1_5197_mod5_gly      VTTGLLAERVPARENTDVLLLDDPDVAEAVEAEP----AELPPMPV--------AADATA
Q45R83_A3_10__gly                        ITTTDLARRLPPVPAP-LLVLDDPATAARLAATTATALAEDPREQNG------EWGEELA
AHH53506.1_5177_mod5_gly                 VTTDEWAARFAGWDGP-LVRVDR---------------ADDTRCERGAPPIVPTRPDTAA
                                                                                                    *

Q50E73_A5_10__gly                        YVIYTSGSTGQPKGVVVPSAALVNFLADMVPRLGLRGGDRLLSVTTVGFDIAALELFVPL
EWS95124_9_mod1_gly                      YIIYTSGSTGAPKGTVVTGENLVNLLSDFRSRLSFGAEDRLLAVTTFGFDISNLELLLPL
BGC0000439_AHH53506.1_5177_mod5_gly      YVIYTSGSTGRPKGVVVTEGGLRNFLLDMAERAGLTRASRLLAVTTVAFDIAGLELFGPL
AHH53507.1_5197_mod5_gly                 YVIYTSGSTGRPKGVVVTRANLGNFLSDMRGRVGLGAEDRLLAVTTIGFDIAALELFLPL
Q9L8H4_A2_5__gly                         YVIYTSGSTGRPKGVVVPHSALVNFVTAMRRQAPLRPQERLLAVTTVAFDIAALELYHPL
BGC0000439_AHH53507.1_5197_mod5_gly      YVIYTSGSTGRPKGVVVTRANLGNFLSDMRGRVGLGAEDRLLAVTTIGFDIAALELFLPL
Q45R83_A3_10__gly                        YTIYTSGSTGRPKGVMVTRSAVANFLADMNERLELGPGDRLLAVTTVSFDIAVLELLAPL
AHH53506.1_5177_mod5_gly                 YVIYTSGSTGRPKGVVVTEGGLRNFLLDMAERAGLTRASRLLAVTTVAFDIAGLELFGPL
                                         * ******** ***.:*.   : *::  :  :  :   .***:***..***: ***  **

Q50E73_A5_10__gly                        LSGATVVLADGETVRDPALARQTCEDHGVTMVQATPSWWHGMLADA-GDS--LRGVHAVV
EWS95124_9_mod1_gly                      ISGGRVVLASKETSQDPNALGGLIAASGATVMQATPALWQTLLASGDPEG--LRQVKVLV
BGC0000439_AHH53506.1_5177_mod5_gly      LRGGRVVLAGEDVTRDPAAVLDLCVRHGVTVVQATPSWWRGV-VEQNRERDVLPGIRVLV
AHH53507.1_5197_mod5_gly                 ASGARVVLAAPDVVRDPAAVARLCGRAGITAIQATPSWWRAVVQDGESTR--LGLGAALV
Q9L8H4_A2_5__gly                         LSGAAVVLAPKEAVPQPSAVLDLIARHGVTTVQGTPSLWQ-LLVGHDAEA--LRGLRMLV
BGC0000439_AHH53507.1_5197_mod5_gly      ASGARVVLAAPDVVRDPAAVARLCGRAGITAIQATPSWWRAVVQDGESTR--LGLGAALV
Q45R83_A3_10__gly                        LTGGTVVLADATTQRDPAAVRSLCAREGVTVIQATPSWWHAMAVDGGLD---LTALRVLV
AHH53506.1_5177_mod5_gly                 LRGGRVVLAGEDVTRDPAAVLDLCVRHGVTVVQATPSWWRGV-VEQNRERDVLPGIRVLV
                                           *. ****   .  :*          * * :*.**: *: :          *     :*

Q50E73_A5_10__gly                        GGEALSPGLRDALTRGARS-----VTNMYGPTETTIWSTSAGQAAG-----DSAPPSIGT
EWS95124_9_mod1_gly                      GGEALPRPLAGALRDSARE-----VTNVYGPTETTIWSTAAFLDEE-----NADRPPIGL
BGC0000439_AHH53506.1_5177_mod5_gly      GGEALPASLATELVASAAS-----VTNLYGPTETTIWSTVDEV--------GPGAPTIGR
AHH53507.1_5197_mod5_gly                 GGEALPADLARALTGVAGS-----VTNVYGPTETTIWSTAAPVTGE-----PDTRPAIGV
Q9L8H4_A2_5__gly                         GGEALPLSLAEALRALTDD-----LVNLYGPTETTIWSTAAEL-AG-----GTGAAPIGR
BGC0000439_AHH53507.1_5197_mod5_gly      GGEALPADLARALTGVAGS-----VTNVYGPTETTIWSTAAPVTGE-----PDTRPAIGV
Q45R83_A3_10__gly                        GGEALPPALARTLLEPGRAPLGDYLLNLYGPTETTVWSTVARITADSLEAHGGAVPT-GT
AHH53506.1_5177_mod5_gly                 GGEALPASLATELVASAAS-----VTNLYGPTETTIWSTVDEV--------GPGAPTIGR
                                         *****.  *   *           : *:*******:***                .. * 

Q50E73_A5_10__gly                        PILNTRVYVLDAALCVVPPGVAGELYIAGDGLARGYLGRAGLTAERFVACPFG-APGERM
EWS95124_9_mod1_gly                      PLANTRAYVLDSALRPVPAGVAGELYLAGAGVARGYLNRPALTAQRFVADPFG-PAGGRM
BGC0000439_AHH53506.1_5177_mod5_gly      PIGNTQVYVLDAALEPVPPGVPGELYLAGAGLARGYAGRPGLTANRFVACPFG-PAGARM
AHH53507.1_5197_mod5_gly                 PIGNTSVYVLDERLAPVAVGVVGELYIAGDGVARGYRGEPGMTAERFVACPFG-GAGTRM
Q9L8H4_A2_5__gly                         PIANTRVYVLDDGLQPVAPGVVGELYIAGAGLARGYLDRPALTAERFPADPYGLEPGGRM
BGC0000439_AHH53507.1_5197_mod5_gly      PIGNTSVYVLDERLAPVAVGVVGELYIAGDGVARGYRGEPGMTAERFVACPFG-GAGTRM
Q45R83_A3_10__gly                        PIARTAAYVLDAALRPVPDGVPGELYLAGAGLARGYLGRPGMTAERFVACPFG-EPGERM
AHH53506.1_5177_mod5_gly                 PIGNTQVYVLDAALEPVPPGVPGELYLAGAGLARGYAGRPGLTANRFVACPFG-PAGARM
                                         *: .* .****  *  *. ** ****:** *:**** ....:**:** * *:*  .* **

Q50E73_A5_10__gly                        YRTGDLVRWRVDGALEFVGRADDQVKVRGFRVELGEVEGAVAAHPDVVRAVVVVREDRPG
EWS95124_9_mod1_gly                      YRTGDLVRRHADGNLEFLDRVDHQVKIRGFRIELGEIEGALNQHPAVARAAVVVHEDQAG
BGC0000439_AHH53506.1_5177_mod5_gly      YRTGDLATWRADGRLRYLGRSDDQVKLRGFRIELGEVESAVERHPRVRAAAVAVRETQAG
AHH53507.1_5197_mod5_gly                 YRTGDLVRWLPDGTLAYVGRADDQVKLRGFRIELGEIETVLRELPDIAGAAVMVREDRPG
Q9L8H4_A2_5__gly                         YRTGDLVRWNPDGELEFVGRADHQVKVRGFRIEPGEIEKVLTDHPDIAQAAVVVREDQPG
BGC0000439_AHH53507.1_5197_mod5_gly      YRTGDLVRWLPDGTLAYVGRADDQVKLRGFRIELGEIETVLRELPDIAGAAVMVREDRPG
Q45R83_A3_10__gly                        YRTGDLARWRADGNLEHLGRTDDQVKVRGFRIELGEVERALTQAHGVGRAAAAVHPDAAG
AHH53506.1_5177_mod5_gly                 YRTGDLATWRADGRLRYLGRSDDQVKLRGFRIELGEVESAVERHPRVRAAAVAVRETQAG
                                         ******.    ** * .:.* *.***:****:* **:* .:     :  *.. *:   .*

Q50E73_A5_10__gly                        DHRLVA
EWS95124_9_mod1_gly                      EKRLVA
BGC0000439_AHH53506.1_5177_mod5_gly      GRTLVA
AHH53507.1_5197_mod5_gly                 DRRLAG
Q9L8H4_A2_5__gly                         DARLVA
BGC0000439_AHH53507.1_5197_mod5_gly      DRRLAG
Q45R83_A3_10__gly                        SARLVG
AHH53506.1_5177_mod5_gly                 GRTLVA
                                            *..
