CLUSTAL W multiple sequence alignment


BGC0000431_EFE73313.1_2638_mod3_gly      LTSRATDAALGTGTGTVRIVVDDPRAVSALTGLDAGPVDDAERTSPLLPSHPAYVIYTSG
EFE73313.1_2638_mod3_gly                 LTSRATDAALGTGTGTVRIVVDDPRAVSALTGLDAGPVDDAERTSPLLPSHPAYVIYTSG
EWS95124_9_mod1_gly                      ---------------------------------HSG--------------NPAYIIYTSG
                                                                          .:*              :***:*****

BGC0000431_EFE73313.1_2638_mod3_gly      STGRPKGVTVPHRAVTNFLAAMDDRCPLDERDRLLAVTTVAFDIHVLELYLPLLAGASVA
EFE73313.1_2638_mod3_gly                 STGRPKGVTVPHRAVTNFLAAMDDRCPLDERDRLLAVTTVAFDIHVLELYLPLLAGASVA
EWS95124_9_mod1_gly                      STGAPKGTVVTGENLVNLLSDFRSRLSFGAEDRLLAVTTFGFDISNLELLLPLISGGRVV
                                         *** ***..*. . :.*:*: : .* .:. .********..***  *** ***::*. *.

BGC0000431_EFE73313.1_2638_mod3_gly      VAPRAAARDPRLLVALAERLDVTVMQATPTLWQAVLDE-DPTALKGARILVGGEALPSSL
EFE73313.1_2638_mod3_gly                 VAPRAAARDPRLLVALAERLDVTVMQATPTLWQAVLDE-DPTALKGARILVGGEALPSSL
EWS95124_9_mod1_gly                      LASKETSQDPNALGGLIAASGATVMQATPALWQTLLASGDPEGLRQVKVLVGGEALPRPL
                                         :*.: :::**. * .*    ..*******:***::* . ** .*: .::******** .*

BGC0000431_EFE73313.1_2638_mod3_gly      SERMLAAPGRATNLYGPTEATVWATTAELTAGEQGSVASIGRPLWNTRAYVLDDRMQPVH
EFE73313.1_2638_mod3_gly                 SERMLAAPGRATNLYGPTEATVWATTAELTAGEQGSVASIGRPLWNTRAYVLDDRMQPVH
EWS95124_9_mod1_gly                      AGALRDSAREVTNVYGPTETTIWSTAAFLDE-ENADRPPIGLPLANTRAYVLDSALRPVP
                                         :  :  :. ..**:*****:*:*:*:* *   *:.. ..** ** ********. ::** 

BGC0000431_EFE73313.1_2638_mod3_gly      AGVAGELYLTGDQLARGYQGRPDLTAERFLACPFGAPGERMYRTGDLVRWSPDGSLEYLT
EFE73313.1_2638_mod3_gly                 AGVAGELYLTGDQLARGYQGRPDLTAERFLACPFGAPGERMYRTGDLVRWSPDGSLEYLT
EWS95124_9_mod1_gly                      AGVAGELYLAGAGVARGYLNRPALTAQRFVADPFGPAGGRMYRTGDLVRRHADGNLEFLD
                                         *********:*  :**** .** ***:**:* ***..* **********  .**.**:* 

BGC0000431_EFE73313.1_2638_mod3_gly      RVDDQVKIRGFRIELGEIEAGLTAHAEVTQAAVVARDDAHGSRQLVA
EFE73313.1_2638_mod3_gly                 RVDDQVKIRGFRIELGEIEAGLTAHAEVTQAAVVARDDAHGSRQLVA
EWS95124_9_mod1_gly                      RVDHQVKIRGFRIELGEIEGALNQHPAVARAAVVVHEDQAGEKRLVA
                                         ***.***************..*. *. *::****.::*  *.::***
