CLUSTAL W multiple sequence alignment


BGC0000431_EFE73313.1_2638_mod3_gly      LTSRAT----DAALGTGTGTVRIVVDDPR---AVSALTGLDAGPVDDAERTSPLLPSHPA
CCA29202.1_393_mod1_gly                  LTDAACIQKLEAGLHRQTAQSPIVLDSEEVQHALQAMGSEDLG----ANSTSRAL----A
EWS95124_9_mod1_gly                      ----------------------------------------HSG--------------NPA
EFE73313.1_2638_mod3_gly                 LTSRAT----DAALGTGTGTVRIVVDDPR---AVSALTGLDAGPVDDAERTSPLLPSHPA
                                                                                 . *                *

BGC0000431_EFE73313.1_2638_mod3_gly      YVIYTSGSTGRPKGVTVPHRAVTNFLAAMDDRCPLDERDRLLAVTTVAFDIHVLELYLPL
CCA29202.1_393_mod1_gly                  YVIYTSGTTGKPKGVAVEHQSFVNIATDISARLSFTPGDRILAVTTVAFDISTLELLMPL
EWS95124_9_mod1_gly                      YIIYTSGSTGAPKGTVVTGENLVNLLSDFRSRLSFGAEDRLLAVTTFGFDISNLELLLPL
EFE73313.1_2638_mod3_gly                 YVIYTSGSTGRPKGVTVPHRAVTNFLAAMDDRCPLDERDRLLAVTTVAFDIHVLELYLPL
                                         *:*****:** ***..*  . ..*: : :  * .:   **:*****..***  *** :**

BGC0000431_EFE73313.1_2638_mod3_gly      LAGASVAVAPRAAARDPRLLVALAERLDVTVMQATPTLWQAVLDE-DPTALKG----ARI
CCA29202.1_393_mod1_gly                  MRGGSLVVAEQADLLDPSKLLFLIEEVGVSVVQATPSLWQTIVPH-----LKGRKLAIRA
EWS95124_9_mod1_gly                      ISGGRVVLASKETSQDPNALGGLIAASGATVMQATPALWQTLLASGDPEGLRQ----VKV
EFE73313.1_2638_mod3_gly                 LAGASVAVAPRAAARDPRLLVALAERLDVTVMQATPTLWQAVLDE-DPTALKG----ARI
                                         : *. :.:* :    **  *  *    ..:*:****:***:::       *:      : 

BGC0000431_EFE73313.1_2638_mod3_gly      LVGGEALPSSLSERMLAAPGRATNLYGPTEATVWATTAELTAGEQGSVASIGRPLWNTRA
CCA29202.1_393_mod1_gly                  LCGGEALPPSLAGQLVASVIECWNVYGPTETTVWSTTFLLD--EHESRVLIGRPLANTQC
EWS95124_9_mod1_gly                      LVGGEALPRPLAGALRDSAREVTNVYGPTETTIWSTAAFLDE-ENADRPPIGLPLANTRA
EFE73313.1_2638_mod3_gly                 LVGGEALPSSLSERMLAAPGRATNLYGPTEATVWATTAELTAGEQGSVASIGRPLWNTRA
                                         * ****** .*:  :  :  .  *:*****:*:*:*:  *   *: .   ** ** **:.

BGC0000431_EFE73313.1_2638_mod3_gly      YVLDDRMQPVHAGVAGELYLTGDQLARGYQGRPDLTAERFLACPF-GAPGERMYRTGDLV
CCA29202.1_393_mod1_gly                  YVLDAEQQPLPPGVPGELYIGGQGLARSYLNAPELTATRFVPNPLPGTPGGRLYRTGDLV
EWS95124_9_mod1_gly                      YVLDSALRPVPAGVAGELYLAGAGVARGYLNRPALTAQRFVADPF-GPAGGRMYRTGDLV
EFE73313.1_2638_mod3_gly                 YVLDDRMQPVHAGVAGELYLTGDQLARGYQGRPDLTAERFLACPF-GAPGERMYRTGDLV
                                         ****   :*: .**.****: *  :**.* . * *** **:. *: *..* *:*******

BGC0000431_EFE73313.1_2638_mod3_gly      RWSPDGSLEYLTRVDDQVKIRGFRIELGEIEAGLTAHAEVTQAAVVA-RDDAHGSRQ---
CCA29202.1_393_mod1_gly                  RYLPCGNLEFFGRNDFQVKLRGHRIELGEIESALKQHPTVEHSLVVVMRHGAHGSSENQF
EWS95124_9_mod1_gly                      RRHADGNLEFLDRVDHQVKIRGFRIELGEIEGALNQHPAVARAAVVV-HEDQAGEKR---
EFE73313.1_2638_mod3_gly                 RWSPDGSLEYLTRVDDQVKIRGFRIELGEIEAGLTAHAEVTQAAVVA-RDDAHGSRQ---
                                         *  . *.**:: * * ***:**.********..*. *. * :: **. :..  *. .   

BGC0000431_EFE73313.1_2638_mod3_gly      LVA
CCA29202.1_393_mod1_gly                  LVG
EWS95124_9_mod1_gly                      LVA
EFE73313.1_2638_mod3_gly                 LVA
                                         **.
