CLUSTAL W multiple sequence alignment


Q5DIV7_A4_horn                           LTHSHLLERLPIPEGLSCLSVDREEEWAGFPAHDPEVALHGDNLAYVIYTSGSTGMPKGV
Q5DIS7_A3_horn                           LTQRDVLERLPLPAGLASLAVDDPGEWQDRPEGAPEVDLAEENLAYVIYTSGSTGLPKGV
Q5DIV8_A2_6__horn                        LTHSHLLERLPIPEGLSCLSVDREEEWAGFPAHDPEVALHGDNLAYVIYTSGSTGMPKGV
Q5DIP4_A4_7__horn                        LSESQALVQLPVPAGVPALALDRL-DLLEHPAQAPQVEVHPANLAYVIYTSGSTGLPKGV
Q5DIP3_A2_horn                           LTQSHLLDRLPIPDGLSCLCLDREQEWAGFPAHDPEVALHGDNLAYVIYTSGSTGMPKGV
Q5DIS9_A2_6__horn                        LTQRDVLERLPLPAGLASLAVDDPGEWQDRPEGAPEVDLAEENLAYVIYTSGSTGLPKGV
                                         *:. . * :**:* *:..*.:*   :    *   *:* :   *************:****

Q5DIV7_A4_horn                           AVSHGPLIAHIVATGERYEMTPEDCELHFMSFAFDGSHEGWMHPLINGARVLIRDDSLWL
Q5DIS7_A3_horn                           AVSHGPLVSHIRATGERYETSPADCELHFMSFAFDGAHEGWMHPLINGARVLVRDDSIWL
Q5DIV8_A2_6__horn                        AVSHGPLIAHIVATGERYEMTPEDCELHFMSFAFDGSHEGWMHPLINGARVLIRDDSLWL
Q5DIP4_A4_7__horn                        AVSHGPLAMHIDAVGERYEMTPADRELHFMSFAFDGAHERWLTALGHGGSLLLRDDALWT
Q5DIP3_A2_horn                           AVSHGPLAAHIVATGERYEMTPADCELHFMSFAFDGSHEGWMHPLINGARVLIRDDSLWL
Q5DIS9_A2_6__horn                        AVSHGPLVSHIRATGERYETSPADCELHFMSFAFDGAHEGWMHPLINGARVLVRDDSIWL
                                         *******  ** *.***** :* * ***********:** *: .* :*. :*:***::* 

Q5DIV7_A4_horn                           PERTYAEMHRHGVTVGVFPPVYLQQLAEHAERDGNPPPVRVYCFGGDAVAQASYDLAWRA
Q5DIS7_A3_horn                           PEETYAQMHRHGVTIGVFPPVYLQQLAEHAERDGNPPPVRVYCFGGDAVPQASYELAWES
Q5DIV8_A2_6__horn                        PERTYAEMHRHGVTVGVFPPVYLQQLAEHAERDGNPPPVRVYCFGGDAVAQASYDLAWRA
Q5DIP4_A4_7__horn                        PEQTYAAMQRHGVTVAAFPPVYLQQLAEHAERDGNPPPVRIYCFGGDAVPVAGFELAKRA
Q5DIP3_A2_horn                           PEQTYAQMHRHGVTVAVFPPVYLQQLAEHAERDGNPPAARVYCFGGDAVAQASYDLAWRA
Q5DIS9_A2_6__horn                        PEETYAQMHRHGVTIGVFPPVYLQQLAEHAERDGNPPPVRVYCFGGDAVPQASYELAWES
                                         **.*** *:*****:..********************..*:********. *.::** .:

Q5DIV7_A4_horn                           LKPKYLFNGYGPTETVVTPLLWKARAGDACGAAYMPIGTLLGNRSGYILDGQLNLLPVGV
Q5DIS7_A3_horn                           LRPDYLFNGYGPTETVVTPLLWKARPQDPCGAAYAPIGTLLGRRRAYVLGADLDLLPLGL
Q5DIV8_A2_6__horn                        LKPKYLFNGYGPTETVVTPLLWKARAGDACGAAYMPIGTLLGNRSGYILDGQLNLLPVGV
Q5DIP4_A4_7__horn                        LKPRYIINGYGPTETVVTPLIWKAAMDTECGAAYAPIGSFVGERCGYVLDADLNPLPAGV
Q5DIP3_A2_horn                           LRPQYLFNGYGPTETVVTPLLWKARPDDPCGAAYMPIGTLLGNRSGYILDAQLNLLPVGV
Q5DIS9_A2_6__horn                        LRPDYLFNGYGPTETVVTPLLWKARPQDPCGAAYAPIGTLLGRRRAYVLGADLDLLPLGL
                                         *:* *::*************:***     ***** ***:::*.* .*:*..:*: ** *:

Q5DIV7_A4_horn                           AGELYLGGEGVARGYLERPALTAERFVPDPFGAPGSRLYRSGDLTRGRADGVVDYLGRVD
Q5DIS7_A3_horn                           AGELYLGGEGVARGYLDRPALTAERFVPDPYGN-GERVYRSGDLTRARADGLVDYLGRVD
Q5DIV8_A2_6__horn                        AGELYLGGEGVARGYLERPALTAERFVPDPFGAPGSRLYRSGDLTRGRADGVVDYLGRVD
Q5DIP4_A4_7__horn                        AGELYLGGVGLARGYLQRPGLSAERFVANPFSRTGERLYRTGDLVRQREDGTFDYLGRID
Q5DIP3_A2_horn                           AGELYLGGEGVARGYLERPALTAERFVPDPFGAPGSRLYRSGDLTRGRADGVVDYLGRVD
Q5DIS9_A2_6__horn                        AGELYLGGEGVARGYLDRPALTAERFVPDPYGN-GERVYRSGDLTRARADGLVDYLGRVD
                                         ******** *:*****:**.*:*****.:*:.  *.*:**:***.* * ** .*****:*

Q5DIV7_A4_horn                           HQVKIRGFRIELGEIEARLREHPAVREAVVVAQPGAVGQQLVG
Q5DIS7_A3_horn                           HQVKIRGFRIELGEIEARLLEQECVREAVVLARDGANGKQLVG
Q5DIV8_A2_6__horn                        HQVKIRGFRIELGEIEARLREHPAVREAVVVAQPGAVGQQLVG
Q5DIP4_A4_7__horn                        NQVKVRGFRIELGEIEARLQDAGEVREAVVVARDAASGKQLLG
Q5DIP3_A2_horn                           HQVKIRGFRIELGEIEARLREQAAVREAVVVAQAGASGQQLVG
Q5DIS9_A2_6__horn                        HQVKIRGFRIELGEIEARLLEQECVREAVVLARDGASGKQLVG
                                         :***:************** :   ******:*: .* *:**:*
