CLUSTAL W multiple sequence alignment


Q93N86_A1_7__hpg|hpg2cl                  LCSRSTRGAVPEDTPVSPLVLDD---LTAKGE-TPSPVPCAADDIAYVMYTSGSSGTPKG
Q8KLL5_A1_4__hpg|hpg2cl                  VCRAANRAAVLDG-GLDPIVLDDPEIRRAVAECARPSVQVSADDLAYVMYTSGSTGTPKG
Q8KLL5_A1_hpg|hpg2cl                     VCRAANRAAVLDG-GLDPIVLDDPEIRRAVAECARPSVQVSADDLAYVMYTSGSTGTPKG
Q93N89_A1_1__hpg|hpg2cl                  ---------VLKN-STPAVTID--AVVEGAGD--ASSVALDGDDLAYVMYTSGSTGTPKG
Q93N87_A1_4__hpg|hpg2cl                  VCSERTRVVVPEDVPAPLVPLDEASILD--GE--PLSLPVAGGDIAYVMYTSGSTGVPKG
Q93N87_A2_5__hpg|hpg2cl                  ---------VLED-SSPAVTID--AVVKGGGE--APSVAVTEGDLAYVMYTSGSTGTPKG
Q93N88_A1_3__hpg|hpg2cl                  ---------MVED-SAPVLTIDDPSVVTAEGE--PEVVETAGGDIAYVMYTSGSTGTPKG
Q93N89_A1_hpg|hpg2cl                     ---------VLKN-STPAVTID--AVVEGAGD--ASSVALDGDDLAYVMYTSGSTGTPKG
Q93N87_A2_hpg|hpg2cl                     ---------VLED-SSPAVTID--AVVKGGGE--APSVAVTEGDLAYVMYTSGSTGTPKG
Q93N87_A1_hpg|hpg2cl                     VCSERTRVVVPEDVPAPLVPLDEASILD--GE--PLSLPVAGGDIAYVMYTSGSTGVPKG
                                                  : ..     : :*        .:     :    .*:*********:*.***

Q93N86_A1_7__hpg|hpg2cl                  VAVPHDAVAALAGDPGWGVHAQDAVLLHAPHAFDASLFEIWVPLVSGARVVVAEPGV-VD
Q8KLL5_A1_4__hpg|hpg2cl                  VAVSHGNVAALVGEPRWEIGPGDTVLTHASHAFDISLFEIWVPLLSGARMMIAEPGA-VD
Q8KLL5_A1_hpg|hpg2cl                     VAVSHGNVAALVGEPRWEIGPGDTVLTHASHAFDISLFEIWVPLLSGARMMIAEPGA-VD
Q93N89_A1_1__hpg|hpg2cl                  VAVPHGSVAALVGESGWGLGPGDSVLFHAPHAFDISLFEVWVPLASGARVVIAEPGVAVD
Q93N87_A1_4__hpg|hpg2cl                  VAVPHGSVAALVGEPGWAVGPGDSVLFHAPHAFDISLFEVWVPLASGARVEVAEPSVVVD
Q93N87_A2_5__hpg|hpg2cl                  VAVPHGSVAALVGETGWGLGPGDSVLFHAPHAFDISLFEVWVPLASGARVVIAEPGVAVD
Q93N88_A1_3__hpg|hpg2cl                  VAVPHASVAALVGEPGWGVGPGDAVLFHAPHAFDISLFEVWVPLASGGRIVVAEPSMAVD
Q93N89_A1_hpg|hpg2cl                     VAVPHGSVAALVGESGWGLGPGDSVLFHAPHAFDISLFEVWVPLASGARVVIAEPGVAVD
Q93N87_A2_hpg|hpg2cl                     VAVPHGSVAALVGETGWGLGPGDSVLFHAPHAFDISLFEVWVPLASGARVVIAEPGVAVD
Q93N87_A1_hpg|hpg2cl                     VAVPHGSVAALVGEPGWAVGPGDSVLFHAPHAFDISLFEVWVPLASGARVEVAEPSVVVD
                                         ***.*  ****.*:. * : . *:** **.**** ****:**** **.*: :***.  **

Q93N86_A1_7__hpg|hpg2cl                  ALRIREEVAAGVTALHLTAGTFRVLAEEEPECFAGLREVLTGGDVVPPQAVERVRQVCPE
Q8KLL5_A1_4__hpg|hpg2cl                  GEALARYVAAGVTAAHLTAGAFRVLAEESPESVAGLREVLTGGDEVPPAAVRRVRRACPD
Q8KLL5_A1_hpg|hpg2cl                     GEALARYVAAGVTAAHLTAGAFRVLAEESPESVAGLREVLTGGDEVPPAAVRRVRRACPD
Q93N89_A1_1__hpg|hpg2cl                  AAAVRRHIAAGVTHVHVTAGLFRVLAEEAPDCFTGAREVLTGGDVVPLEAVERVRAACPD
Q93N87_A1_4__hpg|hpg2cl                  AAAVREYIAGGVTHVHVTAGLFRVLAEESPECFTGAREVLTGGDVVPARAVQRVRSACPE
Q93N87_A2_5__hpg|hpg2cl                  AAAVRRHIAAGVTHVHVTAGLFRVLADEEPECFNGAHEVLTGGDVVPLEAVARVRAACPE
Q93N88_A1_3__hpg|hpg2cl                  GAAVRRHIADGVTHVHVTAGLFRVLAEEASDCFDGVHEVLTGGDVVPLEAVERVRAACPD
Q93N89_A1_hpg|hpg2cl                     AAAVRRHIAAGVTHVHVTAGLFRVLAEEAPDCFTGAREVLTGGDVVPLEAVERVRAACPD
Q93N87_A2_hpg|hpg2cl                     AAAVRRHIAAGVTHVHVTAGLFRVLADEEPECFNGAHEVLTGGDVVPLEAVARVRAACPE
Q93N87_A1_hpg|hpg2cl                     AAAVREYIAGGVTHVHVTAGLFRVLAEESPECFTGAREVLTGGDVVPARAVQRVRSACPE
                                         .  : . :* ***  *:*** *****:* .:.. * :******* **  ** *** .**:

Q93N86_A1_7__hpg|hpg2cl                  LRIRHLYGPTETTLCATWHLVEPGSPAAGTLPIGRPLAGRRVHVLDAFLQPVPAGVPGEL
Q8KLL5_A1_4__hpg|hpg2cl                  IRVRHLYGPTETTLCATWWLLEPGDEAGGVLPIGRPLAGRRVHVLDAFLRPVPPGVKGEL
Q8KLL5_A1_hpg|hpg2cl                     IRVRHLYGPTETTLCATWWLLEPGDEAGGVLPIGRPLAGRRVHVLDAFLRPVPPGVKGEL
Q93N89_A1_1__hpg|hpg2cl                  VRVRHLYGPTESTLCATWHLVEPGDDTARVLPIGHPLTNRHIHVLDDSLRRVAPGVTGEL
Q93N87_A1_4__hpg|hpg2cl                  VRVRHLYGPTEVSLCATWHLLEPGEESPQVLPVGRPLGNRQVYVLDAYLHPVAPGVTGEL
Q93N87_A2_5__hpg|hpg2cl                  VRVRHLYGPTEVSLCATWHLLEPGEGTDRVLPVGSPLANRQVYVLDAFLQPVPPGVAGEL
Q93N88_A1_3__hpg|hpg2cl                  VRVRHLYGPTEVSLCATWHLFEPGEEQGEVLPLGRPLNNRQVYVLDPFLQPVPPGVTGEL
Q93N89_A1_hpg|hpg2cl                     VRVRHLYGPTESTLCATWHLVEPGDDTARVLPIGHPLTNRHIHVLDDSLRRVAPGVTGEL
Q93N87_A2_hpg|hpg2cl                     VRVRHLYGPTEVSLCATWHLLEPGEGTDRVLPVGSPLANRQVYVLDAFLQPVPPGVAGEL
Q93N87_A1_hpg|hpg2cl                     VRVRHLYGPTEVSLCATWHLLEPGEESPQVLPVGRPLGNRQVYVLDAYLHPVAPGVTGEL
                                         :*:******** :***** *.***.    .**:* ** .*:::***  *: *..** ***

Q93N86_A1_7__hpg|hpg2cl                  YIAGEGVAHGYAGRAALTAERFVADPYTDGRRMYRTGDLVRWTDEGELVFVGRADAQVKI
Q8KLL5_A1_4__hpg|hpg2cl                  YVAGAGVARGYLGRSALTAERFVADPFVPGERMYRTGDLAHWTDEGTLVFGGRADDQVKI
Q8KLL5_A1_hpg|hpg2cl                     YVAGAGVARGYLGRSALTAERFVADPFVPGERMYRTGDLAHWTDEGTLVFGGRADDQVKI
Q93N89_A1_1__hpg|hpg2cl                  YIAGAGLARGYLKRAGLSAERFVACPFADGERMYRTGDLARWTDDGELAFAGRADAQVKI
Q93N87_A1_4__hpg|hpg2cl                  YIAGAGLARGYLKRAGLSSERFVACPFADGERMYRTGDLVRWTSDGELVFVGRADAQVKV
Q93N87_A2_5__hpg|hpg2cl                  YIAGAGLARGYLKRAGLSAERFVACPFADGERMYRTGDLARWTDDGELAFAGRADAQVKI
Q93N88_A1_3__hpg|hpg2cl                  YVAGAGLARGYLGRAGLSAERFVASPFADGERMYRTGDLVRWTTGVELVFVGRADAQVKI
Q93N89_A1_hpg|hpg2cl                     YIAGAGLARGYLKRAGLSAERFVACPFADGERMYRTGDLARWTDDGELAFAGRADAQVKI
Q93N87_A2_hpg|hpg2cl                     YIAGAGLARGYLKRAGLSAERFVACPFADGERMYRTGDLARWTDDGELAFAGRADAQVKI
Q93N87_A1_hpg|hpg2cl                     YIAGAGLARGYLKRAGLSSERFVACPFADGERMYRTGDLVRWTSDGELVFVGRADAQVKV
                                         *:** *:*:**  *:.*::***** *:. *.********.:**    *.* **** ***:

Q93N86_A1_7__hpg|hpg2cl                  RGFRVEPGEVEAALAAQPGVRQAVVAARDDGPGEKRLIG
Q8KLL5_A1_4__hpg|hpg2cl                  RGYRVEPGEIEAVLAGLPGVGQAVVLARDE-----RLIG
Q8KLL5_A1_hpg|hpg2cl                     RGYRVEPGEIEAVLAGLPGVGQAVVLARDE-----RLIG
Q93N89_A1_1__hpg|hpg2cl                  RGFRVELGEVEAALAAQPAVAQAVVVAREDRPGEKRLVG
Q93N87_A1_4__hpg|hpg2cl                  RGFRVELGEVEAALAAEAGVGHAVVTAREDRPGERRLIG
Q93N87_A2_5__hpg|hpg2cl                  RGFRVELGEVEAALAAQPAVAQAVVVAREGRPGEKRLVG
Q93N88_A1_3__hpg|hpg2cl                  RGFRVELGEVEAALAAQPAVAQAVVVAREDRPGEKRLVG
Q93N89_A1_hpg|hpg2cl                     RGFRVELGEVEAALAAQPAVAQAVVVAREDRPGEKRLVG
Q93N87_A2_hpg|hpg2cl                     RGFRVELGEVEAALAAQPAVAQAVVVAREGRPGEKRLVG
Q93N87_A1_hpg|hpg2cl                     RGFRVELGEVEAALAAEAGVGHAVVTAREDRPGERRLIG
                                         **:*** **:**.**. ..* :*** **:      **:*
