CLUSTAL W multiple sequence alignment


Q70AZ7_A2_5__hpg|hpg2cl                  VCVQATSGAVPDGLAPVVMDSPAIAAAPSEAPPITVGAHDLAYVMYTSGSTGVPKGVAVP
Q8KLL5_A2_hpg|hpg2cl                     VCAEGTRNAVPDGLEPVPVDAPWAGETRHETP--TVTARDAAYVMYTSGSTGEPKGIVVP
Q8KLL5_A2_5__hpg|hpg2cl                  VCAEGTRNAVPDGLEPVPVDAPWAGETRHETP--TVTARDAAYVMYTSGSTGEPKGIVVP
Q70AZ7_A2_hpg|hpg2cl                     VCVQATSGAVPDGLAPVVMDSPAIAAAPSEAPPITVGAHDLAYVMYTSGSTGVPKGVAVP
                                         **.:.* .****** ** :*:*  . :  *:*  ** *:* *********** ***:.**

Q70AZ7_A2_5__hpg|hpg2cl                  HGSVAALAGDPGWSVGPGDGVLMHAPHAFDASLLEIWVPLLSGAHVVVADPGAVDAQRLR
Q8KLL5_A2_hpg|hpg2cl                     HGSVAALAGDPGWALDADDCVLMHASHAFDASLFEIWAPLVRGARVMVAEPGAVDTQRLR
Q8KLL5_A2_5__hpg|hpg2cl                  HGSVAALAGDPGWALDADDCVLMHASHAFDASLFEIWAPLVRGARVMVAEPGAVDTQRLR
Q70AZ7_A2_hpg|hpg2cl                     HGSVAALAGDPGWSVGPGDGVLMHAPHAFDASLLEIWVPLLSGAHVVVADPGAVDAQRLR
                                         *************::...* *****.*******:***.**: **:*:**:*****:****

Q70AZ7_A2_5__hpg|hpg2cl                  EAIDRGVTTVHLTAGSFRVLAEESPDAFRGLREVLTGGDAVPLASVVRLRETCPEIRVRH
Q8KLL5_A2_hpg|hpg2cl                     EAVARGVTTVHLTAGSFRVLAEESPGSFDGLREILTGGDVVPLASVAQLRRACPDVRVRH
Q8KLL5_A2_5__hpg|hpg2cl                  EAVARGVTTVHLTAGSFRVLAEESPGSFDGLREILTGGDVVPLASVAQLRRACPDVRVRH
Q70AZ7_A2_hpg|hpg2cl                     EAIDRGVTTVHLTAGSFRVLAEESPDAFRGLREVLTGGDAVPLASVVRLRETCPEIRVRH
                                         **: *********************.:* ****:*****.******.:**.:**::****

Q70AZ7_A2_5__hpg|hpg2cl                  LYGPTETTLCATWHLIEPGVATGDTLPIGRPLAGRRAYVLDAFLQPVAPNVTGELYLAGA
Q8KLL5_A2_hpg|hpg2cl                     LYGPTETTLCGTWHLLEPGDEPGDVLPIGRPLAGRRAYVLDAFLQPVAPNVTGELYLAGV
Q8KLL5_A2_5__hpg|hpg2cl                  LYGPTETTLCGTWHLLEPGDEPGDVLPIGRPLAGRRAYVLDAFLQPVAPNVTGELYLAGV
Q70AZ7_A2_hpg|hpg2cl                     LYGPTETTLCATWHLIEPGVATGDTLPIGRPLAGRRAYVLDAFLQPVAPNVTGELYLAGA
                                         **********.****:***  .**.**********************************.

Q70AZ7_A2_5__hpg|hpg2cl                  GLARGYLGAAAATAERFVADPFAAGERMYRTGDLARWTEQGELLFAGRADAQVKIRGYRV
Q8KLL5_A2_hpg|hpg2cl                     GLALGYLGARGATSERFVADPFVPGERMYRTGDLARRNDRGELLFAGRADAQVKIRGYRV
Q8KLL5_A2_5__hpg|hpg2cl                  GLALGYLGARGATSERFVADPFVPGERMYRTGDLARRNDRGELLFAGRADAQVKIRGYRV
Q70AZ7_A2_hpg|hpg2cl                     GLARGYLGAAAATAERFVADPFAAGERMYRTGDLARWTEQGELLFAGRADAQVKIRGYRV
                                         *** ***** .**:********..************ .::********************

Q70AZ7_A2_5__hpg|hpg2cl                  EPAEIEAALTAIPEVAQAVVVAREDGPGEKRLIA
Q8KLL5_A2_hpg|hpg2cl                     EPTEIETVLAEAPQVAQTVVVAREDGPGEKRLIA
Q8KLL5_A2_5__hpg|hpg2cl                  EPTEIETVLAEAPQVAQTVVVAREDGPGEKRLIA
Q70AZ7_A2_hpg|hpg2cl                     EPAEIEAALTAIPEVAQAVVVAREDGPGEKRLIA
                                         **:***:.*:  *:***:****************
