CLUSTAL W multiple sequence alignment


BGC0000400_AGM16414.1_2358_mod3_ile      --LTQHELQSR---IPVQASFVLLDDEHSYSADDSNLEQNNGPADLAYVIYTSGTTGKPK
AGM16414.1_2358_mod3_ile                 --LTQHELQSR---IPVQASFVLLDDEHSYSADDSNLEQNNGPADLAYVIYTSGTTGKPK
O66071_A1_7__ile                         --LTQEELAGQAASLSFHQNTILIDDPAVSAESGRNLEIAAEPDDLAYIMYTSGTTGKPK
BGC0000400_AGM16413.1_4358_mod4_ile      --VTQRHLQER---IPGAGTRVILDDEHSYSSDSTNLDLNNGPADLAYVIYTSGTTGKPK
O68008_A1_8__ile                         --LAQGKAADG---IDCEADIIHLDKGVADGFSKKRLSSVNDSGDTAYIIYTSGSTGMPK
AGM16413.1_4358_mod4_ile                 --VTQRHLQER---IPGAGTRVILDDEHSYSSDSTNLDLNNGPADLAYVIYTSGTTGKPK
O68006_A5_ile                            DSLLKPFDIKT---VDLCSDELHL-------LSEENLPRVNRSSDTAYIVYTSGSTGTPK
O68006_A1_ile                            --LTQGKAADG---IDCEADIVQLDREASDGFSKEPLSSVNDSGDTAYIIYTSGSTGTPK
                                           : :         :      : :        .   *     . * **::****:** **

BGC0000400_AGM16414.1_2358_mod3_ile      GNLATHRNIVRVVQGTSYIDFSERDNVLQLSNYAFDGSTFDMYGALLNGAKLVLIPQETL
AGM16414.1_2358_mod3_ile                 GNLATHRNIVRVVQGTSYIDFSERDNVLQLSNYAFDGSTFDMYGALLNGAKLVLIPQETL
O66071_A1_7__ile                         GNLTTHANITRVVKETNYISLSEKDTLLSLSNYAFDGFTFDVYGALLNGAKLVVADQATI
BGC0000400_AGM16413.1_4358_mod4_ile      GNLTMHRNIVRVVQGADYIDIGEQDNVLQLSSYAFDGSTFDMYGALLNGARLVLIPQETL
O68008_A1_8__ile                         GVVTPHYSAARVVKNTNYIDITEDDAILQLSNYSFDGSVFDIFGALLNGASLVLIEKETV
AGM16413.1_4358_mod4_ile                 GNLTMHRNIVRVVQGADYIDIGEQDNVLQLSSYAFDGSTFDMYGALLNGARLVLIPQETL
O68006_A5_ile                            GVVIPHYSAARVVKNTNYIDITGNDVILQLSNYSFDGSVFDIFGALLNGASLVLIEKETV
O68006_A1_ile                            GVITPHYSVIRVVQNTNYIDITEDNVILQLSNYSFDGSVFDIFGALLNGASLVMIEKEAL
                                         * :  * .  ***: :.**.:   : :*.**.*:*** .**::******* **:  : ::

BGC0000400_AGM16414.1_2358_mod3_ile      LEVGKLAGLIERERISVMFITTAYFNILIDMKADCLRHIRTILFGGERVSISHVRKALYQ
AGM16414.1_2358_mod3_ile                 LEVGKLAGLIERERISVMFITTAYFNILIDMKADCLRHIRTILFGGERVSISHVRKALYQ
O66071_A1_7__ile                         LHIGKLTETIQKENITVMFVTTALFNLLVDAGTEWMKGIRKVLFGGERSSVSHVKKAFAA
BGC0000400_AGM16413.1_4358_mod4_ile      LDVERLAELIERERISVMFITTAFFNVLVDVKADCLRHIRAILFGGERVSVSHVRKALRH
O68008_A1_8__ile                         LNTHELAEVIKKEQVSVMFITTALFNTLADINIGCLAKLRKIFLGGERASIPHVRKVLNH
AGM16413.1_4358_mod4_ile                 LDVERLAELIERERISVMFITTAFFNVLVDVKADCLRHIRAILFGGERVSVSHVRKALRH
O68006_A5_ile                            LNTHELAEVIKKEQVSVMFITTALFNTLADINIGCLAKLRKILFGGERASIPHVRKVLDH
O68006_A1_ile                            LNINRLGSAINEEKVSVMFITTALFNMIADIHVDCLSNLRKILFGGERASIPHVRKVLNH
                                         *.  .*   *:.*.::***:*** ** : *     :  :* :::**** *:.**:*.:  

BGC0000400_AGM16414.1_2358_mod3_ile      LGPGKIKHVYGPTESTVFATCHDVNEVAEDAVTVPIGRPISNTTIYIVNAQNDLQPIGVA
AGM16414.1_2358_mod3_ile                 LGPGKIKHVYGPTESTVFATCHDVNEVAEDAVTVPIGRPISNTTIYIVNAQNDLQPIGVA
O66071_A1_7__ile                         MGPDRIIHVYGPTETTVFATFYPVNRIEDNAVSIPIGKPINETNAYILTENNRLQPIGAV
BGC0000400_AGM16413.1_4358_mod4_ile      LGPGKIKHVYGPTESTVFATCHDVNEVAADALNVPIGRPISNTTIYIVNEENGLQPIGVA
O68008_A1_8__ile                         VGRDKLIHVYGPTESTVYATYYFINEIDDEAETIPIGSPLANTSVLIMDEAGKLLPIGVP
AGM16413.1_4358_mod4_ile                 LGPGKIKHVYGPTESTVFATCHDVNEVAADALNVPIGRPISNTTIYIVNEENGLQPIGVA
O68006_A5_ile                            VGRDKLIHVYGPTESTVYATYYFINEIDDEAETIPIGSPLANTSVLIMDEAGKLLPIGVP
O68006_A1_ile                            VGRDKLIHVYGPTESTVYATYYFINEIDDEAETIPIGSPLANTSVLIMDEAGKLVPIGVP
                                         :* .:: *******:**:** : :*.:  :* .:*** *: :*.  *:   . * ***. 

BGC0000400_AGM16414.1_2358_mod3_ile      GELCIAGDGLARGYLNRPELTAAKFVDNPFAPRERMYRTGDLARWLPDGTIEYVGRIDDQ
AGM16414.1_2358_mod3_ile                 GELCIAGDGLARGYLNRPELTAAKFVDNPFAPRERMYRTGDLARWLPDGTIEYVGRIDDQ
O66071_A1_7__ile                         GELCLSGTGVSRGYLNRPELTAEKFVPHPFNSGETMYRTGDLARWLPDGNIDFIGRIDDQ
BGC0000400_AGM16413.1_4358_mod4_ile      GELCVAGDGLARGYLNRPELTAEKFVDNPFVPGERMYRTGDLARWLPDGSIEYVGRIDHQ
O68008_A1_8__ile                         GELCIAGDGLSKGYLNREELTAEKFIPHPFIPGERLYKTGDLAKWLPDGNIEFIGRIDHQ
AGM16413.1_4358_mod4_ile                 GELCVAGDGLARGYLNRPELTAEKFVDNPFVPGERMYRTGDLARWLPDGSIEYVGRIDHQ
O68006_A5_ile                            GELCIAGDGLSKGYLNREELTAEKFIPHPFIPGERLYKTGDLAKWLPDGNIEFIGRIDHQ
O68006_A1_ile                            GELCIAGDGLSKGYLNREELTAEKFIPHPFIPGERLYKTGDLAKWLPDGNIEFIGRIDHQ
                                         ****::* *:::***** **** **: :** . * :*:*****:*****.*:::****.*

BGC0000400_AGM16414.1_2358_mod3_ile      VKIRGYRIELGEVETHLLRVEPIQEATVIARESDSGEKRLCA
AGM16414.1_2358_mod3_ile                 VKIRGYRIELGEVETHLLRVEPIQEATVIARESDSGEKRLCA
O66071_A1_7__ile                         VKIRGHRIELGEIEEELMRCQGVKEAVVIAKKRGNGDAALTA
BGC0000400_AGM16413.1_4358_mod4_ile      VKIRGYRIELGEVEAHLLKVQPVQEGTVVARETGSGEKQLCA
O68008_A1_8__ile                         VKIRGFRIELGEIESRLEMHEDINETIVTVREDEESRPYICA
AGM16413.1_4358_mod4_ile                 VKIRGYRIELGEVEAHLLKVQPVQEGTVVARETGSGEKQLCA
O68006_A5_ile                            VKIRGFRIELGEIESRLEMHEDINETIVTVREDEESRPYICA
O68006_A1_ile                            VKIRGFRIELGEIESRLEMHEDINETIVTVREDEESRPYICA
                                         *****.******:* .*   : ::*  * .::  ..   : *
