CLUSTAL W multiple sequence alignment


AFZ61526.1_2645_mod3_ile                 LTHSDRAVDYAVQRLDLDTLALDPQPSHNPDLSQSSDSVAYIMYTSGSTGTPKGVLVPHR
BGC0000425_AFH75322.1_2740_mod3_ile      LTTSAHQAPEGGERLDLDSLDLSDAPVHDPAIEQSAESVAYIMYTSGSTGVPKGVLVPHR
Q84BQ4_A3_9__ile                         LTLSSEAIDYAAPRIDLDRLKLSGQSTHNPNLAQSSDALAYIMYTSGSTGTPKGVMVPHR
Q84BQ4_A4_10__ile                        LTLSREDIDYAAPRIDLDRLILSGQPTHNPNLLQSSEALAYIMYTSGSTGTPKGVMVPHR
                                         ** * .    .  *:*** * *.  . *:* : **::::***********.****:****

AFZ61526.1_2645_mod3_ile                 GITRLVINNGYADFNASDRVAFASNPAFDASTMDVWGPLLNGGQVQVIDHATLLDPAAFG
BGC0000425_AFH75322.1_2740_mod3_ile      GITRLVINGGYADFNTHDRIAFASNPAFDASTMDVWGALLNGGQVVVIDHDTLLDPLRFG
Q84BQ4_A3_9__ile                         GIARLVLNNGYADFNRQDRVAFASNPAFDASTMDIWGPLLNGGRVVVIDHQTLLDPNAFG
Q84BQ4_A4_10__ile                        AIGRLVLNNGYADFNAQDRVVFASNPAFDASTMDIWGPLLNGGRVVVIDHQTLLDPNAFG
                                         .* ***:*.******  **:.*************:**.*****:* **** *****  **

AFZ61526.1_2645_mod3_ile                 --VALADVTVLFVTTALFNQYVQLIPQALAGLRILLCGGERADPAAFRSLLHQAPALRLV
BGC0000425_AFH75322.1_2740_mod3_ile      AVLSESAVTILFTTTALFNQYVQLIPDALKGLRMLLCGGERADPAAFRSLLEHAPKLRLV
Q84BQ4_A3_9__ile                         RELSASGATILFVTTALFNQYVQLIPQALKGLRMVLCGGERGDPTSFRRLRAEAPQLRIV
Q84BQ4_A4_10__ile                        HELSASRATVLFVTTALFNQYVQLIPQALKGLRILLCGGERGDPAAFRRLLAEAPKLRIV
                                           :: : .*:**.*************:** ***::******.**::** *  .** **:*

AFZ61526.1_2645_mod3_ile                 HCYGPTETTTYATTYEVRALAEAADSVPIGRPISNTQVHVLDAHLQPVPVGVTGEICIGG
BGC0000425_AFH75322.1_2740_mod3_ile      HCYGPTESTTYATTFEVRALADDAESVPIGGPISNTRIYLLDQRQQPVPLGVVGEIYIGG
Q84BQ4_A3_9__ile                         HCYGPTETTTYATTFEVHEVAENAESVPIGAPISNTQVYVLDAHQQPVPMGVTGELYIGG
Q84BQ4_A4_10__ile                        HCYGPTETTTYATTFEVREVAENAESVPIGGPISNTQVYVLDAHQQPVPMGVTGELYIGG
                                         *******:******:**: :*: *:***** *****::::** : ****:**.**: ***

AFZ61526.1_2645_mod3_ile                 DGVALGYLNRPDLTAEKFVRDPLSE--GALMYRTGDLGRWTADGLLDCIGRNDDQVKIRG
BGC0000425_AFH75322.1_2740_mod3_ile      KGVAKGYLNRPELTAEKFILDPFSHEPGALMYRTGDLGRWLAKGELDCLGRNDDQVKIRG
Q84BQ4_A3_9__ile                         QGVALGYLNRADLTAEKFLPDPFSDRPGALLYRTGDLVRWLAPGQLDCIGRNDDQVKIRG
Q84BQ4_A4_10__ile                        QGVALGYLNRADLTAEKFLRDPFSDQPGALLYRTGDLARWLAPGQLDCIGRNDDQVKIRG
                                         .*** *****.:******: **:*.  ***:****** ** * * ***:***********

AFZ61526.1_2645_mod3_ile                 FRIELGEIEARLATFAGIQDVVVLAREDAPGDKRLAA
BGC0000425_AFH75322.1_2740_mod3_ile      FRIELGEIENRLGEHPQINEVVVLAREDEPGSKRLVA
Q84BQ4_A3_9__ile                         FRIELGEIENRLLSYPGINEAVVLARRDGQEPLRLVA
Q84BQ4_A4_10__ile                        FRIELGEIENRLLNCQGIKEAVVLARRDGQDITRLVA
                                         ********* **     *::.*****.*     **.*
