CLUSTAL W multiple sequence alignment


Q70LM5_A4_10__leu                        LTQEHLLAQLPEA-RATFLCLDRDWSLIAEE----SDVAPVIATNRDNLAYVIYTSGSTG
Q70LM5_A6_12__leu                        LTQERLLETLPAG-DAAFICLDADWEVIAEE----STQAPELAVTTDQLAYVIYTSGSTG
Q65NK5_A3_leu                            LTQTNL--AVPEEFSGETLLLD---SMLSEEITNDDEVNPQAGTQPNNLAYLIYTSGTTG
Q9S1A8_A1_8__leu                         LTQESLGDFLPQT-GAELLCLDRDWEKIATY----SPENPFNLTTPENLAYVIYTSGSTG
Q9RAH4_A4_leu                            LTQQKLLDRLAQH-QAKLVCLDTDWQLISQS----SQDNLITETQAANLAYVIYTSGSTG
O69246_A3_6__leu                         LTQSGL--TVPDTFTGDVIDLNREGSILDGELYPEDDMNPNAQAQSDNLAYLIYTSGTTG
Q70LM6_A2_4__leu                         LTQERLLDALPQE-AAALLCLDRDWQEIAAE----STAAPAIKTNADQLAYVIYTSGSTG
Q9RAH2_A1_leu                            LTQQKLIDRLPEH-TAQRVCLDADWQVISQL----SQDNLIPETQATNLAYVIYTSGSTG
Q70LM4_A2_14__leu                        LTQAKLRQKLPAD-TSRLICLDADWETIAQE----PTAALVNTTAASDLAYVIYTSGSTG
                                         ***  *   :.    .  : *:   . :               .   :***:*****:**

Q70LM5_A4_10__leu                        TPKGVEIEHAALLNLVSWHQRAYEVGAEDRATQIAGTAFDASVWEIWPYLTKGATLYLPS
Q70LM5_A6_12__leu                        TPKGVEIEHRALLNLIYWHQHAYTITPDDRASQIAGTAFDAAVWEIWPYMTAGATLYLPQ
Q65NK5_A3_leu                            QPKGVMVEHQSLVNLCYWHNDAFAVTEQDKSAKYAGFGFDASVWEMFPYWIAGAELHIID
Q9S1A8_A1_8__leu                         KPKGVLISHRGLMNLICWHQDAFEITPLDKITQLARSAFDAAVWELWPCLTAGASLVLVK
Q9RAH4_A4_leu                            QPKGVLIAHQGLLNLVFWHQNTFKITTLDKATQLAGTAFDAAVWELWPYLTAGASIYLVK
O69246_A3_6__leu                         QPKGVMVEHRSLVNLCYWHNDAFKVTEHDKSAKYAGFGFDASVWEMFPYWIAGAELHIID
Q70LM6_A2_4__leu                         TPKGVEIEHGSLLNLVNWHQRAYSVSAEDRASQIAGTAFDASVWETWPYLTAGATICQPR
Q9RAH2_A1_leu                            QPKGVLIAHQGLLNLVFWHQRTFKITTLDKATQLAGTAFDAAVWELWPYLTAGASIYLVK
Q70LM4_A2_14__leu                        TPKGVEIEHAALLNLIFWHQRAYDVTATDRASQIAGTAFDASVWEIWPYVTKGATLYLPE
                                          **** : * .*:**  **: :: :   *: :: *  .***:*** :*    ** :    

Q70LM5_A4_10__leu                        EEIRLVPEQLRDWLVASGITISFLPTPLAERLLTLEWP-SDAKLRYMLTGGDKLHDYPPA
Q70LM5_A6_12__leu                        EEIRLIPEKLRDWLVAEGITISFLPTPLAESMLSVDWP-SHAALRYVLTGGDKLHHYPAE
Q65NK5_A3_leu                            EAIRMDITRLNEYFEENGITITFLPTQLCEQFMEL----DNQSLRVLLTGGDKLKRIEKR
Q9S1A8_A1_8__leu                         PEIMQSPPDLRDWLIAQEITVSFLPTPLVEKILSLKWD-ENIALRIILTGGDKLHHYPSV
Q9RAH4_A4_leu                            SEFLSSLVKLRDWLISKKITISFLPTPLAQELLSLEWPTESLALRTILTGGDKLHQYPSD
O69246_A3_6__leu                         EAIRMDITRLNQYFEENKITITFLPTQLCEQFMEL----DNQSLRVLLTGGDKLKRIAKR
Q70LM6_A2_4__leu                         EEIRLSPEKLRDWLVETGITISFLPTPLAENLLPLPWP-TGAALRYMLTGGDTLHQYPTA
Q9RAH2_A1_leu                            PEILLSPVDLQDWLESKKITISFLPTPMAEQLLSLEWP-ESTTLRTMLTGGDKLHRYPSG
Q70LM4_A2_14__leu                        EEIRLVPEKLRDWLVASNITVSFLPTPLTESMLALEWP-GDTALRYMLTGGDKLHHYPSE
                                           :      *.:::    **::**** : : :: :        ** :*****.*:     

Q70LM5_A4_10__leu                        TLPFVLANQYGPTENAVVATAGIVPAAAGQ-VSAPSIGRPIDNVQVYVLDEKLQPVPIGV
Q70LM5_A6_12__leu                        HVPFTLVNQYGPTENAVVATAGIVAVQAGQ-VTPPSIGRPIDNVQVYILDEQRQPVPIGV
Q65NK5_A3_leu                            N--YTLVNNYGPTENTVVATSTAIDPDEGM----LSIGKPIANTRAYVLGQNNEVQPVGV
Q9S1A8_A1_8__leu                         SMPFKLINNYGPTENTVVTTSGLVPDYEEGNSSSPSIGKPISNTKIYILDQNLQPLPIGV
Q9RAH4_A4_leu                            LVPSQLVNNYGPTENTVVTTSGLVVAKEQD-QISPSIGRAIANTQIYILDNNLQLVPIGI
O69246_A3_6__leu                         S--YTLVNNYGPTENTVVATSAAIDLDEGM----LSIGKPIANTRVYVLGQNNEVQPVGV
Q70LM6_A2_4__leu                         DVPFTLVNQYGPTENTVVATAGAVPVLGER-ESAPTIGRPIDNVSVYVLDENRQPVPVGV
Q9RAH2_A1_leu                            LLPFQVVNNYGPTENTVVSTSGLVVSNGRDNNISPPIGRPIANVEIYILDSYLQPVPVGV
Q70LM4_A2_14__leu                        KIPFTLVNQYGPTENTVVATAGIVPKEAGQ-TAAPTIGRPIDNVQVYILDAHRQPVPVGV
                                              : *:******:**:*:  :           .**:.* *.  *:*.   :  *:*:

Q70LM5_A4_10__leu                        AGELYIAGDSLARGYLHRPDLTRERFIANPYGQKAGA---------------------RM
Q70LM5_A6_12__leu                        TGELYIAGSSLARGYYKRPDLTQERFVDNPFTANRGA---------------------KM
Q65NK5_A3_leu                            AGELCIAGRGLARGYLNKPEETAKRFTEDPFVPGE-----------------------RM
Q9S1A8_A1_8__leu                         PGELHISSVGLARGYLNRLELTQEKFISNPFNSG------------------------IL
Q9RAH4_A4_leu                            PGELHIAGVGLAKGYLNRPELTTEKFIPNPFKRSREAGEQGSRGAKILPNSQSLVPSPRL
O69246_A3_6__leu                         AGELCIAGRGLARGYLNKPEETAKRFTEDPFVPGE-----------------------RM
Q70LM6_A2_4__leu                         VGELYIGGKSLARGYRNRPDLTEASFVPNPFSPIEGA---------------------RM
Q9RAH2_A1_leu                            PGELHIGGAGLARGYLNRPQLTQEKFISNPFKRSRGAGEQRSRGETFNSN--------RL
Q70LM4_A2_14__leu                        SGELYIGGSSLARGYLNRPDLTQERFVAHPFTEKAGA---------------------RL
                                          *** *.. .**:** :: : *   *  .*:                            :

Q70LM5_A4_10__leu                        YKTGDLVRYLPDGNIEFIGRADDQVSIRGFRVELGEIETALYSHPAVKETIVLVREDM-P
Q70LM5_A6_12__leu                        YRTGDLVRYLPDGQIEFIGRSDDQVSIRGFRVELGEIESVLYQHPAVKEAIVLAREDM-P
Q65NK5_A3_leu                            YRTGDAVKWLEDGRLEYIGRIDQQVKIRGFRIELSEIEVQLARLSEVQEAVVTDIEDA-Y
Q9S1A8_A1_8__leu                         YKTGDLVRYLPEGNIEFLGRIDNQVKLRGLRIELGEIEAVLETHSEVEKAVVILREDT-S
Q9RAH4_A4_leu                            YKTGDLARYLPDGNIEYLGRIDNQVKIRGFRIELAEIEALLGQHDDVQICCVIAREET-P
O69246_A3_6__leu                         YRTGDAVKWLEDGRLEYIGRIDQQVKIRGFRIELSEIEVQLARLSEVQEAVVTDIEDA-C
Q70LM6_A2_4__leu                         YRTGDLVRYAADGSIEFIGRADDQVSIRGFRVELGEIESALYAHPAVAESVVIVREDVTP
Q9RAH2_A1_leu                            YKTGDLARYLPDGTIEYLGRIDNQVKIRGFRIELSEIEAVLSQHSDVQLSCVIAREDT-P
Q70LM4_A2_14__leu                        YRTGDLVRSLPDGSIEFIGRADDQTSIRGFRVELGEVETAIVALPAVKEAVVTVCTDK-Q
                                         *:*** .:   :* :*::** *:*..:**:*:**.*:*  :     *    *    :   

Q70LM5_A4_10__leu                        GMKRLVA
Q70LM5_A6_12__leu                        GVKRLAA
Q65NK5_A3_leu                            GNKALCG
Q9S1A8_A1_8__leu                         DNQRLVA
Q9RAH4_A4_leu                            GNKRLVA
O69246_A3_6__leu                         GNKALCG
Q70LM6_A2_4__leu                         GVKRLVA
Q9RAH2_A1_leu                            GDKRLVA
Q70LM4_A2_14__leu                        GTKRLAA
                                         . : * .
