CLUSTAL W multiple sequence alignment


Q09164_A2_leu                            AGEPSPEGQSPEVSIVRIADATSPAGHASLRD-GKSKPTAGSLAYVIFTSGSTGKPKGVM
Q09164_A3_leu                            AETPIPEGMA-EAETIRITEILADAKTDDINGLAASQPTAASLAYVIFTSGSTGRPKGVM
Q09164_A8_leu                            SGIDMPQSDRMDVETARIQDILTNTKVERSD--PMSRPSATSLAYVIFTSGSTGRPKGVM
Q09164_A10_leu                           AGVPIPDNKTADVRMVFISDIVASKTDKSYS--PGTRPSASSLAYVIFTSGSTGRPKGVM
                                         :    *:.   :.    * :  :            ::*:* *************:*****

Q09164_A2_leu                            IEHRGVLRLVKQTNILSSLPPAQTFRMAHMSNLAFDASIWEVFTALLNGGSLVCIDRFTI
Q09164_A3_leu                            VEHRGIVRLTKQTNITSKLP--ESFHMAHISNLAFDASVWEVFTTLLNGGTLVCIDYFTL
Q09164_A8_leu                            IEHRNILRLVKQSNVTSQLP--QDLRMAHISNLAFDASIWEIFTAILNGGALICIDYFTL
Q09164_A10_leu                           VEHRGVISLVKQN--ASRIP--QSLRMAHVSNLAFDASVWEIFTTLLNGGTLFCISYFTV
                                         :***.:: *.**.   * :*  : ::***:********:**:**::****:*.**. **:

Q09164_A2_leu                            LDAQALEALFLREHINIALFPPALLKQCLTDAAATIKSLDLLYVGGDRLDTADAALAKAL
Q09164_A3_leu                            LESTALEKVFFDQRVNVALLPPALLKQCLDNSPALVKTLSVLYIGGDRLDASDAAKARGL
Q09164_A8_leu                            LDSQALRTTFEKARVNATLFAPALLKECLNHAPTLFEDLKVLYIGGDRLDATDAAKIQAL
Q09164_A10_leu                           LDSKALSAAFSDHRINITLLPPALLKQCLADAPSVLSSLESLYIGGDRLDGADATKVKDL
                                         *:: **   *   ::* :*:.*****:** .:.: .. *. **:****** :**:  : *

Q09164_A2_leu                            VKSEVYNAYGPTENTVMSTLYSIADTERFVNGVPIGRAVS-NSGVYVMDQNQQLVPLGVM
Q09164_A3_leu                            VQTQAFNAYGPTENTVMSTIYPIAE-DPFINGVPIGHAVS-NSGAFVMDQNQQITPPGAM
Q09164_A8_leu                            VKGTVYNAYGPTENTVMSTIYRLTDGESYANGVPIGNAVS-SSGAYIMDQKQRLVPPGVM
Q09164_A10_leu                           VKGKAYNAYGPTENSVMSTIYTIEH-ETFANGVPIGTSLGPKSKAYIMDQDQQLVPAGVM
                                         *:  .:********:****:* : . : : ****** ::. .* .::***.*::.* *.*

Q09164_A2_leu                            GELVVTGDGLARGYTNPALDSDRFVDVIARGQLLRAYRTGDRARYRPKDGQVEFFGRMDH
Q09164_A3_leu                            GELIVTGDGLARGYTTSSLNTGRFINVDIDGEQVRAYRTGDRVRYRPKDLQIEFFGRIDH
Q09164_A8_leu                            GELVVSGDGLARGYTNSTLNADRFVDIVINDQKARAYRTGDRTRYRPKDGSIEFFGRMDQ
Q09164_A10_leu                           GELVVAGDGLARGYTDPSLNTGRFIHITIDGKQVQAYRTGDRVRYRPRDYQIEFFGRLDQ
                                         ***:*:********* .:*::.**:.:   .:  :*******.****:* .:*****:*:

Q09164_A2_leu                            QVKVRGHRIELAEVEHALLSSAGVHDAVVVSNSQEDNQGVEMVA
Q09164_A3_leu                            QVKIRGHRIEPAEVEYALLSHDLVTDAAVVTHSQE-NQDLEMVG
Q09164_A8_leu                            QVKIRGHRVEPAEVEQAMLGNKAIHDAAVVVQAVD-GQETEMIG
Q09164_A10_leu                           QIKIRGHRIEPAEVEQALLSDSSINDAVVVS-AQN-KEGLEMVG
                                         *:*:****:* **** *:*.   : **.**  : :  :  **:.
