CLUSTAL W multiple sequence alignment


Q65NK5_A2_leu                            LTQKAMKPLAEAAEFGGDILFVEDENLYMGDASDLRLPISPEAMANLTYTSGTTGTPKGN
Q45295_A2_leu                            LTQKAMKPFAEAAEFGGDILFLEDEHLYLGDASDLRLPISPEAMANLTYTSGTTGTPKGN
P27206_A2_leu                            LTQRKLKALAEEAEFKGVIVLADEEESYHADARNLALPLDSAAMANLTYTSGTTGTPKGN
Q70KJ7_A2_leu                            LTQQSLKPLAEKAGFQGVIVLADDEASYEKDSRNPALPFDSKTIANLTYTSGTTGTPKGN
                                         ***: :*.:** * * * *:: ::*  *  *: :  **:.. ::****************

Q65NK5_A2_leu                            MVSHRNILRTVKNANYLEVMESDIVLSISNYVFDAFMFDVFGSLLNGAKLVIAPKDTILD
Q45295_A2_leu                            MVSHRNILRTVKNTNYLDVMTSDIVLSISNYVFDAFMFDVFGSLLNGAKLVIAPKDTILD
P27206_A2_leu                            IVTHANILRTVKETNYLSITEQDTILGLSNYVFDAFMFDMFGSLLNGAKLVLIPKETVLD
Q70KJ7_A2_leu                            IVTHANILRTVKNTNYLTVSEEDTVLGLSNYVFDAFMFDMFGSLLNGAKLVIVPKDTVLD
                                         :*:* *******::*** :  .* :*.:***********:***********: **:*:**

Q65NK5_A2_leu                            MSRLAHVLEKEKITILMITTALFNLLTDMRPDSLKGLRRVLFGGERASVDHVRRALKTVG
Q45295_A2_leu                            MSRLAHVLEKEKVTVLMITTALFNLLTDMRPDSLKGLRRVLFGGERASVDHVRRALNTVG
P27206_A2_leu                            MARLSRVIERENISILMITTALFHLLVDLNPACLSTLRKIMFGGERASVEHVRKALQTVG
Q70KJ7_A2_leu                            MSRLSRVIKRENVSILMITTALFHLLVDMEPSCLTTLRKIMFGGERASVEHVKKALAAVG
                                         *:**::*:::*::::********:**.*:.* .*. **:::********:**::** :**

Q65NK5_A2_leu                            RGRLLHMYGPSESTVFTTYHPVNEVPDDAQAIPIGKPVSNTEVLILDSFGNVQPAGVAGE
Q45295_A2_leu                            KGRLLHMYGPSESTVFTTYYPVNEVPDDAQAIPIGKPVSNTEVLILDSFGNVQPAGVAGE
P27206_A2_leu                            KGKLLHMYGPSESTVFATYHPVDELEEHTLSVPIGKPVSNTEVYILDRTGHVQPAGIAGE
Q70KJ7_A2_leu                            KGRLLHMYGPSESTVFATYHPVDVIEEDTLSVPIGKPVSNTEVFIMNSAGRIQPAGIAGE
                                         :*:*************:**:**: : :.: ::*********** *::  *.:****:***

Q65NK5_A2_leu                            LCVGGDGLVRGYFNRPELTAEKFTAHPFKTGEKIYRTGDMARWLA-DGCLEFIGRIDHQV
Q45295_A2_leu                            LCVGGDGLVRGYFNRPELTAEKFTEHPFKTGEKIYRTGDMARWLADDGCLEFIGRIDHQV
P27206_A2_leu                            LCVTGEGLVKGYYNRPELTEEKFVPHPFTSGERMYKTGDLARWLP-NGTIEFIGRIDHQV
Q70KJ7_A2_leu                            LCVSGEGLVEGYYNRPELTEEKFVKHPFKEGERMYKTGDLARWLP-NGDIEFIGRIDHQV
                                         *** *:***.**:****** ***. ***. **::*:***:****. :* :**********

Q65NK5_A2_leu                            KIRGQRIELGEIEHHLLTHDMVQEAAVLAVDTGAGDQMICA
Q45295_A2_leu                            KIRGQRIELGEIEHHLLTHEMVQEAAVLAVDTGKRDQMICA
P27206_A2_leu                            KIRGQAIELGEIEHQLQTHDRVQESVVLAVDQGAGDKLLCA
Q70KJ7_A2_leu                            KIRGQRIELGEIEHQLQSHDQIQECIVLAVDQGAGDKLLCA
                                         ***** ********:* :*: :**. ***** *  *:::**
