CLUSTAL W multiple sequence alignment


AFZ61526.1_575_mod1_leu                  LTQQALLERLPALDVPVINLDRFTWQHHSASNPKV-VVTPFNLAYVIYTSGSTGLPKGVM
AFZ61525.1_2683_mod3_leu                 LAEASTRDLLGA--VATLDLHDPRVQQQAVSNPQLSALTPAHLAYVIYTSGSTGQPKGVM
Q84BQ5_A3_5__leu                         LAQGATRELLGR--VPVIDLDNALWQHLPETNPQLPTLTPAHLAYVIYTSGSTGQPKGVV
Q84BQ5_A2_4__leu                         VAQASTRDLLGG--VQVIDLDNDLWQHLSDANPQVPALTPKHLAYVIYTSGSTGQPKGVM
                                         ::: :  : *    * .::*.    *: . :**:: .:** :************ ****:

AFZ61526.1_575_mod1_leu                  VEHHTVANLVDWHCNAFDLCAGRHTASVAGFGFDAMAWEVWPALCVGATLHLPPAHDGAE
AFZ61525.1_2683_mod3_leu                 VEHRTVENLVHWHCEAFGLDATGHTSSVAGFGFDAMAWEVWPALCVGATLHLPPADVGNE
Q84BQ5_A3_5__leu                         VEHATLENLVHWHCEAFDLRAGSHTASVAGCGFDAMAWEVWPALCVGATLHLPPPSISNE
Q84BQ5_A2_4__leu                         VEHATLENLVHWHAEAFDLQAGSQTASVAGFGFDAMAWEVWPALCVGATLHLPPPSIRNE
                                         *** *: ***.**.:**.* *  :*:**** ***********************.    *

AFZ61526.1_575_mod1_leu                  DIDALLAWWCAQPLDVCFLPTPVAEYAFSQQIEHPTLRTLLIGGDRLRQFGRAQRFDLIN
AFZ61525.1_2683_mod3_leu                 NIDELLAWWLAQPLDVSFLPTPVAEYAFSQNLQHPTLRILLIGGDRLRQFTQERRFAVIN
Q84BQ5_A3_5__leu                         HLDELLDWWRAQPLQVSFLPTPIAEYAFSRELGHPTLRTLLIGGDKLRQFSRGQTFDVIN
Q84BQ5_A2_4__leu                         HLDEMLDWWCAQPLQVSFLPTPVAEYAFSRQLQHPTLRTLLIGGDRLRQFSRQQTFEVIN
                                         .:* :* ** ****:*.*****:******::: ***** ******:**** : : * :**

AFZ61526.1_575_mod1_leu                  NYGPTEATVVATSGKVEAGQPLHIGKPIANATVYLLDEQQRPVPLGVAGELYVGGNGVAR
AFZ61525.1_2683_mod3_leu                 NYGPTEATVVATSGRVRAGQVLHIGRPIANASVYLLDAHLRPVPVGVAGELYVGGSGVAR
Q84BQ5_A3_5__leu                         NYGPTEATVVATSGSIHAGQLLHIGRPISNARIYLLDEQQRPVPVGVAGELYVGGAGVAR
Q84BQ5_A2_4__leu                         NYGPTEATVVATSGPVELDQPLHIGRPIANVRIYVLDAEQRPVPVGVAGELYVGGAGVAR
                                         ************** :. .* ****:**:*. :*:** . ****:********** ****

AFZ61526.1_575_mod1_leu                  GYLNRPELTAERFLQDPFN---TGRMYRTGDLARWLPDGNIEYLGRNDDQVKIRGMRIEL
AFZ61525.1_2683_mod3_leu                 GYLNRPDLSAGRFLHDPFN---EGRMYRTGDLARWLPDGNIEYLGRNDDQVKVRGVRVEL
Q84BQ5_A3_5__leu                         GYLNRPELTAERFLEDPFSDRPQARMYRTGDLARWLADGNIEYLGRNDDQVKLRGVRVEL
Q84BQ5_A2_4__leu                         GYLNRPELSAAQFLFDPFSDEPQARMYRTGDQARWLADGNIEYLGRNDDQVKLRGVRIEL
                                         ******:*:* :** ***.    .******* ****.***************:**:*:**

AFZ61526.1_575_mod1_leu                  GEIETQLNQVAGIQEAVVLVREERLVA
AFZ61525.1_2683_mod3_leu                 GEIESRLAALDGVAEAVVLVREGRLIA
Q84BQ5_A3_5__leu                         GEIEAALSSHPAVQDAVVLVREARLIA
Q84BQ5_A2_4__leu                         GEIEAALGSHVALQEAVVLVRDGRLIA
                                         ****: *    .: :******: **:*
