CLUSTAL W multiple sequence alignment


P27206_A3_leu                            LKQEGISVPDSYTGDVILLDGSRTILSLPLDENDEE----NPENPETAVTAENLAYMIYT
Q70KJ7_A3_leu                            LTQEALGVPESYKGETILLDGSRSILSLPLDENDE-------ANPQTETTADHLAYMIYT
Q65NK5_A3_leu                            LTQTNLAVPEEFSGETLLLD---SMLSEEITNDDE-------VNPQAGTQPNNLAYLIYT
Q70KJ6_A3_6__leu                         LTQEALDVPESYNGETILLDGRRSILSLPLDENDE-------ANPQTETTADHLAYMIYT
Q45295_A3_leu                            LTQTNLAAPEEFSGETLLLD---SMLSEEITKVDE-------VNPQAGTQSDNLAYLIYT
Q04747_A3_6__leu                         LKQEGISVPDSYTGDVILLDGSRTILSLPLDENDE-------GNPETAVTAENLAYMIYT
O68006_A3_leu                            --ISDVPLAEELTAESIEL----------IHMDDERIAGQDRSDIDNVNQSGDLAYVIYT
O69246_A3_6__leu                         LTQSGLTVPDTFTGDVIDLNREGSILDGELYPEDD-------MNPNAQAQSDNLAYLIYT
                                              :  .:  ..: : *          :   *:        : :    . .***:***

P27206_A3_leu                            SGTTGQPKGVMVEHHALVNLCFWHHDAFSMTAEDRSAKYAGFGFDASIWEMFPTWSIGAE
Q70KJ7_A3_leu                            SGTTGQPKGVMVEHHALVNLCFWHHDAFAMTADDKSAKYAGFGFDASIWEMFPTWTIGAE
Q65NK5_A3_leu                            SGTTGQPKGVMVEHQSLVNLCYWHNDAFAVTEQDKSAKYAGFGFDASVWEMFPYWIAGAE
Q70KJ6_A3_6__leu                         SGTTGQPKGVMVEHHALVNLCFWHHDAFAMTADDKSAKYAGFGFDASIWEMFPTWTIGAE
Q45295_A3_leu                            SGTTGQPKGVMVEHRSLVNLCYWHNDAFKVTEQDKSAKYAGFGFDASVWEMFPYWIAGAE
Q04747_A3_6__leu                         SGTTGQPKGVMVEHHALVNLCFWHHDAFSMTAEDRSAKYAGFGFDASIWEMFPTWTIGAE
O68006_A3_leu                            SGSTGKPKGVMIEHQSLINLCSWHQSCFEVGQNDNSSIYASISFDAFVWELFPYITAGAT
O69246_A3_6__leu                         SGTTGQPKGVMVEHRSLVNLCYWHNDAFKVTEHDKSAKYAGFGFDASVWEMFPYWIAGAE
                                         **:**:*****:**::*:*** **:..* :  .*.*: **.:.*** :**:**    ** 

P27206_A3_leu                            LHVIEEAIRLDIVRLNDYFETNGVTITFLPTQLAEQFMELENTSLRVLLTGGDKLKRAVK
Q70KJ7_A3_leu                            LHVIDEAIRLDITRLNHYFEEHGVTITFLPTQLAEQFMDLENTSLRMLLVGGDKLKRAVK
Q65NK5_A3_leu                            LHIIDEAIRMDITRLNEYFEENGITITFLPTQLCEQFMELDNQSLRVLLTGGDKLKRIEK
Q70KJ6_A3_6__leu                         LHVIDEAIRLDITRLNHYFEENGVTITFLPTQLAEQFMELENTSLRMLLVGGDKLKRAVK
Q45295_A3_leu                            LHIIDESIRMDITRLNQYFEENTITITFLPTQLCEQFMELDNQSLRVLLTGGDKLKRIAQ
Q04747_A3_6__leu                         LHVIDEAIRLDIVRLNDYFETNGVTITFLPTQLAEQFMELENTSLRVLLTGGDKLKRAVK
O68006_A3_leu                            VHVLNQETRLDVEKLNRYFHDHHITISFLPTPVCEQFTALDNHSLRTLLTGGDKLNVFKE
O69246_A3_6__leu                         LHIIDEAIRMDITRLNQYFEENKITITFLPTQLCEQFMELDNQSLRVLLTGGDKLKRIAK
                                         :*::::  *:*: :** **. : :**:**** :.***  *:* *** **.*****:   :

P27206_A3_leu                            KPYTLVNNYGPTENTVVATSAEIHPEEGSLSIGRAIANTRVYILGEGNQVQPEGVAGELC
Q70KJ7_A3_leu                            QPYTIINNYGPTENTVVATSGVINPEEGSLSIGRAIANTRVYILGDGDQVQPEGIAGELC
Q65NK5_A3_leu                            RNYTLVNNYGPTENTVVATSTAIDPDEGMLSIGKPIANTRAYVLGQNNEVQPVGVAGELC
Q70KJ6_A3_6__leu                         QPYTIINNYGPTENTVVATSGVINPEEGSLSIGRAIANTRVYILGDGDQVQPEGIAGELC
Q45295_A3_leu                            RSYTLVNNYGPTENTVVATSTAIDPDEGMLSIGKPIANTRAYVLGHNNEVQPVGVAGELC
Q04747_A3_6__leu                         KPYTLVNNYGPTENTVVATSAEIHPEEGSLSIGRAIANTRVYILGEGNQVQPEGVAGELC
O68006_A3_leu                            KSYQIVNNYGPTENTVVATSFPIDKSHQNIPIGKPIDNVKVYILNKDLQLCPLGASGELC
O69246_A3_6__leu                         RSYTLVNNYGPTENTVVATSAAIDLDEGMLSIGKPIANTRVYVLGQNNEVQPVGVAGELC
                                         : * ::**************  *. ..  :.**:.* *.:.*:*... :: * * :****

P27206_A3_leu                            VAGRGLARGYLNREDETAKRFVADPFVPGERMYRTGDLVKW-TGGGIEYIGRIDQQVKVR
Q70KJ7_A3_leu                            VAGRGLARGYLNREEETAKRFTADPFVPGERMYRTGDLVKWNAQCGIEYIGRIDQQVKVR
Q65NK5_A3_leu                            IAGRGLARGYLNKPEETAKRFTEDPFVPGERMYRTGDAVKWLEDGRLEYIGRIDQQVKIR
Q70KJ6_A3_6__leu                         VAGRGLARGYLNREEETAKRFTADPFVPGERMYRTGDLVKWNAQCGIEYIGRIDQQVKVR
Q45295_A3_leu                            IAGRGLARGYLNKPEETAKRFTEDPFVPGERMYRTGDAVKWLEDGRLEYIGRIDQQVKIR
Q04747_A3_6__leu                         VAGRGLARGYLNREDETAKRFVADPFVPGERMYRTGDLVKW-VNGGIEYIGRIDQQVKVR
O68006_A3_leu                            IAGEGLARGYVNRPELTREKFIGNPFVPGERMYRTGDLAKMLPDGNIQFLGRVDQQVKIR
O69246_A3_6__leu                         IAGRGLARGYLNKPEETAKRFTEDPFVPGERMYRTGDAVKWLEDGRLEYIGRIDQQVKIR
                                         :**.******:*: : * ::*  :************* .*      ::::**:*****:*

P27206_A3_leu                            GYRIELSEIEVQLAQLSEVQDAAVTAVKDKGGNTAIAA
Q70KJ7_A3_leu                            GYRIELSEIEVRLAQLADVHDAAVTAVEDKAGNTALCA
Q65NK5_A3_leu                            GFRIELSEIEVQLARLSEVQEAVVTDIEDAYGNKALCG
Q70KJ6_A3_6__leu                         GYRIELSEIEVRLAQLADVHDAAVTAVEDKAGNTALCA
Q45295_A3_leu                            GFRIELSEIEVQLARLSEVQEAVVTDIEDAYGNKALCS
Q04747_A3_6__leu                         GYRIELSEIEVQLAQLSEVQDAAVTAVKDKGGNTAIAA
O68006_A3_leu                            GYRIEPGEIENRLLKYEKIEEAAVIAREDGDHDPYLCA
O69246_A3_6__leu                         GFRIELSEIEVQLARLSEVQEAVVTDIEDACGNKALCG
                                         *:*** .*** :* :  .:.:*.*   :*   :  :..
