CLUSTAL W multiple sequence alignment


Q84BQ6v1_A1_leu                          LTQRALRGHLPALSVPVIELDQPSWSAGRVDAPKVPGLTPANLAYVIYTSGSTGLPKGVM
Q84BQ4_A1_7__leu                         LTQSHLRERLPALNVPVLDLDHCNWPLTVTQNPQVPGLSTANLAYVIYTSGSTGLPKGVM
AFZ61501.1_498_mod1_leu                  LTQHDLLSRLPALEVPVIQLDRPTF--HLGTNPRV-AVSPSNLAYVIYTSGSTGLPKGVM
Q84BQ6v2_A1_leu                          LTQRALRGHLPALSVPVIELDQPSWSAGRVDAPKVPGLTPANLAYVIYTSGSTGLPKGVM
AFZ61526.1_575_mod1_leu                  LTQQALLERLPALDVPVINLDRFTWQHHSASNPKV-VVTPFNLAYVIYTSGSTGLPKGVM
                                         ***  *  :****.***::**: .:       *:*  ::. *******************

Q84BQ6v1_A1_leu                          VEHRTLCNLVDWHADVFDLHAGSHTSSLAGFGFDAMAWEVWPALCVGATLHLAPASEGSE
Q84BQ4_A1_7__leu                         VEHHTLSNLVDWHCTAFDLCAGRHTSSLAGFGFDAMAWEVWPALCAGATLHLAPTHEGGE
AFZ61501.1_498_mod1_leu                  VEHHTVANLVDWHCQAFDLQAGSHTASVAGFGFDAMAWEIWPALCVGATVHLPPAHDGAE
Q84BQ6v2_A1_leu                          VEHRTLCNLVDWHADVFDLHAGSHTSSLAGFGFDAMAWEVWPALCVGATLHLAPASEGSE
AFZ61526.1_575_mod1_leu                  VEHHTVANLVDWHCNAFDLCAGRHTASVAGFGFDAMAWEVWPALCVGATLHLPPAHDGAE
                                         ***:*:.******. .*** ** **:*:***********:*****.***:**.*: :*.*

Q84BQ6v1_A1_leu                          DIDALLDWWRAQPLDVSFLPTPIAEYAFSRQLDHPTLRTLLIGGDRLRQFPRQPSFEVIN
Q84BQ4_A1_7__leu                         DIDALLAWWCAQPLDVSFLPTPVAEYAFSQNLEHPTLRTLLIGGDRLRQFNRNQHFDVIN
AFZ61501.1_498_mod1_leu                  DIDALLRWWQAQPLQVCFLPTPVAEYAFSQSLQHPTLRTLLIGGDRLRSFTQAQSFAVIN
Q84BQ6v2_A1_leu                          DIDALLDWWRAQPLDVSFLPTPIAEYAFSRQLDHPTLRTLLIGGDRLRQFPRQPSFEVIN
AFZ61526.1_575_mod1_leu                  DIDALLAWWCAQPLDVCFLPTPVAEYAFSQQIEHPTLRTLLIGGDRLRQFGRAQRFDLIN
                                         ****** ** ****:*.*****:******:.::***************.* :   * :**

Q84BQ6v1_A1_leu                          NYGPTEATVVATSGRIDAGQALHIGKPVSNATVYLLDEQQQPVPLGVTGELYVGGAGVAR
Q84BQ4_A1_7__leu                         NYGPTEATVVATSGLVQSGDALHIGKPLSNATVYLLDEQQRPVPLGVAGELYVGGAGVAR
AFZ61501.1_498_mod1_leu                  NYGPTEATVVATSGCMEVGQLLHIGAPIANATVYLLDEQQRPVPIGVAGELYVGGKGVAR
Q84BQ6v2_A1_leu                          NYGPTEATVVATSGRIDAGQALHIGKPVSNATVYLLDEQQQPVPLGVTGELYVGGAGVAR
AFZ61526.1_575_mod1_leu                  NYGPTEATVVATSGKVEAGQPLHIGKPIANATVYLLDEQQRPVPLGVAGELYVGGNGVAR
                                         ************** :: *: **** *::***********:***:**:******* ****

Q84BQ6v1_A1_leu                          GYLNRAELSAERFLRDPFSAEPGARLYRTGDLARWRADGNLEYLGRNDDQVKIRGIRIEP
Q84BQ4_A1_7__leu                         GYLNRPDMTAERFLRDPFSRAPNARMYRTGDLARWREDGNIEYLGRNDDQVKIRGVRIEL
AFZ61501.1_498_mod1_leu                  GYLNRPELSAERFLDDPFI---EGRMYRTGDLARWLPEGSLEYLGRNDDQVKIRGMRIEL
Q84BQ6v2_A1_leu                          GYLNRAELSAERFLRDPFSAEPGARLYRTGDLARWRADGNLEYLGRNDDQVKIRGIRIEP
AFZ61526.1_575_mod1_leu                  GYLNRPELTAERFLQDPFN---TGRMYRTGDLARWLPDGNIEYLGRNDDQVKIRGMRIEL
                                         *****.:::***** ***     .*:*********  :*.:**************:*** 

Q84BQ6v1_A1_leu                          GEIESALASHSAVREAVVLVRDG-----QLLA
Q84BQ4_A1_7__leu                         GEIETCLNQLPGIQEAVLLAREDQPGQPRLVA
AFZ61501.1_498_mod1_leu                  GEIESALATHPHVQDAVVQSRDG-----QLLA
Q84BQ6v2_A1_leu                          GEIESALASHSAVREAVVLVRDG-----QLLA
AFZ61526.1_575_mod1_leu                  GEIETQLNQVAGIQEAVVLVREE-----RLVA
                                         ****: *   . :::**:  *:      :*:*
