CLUSTAL W multiple sequence alignment


BGC0000425_AFH75322.1_5909_mod6_lys      LSEYAVLPLLGTLPQAMQVVTLNSALQPWRELGTHNPQPAQLGLVSEHLAYVLYTSGSTG
CCJ67640.1_5904_mod6_lys                 LSEYAVLPLLGALPQALQVVTLNSALQPWRELGEHNPLAAELGLGSEHLAYVLYTSGSTG
                                         ***********:****:**************** *** .*:*** ***************

BGC0000425_AFH75322.1_5909_mod6_lys      TPKGVMIEHAGLCNEIQAIRGLTGLGAGDRALQFATINFDASIEEIFGALTCGATLVLRS
CCJ67640.1_5904_mod6_lys                 TPKGVMIEHAGLCNEIRAIRGLTGLTAGDRTLQFATINFDASIEEIFGALTCGATLVVRS
                                         ****************:******** ****:**************************:**

BGC0000425_AFH75322.1_5909_mod6_lys      ADWLTDAAHFWSLAAQARLSVISLPTRFWQGLADDHSTVIPASVRVIVVGGEELSPEAVQ
CCJ67640.1_5904_mod6_lys                 AAWLTDAAQFWALAAQARLSVISLPTRFWQGLADDHASAIPASVRVIVVGGEELSPEAVQ
                                         * ******:**:************************::.*********************

BGC0000425_AFH75322.1_5909_mod6_lys      HWFLRSGHTPRLLNTYGPTEATIIATANEVFAANPHPRAIGRPIANTRVYVLDTHGHPTG
CCJ67640.1_5904_mod6_lys                 RWFLRSGHTPRLLNTYGPTEATIIATANEVFAANPHPRAIGRPIANTRVYVLDAHGHPTG
                                         :****************************************************:******

BGC0000425_AFH75322.1_5909_mod6_lys      LGVAGEIHLAGIGIARGYLNQPQLSSERFLADPFSDSPGRLYKTGDLGRWLPDGTLEYLG
CCJ67640.1_5904_mod6_lys                 LGVAGEIHIAGAGIARGYLNQPQLSSERFLADPFSDVPGRLYKTGDLGRWLPDGTLEYLG
                                         ********:** ************************ ***********************

BGC0000425_AFH75322.1_5909_mod6_lys      RNDDQVKIRGFRIELGEVESALLACEGVREAVVMARDDSEGQVAGKQLVA
CCJ67640.1_5904_mod6_lys                 RNDDQVKIRGFRIELGEVESALLACEGVRAAVVMARDDSEGQVSGKQLVA
                                         ***************************** *************:******
