CLUSTAL W multiple sequence alignment


Q847C7_A2_7__me-asp                      VTAAEYLDVVKSRLAALSKPPHILVITANEITQRYEWNGTNYQSFSVVESENPKTLLLPD
Q8G982_A2_9__me-asp                      LIAAENLEMIKPRLLVLAKPPNLLVVNHQEIQQYYEWNGTNYQEFSIVENNNRKDLLMPD
Q9S1A8_A2_9__me-asp                      LVAAENLEGIKPQLSALEKPPHILVVKAHKIQQYHQWNGMDYQEFPCQLSKLQPLLAMPD
Q7WRQ4_A2_9__me-asp                      VVDSENLDIIKPRLALLPKPPQILVINAHEIQQYYQWDGTNYQCLLVEANHDKKVLIMPD
                                         :  :* *: :*.:*  * ***::**:. ::* * ::*:* :** :    ..    * :**

Q847C7_A2_7__me-asp                      ADDSNYIMFTSGSTGEPKAILGSHGSLRHFINWEKIEFGINQNWRCLQIAQINFDAYLRE
Q8G982_A2_9__me-asp                      ADDANYIIFTSGSTGEPKAILGSHGSLRHFINWEKIEFGINHNWRCLQIAQINFDPYLRE
Q9S1A8_A2_9__me-asp                      ADDSNYIMFTSGSTGEPKAILGSHGSLRHFIDWEKREFGINESWHCLQIAQINFDAYLRE
Q7WRQ4_A2_9__me-asp                      ADDSNYIMFTSGSTGEPKAILGSHGSLRHFINWEKLEFGINSNWRCLQIAQINFDAYLRE
                                         ***:***:***********************:*** ***** .*:**********.****

Q847C7_A2_7__me-asp                      TLVTLCSGGTLYIPDSTDREDLEGLLLRLGEWQINLLHTVPSVMRLFLKIGENLAHADQL
Q8G982_A2_9__me-asp                      TLVTLCSGGTLYIPDSIDREDLERLLLRLGEWQINLLHTVPSVMRLFLNIGRNLPNANQL
Q9S1A8_A2_9__me-asp                      TCVTLCSGGTLYIPESTEREDLELLLLRIGEWEINLLHTVPSVMRLFLKIGRGLVNAHNL
Q7WRQ4_A2_9__me-asp                      TLVTLCSGGTLYIPDSTDREDLEKLLLRLGEWQINLLHTVPSVMRLFLKIGRNLTNADQL
                                         * ************:* :***** ****:***:***************:**..* :*.:*

Q847C7_A2_7__me-asp                      LKNLQVLVLGGEPLFVKELCEWHKVFGEQTEFVNIYGASETTFVKHFYRIPDPSKITYAR
Q8G982_A2_9__me-asp                      LKNLQVLVLGGEPLFVKELCEWHEVFGNQTEFVNIYGASETTFIKHFHRIPKPNNISYAR
Q9S1A8_A2_9__me-asp                      LKSLRIFVLGGEPLFVKELAEWHQIFGSQTEFVNIYGASETTFVKHFYRIPNPNNIPYER
Q7WRQ4_A2_9__me-asp                      LKNLRVLVLGGEPLFVKELREWHQVFGSQTEFVNIYGASETTFVKHFHRIPDPNKITYAR
                                         **.*:::************ ***::**.***************:***:***.*.:*.* *

Q847C7_A2_7__me-asp                      VPAGKTLSDAAFAVINGTRPCAVGEVGEIFVKSPYLTKGYYQDQKLTNLVFVPNPLNNGS
Q8G982_A2_9__me-asp                      VPGGKTLPDAAFAVIDENRPCAIGEVGEIFVKSPYLTKGYYQDEILTNSVFVPNPLNNGN
Q9S1A8_A2_9__me-asp                      VPGGQTLPDAAYAVVDGNRARAIGEVGEVFVKSPYLTKGYYQDESLTHSVFVPNPLNGGR
Q7WRQ4_A2_9__me-asp                      VPGGKTLPEAAFAVIDGTRPCAVGEVGEIFVKSPYLTKGYYQDQRLTNSVFIPNPLNHGA
                                         **.*:**.:**:**:: .*. *:*****:**************: **: **:***** * 

Q847C7_A2_7__me-asp                      DLVYRTGDLGRLLPDMSLEVVG-RSDNQIKLNGVRIELGEIENAIYAIDGVEKTLVVAEK
Q8G982_A2_9__me-asp                      DLVYRTGDLGRLLPDLTLEVIGRRSDNQIKLNGVRIELGEIEDAVAAIDGVQKALVIADK
Q9S1A8_A2_9__me-asp                      DIVYRTGDLGRLLPDLTLEVIG-RSDNQIKLNGVRIELGEIEDVLSGIEGVEKALVMANK
Q7WRQ4_A2_9__me-asp                      DIVYCTGDLGRLLPDLTVEVIG-RSDKQVKLNGVRIELGEIEDALAAIDGVEKALVIAEE
                                         *:** **********:::**:* ***:*:*************:.: .*:**:*:**:*::

Q847C7_A2_7__me-asp                      KEELVTVIA
Q8G982_A2_9__me-asp                      KEELVTVIA
Q9S1A8_A2_9__me-asp                      KEELVTVIA
Q7WRQ4_A2_9__me-asp                      KEELVTVIA
                                         *********
