CLUSTAL W multiple sequence alignment


BGC0000439_AHH53507.1_475_mod1_orn       --LTTTANHLPDHPAPTLALDDAPARAELLAAPTRTPRDVDRVVPAHPAHPAYVIYTSGS
BGC0000423_CBG75492.1_4248_mod4_orn      LSTAELAAKLP-EGAPVVLIDDLVPDEG--EAPA--------VVPPAPSGTAYVIFTSGS
AHH53507.1_475_mod1_orn                  --LTTTANHLPDHPAPTLALDDAPARAELLAAPTRTPRDVDRVVPAHPAHPAYVIYTSGS
CBG75492_4248_mod4_orn                   LSTAELAAKLP-EGAPVVLIDDLVPDEG--EAPA--------VVPPAPSGTAYVIFTSGS
Q50E73_A1_6__orn                         --TTTTATPLP-HPGRTLVLDSPTTARALAAAPAHNLTDADRRTPLNARNAAYIIHTSGS
                                            :  *  ** . . .: :*.  .      **:         .*  .  .**:*.****

BGC0000439_AHH53507.1_475_mod1_orn       TGRPKGVVLTHEGLRNLYHDHATGLIEP--HAPRTRRLRAGLSAALSFDTSWECLLSLAA
BGC0000423_CBG75492.1_4248_mod4_orn      TGTPKGVVGTHRGLSNLFAAHRDDLIRPAERSLGRDRLRAVHAASFSFDGSWEPLLWLLA
AHH53507.1_475_mod1_orn                  TGRPKGVVLTHEGLRNLYHDHATGLIEP--HAPRTRRLRAGLSAALSFDTSWECLLSLAA
CBG75492_4248_mod4_orn                   TGTPKGVVGTHRGLSNLFAAHRDDLIRPAERSLGRDRLRAVHAASFSFDGSWEPLLWLLA
Q50E73_A1_6__orn                         TGRPKGVVIEHRSLANLFHDHRRALIEP--HAAGGSRLKAGLTASLSFDTSWEGLICLAA
                                         ** *****  *..* **:  *   **.*  ::    **:*  :*::*** *** *: * *

BGC0000439_AHH53507.1_475_mod1_orn       GHELHLVDDDTRRDAELLVRYVEHHRLDLLDLTPSHAQQLVETGLLAEDAHHPTVLMLGG
BGC0000423_CBG75492.1_4248_mod4_orn      GHEVQVVEEAVMADPAALLAHLCREDIDFLDVTPTYLRELIHHGFLEPGTPLPGVIAVGG
AHH53507.1_475_mod1_orn                  GHELHLVDDDTRRDAELLVRYVEHHRLDLLDLTPSHAQQLVETGLLAEDAHHPTVLMLGG
CBG75492_4248_mod4_orn                   GHEVQVVEEAVMADPAALLAHLCREDIDFLDVTPTYLRELIHHGFLEPGTPLPGVIAVGG
Q50E73_A1_6__orn                         GHELHLIDDDTRRDAERVAELIDRQRIDVIDVTPSFAQQLVETGILDEGRHHPAAFMLGG
                                         ***:::::: .  *.  :   : :. :*.:*:**:. ::*:. *:*  .   * .: :**

BGC0000439_AHH53507.1_475_mod1_orn       EAVPPALWSRLRAAPHTRCYNYYGPTEFTVDAVACALDESEHPIVGRPLDNTRAYVLNAA
BGC0000423_CBG75492.1_4248_mod4_orn      EATPAPLWERLCALPGVQVHDLYGPTESAVDAYGWHSDATGR--WAAPLDNIRAHVLDEL
AHH53507.1_475_mod1_orn                  EAVPPALWSRLRAAPHTRCYNYYGPTEFTVDAVACALDESEHPIVGRPLDNTRAYVLNAA
CBG75492_4248_mod4_orn                   EATPAPLWERLCALPGVQVHDLYGPTESAVDAYGWHSDATGR--WAAPLDNIRAHVLDEL
Q50E73_A1_6__orn                         EGVDAKLWTRLSDVPGVTSYNYYGPTEFTVDALACTVGIAPRPVIGHPLDNTAAYILDGF
                                         *.. . ** **   * .  :: ***** :*** .   . : :   . ****  *::*:  

BGC0000439_AHH53507.1_475_mod1_orn       LLPVAPGVPGELYLAGPQLARGYLGRAALTADRFVACPFGTPGERMYRTGDLAAWTEHGT
BGC0000423_CBG75492.1_4248_mod4_orn      LRPVPAGVTGELYLAGEGLARGYLNRPGLTAERFTADPFGAPGSRMYRTGDLVRRRRDGS
AHH53507.1_475_mod1_orn                  LLPVAPGVPGELYLAGPQLARGYLGRAALTADRFVACPFGTPGERMYRTGDLAAWTEHGT
CBG75492_4248_mod4_orn                   LRPVPAGVTGELYLAGEGLARGYLNRPGLTAERFTADPFGAPGSRMYRTGDLVRRRRDGS
Q50E73_A1_6__orn                         LRPVPEGVAGELYLAGTQLARGYAGRPGLTAERFVACPFGAPGERMYRTGDLVRRSPGGV
                                         * **. **.*******  ***** .*..***:**.* ***:**.********.     * 

BGC0000439_AHH53507.1_475_mod1_orn       LRFLGRADGQVKIRGFRVELGEVEHALLTHPSVGQCAVVAARTEPAGTRLVA
BGC0000423_CBG75492.1_4248_mod4_orn      LEFLGRADGQVKLRGFRIEPGEIEALLARHPDVATAAVVVREDTPGVRRLVA
AHH53507.1_475_mod1_orn                  LRFLGRADGQVKIRGFRVELGEVEHALLTHPSVGQCAVVAARTEPAGTRLVA
CBG75492_4248_mod4_orn                   LEFLGRADGQVKLRGFRIEPGEIEALLARHPDVATAAVVVREDTPGVRRLVA
Q50E73_A1_6__orn                         VEYLGRVDDQIKLRGFRIEPAEIELALAGHPAVAQNVVLLHRSATGEARLVA
                                         :.:***.*.*:*:****:* .*:*  *  ** *.  .*:  .  ..  ****
