CLUSTAL W multiple sequence alignment


P0C064_A3_4__orn                         LTQQKLTQQIAFSGDILYLDQEEWLHEEASNLEPIARPQDIAYIIYTSGTTGKPKGVMIE
O68007_A2_7__orn                         LTQHQLIGSISFAGEIIQIDQADAYDTDGSNLEHLNSPGDLAYVIYTSGTTGNPKGVMVE
O33743_A5_9__orn                         LTLQKMNSQVAFPYETFYLDTETVDQEETGNLEHVAQPENVAYIIYTSGTTGKPKGVVIE
P0C063_A3_orn                            LTQQKLTQQIAFSGDILYLDQEEWLHEEASNLEPIARPHYIAYIIYTSGTTGKPKGVMIE
                                         ** :::  .::*. : : :*     . : .*** :  *  :**:********:****::*

P0C064_A3_4__orn                         HQSYVNVAMAWKDAYRLDTFPVRLLQMAS--FAFDVSAGDFARALLTGGQLIVCPNEVKM
O68007_A2_7__orn                         HRNIIHAHYTWRKHYELASFSVNLLQLAS--MSFDVFAGDLCRSLLNGGTMYIVPDDVKL
O33743_A5_9__orn                         HRSYANVAFAWKDEYHLDSFPVRLLQMAS--FAFDVSTGDFARALLTGGQLVICPNGVKM
P0C063_A3_orn                            HQSYVNVAMAWKDAYRLDTFPVRLLQMASFAFAFDVSAGDFARALLTGGQLIVCPNEVKM
                                         *:.  :.  :*:. *.* :*.*.***:**  ::*** :**:.*:**.** : : *: **:

P0C064_A3_4__orn                         DPASLYAIIKKYDITIFEATPALVIPLMEYIYEQKLDISQLQILIVGSDSCSMEDFKTLV
O68007_A2_7__orn                         EMNLLYDMINKYGIHMLESTPSLIIPLMKYIDHHKLDFSSMKLLIMGSDTCTIKDYKWLV
O33743_A5_9__orn                         DPASLYETIRRHEITIFEATPALIMPLMHYVYENELDMSQMKLLILGADSCPAEDFKTLL
P0C063_A3_orn                            DPASLYAIIKKYDITIFEATPALVIPLMEYIYEQKLDISQLQILIVGSDSCSMEDFKTLV
                                         :   **  *.:: * ::*:**:*::***.*: .::**:*.:::**:*:*:*. :*:* *:

P0C064_A3_4__orn                         SRFGSTIRIVNSYGVTEACIDSSYYEQPLSSLHVTGTVPIGKPYANMKMYIMNQYLQIQP
O68007_A2_7__orn                         ERFGQRMRIINSYGVTEASVDSGYYEEALDRIPEIANTPIGKPLDNTAFYILDPSLNPQP
O33743_A5_9__orn                         ARFGQKMRIINSYGVTEACIDTSYYEETDVTAIRSGTVPIGKPLPNMTMYVVDAHLNLQP
P0C063_A3_orn                            SRFGSTIRIVNSYGVTEAALILAIMNQPLSSLHVTGTVPIGKPYANMKMYIMNQYLQIQP
                                          ***. :**:********.:  .  ::.       ...*****  *  :*:::  *: **

P0C064_A3_4__orn                         VGVIGELCIGGAGVARGYLNRPDLTAEKFVPNPFVPGEKLYRTGDLARWMPDGNVEFLGR
O68007_A2_7__orn                         VGVYGELYIGGEGIARGYLNKPELTKERFVPNRFAAGGNMYKTGDLARWLPDGNVEFLGR
O33743_A5_9__orn                         VGVVGELCIGGAGVARGYLNRPELTEEKFVPNPFAPGERLYRTGDLAKWRADGNVEFLGR
P0C063_A3_orn                            VGVIGELCIGGAGVARGYLNRPDLTAEKFVPNPFVPGEKLYRTGDLARWMPDGNVEFLGR
                                         *** *** *** *:******:*:** *:**** *..* .:*:*****:* .*********

P0C064_A3_4__orn                         NDHQVKIRGIRIELGEIEAQLRKHDSIKEATVIAREDHMKEKYLCA
O68007_A2_7__orn                         IDHQVKIRGFRIETGEIETKLLENQNISEAVVIDREDKKGHKYLCA
O33743_A5_9__orn                         NDHQVKIRGVRIELGEIETQLRKLDGITEAVVVAREDRGQEKELCA
P0C063_A3_orn                            NDHQVKIRGIRIELGEIEAQLRKHDSIKEATVIAREDHMKEKYLCA
                                          ********.*** ****::* : :.*.**.*: ***:  .* ***
