CLUSTAL W multiple sequence alignment


P39845_A2_orn                            LLQRELKHLISNSPESEMSHIFLDDEGSFEESNCNLNLSPAPEEPVYIIYTSGTTGAPKG
O33743_A5_9__orn                         LTLQKMNSQVAFPYE----TFYLDTETVDQEETGNLEHVAQPENVAYIIYTSGTTGKPKG
P0C063_A3_orn                            LTQQKLTQQIAFSGD----ILYLDQEEWLHEEASNLEPIARPHYIAYIIYTSGTTGKPKG
P0C064_A3_4__orn                         LTQQKLTQQIAFSGD----ILYLDQEEWLHEEASNLEPIARPQDIAYIIYTSGTTGKPKG
O87606_A2_orn                            LLQNEVKHLIAGSDIGDISRVCLDDESFYESKKMHLSSSPAPEDSAYIIYTSGTTGAPKG
Q70JX1_A2_orn                            MVQSEYKELASQLTDHNLFLIQLDLEDQYDICAKNIQPSASPDDTAYIIYTSGTTGTPKG
                                         :   : .   :         . ** *   .    ::.  . *.  .********** ***

P39845_A2_orn                            VIVTYQNFTHAALAWRQIYELDRKPVRLLQIAS--FSFDVFSGDLARTLTNGGTLIVCPD
O33743_A5_9__orn                         VVIEHRSYANVAFAWKDEYHLDSFPVRLLQMAS--FAFDVSTGDFARALLTGGQLVICPN
P0C063_A3_orn                            VMIEHQSYVNVAMAWKDAYRLDTFPVRLLQMASFAFAFDVSAGDFARALLTGGQLIVCPN
P0C064_A3_4__orn                         VMIEHQSYVNVAMAWKDAYRLDTFPVRLLQMAS--FAFDVSAGDFARALLTGGQLIVCPN
O87606_A2_orn                            VIVTHRNFAHAVLAWRRIYQLDQMPVRLLQMAS--FSFDVFSGDLARTLANGGTLVICPD
Q70JX1_A2_orn                            VEVRNRSFTHAALAWRRIYELDLIPVRVLQMAS--FSFDVFSGDLARALLNGGTLVICPD
                                         * :  :.:.:..:**:  *.**  ***:**:**  *:*** :**:**:* .** *::**:

P39845_A2_orn                            ETRLEPAEIYKIIKSQRITVMESTPALIIPVMEYVYRNQFKLPDLDILILGSDMVKAQDF
O33743_A5_9__orn                         GVKMDPASLYETIRRHEITIFEATPALIMPLMHYVYENELDMSQMKLLILGADSCPAEDF
P0C063_A3_orn                            EVKMDPASLYAIIKKYDITIFEATPALVIPLMEYIYEQKLDISQLQILIVGSDSCSMEDF
P0C064_A3_4__orn                         EVKMDPASLYAIIKKYDITIFEATPALVIPLMEYIYEQKLDISQLQILIVGSDSCSMEDF
O87606_A2_orn                            ETRLEPAELYALMNRQRITIMESTPALIVPFMEYVYRNQLSLPDLDILILGSDMVKAHDF
Q70JX1_A2_orn                            DVRLEPQQLYRLIDQHRITFMESTPALVVPFMEYIYRRKLALQSVKILVLGSDMIKSQDF
                                          .:::* .:*  :    **.:*:****::*.*.*:*..:: : .:.:*::*:*    .**

P39845_A2_orn                            KTLTDRFGQSMRIINSYGVTEATIDSSFYETSMGGECTGDNVPIGSPLPNVHMYVLSQTD
O33743_A5_9__orn                         KTLLARFGQKMRIINSYGVTEACIDTSYYEETDVTAIRSGTVPIGKPLPNMTMYVVDAHL
P0C063_A3_orn                            KTLVSRFGSTIRIVNSYGVTEAALILAIMNQPLSSLHVTGTVPIGKPYANMKMYIMNQYL
P0C064_A3_4__orn                         KTLVSRFGSTIRIVNSYGVTEACIDSSYYEQPLSSLHVTGTVPIGKPYANMKMYIMNQYL
O87606_A2_orn                            KTLADRFGNKMRLINSYGVTEATIDSSYYEMNMGEEYSGDSVPIGIPLPNVKLCVLSQTD
Q70JX1_A2_orn                            YTLHERFGKEMRIINSYGVTEATIDSSYYEAEMSEEPREDDVPIGVPLPNVQMYVLNKDK
                                          **  ***. :*::******** :  :  :         . **** * .*: : ::.   

P39845_A2_orn                            QIQPIGVAGELCIGGAGVAKGYHHKPDLTQMKFTENPFVSGERLYRTGDRACWLPNGTIR
O33743_A5_9__orn                         NLQPVGVVGELCIGGAGVARGYLNRPELTEEKFVPNPFAPGERLYRTGDLAKWRADGNVE
P0C063_A3_orn                            QIQPVGVIGELCIGGAGVARGYLNRPDLTAEKFVPNPFVPGEKLYRTGDLARWMPDGNVE
P0C064_A3_4__orn                         QIQPVGVIGELCIGGAGVARGYLNRPDLTAEKFVPNPFVPGEKLYRTGDLARWMPDGNVE
O87606_A2_orn                            QIQPIGIAGELCIAGAGVAKGYHGKFELTEKKFTENPFVPGERLYRTGDLACWLPNGTLR
Q70JX1_A2_orn                            QVQPIGVFGELYIGGAGVAKGYWGQPELTEGAFSD-PLQMGETLYRTGDQACWLPDGTLR
                                         ::**:*: *** *.*****:**  : :**   *   *:  ** ****** * * .:*.:.

P39845_A2_orn                            LLGRMDYQVKINGYRIETEEIESVLLQTGLVREAAVAVQHDKNGQAGLAA
O33743_A5_9__orn                         FLGRNDHQVKIRGVRIELGEIETQLRKLDGITEAVVVAREDRGQEKELCA
P0C063_A3_orn                            FLGRNDHQVKIRGIRIELGEIEAQLRKHDSIKEATVIAREDHMKEKYLCA
P0C064_A3_4__orn                         FLGRNDHQVKIRGIRIELGEIEAQLRKHDSIKEATVIAREDHMKEKYLCA
O87606_A2_orn                            LLGRIDHQVKINGYRIETEEIESVLLQTGLVNEAVVAVQNDTNGQARLAA
Q70JX1_A2_orn                            FQGRIDKQVKIRGYRIETGEIESVLLKHDQVKEAAVTVIKDAEGQARLAA
                                         : ** * ****.* ***  ***: * : . : **.* . .*   :  *.*
