CLUSTAL W multiple sequence alignment


Q9FDT8_ALod_phe-ac                       LGTYSHLEGWQVISVNELR-----------KAPSKIEQLPILDPQDAALLLFTSGSTGMP
Q7WRJ0/31616733_ALod_phe-ac              LTTQSHLKELRVVSIDKLRSNQSLSNQL------SAHELPHLTPLDPALLLFTSGSTGLP
Q8G985/24744795_ALod_phe-ac              LETQSHLKGLQVVSIDYLRSIESQSNSQPDKTSKKCYSLPDLTPENQALLLFTSGSTGMP
                                         * * ***:  :*:*:: **               .  .** * * : ***********:*

Q9FDT8_ALod_phe-ac                       KGVILTHHNILSMTAGTVVMNHFTQQEVTLNWMPLDHVGAIVFLGIMAVDLACDQIHVPM
Q7WRJ0/31616733_ALod_phe-ac              KGVMLHHRNLLSMSVGTVRMNNFTRQEVTLNWMPLDHVGAIVFLGIMAVDLACHQIHVPI
Q8G985/24744795_ALod_phe-ac              KGVMLTHNNLLSMSAGTVAMNNFSQQEVTLNWMPLDHAGAIVFLGIMAVDLACDQIHVPM
                                         ***:* *.*:***:.*** **:*::************.***************.*****:

Q9FDT8_ALod_phe-ac                       ELVLRQPLQWLELIQKHQVSISWSPNFAFSLINQQAEELKHVSYNLSSMKFLVNAGEQVS
Q7WRJ0/31616733_ALod_phe-ac              ELILRQPLKWLGLIQKYQATISWSPNFAFSLINQHTEELNQSCYDLSSIKFLVNAGEQVS
Q8G985/24744795_ALod_phe-ac              ELILRQPLKWLELIQNHQATISWAPNFAFSLINQQSEQLNQSSYNLSSMKFLVNAGEQVS
                                         **:*****:** ***::*.:***:**********::*:*:: .*:***:***********

Q9FDT8_ALod_phe-ac                       VKTIRLFLEILEKHQLQERAIKPAFGMTESCSGITWSAGLSKNELTEENSFVSLGKPIPG
Q7WRJ0/31616733_ALod_phe-ac              VKTIRLFLEILEKHKLRDRVIKPAFGMTESCSGITWSAGLSKDELIEENSFVSLGRPIPG
Q8G985/24744795_ALod_phe-ac              IKTIRLFLEILEKHQLPDRAIKPAFGMTESCSGITWSVGLSQDKLTEENIIISLGKPIPG
                                         :*************:* :*.*****************.***:::* *** ::***:****

Q9FDT8_ALod_phe-ac                       ATIRIVDQENNPLPEREIGRLQIQGNSVTKGYYNNNELNQEVFQ-EGWFTTGDLGYLSKG
Q7WRJ0/31616733_ALod_phe-ac              ATIRIIDQENNILPENEVGRLQIKGPSVTEGYYNNPDLNQEVFQDGGWFTTGDLGYLHNG
Q8G985/24744795_ALod_phe-ac              ATIRIVDQENNVLPEAEIGRLQIKGKSVTKEYYHNPELNQEVFQDEGWFTTGDLAYLLDG
                                         *****:***** *** *:*****:* ***: **:* :*******  ********.** .*

Q9FDT8_ALod_phe-ac                       ELFITGREKQEIIINGVNYFAHELETTIEELEGVKVSYTAAFAVFDQSRETDLLIIT
Q7WRJ0/31616733_ALod_phe-ac              ELVITGREKQEIIINGINYFAHEIETAIEELDGVAISYTAAFAVFDQNRETDLLVIT
Q8G985/24744795_ALod_phe-ac              ELFITGREKQEIIINGINYFAHEIETVIEELEGVNVSYTAAFALFDQIQETDLLIII
                                         **.*************:******:**.****:** :*******:*** :*****:* 
