CLUSTAL W multiple sequence alignment


O30408_A3_4__phe                         VTH---AHLLHKVSSQSEVVDVDDPGSYATQTDNLPCANTPSDLAYIIYTSGTTGKPKGV
P0C062_A1_1__phe                         LTQKHLVHLIHNIQFNGQVEIFEEDTIKIREGTNLHVPSKSTDLAYVIYTSGTTGNPKGT
P09095_A1_phe                            LTQKSVSQLVHDVGYSGEVVVLDEEQLDARETANLHQPSKPTDLAYVIYTSGTTGKPKGT
BGC0000426_AGZ03650.1_37_mod1_phe        ITTKEISQ---NIRFEGEHVLLYDDSIWHFPKENPNVKIQVTDLAYVIYTSGTTGQPKGV
                                         :*     :   .:  ..:   . :         *       :****:********:***.

O30408_A3_4__phe                         MLEHKGVANLQAVFAHHLGVTPQDRAGHFASISFDASVWDMFGPLLSGATLYVLSRDVIN
P0C062_A1_1__phe                         MLEHKGISNLKVFFENSLNVTEKDRIGQFASISFDASVWEMFMALLTGASLYIILKDTIN
P09095_A1_phe                            MLEHKGIANLQSFFQNSFGVTEQDRIGLFASMSFDASVWEMFMALLSGASLYILSKQTIH
BGC0000426_AGZ03650.1_37_mod1_phe        MVEHKGIANLKVVWEESFGISPRDRIGFFASISFDASVWEIFMALLNGATLYVLSKELLS
                                         *:****::**: .: . :.:: :** * ***:*******::* .**.**:**:: :: : 

O30408_A3_4__phe                         DFQRFAEYVRDNAITFLTLPPTYAIYLEPEQVPSLRTLITAGSASSVALVDKWKEKVTYV
P0C062_A1_1__phe                         DFVKFEQYINQKEITVITLPPTYVVHLDPERILSIQTLITAGSATSPSLVNKWKEKVTYI
P09095_A1_phe                            DFAAFEHYLSENELTIITLPPTYLTHLTPERITSLRIMITAGSASSAPLVNKWKDKLRYI
BGC0000426_AGZ03650.1_37_mod1_phe        NLCEFQNYLGENSITVMTLPPSYAQYLDPVSLFDLRLLITAGSAPSQSLVNKWNQIVTYV
                                         ::  * .*: :: :*.:****:*  :* *  : .:: :******.* .**:**:: : *:

O30408_A3_4__phe                         NGYGPTESTVCATLWKA-KPDEPVETITIGKPIQNTKLYIVDDQLQLKAPGQMGELCISG
P0C062_A1_1__phe                         NAYGPTETTICATTWVA-TKETTGHSVPIGAPIQNTQIYIVDENLQLKSVGEAGELCIGG
P09095_A1_phe                            NAYGPTETSICATIWEAPSNQLSVQSVPIGKPIQNTHIYIVNEDLQLLPTGSEGELCIGG
BGC0000426_AGZ03650.1_37_mod1_phe        NAYGPTETSICATNWIAPREWCNASHIPIGTPIRNTQVYILDDNLQPVATGESGQLWVGG
                                         *.*****:::*** * *         :.** **:**::**::::**  . *. *:* :.*

O30408_A3_4__phe                         LSLARGYWNRPELTAEKFVDNPFVPGTKMYRTGDLARWLPDGTIEYLGRIDHQVKIRGHR
P0C062_A1_1__phe                         EGLARGYWKRPELTSQKFVDNPFVPGEKLYKTGDQARWLPDGNIEYLGRIDNQVKIRGHR
P09095_A1_phe                            VGLARGYWNRPDLTAEKFVDNPFVPGEKMYRTGDLAKWLTDGTIEFLGRIDHQVKIRGHR
BGC0000426_AGZ03650.1_37_mod1_phe        VGLARGYLNRPELTAEKFIDNPFIPGEKLYCTGDYARWLSDGNIEYRGRMDHQVKIRGYR
                                          .***** :**:**::**:****:** *:* *** *:**.**.**: **:*:******:*

O30408_A3_4__phe                         VELGEVESVLLRYDTVKEAAAITHEDDRGQAYLCA
P0C062_A1_1__phe                         VELEEVESILLKHMYISETAVSVHKDHQEQPYLCA
P09095_A1_phe                            IELGEIESVLLAHEHITEAVVIAREDQHAGQYLCA
BGC0000426_AGZ03650.1_37_mod1_phe        IELGEIEAVLQKHSGISEAAVLVKKDKLGNPFLSA
                                         :** *:*::*  :  :.*:.. .::*.    :*.*
