CLUSTAL W multiple sequence alignment


Q9KID8v2_A1_pip                          ALDDPELDRQPDDTAPDVELDRDSLAYAIYTSGSTGRPKAVLMPGVSAVNLLLWQERTMG
Q9ZGA6_A1_11__pip                        TPDDPDLGRQP-DTAPHLTLGRDSLAYAIYTSGSTGKPKAVLMPGVSAVNLLLWQERTMG
Q9KID8v1_A1_pip                          ALDDPELDRQPDDTAPDVELDRDSLAYAIYTSGSTGRPKAVLMPGVSAVNLLLWQERTMG
Q54298_A1_pip                            LPDDPGLENQP-ASPPDVTTDRNSLAYAIYTSGSTGRPKAVLMPGICVVNLLLWQERTMG
                                           *** * .**  :.*.:  .*:*************:********:..************

Q9KID8v2_A1_pip                          REPASRTVQFVTPTFDYSVQEIFSALLGGTLVIPPDEVRFDPPGLARWMDEQAITRIYAP
Q9ZGA6_A1_11__pip                        REPASRTVQFVTATFDYSVQEIFSALLGGTLVIPPDEARFDPPGLARWMDEQAITRIYAP
Q9KID8v1_A1_pip                          REPASRTVQFVTPTFDYSVQEIFSALLGGTLVIPPDEVRFDPPGLARWMDEQAITRIYAP
Q54298_A1_pip                            REPASRTAQFITATFDYSVQEIFSALLGGTLVIPPDDIRLDPARLAQWIDDSRITRIYAP
                                         *******.**:*.***********************: *:**. **:*:*:. *******

Q9KID8v2_A1_pip                          TAVLRALIEHVDPHSDQLAALRHLCQGGEALILDARLRELCRHRPHLRVHNHYGPAESQL
Q9ZGA6_A1_11__pip                        TAVLRALVEHVDPHSDQLSALRHLCQGGEALALDARLRELCRHRPHLRVHNHYGPAESQL
Q9KID8v1_A1_pip                          TAVLRALIEHVDPHSDQLAALRHLCQGGEALILDARLRELCRHRPHLRVHNHYGPAESQL
Q54298_A1_pip                            TTVLRALVEHVDPHGHGLVDIASPLPGGESLVLDGKLRECALHRPHLRVHNHYGPAESQL
                                         *:*****:******.. *  :     ***:* **.:*** . ******************

Q9KID8v2_A1_pip                          ITGYTLPADPDAWPATAPIGPPIDNTRIHLLDEAMRPVPDGMPGQLCVAGVGLARGYLAR
Q9ZGA6_A1_11__pip                        ITGYTLPADPDTWPAAAPIGRPIDNTRIHLLDDALRPVPDGMPGQLCVAGIGLARGYLAR
Q9KID8v1_A1_pip                          ITGYTLPADPDAWPATAPIGPPIDNTRIHLLDEAMRPVPDGMPGQLCVAGVGLARGYLAR
Q54298_A1_pip                            VTGYTLPEDVSAWPSTTPIGKPIDNTRIHLLDDALRPYPTAYAAQVCISGIGLARGYLAR
                                         :****** * .:**:::*** ***********:*:** * . ..*:*::*:*********

Q9KID8v2_A1_pip                          PELTAERWVPGDAVGEERMYLTGDLARRAPDGDLEFLGRIDDQVKIRGIRVEPGEIESLL
Q9ZGA6_A1_11__pip                        PELTAERWVSGGATGEERMYLTGDLARRAPGGDLDFLGRIDDQVKIRGIRIEPGEVENVL
Q9KID8v1_A1_pip                          PELTAERWVPGDAVGEERMYLTGDLARRAPDGDLEFLGRIDDQVKIRGIRVEPGEIESLL
Q54298_A1_pip                            PELTRQRFITEGTGSEPRMYLSGDLARRLPDGNLEFLGRIDDQVKIRGIRIELGEIETAL
                                         **** :*::. .: .* ****:****** *.*:*:***************:* **:*. *

Q9KID8v2_A1_pip                          AEDARVTQAAVSVREDRRGEKFLAA
Q9ZGA6_A1_11__pip                        AEDARVAHAAVSVREDPRGEKFLAA
Q9KID8v1_A1_pip                          AEDARVTQAAVSVREDRRGEKFLAA
Q54298_A1_pip                            SEHAAITQAAVTVREDDRGDKRLVA
                                         :*.* :::***:**** **:* *.*
