CLUSTAL W multiple sequence alignment


Q6YK40_A3_pro                            VTEKDRSVPEAATQIVTFIEEAET-EPDGSNVQTINTAEDLLYVIYTSGTTGKPKGVLLE
Q93I55_A4_pro                            LTCAGHAIPPLFEGEVLLLDDPLLYQGRTDNLNLSCSENDLMYVIYTSGTTGQPKGVQLE
O30408_A1_2__pro                         VTQNHLRAKVTTPTETIDINTAVIGEESRAPIESLNQPHDLFYIIYTSGTTGQPKGVMLE
Q70JZ9_A3_pro                            VTEKDRSVPEAATQIVTFIEEAET-EPDGSNVQTINTAEDLLYVIYTSGTTGKPKGVLLE
P94459_A1_pro                            VSQAHLPSSLEDNYIITHPEDIES-KVDGSNIKSVNNADDLLYMIYTSGTTGKPKGVQFE
AGM16413.1_5398_mod5_pro                 LTELAWFEVIPPEVEKVDIHDASLYQGHDENVPNESEPSNLLYIIYTSGTTGNPKGVMLE
BGC0000400_AGM16413.1_5398_mod5_pro      LTELAWFEVIPPEVEKVDIHDASLYQGHDENVPNESEPSNLLYIIYTSGTTGNPKGVMLE
Q9R9J0_A4_pro                            VTCVEHTVPPSFEGSVVLLDDPLVYQGDASNLNLSYAENHLLYVIYTSGTTGKPKGVQLE
P0C063_A1_pro                            LTQRHLKDKFAFTKETIVIEDPSISHELTEEIDYINESEDLFYIIYTSGTTGKPKGVMLE
O30980_A1_pro                            VSQAHFAPLLETGLNVIYMEDIQI-E-DGSCLHSVNSADDLLYMIYTSGTTGKPKGVQFE
P0C064/68845359_A1_2__pro                LTQRHLKDKFAFTKETIVIEDPSISHELTEEIDYINESEDLFYIIYTSGTTGKPKGVMLE
O30980_A1_7__pro                         VSQAHFAPLLETGLNVIYMEDIQI-E-DGSCLHSVNSADDLLYMIYTSGTTGKPKGVQFE
                                         ::                 .     .     :       .*:*:********:**** :*

Q6YK40_A3_pro                            HRNMANLLYDQFTNSGIDFKTNVLQYASPAFDVCYQELFSALLSGGTLHIVPESIKRDAA
Q93I55_A4_pro                            HKTMTNLLAYEQDHTQLRF-DRVLQFAAMSFDVCYQEMFSALSSGGTLFIIGNEAKRDIR
O30408_A1_2__pro                         HRNMANLMHFTFDQTNIAFHEKVLQYTTCSFDVCYQEIFSTLLSGGQLYLITNELRRHVE
Q70JZ9_A3_pro                            HRNMANLLYDQFTNSGIDFKTNVLQYASPAFDVCYQELFSALLSGGTLHIVPESIKRDAA
P94459_A1_pro                            HRNMANLLKFEYTHSGIDFEADVLQFATPSFDVCYQEIFSALLKGGTLHIVPEAIKRDVP
AGM16413.1_5398_mod5_pro                 QRNLINLLHYEQVGTSIPLPSRILQYASNSFDVCYQEMFSALLFGGCLFLIPNEARKDPA
BGC0000400_AGM16413.1_5398_mod5_pro      QRNLINLLHYEQVGTSIPLPSRILQYASNSFDVCYQEMFSALLFGGCLFLIPNEARKDPA
Q9R9J0_A4_pro                            HKTMLNLLAYEREYTQLRF-DRVLQFAAMSFDVCYQEIFSTILSGGTLYIIDNEAKREIR
P0C063_A1_pro                            HKNIVNLLHFTFEKTNINFSDKVLQYTNAVLTCVTKKFFSTLLSGGQLYLIRKETQRDVE
O30980_A1_pro                            HRNMANLLQFEFTRSGIDFENDVLQFATPAFDVCYQEIFSTLLGGGTLHIVPEAIKRDVP
P0C064/68845359_A1_2__pro                HKNIVNLLHFTFEKTNINFSDKVLQYTTCSFDVCYQEIFSTLLSGGQLYLIRKETQRDVE
O30980_A1_7__pro                         HRNMANLLQFEFTRSGIDFENDVLQFATPAFDVCYQEIFSTLLGGGTLHIVPEAIKRDVP
                                         ::.: **:      : : :   :**::   :    :::**::  ** *.:: :  ::.  

Q6YK40_A3_pro                            QLFSFINKHQTDIVFFPTAFAKMLFNEESYAYSFPRCVKHLITAGEQLTVSRLFQQMLRT
Q93I55_A4_pro                            QLNDFVRTHGIQTAFLPTAFLKLLASEKHYFEPFAECVDHIIAAGEQLIATRMLRDMLAR
O30408_A1_2__pro                         KLFAFIQEKQISILSLPVSFLKFIFNEQDYAQSFPRCVKHIITAGEQLVVTHELQKYLRQ
Q70JZ9_A3_pro                            QLFSFINKHQTDIVFFPTAFAKMLFNEESYAYSFPRCVKHLITAGEQLTVSRLFQQVLRT
P94459_A1_pro                            QLFAFINKHQTNIVFLPTAFIKMIFSERELANSFPDGVKHLIAAGEQLMISDLFQDVLRK
AGM16413.1_5398_mod5_pro                 QLFTWIQDNGIEVLYLPVAFLKFIFAEPEWAERFPDCVTHIITAGEQLVVTPQIQACLQR
BGC0000400_AGM16413.1_5398_mod5_pro      QLFTWIQDNGIEVLYLPVAFLKFIFAEPEWAERFPDCVTHIITAGEQLVVTPQIQACLQR
Q9R9J0_A4_pro                            ELNEFVKTHRIQTAFLPTAFLKLLASEKQYFEPFAECVDHIITAGEQLIMTNTLREMMMR
P0C063_A1_pro                            QLFDLVKRENIEVLSFPVAFLKFIFNEREFINRFPTCVKHIITAGEQLVVNNEFKRYLHE
O30980_A1_pro                            QLFAFIKEHQTTISVSPTAFIKMIFSEQEFANAFPHDVKHLITAGEQLIVSSLLQDVLRQ
P0C064/68845359_A1_2__pro                QLFDLVKRENIEVLSFPVAFLKFIFNEREFINRFPTCVKHIITAGEQLVVNNEFKRYLHE
O30980_A1_7__pro                         QLFAFIKEHQTTISVSPTAFIKMIFSEQEFANAFPHDVKHLITAGEQLIVSSLLQDVLRQ
                                         :*   :. .       *.:* *::  *      *.  * *:*:*****  .  ::  :  

Q6YK40_A3_pro                            HGLHLHNHYGPSETHVVSTYTIQPGDDIPEYPPIGKPICHNNMYVINKNKQLQPLGIAGE
Q93I55_A4_pro                            HQVTLHNHYGPSETHVVTMYTVDP-DTDQELQPIGKPISNTEIFILNEAGTLQPVGIVGE
O30408_A1_2__pro                         HRVFLHNHYGPSETHVVTTCTMDPGQAIPELPPIGKPISNTGIYILDEGLQLKPEGIVGE
Q70JZ9_A3_pro                            HGLHLHNHYGPSETHVVSTYTIQPGDDIPEYPPIGKPICHNNMYVINKNKQLQPFGIAGE
P94459_A1_pro                            RGIHLHNHYGPSETHVVSTYTIHPGDPIPELPPIGKPIGCTDLYILNHQKQLQPCGVPGE
AGM16413.1_5398_mod5_pro                 LRISLHNHYGPSETHVVTAYTMEPDDIAVGLPPIGAPIANTAIYILNDRLELQPIGIAGE
BGC0000400_AGM16413.1_5398_mod5_pro      LRISLHNHYGPSETHVVTAYTMEPDDIAVGLPPIGAPIANTAIYILNDRLELQPIGIAGE
Q9R9J0_A4_pro                            HQVSLHNHYGPSETHVVTMCTVDP-EIHQEMPPIGKPISNTEILILNEAGTLQPIGIVGE
P0C063_A1_pro                            HNVHLHNHYGPSETHVVTTYTINPEAEIPELPPIGKPISNTWIYILDQEQQLQPQGIVGE
O30980_A1_pro                            RSMYLHNHYGPSETHVVSAYTIHPGNQIPEFPPIGKPIDCTDLYILNRQKQLQPRGVSGE
P0C064/68845359_A1_2__pro                HNVHLHNHYGPSETHVVTTYTINPEAEIPELPPIGKPISNTWIYILDQEQQLQPQGIVGE
O30980_A1_7__pro                         RSMYLHNHYGPSETHVVSAYTIHPGNQIPEFPPIGKPIDCTDLYILNRQKQLQPRGVSGE
                                           : *************:  *:.*        *** **  . : :::    *:* *: **

Q6YK40_A3_pro                            LYISGANTGRGYVNNPALTGEKFLPDLFREGAVMYRTGDLARLREDGQIEYLGRIDDQAK
Q93I55_A4_pro                            LCISGVSLARGYHNRESLTLETFVPHPYDSNQRMYKTGDLARYLPEGNIEYAGRRDHQVK
O30408_A1_2__pro                         LYISGANVGRGYLHQPELTAEKFLDNPYQPGERMYRTGDLALWLPDGQLEFLGRIDHQVK
Q70JZ9_A3_pro                            LYISGANTGRGYVNNPALTGEKFLPDPFREGAVMYRTGDLARLREDGQIEYIGRIDDQAK
P94459_A1_pro                            LYISGASVARGYVNHDKLTSDKFSSDPFKPDVIMYRTGDLARRLEDGNIEYIGRADNQVK
AGM16413.1_5398_mod5_pro                 LYVSGDCVGRGYWGRQELTDEKFIANPFAPGDLMYKTGDVARWLPDGTIEYVGRSDHQVK
BGC0000400_AGM16413.1_5398_mod5_pro      LYVSGDCVGRGYWGRQELTDEKFIANPFAPGDLMYKTGDVARWLPDGTIEYVGRSDHQVK
Q9R9J0_A4_pro                            LCIAGISLARGYHNRESLTHEKFVPHPYDANKRMYKTGDLARYLPDGNIEYAGRMDHQVK
P0C063_A1_pro                            LYISGANVGRGYLNNQELTAEKFFADPFRPNERMYRTGDLARWLPDGNIEFLGRADHQVK
O30980_A1_pro                            LYISGSSVARGYINNDKLTREKFLPDPFRSGAVMYRTGDVARIREDGSFEYIGRADDQVK
P0C064/68845359_A1_2__pro                LYISGANVGRGYLNNQELTAEKFFADPFRPNERMYRTGDLARWLPDGNIEFLGRADHQVK
O30980_A1_7__pro                         LYISGSSVARGYINNDKLTREKFLPDPFRSGAVMYRTGDVARIREDGSFEYIGRADDQVK
                                         * ::*   .***  .  ** :.*  . :  .  **:***:*    :* :*: ** *.*.*

Q6YK40_A3_pro                            IRGYRIEPKEVEVILANHPAVREAAVLIQKNALGENELCA
Q93I55_A4_pro                            IRGYRVELGEVEAALL--KHVQEAVVLAKENTDGQSDLYA
O30408_A1_2__pro                         IRGHRIELGEIESRLLNHPAIKEAVVIDRADETGGKFLCA
Q70JZ9_A3_pro                            IRGYRIEPKEVEVILANHPAVREAAVLIQKNALGENELCA
P94459_A1_pro                            IRGYRIEPQEIEVTLMNHPDISEAAILIWQDQNGEHELCA
AGM16413.1_5398_mod5_pro                 IRGFRIELGEVESQLLSVEFVQEATVMAREDDGGQKQLCA
BGC0000400_AGM16413.1_5398_mod5_pro      IRGFRIELGEVESQLLSVEFVQEATVMAREDDGGQKQLCA
Q9R9J0_A4_pro                            IRGYRIELNEVEAALLNIEHVQEAVVLARENTEGQSDLYA
P0C063_A1_pro                            IRGHRIELGEIEAQLLNCKGVKEAVVIDKADDKGGKYLCA
O30980_A1_pro                            IRGYRIEPQEIEIALMNHPEVKEAAILIRQNQGEEHELCA
P0C064/68845359_A1_2__pro                IRGHRIELGEIEAQLLNCKGVKEAVVIDKADDKGGKYLCA
O30980_A1_7__pro                         IRGYRIEPQEIEIALMNHPEVKEAAILIRQNQGEEHELCA
                                         ***.*:*  *:*  *     : **.::   :      * *
