CLUSTAL W multiple sequence alignment


BGC0001125_AIW82277.1_2006_mod2_pro      LTQSHLIDILPEHESRLVCLDTEWQSSLTQIQPEPANSRLQPDNLAYVIYTSGSTGTPKG
AEU11003.1_555_mod1_pro                  LTQQNLVEKLPPNHAQLVCLDNDWQ-IISQLSQENLVCGVQENNLGYVIYTSGSTGQPKG
AEU11003.1_4205_mod4_pro                 LTQQQLVEKLPPNQARVIYLDSDWQ-IISQLSQENVISGVQENNLGYVIYTSGSTGQPKG
                                         ***.:*:: ** :.:::: **.:**  ::*:. *   . :* :**.********** ***

BGC0001125_AIW82277.1_2006_mod2_pro      VAMTQGALTNLLLWQIRQTHIAAS-AKTLQFAPVSFDVSFQEMFTTWCAGGTLVLVPDAL
AEU11003.1_555_mod1_pro                  VAMNQLALCNLMLWQLQNTSITSSKAKTLQFAPISFDVSFQEMFSTWCSGGTLLLIDSQL
AEU11003.1_4205_mod4_pro                 VAMNQLALCNLILWQLQNTSITSSKAKTLQFAPISFDVSFQEMFSTWCSGGTLLLIDSQL
                                         ***.* ** **:***:::* *::* ********:**********:***:****:*: . *

BGC0001125_AIW82277.1_2006_mod2_pro      RRDATALLGLLSEQSVERVFLPFVALQQLAEAAAGVE-SLPPLREIMTAGEQLQITPALK
AEU11003.1_555_mod1_pro                  RREPLALLGLLKEQGVERVFLPFVALQQLAEVAVDSELVINHLKEVITAGEQLQITPAIS
AEU11003.1_4205_mod4_pro                 RREPLALLGLLQEQAVERVFVPFVALQQLAEVAVSNELVIDNLREIITAGEQLQITPAIS
                                         **:. ******.**.*****:**********.*.. *  :  *:*::***********:.

BGC0001125_AIW82277.1_2006_mod2_pro      NFLRRLPGCSLHNQYGPSETHVVTAFSLEDGLEELPALPPIGRPIDNTQIYILDRQMQQV
AEU11003.1_555_mod1_pro                  KWFSQLNGCTLHNHYGPSESHVVTTLTLSDAVENWALLPPIGRPITNTQIYILDEYLQPV
AEU11003.1_4205_mod4_pro                 KWFGQLNGCTLNNHYGPSESHVVTTFTLSNSVDNWALLPPIGRAIANTQIYILDECLQPL
                                         ::: :* **:*:*:*****:****:::*.:.::: . ******.* ********. :* :

BGC0001125_AIW82277.1_2006_mod2_pro      PIGVRGELYIGGVGVARGYLNRPDLTEERFIPDFFTNSKVNRLYKTGDGARYLPDGNIEY
AEU11003.1_555_mod1_pro                  PIGVPGELHIGGVCLARGYLNRPELTQERFIPNPFNNSK---LYKTGDLARYLPDGNIEY
AEU11003.1_4205_mod4_pro                 PVGVPGELYIGGVCLARGYLNRPELTQEKFISNPFGGSKGERLYKTGDLARYLPDGNIEY
                                         *:** ***:**** :********:**:*:**.: * .**   ****** ***********

BGC0001125_AIW82277.1_2006_mod2_pro      LGRMDDQVKVRGFRIELGEIEAVLGLHPQVQQAIAIAYGETAAEKRLVV
AEU11003.1_555_mod1_pro                  LGRIDNQVKIRGFRIELGEVEAVLSQCEDVQVCCAMAREDSPGDKRLVA
AEU11003.1_4205_mod4_pro                 LGRIDNQVKIRGFRIELGEVEAVLSQYENVQVCCAIAREDYPGDKRLVA
                                         ***:*:***:*********:****.   :** . *:*  : ..:****.
