CLUSTAL W multiple sequence alignment


Q01886v2_A1_pro                          LVGAGKTAALFKSADTAVQTIDITKDIPHGLSDTVVQSNTKIDDPAFGLFTSGSTGVPKC
BGC0001166_AGQ43600.1_228_mod1_pro       LVGAGKTAALFESADAAIRTIDITKDIPSGLSNMVALSKTKIEDPAFGLFTSGSTGVPKC
Q01886v1_A1_pro                          LVGAGKTAALFKSADTAVQTIDITKDIPHGLSDTVVQSNTKIDDPAFGLFTSGSTGVPKC
                                         ***********:***:*::********* ***: *. *:***:*****************

Q01886v2_A1_pro                          IVVTHSQICTAVQAYKDRFGVTSETRVLQFSSYTFDISIADTFTALFYGGTLCIPSEEDR
BGC0001166_AGQ43600.1_228_mod1_pro       IVVTHSQICTGVQAYRDRFGVTAETRVLQFSSYTFDISIADTFAALFYGGTLCIPSEEDR
Q01886v1_A1_pro                          IVVTHSQICTAVQAYKDRFGVTSETRVLQFSSYTFDISIADTFTALFYGGTLCIPSEEDR
                                         **********.****:******:********************:****************

Q01886v2_A1_pro                          MSNLQDYMVSVRPNWAVLTPTVSRFLDPGVVKDFISTLIFTGEASREADTVPWIEAGVNL
BGC0001166_AGQ43600.1_228_mod1_pro       MSNLQEYMVSVRPNWAVLTPTVSRFLDPAVVKDFVSTLIFTGEASRESDTAPWIEAGVNL
Q01886v1_A1_pro                          MSNLQDYMVSVRPNWAVLTPTVSRFLDPGVVKDFISTLIFTGEASREADTVPWIEAGVNL
                                         *****:**********************.*****:************:**.*********

Q01886v2_A1_pro                          YNVYGPAENTLITTATRIRKGKSSNIGYGVNTRTWVTDVSGACLVPVGSIGELLIESGHL
BGC0001166_AGQ43600.1_228_mod1_pro       YNVYGPAENTLITTATRVRKGESSNIGYGVNTRTWVTDVSSACLVPVGRIGELLIESGHL
Q01886v1_A1_pro                          YNVYGPAENTLITTATRIRKGKSSNIGYGVNTRTWVTDVSGACLVPVGSIGELLIESGHL
                                         *****************:***:******************.******* ***********

Q01886v2_A1_pro                          ADKYLNRPDRTEAAFLSDLPWIPNYEGDSVRRGRRFYRTGDLVRYCDDGSLICVGRSDTQ
BGC0001166_AGQ43600.1_228_mod1_pro       ADKYLNNPDKTEAAFLSDVSWIPNCDGDSVHRGRRFYRTGDLVRYCDDGSLICVGRSDTQ
Q01886v1_A1_pro                          ADKYLNRPDRTEAAFLSDLPWIPNYEGDSVRRGRRFYRTGDLVRYCDDGSLICVGRSDTQ
                                         ******.**:********:.**** :****:*****************************

Q01886v2_A1_pro                          IKLAGQRVELGDVEAHLQSDPTTSQAAVVFPRSGPLEARLIA
BGC0001166_AGQ43600.1_228_mod1_pro       IKLAGQRVELGDVEAHLQSDPATSQAAVFFPTSGTLKARLTA
Q01886v1_A1_pro                          IKLAGQRVELGDVEAHLQSDPTTSQAAVVFPRSGPLEARLIA
                                         *********************:******.** **.*:*** *
