CLUSTAL W multiple sequence alignment


Q5DIV7_A1_ser                            LSQS-HL-----KLPLAQGVQRIDLDQADAWLENHAENNPGVELNGENLAYVIYTSGSTG
Q5DIP3_A1_ser                            LSQS-HL-----KLPLAQGVQRIDLDQADAWLENHAENNPGVELNGENLAYVIYTSGSTG
Q5DIV7_A3_ser                            LSQS-HL-----KLPLAQGVQRIDLDRGAPWFEDYSEANPDIHLDGENLAYVIYTSGSTG
Q5DIP4_A3_6__ser                         LSQS-HL-----KLPLAQGVQRIDLDQADAWLENHAENNPGVELNGENLAYVIYTSGSTG
CCA29203.1_542_mod1_ser                  LTQERHLPSWRDRQPSAH-VFAIDSASTRATLAQHPRDNPASVIDGEALAYVIYTSGTTG
                                         *:*. **     : * *: *  **     . : ::.. **   ::** *********:**

Q5DIV7_A1_ser                            KPKGAGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVVAA
Q5DIP3_A1_ser                            KPKGAGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVVAA
Q5DIV7_A3_ser                            KPKGAGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVVAA
Q5DIP4_A3_6__ser                         KPKGAGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVVAA
CCA29203.1_542_mod1_ser                  KPKGVMSEHTGLVNRLQWMNKQYPLQATDKILQKTTYVFDVSVWELLWANWYGACVVFAE
                                         ****. ..*:.* *** **:: * * . *.:****.: *******::*.   ** :*.* 

Q5DIV7_A1_ser                            PGDHRDPAKLVELINREGVDTLHFVPSMLQAFLQDEDVASC----TSLKRIVCSGEALPA
Q5DIP3_A1_ser                            PGDHRDPAKLVKLINREGVDTLHFVPSMLQAFLQDEDVASC----TSLKRIVCSGEALPA
Q5DIV7_A3_ser                            PGDHRDPAKLVALINREGVDTLHFVPSMLQAFLQDEDVVSC----TSLKRIVCSGEALPA
Q5DIP4_A3_6__ser                         PGDHRDPAKLVALINREGVDTLHFVPSMLQAFLQDEDVASC----TSLKRIVCSGEALPA
CCA29203.1_542_mod1_ser                  PEGHKDVDYLLGLMERESISVVHFVPSMFGVFLDSLRARATPSHLSSLRYIFCSGEALPL
                                         * .*:*   *: *::**.:..:******: .**:.  . :     :**: *.******* 

Q5DIV7_A1_ser                            DAQQQVFAKLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLE
Q5DIP3_A1_ser                            DAQQQVFAKLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLE
Q5DIV7_A3_ser                            DAQQQVFAKLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLE
Q5DIP4_A3_6__ser                         DAQQQVFAKLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLE
CCA29203.1_542_mod1_ser                  NQVRDTHALLPAVRLHNLYGPTEASIDVLHFDCTDRALDSVPIGKPIDNTQVYVLNEALR
                                         :  ::..* ** . *:********:*** *: *.:.. *:****:** *   *:*:  *.

Q5DIV7_A1_ser                            PVPVGVLGELYLAGQGLARGYHQRPGLTAERFVASPFVAG-------ERMYRTGDLARYR
Q5DIP3_A1_ser                            PVPVGVLGELYLAGRGLARGYHQRPGLTAERFVASPFVAG-------ERMYRTGDLARYR
Q5DIV7_A3_ser                            PVPVGVLGELYLAGQGLARGYHQRPGLTAERFVASPFVAG-------ERMYRTGDLARYR
Q5DIP4_A3_6__ser                         PVPVGVLGELYLAGRGLARGYHQRPGLTAERFVASPFVAG-------ERMYRTGDLARYR
CCA29203.1_542_mod1_ser                  PLPIHAIGELFLGGVGLARGYLNRPELTAQRFIPNPFAAPSERDASRSRLYRTGDLVRWL
                                         *:*: .:***:*.* ****** :** ***:**:..**.*        .*:******.*: 

Q5DIV7_A1_ser                            ADGVIEYAGRIDHQVKLRGLRIELGEIEARLLEHPRVREAAVLA------VDGRQ-LVG
Q5DIP3_A1_ser                            ADGVIEYAGRIDHQVKLRGLRIELGEIEARLLEHPRVREAAVLA------VDGRQ-LVG
Q5DIV7_A3_ser                            ADGVIEYAGRIDHQVKLRGLRIELGEIEARLLEHPWVREAAVLA------VDGKQ-LVG
Q5DIP4_A3_6__ser                         ADGVIEYAGRIDHQVKLRGLRIELGEIEARLLEHPWVREAAVLA------VDGKQ-LVG
CCA29203.1_542_mod1_ser                  PDGNLEYLGRNDFQVKIRGQRVELGEIEAALARFPGVKQGLALVRTPTGDPDAAQVLVG
                                         .** :** ** *.***:** *:******* * ..* *::. .*.       *. * ***
