CLUSTAL W multiple sequence alignment


BGC0000423_CBG75492.1_1712_mod2_ser      VTLSATADRLPG-QALPSVLLLDTPDTPDTHDASDTHDGLDDLDGLGGEPPAGRSADPAR
Q9Z4X6_A1_ser                            LTTRDTAERLPG-DGTPRLLLDEPAAAGTTAAGA-------------PAPPGTLPRALPA
CBG75492_1712_mod2_ser                   VTLSATADRLPG-QALPSVLLLDTPDTPDTHDASDTHDGLDDLDGLGGEPPAGRSADPAR
EFE73313.1_484_mod1_ser                  LTSESVRSVVPGVEGLERVVVDAAQTVSALADLS-------------GEPVSS---VEVL
Q50E73_A6_11__ser                        -LTRGDVE-LPG-S-VPRIGLDDTEIRATLATA-----------------PGTNPGTPVT
BGC0000431_EFE73313.1_484_mod1_ser       LTSESVRSVVPGVEGLERVVVDAAQTVSALADLS-------------GEPVSS---VEVL
                                                . :** .    : :  .                           .        

BGC0000423_CBG75492.1_1712_mod2_ser      PDDPAYLIYTSGSTGVPKGVVVTHRAIVNRLAWMQAAYGLASDDRVLQKTPSSFDVSVWE
Q9Z4X6_A1_ser                            PGHPAYVIYTSGSTGRPKGVVISHRAIVNRLAWMQDTYGLEPSDRVLQKTPSGFDVSVWE
CBG75492_1712_mod2_ser                   PDDPAYLIYTSGSTGVPKGVVVTHRAIVNRLAWMQAAYGLASDDRVLQKTPSSFDVSVWE
EFE73313.1_484_mod1_ser                  PSHVAYVIYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWE
Q50E73_A6_11__ser                        EAHPAYMIYTSGSTGRPKGVVVSHGAIVNRLAWMQAEYRLDATDRVLQKTPAGFDVSVWE
BGC0000431_EFE73313.1_484_mod1_ser       PSHVAYVIYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWE
                                           . **:******** ****.:.* .:**** ***  : *   ***:**** .*******

BGC0000423_CBG75492.1_1712_mod2_ser      FFWPLLEGASVVLARPDGHRDPAYLAGLVREQAVTTMHFVPSMLEAFLGHDEVTGDPAWS
Q9Z4X6_A1_ser                            FFWPLVQGATLVVARPGGHTDPAYLAGTVRREGVTTLHFVPSMLDVFL------REPAAA
CBG75492_1712_mod2_ser                   FFWPLLEGASVVLARPDGHRDPAYLAGLVREQAVTTMHFVPSMLEAFLGHDEVTGDPAWS
EFE73313.1_484_mod1_ser                  FFWPLITGAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFL------REPDAA
Q50E73_A6_11__ser                        FFWPLLEGAVLVFARPGGHRDAAYLAGLIERERITTAHFVPSMLRVFL------EEPGAA
BGC0000431_EFE73313.1_484_mod1_ser       FFWPLITGAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFL------REPDAA
                                         *****: ** :*.***.** *..**:  :..: :*. ******* .**       :*  :

BGC0000423_CBG75492.1_1712_mod2_ser      AS-----LRRVLSSGEALPATAASRWHALTG-VPLHNLYGPTEAAVDVTYHPYAPDEDRG
Q9Z4X6_A1_ser                            ALGGATPVRRVFCSGEALPAELRARFRAVSD-VPLHNLYGPTEAAVDVTYWPCAEDT--G
CBG75492_1712_mod2_ser                   AS-----LRRVLSSGEALPATAASRWHALTG-VPLHNLYGPTEAAVDVTYHPYAPDEDRG
EFE73313.1_484_mod1_ser                  ACTG---LRWVVCSGEALPPELRDQFFDVLEGVELHNLYGPTEASVDVTAWPCTPDE--G
Q50E73_A6_11__ser                        LCTG---LRRVICSGEALGTDLAVDFRAKLP-VPLHNLYGPTEAAVDVTHHAYEPAT--G
BGC0000431_EFE73313.1_484_mod1_ser       ACTG---LRWVVCSGEALPPELRDQFFDVLEGVELHNLYGPTEASVDVTAWPCTPDE--G
                                                :* *..***** .     :      * **********:****  .       *

BGC0000423_CBG75492.1_1712_mod2_ser      TA-VPIGRPVWNTGLRVLDACLRPVPDGVPGELYLTGVQLARGYHARPALTAERFTADPY
Q9Z4X6_A1_ser                            DGPVPIGRPVWNTRMYVLDAALRPVPAGVPGELYIAGVQLARGYLGRPALSAERFTADPH
CBG75492_1712_mod2_ser                   TA-VPIGRPVWNTGLRVLDACLRPVPDGVPGELYLTGVQLARGYHARPALTAERFTADPY
EFE73313.1_484_mod1_ser                  PA-VPIGRPVWNTRTYVLDTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPF
Q50E73_A6_11__ser                        TATVPIGRPIWNIRTYVLDAALRPVPPGVPGELYLAGAGLARGYHGRPALTAERFVACPF
BGC0000431_EFE73313.1_484_mod1_ser       PA-VPIGRPVWNTRTYVLDTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPF
                                          . ******:**    ***: ***** **.*:**::*  ***** .**.*:****.* *.

BGC0000423_CBG75492.1_1712_mod2_ser      GRPGSRMYRTGDLVRRRADGVIEYLGRTDRQVKLRGNRIELGEVEAALVRLPEVAQAAVT
Q9Z4X6_A1_ser                            GAPGSRMYRTGDLARWNHDGSLDYLGRADHQVKLRGFRIELGEIEAALVRQPEIAQAAVV
CBG75492_1712_mod2_ser                   GRPGSRMYRTGDLVRRRADGVIEYLGRTDRQVKLRGNRIELGEVEAALVRLPEVAQAAVT
EFE73313.1_484_mod1_ser                  GTAGERMYRTGDVVRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALTSHATVAQTAVL
Q50E73_A6_11__ser                        GVPGERMYRTGDLVRWRVDGTLEFVGRADDQVKVRGFRVELGEVEGAVAAHPDVVRAVVV
BGC0000431_EFE73313.1_484_mod1_ser       GTAGERMYRTGDVVRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALTSHATVAQTAVL
                                         * .*.*******:.* . ** ::::**:* ***:** *:****:*.*:.  . :.::.* 

BGC0000423_CBG75492.1_1712_mod2_ser      VRDDA-----LVA
Q9Z4X6_A1_ser                            LREDRPGDQRLVA
CBG75492_1712_mod2_ser                   VRDDA-----LVA
EFE73313.1_484_mod1_ser                  VREDVPGDKRLVA
Q50E73_A6_11__ser                        VREDRPGDHRLVA
BGC0000431_EFE73313.1_484_mod1_ser       VREDVPGDKRLVA
                                         :*:*      ***
