CLUSTAL W multiple sequence alignment


Q5DIP4_A3_6__ser                         LSQSHL--KLPLAQGVQRIDLDQADAWLENHAENNPGVELNGENLAYVIYTSGSTGKPKG
Q884E3_A2_ser                            LTQTSLLECLPVPEHVQSICLDQDGDWLAGYSTANPVNLSHPQNLAYVIYTSGSTGKPKG
Q884E4_A2_ser                            LTQTSLLERLPV--QVQSMCLDQDGDWLEGYSTANPVNLSHPQNLAYVIYTSGSTGKPKG
Q5DIV7_A3_ser                            LSQSHL--KLPLAQGVQRIDLDRGAPWFEDYSEANPDIHLDGENLAYVIYTSGSTGKPKG
Q5DIV7_A1_ser                            LSQSHL--KLPLAQGVQRIDLDQADAWLENHAENNPGVELNGENLAYVIYTSGSTGKPKG
Q5DIP3_A1_ser                            LSQSHL--KLPLAQGVQRIDLDQADAWLENHAENNPGVELNGENLAYVIYTSGSTGKPKG
Q5DIS7_A1_ser                            LTQAHLLDGLPVSAEVQPLMLAADSEWLEGFDASDPEVAVTGENLAYVIYTSGSTGRPKG
                                         *:*: *   **:   ** : *     *: ..   :*      :*************:***

Q5DIP4_A3_6__ser                         AGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVVAAPGDH
Q884E3_A2_ser                            AGNSHRALVNRLHWMQKAYALDGSDTVLQKTPFSFDVSVWEFFWPLLTGARLAVALPGDH
Q884E4_A2_ser                            AGNSHRALVNRLHWMQKAYALDDSDTVLQKTPFSFDVSVWEFFWPLLTGARLAVALPGDH
Q5DIV7_A3_ser                            AGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVVAAPGDH
Q5DIV7_A1_ser                            AGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVVAAPGDH
Q5DIP3_A1_ser                            AGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVVAAPGDH
Q5DIS7_A1_ser                            AGNRHSALTNRLCWMQDAYQLDGSDAVMQKTPFSFDVSVWEFFWPLMVGARLVLAQPGDH
                                         *** * ** *** ***.** *. .*:*:******************: ****.:* ****

Q5DIP4_A3_6__ser                         RDPAKLVALINREGVDTLHFVPSMLQAFLQDEDVASCTSLKRIVCSGEALPADAQQQVFA
Q884E3_A2_ser                            RDPERLVQTIQEHQIRTLHFVPSMLQAFLTHPQVESCNSLRRVVCSGEALPAELAGQVLK
Q884E4_A2_ser                            RDPERLVQTIRQHEVTTLHFVPSMLQAFMTHPQVESCNSLSRVMCSGEALPAELVGQVLK
Q5DIV7_A3_ser                            RDPAKLVALINREGVDTLHFVPSMLQAFLQDEDVVSCTSLKRIVCSGEALPADAQQQVFA
Q5DIV7_A1_ser                            RDPAKLVELINREGVDTLHFVPSMLQAFLQDEDVASCTSLKRIVCSGEALPADAQQQVFA
Q5DIP3_A1_ser                            RDPAKLVKLINREGVDTLHFVPSMLQAFLQDEDVASCTSLKRIVCSGEALPADAQQQVFA
Q5DIS7_A1_ser                            RDPSRLMDLIGRESISTLHFVPSMLQAFLQAPGVSACTSLKRIVCSGEALPVDAQQRVLA
                                         *** :*:  * .. : ************:    * :*.** *::*******.:   :*: 

Q5DIP4_A3_6__ser                         KLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLEPVPVGVLG
Q884E3_A2_ser                            RLPQASLYNLYGPTEAAIDVTHWTCTTDDVLSVPIGRPIDNLKTHILDDGLLPAAQGVAA
Q884E4_A2_ser                            RLPQVGLFNLYGPTEAAIDVTHWTCTTDDVLSVPIGRPIDNLKTHILDDGLLPAAQGVAA
Q5DIV7_A3_ser                            KLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLEPVPVGVLG
Q5DIV7_A1_ser                            KLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLEPVPVGVLG
Q5DIP3_A1_ser                            KLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLEPVPVGVLG
Q5DIS7_A1_ser                            ELPGVRLYNLYGPTEAAIDVTHWDCREEGRDTVPIGRPIANLRCYVLDDALEPVPVGALG
                                         .** . *:*************** *  :.  :******* **  ::**. * *.. *. .

Q5DIP4_A3_6__ser                         ELYLAGRGLARGYHQRPGLTAERFVASPF-VAGERMYRTGDLARYRADGVIEYAGRIDHQ
Q884E3_A2_ser                            ELYLGGVGLARGYHNRAALTAERFVPDPFDEQGGRLYRTGDLARYRNEGVIEYAGRIDHQ
Q884E4_A2_ser                            ELYLGGVGLARGYHNRAALTAERFVPDPFDGQGGRLYRTGDLARYRDEGVIEYAGRIDHQ
Q5DIV7_A3_ser                            ELYLAGQGLARGYHQRPGLTAERFVASPF-VAGERMYRTGDLARYRADGVIEYAGRIDHQ
Q5DIV7_A1_ser                            ELYLAGQGLARGYHQRPGLTAERFVASPF-VAGERMYRTGDLARYRADGVIEYAGRIDHQ
Q5DIP3_A1_ser                            ELYLAGRGLARGYHQRPGLTAERFVASPF-VAGERMYRTGDLARYRADGVIEYAGRIDHQ
Q5DIS7_A1_ser                            ELYLAGAGLARGYHLRPALSAERFLADPF-ATGERMYRTGDLARYRADGVIEYAGRIDHQ
                                         ****.* ******* *..*:****:..**   * *:********** :************

Q5DIP4_A3_6__ser                         VKLRGLRIELGEIEARLLEHPWVREAAVLAVD---GKQLVG
Q884E3_A2_ser                            VKIRGLRIELGEIEARLHEHAGVREANVIDIDGPSGKQLVA
Q884E4_A2_ser                            VKIRGLRIELGEIEACLLEHDSVQEAVVIDVDGPSGKQLAA
Q5DIV7_A3_ser                            VKLRGLRIELGEIEARLLEHPWVREAAVLAVD---GKQLVG
Q5DIV7_A1_ser                            VKLRGLRIELGEIEARLLEHPRVREAAVLAVD---GRQLVG
Q5DIP3_A1_ser                            VKLRGLRIELGEIEARLLEHPRVREAAVLAVD---GRQLVG
Q5DIS7_A1_ser                            VKLRGLRIELGEIETRLLEHHAVREAAVLVVD---GKQLVG
                                         **:***********: * **  *:** *: :*   *:**..
