CLUSTAL W multiple sequence alignment


AFZ61525.1_3733_mod4_ser                 AQGATRGLLGD--APVIDLDRPTWQHQSIDNPQVQAF----SAYVIYTSGSTGQPKGVIN
AFZ61526.1_1614_mod2_ser                 AQGGTRGLLGD--VPVVDLDRPTWQHPREDNPAVQGI----SAYVIYTSGSTGQPKGVIN
Q84BQ4_A2_8__ser                         VQGTTRSLLGEVSVPVIDLDQSQWQSLPADNLSVAELTPQHTAYVIYTSGSTGQPKGVIN
Q84BQ5_A4_6__ser                         VQGTTRSLLGEVSVPVVDLDQPHWQSLPADNLSVAELTPQHTAYVIYTSGSTGQPKGVIN
                                         .** **.***:  .**:***:. **    **  *  :    :******************

AFZ61525.1_3733_mod4_ser                 DHPGVVNRLLWMQDAYGLQAHDRVLQKTPFSFDVSVWEFFWPLFTGACLVMARPGGHKDP
AFZ61526.1_1614_mod2_ser                 DHPGVVNRLLWMQDAYGLQAHDRVLQKTPFSFDVSVWEFFWPLFTGACLVMARPGGHKDP
Q84BQ4_A2_8__ser                         EHSGVVNRLLWMQDAYQLTSSDTVLQKTPFSFDVSVWEFFWSLMTGARLVMARPEGHKDP
Q84BQ5_A4_6__ser                         EHSGVVNRLLWMQDAYQLTSSDTVLQKTPFSFDVSVWEFFWPLMTGARLVMARPEGHKDP
                                         :*.************* * : * ******************.*:*** ****** *****

AFZ61525.1_3733_mod4_ser                 AYLCEVIANEQITTLHFVPSMLDVFLAHGDVSQAAGLQRVMCSGEALPGSLVRRFKQQLP
AFZ61526.1_1614_mod2_ser                 AYLCEVIAAEQITTLHFVPSMLDVFLAHGDVSQAAGLVRVMCSGEALPGSLVRRFKQQLP
Q84BQ4_A2_8__ser                         LYLSEIIEREHITTLHFVPSMLDVFLAHADTARCASLRQVMCSGEALPGSVVRRFKQQLP
Q84BQ5_A4_6__ser                         QYLSEIIEREQITTLHFVPSMLDVFLAHADTARCSSLRQVMCSGEALPGSVVRRFKQQLP
                                          **.*:*  *:*****************.*.::.:.* :***********:*********

AFZ61525.1_3733_mod4_ser                 GIGLYNLYGPTEAAVDVTAWNCARP--DVPDNTPIGKPIANTRMYVLDGQMQPVPLGVVG
AFZ61526.1_1614_mod2_ser                 GSELHNLYGPTEAAVDVTAWNCAGP--VTPDNTPIGKPIANTRMYVLDAQMQPVPLGVVG
Q84BQ4_A2_8__ser                         GSQLHNLYGPTEAAVDVTAWNCAGPLESTPDNTPIGKPIANTRMYILDAQQQPVPHGVVG
Q84BQ5_A4_6__ser                         ASQLHNLYGPTEAAVDVTAWNCAGPLEQTPDNTPIGKPIANTRMYILDAQQQPVPHGVVG
                                         .  *:****************** *   .****************:**.* **** ****

AFZ61525.1_3733_mod4_ser                 ELFIGGVQVARGYLNRPELTAERFLKDPF-TDGRLYRTGDLGRYLLDGTIEYLGRNDDQV
AFZ61526.1_1614_mod2_ser                 ELFIGGVQVARGYLNRPELTAERFLKDPF-TDGRLYRTGDVGRYLADGTIEYLGRNDDQV
Q84BQ4_A2_8__ser                         ELYIGGVQVARGYLNRPELNAERFLNDPFQSNGRMYRTGDVARYLPDGNIEYLGRNDDQV
Q84BQ5_A4_6__ser                         ELYIGGVQVARGYLNRPELNAERFLNDPFQANGRMYRTGDVARYLPDGNIEYLGRNDDQV
                                         **:****************.*****:*** ::**:*****:.*** **.***********

AFZ61525.1_3733_mod4_ser                 KIRGLRIELGEIQARLLEHPQVNEAAVVAR-----DDRLVA
AFZ61526.1_1614_mod2_ser                 KIRGLRIELGEIQSRLTEYPPVNEAAVIAR-----DNRLIA
Q84BQ4_A2_8__ser                         KIRGLRIELGEIQARLTQIDGIQEVAVLAREDVPGDKRLVA
Q84BQ5_A4_6__ser                         KIRGLRIELGEIQARLTQIDGVQEAAVLAREDASGDKRLVA
                                         *************:** :   ::*.**:**     *.**:*
