CLUSTAL W multiple sequence alignment


BGC0000431_EFE73313.1_484_mod1_ser       LTSESVRSVVPGVEGLERVVVDAAQTVSALADLSGEPVSS---VEVLPSHVAYVIYTSGS
Q50E73_A6_11__ser                        -LTRGDVE-LPG-S-VPRIGLDDTEIRATLATA----PGTNPGTPVTEAHPAYMIYTSGS
BGC0000371_BAH31686.1_1984_mod2_ser      --VSEDSSLDSG-S-VPRVTVSES------AQFPAEPLS----VPGSPADAAYMIYTSGS
EFE73313.1_484_mod1_ser                  LTSESVRSVVPGVEGLERVVVDAAQTVSALADLSGEPVSS---VEVLPSHVAYVIYTSGS
Q9Z4X6_A1_ser                            LTTRDTAERLPG-DGTPRLLLDEPAAAGTTAAGAPAPPGTLPRALPAPGHPAYVIYTSGS
                                                .  .* .   *: :. .      *       .    .    .. **:******

BGC0000431_EFE73313.1_484_mod1_ser       TGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFFWPLITGAGLVV
Q50E73_A6_11__ser                        TGRPKGVVVSHGAIVNRLAWMQAEYRLDATDRVLQKTPAGFDVSVWEFFWPLLEGAVLVF
BGC0000371_BAH31686.1_1984_mod2_ser      TGRPKGVVVTNEGVVNRLLWAQQIRPLDFSDRMLQKTPSSFDVSVPEFFWPFLVGATLVM
EFE73313.1_484_mod1_ser                  TGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFFWPLITGAGLVV
Q9Z4X6_A1_ser                            TGRPKGVVISHRAIVNRLAWMQDTYGLEPSDRVLQKTPSGFDVSVWEFFWPLVQGATLVV
                                         *******.:.: .:**** * *    *: :**::**** .***** *****:: ** **.

BGC0000431_EFE73313.1_484_mod1_ser       ARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG---LRWVVCSGEALP
Q50E73_A6_11__ser                        ARPGGHRDAAYLAGLIERERITTAHFVPSMLRVFLEEPGAALCTG---LRRVICSGEALG
BGC0000371_BAH31686.1_1984_mod2_ser      AEPDGHKDPGYLADVIVEHSVTRVHFVPSMLEVFLAEPKAALCTS---LEIVNCSGEALP
EFE73313.1_484_mod1_ser                  ARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG---LRWVVCSGEALP
Q9Z4X6_A1_ser                            ARPGGHTDPAYLAGTVRREGVTTLHFVPSMLDVFLREPAAAALGGATPVRRVFCSGEALP
                                         *.*.** *..**:  : .. :*  ******* *** ** **   .   :. * ****** 

BGC0000431_EFE73313.1_484_mod1_ser       PELRDQFFDVLEGVELHNLYGPTEASVDVTAWPC---TPDEGPA-VPIGRPVWNTRTYVL
Q50E73_A6_11__ser                        TDLAVDFRAKLP-VPLHNLYGPTEAAVDVTHHAY---EPATGTATVPIGRPIWNIRTYVL
BGC0000371_BAH31686.1_1984_mod2_ser      VHVARKVAEILPNVLVDNLYGPTEAAVDVSWQPSVQETPADAVS-VPIGEPAANTGLFVL
EFE73313.1_484_mod1_ser                  PELRDQFFDVLEGVELHNLYGPTEASVDVTAWPC---TPDEGPA-VPIGRPVWNTRTYVL
Q9Z4X6_A1_ser                            AELRARFRAVSD-VPLHNLYGPTEAAVDVTYWPC---AEDTGDGPVPIGRPVWNTRMYVL
                                          .:   .      * :.********:***:  .        . . ****.*  *   :**

BGC0000431_EFE73313.1_484_mod1_ser       DTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFGTAGERMYRTGDVVRWRT
Q50E73_A6_11__ser                        DAALRPVPPGVPGELYLAGAGLARGYHGRPALTAERFVACPFGVPGERMYRTGDLVRWRV
BGC0000371_BAH31686.1_1984_mod2_ser      DPYLQNVPAGATGELYLAGPQLARGYHGRGGLTSERFVANPYSDGGSRMYRTGDIVRWNG
EFE73313.1_484_mod1_ser                  DTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFGTAGERMYRTGDVVRWRT
Q9Z4X6_A1_ser                            DAALRPVPAGVPGELYIAGVQLARGYLGRPALSAERFTADPHGAPGSRMYRTGDLARWNH
                                         *. *: ** *..*:**:**  ***** ** .*::***.* *..  *.*******:.**. 

BGC0000431_EFE73313.1_484_mod1_ser       DGNLEFLGRADDQVKVRGFRIELGEIEAALTSHATVAQTAVLVREDVPGDK-RLVA
Q50E73_A6_11__ser                        DGTLEFVGRADDQVKVRGFRVELGEVEGAVAAHPDVVRAVVVVREDRPGDH-RLVA
BGC0000371_BAH31686.1_1984_mod2_ser      DGVLEYLGRVDEQVKVRGFRIELGEIEAQLALCPGVSASAVIVRTDGPSDRAQVVA
EFE73313.1_484_mod1_ser                  DGNLEFLGRADDQVKVRGFRIELGEIEAALTSHATVAQTAVLVREDVPGDK-RLVA
Q9Z4X6_A1_ser                            DGSLDYLGRADHQVKLRGFRIELGEIEAALVRQPEIAQAAVVLREDRPGDQ-RLVA
                                         ** *:::**.*.***:****:****:*. :.  . :  :.*::* * *.*: ::**
