CLUSTAL W multiple sequence alignment


Q50E73_A6_11__ser                        ------LTRGDVE-LP-G-S-VPRIGLDDTEIRATLATA----PGTNPGTPVTEAHPAYM
BGC0000431_EFE73313.1_484_mod1_ser       -----LTSESVRSVVP-GVEGLERVVVDAAQTVSALADLSGEPVSS---VEVLPSHVAYV
EFE73313.1_484_mod1_ser                  -----LTSESVRSVVP-GVEGLERVVVDAAQTVSALADLSGEPVSS---VEVLPSHVAYV
EWS95122_476_mod1_ser                    -----VTTTAALGRLP-AAQTPPRLLLDDPATLAVLREAPSSRPAGDTAVRPHPRNPANV
Q9Z4X6_A1_ser                            -----LTTRDTAERLP-G-DGTPRLLLDEPAAAGTTAAGAPAPPGTLPRALPAPGHPAYV
EFE73312.1_2615_mod3_ser                 -----VTSRATEGAVPEGADIPARVQVDGADVLAQLKALSGEPVSS---VEVLPSHVAYV
Q9FB23_A1_ser                            LTETGTASRAAEAAGP-G--------------VRALTVREGATGGERFSADVHPEQSAYL
                                                :       * .                          .    .     : * :

Q50E73_A6_11__ser                        IYTSGSTGRPKGVVVSHGAIVNRLAWMQAEYRLDATDRVLQKTPAGFDVSVWEFFWPLLE
BGC0000431_EFE73313.1_484_mod1_ser       IYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFFWPLIT
EFE73313.1_484_mod1_ser                  IYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFFWPLIT
EWS95122_476_mod1_ser                    IYTSGSTGTPKGVVNTHEGLVNRLLWMQDRYGLDATDRVLQKTSCGFDVAGWEFFWPLIT
Q9Z4X6_A1_ser                            IYTSGSTGRPKGVVISHRAIVNRLAWMQDTYGLEPSDRVLQKTPSGFDVSVWEFFWPLVQ
EFE73312.1_2615_mod3_ser                 IYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFFWPLIT
Q9FB23_A1_ser                            LYTSGSTGDPKGVLVPHRAIVNRLLWMQETYRLRPGERVLHKTPVTFDVSMWELLWPLTA
                                         :******* ****  .* .:**** ***  : *   :**::**.  ***: **::***  

Q50E73_A6_11__ser                        GAVLVFARPGGHRDAAYLAGLIERERITTAHFVPSMLRVFLEEPGAALCTG---LRRVIC
BGC0000431_EFE73313.1_484_mod1_ser       GAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG---LRWVVC
EFE73313.1_484_mod1_ser                  GAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG---LRWVVC
EWS95122_476_mod1_ser                    GATLVVAEPERHKDPAYLAALIAEQDVTTVHFVPSMLKGFLAEPTTAGCVS---LRRVMC
Q9Z4X6_A1_ser                            GATLVVARPGGHTDPAYLAGTVRREGVTTLHFVPSMLDVFLREPAAAALGGATPVRRVFC
EFE73312.1_2615_mod3_ser                 GAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG---LRWVVC
Q9FB23_A1_ser                            GATVVMARPGTHRDPARLVRRIAREAVTTVHFVPSMLTPFLTELARGTTRLPA-LRRVVC
                                         ** :*.*.*  * *.. *.  : .: :*. *******  ** *   .       :* *.*

Q50E73_A6_11__ser                        SGEALGTDLAVDFRAKL-PVPLHNLYGPTEAAVDVTHHAYEP--ATGTATVPIGRPIWNI
BGC0000431_EFE73313.1_484_mod1_ser       SGEALPPELRDQFFDVLEGVELHNLYGPTEASVDVTAWPCTP--DEGPA-VPIGRPVWNT
EFE73313.1_484_mod1_ser                  SGEALPPELRDQFFDVLEGVELHNLYGPTEASVDVTAWPCTP--DEGPA-VPIGRPVWNT
EWS95122_476_mod1_ser                    SGEALSADLVARFHALL-GCELHNLYGPTEAAIDVTAFACDPADASGSA-PPIGTPIANT
Q9Z4X6_A1_ser                            SGEALPAELRARFRAVS-DVPLHNLYGPTEAAVDVTYWPCAE--DTGDGPVPIGRPVWNT
EFE73312.1_2615_mod3_ser                 SGEALPPELRDQFFDVLEDVELHNLYGPTEASVDVTAWPCTP--DEGPA-VPIGHPVWNT
Q9FB23_A1_ser                            SGEELPAAAVNRAAGLL-DARLYNLYGPTEAAVDVTAWPCRPP-EPGP--VPIGLPIANT
                                         *** * .              *:********::***  .       *    *** *: * 

Q50E73_A6_11__ser                        RTYVLDAALRPVPPGVPGELYLAGAGLARGYHGRPALTAERFVACPFGVPGERMYRTGDL
BGC0000431_EFE73313.1_484_mod1_ser       RTYVLDTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFGTAGERMYRTGDV
EFE73313.1_484_mod1_ser                  RTYVLDTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFGTAGERMYRTGDV
EWS95122_476_mod1_ser                    RVYVLNRALRPVPAGVMGELYLAGTGLARGYLDRAPLTAERFVACPYGPSGSRMYRTGDL
Q9Z4X6_A1_ser                            RMYVLDAALRPVPAGVPGELYIAGVQLARGYLGRPALSAERFTADPHGAPGSRMYRTGDL
EFE73312.1_2615_mod3_ser                 RTYVLDTGLHPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFGTTGERMYRTGDV
Q9FB23_A1_ser                            TTEVLDGRLRPLPRPVPGELYLGGACLAHGYHHDPALTAARFLPAP---GGGRRYRTGDL
                                            **:  *:*:*  * *:**:.*  **:**   . *:* ** . *    * * *****:

Q50E73_A6_11__ser                        VRWRVDGTLEFVGRADDQVKVRGFRVELGEVEGAVAAHPDVVRAVVVVREDRPGDHRLVA
BGC0000431_EFE73313.1_484_mod1_ser       VRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALTSHATVAQTAVLVREDVPGDKRLVA
EFE73313.1_484_mod1_ser                  VRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALTSHATVAQTAVLVREDVPGDKRLVA
EWS95122_476_mod1_ser                    ARWDAYGRLVYMGRADEQVKIRGVRVEPAEIAAALVGHPDVGEAEVVARDDGPAGTHLVG
Q9Z4X6_A1_ser                            ARWNHDGSLDYLGRADHQVKLRGFRIELGEIEAALVRQPEIAQAAVVLREDRPGDQRLVA
EFE73312.1_2615_mod3_ser                 VRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALMSHAAVAQAAVLVREDVPGDKRLVA
Q9FB23_A1_ser                            VRQRADGALVFRGRTDDQVKIGGIRVEPGEVAEALRALPGVADAAVV-----PHDGRLAA
                                         .*    * * : **:*.***: *.*:* .*:  *:   . :  : *:     * . :*..
