CLUSTAL W multiple sequence alignment


Q9R9I9_A1_ser                            LVQHHLREK--VPFTGKVLDMEDP-----QTFSEDGSNLESISGPNQLAYVIYTSGSTGK
Q93I54v2_A2_ser                          LAQSHLRKS--VPFTGKVLDLEDP-----RFSWEDGSNLKQTAGPNHLAYVIYTSGSTGR
BGC0000400_AGM16413.1_2831_mod3_ser      LLQGRAGEE--VSFAGRIVNLDDA-----NSYAGDGSNPERVNQASDAAYVIYTSGTTGR
BGC0000400_AGM16412.1_5576_mod5_ser      LLQGRSGES--VSFAGRIVNLDDE-----SSYAEDGSNLEWVNQASDAAYVIYTSGTTGK
AHF21228.1_8208_mod6_ser                 LTQSHLEEQASLSFDGKVLVLDRPVLDGKDMYHEDGSNLEPLAGPRHVAYVIYTSGSTGK
AGM16413.1_2831_mod3_ser                 LLQGRAGEE--VSFAGRIVNLDDA-----NSYAGDGSNPERVNQASDAAYVIYTSGTTGR
Q70K00_A1_ser                            LVQNQSQER--VPFTGKVLDMKDP-----QNFCEDGSNVEPAAGPDHLAYVIYTSGSTGK
BGC0000449_AHF21228.1_8208_mod6_ser      LTQSHLEEQASLSFDGKVLVLDRPVLDGKDMYHEDGSNLEPLAGPRHVAYVIYTSGSTGK
AGM16412.1_5576_mod5_ser                 LLQGRSGES--VSFAGRIVNLDDE-----SSYAEDGSNLEWVNQASDAAYVIYTSGTTGK
AHF21228.1_5129_mod4_ser                 LTQSHLEEQATLSFDGKVLVLDRPVLNGKDMYHEDGTNLEPLAGPRHVAYVIYTSGSTGK
BGC0000449_AHF21228.1_5129_mod4_ser      LTQSHLEEQATLSFDGKVLVLDRPVLNGKDMYHEDGTNLEPLAGPRHVAYVIYTSGSTGK
Q93I54v1_A2_ser                          LAQSHLRKS--VPFTGKVLDLEDP-----RFSWEDGSNLKQTAGPNHLAYVIYTSGSTGR
Q6YK39_A1_ser                            LVQNQSQER--VPFTGKVLDMKNP-----QNFCEDGSNVEPAAGPDHLAYVIYTSGSTGK
                                         * * :  :   :.* *::: :.            **:* :    . . ********:**:

Q9R9I9_A1_ser                            PKGVMVEHRSVINRLVWMQENYPLDERDAILQKTAITFDVSVWELFWWSIVGSKVVLLPN
Q93I54v2_A2_ser                          PKGVMVEHRSVINRLVWMQEHYPLDKQDVILQKTPITFDVSVWELFWWSMTGSKAVLLSN
BGC0000400_AGM16413.1_2831_mod3_ser      PKGVLVEHGSVINRLLWMQKRYPIGPSDTIMQKTAITFDVSVWELFWWAFVGSKVCLLPV
BGC0000400_AGM16412.1_5576_mod5_ser      PKGVLVEHGSVINRLLWMQKQYPINANDTIMQKTAITFDVSVWELFWWAFVGSKVCLLPV
AHF21228.1_8208_mod6_ser                 PKGVMVEHHSVLNRILWMHDRYGLSAEDTILQKTAFTFDVSVWELFWWSMVGSKVSLLSV
AGM16413.1_2831_mod3_ser                 PKGVLVEHGSVINRLLWMQKRYPIGPSDTIMQKTAITFDVSVWELFWWAFVGSKVCLLPV
Q70K00_A1_ser                            PKGVMVEHRSVINRLVWMQEKYPLDERDAILQKTAITFDVSVWELFWWTISGSRLVLLPN
BGC0000449_AHF21228.1_8208_mod6_ser      PKGVMVEHHSVLNRILWMHDRYGLSAEDTILQKTAFTFDVSVWELFWWSMVGSKVSLLSV
AGM16412.1_5576_mod5_ser                 PKGVLVEHGSVINRLLWMQKQYPINANDTIMQKTAITFDVSVWELFWWAFVGSKVCLLPV
AHF21228.1_5129_mod4_ser                 PKGVMVEHHSVLNRILWMHDRYGLSAEDTILQKTAFTFDVSVWELFWWSMVGSKVSLLSV
BGC0000449_AHF21228.1_5129_mod4_ser      PKGVMVEHHSVLNRILWMHDRYGLSAEDTILQKTAFTFDVSVWELFWWSMVGSKVSLLSV
Q93I54v1_A2_ser                          PKGVMVEHRSVINRLVWMQEHYPLDKQDVILQKTPITFDVSVWELFWWSMTGSKAVLLSN
Q6YK39_A1_ser                            PKGVMVEHRSVINRLVWMQEKYPLDERDAILQKTAITFDVSVWELFWWTISGSRLVLLPN
                                         ****:*** **:**::**:..* :.  *.*:***.:************:: **:  **. 

Q9R9I9_A1_ser                            GGEKNPELILDTIEQKGVSTLHFVPAMLHAFLESMEQTPSGKLKRKLASLRYVFASGEAL
Q93I54v2_A2_ser                          GGEKNPDVILDTIAQKNVTIMHFVPAMLHAFLESMEQKSDEELKRKLASLKYVFASGEAL
BGC0000400_AGM16413.1_2831_mod3_ser      GGEKNPAVILDTIERQHISTMHFVPSMLHAFLEYVEEQPVAERERSLASLRRVFASGEAL
BGC0000400_AGM16412.1_5576_mod5_ser      GGEKNPAVILDTIAQQHISTMHFVPSMLHAFLEYVEEQPIAERERSLAALSRVFASGEAL
AHF21228.1_8208_mod6_ser                 GGEKNPEDIVETIARDGVSTMHFVPAMLHAFLEYVEQQPLEVVKAKLGTLRHVFASGEAL
AGM16413.1_2831_mod3_ser                 GGEKNPAVILDTIERQHISTMHFVPSMLHAFLEYVEEQPVAERERSLASLRRVFASGEAL
Q70K00_A1_ser                            GGEKNPELILDTIAQKGVSTMHFVPAMLHAFLESMDQKPSGMLKQKLASLRHVFASGEAL
BGC0000449_AHF21228.1_8208_mod6_ser      GGEKNPEDIVETIARDGVSTMHFVPAMLHAFLEYVEQQPLEVVKAKLGTLRHVFASGEAL
AGM16412.1_5576_mod5_ser                 GGEKNPAVILDTIAQQHISTMHFVPSMLHAFLEYVEEQPIAERERSLAALSRVFASGEAL
AHF21228.1_5129_mod4_ser                 GGEKNPEDIVETIARDSVSTMHFVPAMLHAFLEYVEQQPQEVIQAKLGTLRHVFASGEAL
BGC0000449_AHF21228.1_5129_mod4_ser      GGEKNPEDIVETIARDSVSTMHFVPAMLHAFLEYVEQQPQEVIQAKLGTLRHVFASGEAL
Q93I54v1_A2_ser                          GGEKNPDVILDTIAQKNVTIMHFVPAMLHAFLESMEQKSDEELKRKLASLKYVFASGEAL
Q6YK39_A1_ser                            GGEKNPELILDTIAQKGVSTMHFVPAMLHAFLESMDQKPSGMLKQKLASLRHVFASGEAL
                                         ******  *::** :. :: :****:******* ::: .    : .*.:*  ********

Q9R9I9_A1_ser                            TPKHVDGFQRIITPVSHAQIINLYGPTEATIDVSYFECEADKRYNSVPIGKPISNIQLYI
Q93I54v2_A2_ser                          TPAHVAGFHRMITPAGEAQIINLYGPTEATIDVSYFECEAGETLNSVPIGKPISNIQLYI
BGC0000400_AGM16413.1_2831_mod3_ser      TASQAERFERCIAPVNGARLINLYGPTEATVDVTYFDCQAGQPYTSVPIGRPIDNTQIYI
BGC0000400_AGM16412.1_5576_mod5_ser      TLSQVERFERCIAPASGARLINLYGPTEATVDVTYYDCEAGQPYTSVPIGKPIDNTQIYI
AHF21228.1_8208_mod6_ser                 PPQHVARFQRLVSDIAGAKLINLYGPTEATVDVSYFDCEPTEEYAVIPIGKPIQNIRLYI
AGM16413.1_2831_mod3_ser                 TASQAERFERCIAPVNGARLINLYGPTEATVDVTYFDCQAGQPYTSVPIGRPIDNTQIYI
Q70K00_A1_ser                            KPVHVAGFKRIITSVSQAQIINLYGPTEATIDVSYFDCQTEETYASIPIGKPISNIQLYI
BGC0000449_AHF21228.1_8208_mod6_ser      PPQHVARFQRLVSDIAGAKLINLYGPTEATVDVSYFDCEPTEEYAVIPIGKPIQNIRLYI
AGM16412.1_5576_mod5_ser                 TLSQVERFERCIAPASGARLINLYGPTEATVDVTYYDCEAGQPYTSVPIGKPIDNTQIYI
AHF21228.1_5129_mod4_ser                 PPQHVARFQRLVSGIAGAKLINLYGPTEATVDVSYFDCEPTEEYAVIPIGKPIQNIRLYI
BGC0000449_AHF21228.1_5129_mod4_ser      PPQHVARFQRLVSGIAGAKLINLYGPTEATVDVSYFDCEPTEEYAVIPIGKPIQNIRLYI
Q93I54v1_A2_ser                          TPAHVAGFHRMITPAGEAQIINLYGPTEATIDVSYFECEAGETLNSVPIGKPISNIQLYI
Q6YK39_A1_ser                            KPVHVAGFKHIITSVSQAQIINLYGPTEATIDVSYFDCQTEETYASIPIGKPISNIQLYI
                                            :.  *.: ::    *::**********:**:*::*:. :    :***:**.* ::**

Q9R9I9_A1_ser                            LQAG--YMQPVGVAGELCIAGDGLARGYLNRPELTAEKFVKNPFSAG----ERMYRTGDL
Q93I54v2_A2_ser                          VQPGSEYFQPLGVAGELCIAGDGLARGYLNRPELTAEKFAAHPFEAG----KRMYRTGDL
BGC0000400_AGM16413.1_2831_mod3_ser      VNRQ-NQLQPIGVAGELCIAGAGLARGYWERPELTAEKFVEIPFKPS----ERMYRTGDL
BGC0000400_AGM16412.1_5576_mod5_ser      VNRQ-DQLQPIGVAGELCIAGVGLARGYLKRPELTAEKFVTIPFMPG----ARMYRTGDL
AHF21228.1_8208_mod6_ser                 VKEGTEQLQPIGVAGELCIGGVGVARGYLNRPELTAEKFVADSFAGGEAGYERMYRTGDL
AGM16413.1_2831_mod3_ser                 VNRQ-NQLQPIGVAGELCIAGAGLARGYWERPELTAEKFVEIPFKPS----ERMYRTGDL
Q70K00_A1_ser                            LHADLEHMQPIGVAGELCIAGDGLARGYLNRPELTAEKFVNHPIASG----ERIYRTGDL
BGC0000449_AHF21228.1_8208_mod6_ser      VKEGTEQLQPIGVAGELCIGGVGVARGYLNRPELTAEKFVADSFAGGEAGYERMYRTGDL
AGM16412.1_5576_mod5_ser                 VNRQ-DQLQPIGVAGELCIAGVGLARGYLKRPELTAEKFVTIPFMPG----ARMYRTGDL
AHF21228.1_5129_mod4_ser                 VKEGTEQLQPIGVAGELCIGGVGVARGYLNRPELTAEKFVADPFADGEAGYERMYRTGDL
BGC0000449_AHF21228.1_5129_mod4_ser      VKEGTEQLQPIGVAGELCIGGVGVARGYLNRPELTAEKFVADPFADGEAGYERMYRTGDL
Q93I54v1_A2_ser                          VQPGSEYFQPLGVAGELCIAGDGLARGYLNRPELTAEKFAAHPFEAG----KRMYRTGDL
Q6YK39_A1_ser                            LHADLEHMQPIGVAGELCIAGDGLARGYLNRPELTAEKFVNHPIASG----ERIYRTGDL
                                         ::     :**:********.* *:**** :*********.  .:  .     *:******

Q9R9I9_A1_ser                            ARWLPDGNIEYLGRIDHQVKIRGYRIETGEVEAALFHIPSIQESIVLAQEIN-EEISLCA
Q93I54v2_A2_ser                          ARWLPDGNIEYLGRIDHQVKIRGYRIELGEIEASLLQLDAVKEAVVIAIEKE-GSKQLCA
BGC0000400_AGM16413.1_2831_mod3_ser      ARWLPDGNIEYLGRLDHQVKIRGYRIELGEIEAQLLQAAAIRETVVVAREDESGQKALCA
BGC0000400_AGM16412.1_5576_mod5_ser      ARWLPDGSIEYLGRIDHQVKIRGYRIELGEIEAQLLQVEFIREAVVVAREDESGQKALCA
AHF21228.1_8208_mod6_ser                 ARWMPDGNIEYLGRIDHQVKIRGYRIELGEVESQLLKVESVREAVVMARADETGQKQMVA
AGM16413.1_2831_mod3_ser                 ARWLPDGNIEYLGRLDHQVKIRGYRIELGEIEAQLLQAAAIRETVVVAREDESGQKALCA
Q70K00_A1_ser                            ARWLPDGNIEYLGRIDHQVKIRGYRIEIGEVEGAFFQLPAIKEAIIIAREID-GETSLCA
BGC0000449_AHF21228.1_8208_mod6_ser      ARWMPDGNIEYLGRIDHQVKIRGYRIELGEVESQLLKVESVREAVVMARADETGQKQMVA
AGM16412.1_5576_mod5_ser                 ARWLPDGSIEYLGRIDHQVKIRGYRIELGEIEAQLLQVEFIREAVVVAREDESGQKALCA
AHF21228.1_5129_mod4_ser                 ARWMPDGNIEYLGRIDHQVKIRGYRIELGEVESQLLKVESVREAVVMARADETGQKQMVA
BGC0000449_AHF21228.1_5129_mod4_ser      ARWMPDGNIEYLGRIDHQVKIRGYRIELGEVESQLLKVESVREAVVMARADETGQKQMVA
Q93I54v1_A2_ser                          ARWLPDGNIEYLGRIDHQVKIRGYRIELGEIEASLLQLDAVKEAVVIAIEKE-GSKQLCA
Q6YK39_A1_ser                            ARWLPDGNIEYLGRIDHQVKIRGYRIEIGEVEGAFFQLPVIKEAIVIAREID-GETSLCA
                                         ***:***.******:************ **:*. :::   ::*::::*   :  .  : *
