CLUSTAL W multiple sequence alignment


Q9Z4X6_A1_ser                            --LTTRDTAERLP-G-DGTPRLLLDEPAAAGTTAAGAPAPPGTLPRALPAPGHPAYVIYT
O85168_A1_ser                            --LTTRDLSDNLP-A-SDLPVLVLDGHNDRAQLARQQSVNPDA-KALGLQPNHLAYVLYT
BGC0000398_AFH75329.1_3793_mod4_ser      VQGATRHLAQA-----SGLALLDLD----QPQWAGQSRDNP---QLPHLTPRHLAYVIYT
BGC0000398_AFH75330.1_2671_mod3_ser      AQGATLGLLGD-----PDVPVVDLE----QSVWSRQPRINP---RIAGLTPRHLAYVIYT
AFZ61525.1_3733_mod4_ser                 AQGATRGLLG-------DAPVIDLD----RPTWQHQSIDNP---QVQAFS----AYVIYT
EFE73312.1_2615_mod3_ser                 --VTSRATEGAVPEGADIPARVQVDGADVLAQLKALSGEPVSS---VEVLPSHVAYVIYT
BGC0000431_EFE73313.1_484_mod1_ser       --LTSESVRSVVP-GVEGLERVVVDAAQTVSALADLSGEPVSS---VEVLPSHVAYVIYT
Q83VS0_A6_16__ser                        --LTTRDLSDNLP-A-SDLPVLVLDGHDDRAQLARQQSVNPDA-KALGLQPNHLAYVLYT
O85168_A2_ser                            --LTSHELLADLP-D-LGVPALVLDGRDDSALLKKQPTGNPDA-KALDLQPNHLAYVLYT
Q2N3S9_A1_9__ser                         --LTQSSFSGVLA-GFTGT-RLCLDTEASRLSSYSADS------PRVEVRPEHLAYVIYT
Q50E73_A6_11__ser                        ---LTRGDVE-LP-G-S-VPRIGLDDTEIRATLATA----PGTNPGTPVTEAHPAYMIYT
AFZ61526.1_1614_mod2_ser                 AQGGTRGLLG-------DVPVVDLD----RPTWQHPREDNP---AVQGIS----AYVIYT
BGC0001149_CDF96614.1_480_mod1_ser       --LTTRVLLSSLP-A-VTMPVLCLD--SDLEQLSRQPQHNPDP-VAQGLTPRHLAYVIYT
EFE73313.1_484_mod1_ser                  --LTSESVRSVVP-GVEGLERVVVDAAQTVSALADLSGEPVSS---VEVLPSHVAYVIYT
                                                              : ::                             **::**

Q9Z4X6_A1_ser                            SGSTGRPKGVVISHRAIVNRLAWMQDTYGLEPSDRVLQKTPSGFDVSVWEFFWPLVQGAT
O85168_A1_ser                            SGSTGTPKGVMNEHLGVVNRLLWARDAYQVNSQDRVLQKTPCGFDLSVWEFFLPLLTGAE
BGC0000398_AFH75329.1_3793_mod4_ser      SGSTGQPKGAMNEHRAVVNRLLWMQEQYRLDVDDAVLQKTPFSFDVSVWEFFWPLFTGAR
BGC0000398_AFH75330.1_2671_mod3_ser      SGSTGQPKGAMNEHRAVVNRLLWMQEQYRLTSCDAVLQKTPFSFDVSVWEFFWPLFTGAR
AFZ61525.1_3733_mod4_ser                 SGSTGQPKGVINDHPGVVNRLLWMQDAYGLQAHDRVLQKTPFSFDVSVWEFFWPLFTGAC
EFE73312.1_2615_mod3_ser                 SGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFFWPLITGAG
BGC0000431_EFE73313.1_484_mod1_ser       SGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFFWPLITGAG
Q83VS0_A6_16__ser                        SGSTGTPKGVMNEHLGVVNRLLWARDAYQVNSQDRVLQKTPFGFDVSVWEFFLPLLTGAE
O85168_A2_ser                            SGSTGTPKGVMNEHLGVVNRLLWARDAYQVNSQDRVLQKTPFGFDVSVWEFFLPLLTGAE
Q2N3S9_A1_9__ser                         SGSTGMPKGCMLSHRAICNRLHWMQEAYALTPLDRVLQKTPFTFDVSVWEFFWPLITGAR
Q50E73_A6_11__ser                        SGSTGRPKGVVVSHGAIVNRLAWMQAEYRLDATDRVLQKTPAGFDVSVWEFFWPLLEGAV
AFZ61526.1_1614_mod2_ser                 SGSTGQPKGVINDHPGVVNRLLWMQDAYGLQAHDRVLQKTPFSFDVSVWEFFWPLFTGAC
BGC0001149_CDF96614.1_480_mod1_ser       SGSTGLPKGVMNQHDGVVNRLLWARDAYQVDEHSRVLQKTPFSFDVSVWEFFLPLLSGAQ
EFE73313.1_484_mod1_ser                  SGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFFWPLITGAG
                                         ***** ***    * .: *** * :  : :   . *:****  **:****** **. ** 

Q9Z4X6_A1_ser                            LVVARPGGHTDPAYLAGTVRREGVTTLHFVPSMLDVFLREPAAAALGGATPVRRVFCSGE
O85168_A1_ser                            LVMAPPGGHQDPDYLAQVMSDAGITLLHFVPSMLDVFLEHRSTRDFPQ---LRRVLCSGE
BGC0000398_AFH75329.1_3793_mod4_ser      LVMARPEGHKDPAYLRQLIREQGISTLHFVPSMLDVFLAHDATPDDLG---LRQVMCSGE
BGC0000398_AFH75330.1_2671_mod3_ser      LVMARPEGHKDPAYLRQVIARENITTLHFVPSMLDVFLAYGETRECAS---LRQVMCSGE
AFZ61525.1_3733_mod4_ser                 LVMARPGGHKDPAYLCEVIANEQITTLHFVPSMLDVFLAHGDVSQAAG---LQRVMCSGE
EFE73312.1_2615_mod3_ser                 LVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG---LRWVVCSGE
BGC0000431_EFE73313.1_484_mod1_ser       LVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG---LRWVVCSGE
Q83VS0_A6_16__ser                        LVMARPGGHQDPDYLAQVMSDAGITLLHFVPSMLDVFLEHRSTRDFPQ---LRRVLCSGE
O85168_A2_ser                            LVMARPSGHQDPDYLAQVISDAGITLLHFVPSMLDVFLEHRSTRDFPQ---LRRVLCSGE
Q2N3S9_A1_9__ser                         IVLAAPGAERDPAALAGLIQEHGVTACHFVPSMLRLFLDEPRAAGCAS---LRHVFFSGE
Q50E73_A6_11__ser                        LVFARPGGHRDAAYLAGLIERERITTAHFVPSMLRVFLEEPGAALCTG---LRRVICSGE
AFZ61526.1_1614_mod2_ser                 LVMARPGGHKDPAYLCEVIAAEQITTLHFVPSMLDVFLAHGDVSQAAG---LVRVMCSGE
BGC0001149_CDF96614.1_480_mod1_ser       LVVAAPGGHQDPRYLLDIMASAGITLLHFVPSMLQVFLDQVTAQPLPA---LKKVLCSGE
EFE73313.1_484_mod1_ser                  LVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG---LRWVVCSGE
                                         :*.* * .. *.  *   :    ::  ******* :**    .        :  *. ***

Q9Z4X6_A1_ser                            ALPAELRARFRAVS-DVPLHNLYGPTEAAVDVTYWPC-AE-DTGDG-PVPIGRPVWNTRM
O85168_A1_ser                            ALPRALQRRFEQQLKGVELHNLYGPTEAAIDVTAWEC-RP--TDPGDSVPIGRPIANIQM
BGC0000398_AFH75329.1_3793_mod4_ser      ALPGSLVRRFKQQLPNVALHNLYGPTEAAVDVTAWDCTGPLDATPD-NTPIGKPIANTRL
BGC0000398_AFH75330.1_2671_mod3_ser      ALPGSLVRRFKQQLPNVGLHNLYGPTEAAVDVTAWDCTGPLETTPD-NTPIGKPIANTRL
AFZ61525.1_3733_mod4_ser                 ALPGSLVRRFKQQLPGIGLYNLYGPTEAAVDVTAWNCARP--DVPD-NTPIGKPIANTRM
EFE73312.1_2615_mod3_ser                 ALPPELRDQFFDVLEDVELHNLYGPTEASVDVTAWPC-TP-DEGPA--VPIGHPVWNTRT
BGC0000431_EFE73313.1_484_mod1_ser       ALPPELRDQFFDVLEGVELHNLYGPTEASVDVTAWPC-TP-DEGPA--VPIGRPVWNTRT
Q83VS0_A6_16__ser                        ALPRALQRRFEQQLKGVELHNLYGPTEAAIDVTAWEC-RP--TDPGDSVPIGRPIANIQM
O85168_A2_ser                            ALPRALQRRFEQHLKGVELHNLYGPTEAAIDVTAWEC-RP--TDPGDSVPIGRPIANIQM
Q2N3S9_A1_9__ser                         ALPYPLMERALSTF-SAQLHNLYGPTEAAVDVSFWKC-NL-RDDRK--VPIGRPIANIRL
Q50E73_A6_11__ser                        ALGTDLAVDFRAKL-PVPLHNLYGPTEAAVDVTHHAY-EP-ATGTA-TVPIGRPIWNIRT
AFZ61526.1_1614_mod2_ser                 ALPGSLVRRFKQQLPGSELHNLYGPTEAAVDVTAWNCAGP--VTPD-NTPIGKPIANTRM
BGC0001149_CDF96614.1_480_mod1_ser       ALPYALQTRFFERLPGVQLHNLYGPTEAAIDVTAWQC-RP-DVHPG-IVPIGRPIANTQL
EFE73313.1_484_mod1_ser                  ALPPELRDQFFDVLEGVELHNLYGPTEASVDVTAWPC-TP-DEGPA--VPIGRPVWNTRT
                                         **   *            *:********::**:               .***:*: * : 

Q9Z4X6_A1_ser                            YVLDAALRPVPAGVPGELYIAGVQLARGYLGRPALSAERFTADPHG-APGSRMYRTGDLA
O85168_A1_ser                            HVLDALGQLQPMGVAGELHIGGIGVARGYLNQPQLSAERFIADPFSNDPQARLYKTGDVG
BGC0000398_AFH75329.1_3793_mod4_ser      YLLDAQLQPVPLGVVGELFIAGVQVARGYLNREQLTAERFVDDPFSAEPGARMYRTGDLG
BGC0000398_AFH75330.1_2671_mod3_ser      YLLDAQLQPVPLGVVGELFIAGVQVARGYLNREQLTAERFVDDPFSAEPDARMYRTGDLG
AFZ61525.1_3733_mod4_ser                 YVLDGQMQPVPLGVVGELFIGGVQVARGYLNRPELTAERFLKDPFT---DGRLYRTGDLG
EFE73312.1_2615_mod3_ser                 YVLDTGLHPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFG-TTGERMYRTGDVV
BGC0000431_EFE73313.1_484_mod1_ser       YVLDTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFG-TAGERMYRTGDVV
Q83VS0_A6_16__ser                        HVLDALGQLQPLGVAGELHIGGIGVARGYLNQPDLSAERFIADPFSEDRQARLYKTGDVG
O85168_A2_ser                            HVLDALGQLQPMGVAGELHIGGIGVARGYLNQPQLSAERFIADPFSNDPQARLYKTGDVG
Q2N3S9_A1_9__ser                         YILDEQQRPVRPDQTGELYIAGVGLARGYLNRPELTAERFVRDPFDPSPGARMYKTGDRA
Q50E73_A6_11__ser                        YVLDAALRPVPPGVPGELYLAGAGLARGYHGRPALTAERFVACPFG-VPGERMYRTGDLV
AFZ61526.1_1614_mod2_ser                 YVLDAQMQPVPLGVVGELFIGGVQVARGYLNRPELTAERFLKDPFT---DGRLYRTGDVG
BGC0001149_CDF96614.1_480_mod1_ser       YILDANLQLLPPGIAGELHIGGIGVARGYLNREQLTAERFIRDPFQADPQARLYKTGDLG
EFE73313.1_484_mod1_ser                  YVLDTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFG-TAGERMYRTGDVV
                                         ::**   :    .  *:*.:.*  :**** .:  *:****   *.      *:*:***  

Q9Z4X6_A1_ser                            RWNHDGSLDYLGRADHQVKLRGFRIELGEIEAALVRQPEIAQAAVVLREDRPGDQRLVA
O85168_A1_ser                            RWLANGALEYLGRNDFQVKIRGLRIEIGEIEAALAKHPAVHEAVVTAREDIPGDKRLVA
BGC0000398_AFH75329.1_3793_mod4_ser      RYLTDGNIEYLGRNDDQVKIRGLRIELGEIQARLTQLEGIKEAVVLAREDVPGDKRLVA
BGC0000398_AFH75330.1_2671_mod3_ser      RYLADGNIEYLGRNDDQVKIRGLRIELGEIQARLTQLEGIKEAVVLAREDVPGDKRLVA
AFZ61525.1_3733_mod4_ser                 RYLLDGTIEYLGRNDDQVKIRGLRIELGEIQARLLEHPQVNEAAVVAR-----DDRLVA
EFE73312.1_2615_mod3_ser                 RWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALMSHAAVAQAAVLVREDVPGDKRLVA
BGC0000431_EFE73313.1_484_mod1_ser       RWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALTSHATVAQTAVLVREDVPGDKRLVA
Q83VS0_A6_16__ser                        RWLANGALEYLGRNDFQVKIRGLRIEIGEIEAALAKHPAVHEAVVTAREDIPGDKRLVA
O85168_A2_ser                            RWLANGALEYLGRNDFQVKIRGLRIEIGEIEAALAKHPAVHEAVVTAREDIPGDKRLVA
Q2N3S9_A1_9__ser                         AWLPDGNIDFLGRMDGQIKLRGLRIELGEIEAALLGHEAVREAAVAVRDADSGDPRLVA
Q50E73_A6_11__ser                        RWRVDGTLEFVGRADDQVKVRGFRVELGEVEGAVAAHPDVVRAVVVVREDRPGDHRLVA
AFZ61526.1_1614_mod2_ser                 RYLADGTIEYLGRNDDQVKIRGLRIELGEIQSRLTEYPPVNEAAVIAR-----DNRLIA
BGC0001149_CDF96614.1_480_mod1_ser       RWLPDGSIEYLGRNDFQVKIRGLRIELGEIEARLAACAGVKEVVVIARQETEGDACLSA
EFE73313.1_484_mod1_ser                  RWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALTSHATVAQTAVLVREDVPGDKRLVA
                                          :  :* ::::** * *:*:**:*:*:**::. :     : ...*  *     *  * *
