CLUSTAL W multiple sequence alignment


AGM16412.1_3015_mod3_thr                 LLPHDLRDKVGFDGT-------VVMLDDEQSYVE----DSSNPATASK-----P-SDLAY
AEI70245.1_1510_mod2_thr                 -----VTSEAGAQGLPDTGSLPRLVLDAPDTAERLRAYSPDNPGDGDRRGPLSP-LSPAY
AEF33078.1_463_mod1_thr                  -----LTDTDGADRV--RGAVHPLLLDDPALAAELTGLPGTDPTAAERPAAAGP-DSLAY
BGC0000400_AGM16412.1_3015_mod3_thr      LLPHDLRDKVGFDGT-------VVMLDDEQSYVE----DSSNPATASK-----P-SDLAY
Q9RBY6_A1_thr                            -----IGDAANLPKI---SSLSVLALD------ELLSAPALQPAAQDTR--IDPNNSTAY
                                              : .  .            : **      .       :*   .      *  . **

AGM16412.1_3015_mod3_thr                 VIYTSGTTGKPKGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALL
AEI70245.1_1510_mod2_thr                 MIYTSGSTGKPKGVVIPHQNVIRLFASTQHWFGFGSEDVWTLFHSYAFDFSVWEIWGPLL
AEF33078.1_463_mod1_thr                  VIYTSGSTGRPKGVAVTHHNVLRLFRQTDHWFGFGADDVWTLFHSYAFDFSVWEIWGPLL
BGC0000400_AGM16412.1_3015_mod3_thr      VIYTSGTTGKPKGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALL
Q9RBY6_A1_thr                            IIYTSGSTGEPKGVQVSHGNVSRLLESTQRAYGFNAQDVWSMFHSIGFDFSVWEIWGALA
                                         :*****:**.***. : * ** **: .:.. :.*.: *.*::***  *******::*.* 

AGM16412.1_3015_mod3_thr                 YGGRLVVVPQLTAK--------------NPAQFLELLHEQQVTILNQTPTYFYQLLREAL
AEI70245.1_1510_mod2_thr                 HGSRLVVVSHTVSR--------------SPAEFLQLLVRERVTVLNQTPSAFYQLMQADR
AEF33078.1_463_mod1_thr                  HGGRLVVVPFDTSR--------------SPADFLRLLVRERVTVLNQTPSAFYQLIAAER
BGC0000400_AGM16412.1_3015_mod3_thr      YGGRLVVVPQLTAK--------------NPAQFLELLHEQQVTILNQTPTYFYQLLREAL
Q9RBY6_A1_thr                            HGARW-PLSRMTSRALLPPCVNGSPISASPCS----ARRHRLSVV---------LMRPIV
                                         :*.*   :.  .::              .*..      ..:::::         *:    

AGM16412.1_3015_mod3_thr                 AEP--GQELKVRKVIFGG---EALNPQLLKDWKTKYPHT--QLINMYGITETTVHVTYKE
AEI70245.1_1510_mod2_thr                 EHPSLGGELALRYVVFGG---EALELGRLEEWYARHPDDAPRLINMYGITETTVHVSYKE
AEF33078.1_463_mod1_thr                  ERPDLAGRLTLRHVVFGG---EALETHRLEDWYARHGDDAPRLVNMYGITETTVHVTYAA
BGC0000400_AGM16412.1_3015_mod3_thr      AEP--GQELKVRKVIFGG---EALNPQLLKDWKTKYPHT--QLINMYGITETTVHVTYKE
Q9RBY6_A1_thr                            ATPR-------RCAALRGARWRTLPASVLRPWVERHGDQKPALINMYGITEATVHTTFKR
                                           *        * . : *   .:*    *. *  :: .    *:*******:***.::  

AGM16412.1_3015_mod3_thr                 ITQVEIEQAK-SNIGRPIPTLKVYVLDANRQCVPVGVAGEMYVAGDGLARGYLHRPELTA
AEI70245.1_1510_mod2_thr                 LDRSSAASGAGSLIGEAIPDLRVYVLDEALQPVPPGVAGEMYVAGAGLARGYWGRPGLTA
AEF33078.1_463_mod1_thr                  LDRETVRAARGSVIGEPIPDLDVYVLDGELRPVPEGATGELYVAGPGLARGYLGRPGLTA
BGC0000400_AGM16412.1_3015_mod3_thr      ITQVEIEQAK-SNIGRPIPTLKVYVLDANRQCVPVGVAGEMYVAGDGLARGYLHRPELTA
Q9RBY6_A1_thr                            VLAQDLETAAMVSLGKPL-DVRLHLLDANQAPVAAGTTGELYIEGAGVAQGYLNRERLNV
                                         :       .    :*..:  : :::**     *. *.:**:*: * *:*:**  *  *..

AGM16412.1_3015_mod3_thr                 DKFVDSPFES-GGRMYRTGDLARWLPDGNIEYLGRIDHQVKIRGYRIELGEVEAQLTKVD
AEI70245.1_1510_mod2_thr                 ERFVADPFGAPGSRMYRTGDLARRFADGSLDYLGRADHQVKIRGFRIEPGEIEAVLAKHP
AEF33078.1_463_mod1_thr                  ERFVADPFGAPGGRMYRTGDLACVLDDGSLGYLGRADSQVKIRGFRIELGEIEAALERHP
BGC0000400_AGM16412.1_3015_mod3_thr      DKFVDSPFES-GGRMYRTGDLARWLPDGNIEYLGRIDHQVKIRGYRIELGEVEAQLTKVD
Q9RBY6_A1_thr                            ERFVELPGAV---RAYRTGDLMTLESNGEYRYAGRCDEQLKISGFRIEPGEIEASLQTSP
                                         ::**  *      * ******     :*.  * ** * *:** *:*** **:** *    

AGM16412.1_3015_mod3_thr                 PVREAIVIAREDGHGEKQLCA
AEI70245.1_1510_mod2_thr                 GVAQVAVVVREDQPGDKRLVA
AEF33078.1_463_mod1_thr                  GVERAAVVVREDRPGDQRLVA
BGC0000400_AGM16412.1_3015_mod3_thr      PVREAIVIAREDGHGEKQLCA
Q9RBY6_A1_thr                            SVAAAHVGVHDYGDGDLRLVA
                                          *  . * .::   *: :* *
