CLUSTAL W multiple sequence alignment


AEF33078.1_463_mod1_thr                  LTDTDGADRV--RGAVHPLLLDDPALAAELTGLPGTDPTAAERPAAAGPDSLAYVIYTSG
AEI70245.1_1510_mod2_thr                 VTSEAGAQGLPDTGSLPRLVLDAPDTAERLRAYSPDNPGDGDRRGPLSPLSPAYMIYTSG
AEA30272.1_474_mod1_thr                  LTDSASAAGLPDPGTAAPLLLDDPGIVAELARQADGDLTEAERTAALDPRHAAYMIYTSG
                                         :*.  .*  :   *:   *:** *  . .*   .  :   .:* .. .*   **:*****

AEF33078.1_463_mod1_thr                  STGRPKGVAVTHHNVLRLFRQTDHWFGFGADDVWTLFHSYAFDFSVWEIWGPLLHGGRLV
AEI70245.1_1510_mod2_thr                 STGKPKGVVIPHQNVIRLFASTQHWFGFGSEDVWTLFHSYAFDFSVWEIWGPLLHGSRLV
AEA30272.1_474_mod1_thr                  STGRPKGVVVPHRNVVRLFTATEPWFGFDADDVWTLFHSYAFDFSVWEIWGPLLHGGTLV
                                         ***:****.:.*:**:***  *: ****.::*************************. **

AEF33078.1_463_mod1_thr                  VVPFDTSRSPADFLRLLVRERVTVLNQTPSAFYQLIAAERERPDLAGRLTLRHVVFGGEA
AEI70245.1_1510_mod2_thr                 VVSHTVSRSPAEFLQLLVRERVTVLNQTPSAFYQLMQADREHPSLGGELALRYVVFGGEA
AEA30272.1_474_mod1_thr                  VVPHEVNRSPEEFLRLLARERVTVLNQTPSAFYQLMRADRETSDAGALPALRRVVFGGEA
                                         **.. ..*** :**:**.*****************: *:** .. ..  :** *******

AEF33078.1_463_mod1_thr                  LETHRLEDWYARHGDDAPRLVNMYGITETTVHVTYAALDRETVRAARGSVIGEPIPDLDV
AEI70245.1_1510_mod2_thr                 LELGRLEEWYARHPDDAPRLINMYGITETTVHVSYKELDRSSAASGAGSLIGEAIPDLRV
AEA30272.1_474_mod1_thr                  LDLWRLEPWYDSHPDDAPVLVNMYGITETTVHVSHVALDATSVGAERGSVIGTPIPDLGV
                                         *:  *** **  * **** *:************::  **  :. :  **:** .**** *

AEF33078.1_463_mod1_thr                  YVLDGELRPVPEGATGELYVAGPGLARGYLGRPGLTAERFVADPFGAPGGRMYRTGDLAC
AEI70245.1_1510_mod2_thr                 YVLDEALQPVPPGVAGEMYVAGAGLARGYWGRPGLTAERFVADPFGAPGSRMYRTGDLAR
AEA30272.1_474_mod1_thr                  HLLDDALRPVPSGVAAEMYVSGEGLARGYHGRPDLTSHRFVADPFGAPGSRMYRTGDVAR
                                         ::**  *:*** *.:.*:**:* ****** ***.**:.***********.*******:* 

AEF33078.1_463_mod1_thr                  VLDDGSLGYLGRADSQVKIRGFRIELGEIEAALERHPGVERAAVVVREDRPGDQRLVA
AEI70245.1_1510_mod2_thr                 RFADGSLDYLGRADHQVKIRGFRIEPGEIEAVLAKHPGVAQVAVVVREDQPGDKRLVA
AEA30272.1_474_mod1_thr                  RTADGELEFVGRADHQVKIRGFRIELGEIEAVVEGLAEVAQAAVVVREDQPGDKRLVA
                                            **.* ::**** ********** *****.:   . * :.*******:***:****
