CLUSTAL W multiple sequence alignment


BGC0000400_AGM16412.1_3015_mod3_thr      LLPHDLRDK---VGFDGTVVMLDDEQSYVEDSSNPATASK------PSDLAYVIYTSGTT
AEC14346.1_19_mod1_thr                   -----IGDKGRINGIDCNYVTLDE----VIENSNDITGENFHSLIDPKDPAYIIFTSGST
AGM16412.1_3015_mod3_thr                 LLPHDLRDK---VGFDGTVVMLDDEQSYVEDSSNPATASK------PSDLAYVIYTSGTT
                                              : **    *:* . * **:    * :.**  *..:      *.* **:*:***:*

BGC0000400_AGM16412.1_3015_mod3_thr      GKPKGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGRLVVV
AEC14346.1_19_mod1_thr                   GKPKGVCVSHENVMNLFLGCDGLFEFNNKDIWTFFHSYAFDFSVWEMWGAWIYGGEVVVV
AGM16412.1_3015_mod3_thr                 GKPKGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGRLVVV
                                         *****. :.*:**:.*::....**:**. * **:***:.********:** :***.:***

BGC0000400_AGM16412.1_3015_mod3_thr      PQLTAKNPAQFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEALNPQ
AEC14346.1_19_mod1_thr                   SFEESRNPISFVDLLISTQTTVFNCTPSAFFEVIGE-LINRQNELSLKYIIFGGEALNFK
AGM16412.1_3015_mod3_thr                 PQLTAKNPAQFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEALNPQ
                                         .   ::** .*::** . *.*::* **: *:::: * * :  :**.:: :******** :

BGC0000400_AGM16412.1_3015_mod3_thr      LLKDW----KTKYPHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKVYVL
AEC14346.1_19_mod1_thr                   KLTQWFSPENDRLP--KLINMYGITETTVHVTYKQITKSDVEKGITNIGKVLPHLGFKVM
AGM16412.1_3015_mod3_thr                 LLKDW----KTKYPHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKVYVL
                                          *.:*    : : *  :*****************:**: ::*:. :***: :* * . *:

BGC0000400_AGM16412.1_3015_mod3_thr      DANRQCVPVGVAGEMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARWLPD
AEC14346.1_19_mod1_thr                   NQNEEEVTGDEEGELYVSGKGVSLGYYKNTMMNKMKFTDI---DNVRYYKSGDVVKVLDD
AGM16412.1_3015_mod3_thr                 DANRQCVPVGVAGEMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARWLPD
                                         : *.: *. .  **:**:*.*:: ** :.. :.  **.*    .. * *::**:.: * *

BGC0000400_AGM16412.1_3015_mod3_thr      GNIEYLGRIDHQVKIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCA
AEC14346.1_19_mod1_thr                   GDLQYIARNDEQVQLRGFRIELGEIESSYNDLKNIKNAVVTMDKAFNDDMHLFL
AGM16412.1_3015_mod3_thr                 GNIEYLGRIDHQVKIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCA
                                         *:::*:.* *.**::**:******:*:. ..:. :::*:*   :  :.: :*  
