CLUSTAL W multiple sequence alignment


Q70K00_A2_thr                            LLQHHLLEGTDYQSHTVFLDDPSSYGAEASNLKLNVMPNQLAYVIYTSGTTGNPKGTLIE
BGC0000400_AGM16412.1_3015_mod3_thr      LLPHDLRDKVGFDGTVVMLDDEQSYVEDSSNPATASKPSDLAYVIYTSGTTGKPKGTLIE
AGM16412.1_3015_mod3_thr                 LLPHDLRDKVGFDGTVVMLDDEQSYVEDSSNPATASKPSDLAYVIYTSGTTGKPKGTLIE
Q6YK39_A2_thr                            LLQHHLLEGTDYQSHTVFLDDPSSYGAETSNLNLNVMPNQLAYVIYTSGTTGNPKGTLIE
                                         ** *.* : ..::. .*:*** .**  ::**      *.:************:*******

Q70K00_A2_thr                            HKNVVRLLFNNKNVFDFNASDTWTLFHSFCFDFSVWEMYGALLYGGKLVIIPKQIAKNPE
BGC0000400_AGM16412.1_3015_mod3_thr      HKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGRLVVVPQLTAKNPA
AGM16412.1_3015_mod3_thr                 HKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGRLVVVPQLTAKNPA
Q6YK39_A2_thr                            HKNVVRLLFNNKNVFDFNASDTWTLFHSFCFDFSVWEMYGALLYGGKLVIVPKQIAKNPE
                                         **********.**:****::**************************:**::*:  **** 

Q70K00_A2_thr                            RYLQLLKSEAVTILNQTPSYFYQLMQEERADPESNLNIRKIIFGGEALNPSFLKDWKLKY
BGC0000400_AGM16412.1_3015_mod3_thr      QFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEALNPQLLKDWKTKY
AGM16412.1_3015_mod3_thr                 QFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEALNPQLLKDWKTKY
Q6YK39_A2_thr                            RYLQLLKSEAVTILNQTPSYFYQLMQEERADPESNLNIRKIIFGGEALNPSFLKDWKLKY
                                         ::*:**:.: ********:*****::*  *:* .:*::**:*********.:***** **

Q70K00_A2_thr                            PLTQLINMYGITETTVHVTYKEITEREIDEGRSNIGQPIPTLQAYILDEYQRIQVMGIPG
BGC0000400_AGM16412.1_3015_mod3_thr      PHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKVYVLDANRQCVPVGVAG
AGM16412.1_3015_mod3_thr                 PHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKVYVLDANRQCVPVGVAG
Q6YK39_A2_thr                            PLTQLINMYGITETTVHVTYKEITEREIDEGRSNIGQPIPTLQAYILDEYQHIQVMGIPG
                                         * **********************: **::.:****:*****:.*:**  ::   :*:.*

Q70K00_A2_thr                            ELYVAGEGLARGYLNRPELTGEKFVEHPFAAGEKMYKTGDVARWLPDGNIEYLGRIDHQV
BGC0000400_AGM16412.1_3015_mod3_thr      EMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARWLPDGNIEYLGRIDHQV
AGM16412.1_3015_mod3_thr                 EMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARWLPDGNIEYLGRIDHQV
Q6YK39_A2_thr                            ELYVAGEGLARGYLNRPELTAEKFVEHPFAAGEKMYKTGDVARWLPDGNIEYLGRIDHQV
                                         *:****:*******:*****.:***: ** :* :**:***:*******************

Q70K00_A2_thr                            KIRGYRIEIGEVEAALLQLESVKEAVVIAIEE-EGSKQLCA
BGC0000400_AGM16412.1_3015_mod3_thr      KIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCA
AGM16412.1_3015_mod3_thr                 KIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCA
Q6YK39_A2_thr                            KIRGYRIEIGEVEAALLQSESVKEAVVIAIEE-EGSKQLCA
                                         ********:***** * : :.*:**:*** *: .*.*****
