CLUSTAL W multiple sequence alignment


Q9K5M1_A3_5__thr                         LIQQHLVEKLQQHQAHIVCLDSDGEKIAQNSNSNPLNIATPSNLAYVIYTSGSTGKPKGV
BGC0001125_AIW82285.1_488_mod1_thr       LTQSQWLNSLTEVSAQTVCLDTDWEAISAFSQENPVNQATPNNLAYVIYTSGSTGKPKGV
Q847C7_A1_6__thr                         LTQKSLLPSLPENQAIVMCLDRDWGVIAACSQENIVSHAQPQNLAYVIYTSGSTGKPKGV
BAH22763.1_488_mod1_thr                  LTQQKLGETLPQHQAQIIYLDTDWEKIAENSHSNPENTVTPDNLAYVIYTSGSTGKPKGV
                                         * *.    .* : .*  : ** *   *:  *:.*  . . *.******************

Q9K5M1_A3_5__thr                         LVNHSHVVRLFAATDSWYNFNSQDVWTMFHSYAFDFSVWEVWGALLYGGRLVVVGYLVTR
BGC0001125_AIW82285.1_488_mod1_thr       LVNHANVTRLFTATQSWFNFNESDVWTLFHSYAFDFSVWELWGALLYGGRLVIVPFWISR
Q847C7_A1_6__thr                         LINHQNVIRLFAATQAWYHFGASDVFTLFHSIAFDFSVWELWGALLYGGSLVIVPYWVSR
BAH22763.1_488_mod1_thr                  LVNHSNVVRLFAATDAWYNFSSQDVWSLFHSYAFDFSVWEMWGALLYGGRLVVVPYLITR
                                         *:** :* ***:**::*::*. .**:::*** ********:******** **:* : ::*

Q9K5M1_A3_5__thr                         SPKSFYELLCQEKVTILNQTPSAFRQLIPAEQSI-------------ATVGDLNLRLVIF
BGC0001125_AIW82285.1_488_mod1_thr       DPQAFYQLLCQEKVTVLNQTPSAFRQLIWVEEQAE------------VTVAKLYLRWVIF
Q847C7_A1_6__thr                         DPSAFHTLLRQEQVTVLNQTPSAFRQLIRVEELAK------------TGESQLSLRLVIF
BAH22763.1_488_mod1_thr                  SPEAFYQLLCQEKVTILNQTPTAFRQLIQAEKSLKGSFPLSRGDRSSTTDNDLSLRLVIF
                                         .*.:*: ** **:**:*****:****** .*:               .   .* ** ***

Q9K5M1_A3_5__thr                         GGETLELNSLQPWFDRHGDQSPQLVNMYGITETTVHVTYRPLSKADLHGKASVIGRPIGD
BGC0001125_AIW82285.1_488_mod1_thr       GGESLDPSSLMPWFERHGDGTPQLVNMYGITETTVHVTFRPLTIEDAHSRGSVIGLPIPD
Q847C7_A1_6__thr                         GGEALEPQSLQPWFEGYKDQSPQLVNMYGITETTVHVTYRPLSIADVNNSKSLIGVPIPD
BAH22763.1_488_mod1_thr                  GGEALEINSLQPWFQRHGDQCPQLVNMYGITETTVHVTYRPLSMTDLDSTASVIGRPIPD
                                         ***:*: .** ***: : *  *****************:***:  * ..  *:** ** *

Q9K5M1_A3_5__thr                         LQVYVLDEHLQPVPIGVAGEMYVGGAGVTRGYLNRAELTAQRFISNPFN-----------
BGC0001125_AIW82285.1_488_mod1_thr       LQLYILDESLQPVPIGVRGQMFVGGAGVARGYLNRPELTADRFIQNPFS-----------
Q847C7_A1_6__thr                         LQLYILDEQLKPLPIGIKGEMYIGGAGLARGYLNRPELTAERFIPNPFS-----------
BAH22763.1_488_mod1_thr                  LQVYLLDQYLQLVPVGVPGEMYVGGAGVTKGYLNRPELTTERFISSPFEKDEVIPPTPLN
                                         **:*:**: *: :*:*: *:*::****:::*****.***::*** .**.           

Q9K5M1_A3_5__thr                         --GNSEQLLYKSGDLARYLPNGELEYLGRIDNQVKIRGFRIELGEIEAALSQLREVREVV
BGC0001125_AIW82285.1_488_mod1_thr       --EQLGDKLYKTGDLARYRSDGNIEYLGRIDYQVKIRGFRIELGEIEAALSQHPVVKEAV
Q847C7_A1_6__thr                         --DAPEARLYKTGDLARYLENGDIEYLDRIDNQVKIRGFRIELGEIEAALLKYPEVQEAV
BAH22763.1_488_mod1_thr                  KGGNEPSKLYKTGDLARYLPKGELEYLGRIDNQVKIRGFRIELGEIEALLASHPQIWETV
                                                 ***:******  .*::***.*** **************** * .   : *.*

Q9K5M1_A3_5__thr                         VVARSDQPDNKRLVA
BGC0001125_AIW82285.1_488_mod1_thr       VIDREGKAGDKRLVA
Q847C7_A1_6__thr                         VMARTDQPGDKRLVA
BAH22763.1_488_mod1_thr                  VIVRDDATGDKRLVA
                                         *: * . ..:*****
