CLUSTAL W multiple sequence alignment


BGC0000400_AGM16412.1_3015_mod3_thr      LLPHDLRDKVGFDGTVVMLDDEQSYVEDSSNPA-------TASKPSDLAYVIYTSGTTGK
P39846_A2_thr                            LTERGLNKPADYTGHILYIDE----CENNSIPADVNIEEIVTDQP---AYVIYTSGTTGQ
AGM16412.1_3015_mod3_thr                 LLPHDLRDKVGFDGTVVMLDDEQSYVEDSSNPA-------TASKPSDLAYVIYTSGTTGK
O87704_A2_4__thr                         LTEHGHNKPADYHGQILYLND----AENELISPDLKAQETLADQP---AYVIYTSGTTGQ
                                         *  :. .. ..: * :: :::     *:.  ..        :.:*   ***********:

BGC0000400_AGM16412.1_3015_mod3_thr      PKGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGRLVVVPQ
P39846_A2_thr                            PKGVIVEHRNVISLLKHQNLPFEFNHEDVWTLFHSYCFDFSVWEMFGALLNGSTLVVVSK
AGM16412.1_3015_mod3_thr                 PKGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGRLVVVPQ
O87704_A2_4__thr                         PKGVVVEHRNVISLLKHQDLPFDFGSEDVWTLFHSYCFDFSVWEMFGALLNGSTLVVVSR
                                         ***.::**:**: ** :..  *:*.  *.******:*********:**** *. ****.:

BGC0000400_AGM16412.1_3015_mod3_thr      LTAKNPAQFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEALNPQLL
P39846_A2_thr                            ETARDPQAFRLLLKKERVTVLNQTPTAFYGLMLED-QNHTDHLNIRYVIFGGEALQPGLL
AGM16412.1_3015_mod3_thr                 LTAKNPAQFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEALNPQLL
O87704_A2_4__thr                         ETARDPNAFRLLLKNEGVTVLNQTPTAFYGLIHEE-ENHTDRLHVRYVIFGGEALQPGML
                                          **::*  *  **::: **:****** ** *: *   :  :.*::* ********:* :*

BGC0000400_AGM16412.1_3015_mod3_thr      KDWKTKYPHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKVYVLDANRQC
P39846_A2_thr                            QSWNEKYPHTDLINMYGITETTVHVTFKKLSAADIAKNKSNIGRPLSTLQAHVMDAHMNL
AGM16412.1_3015_mod3_thr                 KDWKTKYPHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKVYVLDANRQC
O87704_A2_4__thr                         VTWNEKYPDTDLINMYGITETTVHVTYKKLSSADIEKNKSNIGKPLATLQAYVMDAHMNL
                                           *: ***.*:***************:*::: .:* : *****:*:.**:.:*:**: : 

BGC0000400_AGM16412.1_3015_mod3_thr      VPVGVAGEMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARWLPDGNIEYL
P39846_A2_thr                            QPTGVPGELYIGGEGVARGYLNRDELTADRFVSNPYLPGDRLYRTGDLAKRLSNGELEYL
AGM16412.1_3015_mod3_thr                 VPVGVAGEMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARWLPDGNIEYL
O87704_A2_4__thr                         QPTGVPGELYIGGEGVARGYLNRDDLTAARFVPNPYLPGDRLYRTGDLAKRLASGDLEYM
                                          *.**.**:*:.*:*:*****:* :*** :** .*: .*.*:*******: *..*::**:

BGC0000400_AGM16412.1_3015_mod3_thr      GRIDHQVKIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCA
P39846_A2_thr                            GRIDEQVKVRGHRIELGEIQAALLQYPMIKEAAVITRADEQGQTAIYA
AGM16412.1_3015_mod3_thr                 GRIDHQVKIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCA
O87704_A2_4__thr                         GRIDDQVKVRGHRIELGEIQASLLQLPIIKEAAVITRDDEQGQSAVYA
                                         ****.***:**:******::* * :   ::** **:* * :*:. : *
