CLUSTAL W multiple sequence alignment


Q847C7_A1_6__thr                         LTQKSLLPSLPENQAIVMCLDRDWGVIAACSQEN-IVSHAQPQNLAYVIYTSGSTGKPKG
AHZ20774.1_477_mod1_thr                  LTTTNITEKLPD-STIKICLDAENAPYLNVSTEALIIDNIEPDSGAYIIYTSGSTGKPKG
BGC0001125_AIW82285.1_488_mod1_thr       LTQSQWLNSLTEVSAQTVCLDTDWEAISAFSQEN-PVNQATPNNLAYVIYTSGSTGKPKG
BGC0000369_AHZ20774.1_477_mod1_thr       LTTTNITEKLPD-STIKICLDAENAPYLNVSTEALIIDNIEPDSGAYIIYTSGSTGKPKG
                                         ** ..   .*.: .:  :*** :       * *   :.:  *:. **:************

Q847C7_A1_6__thr                         VLINHQNVIRLFAATQAWYHFGASDVFTLFHSIAFDFSVWELWGALLYGGSLVIVPYWVS
AHZ20774.1_477_mod1_thr                  VLVTQHNLTRLFKSTEHWFKFNEQDVWTFFHSFAFDFSVWEIWGALFYGGKLVIVPHCVS
BGC0001125_AIW82285.1_488_mod1_thr       VLVNHANVTRLFTATQSWFNFNESDVWTLFHSYAFDFSVWELWGALLYGGRLVIVPFWIS
BGC0000369_AHZ20774.1_477_mod1_thr       VLVTQHNLTRLFKSTEHWFKFNEQDVWTFFHSFAFDFSVWEIWGALFYGGKLVIVPHCVS
                                         **:.: *: *** :*: *::*. .**:*:*** ********:****:*** *****. :*

Q847C7_A1_6__thr                         RDPSAFHTLLRQEQVTVLNQTPSAFRQLIRVEELAKTGESQLSLRLVIFGGEALEPQSLQ
AHZ20774.1_477_mod1_thr                  RDPQRFLQLLQNEQVTVLNQTPSAFAQLLACKD---VTVNLSSLRYIIFGGEALNLASLR
BGC0001125_AIW82285.1_488_mod1_thr       RDPQAFYQLLCQEKVTVLNQTPSAFRQLIWVEEQAEVTVAKLYLRWVIFGGESLDPSSLM
BGC0000369_AHZ20774.1_477_mod1_thr       RDPQRFLQLLQNEQVTVLNQTPSAFAQLLACKD---VTVNLSSLRYIIFGGEALNLASLR
                                         ***. *  ** :*:*********** **:  ::   .      ** :*****:*:  ** 

Q847C7_A1_6__thr                         PWFEGYKDQSPQLVNMYGITETTVHVTYRPLSIADV-NNSKSLIGVPIPDLQLYILDEQL
AHZ20774.1_477_mod1_thr                  PWFEHYGENQTRLVNMYGITETTVHVTYRPISKQDVDNSSGSLIGQPIPDLHLYILDSDG
BGC0001125_AIW82285.1_488_mod1_thr       PWFERHGDGTPQLVNMYGITETTVHVTFRPLTIEDA-HSRGSVIGLPIPDLQLYILDESL
BGC0000369_AHZ20774.1_477_mod1_thr       PWFEHYGENQTRLVNMYGITETTVHVTYRPISKQDVDNSSGSLIGQPIPDLHLYILDSDG
                                         **** : :  .:***************:**::  *. :.  *:** *****:*****.. 

Q847C7_A1_6__thr                         KPLPIGIKGEMYIGGAGLARGYLNRPELTAERFIPNPFSDAPEARLYKTGDLARYLENGD
AHZ20774.1_477_mod1_thr                  NRLPTGVIGEMYVGGAGVARGYLNRPELTAERFVKDHFSSS--SCLYRTGDLGRFLPNGD
BGC0001125_AIW82285.1_488_mod1_thr       QPVPIGVRGQMFVGGAGVARGYLNRPELTADRFIQNPFSEQLGDKLYKTGDLARYRSDGN
BGC0000369_AHZ20774.1_477_mod1_thr       NRLPTGVIGEMYVGGAGVARGYLNRPELTAERFVKDHFSSS--SCLYRTGDLGRFLPNGD
                                         : :* *: *:*::****:************:**: : **.     **:****.*:  :*:

Q847C7_A1_6__thr                         IEYLDRIDNQVKIRGFRIELGEIEAALLKYPEVQEAVVMARTD-QPGDKRLVA
AHZ20774.1_477_mod1_thr                  LEYLGRIDNQVKIRGFRIEIGEIETAFSQFPAVQENIVVVATDAETNQKRLIA
BGC0001125_AIW82285.1_488_mod1_thr       IEYLGRIDYQVKIRGFRIELGEIEAALSQHPVVKEAVVIDREG-KAGDKRLVA
BGC0000369_AHZ20774.1_477_mod1_thr       LEYLGRIDNQVKIRGFRIEIGEIETAFSQFPAVQENIVVVATDAETNQKRLIA
                                         :***.*** **********:****:*: :.* *:* :*:   . :..:***:*
