CLUSTAL W multiple sequence alignment


BGC0000449_AHF21228.1_6670_mod5_trp      LTQSHLVNKVTFDGNVLVLDGAQGMYHEDGSNLEPLSGPNDLAYVIYTSGTTGQPKGVML
AHF21228.1_6670_mod5_trp                 LTQSHLVNKVTFDGNVLVLDGAQGMYHEDGSNLEPLSGPNDLAYVIYTSGTTGQPKGVML
                                         ************************************************************

BGC0000449_AHF21228.1_6670_mod5_trp      EHHGLCNLKTYFDQTLRISTSDHALLFASYSFDAACWEIFQALFCGATLYVPTSETILNY
AHF21228.1_6670_mod5_trp                 EHHGLCNLKTYFDQTLRISTSDHALLFASYSFDAACWEIFQALFCGATLYVPTSETILNY
                                         ************************************************************

BGC0000449_AHF21228.1_6670_mod5_trp      ERFEQYMADHQITVAALPPTYAVYLEPERMPNLRILFTAGSASSTELIYKWKDQVAYYNG
AHF21228.1_6670_mod5_trp                 ERFEQYMADHQITVAALPPTYAVYLEPERMPNLRILFTAGSASSTELIYKWKDQVAYYNG
                                         ************************************************************

BGC0000449_AHF21228.1_6670_mod5_trp      YGPTENSVATSVWSVSEDERAGQLISIGRPIPNHRVYMVDVHGHLAPVGVAGELCVSGPG
AHF21228.1_6670_mod5_trp                 YGPTENSVATSVWSVSEDERAGQLISIGRPIPNHRVYMVDVHGHLAPVGVAGELCVSGPG
                                         ************************************************************

BGC0000449_AHF21228.1_6670_mod5_trp      LARGYLDRPELTAEKFVPNPFAAGEAGYERMYRTGDLARWMPDGNIEYLGRIDHQVKIRG
AHF21228.1_6670_mod5_trp                 LARGYLDRPELTAEKFVPNPFAAGEAGYERMYRTGDLARWMPDGNIEYLGRIDHQVKIRG
                                         ************************************************************

BGC0000449_AHF21228.1_6670_mod5_trp      YRIELGEVEAQILKVEDVQEVIVLAQADEQGQNQLVA
AHF21228.1_6670_mod5_trp                 YRIELGEVEAQILKVEDVQEVIVLAQADEQGQNQLVA
                                         *************************************
