CLUSTAL W multiple sequence alignment


Q70LM5_A3_9__trp                         LTQQSLAELLPKTQARVICLDGDSLANEP---VANPASEVTEQNLAYVMYTSGSTGLPKG
BGC0001019_AHB82071.1_2004_mod2_trp      LTERQLADHLP-SRCDVVLIDEDRGPGRAA--AGRARPPATPDNLAYVIYTSGSTGRPKG
Q70LM5_A5_11__trp                        LTQASLTDRLPASSRQVICLDSDELANEP---VTNAETSVGEHNLAYVIYTSGSTGLPKG
Q70LM4_A1_13__trp                        LTQQSLLEILPVTAAHVICLDSDLLADEP---VDNASSEVTEQNLAYVIYTSGSTGLPKG
Q70LM4_A3_15__trp                        LTQAGLADKFTQAAAPVICLGEKLFADRAHVDVDNIQTDVASTNLAYVIYTSGTTGLPKG
                                         **:  * : :. :   *: :. .  ....   . .  . .   *****:****:** ***

Q70LM5_A3_9__trp                         VMVEHHSVVNLAHALIEAFRIQPSSRVLQFTSFSFDVSVSEIVMALLAGAALVIEDREVL
BGC0001019_AHB82071.1_2004_mod2_trp      VGVSHRAICSLAWDHIAQYGIDARSRILQFVSLSFDVATSDVVMALLSGATLCVCSAEER
Q70LM5_A5_11__trp                        VMIEHRSVINLAYDLIRHFQIDATSRVLQFISFSFDVSVSEIVMSLLAGATLVIEDRESL
Q70LM4_A1_13__trp                        VMIEHHSAINLAYALIDAFDIQPTSRVLQFTSFSFDVSVSEVVMALLAGATLVIEDRESL
Q70LM4_A3_15__trp                        VAVEHRSAMNMVQAYIAYFGLDESSRVLQFTSFSFDVSVSEIWQALLSGGTLVIEDRESL
                                         * :.*::  .:.   *  : ::  **:*** *:****:.*::  :**:*.:* : . *  

Q70LM5_A3_9__trp                         LPGPELISVLQQKRITTVSMVSSVLAALPAADLPDLQTLIVGGEAPSRELVARYADRRQF
BGC0001019_AHB82071.1_2004_mod2_trp      SPGAALVERLAERGITHLQIPASLLAGLPARALPELRAIIVGGEACAMDVLQRWRSGRRL
Q70LM5_A5_11__trp                        LPGPELIRVLQEQRITTFAMVSSVLAALPEADLPDLRTIIVGGEAPSRELVARYATGRQF
Q70LM4_A1_13__trp                        LPGPELIQVLQEQRITTVSMVSSVLAALPDADLPDLHTLIVGGEAPSRELVARYAPGRQF
Q70LM4_A3_15__trp                        LPGPDLVRTLRERRISKVSMASSLLASLPVAEYPDLAVLEVGGDACSRELVARYATGRKF
                                          **. *:  * :: *: . : :*:**.**    *:* .: ***:* : ::: *:   *::

Q70LM5_A3_9__trp                         FNCYGPTEATVCSTMMLCNAGMKSAPIGRPLANATLYVLDANQKPVPVGVPGELYIGGKG
BGC0001019_AHB82071.1_2004_mod2_trp      FNAYGPTETTVCATIGEIGPDDAVTHIGRPIANARVYILDPHLEPAPTGVAGEIYVGGAH
Q70LM5_A5_11__trp                        INCYGPTETTVTATLKHCQDDGKNPPIGRPIANTTVYVLDAHLQPVPIGVPGELYIGGKG
Q70LM4_A1_13__trp                        FNCYGPTEATVCSTMMLCQAGMNNPPIGRPIANATVYVLDANLNPVPVGVPGELYIGGKG
Q70LM4_A3_15__trp                        FNCYGPTEATVGTVIKQLTLDDDTPTIGRPFPNTKLYVLDQNRKPVPVGVPGELYIGGEC
                                         :*.*****:** :.:     .   . ****:.*: :*:** : :*.* **.**:*:**  

Q70LM5_A3_9__trp                         LARGYWNRPELTAERFIAHPFG-AKGERLYRTGDLVRYLPDGNLEFLGRIDTQVKIRGYR
BGC0001019_AHB82071.1_2004_mod2_trp      LARGYLGQPGLTAERFLPDPHAPEPGARMYRTGDLALHREDGRIEFLGRTDQQVKLHGNR
Q70LM5_A5_11__trp                        VARGYWNRPELTAERFIADPFG-QADERLYRTGDLVRYLENGELEFLGRIDDQVKIRGYR
Q70LM4_A1_13__trp                        LARGYWNRPELTAESFIPHPFG-TAGERLYRTGDLVRYRQDGNLEFLGRIDHQVKIRGYR
Q70LM4_A3_15__trp                        LARGYWNRPELTAERFVANPFG-QPGERLYRTGDLVRYLPDGNVDYLGRFDDQVKIRGYR
                                         :**** .:* **** *:..*..   . *:******. :  :*.:::*** * ***::* *

Q70LM5_A3_9__trp                         IELGEIESALSQHPAIQEAVVIAWEQ-----RLAA
BGC0001019_AHB82071.1_2004_mod2_trp      IELGEIEAALSGHPDVAQAVVLLREDRPGQRRLVA
Q70LM5_A5_11__trp                        IELGEIENALRQHPAVQNVVVIARQEGAGDKRLAA
Q70LM4_A1_13__trp                        IELGEIENAIRQHPAVQEAVVIAREEKAGDKRLAA
Q70LM4_A3_15__trp                        IELGEIAEALRQHAAIREAVVLAREVRPGDKRLAA
                                         ******  *:  *. : :.**:  :      **.*
