CLUSTAL W multiple sequence alignment


Q6YK40_A1_tyr                            LVQHHLKNSLAFDGPVIDLNDETSYHADCSLLSPVAGHSHLAYVIYTSGTTGKPKGVMVE
Q93I55_A1_tyr                            LVQHHLKNSLAFDGPVIDLNDETSYHADCSLLSPVAGHSHLAYVIYTSGTTGKPKGVMVE
Q9R9J0_A1_tyr                            VVQRHFKNSLVFDGPMIDLNDETSYHADCSLLSPIAEHSHLAYVIYTSGTTGKPKGVMVE
Q70JZ9_A1_tyr                            LVQHHLKNSLAFDGPVIDLNDETSYHADCSLLSPVAGHSHLAYVIYTSGTTGKPKGVMVE
                                         :**:*:****.****:******************:* ***********************

Q6YK40_A1_tyr                            HSGIVNSLQWKKAFFKHSPADRVLVLYPYVFDAFILNFFGPLISGATLHLLPNEENKETF
Q93I55_A1_tyr                            HGGIVNSLQWKKAFFRHSPADRVLVLYPYVFDAFILNFFGPLISGATLHLLPNKENKETF
Q9R9J0_A1_tyr                            HGGIVNSLQWKKAFFKHSAEDRVLVLYPYVFDAFILNFFGPLISGAALYLLPNEDNKDLF
Q70JZ9_A1_tyr                            HGGIVNSLQWKKAFFKHSPADRVLVLYPYVFDAFILNFFGPLISGATLHLLPNEENKETF
                                         *.*************:**. **************************:*:****::**: *

Q6YK40_A1_tyr                            AIQNAIKQERITHFSTSPRLLKTMIEQMNREDFIHVQHVVVGGEQLETDTVEKLHSLQPR
Q93I55_A1_tyr                            AIQNAIKQERITHFSTSPRLLKTMIEQMNREDFIHVQHVVVGGEQLEADTVEKLHSLQPR
Q9R9J0_A1_tyr                            AIQNVLKLERITHFSTSPRLLQAMTEQMNAEDFYHVQHVVVGGEKLEPDTVERLFSLQPQ
Q70JZ9_A1_tyr                            AIQNAIKQERITHFSTSPRLLKTMIEQMNREDFIHVQHVVVGGEQLEADTVEKLHSLQPR
                                         ****.:* *************::* **** *** **********:**.****:*.****:

Q6YK40_A1_tyr                            IRINNEYGPTENSVVSTFHPVQSADEQITIGSPVANHQAYILGAHHQIQPIGVPGELYVG
Q93I55_A1_tyr                            IRINNEYGPTENSVVSTFHPVQSADEQITIGSPVANHQAYILGAHHQIQPIGVPGELYVG
Q9R9J0_A1_tyr                            IRINNEYGPTENSVVSTFQPVYSADEQITIGKPVANHQAYILGAHRQIQPIGVPGELYVG
Q70JZ9_A1_tyr                            IRINNEYGPTENSVVSTFHPVQSADEQITIGSPVANHQAYILGAHHQIQPIGVPGELYVG
                                         ******************:** *********.*************:**************

Q6YK40_A1_tyr                            GAGVARGYLNRPELTEEKFVEHLHVPGQKMYKTGDLARWLPDGRIEYLGRIDHQVKIRGY
Q93I55_A1_tyr                            GAGVARGYLNRPELTEEKFVEHLHVPGQKMYKTGDLARWLPDGRIEYLGRIDHQVKIRGY
Q9R9J0_A1_tyr                            GSGVARGYLNQPDLTEEKFVDHLLIPRRKMYKTGDLARWLPDGRIEYLGRIDHQVKIRGY
Q70JZ9_A1_tyr                            GAGVARGYLNRPELTEEKFVEHLHVPGQKMYKTGDLARWLPDGRIEYLGRIDHQVKIRGY
                                         *:********:*:*******:** :* :********************************

Q6YK40_A1_tyr                            RIEIGEVEAAMFNLENVREAAVVAREDADGAKQLYA
Q93I55_A1_tyr                            RIEIGEVEAAMFNLENVREAAVVAREDADGAKQLYA
Q9R9J0_A1_tyr                            RIELGEVEAALSNLEEVRETTVESREGIDGTKQLYA
Q70JZ9_A1_tyr                            RIEIGEVEAAMFNLENVREAAVVAREDADGAKQLYA
                                         ***:******: ***:***::* :**. **:*****
