CLUSTAL W multiple sequence alignment


Q70AZ9_A2_tyr                            VCAGKTREAVPAAFADRLLVVDEMDLTGGSAARLPR--VRPGDAAYVIYTSGSTGRPKGV
Q93N87_A3_tyr                            LCTARTRAAVPADYPGRNVVLDELDDSALPAEPFTATPVPPDQAAYVIYTSGSTGAPKGV
Q8KLL3_A2_tyr                            VCDGKARDAVPEEFADRSLVIDEVDLSAVPDAELPR--VGPDDVAYVIYTSGSTGTPKGV
Q93N87_A3_6__tyr                         LCTARTRAAVPADYPGRNVVLDELDDSALPAEPFTATPVPPDQAAYVIYTSGSTGAPKGV
BGC0001178_AGS77307.1_1045_mod2_tyr      ICVGKTREAVPAEFADRLIVVDEVEPAAGPDGKLPR--VGPDDAAYVIYTSGSTGTPKGV
                                         :* .::* ***  :..* :*:**:: :. .   :.   * *.:.*********** ****

Q70AZ9_A2_tyr                            VVPHAGLGNLALAQIDRFGVSPSSRVLQFAALGFDAMVSEVLMALLSGARLVMAPEHQLP
Q93N87_A3_tyr                            VVPHAGLGNLAAAQIDRFAVGPDARVLQLASLGFDAAVSELLMALLSGAAAIVAPAETLP
Q8KLL3_A2_tyr                            VVTHAGLGNLAAAQIDRFAVSPSSRVLQFAALGFDATVSEALMALLSGATLVMAPKQDLP
Q93N87_A3_6__tyr                         VVPHAGLGNLAAAQIDRFAVGPDARVLQLASLGFDAAVSELLMALLSGAAAIVAPAETLP
BGC0001178_AGS77307.1_1045_mod2_tyr      VVTHAGLGNLAAAQIDRFGVSPSSRVLQFAALGFDAVVSETLMALLSGARLVLAPPQDMP
                                         **.******** ******.*.*.:****:*:***** *** ********  ::** . :*

Q70AZ9_A2_tyr                            PRVSLAEALQRWDVTHVTVPPSVLATAEALPARLETVVVAGEACPPSLADRWSAGLRLVN
Q93N87_A3_tyr                            PLVSLTEALRHWDVTHVTVPPSALATADELPDGLRTLVVAGEACPPALADRWAGGRRMIN
Q8KLL3_A2_tyr                            PRVSLAEALERWDVTHVTVPPSVLATADVLPESLETVVVAGEACPPGLADRWSEGRRLIN
Q93N87_A3_6__tyr                         PLVSLTEALRHWDVTHVTVPPSALATADELPDGLRTLVVAGEACPPALADRWAGGRRMIN
BGC0001178_AGS77307.1_1045_mod2_tyr      PRVSLAEALERWDVTHVTVPPSVLATADALPAKLETVVVAGEACPPSLVDRWSAGRRLVN
                                         * ***:***.:***********.****: **  *.*:*********.*.***: * *::*

Q70AZ9_A2_tyr                            AYGPTEATVCAAMSMPLVASRPVVPIGTPIAGGRCYVLDAFLRPLPPGLTGELYVAGIGL
Q93N87_A3_tyr                            AYGPTETTVCASMSPPLAPGADVVPVGRPIANGRTYVLDPFLRPVPPGVTGELYVAGAGL
Q8KLL3_A2_tyr                            AYGPTEATVCAAMSMPLTAGRDVVPIGEPIAGSRCHVLDAFLRPLPPGVTGELYVSGIGL
Q93N87_A3_6__tyr                         AYGPTETTVCASMSPPLAPGADVVPVGRPIANGRTYVLDPFLRPVPPGVTGELYVAGAGL
BGC0001178_AGS77307.1_1045_mod2_tyr      AYGPTEATVCAAMSMPLAASRDVVPIGTPIAGGRCYVLDAFLRPLPPGIIGELYVAGIGL
                                         ******:****:** **...  ***:* ***..* :***.****:***: *****:* **

Q70AZ9_A2_tyr                            ARGYLGRAALTAERFVADPFVPGERMYRTGDLAYRTGEGELVFAGRADDQVKVRGFRIEP
Q93N87_A3_tyr                            ARGYLGQGGLTATRFVPDPFTPGERMYRTGDLARWTHDGLLVFAGRADAQVKVRGHRIEP
Q8KLL3_A2_tyr                            ARGYLGRAALTAERFVADPFVPGERMYRTGDLAHLTSSGELVFAGRADDQVKLRGFRIEP
Q93N87_A3_6__tyr                         ARGYLGQGGLTATRFVPDPFTPGERMYRTGDLARWTHDGLLVFAGRADAQVKVRGHRIEP
BGC0001178_AGS77307.1_1045_mod2_tyr      ARGYLGRAALTAERFVADPFVPVERMYRTGDLAYWTDRSELVFAGRADDQMKIRGFRVEP
                                         ******:..*** ***.***.* **********  *  . ******** *:*:**.*:**

Q70AZ9_A2_tyr                            GEVESALSGHPGVAQAAVIVRGD-----RLLA
Q93N87_A3_tyr                            GEVEAVLAEHPGVAQAAVVAREDTPGERRLIG
Q8KLL3_A2_tyr                            GEIESVLSGHPQVAQAAVTVRDD-----RLLA
Q93N87_A3_6__tyr                         GEVEAVLAEHPGVAQAAVVAREDTPGERRLIG
BGC0001178_AGS77307.1_1045_mod2_tyr      GEIESALSGHPGVAQAAVTVRED-----RLLA
                                         **:*:.*: ** ****** .* *     **:.
