CLUSTAL W multiple sequence alignment


O30980_A3_tyr                            PAADQEALE----DFEGEIFAIENAETYDGSPLPQVSRPQHLAYIIYTSGTTGQPKGVMV
O30980_A3_9__tyr                         PAADQEALE----DFEGEIFAIENAETYDGSPLPQVSRPQHLAYIIYTSGTTGQPKGVMV
O87704_A1_3__tyr                         --TEEELISSIPSGYEGSIVTSGHTTHY-RTDSPDAS-IGELAYLIYTSGTTGRPKGVLV
P94459_A3_tyr                            NEADLGVLA----DFEGEILTIESVEEDDKSPLPQMSSAHHLAYIIYTSGTTGRPKGVMV
P39846_A1_tyr                            --IEEDLISLIPPSYEGNTITIEHTESY-QTEAPNMP-PGDLAYLIYTSGTTGRPKGVLV
                                            :   :     .:**. .:   .     :  *: .   .***:********:****:*

O30980_A3_tyr                            EHKGIANTLQWRRNAYTLNETDTVLQLFSFSFDGFLTSMFTPLLSGAKTVLPDENEAKDI
O30980_A3_9__tyr                         EHKGIANTLQWRRNAYTLNETDTVLQLFSFSFDGFLTSMFTPLLSGAKTVLPDENEAKDI
O87704_A1_3__tyr                         DHQGIANTLQWRREEYGMSEGDTALHLFSYVFDGCVTSLFTPLLSGACVLLTTDNEAKDV
P94459_A3_tyr                            EHKGIANTLQWRRNAYAFNETDTILQLFSFSFDGFITSMFTPLLSGAKAVLLHEEEAKDI
P39846_A1_tyr                            DHHGIANTLQWRREEYSMTEQDISLHLFSYVFDGCVTSLFTPLLSGACVLLTTDDEAKDV
                                         :*:**********: * :.* *  *:***: *** :**:******** .:*  ::****:

O30980_A3_tyr                            LSIKHDLSHHRITHMIIVPVLYRALLDVIQPEDAKTLRVVTLAGEAADRELIDRSMAICP
O30980_A3_9__tyr                         LSIKHDLSHHRITHMIIVPVLYRALLDVIQPEDAKTLRVVTLAGEAADRELIDRSMAICP
O87704_A1_3__tyr                         LALRRKIAQYKVSHMLIVPSLYRVLLEVLTAEDAKSLRIVTFAGEAVTPDLLETSRKICP
P94459_A3_tyr                            LAIKHQLSRQRITHMIIVPVLYRALLDVVQPEDVKTLRVVTLAGEAADRELIARSLAICP
P39846_A1_tyr                            LALKRKIARYKVSHMIIVPSLYRVLLEVMTADDAKSLRIVTFAGEAVTPDLLELNQIICP
                                         *::::.::: :::**:*** ***.**:*: .:*.*:**:**:****.  :*:  .  ***

O30980_A3_tyr                            NTELANEYGPTENSVATTAMRHMERQKNVCIGRPIDNTEVLILNGD-QLQPIGVAGELCI
O30980_A3_9__tyr                         NTELANEYGPTENSVATTAMRHMERQKNVCIGRPIDNTEVLILNGD-QLQPIGVAGELCI
O87704_A1_3__tyr                         SAELANEYGPTENSVATTILRHLNEEERITIGHPIANTKVYILQGE-QLQPIGAAGELCI
P94459_A3_tyr                            HTELANEYGPTENSVATTVMRHMEKQAYVSIGQPIDGTQVLILNSNHQLQPIGVAGELCI
P39846_A1_tyr                            SAELANEYGPTENSVATTILRHLNKKERITIGHPIRNTKVFVLHGN-QMQPIGAAGELCI
                                          :**************** :**::.:  : **:** .*:* :*:.: *:****.******

O30980_A3_tyr                            AGTGLARGYVNLPELTAKTFVQHPYQPEKRMYRTGDAARWMADGTIEYLGRMDDQVKIRG
O30980_A3_9__tyr                         AGTGLARGYVNLPELTAKTFVQHPYQPEKRMYRTGDAARWMADGTIEYLGRMDDQVKIRG
O87704_A1_3__tyr                         SGAGLARGYYKRTELTEKAFTDHPFLKGERLYRTGDAGRFLPDGTIEYIGRFDDQVKIRG
P94459_A3_tyr                            AGTGLARGYVNLPELTERAFTQNPFKPEARMYRTGDAARWMADGTLEYLGRIDDQVKIRG
P39846_A1_tyr                            SGAGLARGYYKQQELTQKAFSDHPFLEGERLYRTGDAGRFLPDGTIEYIGRFDDQVKIRG
                                         :*:****** :  *** ::* ::*:    *:******.*::.***:**:**:********

O30980_A3_tyr                            HRVETKEIESVIRRISGVKEAVVLARETAPAQTELCA
O30980_A3_9__tyr                         HRVETKEIESVIRRISGVKEAVVLARETAPAQTELCA
O87704_A1_3__tyr                         YRIELSEIETVLRQASGVKEAAVLARDVSDEEKELVA
P94459_A3_tyr                            YRVETKEIESVIRCIKGVKDAAVVAHVTASGQTELSA
P39846_A1_tyr                            YRIELREIETVLRQAPGVKEAAVLARDVSAEEKELVA
                                         :*:*  ***:*:*   ***:*.*:*: .:  :.** *
