CLUSTAL W multiple sequence alignment


Q9C1G0v1_A3_val                          ITTSKHETGMMCI---PGINLISI---DDPEVQKEL--QKQSLENFTSRSSAPSNPAYII
Q9C1G0v2_A3_val                          ITTSKHETGMMCI---PGINLISI---DDPEVQKEL--QKQSLENFTSRSSAPSNPAYII
P26046_A3_val                            LVHSSHASKCER----HGAKVIAV---DSPAIETAV--SQQSAADLPTIASL-GNLAYII
P25464_A3_val                            ITTRKHTPRGGTV---ANVPSVVL---DSPETLACL--NQQSKENPTTSTQKPSDLAYVI
P27742_A3_val                            ITESRYASAWGS----QTSTILAI---DSPKVSNMV--NNQATHNLPNIAGI-KNLAYII
P27743_A3_val                            LAGEAHGSRVRGL---TSGDVLDL---------EQLDLTGEPAENPVTETTS-TELAYAI
P19787_A3_val                            LVHSSHASKCER----HGAKVIAV---DSPAIETAV--SQQSAADLPTIASL-GNLAYII
P94873_A3_val                            IADEASYPRISALAGHAARPVLNVHAHASASASELL-----PA--PASAAGG-DDFAYAI
                                         :.     .             : :           :     .     . :    : ** *

Q9C1G0v1_A3_val                          FTSGTTGKPKGVLVEHSSVAKLRDSLVGRYFG-DTNGSHAVLFLSNYVFDFSLEQLCLSI
Q9C1G0v2_A3_val                          FTSGTTGKPKGVLVEHSSVAKLRDSLVGRYFG-DTNGSHAVLFLSNYVFDFSLEQLCLSI
P26046_A3_val                            FTSGTSGKPKGVLVEQKAVLLLRDALRERYFGRDCTKHHGVLFLSNYVFDFSVEQLVLSV
P25464_A3_val                            FTSGTTGKPKGVLVEHQSVVQLRNSLIERYFG-ETNGSHAVLFLSNYVFDFSLEQLCLSV
P27742_A3_val                            FTSGTSGKPKGVLVEQGGVLHLRDALRKRYFGIECNEYHAVLFLSNYVFDFSIEQLVLSI
P27743_A3_val                            YTSGTTGKPKAVLVSHGSVDSFRAQLSGRYFGSPDESAEAVLFLANYVFDFSVEQLALSV
P19787_A3_val                            FTSGTSGKPKGVLVEQKAVLLLRDALRERYFGRDCTKHHGVLFLSNYVFDFSVEQLVLSV
P94873_A3_val                            YTSGTTGRPKAVLVRHRNVLSFSAGLAQRYFGDAGAARQAILFLSSYVFDFSVEQLALSI
                                         :****:*:**.*** :  *  :   *  ****      ..:***:.******:*** **:

Q9C1G0v1_A3_val                          FSGNKLVIPPEEGLTHEFFYAVAEAEKLSYISGTPSTLQQIQLSRLNHLQMVTAAGEEFH
Q9C1G0v2_A3_val                          FSGNKLVIPPEEGLTHEFFYAVAEAEKLSYISGTPSTLQQIQLSRLNHLQMVTAAGEEFH
P26046_A3_val                            LSGHKLIVPPAEFVADDEFYRMASTHGLSYLSGTPSLLQKIDLARLDHLQVVTAAGEELH
P25464_A3_val                            LGGNKLIIPPEEGLTHEAFYDIGRREKLSYLSGTPSVLQQIELSRLPHLHMVTAAGEEFH
P27742_A3_val                            MSGHKLIIPEGEFVADDEFYITANGQRLSYLSGTPSLLQQIDLARLNHLQVVTAAGEQLH
P27743_A3_val                            LGGHKLLVPPPSAADDPAFYELANREGLSYLSGTPTQVERFDLARLSHLRCVLVAGEAFQ
P19787_A3_val                            LSGHKLIVPPAEFVADDEFYRMASTHGLSYLSGTPSLLQKIDLARLDHLQVVTAAGEELH
P94873_A3_val                            LSGNALLIPESSLLFDDAFYQRMNQERLSYISGTPTQLQLFDLARLDHLHAVLVAGEAFR
                                         :.*: *::*  .   .  **     . ***:****: :: ::*:** **: * .*** ::

Q9C1G0v1_A3_val                          SSHYDSMRGQFKGPINNAYGITETSVYNIVTTFDADMPFTKALCEELPGTLAYVLNDNLQ
Q9C1G0v2_A3_val                          SSHYDSMRGQFKGPINNAYGITETSVYNIVTTFDADMPFTKALCEELPGTLAYVLNDNLQ
P26046_A3_val                            ATQYEKMRRRFNGPIYNAYGVTETTVYNIIAEFTTNSIFENALREVLPGTRAYVLNAALQ
P25464_A3_val                            ASQFEKMRSQFAGQINNAYGITETTVYNIITTFKGDAPFTKALCHGIPGSHVYVLNDRLQ
P27742_A3_val                            AAQFNKLRSGFRGPIYNAYGITETTVYNIVSEFSAQSQFENALRELLPGTRAYLLNHATQ
P27743_A3_val                            PQHFEKMRGEFAGPILNAYGTTETTVYNTVHRFEPGDAYRNTLGAPLGNTRLYVLGDGMK
P19787_A3_val                            ATQYEKMRRRFNGPIYNAYGVTETTVYNIIAEFTTNSIFENALREVLPGTRAYVLNAALQ
P94873_A3_val                            AHHFDKIRAEYRGPLYNAYGTTETTVYNLVKRFAPDAPYRNDLGHAIANTELHILDGELR
                                         . :::.:*  : * : **** ***:*** :  *     : : *   : .:  ::*.   :

Q9C1G0v1_A3_val                          RVPPNAVGELYIGGECLSLGYLNQKALTEERFIPNPF-----TCDAE-QRLYKTGDMVRS
Q9C1G0v2_A3_val                          RVPPNAVGELYIGGECLSLGYLNQKALTEERFIPNPF-----TCDAE-QRLYKTGDMVRS
P26046_A3_val                            PVPFDAVGELYLAGDSVTRGYLNQPLLTDQRFIPNPFCKEEDIAMGRFARLYKTGDLVRS
P25464_A3_val                            RVPFNAVGELYLGGDCLARGYLNQDALTNERFIPNPFYEPKQASDSRPQRLYKTGDLVRF
P27742_A3_val                            PVPMNAVGELYLAGDCVARGYLNQPVLTGDRFIQNPFQTEQDIACGSYPRLYRTGDLFRC
P27743_A3_val                            LLPTGAVGELYLAGDCVTEGYLHRPELTRERFLPNPFAAES----GRFPMIYRTGDVVRR
P19787_A3_val                            PVPFDAVGELYLAGDSVTRGYLNQPLLTDQRFIPNPFCKEEDIAMGRFARLYKTGDLVRS
P94873_A3_val                            ELPPGGLGEIYMAGDCVGAGYLNRDELSRERFVANPFRSEDDRRLGRNDTLYKTGDLVRR
                                          :* ..:**:*:.*:.:  ***::  *: :**: ***        .    :*:***:.* 

Q9C1G0v1_A3_val                          LGSRG----IEFIGRRDQQVKLRGFRIELSEIRDAVLSSSGVKEAVVFPRYDETKSSAGN
Q9C1G0v2_A3_val                          LGSRG----IEFIGRRDQQVKLRGFRIELSEIRDAVLSSSGVKEAVVFPRYDETKSSAGN
P26046_A3_val                            RFNRQQQPQLEYLGRGDLQIKMRGYRIEISEVQNVLTSSPGVREGAVVAKYENNDTYSRT
P25464_A3_val                            RGPHH----LEYLGRKDQQVKLRGFRIELSEVRDAVLAISAVKEAAVIPKYDEDGSDSRR
P27742_A3_val                            RLDRQHQPYLEYLGRADLQVKIRGYRIEPSEVQNVLASCPGVRECAVVAKYENTDAYSRI
P27743_A3_val                            GPDGE----LQYLGRNDAQVKINGLRIEPGEVEAALAGCSGVRQCAVVAGADPQAPERKR
P19787_A3_val                            RFNRQQQPQLEYLGRGDLQIKMRGYRIEISEVQNVLTSSPGVREGAVVAKYENNDTYSRT
P94873_A3_val                            RHSGE----LEFFGRNDHQVKINGVRIELGEIEAVAAAFPGVAQCAVVARHDGERSGGSR
                                                  ::::** * *:*:.* *** .*:. .  . ..* : .*..  :   .    

Q9C1G0v1_A3_val                          VTALVC
Q9C1G0v2_A3_val                          VTALVC
P26046_A3_val                            AHSLVG
P25464_A3_val                            VSAIVC
P27742_A3_val                            AKFLVG
P27743_A3_val                            ---LVG
P19787_A3_val                            AHSLVG
P94873_A3_val                            ---LVC
                                            :* 
