CLUSTAL W multiple sequence alignment


Q83VS1_A3_val                            LTLSQMSLTTSTQRVDLDRLMLNGLDNDDLAL--AQSSESVAYIMYTSGSTGTPKGVLVP
Q9FDB3_A3_3__val                         LTLSRMSLTASTQRIDLDGLTLDGLKDTDLTL--PQSSESVAYIMYTSGSTGVPKGVLVP
Q83VS0_A1_11__val                        LTLSRHDLPDGIQRIDLDLL---ELQSDAPNPVHSASAESVAYIMYTSGSTGMPKGVLVP
Q83VS1_A3_8__val                         LTLSQMSLTTSTQRVDLDRLMLNGLDNDDLAL--AQSSESVAYIMYTSGSTGTPKGVLVP
Q83VS1_A2_val                            LTHSQVSLTTSAQRIDLDGLTLERLKGTDLAL-PPQSSESVAYIMYTSGSTGTPKGVLVP
Q83VS1_A2_7__val                         LTHSQVSLTTSAQRIDLDGLTLERLKGTDLAL-PPQSSESVAYIMYTSGSTGTPKGVLVP
Q9FDB3_A4_4__val                         LTYSTETLDPGTQRLDLDTRPASTVPADNPNP--EACADSVAYIMYTSGSTGTPKGVLVP
                                         ** *   *  . **:***      :           .::************* *******

Q83VS1_A3_val                            HRAISRLVINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHDLLSPLN
Q9FDB3_A3_3__val                         HRAISRLVINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHDLLSPLN
Q83VS0_A1_11__val                        HRAVSRLVLNNGYADFNAGDRVAFASNPAFDASTLDVWAPLLNGGCVVVVEQSVLLSLDE
Q83VS1_A3_8__val                         HRAISRLVINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHDLLSPLN
Q83VS1_A2_val                            HRAISRLAINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHDLLSPLN
Q83VS1_A2_7__val                         HRAISRLAINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHDLLSPLN
Q9FDB3_A4_4__val                         HRAISRLVIDNGYADFNGQDRVAFASNPAFDASTLDVWAPLLNGGCVIVVEQSVLLSQEA
                                         ***:***.::*******. ****************************:*: *  ***   

Q83VS1_A3_val                            FQRLLLEQSVTVLWMTAGLFHQYASGLGEAFSRLRYLIVGGDVLDPAVIARVLANNAPQH
Q9FDB3_A3_3__val                         FQRLLLEQSVSVLWMTAGLFHQYATGLGEAFSRLRYLIVGGDVLDPAVIARVLANNAPQH
Q83VS0_A1_11__val                        FRALLLSQSVSVLWMTAGLFHQYASGLMEALARLRYLIVGGDVLDPAVIARVLAEGAPQH
Q83VS1_A3_8__val                         FQRLLLEQSVTVLWMTAGLFHQYASGLGEAFSRLRYLIVGGDVLDPAVIARVLANNAPQH
Q83VS1_A2_val                            FQRLLLEQSVSVLWMTAGLFHQYASGLGEAFSRLRYLIVGGDVLDPAVIGRVLANNPPQH
Q83VS1_A2_7__val                         FQRLLLEQSVSVLWMTAGLFHQYASGLGEAFSRLRYLIVGGDVLDPAVIGRVLANNPPQH
Q9FDB3_A4_4__val                         FRALLLAQSISVLWLTAGLFHQYADGLMEVFAGLRYLIVGGDVLDPAVIARVLAQGAPQH
                                         *: *** **::***:********* ** *.:: ****************.****:..***

Q83VS1_A3_val                            LLNGYGPTEATTFSATYEIVSVDNGSIPIGKPVGNTRLYVLDSQGQPVPLGVPGELYIGG
Q9FDB3_A3_3__val                         LLNGYGPTEATTFSATYEITSVDNGSIPIGKPVGNTRLYVLDSQGQPAPLGVAGELYIGG
Q83VS0_A1_11__val                        LLNGYGPTEATTFSTTHEITSVGSGGIPIGRPIGNSQVYVLDTLRQPVAVGVAGELYIGG
Q83VS1_A3_8__val                         LLNGYGPTEATTFSATYEIVSVDNGSIPIGKPVGNTRLYVLDSQGQPVPLGVPGELYIGG
Q83VS1_A2_val                            LLNGYGPTEATTFSATYEIVSVGNGSIPIGKPVGNSRLYVLDNQGQPVPLGVPGELYIGG
Q83VS1_A2_7__val                         LLNGYGPTEATTFSATYEIVSVGNGSIPIGKPVGNSRLYVLDNQGQPVPLGVPGELYIGG
Q9FDB3_A4_4__val                         LLNGYGPTEATTFSTTYEITAADHGGIPIGRPIANSQVYVLDALRQPVAVGVPGELYIGG
                                         **************:*:**.:.. *.****:*:.*:::****   **..:**.*******

Q83VS1_A3_val                            QGVAKGYLNRDELSTTQFVVDPFSEQIDALMYRTGDLVRWRADGNLEYLGRNDDQVKIRG
Q9FDB3_A3_3__val                         QGVARGYLHRDELTLEKFLADPFDSDPQARLYRTGDLVRWRADGNLEYLGRNDDQVKIRG
Q83VS0_A1_11__val                        QGVAKGYLNRPELNATQFVANPFSDDAGALLYRTGDLGRWNADGIVEYLGRNDDQVKIRG
Q83VS1_A3_8__val                         QGVAKGYLNRDELSTTQFVVDPFSEQIDALMYRTGDLVRWRADGNLEYLGRNDDQVKIRG
Q83VS1_A2_val                            QGVARGYLHRDELTLERFVADPFDSDPQARLYRTGDLVRWRADGNLEYLGRNDEQVKIRG
Q83VS1_A2_7__val                         QGVARGYLHRDELTLERFVADPFDSDPQARLYRTGDLVRWRADGNLEYLGRNDEQVKIRG
Q9FDB3_A4_4__val                         QGVAKGYLNRDELSTTQFVADPFSGHDGALMYRTGDLGRWRADGNLEYLGRNDGQVKIRG
                                         ****:***:* **.  :*:.:**. .  * :****** **.*** :******* ******

Q83VS1_A3_val                            FRVELGEIEARLAEHADVREAVVLCRQDVPGDKRLVA
Q9FDB3_A3_3__val                         FRVELGEIEARLAEHVDVREAVVLCRQDVPGDKRLVA
Q83VS0_A1_11__val                        FRIELGEIEARLVECPGVREAVVLARQDESAHKRLVA
Q83VS1_A3_8__val                         FRVELGEIEARLAEHADVREAVVLCRQDVPGDKRLVA
Q83VS1_A2_val                            FRVELGEIEARLAEHAEVREAVVLCRQDAPGDKRLVA
Q83VS1_A2_7__val                         FRVELGEIEARLAEHAEVREAVVLCRQDAPGDKRLVA
Q9FDB3_A4_4__val                         FRIELSEIEAALATHPAVHEAVLLARQD-TGEKRLVA
                                         **:**.**** *.    *:***:*.*** ...*****
