CLUSTAL W multiple sequence alignment


O69246_A1_4__val                         -LTKDGTQISLEGYE---------VLAVNAMDAEKEDAANLEHVNKPEDLAYYIYTSGST
O33743_A4_8__val                         LVQKHLLPLVGEGLM---------PIVLEEESLRPEDCGNPAIVNGASDLAYVMYTSGST
P0C064_A2_3__val                         LTQQHLLSLVHDEFD---------CVILDEDSLYKGDSSNLAPVNQAGDLAYIMYTSGST
Q70KJ6_A1_4__val                         --------LTVQDYQEQAGALQVPVVMLDESADETVSGTDLNLPAGGNDLAYIMYTSGST
P0C063_A2_val                            LTQQHLLSLVHDEFD---------CVILDEDSLYKGDSSNLAPVNQAGDLAYIMYTSGST
Q04747_A1_4__val                         --------LIGNSYTGQAHQLQVPVLTLDIGFEESEAADNLNLPSAPSDLAYIMYTSGST
                                                 :  :             : ::          :        **** :******

O69246_A1_4__val                         GRPKGVMVEHRNIVRLVKNAGCIPLKSGVKMAQTGAVSFDASTFEVFGALLNGGTLYPVP
O33743_A4_8__val                         GKPKGVMVEHRNVTRLVMHTNYVQVRESDRMIQTGAIGFDAMTFEIFGALLHGASLYLVS
P0C064_A2_3__val                         GKPKGVMVEHRNVIRLVKNTNYVQVREDDRIIQTGAIGFDALTFEVFGSLLHGAELYPVT
Q70KJ6_A1_4__val                         GKPKGVMIEHRNIIRLVKHSNYVPVHEEDRMAQTGAVSFDAGTFEVFGALLNGASLHPVK
P0C063_A2_val                            GKPKGVMVEHRNVIRLVKNTNYVQVREDDRIIQTGAIGFDALTFEVFGSLLHGAELYPVT
Q04747_A1_4__val                         GKPKGVMIEHKSILRLVKNAGYVPVTEEDRMAQTGAVSFDAGTFEVFGALLNGAALYPVK
                                         *:*****:**:.: *** ::. : : .  :: ****:.*** ***:**:**:*. *: * 

O69246_A1_4__val                         KETLLDGKRFNMFLKETGITTMWLTSPLFNQIAQQDPGMFATLNDLIIGGDALVPGIVNR
O33743_A4_8__val                         KDVLLDAEKLGDFLRTNQITTMWLTSPLFNQLSQDNPAMFDSLRALIVGGEALSPKHINR
P0C064_A2_3__val                         KDVLLDAEKLHKFLQANQITIMWLTSPLFNQLSQGTEEMFAGLRSLIVGGDALSPKHINN
Q70KJ6_A1_4__val                         KETLLDAGQFAQFLKEQRITTMWLTSPLFNQLAQKDAGMFNTLRHLIIGGDALVPHIVSK
P0C063_A2_val                            KDVLLDAEKLHKFLQANQITIMWLTSPLFNQLSQGTEEMFAGLRSLIVGGDALSPKHINN
Q04747_A1_4__val                         KETLLDAKQFAAFLREQSITTMWLTSPLFNQLAAKDAGMFGTLRHLIIGGDALVPHIVSK
                                         *:.***. ::  **:   ** **********::     **  *. **:**:** *  :..

O69246_A1_4__val                         VKRESPELSLWNGYGPTENTTFSTCFLIDQAYERTIPIGKPIGNSTAYIVDEHGSLQPIG
O33743_A4_8__val                         VKSALPDLEIWNGYGPTENTTFSTCYLIEQHFEEQIPIGKPIANSTAYIVDGNNQPQPIG
P0C064_A2_3__val                         VKRKCPNLTMWNGYGPTENTTFSTCFLIDKEYDDNIPIGKAISNSTVYIMDRYGQLQPVG
Q70KJ6_A1_4__val                         VRKASPELSLWNGYGPTENTTFSTSFLIDQDYDGSVPIGKPIGNSTAYIMDENRNLQPIG
P0C063_A2_val                            VKRKCPNLTMWNGYGPTENTTFSTCFLIDKEYDDNIPIGKAISNSTVYIMDRYGQLQPVG
Q04747_A1_4__val                         VKQASPSLSLWNGYGPTENTTFSTSFLIDREYGGSIPIGKPIGNSTAYIMDEQQCLQPIG
                                         *:   *.* :**************.:**:: :   :****.*.***.**:*     **:*

O69246_A1_4__val                         VPGELCVGGDGVARGYLNQPELTDEKFVGDPFAEGKRMYRTGDLAKWLPDGNIEFLGRID
O33743_A4_8__val                         VPGELCVGGDGVARGYVNKPELTAEKFVPNPFAPGETMYRTGDLARWLPDGTIEYLGRID
P0C064_A2_3__val                         VPGELCVGGDGVARGYMNQPALTEEKFVPNPFAPGERMYRTGDLARWLPDGTIEYLGRID
Q70KJ6_A1_4__val                         APGELCVGGSGVARGYVNLPELTEKQFVRDPFRPDEMIYRTGDLAKWLPDGTIEFLGRID
P0C063_A2_val                            VPGELCVGGDGVARGYMNQPALTEEKFVPNPFAPGERMYRTGDLARWLPDGTIEYLGRID
Q04747_A1_4__val                         APGELCVGGIGVARGYVNLPELTEKQFLEDPFRPGERIYRTGDLARWLPDGNIEFLGRID
                                         .******** ******:* * ** ::*: :**  .: :*******:*****.**:*****

O69246_A1_4__val                         HQVKVRGFRIELGEVEAALARLEGISEAAAVIRENNAGENEICV
O33743_A4_8__val                         QQVKIRGYRIELGEIETVLSQQAQVKEAVVAVIEEANGQKALCA
P0C064_A2_3__val                         QQVKIRGYRIEPGEIETLLVKHKKVKESVIMVVEDNNGQKALCA
Q70KJ6_A1_4__val                         NQVKVRGFRIELGEIEAKISQAENVTESAAVIRKNKADENEICA
P0C063_A2_val                            QQVKIRGYRIEPGEIETLLVKHKKVKESVIMVVEDNNGQKALCA
Q04747_A1_4__val                         NQVKVRGFRIELGEIETKLNMAEHVTEAAVIIRKNKADENEICA
                                         :***:**:*** **:*: :     :.*:.  : ::  .:: :*.
