CLUSTAL W multiple sequence alignment


Q83VS1_A2_7__val                         LTHSQVSLTTSAQRIDLDGLTLERLKGTDLALPPQSSESVAYIMYTSGSTGTPKGVLVPH
AFZ61525.1_1627_mod2_val                 -AHRVLN---NLADLNLD----AQSPRN-PEL-PQSAESVAYILYTSGSTGAPKGVQVPH
Q83VS1_A2_val                            LTHSQVSLTTSAQRIDLDGLTLERLKGTDLALPPQSSESVAYIMYTSGSTGTPKGVLVPH
BGC0000425_AFH75321.1_5900_mod6_val      LSHAGLGKALQVQRLDLDQAHLGQLPDDQPAV-VVSSEAAAYIMYTSGSTGTPKGVRVPH
                                          :*  :.   .   ::**     :       :   *:*:.***:*******:**** ***

Q83VS1_A2_7__val                         RAISRLAINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHDLLSPLNF
AFZ61525.1_1627_mod2_val                 RAISRLVLNNGYAEFNARDRVAFASNPAFDASTLDVWAPLLNGGCVVVVEHGVLLSQAAF
Q83VS1_A2_val                            RAISRLAINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHDLLSPLNF
BGC0000425_AFH75321.1_5900_mod6_val      RAITRLVINNGYADFNQHDRVAFASNPAFDASTLEVWAPLLNGGAVVVIDQDTLLTQHAF
                                         ***:**.:*****:** :****************:*********.***: :  **:   *

Q83VS1_A2_7__val                         QRLLLEQSVSVLWMTAGLFHQYASGLGEAFSRLRYLIVGGDVLDPAVIGRVLANNPPQHL
AFZ61525.1_1627_mod2_val                 ASLLQEQSVSVLWMTAGLFHQYADALMPVFRQLRYLIVGGDVLDPQVIGRVLEHGKPQHL
Q83VS1_A2_val                            QRLLLEQSVSVLWMTAGLFHQYASGLGEAFSRLRYLIVGGDVLDPAVIGRVLANNPPQHL
BGC0000425_AFH75321.1_5900_mod6_val      AALLQQQDVSVVWMTAGLFHQYAEGLLEAFARLRYLIVGGDVLDPSVIARVLKGGAPRHL
                                           ** :*.***:***********..*  .* :************* **.***  . *:**

Q83VS1_A2_7__val                         LNGYGPTEATTFSATYEIVSVGNGSIPIGKPVGNSRLYVLDNQGQPVPLGVPGELYIGGQ
AFZ61525.1_1627_mod2_val                 LNGYGPTEATTFSTTFEITSVGEGGIPIGRPIANAQAYVLDPRQQPVPLGVVGELYIGGA
Q83VS1_A2_val                            LNGYGPTEATTFSATYEIVSVGNGSIPIGKPVGNSRLYVLDNQGQPVPLGVPGELYIGGQ
BGC0000425_AFH75321.1_5900_mod6_val      LNGYGPTEATTFSTTHEITRADEGSIPIGKPVGNSRAYVLDAHQQPVPVGVTGELYIGGQ
                                         *************:*.**. ..:*.****:*:.*:: **** : ****:** ******* 

Q83VS1_A2_7__val                         GVARGYLHRDELTLERFVADPFDSDPQARLYRTGDLVRWRADGNLEYLGRNDEQVKIRGF
AFZ61525.1_1627_mod2_val                 GVAKGYLNQPQLTAEKFIPNPFGE---GVLYRTGDLACWQVDGTLVYQGRNDLQVKIRGF
Q83VS1_A2_val                            GVARGYLHRDELTLERFVADPFDSDPQARLYRTGDLVRWRADGNLEYLGRNDEQVKIRGF
BGC0000425_AFH75321.1_5900_mod6_val      GVALGYLNRPELTAEKFLVDPFSDG--GLMYRTGDLVAWRADGTLQYQGRNDQQVKIRGF
                                         *** ***:: :** *:*: :**..   . :******. *:.**.* * **** *******

Q83VS1_A2_7__val                         RVELGEIEARLAEHAEVREAVVLCRQDAPGDKRLVA
AFZ61525.1_1627_mod2_val                 RIEPGEIETCLASFTGVKDAVVLAREDEPGDKRLVA
Q83VS1_A2_val                            RVELGEIEARLAEHAEVREAVVLCRQDAPGDKRLVA
BGC0000425_AFH75321.1_5900_mod6_val      RIELGEIETRLAGCPGVKDAVVLARQDEPGHKRLVA
                                         *:* ****: **  . *::****.*:* **.*****
