CLUSTAL W multiple sequence alignment


P27742_A1_aad                            TQAKVIIASNHLAERLQSEVISDR--ELSIIRLEHCLSAI-DQQPSTF-P--RANLRDPS
P27743_A1_aad                            TGLSGIVTNRRHAERLR-EVLGDEHASVHVIEVEAVVAGPHPEQAREN--------PGLA
P26046_A1_aad                            TKARAIIASNQHVERLQREVIGDR--NLCIIRLEPLLASL-AQDSSKF-P--AHNLDDLP
Q01757_A1_aad                            TGLRGIVTNRHHAGRLR-EILGAEHADVTVVEIESVL----DEQAAADTDGLLSVKPELA
P19787_A1_aad                            TKARAIIASNQHVERLQREVIGDR--NLCIIRLEPLLASL-AQDSSKF-P--AHNLDDLP
P25464_A1_aad                            TKAQVVIASQRHVDRLRAEAVGGQ--HLRIIGLESLFDNL-AQQTQHS-PETSGNLTHLP
P94873_A1_aad                            TGSRRIVTHRHYFERLR-EMLAEACPEVELIDIEDALA---DADANAD-PGADAGNPDLG
Q9C1G0v2_A1_aad                          TQVGILIASRRHVPRLQNNLIEKR--QLQILTLESVLSSL-HEQPAH----TSSNLDHLQ
Q9C1G0v1_A1_aad                          TQVGILIASRRHVPRLQNNLIEKR--QLQILTLESVLSSL-HEQPAH----TSSNLDHLQ
                                         *    ::: .:   **: : :      : :: :*  .      :.               

P27742_A1_aad                            LTSKQLAYVTYTSGTTGFPKGILKQHTNVVNSITDLSARYGVTGDHHEAILLFSAYVFEP
P27743_A1_aad                            LSSRDRAYVTYTSGTTGVPKGVPKYHYSVVNSITDLSERYDMRRPGTERVALFASYVFEP
P26046_A1_aad                            LTSQQLAYVTYTSGTTGFPKGIFKQHTNVVNSITDLSARYGVAGQHHEAILLFSACVFEP
Q01757_A1_aad                            LGVRDLAYLTYTSGTTGVPKGVPKYHDSVVNSITDLSERYDMRRPGTERVALFASYVFEP
P19787_A1_aad                            LTSQQLAYVTYTSGTTGFPKGIFKQHTNVVNSITDLSARYGVAGQHHEAILLFSACVFEP
P25464_A1_aad                            LNSKQLAYVTYTSGTTGFPKGIYKEHTSVVNSITDLSARYGVAGEDDEVILVFSAYVFEP
P94873_A1_aad                            LGSQQVAYVTYTSGTTGIPKGVPKTHRSVVNAITDLSDRYQMREAGTEHVALFAALVFEP
Q9C1G0v2_A1_aad                          LNSKQLAYVTYTSGTTGFPKGIYKEHTSVVNSITDLSARYGVSGSDDEVILLFSAYVFEP
Q9C1G0v1_A1_aad                          LNSKQLAYVTYTSGTTGFPKGIYKEHTSVVNSITDLSARYGVSGSDDEVILLFSAYVFEP
                                         *  :: **:********.***: * * .***:***** ** :     * : :*:: ****

P27742_A1_aad                            FVRQMLMALVNGHLLAMVDDAEKYDAEKLIPFIREHKITYLNGTASVLQEYDFSSCPSLK
P27743_A1_aad                            HLRQTLIALINEQTLVIVPDDVRLDPDLFPEYIERHGVTYLNATGSVLQHFDLRRCASLK
P26046_A1_aad                            FVRQTLMALVNGHLLAVINDVEKYDADTLLPFIRRHSITYLNGTASVLQEYDFSDCPSLN
Q01757_A1_aad                            HLRQTLIALINGQTLVVVPEEVRLDPDRFPAYIEEHGVTYLNATGSVLQHFDLRRRTSLK
P19787_A1_aad                            FVRQTLMALVNGHLLAVINDVEKYDADTLLPFIRRHSITYLNGTASVLQEYDFSDCPSLN
P25464_A1_aad                            FVRQMLMALTTGNSLAIISDEDKFDPDTLIPFIQKHKVTYIHATSSVLQEYDFGSCPSLK
P94873_A1_aad                            FMRQTLIALINSQTLVVVPDDVRLDPLRFPRFVDEHRISYLNGTRSVLQHFDLSQCRSLK
Q9C1G0v2_A1_aad                          FVRQMLMALTTGNTLAIINDEDKFDPDILLPFIRRHKVTYLNGTASVVQEYDLTTCPSLK
Q9C1G0v1_A1_aad                          FVRQMLMALTTGNTLAIINDEDKFDPDILLPFIRRHKVTYLNGTASVVQEYDLTTCPSLK
                                         .:** *:** . : *.:: :  : *.  :  :: .* ::*::.* **:*.:*:    **:

P27742_A1_aad                            RLILVGENLTESRYLALRRHFKNCILNEYGFTESAFVTALNVFEPG-SARNNTSLGRPVR
P27743_A1_aad                            RLLLVGEELTASGLRQLREKFAGRVVNEYAFTEAAFVTAVKEFGPGVTERRDRSIGRPLR
P26046_A1_aad                            RIILVGENLTEARYLALRQRFKNRILNEYGFTESAFVTALKIFDPE-STRKDTSLGRPVR
Q01757_A1_aad                            RLLLVGEELTAAGLRQLRERFSGRIVNEYAFTEAAFVTAVKKFAPGVTERADRSIGRPVR
P19787_A1_aad                            RIILVGENLTEARYLALRQRFKNRILNEYGFTESAFVTALKIFDPE-STRKDTSLGRPVR
P25464_A1_aad                            RMILVGENLTEPRYEALRQRFKSRILNEYGFTESAFVTALNIFEPT-SQRKDMSLGRPVR
P94873_A1_aad                            RMLLVGEELTPSGLRTLRERFHGRIINEYAFTETAFVTAIKEYPPGDAERNDRSIGRPLR
Q9C1G0v2_A1_aad                          RLVLVGENLTEARYKALRRRFKARILSEYGFTESAFVTALNIFDPA-SERTNMSLGRPVR
Q9C1G0v1_A1_aad                          RLVLVGENLTEARYKALRRRFKARILSEYGFTESAFVTALNIFDPA-SERTNMSLGRPVR
                                         *::****:** .    **.:*   ::.**.***:*****:: : *  : * : *:***:*

P27742_A1_aad                            NVKCYILNKSLKRVPIGATGELHIGGLGISKGYLNRPDLTPQRFIPNPFQTDHEKELGLN
P27743_A1_aad                            NVKWYVLSQGLKQLPIGAIGELYIGGCGVAPGYLNRDDLTAERFTANPFQTEEEKARGRN
P26046_A1_aad                            NVKCYILNPSLKRVPIGATGELHIGGLGISKGYLNRPELTPHRFIPNPFQTDCEKQLGIN
Q01757_A1_aad                            NVKWYVLSQDLKRLPVGAIGELYIGGCGVAPGYLNRDDLTAERFLTNPYASEQDRARGTN
P19787_A1_aad                            NVKCYILNPSLKRVPIGATGELHIGGLGISKGYLNRPELTPHRFIPNPFQTDCEKQLGIN
P25464_A1_aad                            NVKCYILDANLKRVPIGVTGELHIGGLGISRGYMNREELTRQKFLPNPYQTDKERQRGVN
P94873_A1_aad                            NVKCYIVSQNMKQVPIGAIGELYIGGTGVASGYLNRPDLTAERFLDNPFRTPGERAAGRN
Q9C1G0v2_A1_aad                          NVKCYILDSNLKRLPLGVTGELHIGGLGISRGYMNRDELTRAKFLKNPYQ-DDEKGRGVN
Q9C1G0v1_A1_aad                          NVKCYILDSNLKRLPLGVTGELHIGGLGISRGYMNRDELTRAKFLKNPYQ-DDEKGRGVN
                                         *** *::. .:*::*:*. ***:*** *:: **:** :**  :*  **:    ::  * *

P27742_A1_aad                            QLMYKTGDLARWLPNGEIEYLGRADFQIKLRGIRIEPGEIESTLAGYPGVRTSLVVSKRL
P27743_A1_aad                            GRLYRTGDLARVLLNGEVEFMGRADFQLKLNGVRVEPGEIEAQATEFPGVKKCVVVAK--
P26046_A1_aad                            SLMYKTGDLARWLPNGEVEYLGRADFQIKLRGIRIEPGEIETMLAMYPRVRTSLVVSKKL
Q01757_A1_aad                            ARIYRTGDLARMLPSGEVEFMGRSDFQLKLNGVRVEPGEIEAQATEYAGVRKCVVIAR--
P19787_A1_aad                            SLMYKTGDLARWLPNGEVEYLGRADFQIKLRGIRIEPGEIETMLAMYPRVRTSLVVSKKL
P25464_A1_aad                            STMYKTGDLARWLPSGEVEYLGRADFQIKLRGIRIEPGEIESTLAMYPGIRASIVVSKKL
P94873_A1_aad                            ERIYRTGDLAKFLPDGQIEFMGRSDFQLKLNGVRVEPGEIEARALEFPGVRQCVVVAR--
Q9C1G0v2_A1_aad                          GLMYKTGDLARWLPNGEVEYLGRADFQIKLRGIRIEPGEIESTLGAYPGIRTSIVVSKKL
Q9C1G0v1_A1_aad                          GLMYKTGDLARWLPNGEVEYLGRADFQIKLRGIRIEPGEIESTLGAYPGIRTSIVVSKKL
                                           :*:*****: * .*::*::**:***:**.*:*:******:    :. :: .:*:::  

P27742_A1_aad                            RHGEKETTNEHLVGYYVGD-NTSVSETA
P27743_A1_aad                            -ENATG--DRHLVGYYLVEDGAEVAEAD
P26046_A1_aad                            RNGPEETTNEHLVGYYVCD-SASVSEAD
Q01757_A1_aad                            -EGAGGGSDRHLVGYYLTEPGAGVTEAE
P19787_A1_aad                            RNGPEETTNEHLVGYYVCD-SASVSEAD
P25464_A1_aad                            LSQGQETIQDHLVGYYVCD-EGHIPEGD
P94873_A1_aad                            -GESVETGNWRLIGYYVADGDEPIPEAD
Q9C1G0v2_A1_aad                          LSQGEETRQDHLVGYFVCD-DEMLSESD
Q9C1G0v1_A1_aad                          LSQGEETRQDHLVGYFVCD-DEMLSESD
                                                 : :*:**:: :    :.*  
