CLUSTAL W multiple sequence alignment


BGC0000414_BAO84861.1_508_mod1_ala       ARATVLITTQNLTATLPEGTWHALTLDT--THTGRHPTRRPTNKTVPANLAYTIYTSGST
Q93TX2/14210837_A1_8__ala                AQVPVLLTQQRLVPELPATQARVVCLDKDWPTIGAESDTNPERITAPEAIAYLIYTSGST
                                         *:..**:* *.*.. **    :.: **.  .  * ..  .* . *.*  :** *******

BGC0000414_BAO84861.1_508_mod1_ala       GRPKGVMIEHRQTTTLLAWAHTTYTPAQLTNVLASTSICFDLSVFEIFAPLTTGGSITLT
Q93TX2/14210837_A1_8__ala                GKPKGVMIEHRNAVAFLIWAMSVFSPKELAGTLASTSICFDLSVFEIFTPLCCGAKV-IV
                                         *:*********::.::* ** :.::* :*:..****************:**  *..: :.

BGC0000414_BAO84861.1_508_mod1_ala       HTNALDLLT-PPHPDITLINTVPSIIQELHTHNAIPPTTTTINLAGEPLPPHLVNTLHNH
Q93TX2/14210837_A1_8__ala                AKNALELPELPAAREVTLINTVPSAMGALLRSGGVPSSVAIVNLAGEALAGALVDQIYQL
                                          .***:*   *.  ::******** :  *   ..:*.:.: :*****.*.  **: ::: 

BGC0000414_BAO84861.1_508_mod1_ala       PHIHTINNLYGPTEDTTYSTHATTTPNDPRTP-IGHPLPHTHAHILDHNLNPVPTGTIGE
Q93TX2/14210837_A1_8__ala                DHVRDVFNLYGPSETTTYSTF--TRVNRGQTPTIGRPVGNTQVYALDSNREPMPIGVPGE
                                          *:: : *****:* *****.  *  *  :** **:*: :*:.: ** * :*:* *. **

BGC0000414_BAO84861.1_508_mod1_ala       LYLTSHRTTRGYHNHPRQTAEHYLPNPH--NPHTRLYRTGDLARWRPDGQLDYHGRTDNQ
Q93TX2/14210837_A1_8__ala                VYIGGMGVARGYLGRPELTAERFVRSPFGGGSEARLYRTGDLARWLPDGQLEYLGRMDHQ
                                         :*: .  .:*** .:*. ***::: .*.  ...:*********** *****:* ** *:*

BGC0000414_BAO84861.1_508_mod1_ala       IKINGHRIEPAEIETTLLTHPHVQETTITTHT-TPHTTQLIAYITAPQLNNNPTP--
Q93TX2/14210837_A1_8__ala                VKLRGFRIELGEIGAVLMEHSGIRDAVVVVREGLGADKQLVAYVVG-RGEKAPEPAE
                                         :*:.*.*** .** :.*: *. ::::.:..:      .**:**:.. : :: * *  
