CLUSTAL W multiple sequence alignment


Q83VS0/81321400_A9_19__ala               SAPAAVLAQTA-------TQGLLAD---VSVPVINL-DLSDWQD-----QSV-------Q
BGC0000464_CDG17982.1_523_mod1_ala       AAPVAVVTQKAIVTQKAIATQMLADGVTRSVPTVLIDDILNHQEPVPEARSIAPPLTDNP
Q83VS1_A5_10__ala                        SAPAAVLVQAA-------TRHLLAG---VSVQAIDLDDQSAWQD-----EPV-------Q
Q83VS1_A1_6__ala                         SVPAAVLAQTA-------TQGLLAD---VSVPVINL-DLSVWQD-----ESV-------Q
Q83VS0_A2_12__ala                        SAPAAVLAQTA-------TQGLLAD---VSVPVINL-DLSNWQD-----ESV-------Q
Q83VS1_A1_ala                            SVPAAVLAQTA-------TQGLLAD---VSVPVINL-DLSVWQD-----ESV-------Q
Q9FDB3_A5_5__ala                         SAPAAVLVQTA-------TQRLLAD---TSVPLIHL-DLSDWQD-----ESV-------Q
Q83VS1_A5_ala                            SAPAAVLVQAA-------TRHLLAG---VSVQAIDLDDQSAWQD-----EPV-------Q
Q83VS0_A7_17__ala                        SAPTAVLAQTA-------TQGLLAD---VSVPVINL-DLSNWQD-----ESV-------Q
BGC0000464_CDG17980.1_1601_mod2_ala      AAPIVVLTQTT-----------LADKLVSTVSTVLLDS----QEPFMAMEAL--PAGD-P
Q83VS0_A3_13__ala                        SAPAAVLAQSA-------TEALLAD---VSVPVINL-DLGNWQD-----QSV-------Q
                                         :.* .*:.* :           **.    :*  : : .    *:     ..:        

Q83VS0/81321400_A9_19__ala               NPQVPGLTSAHLAYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHTAFDA----SALEKTLF
BGC0000464_CDG17982.1_523_mod1_ala       DARRLGLTSRHLAYVIYTSGSTGLPKGVTITHRNTVNLLTWAQRTFSA----EELAHTLF
Q83VS1_A5_10__ala                        NPDVEGLSSAHLAYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHHAFNG----SALEKTLF
Q83VS1_A1_6__ala                         NPQVPGLTSAHLAYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHTAFDG----SALEKTLF
Q83VS0_A2_12__ala                        NPQVPGLTSAHLAYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHSAFDA----SALEKTLF
Q83VS1_A1_ala                            NPQVPGLTSAHLAYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHTAFDG----SALEKTLF
Q9FDB3_A5_5__ala                         NPRVPGLTSAHLAYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHAAFDAGTNNSALEKTLF
Q83VS1_A5_ala                            NPDVEGLSSAHLAYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHHAFNG----SALEKTLF
Q83VS0_A7_17__ala                        NPQVPGLTSAHLAYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHSAFDA----SALEKTLF
BGC0000464_CDG17980.1_1601_mod2_ala      DPQTLGLTSHHLAYVIYTSGSTGLPKGVAVTHRNTVNFLTWAQRTFQR----DELAQALF
Q83VS0_A3_13__ala                        NPQVPGLTSAHLAYLIYTSGSTGLPKGVMIEHRNTVNFLTWAHSAFDAGTATSALEKTLF
                                         :.   **:* ****:************* : ******:****: :*.     . * ::**

Q83VS0/81321400_A9_19__ala               STSLNFDLAVYECFAPLTSGGSIEVVKNVLELQHG---------------EHDIGLINTV
BGC0000464_CDG17982.1_523_mod1_ala       ATSFNFDLSVYECFVPLISGGTVHLVADALALINTERFTSERFTSERFTSEKAISLINTV
Q83VS1_A5_10__ala                        STSLNFDLAVYECFAPLTSGGSINVVKNVLELQHG---------------EHDIGLVNTV
Q83VS1_A1_6__ala                         STSLNFDLAVYECFAPLTSGGSIEVVKNVLELQHG---------------EHDIGLINTV
Q83VS0_A2_12__ala                        STSLNFDLAVYECFAPLTSGGSIEVVKNVLELQHG---------------EHDIGLINTV
Q83VS1_A1_ala                            STSLNFDLAVYECFAPLTSGGSIEVVKNVLELQHG---------------EHDIGLINTV
Q9FDB3_A5_5__ala                         STSLNFDLAVYECFAPLTSGGSIEVVRNVLELQHL---------------DDDIRLINTV
Q83VS1_A5_ala                            STSLNFDLAVYECFAPLTSGGSINVVKNVLELQHG---------------EHDIGLVNTV
Q83VS0_A7_17__ala                        STSLNFDLAVYECFAPLTSGGSIEVVKNVLELQHG---------------EHDIGLINTV
BGC0000464_CDG17980.1_1601_mod2_ala      ATSLNFDISVFECFAPLLVGGTVHLMPDILSLVNA-------------ATTPSLSLINTV
Q83VS0_A3_13__ala                        STSLNFDLAVYECFAPLTSGGSIEVVKNVLELQNG---------------EHDIGLINTV
                                         :**:***::*:***.**  **::.:: : * * :                   : *:***

Q83VS0/81321400_A9_19__ala               PSALKALLEVNGLPESVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWV
BGC0000464_CDG17982.1_523_mod1_ala       PSAIAHLLEADAIPPTVQTVNLAGEALKPHIVERLFTLSSIQNVCNLYGPSETTTYSTWT
Q83VS1_A5_10__ala                        PSALKALLEINGLPESVHTVNVAGEALKRSLVENLFEKTGVQRLCNLYGPSETTTYSSWV
Q83VS1_A1_6__ala                         PSALKALLEVNGLPESVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWV
Q83VS0_A2_12__ala                        PSALKALLEVNGLPESVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWV
Q83VS1_A1_ala                            PSALKALLEVNGLPESVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWV
Q9FDB3_A5_5__ala                         PSALKALLETDGLPKSVHTVNVAGEALKRSLVEALFEQTGVQRLCNLYGPSETTTYSSWV
Q83VS1_A5_ala                            PSALKALLEINGLPESVHTVNVAGEALKRSLVENLFEKTGVQRLCNLYGPSETTTYSSWV
Q83VS0_A7_17__ala                        PSALKALLDVDGLPRSVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWV
BGC0000464_CDG17980.1_1601_mod2_ala      PSAIVHLIEARAVPSCIQTVNLAGEALKAHVVEHLFAHSTVQDVCNLYGPSETTIYSTWT
Q83VS0_A3_13__ala                        PSALKALLDVDGLPRSVHTVNVAGEALKQSLVESLFENTGVQRLCNLYGPSETTTYSSWV
                                         ***:  *::  .:*  ::***:******  :** **  : :* :********** **:*.

Q83VS0/81321400_A9_19__ala               AMDRDDGFAAHIGKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAER
BGC0000464_CDG17982.1_523_mod1_ala       RLNRTTGVVTHIGRPIANTQIYILDADKQPVPLGVTGEIYIAGAGVASGYLNRPQLTAER
Q83VS1_A5_10__ala                        AMDREDGFAAHIGRPVGNTRFYLLDEQQQLVPRGVPGEIYIGGAGVARGYLNRDDLTAER
Q83VS1_A1_6__ala                         AMDREHGFAAHIGKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAER
Q83VS0_A2_12__ala                        AMDREHGFAAHIGKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAER
Q83VS1_A1_ala                            AMDREHGFAAHIGKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAER
Q9FDB3_A5_5__ala                         AMDREDGFAAHIGKPVGNTRFYLLDEQQQPVPRGVAGEIYIGGAGVARGYRNRDDLTAER
Q83VS1_A5_ala                            AMDREDGFAAHIGRPVGNTRFYLLDEQQQLVPRGVPGEIYIGGAGVARGYLNRDDLTAER
Q83VS0_A7_17__ala                        AMDREDGFAAHIGKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAER
BGC0000464_CDG17980.1_1601_mod2_ala      RMKRTTGFHHHIGRPIANTQIYILDTQGQPVPLGVIGEIHIAGAGVARGYFNRPELTKAR
Q83VS0_A3_13__ala                        AMDREDGFAAHIGKPVGNTQFYLLDEQQQPVPLGVAGEIYIGGAGVARGYLNRDDLTAER
                                          :.*  *.  ***:*:.**::*:** : * ** ** ***:*.***** ** ** :**  *

Q83VS0/81321400_A9_19__ala               FVKDPFSPQPAARMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLTRHPA
BGC0000464_CDG17982.1_523_mod1_ala       FLSDPFSLEANARMYKTGDLGRWLPDGNIEYLGRNDFQVKLRGFRIELGEIEAQLVQCHG
Q83VS1_A5_10__ala                        FLTDPFSLTPGARMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDACLAKHPA
Q83VS1_A1_6__ala                         FLKDPFSQQSAARMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLARHPA
Q83VS0_A2_12__ala                        FLKDPFSQNPAARMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLAKHPA
Q83VS1_A1_ala                            FLKDPFSQQSAARMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLARHPA
Q9FDB3_A5_5__ala                         FLKDPFSPQPAARMYHTGDLGRYLPDGNIQYLGRNDDQVKIRGFRIELGEIDACLAKHPA
Q83VS1_A5_ala                            FLTDPFSLTPGARMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDACLAKHPA
Q83VS0_A7_17__ala                        FVKDPFSSQPAARMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLAKHPA
BGC0000464_CDG17980.1_1601_mod2_ala      FLTDPFSPEPDARMYKTGDLGRWLPDGNIEYLGRNDFQVKLRGFRIELGEIEAQLMQCHG
Q83VS0_A3_13__ala                        FVKDPFSSQPAARMYRTGDLGRYLPDGNIEYLGRNDDQVKIRGFRIELGEIDARLTKHPA
                                         *:.****  . ****:******:******:****** ***:**********:* * :  .

Q83VS0/81321400_A9_19__ala               IHEAVVAAR----------EDVPGDKRLVAYYTLSAGHASVDIDS--
BGC0000464_CDG17982.1_523_mod1_ala       VREAVVLAREEVVGKEIAGENRAGQKRLVAYLR--PQDGVELIPAEL
Q83VS1_A5_10__ala                        VHEAVVMAR----------EDVPGEIRLVAYFT--PTDPAVITDSGS
Q83VS1_A1_6__ala                         IHEAVVAAR----------EDVPGDKRLVAYYTLAAGHTSADIDS--
Q83VS0_A2_12__ala                        VHEAVVTAR----------EDIPGDKRLVAYYTLVSGHTSVDIDN--
Q83VS1_A1_ala                            IHEAVVAAR----------EDVPGDKRLVAYYTLAAGHTSADIDS--
Q9FDB3_A5_5__ala                         VQDAVVTAR----------EDVPGDKRLVAYYTVQPAQTEPAIDS--
Q83VS1_A5_ala                            VHEAVVMAR----------EDVPGEIRLVAYFT--PTDPAVITDSGS
Q83VS0_A7_17__ala                        VHEAVVTAR----------EDIPGDKRLVAYYTLASGHTSADIDS--
BGC0000464_CDG17980.1_1601_mod2_ala      VRNAVVIAR----------EDEPGQKRLVAYLQ--PLDGIELLPAEL
Q83VS0_A3_13__ala                        VHEAVVTAR----------EDIPGDKRLVAYYTLSAGHASVDIDS--
                                         :::*** **          *: .*: *****    . .         
