CLUSTAL W multiple sequence alignment


Q01886v2_A2_ala                          VQAELLLCSPATSRMGALQNISTQMGTEFKIVELEPEFIRSLPLPPKPNHQPMVGLNDDL
Q01886v1_A2_ala                          VQAELLLCSPATSRMGALQNISTQMGTEFKIVELEPEFIRSLPLPPKPNHQPMVGLNDDL
BGC0001166_AGQ43600.1_1838_mod2_ala      VQARVLLCSPVTRSIGALQNISTEMGAGLKIIRIEPEFIQGLPPVPRLAHQDMAGLDDDL
                                         ***.:*****.*  :********:**: :**:.:*****:.**  *:  ** *.**:***

Q01886v2_A2_ala                          YVVFTSGSTGVPKGAVATHQAYATGIYEHAVACGMTSLGAPPRSLQFASYSFDASIGDIF
Q01886v1_A2_ala                          YVVFTSGSTGVPKGAVATHQAYATGIYEHAVACGMTSLGAPPRSLQFASYSFDASIGDIF
BGC0001166_AGQ43600.1_1838_mod2_ala      YVVFTSGSTGDPKGAVATHRAFATGIYEHAMACGMTSVGAPPRSLQFASYSFDASIGDIF
                                         ********** ********:*:********:******:**********************

Q01886v2_A2_ala                          TTLAVGGCLCIPREEDRNPAGITTFINRYGVTWAGITPSLALHLDPDAVPTLKALCVAGE
Q01886v1_A2_ala                          TTLAVGGCLCIPREEDRNPAGITTFINRYGVTWAGITPSLALHLDPDAVPTLKALCVAGE
BGC0001166_AGQ43600.1_1838_mod2_ala      TTFVASGCLCIPREEDRNPVGITAFINRCGVTWAGITPSFVSHLEPDAVPTLKALCVAGE
                                         **:...*************.***:**** **********:. **:***************

Q01886v2_A2_ala                          PLSMSVVTVWSKRLNLINMYGPTEATVACIANQVTCTTTTVSDIGRGYRATTWVVQPDNH
Q01886v1_A2_ala                          PLSMSVVTVWSKRLNLINMYGPTEATVACIANQVTCTTTTVSDIGRGYRATTWVVQPDNH
BGC0001166_AGQ43600.1_1838_mod2_ala      PLSMSVVTAWSNRLNLINMYGPTEATVACIANRVLCTTTTVGDIGRGYRAATWVVQPDNH
                                         ********.**:********************:* ******.********:*********

Q01886v2_A2_ala                          NSLVPIGAVGELIIEGSILCRGYLNDPERTAEVFIRSPSWLHDLRPNSTLYKTGDLVRYS
Q01886v1_A2_ala                          NSLVPIGAVGELIIEGSILCRGYLNDPERTAEVFIRSPSWLHDLRPNSTLYKTGDLVRYS
BGC0001166_AGQ43600.1_1838_mod2_ala      NSLVPIGAVGELIIEGSILCRGYLNDPERTAEVFIRSPSWLHDLRPNSTLYKTGDLVRYS
                                         ************************************************************

Q01886v2_A2_ala                          ADGKIIFIGRKDTQVKMNGQRFELGEVEHALQLQLDPSDGPIIVDLLKRTQSGEPDLLIA
Q01886v1_A2_ala                          ADGKIIFIGRKDTQVKMNGQRFELGEVEHALQLQLDPSDGPIIVDLLKRTQSGEPDLLIA
BGC0001166_AGQ43600.1_1838_mod2_ala      ADGKIIFIGRKDTQVKMNGQRFELGEVEHALQLQLDPSDGPIIVDLLKRTQSGEPDLLIA
                                         ************************************************************

Q01886v2_A2_ala                          FLFVGRANTGTGNSDEIFIATSTSS
Q01886v1_A2_ala                          FLFVGRANTGTGNSDEIFIATSTSS
BGC0001166_AGQ43600.1_1838_mod2_ala      FLFVGRANTGTGNSDEIFIATSTSS
                                         *************************
