CLUSTAL W multiple sequence alignment


Q9S1A9_A2_7__ala                         AQVSLLLTQAKLVEKLGNYPGNLVILEAEARNIALESPENLSLPVSSSNTAYVIYTSGST
Q6E7J5_A1_ala                            AAVPVLLASESVLDSLPEHQAKIVCLDTIGETITNEGTDNPASQVTPENLAYVIYTSGST
BGC0001125_AIW82284.1_2452_mod3_ala      SQVSVLLTQSQCLKSLPDVDNLRICLDTDWGIIETQSQENPVSEVAPNNLAYIIYTSGST
Q93TX2/14210837_A1_8__ala                AQVPVLLTQQRLVPELPATQARVVCLDKDWPTIGAESDTNPERITAPEAIAYLIYTSGST
Q8G983/24744797_A2_7__ala                SQVPVLLTQQTLLSHLSHYSGDRVVLDRDAAIIAQQPKTNPKSQVSSSNSVYVIYTSGST
                                         : *.:**:.   :  *       : *:     *  :   *    .:..  .*:*******

Q9S1A9_A2_7__ala                         GKPKGVVIEHHSTTTLLNWSKEVFSSEELAGVLGSTSICFDLSVFELFLPLAVGGKIILA
Q6E7J5_A1_ala                            GKPKGVAIEHHSPVALCYWASQVFTIKELAAVLASTSICFDLSVFEIFVTLSQGGQVILA
BGC0001125_AIW82284.1_2452_mod3_ala      GKPKGVAIAHCSPVALVAWALKVFTPQQLAGVLASTSLCFDLSIFEMFVPLSCGGMVIVA
Q93TX2/14210837_A1_8__ala                GKPKGVMIEHRNAVAFLIWAMSVFSPKELAGTLASTSICFDLSVFEIFTPLCCGAKVIVA
Q8G983/24744797_A2_7__ala                GKPKGVVIEHRSTVTLLDWARTVFSFDELAGVLASTSVCFDLSVFELFLPLTVGGAVILA
                                         ****** * * ...::  *:  **: .:**..*.***:*****:**:* .*  *. :*:*

Q9S1A9_A2_7__ala                         QNVLDLPSLSAAKEVTLINTVPTAIAQLLEIEAIPETVQTVNFAGEALSNQLVQKLYQQE
Q6E7J5_A1_ala                            QNALDLPNIKS--EITLINTVPSAITELSRINAIPDSVKVINLAGEPFSNQLLQRLYQQE
BGC0001125_AIW82284.1_2452_mod3_ala      ENALHLPELIAFEQVTLINTVPSAIRELLNGPGLPQSLATVNLAGEPLPLSLVQQLYQRQ
Q93TX2/14210837_A1_8__ala                KNALELPELPAAREVTLINTVPSAMGALLRSGGVPSSVAIVNLAGEALAGALVDQIYQLD
Q8G983/24744797_A2_7__ala                DNALALPNLAAATEVTLINTVPTAIAQLLALEAIPQSVRTVNLAGEPLSNSLVQKLYQLP
                                         .*.* **.: :  ::*******:*:  *    .:*.::  :*:***.:.  *::::**  

Q9S1A9_A2_7__ala                         NIKNVYNLYGPSEDTTYSTFSLVPKKDHGQPSIGRPIANTQVYILDSFKQPVPLGTIGDL
Q6E7J5_A1_ala                            NIQSVYNLYGPSEYTTYTTFTLLKKGTTTQPTIGHPIANTQVYILDSHLQPVPIGVVGEL
BGC0001125_AIW82284.1_2452_mod3_ala      TIHQVFNLYGPSETTTYSTFALCNRGDSLAPTIGRAIANTQIYILDALMQPVPIGVRGEL
Q93TX2/14210837_A1_8__ala                HVRDVFNLYGPSETTTYSTFTRVNRGQT--PTIGRPVGNTQVYALDSNREPMPIGVPGEV
Q8G983/24744797_A2_7__ala                QIERVYNLYGPSEDTSYSTFSCIEKGATTQPSIGRPIAHSQVYLLNATHQPVPLGTIGEL
                                          :. *:******* *:*:**:   :     *:**:.:.::*:* *::  :*:*:*. *::

Q9S1A9_A2_7__ala                         YIGGKGLARCYLNQPELTAEKFISNPFSN--------EPKAKLYKTGDLARYLPDGNIDF
Q6E7J5_A1_ala                            YIGGDGLARGYHNRPELTAEKFIPNPFDN--------STSTRLYKTGDLARYLPDGNIAF
BGC0001125_AIW82284.1_2452_mod3_ala      YIGGAGVARGYLNRPELTAEKFIPNPFEN--------SKFHRLYKTGDLARYLPDGNIEY
Q93TX2/14210837_A1_8__ala                YIGGMGVARGYLGRPELTAERFVRSPFGG--------GSEARLYRTGDLARWLPDGQLEY
Q8G983/24744797_A2_7__ala                YMGGAGLARGYLHRPELTAEKFIANPFHSPLQKYQGLSPSPKLYKTGDLARYRPDGNLEF
                                         *:** *:** *  :******:*: .** .            :**:******: ***:: :

Q9S1A9_A2_7__ala                         LGRGDNQVKLRGFRIELGEIEATLGTYPQVKQKVVKVWEDSYRNKRLVAYLVGENGPINT
Q6E7J5_A1_ala                            IGRIDHQVKIRGFRIEMGEIEAFVSQYPDVKENAVIAQSDPAGGKRLVVYIVPKQESTQD
BGC0001125_AIW82284.1_2452_mod3_ala      LGRIDNQVKLRGFRIELGEIETAIALHPQLKQAVVSIREDQPGIRRLVAYLVAEVETPSS
Q93TX2/14210837_A1_8__ala                LGRMDHQVKLRGFRIELGEIGAVLMEHSGIRDAVVVVREGLGADKQLVAYVVGRGEKAPE
Q8G983/24744797_A2_7__ala                LGRSDYQIKLRGFRIELGEIEVVLENCPGVKQAVVLRREDLVGGAKLVAYVVSENSTLTT
                                         :** * *:*:******:*** . :   . ::: .*   ..     :**.*:* .      

Q9S1A9_A2_7__ala                         ED-
Q6E7J5_A1_ala                            TS-
BGC0001125_AIW82284.1_2452_mod3_ala      SE-
Q93TX2/14210837_A1_8__ala                PAE
Q8G983/24744797_A2_7__ala                QD-
                                            
