CLUSTAL W multiple sequence alignment


P0A398_A1_ala                            AEPSLIIAISAFPLEQVSTPMINLAQVQEAFAQGNN-YEITHPVKGDDNYYIIFTSGTTG
P59591_A1_ala                            AQPSLIISIGEFPLEVDNVPILDVSQVSAIFEEKTP-YEVTHSVKGDDNYYIIFTSGTTG
P68876_A1_ala                            VQPEFVFNTTDESFESLEGEVFTI---EDIKTSQDP-VIFDSQIKDNDTVYTIFTSGSTG
P35854_A1_ala                            AHAPAVIEVAPLPITVPDVKIIRAPALHQAEQSHAPIHSLQHAVAGDDNYYIIFTSGTTG
P39581_A1_ala                            SGAELLIHAAGLSIDAVGQQIQTVSAEELLENEGGS-VSQDQWVKEHETFYIIYTSGSTG
Q53526_A1_ala                            AEPSLVIAVDDFPIDNLQVPVIQYSQLEEIFKQKLS-YQINHAVKGDDTYYIIFTSGTTG
P68878_A1_ala                            VQPEFVFNTTDESFESLEGEVFTI---EDIKTSQDP-VIFDSQIKDNDTVYTIFTSGSTG
                                           .  ::     .:      :           .          :  .:. * *:***:**

P0A398_A1_ala                            KPKGVQISHDNLLSFTNWMITDKEFATPSRP-QMLAQPPYSFDLSVMYWAPTLALGGTLF
P59591_A1_ala                            LPKGVQISHDNLLSFTNWMISDDEFSVPERP-QMLAQPPYSFDLSVMYWAPTLAMGGTLF
P68876_A1_ala                            EPKGVQIEYASLVQFTEWM-LE--LNKSGNKQQWLNQAPFSFDLSVMAIYPCLASGGTLN
P35854_A1_ala                            KPKGVQISHDNLLSYVNWNISD--FGLEEGV-VAMSQPPYSFDLSVMDLYPTLVLGGTLK
P39581_A1_ala                            NPKGVQISAANLQSFTDWICAD--FPVSGGK-IFLNQAPFSFDLSVMDLYPCLQSGGTLH
Q53526_A1_ala                            KPKGVQISHDNLLSFTNWMINAEAFAIPHRP-QMLAQPPYSFDLSVMYWAPTLALGGTLF
P68878_A1_ala                            EPKGVQIEYASLVQFTEWM-LE--LNKSGNEQQWLNQAPFSFDLSVMAIYPCLASGGTLN
                                          ******.  .* .:.:*      :         : *.*:*******   * *  **** 

P0A398_A1_ala                            TLPSVITQDFKQLFAAIFSLPIAIWTSTPSFADMAMLSEYFNSEKMPGITHFYFDGEELT
P59591_A1_ala                            ALPKTVVNDFKKLFATINELPIQVWTSTPSFADMALLSNDFNSETLPQLTHFYFDGEELT
P68876_A1_ala                            LVDKNMINKPKLLNEMLTATPINIWVSTPSFMEMCLLLPTLNEEQYGSLNEFFFCGEILP
P35854_A1_ala                            ALPKEVTDNFKELFATLPKLGLNEWVSTPSFVEIALLDPNFKQENYPNLTHFLFCGEELV
P39581_A1_ala                            CVTKDAVNKPKVLFEELKKSGLNVWTSTPSFVQMCLMDPGFSQDLLPHADTFMFCGEVLP
Q53526_A1_ala                            ALPKEITADFKQLFTTITNYHWCVDINT-FFVDMAMLSDDFNAQQLPHLTHFYFDGEELT
P68878_A1_ala                            LVDKNMINKPKLLNEMLTATPINIWVSTPSFMEMCLLLPTLNEEQYGSLNEFFFCGEILP
                                          : .    . * *   :         .*  * ::.::   :. :       * * ** * 

P0A398_A1_ala                            VKTAQKLRERFPNARIINAYGPTEATVALSAVAVTDEMLATLKRLPIGYTKADSPTFIID
P59591_A1_ala                            VKTAQKLRQRFPKARIVNAYGPTEATVALSAVAITDEMLETCKRLPIGYTKDDSPTYVID
P68876_A1_ala                            HRAAKALVSRFPSATIYNTYGPTEATVAVTSIQITQEILDQYPTLPVGVERL--------
P35854_A1_ala                            NKTAQALITRFPKATVYNTYGPTEATVAVTGMAITQAIVDQYPRLPIGYAKPDTNVYVVD
P39581_A1_ala                            VSVAKALLERFPKAKIFNTYGPTEATVAVTSVEITNDVISRSESLPVGFAKPDMNIFIMD
Q53526_A1_ala                            VKTAKKLRQRFPQARIVNAYGPTEATVALSALAVTDKMLETCKRLPIGYTKPDSPTFIID
P68878_A1_ala                            HRAAKALVNRFPSATIYNTYGPTEATVAVTSIQITQEILDQYPTLPVGVERP--------
                                           .*: *  ***.* : *:*********::.: :*: ::     **:*  :         

P0A398_A1_ala                            EEGNKLPNGEQGEIIVSGPAVSKGYMNNPEKTAEAFFEFEDLPAYHTGDVGTMTDEGLLL
P59591_A1_ala                            EEGHKLPNGEQGEIIIAGPAVSKGYLNNPEKTAEAFFQFEGLPAYHTGDLGSMTDEGLLL
P68876_A1_ala                            --GARLSTTDDGELVIEGQSVSLGYLKNDQKTAEVFNFDDGIRTYHTGDKAKF-ENGQWF
P35854_A1_ala                            EQGEQVSAGTEGELMIVGPSVSKGYLNNPDKTAAAFFKAGNQRGYRSGDLVTMTADGMVF
P39581_A1_ala                            EEGQPLPEGEKGEIVIAGPSVSRGYLGEPELTEKAFFSHEGQWAYRTGDAGFI-QDGQIF
Q53526_A1_ala                            ESGHKLANGQQGEIIVSGPAVSKGYLNNPERTAAAFFEFEGLPAYHTGDLGSMTDEGLLL
P68878_A1_ala                            --GARLSTTDEGELVIEGQSVSLGYLKNDQKTAEVFNFDDGIRTYHTGDKAKF-ENGQWF
                                           *  :.   .**::: * :** **: : : *  .*    .   *::**   :  :*  :

P0A398_A1_ala                            YGGRMDFQIKFNGYRIELEDVSQNLNKSRFIESAVAVPRYNKDHKVQNLLAYVILKDGVR
P59591_A1_ala                            YGGRMDFQIKFNGYRIELEDVSQNLNKSQYVKSAVAVPRYNKDHKVQNLLAYIVLKEGVR
P68876_A1_ala                            IQGRIDFQIKLNGYRMELEEIETQLRQSEFVKEAIVVP-VYKNDKVIHLIGAIVPTTEV-
P35854_A1_ala                            YRGRTDFQVKLHGYRIELEDVDHNLNQVSYIKQASTVPRYDKDHKVAQLIAFAVAKPND-
P39581_A1_ala                            CQGRLDFQIKLHGYRMELEEIEFHVRQSQYVRSAVVIP-YQPNGTVEYLIAAIVPEEHE-
Q53526_A1_ala                            YGGRMDFQIKFNGYRIELEEVSQNLNKSQYIASAVAVPRYNKDHKVQNLLAYVVLKDGVE
P68878_A1_ala                            IQGRIDFQIKLNGYRMELEEIETQLRQSEFVKEAIVVP-VYKNDKVIHLIGAIVPTTEV-
                                           ** ***:*::***:***::. ::.:  :: .* .:*    : .*  *:.  :      

P0A398_A1_ala                            EQ
P59591_A1_ala                            DD
P68876_A1_ala                            --
P35854_A1_ala                            --
P39581_A1_ala                            --
Q53526_A1_ala                            EQ
P68878_A1_ala                            --
                                           
