CLUSTAL W multiple sequence alignment


O68008_A5_12__asn                        SGAAIILADHKQDLGT-LHQ-EAVELTGDF----------------SSYPA---------
Q9R9I9_A2_asn                            SKTEIVLTQSHLQQRL-AHE-GTIVLLDDE----------------NSYHK---------
Q93I55_A2_asn                            SQAGIVLMQQDVRKQL-AYE-GVTVLLDDE----------------SSYHQ---------
BGC0001125_AIW82277.1_525_mod1_asn       SQVPLLLTQSHLLDIL-PEEVNRILCLDSDWQAIAHQSTDNVFS----------------
Q70JZ8_A1_asn                            SRAEVVLTQRSLLDQL-PYD-GDVVLLDEE----------------NSYHE---------
Q9R9J0_A2_asn                            SKAGIILMPRDVRQQI-TYE-GVVILLDEE----------------SSYHE---------
Q93I54_A1_asn                            SQADIVLTQSHLQKQL-ELA-GTMVFLDQE----------------SSYHE---------
Q9R9J1_A1_asn                            SEAKIVLAQLDLHKHL-TFD-ADVVLLDEE----------------SSYHE---------
Q70JZ9_A2_asn                            SQAGIVLMQRDVRKQL-AYE-GVTVLLDDE----------------GSYHQ---------
BGC0001125_AIW82284.1_1365_mod2_asn      SQVSVLLTQSHLLDIL-PEG-NSIFCLDTDWQLIAQQGTENVSSLGTRYEEIGVLRTAKT
Q93I56_A1_asn                            SRAEVVLTQRSLLDQL-PYD-GDVVLLDEE----------------NSYHE---------
Q70C44_A1_asn                            SQARLVLVDDEGQGRLDELELGAMTAVDVC----------------GTLDG---------
Q6YK40_A2_asn                            SQAGIVLMQRDVRKQL-AYE-GVTVLLDDE----------------SSYHQ---------
Q6YK41_A1_asn                            SRAEVVLTQRSLLDQL-PYD-GDIVLLDEE----------------NSYHE---------
O33743_A1_5__asn                         SQTTLLLTQSHLQPNI-RFA-GSVLYLDDR----------------SLYEG---------
                                         * . ::*                    .                                

O68008_A5_12__asn                        ------D--NLEPAGNADSLAYIIYTSGSTGKPKGVMIRQRGLVNYITWADRVYVQGEQL
Q9R9I9_A2_asn                            ------ERSNLERISNIKDLAYVIYTSGSTGKPKGVLIEHQGLTNYIWWADRVYVKGEKT
Q93I55_A2_asn                            ------DGSDLAPINDVSHLAYVIYTSGSTGRPKGVLIEHGGLTNYIWWAKEVYVKGEKA
BGC0001125_AIW82277.1_525_mod1_asn       -------------QVQPQNLAYIIYTSGSTGEPKGTMIRHQGVVNYLSWCTQAYAVADGC
Q70JZ8_A1_asn                            ------EHSNLESDSDAHDLAYMIYTSGSTGNPKGVLIEHQGLADYIWWAKEVYVRGEKT
Q9R9J0_A2_asn                            ------EAFNLEPLSNANHLAYVIYTSGSTGKPKGVLIEHRGLSNYIWWAKEVYVKNEKT
Q93I54_A1_asn                            ------DGSYLEPISSTKDLAYVIYTSGSTGKPKGVAIEHQGLTNYIWWARRVYVKGEKT
Q9R9J1_A1_asn                            ------DRSNLEPTCGANDLAYMIYTSGSTGNPKGVLIEHRGLANYIEWAKEVYVNDEKT
Q70JZ9_A2_asn                            ------DGSDLAPINDASHLAYVIYTSGSTGRPKGVLIEHRGLTNYIWWAKEVYVKGEKA
BGC0001125_AIW82284.1_1365_mod2_asn      PRTPRNERRCVSPEVESSNLAYIIYTSGSTGQPKGTMIQHQGVVNYLSWCTQAYAIADGC
Q93I56_A1_asn                            ------EHSNFESDSDAHDLAYMIYTSGSTGNPKGVLIEHQGLADYIWWAKEVYVRGEKT
Q70C44_A1_asn                            ------DEANLDLPCDPAQPVYCIYTSGSTGSPKGVLVRHSGLANYVAWAKRQYVTADTT
Q6YK40_A2_asn                            ------DGSDLAPINDVSHLAYVIYTSGSTGRPKGVLIEHGGLTNYIWWAKKVYVKGEKA
Q6YK41_A1_asn                            ------DHSNLESDSDAHDLAYMIYTSGSTGNPKGVLIEHQGLANYIWWAKEVYVRGEKT
O33743_A1_5__asn                         ------GSTSFAPESKPDDLAYMIYTSGSTGNPKGAMITHQGLVNYIWWANKVYVQGEAV
                                                             .* ******** ***. : : *: :*: *. . *.  :  

O68008_A5_12__asn                        DFALYSSIAFDLTVTSIFTPLISGNRVIVYRHSEDGEPLIRKVFRDQKAGIVKLTPSHLS
Q9R9I9_A2_asn                            TFPLYSSIAFDLTVTSIFTPLISGNAIIVYG-DKDRTTLLSSIIEDSRVDIIKLTPAHLQ
Q93I55_A2_asn                            NFPLYSSISFDLTVTSIFTPLVTGNAIIVYD-GEDKTALLESIVRDPRVDIIKLTPAHLQ
BGC0001125_AIW82277.1_525_mod1_asn       GAPVQSSFAFDATITSIFSPLMVGGQVVLLPEKQEIEALCDVLRSRRRFSLVKLTPAHLE
Q70JZ8_A1_asn                            NFPLYSSISFDLTVTSIFTPLVTGNTIIVFD-GEDKSAVLSEIMRDSRIDMIKLTPAHLH
Q9R9J0_A2_asn                            NFPLYSSISFDLTVTSIFTPLVTGNTIIVYD-GEDKTALLSSIVQDQRVDIIKLTPAHLH
Q93I54_A1_asn                            NFPLYSSIAFDLTITSVFTPLITGNAIIVYG-GENSTALLDSIIQDSRADIIKLTPAHLQ
Q9R9J1_A1_asn                            NFPLYSSISFDLTVTSIFTPLVTGNTIIVFD-GEDKSAVLSTIMQDPRIDIIKLTPAHLH
Q70JZ9_A2_asn                            NFPLYSSISFDLTVTSIFTPLVTGNAIIVYD-GEDKTALLESIVRDPRVDIIKLTPAHLQ
BGC0001125_AIW82284.1_1365_mod2_asn      GAPVQSSFAFDATITSIFSPLIVGGQVVLLPEKQEIEALCEVLRGRHQFSLVKLTPAHLE
Q93I56_A1_asn                            NFPLYSSISFDLTVTSIFTPLVTGNTIIVFD-GEDKSAVLSEIMRDSRIDMIKLTPAHLH
Q70C44_A1_asn                            SFAFYSSLSFDLTVTSIYVPLVAGLCVHVYPEQGDDVPVINRVLDDNQVDVIKLTPSHML
Q6YK40_A2_asn                            NFPLYPSISFDLTVTSNFTPLVTGNAIIVYD-GEDKTALLESIVRDPRVDIIKLTPAHLQ
Q6YK41_A1_asn                            NFPLYSSISFDLTVTSIFTPLVTGNTIIVFD-GEDKSAVLSEIMRDSRIDMIKLTPAHLH
O33743_A1_5__asn                         DFPLYSSISFDLTVTSIFTPLLSGNTIHVYR-GADKVQVILDIIKDNKVGIIKLTPTHLK
                                           .. .*::** *:** : **: *  : :     :   :   :    : .::****:*: 

O68008_A5_12__asn                        LVKDMD-ASG--SSIKRLIVGGEDLKTELAKEIT--ERFHHNIEIYNEYGPTETVVGCMI
Q9R9I9_A2_asn                            LLKEMNISPE--CTIRKMIVGGDNLSTRLAQNIS--EQFQDQIEIFNEYGPTETVVGCMI
Q93I55_A2_asn                            VLKEMNIADQ--MAVRRMIVGGENLSTRLARSIH--EQFEGRIEICNEYGPTETVVGCMI
BGC0001125_AIW82277.1_525_mod1_asn       LLNQLLLPEELPESTQALVIGGEAL---LGKTLQFWQQYAPNIRLINEYGPTETVVGCCI
Q70JZ8_A1_asn                            VIKEMNIAGG--TAIRKMIVGGENLSTRLAKSVS--EQFKGRLDIFNEYGPTEAVVGCMI
Q9R9J0_A2_asn                            VLKAMNIANK--IAIRKMIVGGENLSTQLAQSIH--EQFDGQIEICNEYGPTETVVGCML
Q93I54_A1_asn                            LLKEINIPAE--CTIRKFIVGGDNLSTRLARSIS--GKFGGKIEIFNEYGPTETVVGCMI
Q9R9J1_A1_asn                            VLKEMKIADG--TTIRKMIVGGENLSTRLAQSVS--EQFKGQLDIFNEYGPTEAVVGCMI
Q70JZ9_A2_asn                            VLKEMNIADQ--TAVRRMIVGGENLSTRLARSIH--EQFEGRIEICNEYGPTETVVGCMI
BGC0001125_AIW82284.1_1365_mod2_asn      LLNQLLLPEELPESAQALVIGGEAL---LGKTLQFWQQYAPNTRLINEYGPTETVVGCCI
Q93I56_A1_asn                            VIKEMNIAGD--TAIRKMIVGGENLSTRLAKSVS--EQFKGRLDIFNEYGPTEAVVGCMI
Q70C44_A1_asn                            MLRNAALAT---SRLKTLIVGGEDLKAAVAYDIH--QRFRRDVAIYNEYGPTETVVGCAI
Q6YK40_A2_asn                            VLKEMNIADQ--TAVRRMIVGGENLSTRLARSIH--EQFEGRIEICNEYGPTETVVGCMI
Q6YK41_A1_asn                            VIKEMNIAGG--TAIRKMIVGGENLSTRLAKSVS--EQFKGRLDIFNEYGPTEAVVGCMI
O33743_A1_5__asn                         LIEHID-GKA--SSIRRFIVGGENLPTKLAKQIY--DHFGENVQIFNEYGPTETVVGCMI
                                         ::.            : :::**: *   :.  :    ::     : *******:**** :

O68008_A5_12__asn                        YQYDAGWDRQVSVPIGKPASNVQLYILDERQEVQPVGIAGELYISGDGVAKGYLNKPELT
Q9R9I9_A2_asn                            YLYDPKKDRQESVPIGTAAANMNIYLLDTGMKPVPIGVPGEMYISGAGVARGYLNRPDLT
Q93I55_A2_asn                            YRYDPAKDRRESVPIGTAAANTSIYVLDENMKPAPIGVPGEIYISGAGVARGYLNRPELT
BGC0001125_AIW82277.1_525_mod1_asn       YEVTPETSLTEGILIGRPIANTQLYILDQFWQPVPIGVRGELYIGGAGVARGYLNRPELT
Q70JZ8_A1_asn                            YQFDAERDKREFVPIGTPAANTDIYVADASRNLVPIGVIGEIYISGPGVARGYWNRPDLT
Q9R9J0_A2_asn                            YRYDAVKDRRESVPIGTAAANTSIYVLDEDMKPVPIGVPGEMYISGAGVARGYLNRPELT
Q93I54_A1_asn                            YSFDPQNDRRESVPIGTAADNMNIFVLDKSMKPVPAGVPGEIYISGDGIARGYLNRAELT
Q9R9J1_A1_asn                            YRYDTKRDRREFVPIGSPAANTSIYVLDASMNLVPVGVPGEMYIGGAGVARGYWNRPDLT
Q70JZ9_A2_asn                            YRYDAAKDRRESVPIGTAAANTSIYVLDENMKPAPIGVPGEIYISGAGVARGYLNRPELT
BGC0001125_AIW82284.1_1365_mod2_asn      YEVTPETSLTEKILIGRPIANTQLYILDSHLQPLPIGVGGELYIGGAGVARGYLNRPELT
Q93I56_A1_asn                            YHFDAVRDKREFVPIGTPAANTDIYVADASRNLVPIGVIGEIYISGPGVARGYWNRPDLT
Q70C44_A1_asn                            HRYDPATEREGSVPIGVPIDHTSLHLLDERLQPVAPGEVGQIHIGGAGVAIGYVNKPEIT
Q6YK40_A2_asn                            YRYDAAKDRRESVPIGTAAANTSIYVLDENMKPAPIGVPGEIYISGAGVARGYLNRPELT
Q6YK41_A1_asn                            YHFDAERDKREFVPIGTPAANTDIYVADASRNLVPFGVIGEIYISGPGVARGYWNRPDLT
O33743_A1_5__asn                         YLYDPQTTTQESVPIGVPADNVQLYLLDASMQPVPVGSLGEMYIAGDGVAKGYFNRPELT
                                         :   .       : ** .  : .:.: *   :  . *  *:::*.* *:* ** *:.::*

O68008_A5_12__asn                        SEKFLPNPFL--PGERMYRTGDLAKMRPDGHIEYLGRIDHQVKIRGYRIELGEIEHQLLR
Q9R9I9_A2_asn                            AEKFVEHPFA--AGERMYKTGDAARWMPDGHMEYLGRIDHQVKVRGYRIELGEVEAALLL
Q93I55_A2_asn                            AEKFVDDLFE--PGAKMYKTGDLAKWLADGNIEYAGRIDEQVKIRGYRIELGEIEAALLQ
BGC0001125_AIW82277.1_525_mod1_asn       AERFIRNPFSNDSEARLYKTGDLARYRLDGNIEYLGRMDNQVKLRGFRIELGEIEAAIAK
Q70JZ8_A1_asn                            AEKFVENPYV--PGAKMYKSGDLAKRLKDGNLVYIGRVDEQVKIRGHRIELGEIEAAMHN
Q9R9J0_A2_asn                            AEKFVENPFV--TGERMYKTGDLAKWLPDGNIEYLGRMDEQVKIRGFRIELGEIETAMLQ
Q93I54_A1_asn                            AERFLQHPFV--PEVKMYRTGDLARRLPDGNIEYLGRIDHQVKIRGYRIEIGEVESAFFQ
Q9R9J1_A1_asn                            AEKFVHNPFA--PGTIMYKTGDLAKRLRDGNLIYLGRIDEQVKIRGHRIELGEVEAAMHK
Q70JZ9_A2_asn                            AEKFVDDPFE--PGAKMYKTGDLAKWLADGNIEYAGRIDEQVKIRGYRIELGEIEAALLQ
BGC0001125_AIW82284.1_1365_mod2_asn      AERFIRNPFRNDPEARLYKTGDLARYLPDGNIEYLGRIDNQIKLRGFRIELGEIENALAQ
Q93I56_A1_asn                            EEKFVENPYV--PGAKMYKSGDLAKRLKDGNLVYIGRVDEQVKIRGHRIELGEIEAAMHN
Q70C44_A1_asn                            DAQFIDNPFE--GSGRLYASGDLGRMRADGKLEFLGRKDSQIKLRGYRIELGEIENVLLG
Q6YK40_A2_asn                            AEKFVDDPFE--PGAKMYKTGDLAKWLADGNIEYAGRIDEQVKIRGYRIKLGEIEAALLQ
Q6YK41_A1_asn                            AEKFVENPYV--PGAKMYKSGDLAKRLKDGNLLYIGRVDEQVKIRGHRIELGEIEAAMHN
O33743_A1_5__asn                         KEKFIDNPFR--PGTKMYRTGDLAKWLPDGNMEYAGRMDYQVKIRGHRIEMGEIETRLTQ
                                           :*: . :       :* :** .:   **:: : ** * *:*:**.**::**:*  :  

O68008_A5_12__asn                        HSDIKEAAV--AAKTDQNNDQVLCAYVVSERDITQKD-
Q9R9I9_A2_asn                            VESVKEAVV--IAVEE-EGSNQLCAYVTGDESLKTLQ-
Q93I55_A2_asn                            EEAIKEAVV--TAREDVHGFKQLCAYYVSGGQTTAAR-
BGC0001125_AIW82277.1_525_mod1_asn       YPEVRETVV--IIREDIPSDKRLVAYVV-----PNSQD
Q70JZ8_A1_asn                            AEAVQKAAV--TVKEEEDGLKQLCAYYVSDKPIAAAQ-
Q9R9J0_A2_asn                            AEEIKEAVV--TAREDVHGLKQLCGYYVSSQPITVSQ-
Q93I54_A1_asn                            IPPIQEALV--TAQET-NGETSLCAYYTAQHSLTAGE-
Q9R9J1_A1_asn                            VEAVQKAVV--LAREEEDGLQQLCAYYVSNKPITIAE-
Q70JZ9_A2_asn                            EEAIKEAVV--TAREDVHGFKQLCAYYVSGGQTTAAR-
BGC0001125_AIW82284.1_1365_mod2_asn      HPQVRETAV--LLREDISGDKRLIAYFVADTEAPTSSD
Q93I56_A1_asn                            AEAVQKAAV--TVKEEEDGLKQLCAYYVSDKPIAAAQ-
Q70C44_A1_asn                            HAALRECIVDTTVAPRRDYDSKSLRY------------
Q6YK40_A2_asn                            KKAIKEAVV--TAREDVHRFKQLCAYYVSGGQTTAAR-
Q6YK41_A1_asn                            AEAVQKAAV--TVKEEEDGLKQLCAYYVSDKPIAAAQ-
O33743_A1_5__asn                         HEAVKEAVV--IVEKDESGQNVLYAYLVSERELTVAE-
                                            :::  *                *            
