CLUSTAL W multiple sequence alignment


BGC0001125_AIW82284.1_1365_mod2_asn      SQVSVLLTQSHL-------------LDILPEG-NSIFCLDTDWQLIAQQGTENVSSLGTR
Q9RAH2_A3_asn                            CGAKVLLTHSQLKLGAGDWGSGTGNKETFPQS-PSILYLDRD--NFANQSTENPSR----
BGC0001125_AIW82277.1_525_mod1_asn       SQVPLLLTQSHL-------------LDILPEEVNRILCLDSDWQAIAHQSTDNVFS----
                                         . . :***:*:*              : :*:    *: ** *   :*:*.*:*       

BGC0001125_AIW82284.1_1365_mod2_asn      YEEIGVLRTAKTPRTPRNERRCVSPEVESSNLAYIIYTSGSTGQPKGTMIQHQGVVNYLS
Q9RAH2_A3_asn                            -------------------------QSQPDDLAYVIYTSGSTGKPKGVQLPHRGLSNYLH
BGC0001125_AIW82277.1_525_mod1_asn       -------------------------QVQPQNLAYIIYTSGSTGEPKGTMIRHQGVVNYLS
                                                                  : :..:***:********:***. : *:*: *** 

BGC0001125_AIW82284.1_1365_mod2_asn      WCTQAYAIADGCGAPVQSSFAFDATITSIFSPLIVGGQVVLLPEKQEIEALCEVLRGRHQ
Q9RAH2_A3_asn                            WAKDYYAVAQGQGTPVQSSLSFDATITSLYLPLICGRTTILVREKQELQLLADIVKQNNH
BGC0001125_AIW82277.1_525_mod1_asn       WCTQAYAVADGCGAPVQSSFAFDATITSIFSPLMVGGQVVLLPEKQEIEALCDVLRSRRR
                                         *..: **:*:* *:*****::*******:: **: *  .:*: ****:: *.:::: ..:

BGC0001125_AIW82284.1_1365_mod2_asn      FSLVKLTPAHLELLNQLLLPEELPESAQALVIGGEALLGKTLQFWQQYAPNTRLINEYGP
Q9RAH2_A3_asn                            LSLVKITPSHLEILNQQIEPDTMPNRVNAFVLGGEALHANQIIPWLTHAPDTRLINEYGP
BGC0001125_AIW82277.1_525_mod1_asn       FSLVKLTPAHLELLNQLLLPEELPESTQALVIGGEALLGKTLQFWQQYAPNIRLINEYGP
                                         :****:**:***:*** : *: :*: .:*:*:***** .: :  *  :**: ********

BGC0001125_AIW82284.1_1365_mod2_asn      TETVVGCCIYEVTPETSLTEKILIGRPIANTQLYILDSHLQPLPIGVGGELYIGGAGVAR
Q9RAH2_A3_asn                            TEAVVGCCVYEATGKRDLAGDLLIGQPIANVRIYILDNQNQLLPVGIPGELCIAGAGLAR
BGC0001125_AIW82277.1_525_mod1_asn       TETVVGCCIYEVTPETSLTEGILIGRPIANTQLYILDQFWQPVPIGVRGELYIGGAGVAR
                                         **:*****:**.* : .*:  :***:****.::****.  * :*:*: *** *.***:**

BGC0001125_AIW82284.1_1365_mod2_asn      GYLNRPELTAERFIRNPFRNDPEARLYKTGDLARYLPDGNIEYLGRIDNQIKLRGFRIEL
Q9RAH2_A3_asn                            GYLNRPELTAEKFIELDLFGKKE-RIYKTGDLARWLPDGNLEYLGRIDNQIKIRGFRIEL
BGC0001125_AIW82277.1_525_mod1_asn       GYLNRPELTAERFIRNPFSNDSEARLYKTGDLARYRLDGNIEYLGRMDNQVKLRGFRIEL
                                         ***********:**.  : .. * *:********:  ***:*****:***:*:*******

BGC0001125_AIW82284.1_1365_mod2_asn      GEIENALAQHPQVRETAVLLREDISGDKRLIAYFVADTE-APTSSD
Q9RAH2_A3_asn                            GEIEALLNQHDDVQASVVTAREDTPGDKRLIAYVVPHQHCTPTINE
BGC0001125_AIW82277.1_525_mod1_asn       GEIEAAIAKYPEVRETVVIIREDIPSDKRLVAYVV------PNSQD
                                         ****  : :: :*: :.*  *** ..****:**.*      *. .:
