CLUSTAL W multiple sequence alignment


O69246_A2_5__asp                         SGVRWLLTEPSHQADLADWYTGRLIDVRKDTLM-ASNKRPHPTTDGASLAYIIYTSGTTG
O68008_A4_11__asp                        SRAAILLVKGSVKENVA--FAGEIVNVADGLIDAKVASNLSASGSADQNAYIIYTSGSTG
Q70KJ6_A2_5__asp                         SGTKLLVVNERNMTAAAV-YKGNTVVMEDGEWQNESADRLETEPGFDQLAYIIYTSGTTG
Q04747_A2_5__asp                         SGAKFAVVNERNMTAIGQ-YEGIIVSLDDGKWRNESKERPSSISGSRNLAYVIYTSGTTG
                                         * .   :.:       .  : *  : : ..       ..  .  .  . **:*****:**

O69246_A2_5__asp                         RPKGVQLEHRNLANYVSWFISEAHLSASDKTMLLSSYAFDLGYTSFFPVLLAGGELHIVP
O68008_A4_11__asp                        KPKGVFVRHGNVVNYTTWFMKEAGLTENDKAMLVSSYAFDLGYTSIFSALLSGSELHIAR
Q70KJ6_A2_5__asp                         KPKGVQLEHRNLINYVTWFSREAGLTEADKSVLLSSYAFDLGYTAIFPILQAGGELHIVP
Q04747_A2_5__asp                         KPKGVQIEHRNLTNYVSWFSEEAGLTENDKTVLLSSYAFDLGYTSMFPVLLGGGELHIVQ
                                         :**** :.* *: **.:**  ** *:  **::*:**********::*. * .*.****. 

O69246_A2_5__asp                         KETYTEPEAFTHYIGEQGITYMKLTPSLFHTVVQPQSFALAKGLQSLRLIVLGGEKINPK
O68008_A4_11__asp                        KECYTNAHRALKYIKENGITYIKLTPSLFNIFVNDPGFSAEKPCATLRLVVLGGEMINTR
Q70KJ6_A2_5__asp                         KETYTAPDQLGEYIQKNGITYMKLTPSLFHMIVNTARFAAERRFSPLRLVVLGGEKIITS
Q04747_A2_5__asp                         KETYTAPDEIAHYIKEHGITYIKLTPSLFHTIVNTASFAKDANFESLRLIVLGGEKIIPT
                                         ** ** ..   .** ::****:*******: .*:   *:      .***:***** * . 

O69246_A2_5__asp                         DVERFHSRYPDTRFINHYGPTETTIGAIAKPVEPDMIGQFAERPTIGRPISGAGALVLDA
O68008_A4_11__asp                        DVETFYNQYPDHVVMNHYGPTETTIGSVFKVIDPEHLDSFKECPVIGTPIHNTNAYVLDE
Q70KJ6_A2_5__asp                         DVRKFHDVYAHTDFINHYGPTETTIGAIAGRINMERLDQYEQRPVIGRPIANTGALVLDG
Q04747_A2_5__asp                         DVIAFRKMYGHTEFINHYGPTEATIGAIAGRVDLYEPDAFAKRPTIGRPIANAGALVLNE
                                         **  * . * .  .:*******:***::   ::    . : : *.** ** .:.* **: 

O69246_A2_5__asp                         SRRLVPAGAAGELYITGSGLARGYVNNRELTAAKFVENPYTPGTFMYRTGDLVRRLPNGE
O68008_A4_11__asp                        NMKLLPEGVYGELCIAGAGVTGGYVNRPDETKEKFIENPFAPHTKMYRTGDLARRLSDGN
Q70KJ6_A2_5__asp                         AMQLVPPGASGELYIAGKGLARGYLHRPQLTAEKFLSNPFSPDSLMYKTGDVVRRLPDGT
Q04747_A2_5__asp                         ALKLVPPGASGQLYITGQGLARGYLNRPQLTAERFVENPYSPGSLMYKTGDVVRRLSDGT
                                           :*:* *. *:* *:* *:: **::. : *  :*:.**::* : **:***:.***.:* 

O69246_A2_5__asp                         IEFLGRTDDQVKIRGYRIELKEIEEAFNELDDIERAIVLSFTTDSGLDELCAYIQAKRQL
O68008_A4_11__asp                        IELAGRIDTQVKVRGYRIEPEEIKNRLLAHDDIKEAFIAAREDHKGAKQLCAYFTADAEL
Q70KJ6_A2_5__asp                         IEFIGRADDQVKIRGYRIELKEVETVLLSVNGIQEAVVLA-VSEGGLPELCAYYKADSEL
Q04747_A2_5__asp                         LAFIGRADDQVKIRGYRIEPKEIETVMLSLSGIQEAVVLA-VSEGGLQELCAYYTSDQDI
                                         : : ** * ***:****** :*::  :   ..*:.*.: :   . *  :****  :. ::

O69246_A2_5__asp                         PVSE
O68008_A4_11__asp                        PFED
Q70KJ6_A2_5__asp                         KGSE
Q04747_A2_5__asp                         EKAE
                                            :
