CLUSTAL W multiple sequence alignment


Q9Z4X6_A4_asp                            ARPALTLTEPVPVERYTGHSVTAVTDEERRSPWSARHAAYMIYTSGSTGRPKGVVIEHHA
Q9Z4X5_A1_asp                            ARPALTLREPVPAAAYGHRPTDDVTDAERRTPWSALHAAYMIYTSGSTGRPKGVVIEHHA
Q9Z4X6_A5_asp                            AQPALTLTAPIPPASYDSRPTSEITDVERRSPWSARHAAYMIYTSGSTGRPKGVVIEHHA
Q9Z4X5_A1_7__asp                         ARPALTLREPVPAAAYGHRPTDDVTDAERRTPWSALHAAYMIYTSGSTGRPKGVVIEHHA
                                         *:*****  *:*   *  :..  :** ***:**** ************************

Q9Z4X6_A4_asp                            LATYLHRARNTYTAMTGVTVLHSPLAFDLTITALWTPLTSGGTVHLTSLEESDTQPSLIK
Q9Z4X5_A1_asp                            LATYLHRARNTYTAMTGVTVLHSPLAFDLTITALWTPLTAGGTVHLTSLEEAEVQPSLIK
Q9Z4X6_A5_asp                            LATYLHRARNTYTAMTGVTVLHSPLAFDLTITALWTPLTAGGTVHLTSLEEAEVQPSLIK
Q9Z4X5_A1_7__asp                         LATYLHRARNTYTAMTGVTVLHSPLAFDLTITALWTPLTAGGTVHLTSLEEAEVQPSLIK
                                         ***************************************:***********::.******

Q9Z4X6_A4_asp                            ATPSHLPLLTTLPETASPSHTLILGGEALHTDHLVTWRTQHPGVQIINAYGPTESTVNIT
Q9Z4X5_A1_asp                            ATPSHLPLLTNLAATASPSHTLILGGEALHTDQLTDWRTQHPGAQIINAYGPTESTVNIT
Q9Z4X6_A5_asp                            ATPSHLPLLTTLPETASPSHTLILGGEALHTDHLATWRTQHPGAQIINAYGPTESTVNIT
Q9Z4X5_A1_7__asp                         ATPSHLPLLTNLAATASPSHTLILGGEALHTDQLTDWRTQHPGAQIINAYGPTESTVNIT
                                         **********.*. ******************:*. *******.****************

Q9Z4X6_A4_asp                            DHHVGEDTPDGPVPIGRPFANTQVYVLDSALRPVAPGVTGELYLAGEQLARGYLGRPALT
Q9Z4X5_A1_asp                            DHRL-DGTEEGPVPIGRPFANTQVYVLDSALRPVAPGTTGELYLAGEQLARGYLGRPALT
Q9Z4X6_A5_asp                            DHHVSEDTPDGPVPIGRPFANTQVYVLDSALRPVAPGVTGELYLAGEQLARGYLGRPALT
Q9Z4X5_A1_7__asp                         DHRL-DGTEEGPVPIGRPFANTQVYVLDSALRPVAPGTTGELYLAGEQLARGYLGRPALT
                                         **:: :.* :***************************.**********************

Q9Z4X6_A4_asp                            AERFTANPHSSTPGARMYRTGDLAHWNHHGHLTYDGRADHQIKLRGHRIEPGEIEATLTA
Q9Z4X5_A1_asp                            AERFTANPHSSVPGARMYRTGDLAHWNHHGHLTYDGRADHQIKLRGHRIEPGEIETTLTA
Q9Z4X6_A5_asp                            AERFTANPHSSTPGARMYRTGDLAHWNHDGHLTYDGRADHQIKLRGHRIEPGEIETTLTA
Q9Z4X5_A1_7__asp                         AERFTANPHSSVPGARMYRTGDLAHWNHHGHLTYDGRADHQIKLRGHRIEPGEIETTLTA
                                         ***********.****************.**************************:****

Q9Z4X6_A4_asp                            QTGITQATVQLREDQPGDQRLVAYLVVNDSTEYDEKT
Q9Z4X5_A1_asp                            QTGITQATVQLREDQPGDQRLVAYLVT--STGYDENT
Q9Z4X6_A5_asp                            QTGITQTTVQLREDTPGDQRLVAYLVVNDSTEYDEPT
Q9Z4X5_A1_7__asp                         QTGITQATVQLREDQPGDQRLVAYLVT--STGYDENT
                                         ******:******* ***********.  ** *** *
