CLUSTAL W multiple sequence alignment


Q939Z0_A3_6__bht                         SAPGVMVCTKTTRAAVPAEFAGTVLVLDELPAADPDVELPPVAPEDAAYVIYTSGSTGVP
Q70AZ7_A3_bht                            AAPQVLVCTARTRSVVPGDFAGAVLALDEPSAAGPQVSLPRVAARDGAYVIYTSGSTGVP
BGC0000419_AIG79241.1_3410_mod3_bht      SAPQVLVCTAATRAVVPSTFDGEILMLEELPAADPAVVLPPVKPTDAAYVIYTSGSTGVP
BGC0000418_AHF20584.1_3410_mod3_bht      SAPQVLVCTAATRAVVPSTFDGEILMLDELPAADPAVVLPPVKATDAAYVIYTSGSTGVP
Q70AZ7_A3_6__bht                         AAPQVLVCTARTRSVVPGDFAGAVLALDEPSAAGPQVSLPRVAARDGAYVIYTSGSTGVP
Q8KLL5_A3_6__bht                         SAPEVLLCTKATRTAVPDGFAGVVVVLDERSAADPGAALPAVAVGDGAYVIYTSGSTGTP
Q8KLL5_A3_bht                            SAPEVLLCTKATRTAVPDGFAGVVVVLDERSAADPGAALPAVAVGDGAYVIYTSGSTGTP
                                         :** *::**  **:.**  * * :: *:* .**.* . ** *   *.***********.*

Q939Z0_A3_6__bht                         KGVLVTHSGLANLGYAHIERMAVTSSSRVLQLSATGFDAIVSELYMALLAGATLVLPDAA
Q70AZ7_A3_bht                            KGVLVTHAGLGNLASAQIERFGVTSSSRVLQFAALGFDAAISEVCMALLSGGSIVLADAE
BGC0000419_AIG79241.1_3410_mod3_bht      KGVMVTHSGLGNLATAHIERLGVTSSSRVLQLSAIGFDAIVSELYMSLLAGATLVLAGAE
BGC0000418_AHF20584.1_3410_mod3_bht      KGVMVTHSGLGNLATAHIERLGVTSSSRVLQLSAIGFDAIVSELYMSLLAGATLVLADAE
Q70AZ7_A3_6__bht                         KGVLVTHAGLGNLASAQIERFGVTSSSRVLQFAALGFDAAISEVCMALLSGGSIVLADAE
Q8KLL5_A3_6__bht                         KGVQVTHAGLGNLAGAQIERFGVTSSSRVLQFASLGFDAAISELCMALLSGGTVVLADPD
Q8KLL5_A3_bht                            KGVQVTHAGLGNLAGAQIERFGVTSSSRVLQFASLGFDAAISELCMALLSGGTVVLADPD
                                         *** ***:**.**. *:***:.*********::: **** :**: *:**:*.::**... 

Q939Z0_A3_6__bht                         SMPPRVTLGEAIRRAGITHLTVSPSVLASEDDLPDTLRTVLTGGEALPPALVDRWSPGRR
Q70AZ7_A3_bht                            HMPPRVSLGDAVRRWDITHVTVPPSVLAVEDDLPDDL-TLIVAGEACPPALVDRWSPGRR
BGC0000419_AIG79241.1_3410_mod3_bht      TMPPRVTLGDALRRWGITHLTVSPSVLAVEEDLPDTLRGVLTGGEVCTPALVDRWSPGRR
BGC0000418_AHF20584.1_3410_mod3_bht      TMPPRVTLGDALRRWGITHLTVSPSVLAVEEDLPDTLRGVLTGGEVCTPALVDRWSPGRR
Q70AZ7_A3_6__bht                         HMPPRVSLGDAVRRWDITHVTVPPSVLAVEDDLPDDL-TLIVAGEACPPALVDRWSPGRR
Q8KLL5_A3_6__bht                         SMPPRVSLGDAVRRWRITHVTVPPSVLAVEEDLPDSLETLVVAGEACPPALVDRWSGDRR
Q8KLL5_A3_bht                            SMPPRVSLGDAVRRWRITHVTVPPSVLAVEEDLPDSLETLVVAGEACPPALVDRWSGDRR
                                          *****:**:*:**  ***:**.***** *:**** *  ::..**. .******** .**

Q939Z0_A3_6__bht                         VIQAYGPTETTICSTMSAPLSPGHDQVPLGGPIHNVRHYVLDAFLQPVPPGVVGELYITG
Q70AZ7_A3_bht                            MINGYGPTETTVCATMSSPLSPGRGAVPIGGPIANMRTYVLDAFLQPVPPGMTGELYVTG
BGC0000419_AIG79241.1_3410_mod3_bht      FINAYGPTETTICSTMSAPLSPGHEVVPLGGPIRNVKHYILDAYLQPVPPGVAGELYIAG
BGC0000418_AHF20584.1_3410_mod3_bht      FINAYGPTETTICSTMSAPLSPGHEVVPLGGPIRNVKHYILDAYLQPVPPGVTGELYIAG
Q70AZ7_A3_6__bht                         MINGYGPTETTVCATMSSPLSPGRGAVPIGGPIANMRTYVLDAFLQPVPPGMTGELYVTG
Q8KLL5_A3_6__bht                         MINGYGPTETTVCVTMSAPLSPGRDAPPIGRPIANMRAYVLDAFLQPVPPGVAGELYVTG
Q8KLL5_A3_bht                            MINGYGPTETTVCVTMSAPLSPGRDAPPIGRPIANMRAYVLDAFLQPVPPGVAGELYVTG
                                         .*:.*******:* ***:*****:   *:* ** *:: *:***:*******:.****::*

Q939Z0_A3_6__bht                         VGLARGYLGRPGLTAERFVASPFAPGERMYRSGDLFRWTREGQLLFAGRVDAQVKVRGYR
Q70AZ7_A3_bht                            VGLARGYLGRPGLTAERFVADPFSPGGRMYRTGDRARWTGDGELVFAGRVDAQVKVRGYR
BGC0000419_AIG79241.1_3410_mod3_bht      AGLARGYLGRPGLTSERFVADPFTPGERMYRSGDRFRWDPDGELIFVGRVDAQVKVRGYR
BGC0000418_AHF20584.1_3410_mod3_bht      AGLARGYLGRPGLTAERFVADPFTPGERMYRSGDRFRWDPDGELIFVGRVDAQVKVRGYR
Q70AZ7_A3_6__bht                         VGLARGYLGRPGLTAERFVADPFSPGGRMYRTGDRARWTGDGELVFAGRVDAQVKVRGYR
Q8KLL5_A3_6__bht                         AGLARGYLGRPGLTAERFVADPFSSGGRMYRTGDRARWTREGELVFVGRADAQVKVRGYR
Q8KLL5_A3_bht                            AGLARGYLGRPGLTAERFVADPFSSGGRMYRTGDRARWTREGELVFVGRADAQVKVRGYR
                                         .*************:*****.**:.* ****:**  **  :*:*:*.**.**********

Q939Z0_A3_6__bht                         VEPAEIEAVLAEHPWVGQVAVSVRRDGPGDKQLVAYVVPS--ADAAAENGT
Q70AZ7_A3_bht                            IEPGEIEAVLAEHPGVAQVVVVARQDGPGEKQLVAYVVPA--AGPTAEAST
BGC0000419_AIG79241.1_3410_mod3_bht      VEPAEIENVLAEHPGVAQAAVAVHRDGPGDKRLVAYVVPSDGADGS-----
BGC0000418_AHF20584.1_3410_mod3_bht      VEPAEIENVLAEHPGVAQAAVAVHRDGPGDKRLVAYVVPSDGADGS-----
Q70AZ7_A3_6__bht                         IEPGEIEAVLAEHPGVAQVVVVARQDGPGEKQLVAYVVPA--AGPTAEAST
Q8KLL5_A3_6__bht                         VEPGEIEAVLSDHPGAAQVVIVAREDGPGEKRLVAYVVPA--AAQPADEL-
Q8KLL5_A3_bht                            VEPGEIEAVLSDHPGAAQVVIVAREDGPGEKRLVAYVVPA--AAQPADEL-
                                         :**.*** **::** ..*..: .:.****:*:*******:  *  .     
