CLUSTAL W multiple sequence alignment


Q9KIZ9_A1_cys                            GEVKLVLTQPWLDGKLSWPP---GIQRLLVSDAGVEGDGDQLP-MMPIQ-----TPSDLA
CCA29203.1_2085_mod2_cys                 AGASLLLVSQAQYDDTEVRTQLGGRYRLLVIDELLARADEEAP----AQPLPQVDADAVA
Q6DNE7_A1_4__cys                         AQVTQVLTQTHLKQSLGWPE---GIKCWSVDTEELA-EYDPNP-LEPVQ-----TSEDLA
Q8GAQ3_A2_4__cys                         GEVKLVVTQAALNASLGLPD---HLHCLVVASQPQE-IID-TP-LEANV-----SSSDLA
Q70P97_A1_cys                            GQVKVALTEPRLAERLSWPE---DVEVVVVADIARG-----AA--LPERR---GSVTDLA
CCA29202.1_1497_mod2_cys                 ANTPVILASRAQLERDEIQA-LAGRYQLLDLDALVS-SEAQAPLASSEQTLPDVHPDDVA
O68006_A2_cys                            SNCKFFISHD-------------------VYDKEHIERFSKAP-VDRKV-----DLDDMA
Q9RFK9_A1_cys                            GQVKVVLTESHLAERLSWPA---SVRVVAIADTARG-----APPRLPAR-----AASDMA
Q9FB18_A2_cys                            AEAALLLTERALLDTLAVPV---GVTVLAVDDDAAL-DADGGP-LQSVQ-----NLTDLA
O85740_A1_3__cys                         AEVVALVCLES-----DVPD--VGCACVAIDRLAADSAWPPPP-------AAEVAADDLA
Q5MD35_A1_cys                            GKVRVVVTEPRLAERLSWPG---DVEVVVVADIARG-----VS--RPERR---GSASDLA
                                         .     :                                   .               :*

Q9KIZ9_A1_cys                            YVIYTSGSTGLPKGVMIDHRGAVNTILDINERFEIGPGDRVLALSSLSFDLSVYDVFGIL
CCA29203.1_2085_mod2_cys                 YVIFTSGSTGKPKGVTISHRGALNTIHAVNQRLAVSPTDKVLALSELSFDLSVYDLFGLL
Q6DNE7_A1_4__cys                         YVIYTSGSTGLPKGVMIDHRGAINTILDINQRFKVTPSDRVLALAALNFDLSVYDIFGVL
Q8GAQ3_A2_4__cys                         YVIFTSGSTGTPKGVMIDHRGAVNTIQDINQRFDVQPTDRMLAVSALNFDLSVYDIFGLL
Q70P97_A1_cys                            YCIYTSGSTGRPKGVMIDHRSAANTVQDINSRFQVGPEDRVFALSSLGFDLSVYDIFGAL
CCA29202.1_1497_mod2_cys                 YVIFTSGSTGKPKGVTISHRGAVNTIDAINSRFKVSSRDSVLALSELSFDLSVYDLFGVL
O68006_A2_cys                            YVIFTSGSTGKPKGVQITHVPQRNTILDINEKFNVTEQDNIMGISSLCFDLSVYDVFGAL
Q9RFK9_A1_cys                            YCIYTSGSTGRPKGVKIEHRAAANTILDINERFGVGPADRVFALSSLGFDLSVYDIFGSL
Q9FB18_A2_cys                            YTIFTSGSTGEPKGVMIDHLGAANTLECVNRRFGTGPGDAVLAVSSPSFDLAVYDLFGVL
O85740_A1_3__cys                         YVIYTSGSTGTPKGVMLSHAAVSNTLLDINQRYGVDANDRVLGLAELSFDLSVYDFFGAT
Q5MD35_A1_cys                            YCIYTSGSTGRPKGVMIEHRAAANTLLDINARFQVGPEDRIFALSSLGFDLSVYDIFGAL
                                         * *:****** **** : *    **:  :* :      * ::.::   ***:***.**  

Q9KIZ9_A1_cys                            AAGGTIVVPDASKLRDPAHWAALIEREKVTVWNSVPALMRMLVEHSEGRPDSLARSLRLS
CCA29203.1_2085_mod2_cys                 AAGGQVVFTPPRATKDPSAWLEAIEREQVTLWNTVPQLAGLLVDAMKHGGKTSS-SLRAF
Q6DNE7_A1_4__cys                         GAGGAIVMPPPKAAKDPACWRELIIAHEVTLWNSVPALMQMLVEHLLGTSATAVGDLRVV
Q8GAQ3_A2_4__cys                         AAGGTLVMPTPEAAKDPVHWVELMTTHQVTLWNTVPALMQMLVEYLSEHPDQVTEDLRLA
Q70P97_A1_cys                            AVGAAFVLPESEATKDPASWLNLLRTHRVSVWNSVPTLMEMLVDVAETRGERLPDSLRLV
CCA29202.1_1497_mod2_cys                 AAGGNIVFPIQAETKNPAHWLEFVEKHGITLWNTVPQLAGLLLDEASGSTGRLA-SLRLF
O68006_A2_cys                            SSGASLVIIDDQ--RDVFSLKETAEKERITIWNSVPAIMGMTADVYPD--NELNHHLRLI
Q9RFK9_A1_cys                            AAGAAIVLPQPEVTRDPAHWLQVLRQQGVTIWNSVPTLMEMLVDQVEARGELLPETLRLV
Q9FB18_A2_cys                            AAGGTVVVPAHDRRRDPGHWAELIRRERVTLWNSVPALGTLLTEYAEALAPDALRTLRAV
O85740_A1_3__cys                         AAGAQVVLPDPARGSDPSHWAELLERHAITLWNSVPAQGQMLIDYLESEPQRHLPGPRCV
Q5MD35_A1_cys                            AAGAALVLPETEATRDPARWLRLLRAHRVSVWNSVPTLMEMLVDVAETRGERLPDSLRLV
                                         . *. .*.       :          . :::**:**    :  :             *  

Q9KIZ9_A1_cys                            LLSGDWIPVGLPGELQAIRP-GVSVISLGGATEASIWSIGYPVRNVDPSWASIPYGRPLR
CCA29203.1_2085_mod2_cys                 MLSGDWIPTRLPEQLRALAP-NAEVLSMGGATEGSIWSIWYPVETVPAEWTSIPYGVAMP
Q6DNE7_A1_4__cys                         MLSGDWLPVDLPSKIQSLWS-NVQVMSLGGATEASIWSIGYPIEKVGSDWKSIPYGKPLL
Q8GAQ3_A2_4__cys                         LLSGDWIPLNLPTQIQSLWP-QGQVVSLGGATEASIWSVYYPITTVEPEWKSIPYGKPLV
Q70P97_A1_cys                            MMSGDWIPVTLPDRIRRLARGDIQIISLGGATEGSVWSILHPIGQVEPTARSIPYGRPML
CCA29202.1_1497_mod2_cys                 LLSGDWIPTSLPGRIRGQCP-NSLVMSLGGATEGSIWSIWYEIAQVDPSWSSIPYGTAMP
O68006_A2_cys                            LLSGDWIPLQLPATIKKTFK-NAEVISLGGATEGSIWSIYYPIQKVEEDWKSIPYGKPLA
Q9RFK9_A1_cys                            MLSGDWIPVTLPDRIRRLSR-DIRVISLGGATEASIWSIIHPIGRVDPAARSIPYGRPML
Q9FB18_A2_cys                            LLSGDWIPLGLPDRIRALSAPGATVMSLGGATEASIWSVWYEIGKVHEAWSSIPYGTPMA
O85740_A1_3__cys                         LWSGDWIPVSLPTRWWRRWP-DSAAVQPGRRTEAAIWSIEQPIRPQHTELASIPYGRALR
Q5MD35_A1_cys                            MMSGDWIPVTLPDRIRRLARGDIQIISLGGATEGSVWSILHPIGQVPPGARSIPYGRPML
                                         : ****:*  **             :. *  **.::**:   :        ***** .: 

Q9KIZ9_A1_cys                            NQTFHVLDEALEPRPVWVPGQLYIGGVGLALGYWRDEEKTRNSFLVHPETGERLYKTGDL
CCA29203.1_2085_mod2_cys                 NQKMYVLSPALCHCPVGVTGEIHIGGMGVALGYWRDETLSRARYIEHPTLG-RLYKTGDL
Q6DNE7_A1_4__cys                         NQSFYVLNELMEPRPVWVPGQLYIGGVGLAKGYWKNEHKTQASFITHPVTQEPLYKTGDL
Q8GAQ3_A2_4__cys                         NQSLHVLNHNLDPCPNWVPGQLYIGGIGLAQGYWRDEQKTNASFILHPQTGERLYKTGDL
Q70P97_A1_cys                            NQRFYVLDDALASRPDYVPGELFIGGVGVARGYFRDDVRTAERFIVHPKTNERLYRTGDL
CCA29202.1_1497_mod2_cys                 NQGMYVLDGQLQHCPVGVTGEIYIGGEGVALNYWRAPALSEARFIQHPHLG-RLYRTGDQ
O68006_A2_cys                            NQKIYVLNQNKQLCPVGVEGELYIGGAGVASGYIHDQEKTEHSFIQHQELG-YIYKTGDY
Q9RFK9_A1_cys                            NQRFYVLDEKLAPRPDHVPGDLYIGGVGLAQGYFRDEETTRARFFNHPRTGERLYRTGDL
Q9FB18_A2_cys                            NQRLEVLDEQLRPRPDWVPGELYIGGTGVAKGYWRDPEQTSLRFPVHPGSGQRLYRTGDF
O85740_A1_3__cys                         GQSVEVLDARGRRCPPGVRGEIHIGGVGLALGYAGDPQRTAERFVRHPD-GRRLYRTGDL
Q5MD35_A1_cys                            NQRFHVLDEALSPRPDHVPGELFIGGVGVARGYFGDEVRTAERFIVHPKTRERLYRTGDL
                                         .* . **.      *  * *::.*** *:* .*      :   :  *      :*:*** 

Q9KIZ9_A1_cys                            GRYLPDGNIEFMGREDNQIKLRGYRVELGEIEETLKSHPNVRDAVIVPVGN---DAANKL
CCA29203.1_2085_mod2_cys                 GRWSAQGYIEFLGRNDFQVKLRGHRVELGEIENALLRHPAIKQSVVLVKNQGQGGHGAQY
Q6DNE7_A1_4__cys                         GRYLPDGNIEFLGREDFQVKINGYRVELGEIEVALKQFPGIKEAIVTAIGE---SQQSKR
Q8GAQ3_A2_4__cys                         ARYLPDGNSEFLGREDFQVKISGYRIELGEIEATLLGHATVKETVVAAVGE----LQSKQ
Q70P97_A1_cys                            GRFLPGGDIEFLGRKDFQVKVAGHRIELGEIEAALLRHPALREAVVAAPGE----RSARR
CCA29202.1_1497_mod2_cys                 GRWSRAGHIEFLGRNDFQVKLNGYRVELEEISAKLCQVPGVDSAVVRIHK----SKGREH
O68006_A2_cys                            GVLKEDGYVEFLGRKDSQVKIRGYRVEMGEIENTLVSHQEITKASVIDYTS---PDGIKN
Q9RFK9_A1_cys                            GRFLPEGEIEFLGRKDFQVKIAGHRIELGEIEAVLQRHPSIREAVVAAPGE----RTSRR
Q9FB18_A2_cys                            ARHLPDGTLEFLGRQDDQVKIGGFRVELGEVEAALGRLPDVAAGAVIATGD---PRGDRR
O85740_A1_3__cys                         GRYLADGSIEFLGREDDQVKIRGHRIELAELDAALCAHPQVNLAATVVLGE----THERS
Q5MD35_A1_cys                            GRFLPSGDIEFLGRKDFQVKVAGHRIELGEIEAALLRHPALREAVVAAPGE----RTARR
                                         .     *  **:**:* *:*: *.*:*: *:.  *     :                 . 

Q9KIZ9_A1_cys                            LLAYVVPEGTRRRAAEQDAS
CCA29203.1_2085_mod2_cys                 LVGYYVAEQALDEQALLE--
Q6DNE7_A1_4__cys                         LVAYAV---FKEKSVISDSS
Q8GAQ3_A2_4__cys                         LVAYVV---FHSESS-SDSA
Q70P97_A1_cys                            LVAYVVV--AEGQAVPSAES
CCA29202.1_1497_mod2_cys                 VVAYLVST------------
O68006_A2_cys                            LYAFVVAENAISQLDV----
Q9RFK9_A1_cys                            LVAYLVP--VEGQEAPSDEV
Q9FB18_A2_cys                            LVGFAVP----AREGGFDAA
O85740_A1_3__cys                         LASF----------------
Q5MD35_A1_cys                            LVAYVVV--AEGQSAPSDES
                                         : .:                
