CLUSTAL W multiple sequence alignment


Q9C1G0v1_A2_cys                          TAALAVIADGPYLERLESIMEGSLPL-IPSDEALRLPP--SPVHPNSNCHSSDLAYVMYT
Q9C1G0v2_A2_cys                          TAALAVIADGPYLERLESIMEGSLPL-IPSDEALRLPP--SPVHPNSNCHSSDLAYVMYT
P27742_A2_cys                            TSAIAVISDACYLSRIQELAGESVRL-YRSDISTQTDGNWSVSNPAPSSTSTDLAYIIYT
P25464_A2_cys                            TAALAVITDSPHIDRLRSITNNRLPV-IQSDFALQLPP--SPVHPVSNCKPSDLAYIMYT
P27743_A2_cys                            TAARVVVTNEIHSDRLRSLAETGTP--VLEIELLHLDD-QPAVNPVTETTSTDLAYAIYT
P94873_A2_cys                            TQARLVLTDRAYAERLDRVAD-GLPCEVFGVQDLPLEP-YPAANPRSAATSTDLAYAIYT
P19787_A2_cys                            TQALAVIADSCYLPRIKGMAASGTLL-YPSVLPANPDSKWSVSNPSPLSRSTDLAYIIYT
P26046_A2_cys                            TQALAVIADSCYLPRIKGMAASGTLL-YPSVLPANPDSKWSVSNPSPLSRSTDLAYIIYT
                                         * *  *:::  :  *:  :                     .  :* .   .:**** :**

Q9C1G0v1_A2_cys                          SGTTGLPKGVMVEHHGVVNLAFSLAQIFGL-RDTDDEVILSFSNYIFDHFVEQMTDALLN
Q9C1G0v2_A2_cys                          SGTTGLPKGVMVEHHGVVNLAFSLAQIFGL-RDTDDEVILSFSNYIFDHFVEQMTDALLN
P27742_A2_cys                            SGTTGKPKGVMVEHHGVVNLQISLSKTFGL-RDTDDEVILSFSNYVFDHFVEQMTDAILN
P25464_A2_cys                            SGTTGNPKGVMVEHHGVVNLCVSLCRLFGL-RNTDDEVILSFSNYVFDHFVEQMTDALLN
P27743_A2_cys                            SGTTGKPKAVLVEHRGVVNLQVSLAKLFGLDKAHRDEALLSFSNYIFDHFVEQMTDALLN
P94873_A2_cys                            SGTTGRPKAVLIEHRGVVNLHTSLERLFDLSRDRGDEAVLSFSNYVFDHFVEQMTDALLS
P19787_A2_cys                            SGTTGRPKGVTVEHHGVVNLQVSLSKVFGL-RDTDDEVILSFSNYVFDHFVEQMTDAILN
P26046_A2_cys                            SGTTGRPKGVTVEHHGVVNLQVSLSKVFGL-RDTDDEVILSFSNYVFDHFVEQMTDAILN
                                         ***** **.* :**:*****  ** : *.* :   **.:******:***********:*.

Q9C1G0v1_A2_cys                          GQTLVVLNDEMRGDKERLYKYIEDNKVTYLSGTPSVISMYEFDRFHSHMRRIDCVGEAFS
Q9C1G0v2_A2_cys                          GQTLVVLNDEMRGDKERLYKYIEDNKVTYLSGTPSVISMYEFDRFHSHMRRIDCVGEAFS
P27742_A2_cys                            GQTLVMLNDAMRSDKERLYQYIETNRVTYLSGTPSVISMYEFSRFKDHLRRVDCVGEAFS
P25464_A2_cys                            GQTLVVLNDEMRGDKERLYRYIETNRVTYLSGTPSVISMYEFDRFRDHLRRVDCVGEAFS
P27743_A2_cys                            GQKLVVLDDSMRTDPGRLCRYMNDEQVTYLSGTPSVLSLYDYSSATS-LTRIDAIGEDFT
P94873_A2_cys                            GQTLVMLDDSMRSDQQRLYAYMNANAVTYLSGTPSVLSLYEYGSIPS-LKRIDAIGEDFT
P19787_A2_cys                            GQTLLVLNDGMRGDKERLYRYIEKNRVTYLSGTPSVVSMYEFSRFKDHLRRVDCVGEAFS
P26046_A2_cys                            GQTLLVLNDGMRGDKERLYRYIEKNRVTYLSGTPSVVSMYEFSRFKDHLRRVDCVGEAFS
                                         **.*::*:* ** *  **  *:: : **********:*:*::.   . : *:*.:** *:

Q9C1G0v1_A2_cys                          EPVFDKIRETFPGLVINGYGPTEVSITTSKRLYPFPERRTNKSIGSQVSNSKSYVLSDDM
Q9C1G0v2_A2_cys                          EPVFDKIRETFPGLVINGYGPTEVSITTSKRLYPFPERRTNKSIGSQVSNSKSYVLSDDM
P27742_A2_cys                            QPVFDQIRDTFQGLIINGYGPTEISITTHKRLYPFPERRTDKSIGQQIGNSTSYVLNADM
P25464_A2_cys                            EPVFDKIRETFPGLIINGYGPTEVSITTHKRPYPFPERRTDKSIGCQLDNSTSYVLNDDM
P27743_A2_cys                            EPVFAKIRGTFPGLIINGYGPTEISITSHKRPYPPDVHRVNKSIGFPVANTKCHVLNKAM
P94873_A2_cys                            TPVFDKIRSSFGGLIINGYGPTEISITSHKRLYLKHEPRLDKSIGHPVANTACYVLNPAM
P19787_A2_cys                            EPVFDKIRETFHGLVINGYGPTEVSITTHKRLYPFPERRMDKSIGQQVHNSTSYVLNEDM
P26046_A2_cys                            EPVFDKIRETFHGLVINGYGPTEVSITTHKRLYPFPERRMDKSIGQQVHNSTSYVLNEDM
                                          *** :** :* **:********:***: ** *     * :****  : *: .:**.  *

Q9C1G0v1_A2_cys                          KRMPIGAVGELYLGGDGVARGYHNRPELTAERFPQNPFQTEQEKREGRNGRLYKTGDLVR
Q9C1G0v2_A2_cys                          KRMPIGAVGELYLGGDGVARGYHNRPELTAERFPQNPFQTEQEKREGRNGRLYKTGDLVR
P27742_A2_cys                            KRVPIGAVGELYLGGEGVARGYHNRPEVTAERFLRNPFQTDSERQNGRNSRLYRTGDLVR
P25464_A2_cys                            KRVPIGAVGELYLGGDGVARGYHNRPDLTADRFPANPFQTEQERLEGRNARLYKTGDLVR
P27743_A2_cys                            KPVPVGGIGELYIGGIGVTRGYLNREDLTADRFVENPFQTAEERRLGENGRLYKTGDLVR
P94873_A2_cys                            QRVPVGGMGELYIGGIGVARGYLNRPELTAERFVSNPFQSAGEKALGNNARLYKTGDLVR
P19787_A2_cys                            KRTPIGSVGELYLGGEGVVRGYHNRADVTAERFIPNPFQSEEDKREGRNSRLYKTGDLVR
P26046_A2_cys                            KRTPIGAVGELYLGGEGVVRGYHNRADVTAERFIPNPFQSEEDKREGRNSRLYKTGDLVR
                                         :  *:*.:****:** **.*** ** ::**:**  ****:  ::  *.*.***:******

Q9C1G0v1_A2_cys                          WIQGSN--GEVEYLGRNDFQVKIRGQRIELGEIEAVLSSYEGIKQSVVLAKDRK------
Q9C1G0v2_A2_cys                          WIQGSN--GEVEYLGRNDFQVKIRGQRIELGEIEAVLSSYEGIKQSVVLAKDRK------
P27742_A2_cys                            WIPGSN--GEIEYLGRNDFQVKIRGLRIELGEIEAVMSSHPDIKQSVVIAKSGK------
P25464_A2_cys                            WIHNANGDGEIEYLGRNDFQVKIRGQRIELGEIEAVLSSYPGIKQSVVLAKDRK------
P27743_A2_cys                            WLPN----GEVEYLGRTDLQVKIRGQRVELGEVEAALSSYPGVVRSLVVAREHA------
P94873_A2_cys                            WLPN----GELEYLGRNDMQVKIRGQRVELGEVEAILASYPGVTRALVLAREYAASAAGG
P19787_A2_cys                            WIPGSS--GEVEYLGRNDFQVKIRGLRIELGEIEAILSSYHGIKQSVVIAKDCR------
P26046_A2_cys                            WIPGSS--GEVEYLGRNDFQVKIRGLRIELGEIEAILSSYHGIKQSVVIAKDCR------
                                         *: .    **:*****.*:****** *:****:** ::*: .: :::*:*:.        

Q9C1G0v1_A2_cys                          IDNQKFLVGYYLGSE-SLSAQA
Q9C1G0v2_A2_cys                          IDNQKFLVGYYLGSE-SLSAQA
P27742_A2_cys                            EGDQKFLVGYFVASS-PLSPGA
P25464_A2_cys                            NDGQKYLVGYFVSSAGSLSAQA
P27743_A2_cys                            -VGQKYLVGFYVGEQ-EFDEQD
P94873_A2_cys                            EASQKYLVAFYLSAE-ELPETD
P19787_A2_cys                            EGAQKFLVGYYVADA-ALPSAA
P26046_A2_cys                            EGAQKFLVGYYVADA-ALPSAA
                                            **:**.:::.    :    
