CLUSTAL W multiple sequence alignment


CCJ67637.1_2717_mod3_d-ser               SAPAVVLVQSATRGLLGEISVPVVDLEQVTWQQALASNPLIAELTPQHQAYVIYTSGSTG
CCJ67636.1_2656_mod3_d-ser               SAPSVVLVQSATRALLGDVAVPVVDLELVTWQHQSASNPLIAELTPQHQAYVIYTSGSTG
BGC0000425_AFH75320.1_2651_mod3_d-ser    SAPAVVLVQTATRALLGDIAVPVVDLDHAHWQHLPSSNPSVAALTPQHAAYVIYTSGSTG
                                         ***:*****:***.***:::******: . **:  :*** :* ***** ***********

CCJ67637.1_2717_mod3_d-ser               KPKGVINEHSAVVNRLLWMQEAYDLDASDTVLQKTPFSFDVSVWEFFWPLFTGARLVMAR
CCJ67636.1_2656_mod3_d-ser               KPKGVINEHSPVVNRLLCMQDTYRLDSSDALLQKTPFSFDVSVWEFFWPLFTGARLVMAR
BGC0000425_AFH75320.1_2651_mod3_d-ser    KPKGVINEHSAVVNRLLWMQEEYRLGADDTVLQKTPFSFDVSVWEFFWPLFTGARLVMAR
                                         **********.****** **: * *.:.*::*****************************

CCJ67637.1_2717_mod3_d-ser               PGGHKDPEYLCEIIQAERVTTLHFVPSMLDVFLAHGDVSQAAGLVRVMCSGEALPGSVVR
CCJ67636.1_2656_mod3_d-ser               PGGHKDPAYLCEVIQAEHITTVHFVPSMLDVFLAHGDVSQAAGLARVMCSGEALPGSLVR
BGC0000425_AFH75320.1_2651_mod3_d-ser    PGGHKDPQYLCDIIEAEQVTTLHFVPSMLDVFLAHGDVSQAAGLVRVMCSGEALPGSVVR
                                         ******* ***::*:**::**:**********************.************:**

CCJ67637.1_2717_mod3_d-ser               RFKQQLPASGLFNLYGPTEAAVDVTAWDCAGPITPDNTPIGKPIANTRMYVLDEHLQPVP
CCJ67636.1_2656_mod3_d-ser               RFKAQLPGSALFNHYGPTEAAVEVTAWDCNGAVTPDNTPIGKPIGNVRMYVLDAHLQPVP
BGC0000425_AFH75320.1_2651_mod3_d-ser    RFKQQLPGSQLFNLYGPTEAAVDVTAWDCNAALAPDNTPIGKAIANTRMYVLDAHMQPVP
                                         *** ***.* *** ********:****** ..::********.*.*.****** *:****

CCJ67637.1_2717_mod3_d-ser               LGVSGELFIGGVQVARGYLNRPQLTAERFFDDPFNPGRMYRTGDVGRFLSDGNIEYLGRN
CCJ67636.1_2656_mod3_d-ser               LGVSGELFIGGVQVARGYLNRPELNAERFLKDPYSTGRIYRTGDVARYLPDGNIEYLGRN
BGC0000425_AFH75320.1_2651_mod3_d-ser    LGVSGELYIGGVQVARGYLNRPDLTAERFLKDPFSEGRLYRTGDVGRFLADGNIEYLGRN
                                         *******:**************:*.****:.**:. **:******.*:*.**********

CCJ67637.1_2717_mod3_d-ser               DDQVKIRGLRIELGEIQARLGEFSQIKEATVLAREDVPGDKRLVAYYTGVPAEVEA
CCJ67636.1_2656_mod3_d-ser               DDQVKIRGVRIELGEIQARLGEFPHIQEATVLAREDVPGDKRLVAYYTGVPAATEA
BGC0000425_AFH75320.1_2651_mod3_d-ser    DDQVKIRGLRIELGEIQARLGEFPQILEATVLAREDVPGDKRLVAYYTGAPAATDE
                                         ********:**************.:* **********************.** .: 
