CLUSTAL W multiple sequence alignment


CCJ67638.1_2717_mod3_d-val               SGAQLLLSVTSIEVPEGARRLDLDTLDLSVEPEHNPALEQLAETAAYIMYTSGSTGTPKG
CCJ67638.1_1653_mod2_d-val               SGAQLLLSVASIEVPEGARRLDLDTLDLSVEPDHNPALEQSAETAAYIMYTSGSTGTPKG
CCJ67639.1_2757_mod3_d-val               SGAQLLLSVASIEVPEGARRLDLDTLDLSVEPDHNPALEQSAETAAYIMYTSGSTGTPKG
CCJ67637.1_1654_mod2_d-val               SGAQLLLSVTSIEVPEGARRLDLDTLDLSVEPEHNPALEQLAETAAYIMYTSGSTGTPKG
                                         *********:**********************:******* *******************

CCJ67638.1_2717_mod3_d-val               VLVPHRAITRLVINNGYADFNQHDRVAFASNPAFDASTLDVWAPLLNGGAVVVVDQDTLL
CCJ67638.1_1653_mod2_d-val               VLVPHRAITRLVINNGYADFNQHDRVAFASNPAFDASTLDVWAPLLNGGAVVVVDQDTLL
CCJ67639.1_2757_mod3_d-val               VLVPHRAITRLVINNGYADFNQHDRVAFASNPAFDASTLDVWAPLLNGGAVVVVDQDTLL
CCJ67637.1_1654_mod2_d-val               VLVPHRAITRLVINNGYADFNQHDRVAFASNPAFDASTLDVWAPLLNGGAVVVVDQDTLL
                                         ************************************************************

CCJ67638.1_2717_mod3_d-val               SQTDFAALLQEQAVSVLWMTAGLFHQYAEGLLAVFPQLRYLIVGGDVLDPSVIARVLKDG
CCJ67638.1_1653_mod2_d-val               SQADFAALLQEQAVSVLWMTAGLFHQYAEGLLPVFTQLRYLIVGGDVLDPSVIARVLKDG
CCJ67639.1_2757_mod3_d-val               SQTDFVALLQQQAVSVLWMTAGLFHQYAEGLLAVFPQLRYLIVGGDVLDPSVIARVLKDG
CCJ67637.1_1654_mod2_d-val               SQTDFAALLQEQAVSVLWMTAGLFHQYAEGLLAVFPQLRYLIVGGDVLDPSVIARVLKDG
                                         **:**.****:*********************.**.************************

CCJ67638.1_2717_mod3_d-val               APQHLLNGYGPTEATTFSTTHEITRADEGSIPIGRPVGNSRAYVLDARQQPVPVGVTGEL
CCJ67638.1_1653_mod2_d-val               APQHLLNGYGPTEATTFSTTHEITRADEGSIPIGRPVGNSRAYVLDARQQPVPVGVTGEL
CCJ67639.1_2757_mod3_d-val               APQHLLNGYGPTEATTFSTTHEITRADEGSIPIGRPVGNSRTYVLDARQQPVAVGVTGEL
CCJ67637.1_1654_mod2_d-val               APQHLLNGYGPTEATTFSTTHEITRADEGSIPIGRPVGNSRAYVLDARQQPVPVGVTGEL
                                         *****************************************:**********.*******

CCJ67638.1_2717_mod3_d-val               YIGGQGVALGYLNRAELTAQAFLADPFNDGALMYRTGDLVAWREDGTLQYQGRNDQQVXI
CCJ67638.1_1653_mod2_d-val               YIGGQGVALGYLNRAELTAEKFLADPFNDGALMYRTGDLVAWREDGTLQYQGRNDQQVKI
CCJ67639.1_2757_mod3_d-val               YIGGQGVALGYLNRAELTAEKFLADPFNDGALMYRTGDLVAWREDGTLQYQGRNDQQVKI
CCJ67637.1_1654_mod2_d-val               YIGGQGVALGYLNRAELTAQAFLADPFNDGALMYRTGDLVAWREDGTLQYQGRNDQQVKI
                                         *******************: ************************************* *

CCJ67638.1_2717_mod3_d-val               RGFRIELGEIETRLSEHPQVKDAVVLAREDEPGHKRLVAYFTEREGVDIQA
CCJ67638.1_1653_mod2_d-val               RGFRIELGEIETRLSEHPQVKDAVVLAREDEPGHKRLVAYFTEREGVDIQA
CCJ67639.1_2757_mod3_d-val               RGFRIELGEIETRLSEHPQVKDAVVLARQDEPGHKRLVAYFTEREALDIEV
CCJ67637.1_1654_mod2_d-val               RGFRIELGEIETRLSEHPQVKDAVVLAREDEPGHKRLVAYFTEREGVDIQA
                                         ****************************:****************.:**:.
