CLUSTAL W multiple sequence alignment


O85168_A3_dab                            SQPAALMTQRHLQEYLPTLTLPLVLLDDDQRKTFTERDDNPVVEALGVRNLAYVIYTSGS
O85168_A4_dab                            SQPAALLTLPGLQDRLPALSMPLVLLDDEQYQGLAECDDNPVVPTLGVRNLAYVIYTSGS
Q83VS0_A10_20__dab                       SQPAALLTQRGLQERLPALSMPLVLLDDEHCQGFTECDDNPVVPTLGVRNLAYVIYTSGS
Q83VS0_A11_21__dab                       SQPAALLTQRDLQKRLPTLTLPLVLLDDDQRNTFTERDDNPVVEALGVRNLAYVIYTSGS
                                         ******:*   **. **:*::*******:: : ::* ****** :***************

O85168_A3_dab                            TGNPKGVMIEHRGLVNYSVDAARLFDLSPTDTVLQQNTLNFDLSVEEIFPALLAGATLTP
O85168_A4_dab                            TGNPKGVMIEHRGLVNYSVDAARLFDLSQSDTVLQQNTLNFDLSVEEIFPALLAGATLAP
Q83VS0_A10_20__dab                       TGNPKGVMIEHRGLVNYSVDAARLFGLSQSDTVLQQNTLNFDLSVEEIFPALLAGATLAP
Q83VS0_A11_21__dab                       TGNPKGVMIEHRGLVNYSVDAARLFALSQSDTVLQQNTLNFDLSVEEIFPALLAGATLAP
                                         ************************* ** :****************************:*

O85168_A3_dab                            SREIFGSEGTENHGINPTVLHLTAAHWHTLVAEWHKQPQVAEQRLQHVRLINVTGDALSA
O85168_A4_dab                            SREIFGSEGTETHGIQPTVLHLTTAHWHTLVAEWHNQPQAAEQRLQHVRLINVTGDALSA
Q83VS0_A10_20__dab                       SREIFGSEGTENHGIYPTVLHLTAAHWHTLVAEWHNQPQAAEQRLAEVRLINVTGDALSA
Q83VS0_A11_21__dab                       SREIFGSEGTENHGIYPTVLHLTAAHWHTLVAEWHNQPQAAAQRLAEVRLINVTGDALSA
                                         ***********.*** *******:***********:***.* *** .*************

O85168_A3_dab                            QKLKLWDEVRPAHTRLINTYGPTEATVSCTAAYVSHDAAAGSEGSGNATIGKPMANTRIY
O85168_A4_dab                            QKLKLWDEVRPAHTLLINTYGPTEATVSCTAAYVSYDAAAGSEGSGNATIGKPMANTRIY
Q83VS0_A10_20__dab                       QKLKLWDEVRPAHTRLINTYGPTEATVSCTAAYVSHDAAAGSEGSGNATIGKPMANTRIY
Q83VS0_A11_21__dab                       QKLKLWDEVRPAHTRLINTYGPTEATVSCTAAYVSHDAIAGSEGSGNATIGKPMANTRIY
                                         ************** ********************:** *********************

O85168_A3_dab                            LLDAHQQPVPYGVAGEIYIGGDGVARGYLNLEEVNAERFLADPFSESPDARMYKTGDLAR
O85168_A4_dab                            LLDAHQQPVPYGVAGEIYIGGDGVARGYLNLEEVNAERFLADPFSESPDARMYKTGDLAR
Q83VS0_A10_20__dab                       LLDAHQQPVPYGVAGEIFIGGDGVARGYLNLEEVNAERFLADPFSNSPDARMYKTGDLAR
Q83VS0_A11_21__dab                       LLDAHQQPVPYGVAGEIFIGGDGVARGYLNLEEVNAERFLADPFSNSPEARMYKTGDLAR
                                         *****************:***************************:**:***********

O85168_A3_dab                            YMADGRIEYLGRNDFQVKVRGFRIELGEIEARLGNCTGVKEAVVIAREDNPGDKRLVAYV
O85168_A4_dab                            YMADGRIEYLGRNDFQVKVRGFRIELGEIEARLGNCKGVKEAVVIAREDNPGEKRFVAYV
Q83VS0_A10_20__dab                       YMADGRIEYLGRNDFQVKVRGFRIELGEIEARLGNCKGVKEAVVIAREDNPGEKRLVAYV
Q83VS0_A11_21__dab                       YMADGRIEYLGRNDFQVKVRGFRIELGEIEARFGNCAGVKEAVVIAREDTPGDKRLVAYV
                                         ********************************:*** ************.**:**:****

O85168_A3_dab                            VAQPQSQLTAAD
O85168_A4_dab                            VAQPQTQITAAE
Q83VS0_A10_20__dab                       IAQPQANLDAAS
Q83VS0_A11_21__dab                       VGQPQASLDAAS
                                         :.***:.: **.
