CLUSTAL W multiple sequence alignment


Q83VS1_A4_9__dhab|dht                    STPVALLSQQSVQQALPVSQVPVIYLDDAGLQDESVDNPQIS-VKPDNLAYVIYTSGSTG
Q83VS0_A4_14__dhab|dht                   STPVALLSQQSVQQALPVTEVPIISLDDADLQDESVCNPEVAGLTAASLAYVIYTSGSTG
Q9FDB3_A1_1__dhab|dht                    SAPVALLSQQSVQPALPVSDVPLIYLDDVDLQDERACNPQVS-VRPSDLAYVIYTSGSTG
Q9FDB3_A1_dhab|dht                       SAPVALLSQQSVQPALPVSDVPLIYLDDVDLQDERACNPQVS-VRPSDLAYVIYTSGSTG
Q83VS1_A4_dhab|dht                       STPVALLSQQSVQQALPVSQVPVIYLDDAGLQDESVDNPQIS-VKPDNLAYVIYTSGSTG
Q83VS0_A8_18__dhab|dht                   SAPVALLSQRSVQSTLPASEVPVISLDD-DLQGESVCNPQVP-VKPTNLAYVIYTSGSTG
                                         *:*******:*** :**.::**:* *** .**.* . **::. : . .************

Q83VS1_A4_9__dhab|dht                    LPKGVMVEHRNVARLFSATEDWFGFNEQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVP
Q83VS0_A4_14__dhab|dht                   LPKGVMVEHRNVARLFSATQDWFGFGEQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVP
Q9FDB3_A1_1__dhab|dht                    LPKGVMVEHRNVARLFSATQDWFGFNEQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVP
Q9FDB3_A1_dhab|dht                       LPKGVMVEHRNVARLFSATQDWFGFNEQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVP
Q83VS1_A4_dhab|dht                       LPKGVMVEHRNVARLFSATEDWFGFNEQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVP
Q83VS0_A8_18__dhab|dht                   LPKGVMVEHRNVARLFSATEEWFGFNQQDVWALFHSFAFDFSVWEIWGALLHGGRLLIVP
                                         *******************::****.:*********************************

Q83VS1_A4_9__dhab|dht                    QLVSRSPEDFYTLLCSTAVTVLNQTPSAFRQLITAQGENQQAHSLRQVIFGGEALETAML
Q83VS0_A4_14__dhab|dht                   QLVSRSPQDFHDLLCSAGVTVLNQTPSAFRQLIAAQGENEQAHSLRQVIFGGEALETAML
Q9FDB3_A1_1__dhab|dht                    QLVSRSPEDFYNLLCSAGVTVLNQTPSAFRQLIAAQDDKEQVHSLRQVIFGGEALETAML
Q9FDB3_A1_dhab|dht                       QLVSRSPEDFYNLLCSAGVTVLNQTPSAFRQLIAAQDDKEQVHSLRQVIFGGEALETAML
Q83VS1_A4_dhab|dht                       QLVSRSPEDFYTLLCSTAVTVLNQTPSAFRQLITAQGENQQAHSLRQVIFGGEALETAML
Q83VS0_A8_18__dhab|dht                   QLVSRSPEDFYNLLCSAGVTVLNQTPSAFRQLIAAQAENTQAHSLRQVIFGGEALETAML
                                         *******:**: ****:.***************:** :: *.******************

Q83VS1_A4_9__dhab|dht                    KPWYARNVNAATQLVNMYGITETTVHVTYYPLQPEDAQRVGASPIGTRIPDLQLYLLDTC
Q83VS0_A4_14__dhab|dht                   KPWYARNVNAGTQLVNMYGITETTVHVTYYPLQADDAQRIGASPIGRRIPDLQLYVLDTH
Q9FDB3_A1_1__dhab|dht                    KPWYARKVNASTQLVNMYGITETTVHVTYYPLQPEDARRVGASPIGKRIPDLQLYLLDAY
Q9FDB3_A1_dhab|dht                       KPWYARKVNASTQLVNMYGITETTVHVTYYPLQPEDARRVGASPIGKRIPDLQLYLLDAY
Q83VS1_A4_dhab|dht                       KPWYARNVNAATQLVNMYGITETTVHVTYYPLQPEDAQRVGASPIGTRIPDLQLYLLDTC
Q83VS0_A8_18__dhab|dht                   KPWYARQANAGTQLVNMYGITETTVHVTYYPLQPEDAQRLGASPIGRRIPDLQLYVLDAR
                                         ******:.**.**********************.:**:*:****** ********:**: 

Q83VS1_A4_9__dhab|dht                    GEPVPVGVVGELYVGGAGVARGYLNREALTAERFIDNPFNTAPGARLYRTGDLGRWLADG
Q83VS0_A4_14__dhab|dht                   GEPVPVGVVGELYVGGAGVARGYLNREALTAERFIDNPFNTAPGARLYRTGDLGRWLADG
Q9FDB3_A1_1__dhab|dht                    GHPLPPGAVGELYVGGAGVARGYLNRDELNTTRFLDDPFASAPGARMYRSGDLGRWLPDG
Q9FDB3_A1_dhab|dht                       GHPLPPGAVGELYVGGAGVARGYLNRDELNTTRFLDDPFASAPGARMYRSGDLGRWLPDG
Q83VS1_A4_dhab|dht                       GEPVPVGVVGELYVGGAGVARGYLNREALTAERFIDNPFNTAPGARLYRTGDLGRWLADG
Q83VS0_A8_18__dhab|dht                   GEPVPVGVVGELYVGGAGVARGYLNREALTAERFLDNPFSHTADARMYRTGDLGRWLADG
                                         *.*:* *.******************: *.: **:*:**  :..**:**:*******.**

Q83VS1_A4_9__dhab|dht                    TLEYLGRNDEQVKIRGFRIELGEIEARLAEYPDVRDAVVLCREDVPGDKRLVAYV---TT
Q83VS0_A4_14__dhab|dht                   SLEYLGRNDEQVKIRGFRIELGEIEAQLCACDGVQDALVLVREDEPGDKRLVAYVIGTAD
Q9FDB3_A1_1__dhab|dht                    SLEYLGRNDEQVKIRGFRIELGEIEARLSACEGVRDAVVVVREDEPGDQRLVAYVIGTAG
Q9FDB3_A1_dhab|dht                       SLEYLGRNDEQVKIRGFRIELGEIEARLSACEGVRDAVVVVREDEPGDQRLVAYVIGTAG
Q83VS1_A4_dhab|dht                       TLEYLGRNDEQVKIRGFRIELGEIEARLAEYPDVRDAVVLCREDVPGDKRLVAYV---TT
Q83VS0_A8_18__dhab|dht                   SLEYLGRNDEQVKIRGFRIELGEIEARLAEYPDVRDAVVLCREDVPGDKRLVAYV---TT
                                         :*************************:*.   .*:**:*: *** ***:******   : 

Q83VS1_A4_9__dhab|dht                    LHPESLLDIET
Q83VS0_A4_14__dhab|dht                   VELDATR----
Q9FDB3_A1_1__dhab|dht                    QEPDATW----
Q9FDB3_A1_dhab|dht                       QEPDATW----
Q83VS1_A4_dhab|dht                       LHPESLLDIET
Q83VS0_A8_18__dhab|dht                   QQPESLLDIET
                                          . ::      
