CLUSTAL W multiple sequence alignment


Q70AZ8_A1_3__dpg                         SAVAAVLCRESTAGAVPAGHELIDMDRVGEGVAAPVAIGADDLAYVMYTSGSTGKPKGVA
Q7WZ65_A1_dpg                            SAVAMVVCQEATSGVVPPGYQQLLVNDADDGEAALVPIGADDLAYVMYTSGSTGTPKGVA
BGC0001178_AGS77308.1_476_mod1_dpg       SAVAAVMCRKETSGAVPAGHVRITVEDAVEGEVPPVAIGPDDLAYVMYTSGSTGTPKGVA
BGC0000418_AHF20583.1_473_mod1_dpg       SSAAAVVCRAGTA--TPAGYQRILVDDRVSGEASLVPVGANDLAYVMYTSGSTGTPKGVA
Q8KLL4v1_A1_dpg                          AAVAAVVCGAGTAAVVPSGHVLVTMDDAVDGETSLVPVGADDLAYVMYTSGSTGTPKGVA
Q8KLL4v2_A1_dpg                          AAVAAVVCGAGTAAVVPSGHVLVTMDDAVDGETSLVPVGADDLAYVMYTSGSTGTPKGVA
BGC0000419_AIG79242.1_473_mod1_dpg       SSAAAVVCRAGTA--TPSGYQRILVDDRVSGEASLVPVGANDLAYVMYTSGSTGTPKGVA
                                         ::.* *:*   *:  .*.*:  : ::   .* .. *.:*.:*************.*****

Q70AZ8_A1_3__dpg                         VAHGGVAALAGDPVWEVGAGDAVLMHAPHTFDASLYDVWVPLVSGARVMLAEPGVVDAQR
Q7WZ65_A1_dpg                            IPHGGVAALAGDPGWGVGPGDAVLMHAPHTFDASLYDVWVPLVSGARVMITEPGVVDAER
BGC0001178_AGS77308.1_476_mod1_dpg       IPHGGVAALAGDPGWDVGAGDAVLMHAPHTFDASLYDVWVPLLSGARVLLAEPGVVDAEQ
BGC0000418_AHF20583.1_473_mod1_dpg       VSHGGVAALLGYKVWDLHPGDAVLMHAPHTFDPALYEVLVPLVAGARVILAGPGVIDADR
Q8KLL4v1_A1_dpg                          VAHGGVAALAGDPGWGVGAGDTVLMHAPHTFDASLYDLWVPLVSGARVLLAEPGVVDAER
Q8KLL4v2_A1_dpg                          VAHGGVAALAGDPGWGVGAGDTVLMHAPHTFDASLYDLWVPLVSGARVLLAEPGVVDAER
BGC0000419_AIG79242.1_473_mod1_dpg       VSHGGVAALLGYKVWDLHPGDAVLMHAPHTFDPALYEVLVPLVAGARVILAGPGVIDADR
                                         :.******* *   * : .**:**********.:**:: ***::****::: ***:**::

Q70AZ8_A1_3__dpg                         LAAHVADGLTAVNFTAGQFRALAQESPESFAGLRDVLAGGDVVPLGAVERVRQACPGLRV
Q7WZ65_A1_dpg                            LAGHVADGLTAVNFTAGHFRALAQESPESFSGLREVAAGGDVVPLDVVERVRRACPRLRV
BGC0001178_AGS77308.1_476_mod1_dpg       LVAHVADGLTAVNFTAGQFRALAQESPESFSGLRVVAAGGDVVPPGALERVRRACPRLRV
BGC0000418_AHF20583.1_473_mod1_dpg       LAAHAAEGLTSVNFTAGQFRALVQEKPDCFAGLRYFQTGGDVVPLGAVERVRQACPDLRV
Q8KLL4v1_A1_dpg                          LAAHVAEGLTSVNFTAGQFRALVQESPESFSGLRDVLAGGDVVPLGEVERVRRACPELVV
Q8KLL4v2_A1_dpg                          LAAHVAEGLTSVNFTAGQFRALVQESPESFSGLRDVLAGGDVVPLGEVERVRRACPELVV
BGC0000419_AIG79242.1_473_mod1_dpg       LAAHAAEGLTSVNFTAGQFRALVQEKPDCFAGLRYFQTGGDVVPLGAVERVRQACPDLRV
                                         *..*.*:***:******:****.**.*:.*:*** . :****** . :****:*** * *

Q70AZ8_A1_3__dpg                         WHTYGPTETTLCATWKKIEPGDRLGSTLPIGRPLPGRRLYVLDVFLRPLPPGVAGDLYIA
Q7WZ65_A1_dpg                            WHTYGPTETTLCATWKAIEPGDEVGPVLPIGRALPGRRLYVLDAFLRPLPPGIAGDLYLA
BGC0001178_AGS77308.1_476_mod1_dpg       LHSYGPTETTLCATWKTIEPDDRIGPVLPIGRPLPGRRLYVLDVFLRPLPPGVAGDLYIA
BGC0000418_AHF20583.1_473_mod1_dpg       LHTYGPTETTFCASWKVIRPGDELGTTLPIGKPHPGRRLYVLDVFLRPLPPGVAGDLYIA
Q8KLL4v1_A1_dpg                          WHTYGPTETTLCATWKAIEPSDRLGSVLPIGRPLPGRRLYVLDVFLRPLPPGVEGDLYIA
Q8KLL4v2_A1_dpg                          WHTYGPTETTLCATWKAIEPSDRLGSVLPIGRPLPGRRLYVLDVFLRPLPPGVEGDLYIA
BGC0000419_AIG79242.1_473_mod1_dpg       LHTYGPTETTFCASWKVIEPGDELGTTLPIGKPHPGRRLYVLDVFLRPLPPGVAGDLYIA
                                          *:*******:**:** *.*.*.:*..****:. *********.********: ****:*

Q70AZ8_A1_3__dpg                         GAGVAQGYLGRPALTAERFVADPFAAGERMYRTGDVAYWTGDGELVFAGRADNQVKIRGY
Q7WZ65_A1_dpg                            GAGVAHGYLGRASLTAERFVADPFVAGERMYRTGDLAYWTGEGELVFAGRDDDQVKIRGY
BGC0001178_AGS77308.1_476_mod1_dpg       GVGLAHGYLGSPALTGGRFVADPFASGERMYRTGDVAYWTGEGELVFAGRADNQVKIRGY
BGC0000418_AHF20583.1_473_mod1_dpg       GAGVAHGYLGRTALTAERFVADPFASGERMYRTGDLAYWNDEGELVFAGRADTQVKIRGY
Q8KLL4v1_A1_dpg                          GAGVAHGYLDRPGLTAERFVADPFASGERMYRTGDVAYWTDEGELVYAGRADNQVKIRGY
Q8KLL4v2_A1_dpg                          GAGVAHGYLDRPGLTAERFVADPFASGERMYRTGDVAYWTDEGELVYAGRADNQVKIRGY
BGC0000419_AIG79242.1_473_mod1_dpg       GAGVAHGYLGRTALTAERFVADPFASGERMYRTGDLAYWNDEGELVFAGRADTQVKIRGY
                                         *.*:*:***. ..**. *******.:*********:***..:****:*** * *******

Q70AZ8_A1_3__dpg                         RVEPGEIETVLAEQPGVDQAVVLARDGRLIGYVVPGGEVDPVR
Q7WZ65_A1_dpg                            RVEPGEVEAVLAGQPGVDQAVVVAREGRLLGYVVSGGGVDPVR
BGC0001178_AGS77308.1_476_mod1_dpg       RVEPGEIETVLAEQPGVDQAVVLARDGRLIGYVVSGGGVDPVR
BGC0000418_AHF20583.1_473_mod1_dpg       RVEPGEVEAVLADQPGVDQAVVAVRDGRLIGYVVTGAGVDPVR
Q8KLL4v1_A1_dpg                          RVEPGEIEAVLAERPGVDQAVVVAREGRLIGYVVSGGDVDPEG
Q8KLL4v2_A1_dpg                          RVEPGEIEAVLAERPGVDQAVVVAREGRLIGYVVSGGDVDPEG
BGC0000419_AIG79242.1_473_mod1_dpg       RVEPGEVEAVLADQPGVDQAVVAVRDGRLIGYVVSGAGVDPVR
                                         ******:*:*** :******** .*:***:****.*. ***  
