CLUSTAL W multiple sequence alignment


Q70AZ6_A1_dpg                            SAVSTVICTQATEAAVPQNVPQRATIVLDAPPTRAAVDACAGTAPTFRPSAADLAYVMYT
Q70AZ6_A1_7__dpg                         SAVSTVICTQATEAAVPQNVPQRATIVLDAPPTRAAVDACAGTAPTFRPSAADLAYVMYT
BGC0000418_AHF20585.1_481_mod1_dpg       SGVSVVVCAQATSGVAPED-----AIVLDAPETRVAIDAFAGTATEFRPSADDLAYVMYT
Q939Y9_A1_dpg                            SGVSTVLCTLATSAVAPGN-----AIVLDAPETRVAVRDCA--APEIRPHADDLAYVMYT
BGC0000419_AIG79240.1_481_mod1_dpg       SGVSVVVCTQATSGVAPAD-----AIVLDAPETRAAVDAFADTATEFRPSADDLAYVMYT
Q939Y9_A1_7__dpg                         SGVSTVLCTLATSAVAPGN-----AIVLDAPETRVAVRDCA--APEIRPHADDLAYVMYT
BGC0001178_AGS77310.1_492_mod1_dpg       SEVSAVICTQATGEGLPGDVAGRATIVLDAPETRAAVEGCAATAPEIRLSAGDLAYVMYT
O52821_A1_7__dpg                         SGVSTVLCTQDTSGVVPEN-----AIVLDAPDTRASIEDCADTAPEIRLYAGDLAYVMYT
                                         * **.*:*:  *    * :     :****** **.::   *  *. :*  * ********

Q70AZ6_A1_dpg                            SGSTGVPKGVAVPHGAVAGLAGDAGWRIGPGDGVLMHATHVFDPSLYEMWVPLATGGRVL
Q70AZ6_A1_7__dpg                         SGSTGVPKGVAVPHGAVAGLAGDAGWRIGPGDGVLMHATHVFDPSLYEMWVPLATGGRVL
BGC0000418_AHF20585.1_481_mod1_dpg       SGSTGLPKGVGIPHGGVAGLAGDRGWQIGPGDGVLMHATHVFDPSLYAMWVPLSTGARVL
Q939Y9_A1_dpg                            SGSTGLPKGVAIPHGAVAGLAGDAGWQIGPGDGVLMHATHVFDPSLYAMWVPLVSGARVL
BGC0000419_AIG79240.1_481_mod1_dpg       SGSTGLPKGVGIPHGGVAGLAGDRGWQIGPGDGVLMHATHVFDPSLYAMWVPLSTGARVL
Q939Y9_A1_7__dpg                         SGSTGLPKGVAIPHGAVAGLAGDAGWQIGPGDGVLMHATHVFDPSLYAMWVPLVSGARVL
BGC0001178_AGS77310.1_492_mod1_dpg       SGSTGVPKGVAIPHGAVAGLAGDAGWQLGTDDGVLMHATHVFDPSLYEMWVPLVTGGRVL
O52821_A1_7__dpg                         SGSTGLPKGVAIPHGAVAGLAGDSGWQIGPDDGVLMHATHVFDPSLYAMWVPLVAGGRVL
                                         *****:****.:***.******* **::*..**************** ***** :*.***

Q70AZ6_A1_dpg                            VAAPGVVDAGGIRQAVARGATAVHLTAGTFRALAEASPDCFAGLREVGTGGDVVPAHTVA
Q70AZ6_A1_7__dpg                         VAAPGVVDAGGIRQAVARGATAVHLTAGTFRALAEASPDCFAGLREVGTGGDVVPAHTVA
BGC0000418_AHF20585.1_481_mod1_dpg       LTEPGVLDAAGVRQAVARGANYVHLTAGTFRALAETSPECFDGLVEIGTGGDIVPAQSVE
Q939Y9_A1_dpg                            LTEPGVLDAAGVRQAVHRGATFVHLTAGTFRALAETAPECFEGLVEIGTGGDVVPLQSVE
BGC0000419_AIG79240.1_481_mod1_dpg       LTEPGVLDAAGVRQAVARGANYVHLTAGTFRALAETSPECFDGLVEIGTGGDIVPAQSVE
Q939Y9_A1_7__dpg                         LTEPGVLDAAGVRQAVHRGATFVHLTAGTFRALAETAPECFEGLVEIGTGGDVVPLQSVE
BGC0001178_AGS77310.1_492_mod1_dpg       VAEPGVVDAGGIRQAVERGATAVHLTAGTFRALAEASPDCFAGLREIGTGGDVVPAHTVA
O52821_A1_7__dpg                         LTEPGVLDAAGVRQAVERGATAVHLTAGSFRALAETSPECFAGLVEIGTGGDVVPAQSVA
                                         :: ***:**.*:**** ***. ******:******::*:** ** *:*****:** ::* 

Q70AZ6_A1_dpg                            HLRRAQPQLRVRNTYGPTETTLCATWKPIEPGAQLGPELPIGRPMTNRRIYILDAFLRPV
Q70AZ6_A1_7__dpg                         HLRRAQPQLRVRNTYGPTETTLCATWKPIEPGAQLGPELPIGRPMTNRRIYILDAFLRPV
BGC0000418_AHF20585.1_481_mod1_dpg       NLRRAQPNLRVRNTYGPTETTLCATWLPIEPGDVVDRELPIGHPMTNRRIYILDAFLRPV
Q939Y9_A1_dpg                            NLRRAQPGLRVRNTYGPTETTLCATWLPIEPGEVLGRELPIGHPMTNRRIYLLDAFLRPV
BGC0000419_AIG79240.1_481_mod1_dpg       NLRRAQPNLRVRNTYGPTETTLCATWLPIEPGDVVDRELPIGHPMTNRRIYILDAFLRPV
Q939Y9_A1_7__dpg                         NLRRAQPGLRVRNTYGPTETTLCATWLPIEPGEVLGRELPIGHPMTNRRIYLLDAFLRPV
BGC0001178_AGS77310.1_492_mod1_dpg       NLRRAQPGVRVRNTYGPTETTLCATWKPIEPGDPLGPELPIGRPMTNRRIYLLDAFLRPV
O52821_A1_7__dpg                         NLRRAQPGLRVRNTYGPTETTLCATWLPIEPGDVIDRELPIGHPMTNRKIYILDAFLRPV
                                         :****** :***************** *****  :. *****:*****:**:********

Q70AZ6_A1_dpg                            APGVAGELYIAGTGLARGYLSRPDLTAERFVACPFLAGERMYRTGDLARWNRDGEVVFLG
Q70AZ6_A1_7__dpg                         APGVAGELYIAGTGLARGYLSRPDLTAERFVACPFLAGERMYRTGDLARWNRDGEVVFLG
BGC0000418_AHF20585.1_481_mod1_dpg       APGVAGELYIAGTGLARGYLDSPGLTSERFVACPFLPGERMYRTGDLARWTRGGEVVFLE
Q939Y9_A1_dpg                            PPGVAGELYIAGTGLAHGYLKSPGLTAGRFVACPFAAGERMYRTGDRARWTRDGEVVFLG
BGC0000419_AIG79240.1_481_mod1_dpg       APGVAGELYIAGTGLARGYLDSPGLTSERFVACPFLPGERMYRTGDLARWTRGGEVVFLE
Q939Y9_A1_7__dpg                         PPGVAGELYIAGTGLAHGYLKSPGLTAGRFVACPFAAGERMYRTGDRARWTRDGEVVFLG
BGC0001178_AGS77310.1_492_mod1_dpg       APGVAGEVYIAGTGLARGYLSRPDLTAERFVACPFLAGERMYRTGDLARWNRDGEVVFLG
O52821_A1_7__dpg                         PPGVAGELYIAGTGLARGYLDSPGLTADRFVACPFLAGERMYRTGDVARWTRDGEVVFLG
                                         .******:********:***. *.**: ******* .********* ***.*.****** 

Q70AZ6_A1_dpg                            RADDQVKIRGYRVELAEVEAVLAAQPGVREAVVVAREDRPGERRLVGYVVSDAGELDTEQ
Q70AZ6_A1_7__dpg                         RADDQVKIRGYRVELAEVEAVLAAQPGVREAVVVAREDRPGERRLVGYVVSDAGELDTEQ
BGC0000418_AHF20585.1_481_mod1_dpg       RADDQVKIRGYRVELGEVESVLAAQPGVVEAVVMAREDQPGEKRLVGYFVSDGGDAGPEE
Q939Y9_A1_dpg                            RADDQVKIRGYRVELGEVEAALAAQPGVVEAVVTAREDQPGEKRLVGYFVSDGGDAGPVE
BGC0000419_AIG79240.1_481_mod1_dpg       RADDQVKIRGYRVELGEVESVLAAQPGVVEAVVMAREDQPGEKRLVGYFVSDGGDAGPEE
Q939Y9_A1_7__dpg                         RADDQVKIRGYRVELGEVEAALAAQPGVVEAVVTAREDQPGEKRLVGYFVSDGGDAGPVE
BGC0001178_AGS77310.1_492_mod1_dpg       RADDQVKIRGFRVELAEVEAVLAAQPGVREAVVVAREYQPGERRLVGYVVSDAGEVDTEE
O52821_A1_7__dpg                         RADDQVKIRGYRVELGEVEAVLAAQPGVVEAVVMAREDQPGEKRLVGYFVSDGSDAGPAE
                                         **********:****.***:.******* **** *** :***:*****.***..: .. :
