CLUSTAL W multiple sequence alignment


BGC0000369_AHZ20774.1_1541_mod2_gln      AKVNLLLTR---SELKVNYGETICLDIYKEEIETQFTDNLEITVFPDNIAYIIFTSGSTG
AHZ20774.1_1541_mod2_gln                 AKVNLLLTR---SELKVNYGETICLDIYKEEIETQFTDNLEITVFPDNIAYIIFTSGSTG
O33743_A2_6__gln                         SQAPILLTQRHLQELAAYQGEII--DVDEEAIYTGADTNLDNVAGKDDLAYVIYTSGSTG
                                         ::. :***:   .** .  ** *  *: :* * *    **: ..  *::**:*:******

BGC0000369_AHZ20774.1_1541_mod2_gln      RPKGVAVSHQALAYHQNWFLENFTVNNHDIVLQKTPFSFDASVWEFWTPLMVGAKLVMAK
AHZ20774.1_1541_mod2_gln                 RPKGVAVSHQALAYHQNWFLENFTVNNHDIVLQKTPFSFDASVWEFWTPLMVGAKLVMAK
O33743_A2_6__gln                         NPKGVMISHQAICNHMLWMRETFPLTTEDAVLQKTPFSFDASVWEFYLPLITGGQLVLAK
                                         .**** :****:. *  *: *.*.:...* ****************: **:.*.:**:**

BGC0000369_AHZ20774.1_1541_mod2_gln      PGGHQDPAYLVKTIQQENVTLLQLVPSLLEIILGEPKFSQCSSLRLVFSGGEALKKRVWH
AHZ20774.1_1541_mod2_gln                 PGGHQDPAYLVKTIQQENVTLLQLVPSLLEIILGEPKFSQCSSLRLVFSGGEALKKRVWH
O33743_A2_6__gln                         PDGHRDIAYMTRLIRDEKITTLQMVPSLLDLVMTDPGWSACTSLQRVFCGGEALTPALVS
                                         *.**:* **:.: *::*::* **:*****:::: :* :* *:**: **.*****.  :  

BGC0000369_AHZ20774.1_1541_mod2_gln      DFKDNLAIPLINLYGPAETTIDVAVHDCRENENADIIPIGEPVTNTKLYVLNSHLQPVPV
AHZ20774.1_1541_mod2_gln                 DFKDNLAIPLINLYGPAETTIDVAVHDCRENENADIIPIGEPVTNTKLYVLNSHLQPVPV
O33743_A2_6__gln                         RFYETQQAQLINLYGPTETTIDATYWPCPRQQEYSAIPIGKPIDNVRLYVVNASNQLQPV
                                          * :.    *******:*****.:   * .::: . ****:*: *.:***:*:  *  **

BGC0000369_AHZ20774.1_1541_mod2_gln      GTPGELFVSGYQLARGYWNAPGMTGERFLPDPFVEGERMYRTGDRARYLPDGTIEFLGRA
AHZ20774.1_1541_mod2_gln                 GTPGELFVSGYQLARGYWNAPGMTGERFLPDPFVEGERMYRTGDRARYLPDGTIEFLGRA
O33743_A2_6__gln                         GVAGELCIAGDGLARGYWQREELTKASFVDNPFEPGGTMYRTGDMVRYLPDGHIEYLGRI
                                         *..*** ::*  ******:   :*   *: :**  *  ****** .****** **:*** 

BGC0000369_AHZ20774.1_1541_mod2_gln      DQQVKIRGFRIETAEIVAALEQQTWVNRAVVKAITTPGKPNRLIAYLQLQETITN--
AHZ20774.1_1541_mod2_gln                 DQQVKIRGFRIETAEIVAALEQQTWVNRAVVKAITTPGKPNRLIAYLQLQETITN--
O33743_A2_6__gln                         DHQVKIRGHRIELGEIEATLLQHEAVKAVVVMARQDGKGQNSLYAYVVAEQDIQTAE
                                         *:******.*** .** *:* *:  *: .** *       * * **:  :: * .  
