CLUSTAL W multiple sequence alignment


AHF21228.1_12993_mod10_glu               SGATVVIT-----SRVAYLSLSLPSTVQAVVLDDEDVQAQLNVQDASNLIPVVGPHNLAY
Q6YK40_A4_glu                            SGAKVLLAQTHLQDRVSFAG-------EILLLNDE----RMNSGDSSNLVTAAGPDHLAY
Q70JZ9_A4_glu                            SGAKVLLAQPHLQDRVSFAG-------EILLLNDE----RMNSGDGSNLVTAAGPDHLAY
BGC0000449_AHF21228.1_12993_mod10_glu    SGATVVIT-----SRVAYLSLSLPSTVQAVVLDDEDVQAQLNVQDASNLIPVVGPHNLAY
                                         ***.*:::     .**:: .       : ::*:**    ::*  *.***:...**.:***

AHF21228.1_12993_mod10_glu               MIYTSGTTGQPKGVMIEQGSVSNLVDALSERVYSRYEQPLHVAWLSAFVFDASVKQIFAS
Q6YK40_A4_glu                            VIYTSGTTGKPKGTLIEHRQVLHLMEGLRGQVYGAYDSGLRVSLLAPYYFDASVKQIFAS
Q70JZ9_A4_glu                            VIYTSGTTGKPKGTLIEHRQVLHLMEGLRGQVYGAYDSGLRVSLLAPYYFDASVKQIFAA
BGC0000449_AHF21228.1_12993_mod10_glu    MIYTSGTTGQPKGVMIEQGSVSNLVDALSERVYSRYEQPLHVAWLSAFVFDASVKQIFAS
                                         :********:***.:**: .* :*::.*  :**. *:. *:*: *:.: **********:

AHF21228.1_12993_mod10_glu               LLLGHTLHVVSRDVSLNGEQLVAYYRTHRIDLSDGTPAHLHILNENVNVTEAPGV--KHY
Q6YK40_A4_glu                            LLGGHALYIVPKASVSDGYALSNYYRTHRIDVTDGTPSHLQLL---IAADSLHGVTIRHM
Q70JZ9_A4_glu                            LLGGHALYIVPKASVSDGYALSNYYRTHRIDVTDGTPSHLQLL---IAADSLHGVTIRHM
BGC0000449_AHF21228.1_12993_mod10_glu    LLLGHTLHVVSRDVSLNGEQLVAYYRTHRIDLSDGTPAHLHILNENVNVTEAPGV--KHY
                                         ** **:*::*.:    :*  *  ********::****:**::*   : . .  **  :* 

AHF21228.1_12993_mod10_glu               LIGGEALS----VQLVNGFLHKWSGYRPVITNVYGPTETTVDATAYTLEDVEALNVLLEK
Q6YK40_A4_glu                            LIGGEALPQATVAQLLELFASNGSSM-PLITNVYGPTETCVDASVFHIVP-ETLASADDG
Q70JZ9_A4_glu                            LIGGEALPQATVAQLLELFASNGSSM-PLITNVYGPTETCVDASVFHIVP-ETLASADDG
BGC0000449_AHF21228.1_12993_mod10_glu    LIGGEALS----VQLVNGFLHKWSGYRPVITNVYGPTETTVDATAYTLEDVEALNVLLEK
                                         *******.    .**:: *  : *.  *:********** ***:.: :   *:*    : 

AHF21228.1_12993_mod10_glu               GEHTVSIGTPIANQSVYILNTQQQLVPIGIVGELYIGGAGVGRGYLNLPQLTAEKFLPNP
Q6YK40_A4_glu                            G--YVPIGKPLGNNRVYIVDSHDRMLPIGVKGELCIAGDGVGRGYLNLPELTGEKFVADP
Q70JZ9_A4_glu                            G--YVPIGKPLGNNRVYIVDSHDRMLPIGVKGELCIAGDGVGRGYLNLPELTGVKFVADP
BGC0000449_AHF21228.1_12993_mod10_glu    GEHTVSIGTPIANQSVYILNTQQQLVPIGIVGELYIGGAGVGRGYLNLPQLTAEKFLPNP
                                         *   *.**.*:.*: ***::::::::***: *** *.* **********:**. **:.:*

AHF21228.1_12993_mod10_glu               FALSEAGEAPDAYIHRMYRTGDLARWLPDGSIEYLGRIDHQVKIRGYRIELGEVEAQLLT
Q6YK40_A4_glu                            FVIGE----------RMYKTGDLARYLPDGNIEYAGRKDHQVKIRGYRIELGEVEAALLN
Q70JZ9_A4_glu                            FVIGE----------RMYKTGDLARYLPDGNIEYAGRKDHQVKIRGYRIELGEVEAALLN
BGC0000449_AHF21228.1_12993_mod10_glu    FALSEAGEAPDAYIHRMYRTGDLARWLPDGSIEYLGRIDHQVKIRGYRIELGEVEAQLLT
                                         *.:.*          ***:******:****.*** ** ****************** **.

AHF21228.1_12993_mod10_glu               VDGIQKAVVTAWENEDGHKDLCAYIVATAPLSLPE
Q6YK40_A4_glu                            IEHVQEAVILARENAEGQSDLYAYFTGEKSLPINQ
Q70JZ9_A4_glu                            IEHVQEAVILARENAEGQSDLYAYFTGEKSLPINQ
BGC0000449_AHF21228.1_12993_mod10_glu    VDGIQKAVVTAWENEDGHKDLCAYIVATAPLSLPE
                                         :: :*:**: * ** :*:.** **:..  .*.: :
