CLUSTAL W multiple sequence alignment


BGC0000398_AFH75328.1_1544_mod2_glu      SQPRVLLVQQSTRHLLQGPGLALLDFDHAAWHHQPGHDPQVPGLNVSHLAYVIYTSGSTG
AFZ61501.1_1515_mod2_glu                 SQPVALLVHAATRDLPGDVSIPVIDFDHCAWSQAPIGNPLVPGLSVANLAYVMYTSGSTG
                                         *** .***: :**.*  . .:.::****.** : *  :* ****.*::****:*******

BGC0000398_AFH75328.1_1544_mod2_glu      TPKGVMVEHRGLGNLMHWGSQLCPQSGGGTLLQKAPFSFDGSVWELFWPLVTGMRLLLAR
AFZ61501.1_1515_mod2_glu                 TPKGVMIEHRGLGNLMHWGSQLCPNAEGGALLQRAPFSFDGSVWELFWPLTNGMRLVLAR
                                         ******:*****************:: **:***:****************..****:***

BGC0000398_AFH75328.1_1544_mod2_glu      PGGQREPTYLAQLVVEQQVTMVKFVPAMLLQFLQLEESGQCQSLTDVFCGGGELTEAIAR
AFZ61501.1_1515_mod2_glu                 PDGHREPAYLAQVIREQQISVIKFVPAMLQQFLELEESALCTSLTDVLCGGGELTEALAR
                                         *.*:***:****:: ***::::******* ***:****. * *****:*********:**

BGC0000398_AFH75328.1_1544_mod2_glu      LFRQRLPRARLHNVYGPTEATVDSTAWTLEPGAAIPAVQLPIGRAITNTRLYVLDTHDQP
AFZ61501.1_1515_mod2_glu                 GVQARLPKVRLHNVYGPTEATVDSSAWTLEPGAPVPALQLPIGRAINNTRLYVLDEHDRP
                                          .: ***:.***************:********.:**:********.******** **:*

BGC0000398_AFH75328.1_1544_mod2_glu      VPRGVSGQLHIGGVGVARGYLGLAQLQAERFIDSPFVAGDRLYRTGDLVRYGDDGNLEFL
AFZ61501.1_1515_mod2_glu                 TPMGVSGQLHIGGVGVARGYLGLEQMTAERFIDSPFVDGDRLYRTGDLVRYLPDGNLEFL
                                         .* ******************** *: ********** *************  *******

BGC0000398_AFH75328.1_1544_mod2_glu      GRNDFQIKLRGLRLEPGEIEARLASHPAVREVAVLMRSERLVAYYSLHPGASAPGVEG
AFZ61501.1_1515_mod2_glu                 GRNDFQVKLRGVRLELGEIESRLMAHQALREVAVLIRDERLVAYFTVR--GQAPSLEA
                                         ******:****:*** ****:** :* *:******:*.******::::  ..**.:*.
