CLUSTAL W multiple sequence alignment


O30981_A1_5__glu                         SGAALLLTQP-GLKAPVFSGKTLEVDMTALANEESECHSLHQADSDSLAYVIYTSGSTGR
P39847_A1_glu                            SGASLLLTQP-GCSAPNFSGETLEVDMTSLECEEVKRHVSASVSDGSLAYVIYTSGSTGQ
P39845_A1_glu                            SGASLLLTQP-GCSAPNFSGETLEVDMTSLASEKAENHEFTPADGGSLAYVIYTSGSTGQ
O87606_A1_glu                            SGAALLLTQP-GLKAPVFSGKTLEVDMTSLANEESEYHSLHQADSDSLAYVIYTSGSTGQ
Q70JX1_A1_glu                            CGACLLLAQP-GLSVSGFSGETLEVSLSALTGETETGAVSEEADSNSLAYIIYTSGSTGT
O30980_A2_glu                            SDSDILLIQSDNLDIPAFDGEIVHLSQLNSGLKRRLSNPNVEVYPDSLAYMIYTSGSTGR
                                         ..: :** *. . . . *.*: :.:.      :         .  .****:******** 

O30981_A1_5__glu                         PKGVAVEHRQAVSFLTGMQMQFPLEEDDIIMMKTSFSFDASVWQLFWWTLSGASAYLLPS
P39847_A1_glu                            PKGVAVEHRQAVSFLTGMQHQFRLSEDDIVMVKTSFSFDASVWQLFWWALSGASAYLLPP
P39845_A1_glu                            PKGVAVEHRQAVSFLTGMQHQFPLSEDDIVMVKTSFSFDASVWQLFWWSLSGASAYLLPP
O87606_A1_glu                            PKGVAVEHLQAVSFLTGMQMQFPLEEDDIIMMKTSFSFDASVWQLFWWTLSGASAYLLPS
Q70JX1_A1_glu                            PKGVAVEHRQAAAFLSGMQGQFPLTEEDVIVLKSSFSFDASIWQLFWWTMSGASVYLLPA
O30980_A2_glu                            PKGVQVEHQSAVNFLNSLQFRYPLNQSDVILHKTSYSFDASIWELFWWPYGGASVYLLPQ
                                         **** *** .*. **..:* :: * :.*::: *:*:*****:*:****. .***.**** 

O30981_A1_5__glu                         GWEKDPALMVKAIREEGVTTAHFIPAMLNSFLDQAEIE--APR-----SLKRVFAGGEPL
P39847_A1_glu                            GWEKDSALIVQAIHQENVTTAHFIPAMLNSFLDQAEIERLSDRT----SLKRVFAGGEPL
P39845_A1_glu                            GWEKDSALIVQAIHQENVTTAHFIPAMLNSFLDQAEIERLSDRT----SLKRVFAGGEPL
O87606_A1_glu                            GWEKDPALMVKAIREEGVTTAHFIPAMLNSFLDQAEIE--APR-----SLKRVFAGGEPL
Q70JX1_A1_glu                            GWEKDPVRMIKAFASEKVTTAHFIPAMVNSFLDALETEPAETRTRLGRTLTRVFAGGEAL
O30980_A2_glu                            GGEKEPDMILKVIEEQQITAMHFVPSMLHAFLEYLKNGPVPIKTN---RLKRVFSGGEQL
                                         * **:.  :::.: .: :*: **:*:*:::**:  :      :      *.***:*** *

O30981_A1_5__glu                         APHTAARFASLLPETSLVHGYGPTEATVDAAFYAC--DPELDKNRLRLPIGKPVPGARLY
P39847_A1_glu                            APRTAARFASVLPQVSLIHGYGPTEATVDAAFYVL--DPERDRDRLRIPIGKPVPGARLY
P39845_A1_glu                            APRTAARFASVLPQVSLIHGYGPTEATVDAAFYVL--DPERDRDRLRIPIGKPVPGARLY
O87606_A1_glu                            APHTAARFASLLPETSLVHGYGPTEATVDAAFYAC--DPELDKDRLRLPIGKPVPGARLY
Q70JX1_A1_glu                            SPLTAARFADLLPETVLIHGYGPTEATVDAAFYVC--DRKRDSGRTRLPIGKPVPGARLY
O30980_A2_glu                            GAHLVSRFCELLPDVTLTNSYGPTEATVEAAFFDCPLDEKLD----RIPIGKPIHHVRLY
                                         ..  .:**..:**:. * :.********:***:    * : *    *:*****:  .***

O30981_A1_5__glu                         VLDPHLAVQPVGVAGELYIAGAGVARGYLNRPELTEERFLDDPFYPGERMYKTGDLARWL
P39847_A1_glu                            VLDPHLAVQPSGVAGELYIAGAGVARGYLNRPALTEERFLEDPFYLGERMYKTGDVARWL
P39845_A1_glu                            VLDPHLAVQPSGVAGELYIAGAGVARGYLNRPALTEERFLEDPFYPGERMYKTGDVARWL
O87606_A1_glu                            VLDPHLAVQPVGVAGELYIAGAGVARGYLNRPELTEERFLDDPFYPGERMYKTGDLAHWL
Q70JX1_A1_glu                            VLDSGGTIQPAGVAGELYIAGTGVARGYLNRPELTEERFLDDPFYPGERMYQTGDIARWT
O30980_A2_glu                            ILNQKQKMLPAGCIGELYIAGAGVARGYLNRPELTEERFLDDPFYPGERMYKTGDLARWL
                                         :*:    : * *  *******:********** *******:**** *****:***:*:* 

O30981_A1_5__glu                         PDGQVEFLGRLDDQVKIRGYRIEPGEIEAALRSIEGVREAAVTVRTESGEAELCAYAEGL
P39847_A1_glu                            PDGNVEFLGRTDDQVKIRGYRIEPGEIEAALRSIEGVREAAVTVRTDSGEPELCAYVEGL
P39845_A1_glu                            PDGNVEFLGRTDDQVKIRGYRIEPGEIEAALRSIEGVREAAVTVRTDSGEPELCAYVEGL
O87606_A1_glu                            PDGQVEFLGRLDDQVKIRGYRIEPGECEAALRSIEGVRDAAVTVRTESGEAELCAYAEGL
Q70JX1_A1_glu                            EDGLVEWLGRSDGQVKVRGYRIEPGEIEAAIRRIDGIREAAVTARNEHGETALYAYIEGR
O30980_A2_glu                            PDGQVEFLGRLDDQVKIRGYRIEPGEIEAALRSIEGVREAAVTVRTESGEAELCAYAEGL
                                          ** **:*** *.***:********* ***:* *:*:*:****.*.: **. * ** ** 

O30981_A1_5__glu                         GRNEV
P39847_A1_glu                            QRNEV
P39845_A1_glu                            QRNEV
O87606_A1_glu                            GRNEV
Q70JX1_A1_glu                            ESDDV
O30980_A2_glu                            GRNEV
                                           ::*
