CLUSTAL W multiple sequence alignment


O68006_A4_glu                            SDVSVLCAAGDVDPGEAYTG-------DIIRID------QTGQNDHVENLKHDIKPQHLA
Q6YK40_A4_glu                            SGAKVLLAQTHLQDRVSFAG-------EILLLNDE----RMNSGD-SSNLVTAAGPDHLA
AHF21228.1_12993_mod10_glu               SGATVVIT-----SRVAYLSLSLPSTVQAVVLDDEDVQAQLNVQD-ASNLIPVVGPHNLA
Q70JZ9_A4_glu                            SGAKVLLAQPHLQDRVSFAG-------EILLLNDE----RMNSGD-GSNLVTAAGPDHLA
BGC0000449_AHF21228.1_12993_mod10_glu    SGATVVIT-----SRVAYLSLSLPSTVQAVVLDDEDVQAQLNVQD-ASNLIPVVGPHNLA
                                         *...*: :        :: .       : : ::      : .  *  .**     *.:**

O68006_A4_glu                            YVIYTSGSTGKPKGVMIEHHSVNNLVHGLNERIYQHLDAHLNVALVAPYIFDASVKQIFA
Q6YK40_A4_glu                            YVIYTSGTTGKPKGTLIEHRQVLHLMEGLRGQVYGAYDSGLRVSLLAPYYFDASVKQIFA
AHF21228.1_12993_mod10_glu               YMIYTSGTTGQPKGVMIEQGSVSNLVDALSERVYSRYEQPLHVAWLSAFVFDASVKQIFA
Q70JZ9_A4_glu                            YVIYTSGTTGKPKGTLIEHRQVLHLMEGLRGQVYGAYDSGLRVSLLAPYYFDASVKQIFA
BGC0000449_AHF21228.1_12993_mod10_glu    YMIYTSGTTGQPKGVMIEQGSVSNLVDALSERVYSRYEQPLHVAWLSAFVFDASVKQIFA
                                         *:*****:**:***.:**: .* :*:..*  ::*   :  *.*: ::.: **********

O68006_A4_glu                            ALLFGHTLCIVPRETAWDAMSLIEYYSKNNINVSDMTPAHLNML-AYVDKTELEFD-VKE
Q6YK40_A4_glu                            SLLGGHALYIVPKASVSDGYALSNYYRTHRIDVTDGTPSHLQLL---IAADSLHGVTIRH
AHF21228.1_12993_mod10_glu               SLLLGHTLHVVSRDVSLNGEQLVAYYRTHRIDLSDGTPAHLHILNENVNVTEAPGV--KH
Q70JZ9_A4_glu                            ALLGGHALYIVPKASVSDGYALSNYYRTHRIDVTDGTPSHLQLL---IAADSLHGVTIRH
BGC0000449_AHF21228.1_12993_mod10_glu    SLLLGHTLHVVSRDVSLNGEQLVAYYRTHRIDLSDGTPAHLHILNENVNVTEAPGV--KH
                                         :** **:* :*.:    :.  *  ** .:.*:::* **:**::*   :   .      :.

O68006_A4_glu                            LIVGGDALT----PDVIGGLFHKFPNLSCNITNVYGPTECCVDAASHQIES---------
Q6YK40_A4_glu                            MLIGGEALPQATVAQLLELFASNGSSM-PLITNVYGPTETCVDASVFHIVP-ETLASADD
AHF21228.1_12993_mod10_glu               YLIGGEALS----VQLVNGFLHKWSGYRPVITNVYGPTETTVDATAYTLEDVEALNVLLE
Q70JZ9_A4_glu                            MLIGGEALPQATVAQLLELFASNGSSM-PLITNVYGPTETCVDASVFHIVP-ETLASADD
BGC0000449_AHF21228.1_12993_mod10_glu    YLIGGEALS----VQLVNGFLHKWSGYRPVITNVYGPTETTVDATAYTLEDVEALNVLLE
                                          ::**:**.     :::  :  : ..    *********  ***: . :           

O68006_A4_glu                            -GKVPQTPSIPIGRPLLNTSIYIVDKELRPLPVGIAGELCIAGEGVARGYVNRPELTAEK
Q6YK40_A4_glu                            GG------YVPIGKPLGNNRVYIVDSHDRMLPIGVKGELCIAGDGVGRGYLNLPELTGEK
AHF21228.1_12993_mod10_glu               KGE----HTVSIGTPIANQSVYILNTQQQLVPIGIVGELYIGGAGVGRGYLNLPQLTAEK
Q70JZ9_A4_glu                            GG------YVPIGKPLGNNRVYIVDSHDRMLPIGVKGELCIAGDGVGRGYLNLPELTGVK
BGC0000449_AHF21228.1_12993_mod10_glu    KGE----HTVSIGTPIANQSVYILNTQQQLVPIGIVGELYIGGAGVGRGYLNLPQLTAEK
                                          *       :.** *: *  :**::.. : :*:*: *** *.* **.***:* *:**. *

O68006_A4_glu                            FVDHPFEPGK----------KMYKTGDLAMWLPDGQIEFLGRADHQVKIRGYRIELGEVE
Q6YK40_A4_glu                            FVADPFVIGE----------RMYKTGDLARYLPDGNIEYAGRKDHQVKIRGYRIELGEVE
AHF21228.1_12993_mod10_glu               FLPNPFALSEAGEAPDAYIHRMYRTGDLARWLPDGSIEYLGRIDHQVKIRGYRIELGEVE
Q70JZ9_A4_glu                            FVADPFVIGE----------RMYKTGDLARYLPDGNIEYAGRKDHQVKIRGYRIELGEVE
BGC0000449_AHF21228.1_12993_mod10_glu    FLPNPFALSEAGEAPDAYIHRMYRTGDLARWLPDGSIEYLGRIDHQVKIRGYRIELGEVE
                                         *: .**  .:          :**:***** :****.**: ** *****************

O68006_A4_glu                            QQLLTHEKIKEAAVIAGKDQNGNSYLCAYIASDKELPAAD
Q6YK40_A4_glu                            AALLNIEHVQEAVILARENAEGQSDLYAYFTGEKSLPINQ
AHF21228.1_12993_mod10_glu               AQLLTVDGIQKAVVTAWENEDGHKDLCAYIVATAPLSLPE
Q70JZ9_A4_glu                            AALLNIEHVQEAVILARENAEGQSDLYAYFTGEKSLPINQ
BGC0000449_AHF21228.1_12993_mod10_glu    AQLLTVDGIQKAVVTAWENEDGHKDLCAYIVATAPLSLPE
                                           **. : :::*.: * :: :*:. * **:..   *.  :
