CLUSTAL W multiple sequence alignment


BGC0000439_AHH53506.1_5177_mod5_gly      AAPALLVTTDEWAARFAGWDGPL---VRVDR---------------ADDTRCERGAPPIV
Q9L8H4_A2_5__gly                         ARPALLLTDTRTEQHLP--ADADTRRLALDSAEVRALL--------ADCPDTDPAEEGVT
Q9Z4X5_A2_gly                            AGPALTVTEPVAEAGLSGYGDAD-----LGADELRG-----------------PVHG---
EWS95124_9_mod1_gly                      ------------------------------------------------------AHS---
BGC0000439_AHH53507.1_5197_mod5_gly      AAPALAVTTGLLAERVPARENTDV--LLLDDPDV------------AEAVEAEPAELPPM
Q9Z4X5_A2_8__gly                         AGPALTVTEPVAEAGLSGYGDAD-----LGADELRG-----------------PVHG---
AHH53507.1_5197_mod5_gly                 AAPALAVTTGLLAERVPARENTDV--LLLDDPDV------------AEAVEAEPAELPPM
AHH53506.1_5177_mod5_gly                 AAPALLVTTDEWAARFAGWDGPL---VRVDR---------------ADDTRCERGAPPIV
Q45R83_A3_10__gly                        SAPGCVITTTDLARRLPPVPAPL---LVLDDPATAARLAATTATALAEDPREQNG-----
Q50E73_A5_10__gly                        ARPAVVLTTEDISARIPGGSH-----VVLDSEQVTGEL--------HDHPATSPAGRG--
                                                                                                     

BGC0000439_AHH53506.1_5177_mod5_gly      PTRPDTAAYVIYTSGSTGRPKGVVVTEGGLRNFLLDMAERAGLTRASRLLAVTTVAFDIA
Q9L8H4_A2_5__gly                         P-APGSAAYVIYTSGSTGRPKGVVVPHSALVNFVTAMRRQAPLRPQERLLAVTTVAFDIA
Q9Z4X5_A2_gly                            ----AHPAYTIYTSGSTGRPKGVVVPRGALDNFLADMGRRFTPGSGDRLLAVTTVGFDIA
EWS95124_9_mod1_gly                      ----GNPAYIIYTSGSTGAPKGTVVTGENLVNLLSDFRSRLSFGAEDRLLAVTTFGFDIS
BGC0000439_AHH53507.1_5197_mod5_gly      PVAADATAYVIYTSGSTGRPKGVVVTRANLGNFLSDMRGRVGLGAEDRLLAVTTIGFDIA
Q9Z4X5_A2_8__gly                         ----AHPAYTIYTSGSTGRPKGVVVPRGALDNFLADMGRRFTPGSGDRLLAVTTVGFDIA
AHH53507.1_5197_mod5_gly                 PVAADATAYVIYTSGSTGRPKGVVVTRANLGNFLSDMRGRVGLGAEDRLLAVTTIGFDIA
AHH53506.1_5177_mod5_gly                 PTRPDTAAYVIYTSGSTGRPKGVVVTEGGLRNFLLDMAERAGLTRASRLLAVTTVAFDIA
Q45R83_A3_10__gly                        -EWGEELAYTIYTSGSTGRPKGVMVTRSAVANFLADMNERLELGPGDRLLAVTTVSFDIA
Q50E73_A5_10__gly                        --NPAGPAYVIYTSGSTGQPKGVVVPSAALVNFLADMVPRLGLRGGDRLLSVTTVGFDIA
                                                ** ******** ***.:*.   : *::  :  :      .***:***..***:

BGC0000439_AHH53506.1_5177_mod5_gly      GLELFGPLLRGGRVVLAGEDVTRDPAAVLDLCVRHGVTVVQATPSWWRGV-VEQNRERDV
Q9L8H4_A2_5__gly                         ALELYHPLLSGAAVVLAPKEAVPQPSAVLDLIARHGVTTVQGTPSLWQLL-V--GHDAEA
Q9Z4X5_A2_gly                            GLEIFLPLLHGAVLVLADEETARDPHALLHRVSASGITMVQATPSLWQGV-AAVAGDE--
EWS95124_9_mod1_gly                      NLELLLPLISGGRVVLASKETSQDPNALGGLIAASGATVMQATPALWQTL-LA-SGDPEG
BGC0000439_AHH53507.1_5197_mod5_gly      ALELFLPLASGARVVLAAPDVVRDPAAVARLCGRAGITAIQATPSWWRAV-VQ-DGESTR
Q9Z4X5_A2_8__gly                         GLEIFLPLLHGAVLVLADEETARDPHALLHRVSASGITMVQATPSLWQGV-AAVAGDE--
AHH53507.1_5197_mod5_gly                 ALELFLPLASGARVVLAAPDVVRDPAAVARLCGRAGITAIQATPSWWRAV-VQ-DGESTR
AHH53506.1_5177_mod5_gly                 GLELFGPLLRGGRVVLAGEDVTRDPAAVLDLCVRHGVTVVQATPSWWRGV-VEQNRERDV
Q45R83_A3_10__gly                        VLELLAPLLTGGTVVLADATTQRDPAAVRSLCAREGVTVIQATPSWWHAMAVDGGLD---
Q50E73_A5_10__gly                        ALELFVPLLSGATVVLADGETVRDPALARQTCEDHGVTMVQATPSWWHGM-LADAGDS--
                                          **:  **  *. :***   .  :*          * * :*.**: *: :      :   

BGC0000439_AHH53506.1_5177_mod5_gly      LPGIRVLVGGEALPASLATELVASAAS-----VTNLYGPTETTIWSTVDEV--------G
Q9L8H4_A2_5__gly                         LRGLRMLVGGEALPLSLAEALRALTDD-----LVNLYGPTETTIWSTAAELAGG-----T
Q9Z4X5_A2_gly                            LAGVRVLVGGEALPSELARALTDRARS-----VTNLYGPTEATIWATAADVAES-----G
EWS95124_9_mod1_gly                      LRQVKVLVGGEALPRPLAGALRDSARE-----VTNVYGPTETTIWSTAAFLDEE-----N
BGC0000439_AHH53507.1_5197_mod5_gly      LGLGAALVGGEALPADLARALTGVAGS-----VTNVYGPTETTIWSTAAPVTGE-----P
Q9Z4X5_A2_8__gly                         LAGVRVLVGGEALPSELARALTDRARS-----VTNLYGPTEATIWATAADVAES-----G
AHH53507.1_5197_mod5_gly                 LGLGAALVGGEALPADLARALTGVAGS-----VTNVYGPTETTIWSTAAPVTGE-----P
AHH53506.1_5177_mod5_gly                 LPGIRVLVGGEALPASLATELVASAAS-----VTNLYGPTETTIWSTVDEV--------G
Q45R83_A3_10__gly                        LTALRVLVGGEALPPALARTLLEPGRAPLGDYLLNLYGPTETTVWSTVARITADSLEAHG
Q50E73_A5_10__gly                        LRGVHAVVGGEALSPGLRDALTRGARS-----VTNMYGPTETTIWSTSAGQAAG-----D
                                         *     :******.  *   *           : *:*****:*:*:*             

BGC0000439_AHH53506.1_5177_mod5_gly      PGAPTIGRPIGNTQVYVLDAALEPVPPGVPGELYLAGAGLARGYAGRPGLTANRFVACPF
Q9L8H4_A2_5__gly                         GA-APIGRPIANTRVYVLDDGLQPVAPGVVGELYIAGAGLARGYLDRPALTAERFPADPY
Q9Z4X5_A2_gly                            ---PVIGRPLANTSAYVLDSALRPVPVGVPGELYLAGEQLAQGYHLRPALTSERFTADPY
EWS95124_9_mod1_gly                      ADRPPIGLPLANTRAYVLDSALRPVPAGVAGELYLAGAGVARGYLNRPALTAQRFVADPF
BGC0000439_AHH53507.1_5197_mod5_gly      DTRPAIGVPIGNTSVYVLDERLAPVAVGVVGELYIAGDGVARGYRGEPGMTAERFVACPF
Q9Z4X5_A2_8__gly                         ---PVIGRPLANTSAYVLDSALRPVPVGVPGELYLAGEQLAQGYHLRPALTSERFTADPY
AHH53507.1_5197_mod5_gly                 DTRPAIGVPIGNTSVYVLDERLAPVAVGVVGELYIAGDGVARGYRGEPGMTAERFVACPF
AHH53506.1_5177_mod5_gly                 PGAPTIGRPIGNTQVYVLDAALEPVPPGVPGELYLAGAGLARGYAGRPGLTANRFVACPF
Q45R83_A3_10__gly                        GAVPT-GTPIARTAAYVLDAALRPVPDGVPGELYLAGAGLARGYLGRPGMTAERFVACPF
Q50E73_A5_10__gly                        SAPPSIGTPILNTRVYVLDAALCVVPPGVAGELYIAGDGLARGYLGRAGLTAERFVACPF
                                            .  * *: .* .****  *  *. ** ****:**  :*:**  ...:*::** * *:

BGC0000439_AHH53506.1_5177_mod5_gly      G-PAGARMYRTGDLATWRADGRLRYLGRSDDQVKLRGFRIELGEVESAVERHPRVRAAAV
Q9L8H4_A2_5__gly                         GLEPGGRMYRTGDLVRWNPDGELEFVGRADHQVKVRGFRIEPGEIEKVLTDHPDIAQAAV
Q9Z4X5_A2_gly                            G-PAGTRMYRTGDLVCRRRDGALRYLSRVDQQVKLRGFRIELGEIEAELSRHPAVAESAV
EWS95124_9_mod1_gly                      G-PAGGRMYRTGDLVRRHADGNLEFLDRVDHQVKIRGFRIELGEIEGALNQHPAVARAAV
BGC0000439_AHH53507.1_5197_mod5_gly      G-GAGTRMYRTGDLVRWLPDGTLAYVGRADDQVKLRGFRIELGEIETVLRELPDIAGAAV
Q9Z4X5_A2_8__gly                         G-PAGTRMYRTGDLVCRRRDGALRYLSRVDQQVKLRGFRIELGEIEAELSRHPAVAESAV
AHH53507.1_5197_mod5_gly                 G-GAGTRMYRTGDLVRWLPDGTLAYVGRADDQVKLRGFRIELGEIETVLRELPDIAGAAV
AHH53506.1_5177_mod5_gly                 G-PAGARMYRTGDLATWRADGRLRYLGRSDDQVKLRGFRIELGEVESAVERHPRVRAAAV
Q45R83_A3_10__gly                        G-EPGERMYRTGDLARWRADGNLEHLGRTDDQVKVRGFRIELGEVERALTQAHGVGRAAA
Q50E73_A5_10__gly                        G-APGERMYRTGDLVRWRVDGALEFVGRADDQVKVRGFRVELGEVEGAVAAHPDVVRAVV
                                         *  .* ********.    ** * .:.* *.***:****:* **:*  :     :  :..

BGC0000439_AHH53506.1_5177_mod5_gly      AVRETQAGGRTLVAYVVP-TAG-GVVDADA------
Q9L8H4_A2_5__gly                         VVREDQPGDARLVAYVVT-GGSADARDEQ-------
Q9Z4X5_A2_gly                            TVREDRPGDRRLVGYVVPKGPEGPAGPTGPVPSARE
EWS95124_9_mod1_gly                      VVHEDQAGEKRLVAYTVP-APGHDAADTAS------
BGC0000439_AHH53507.1_5197_mod5_gly      MVREDRPGDRRLAGYVVP-APGAEPDRAR-------
Q9Z4X5_A2_8__gly                         TVREDRPGDRRLVGYVVPKGPEGPAGPTGPVPSARE
AHH53507.1_5197_mod5_gly                 MVREDRPGDRRLAGYVVP-APGAEPDRAR-------
AHH53506.1_5177_mod5_gly                 AVRETQAGGRTLVAYVVP-TAG-GVVDADA------
Q45R83_A3_10__gly                        AVHPDAAGSARLVGYLVP-AGGSGALDEKA------
Q50E73_A5_10__gly                        VVREDRPGDHRLVAYVTGVDTGGLS-----------
                                          *:   .*   *..* .                   
