CLUSTAL W multiple sequence alignment


Q5DIP4_A4_7__horn                        SGIALLLSESQALVQLPVPAGVPALALDRL-DLLEHPAQAPQVEVHPANLAYVIYTSGST
Q5DIS9_A2_6__horn                        CGAALVLTQRDVLERLPLPAGLASLAVDDPGEWQDRPEGAPEVDLAEENLAYVIYTSGST
Q5DIS7_A3_horn                           CGAALVLTQRDVLERLPLPAGLASLAVDDPGEWQDRPEGAPEVDLAEENLAYVIYTSGST
Q5DIV8_A2_6__horn                        SRAHLLLTHSHLLERLPIPEGLSCLSVDREEEWAGFPAHDPEVALHGDNLAYVIYTSGST
Q5DIP3_A2_horn                           SRAHLLLTQSHLLDRLPIPDGLSCLCLDREQEWAGFPAHDPEVALHGDNLAYVIYTSGST
Q5DIV7_A4_horn                           SRAHLLLTHSHLLERLPIPEGLSCLSVDREEEWAGFPAHDPEVALHGDNLAYVIYTSGST
                                         .   *:*:. . * :**:* *:..*.:*   :    *   *:* :   ************

Q5DIP4_A4_7__horn                        GLPKGVAVSHGPLAMHIDAVGERYEMTPADRELHFMSFAFDGAHERWLTALGHGGSLLLR
Q5DIS9_A2_6__horn                        GLPKGVAVSHGPLVSHIRATGERYETSPADCELHFMSFAFDGAHEGWMHPLINGARVLVR
Q5DIS7_A3_horn                           GLPKGVAVSHGPLVSHIRATGERYETSPADCELHFMSFAFDGAHEGWMHPLINGARVLVR
Q5DIV8_A2_6__horn                        GMPKGVAVSHGPLIAHIVATGERYEMTPEDCELHFMSFAFDGSHEGWMHPLINGARVLIR
Q5DIP3_A2_horn                           GMPKGVAVSHGPLAAHIVATGERYEMTPADCELHFMSFAFDGSHEGWMHPLINGARVLIR
Q5DIV7_A4_horn                           GMPKGVAVSHGPLIAHIVATGERYEMTPEDCELHFMSFAFDGSHEGWMHPLINGARVLIR
                                         *:***********  ** *.***** :* * ***********:** *: .* :*. :*:*

Q5DIP4_A4_7__horn                        DDALWTPEQTYAAMQRHGVTVAAFPPVYLQQLAEHAERDGNPPPVRIYCFGGDAVPVAGF
Q5DIS9_A2_6__horn                        DDSIWLPEETYAQMHRHGVTIGVFPPVYLQQLAEHAERDGNPPPVRVYCFGGDAVPQASY
Q5DIS7_A3_horn                           DDSIWLPEETYAQMHRHGVTIGVFPPVYLQQLAEHAERDGNPPPVRVYCFGGDAVPQASY
Q5DIV8_A2_6__horn                        DDSLWLPERTYAEMHRHGVTVGVFPPVYLQQLAEHAERDGNPPPVRVYCFGGDAVAQASY
Q5DIP3_A2_horn                           DDSLWLPEQTYAQMHRHGVTVAVFPPVYLQQLAEHAERDGNPPAARVYCFGGDAVAQASY
Q5DIV7_A4_horn                           DDSLWLPERTYAEMHRHGVTVGVFPPVYLQQLAEHAERDGNPPPVRVYCFGGDAVAQASY
                                         **::* **.*** *:*****:..********************..*:********. *.:

Q5DIP4_A4_7__horn                        ELAKRALKPRYIINGYGPTETVVTPLIWKAAMDTECGAAYAPIGSFVGERCGYVLDADLN
Q5DIS9_A2_6__horn                        ELAWESLRPDYLFNGYGPTETVVTPLLWKARPQDPCGAAYAPIGTLLGRRRAYVLGADLD
Q5DIS7_A3_horn                           ELAWESLRPDYLFNGYGPTETVVTPLLWKARPQDPCGAAYAPIGTLLGRRRAYVLGADLD
Q5DIV8_A2_6__horn                        DLAWRALKPKYLFNGYGPTETVVTPLLWKARAGDACGAAYMPIGTLLGNRSGYILDGQLN
Q5DIP3_A2_horn                           DLAWRALRPQYLFNGYGPTETVVTPLLWKARPDDPCGAAYMPIGTLLGNRSGYILDAQLN
Q5DIV7_A4_horn                           DLAWRALKPKYLFNGYGPTETVVTPLLWKARAGDACGAAYMPIGTLLGNRSGYILDGQLN
                                         :** .:*:* *::*************:***     ***** ***:::*.* .*:*..:*:

Q5DIP4_A4_7__horn                        PLPAGVAGELYLGGVGLARGYLQRPGLSAERFVANPFSRTGERLYRTGDLVRQREDGTFD
Q5DIS9_A2_6__horn                        LLPLGLAGELYLGGEGVARGYLDRPALTAERFVPDPYGN-GERVYRSGDLTRARADGLVD
Q5DIS7_A3_horn                           LLPLGLAGELYLGGEGVARGYLDRPALTAERFVPDPYGN-GERVYRSGDLTRARADGLVD
Q5DIV8_A2_6__horn                        LLPVGVAGELYLGGEGVARGYLERPALTAERFVPDPFGAPGSRLYRSGDLTRGRADGVVD
Q5DIP3_A2_horn                           LLPVGVAGELYLGGEGVARGYLERPALTAERFVPDPFGAPGSRLYRSGDLTRGRADGVVD
Q5DIV7_A4_horn                           LLPVGVAGELYLGGEGVARGYLERPALTAERFVPDPFGAPGSRLYRSGDLTRGRADGVVD
                                          ** *:******** *:*****:**.*:*****.:*:.  *.*:**:***.* * ** .*

Q5DIP4_A4_7__horn                        YLGRIDNQVKVRGFRIELGEIEARLQDAGEVREAVVVARDAASGKQLLGYVVAEDGADAS
Q5DIS9_A2_6__horn                        YLGRVDHQVKIRGFRIELGEIEARLLEQECVREAVVLARDGASGKQLVGYVVPQDVGALE
Q5DIS7_A3_horn                           YLGRVDHQVKIRGFRIELGEIEARLLEQECVREAVVLARDGANGKQLVGYVVPQDVGALE
Q5DIV8_A2_6__horn                        YLGRVDHQVKIRGFRIELGEIEARLREHPAVREAVVVAQPGAVGQQLVGYVVAQEPAVAD
Q5DIP3_A2_horn                           YLGRVDHQVKIRGFRIELGEIEARLREQAAVREAVVVAQAGASGQQLVGYVVPQDPALVE
Q5DIV7_A4_horn                           YLGRVDHQVKIRGFRIELGEIEARLREHPAVREAVVVAQPGAVGQQLVGYVVAQEPAVAD
                                         ****:*:***:************** :   ******:*: .* *:**:****.:: .  .

Q5DIP4_A4_7__horn                        GL
Q5DIS9_A2_6__horn                        DE
Q5DIS7_A3_horn                           GE
Q5DIV8_A2_6__horn                        SP
Q5DIP3_A2_horn                           DA
Q5DIV7_A4_horn                           SP
                                         . 
