CLUSTAL W multiple sequence alignment


Q93N87_A1_hpg|hpg2cl                     CDPAAVVCSERTRVVVPEDVPAPLVPLDEASILD--GE-PLSLPVAGGDIAYVMYTSGST
Q93N88_A1_3__hpg|hpg2cl                  ---------------MVED-SAPVLTIDDPSVVTAEGE-PEVVETAGGDIAYVMYTSGST
Q93N87_A2_hpg|hpg2cl                     ---------------VLED-SSPAVTID--AVVKGGGE-APSVAVTEGDLAYVMYTSGST
Q93N87_A2_5__hpg|hpg2cl                  ---------------VLED-SSPAVTID--AVVKGGGE-APSVAVTEGDLAYVMYTSGST
Q93N89_A1_hpg|hpg2cl                     ---------------VLKN-STPAVTID--AVVEGAGD-ASSVALDGDDLAYVMYTSGST
Q93N86_A1_7__hpg|hpg2cl                  SAPTAVLCSRSTRGAVPEDTPVSPLVLDD---LTAKGETPSPVPCAADDIAYVMYTSGSS
Q93N87_A1_4__hpg|hpg2cl                  CDPAAVVCSERTRVVVPEDVPAPLVPLDEASILD--GE-PLSLPVAGGDIAYVMYTSGST
Q93N89_A1_1__hpg|hpg2cl                  ---------------VLKN-STPAVTID--AVVEGAGD-ASSVALDGDDLAYVMYTSGST
                                                        : :: . . : :*    :   *: .  :    .*:*********:

Q93N87_A1_hpg|hpg2cl                     GVPKGVAVPHGSVAALVGEPGWAVGPGDSVLFHAPHAFDISLFEVWVPLASGARVEVAEP
Q93N88_A1_3__hpg|hpg2cl                  GTPKGVAVPHASVAALVGEPGWGVGPGDAVLFHAPHAFDISLFEVWVPLASGGRIVVAEP
Q93N87_A2_hpg|hpg2cl                     GTPKGVAVPHGSVAALVGETGWGLGPGDSVLFHAPHAFDISLFEVWVPLASGARVVIAEP
Q93N87_A2_5__hpg|hpg2cl                  GTPKGVAVPHGSVAALVGETGWGLGPGDSVLFHAPHAFDISLFEVWVPLASGARVVIAEP
Q93N89_A1_hpg|hpg2cl                     GTPKGVAVPHGSVAALVGESGWGLGPGDSVLFHAPHAFDISLFEVWVPLASGARVVIAEP
Q93N86_A1_7__hpg|hpg2cl                  GTPKGVAVPHDAVAALAGDPGWGVHAQDAVLLHAPHAFDASLFEIWVPLVSGARVVVAEP
Q93N87_A1_4__hpg|hpg2cl                  GVPKGVAVPHGSVAALVGEPGWAVGPGDSVLFHAPHAFDISLFEVWVPLASGARVEVAEP
Q93N89_A1_1__hpg|hpg2cl                  GTPKGVAVPHGSVAALVGESGWGLGPGDSVLFHAPHAFDISLFEVWVPLASGARVVIAEP
                                         *.******** :****.*:.**.: . *:**:******* ****:****.**.*: :***

Q93N87_A1_hpg|hpg2cl                     SVVVDAAAVREYIAGGVTHVHVTAGLFRVLAEESPECFTGAREVLTGGDVVPARAVQRVR
Q93N88_A1_3__hpg|hpg2cl                  SMAVDGAAVRRHIADGVTHVHVTAGLFRVLAEEASDCFDGVHEVLTGGDVVPLEAVERVR
Q93N87_A2_hpg|hpg2cl                     GVAVDAAAVRRHIAAGVTHVHVTAGLFRVLADEEPECFNGAHEVLTGGDVVPLEAVARVR
Q93N87_A2_5__hpg|hpg2cl                  GVAVDAAAVRRHIAAGVTHVHVTAGLFRVLADEEPECFNGAHEVLTGGDVVPLEAVARVR
Q93N89_A1_hpg|hpg2cl                     GVAVDAAAVRRHIAAGVTHVHVTAGLFRVLAEEAPDCFTGAREVLTGGDVVPLEAVERVR
Q93N86_A1_7__hpg|hpg2cl                  GV-VDALRIREEVAAGVTALHLTAGTFRVLAEEEPECFAGLREVLTGGDVVPPQAVERVR
Q93N87_A1_4__hpg|hpg2cl                  SVVVDAAAVREYIAGGVTHVHVTAGLFRVLAEESPECFTGAREVLTGGDVVPARAVQRVR
Q93N89_A1_1__hpg|hpg2cl                  GVAVDAAAVRRHIAAGVTHVHVTAGLFRVLAEEAPDCFTGAREVLTGGDVVPLEAVERVR
                                         .: **.  :*. :* *** :*:*** *****:* .:** * :********** .** ***

Q93N87_A1_hpg|hpg2cl                     SACPEVRVRHLYGPTEVSLCATWHLLEPGEESPQVLPVGRPLGNRQVYVLDAYLHPVAPG
Q93N88_A1_3__hpg|hpg2cl                  AACPDVRVRHLYGPTEVSLCATWHLFEPGEEQGEVLPLGRPLNNRQVYVLDPFLQPVPPG
Q93N87_A2_hpg|hpg2cl                     AACPEVRVRHLYGPTEVSLCATWHLLEPGEGTDRVLPVGSPLANRQVYVLDAFLQPVPPG
Q93N87_A2_5__hpg|hpg2cl                  AACPEVRVRHLYGPTEVSLCATWHLLEPGEGTDRVLPVGSPLANRQVYVLDAFLQPVPPG
Q93N89_A1_hpg|hpg2cl                     AACPDVRVRHLYGPTESTLCATWHLVEPGDDTARVLPIGHPLTNRHIHVLDDSLRRVAPG
Q93N86_A1_7__hpg|hpg2cl                  QVCPELRIRHLYGPTETTLCATWHLVEPGSPAAGTLPIGRPLAGRRVHVLDAFLQPVPAG
Q93N87_A1_4__hpg|hpg2cl                  SACPEVRVRHLYGPTEVSLCATWHLLEPGEESPQVLPVGRPLGNRQVYVLDAYLHPVAPG
Q93N89_A1_1__hpg|hpg2cl                  AACPDVRVRHLYGPTESTLCATWHLVEPGDDTARVLPIGHPLTNRHIHVLDDSLRRVAPG
                                          .**::*:******** :*******.***.    .**:* ** .*:::***  *: *..*

Q93N87_A1_hpg|hpg2cl                     VTGELYIAGAGLARGYLKRAGLSSERFVACPFADGERMYRTGDLVRWTSDGELVFVGRAD
Q93N88_A1_3__hpg|hpg2cl                  VTGELYVAGAGLARGYLGRAGLSAERFVASPFADGERMYRTGDLVRWTTGVELVFVGRAD
Q93N87_A2_hpg|hpg2cl                     VAGELYIAGAGLARGYLKRAGLSAERFVACPFADGERMYRTGDLARWTDDGELAFAGRAD
Q93N87_A2_5__hpg|hpg2cl                  VAGELYIAGAGLARGYLKRAGLSAERFVACPFADGERMYRTGDLARWTDDGELAFAGRAD
Q93N89_A1_hpg|hpg2cl                     VTGELYIAGAGLARGYLKRAGLSAERFVACPFADGERMYRTGDLARWTDDGELAFAGRAD
Q93N86_A1_7__hpg|hpg2cl                  VPGELYIAGEGVAHGYAGRAALTAERFVADPYTDGRRMYRTGDLVRWTDEGELVFVGRAD
Q93N87_A1_4__hpg|hpg2cl                  VTGELYIAGAGLARGYLKRAGLSSERFVACPFADGERMYRTGDLVRWTSDGELVFVGRAD
Q93N89_A1_1__hpg|hpg2cl                  VTGELYIAGAGLARGYLKRAGLSAERFVACPFADGERMYRTGDLARWTDDGELAFAGRAD
                                         *.****:** *:*:**  **.*::***** *::**.********.***   **.*.****

Q93N87_A1_hpg|hpg2cl                     AQVKVRGFRVELGEVEAALAAEAGVGHAVVTAREDRPGERRLIGYVLPDGEDVDTEL
Q93N88_A1_3__hpg|hpg2cl                  AQVKIRGFRVELGEVEAALAAQPAVAQAVVVAREDRPGEKRLVGYLVPSGEEPDTEA
Q93N87_A2_hpg|hpg2cl                     AQVKIRGFRVELGEVEAALAAQPAVAQAVVVAREGRPGEKRLVGYLVPHGGQPDSDV
Q93N87_A2_5__hpg|hpg2cl                  AQVKIRGFRVELGEVEAALAAQPAVAQAVVVAREGRPGEKRLVGYLVPHGGQPDSDV
Q93N89_A1_hpg|hpg2cl                     AQVKIRGFRVELGEVEAALAAQPAVAQAVVVAREDRPGEKRLVGYLVPDGHQADSDV
Q93N86_A1_7__hpg|hpg2cl                  AQVKIRGFRVEPGEVEAALAAQPGVRQAVVAARDDGPGEKRLIGYVVADGPDLDPDH
Q93N87_A1_4__hpg|hpg2cl                  AQVKVRGFRVELGEVEAALAAEAGVGHAVVTAREDRPGERRLIGYVLPDGEDVDTEL
Q93N89_A1_1__hpg|hpg2cl                  AQVKIRGFRVELGEVEAALAAQPAVAQAVVVAREDRPGEKRLVGYLVPDGHQADSDV
                                         ****:****** *********:..* :***.**:. ***:**:**::. * : *.: 
