CLUSTAL W multiple sequence alignment


Q8KLL5_A2_hpg|hpg2cl                     AGVTVAVCAEGTRNAVPDGLEPVPVDAPWAGETRHETP--TVTARDAAYVMYTSGSTGEP
Q8KLL5_A2_5__hpg|hpg2cl                  AGVTVAVCAEGTRNAVPDGLEPVPVDAPWAGETRHETP--TVTARDAAYVMYTSGSTGEP
Q70AZ7_A2_hpg|hpg2cl                     AGVSVAVCVQATSGAVPDGLAPVVMDSPAIAAAPSEAPPITVGAHDLAYVMYTSGSTGVP
Q70AZ7_A2_5__hpg|hpg2cl                  AGVSVAVCVQATSGAVPDGLAPVVMDSPAIAAAPSEAPPITVGAHDLAYVMYTSGSTGVP
                                         ***:****.:.* .****** ** :*:*  . :  *:*  ** *:* *********** *

Q8KLL5_A2_hpg|hpg2cl                     KGIVVPHGSVAALAGDPGWALDADDCVLMHASHAFDASLFEIWAPLVRGARVMVAEPGAV
Q8KLL5_A2_5__hpg|hpg2cl                  KGIVVPHGSVAALAGDPGWALDADDCVLMHASHAFDASLFEIWAPLVRGARVMVAEPGAV
Q70AZ7_A2_hpg|hpg2cl                     KGVAVPHGSVAALAGDPGWSVGPGDGVLMHAPHAFDASLLEIWVPLLSGAHVVVADPGAV
Q70AZ7_A2_5__hpg|hpg2cl                  KGVAVPHGSVAALAGDPGWSVGPGDGVLMHAPHAFDASLLEIWVPLLSGAHVVVADPGAV
                                         **:.***************::...* *****.*******:***.**: **:*:**:****

Q8KLL5_A2_hpg|hpg2cl                     DTQRLREAVARGVTTVHLTAGSFRVLAEESPGSFDGLREILTGGDVVPLASVAQLRRACP
Q8KLL5_A2_5__hpg|hpg2cl                  DTQRLREAVARGVTTVHLTAGSFRVLAEESPGSFDGLREILTGGDVVPLASVAQLRRACP
Q70AZ7_A2_hpg|hpg2cl                     DAQRLREAIDRGVTTVHLTAGSFRVLAEESPDAFRGLREVLTGGDAVPLASVVRLRETCP
Q70AZ7_A2_5__hpg|hpg2cl                  DAQRLREAIDRGVTTVHLTAGSFRVLAEESPDAFRGLREVLTGGDAVPLASVVRLRETCP
                                         *:******: *********************.:* ****:*****.******.:**.:**

Q8KLL5_A2_hpg|hpg2cl                     DVRVRHLYGPTETTLCGTWHLLEPGDEPGDVLPIGRPLAGRRAYVLDAFLQPVAPNVTGE
Q8KLL5_A2_5__hpg|hpg2cl                  DVRVRHLYGPTETTLCGTWHLLEPGDEPGDVLPIGRPLAGRRAYVLDAFLQPVAPNVTGE
Q70AZ7_A2_hpg|hpg2cl                     EIRVRHLYGPTETTLCATWHLIEPGVATGDTLPIGRPLAGRRAYVLDAFLQPVAPNVTGE
Q70AZ7_A2_5__hpg|hpg2cl                  EIRVRHLYGPTETTLCATWHLIEPGVATGDTLPIGRPLAGRRAYVLDAFLQPVAPNVTGE
                                         ::**************.****:***  .**.*****************************

Q8KLL5_A2_hpg|hpg2cl                     LYLAGVGLALGYLGARGATSERFVADPFVPGERMYRTGDLARRNDRGELLFAGRADAQVK
Q8KLL5_A2_5__hpg|hpg2cl                  LYLAGVGLALGYLGARGATSERFVADPFVPGERMYRTGDLARRNDRGELLFAGRADAQVK
Q70AZ7_A2_hpg|hpg2cl                     LYLAGAGLARGYLGAAAATAERFVADPFAAGERMYRTGDLARWTEQGELLFAGRADAQVK
Q70AZ7_A2_5__hpg|hpg2cl                  LYLAGAGLARGYLGAAAATAERFVADPFAAGERMYRTGDLARWTEQGELLFAGRADAQVK
                                         *****.*** ***** .**:********..************ .::**************

Q8KLL5_A2_hpg|hpg2cl                     IRGYRVEPTEIETVLAEAPQVAQTVVVAREDGPGEKRLIAYAIAEPDQVLDPEA
Q8KLL5_A2_5__hpg|hpg2cl                  IRGYRVEPTEIETVLAEAPQVAQTVVVAREDGPGEKRLIAYAIAEPDQVLDPEA
Q70AZ7_A2_hpg|hpg2cl                     IRGYRVEPAEIEAALTAIPEVAQAVVVAREDGPGEKRLIAYVTAAGQPGPDPAA
Q70AZ7_A2_5__hpg|hpg2cl                  IRGYRVEPAEIEAALTAIPEVAQAVVVAREDGPGEKRLIAYVTAAGQPGPDPAA
                                         ********:***:.*:  *:***:*****************. *  :   ** *
