CLUSTAL W multiple sequence alignment


BGC0000400_AGM16414.1_2358_mod3_ile      SGTQIILTQHEL---QS--RIPVQASFVLLDDEHSYSADDSNLEQNNGPADLAYVIYTSG
O68006_A5_ile                            SGAALLVTTDSLLKPFDIKTVDLCSDELHL-------LSEENLPRVNRSSDTAYIVYTSG
O66071_A1_7__ile                         SGAVCMLTQEELAGQAA--SLSFHQNTILIDDPAVSAESGRNLEIAAEPDDLAYIMYTSG
O68008_A1_8__ile                         TKAGVLLAQG---KAAD--GIDCEADIIHLDKGVADGFSKKRLSSVNDSGDTAYIIYTSG
AGM16414.1_2358_mod3_ile                 SGTQIILTQHEL---QS--RIPVQASFVLLDDEHSYSADDSNLEQNNGPADLAYVIYTSG
AGM16413.1_4358_mod4_ile                 SGTQIIVTQRHL---QE--RIPGAGTRVILDDEHSYSSDSTNLDLNNGPADLAYVIYTSG
BGC0000400_AGM16413.1_4358_mod4_ile      SGTQIIVTQRHL---QE--RIPGAGTRVILDDEHSYSSDSTNLDLNNGPADLAYVIYTSG
O68006_A1_ile                            TKAAVLLTQG---KAAD--GIDCEADIVQLDREASDGFSKEPLSSVNDSGDTAYIIYTSG
                                         : :  :::            :      : :        .   *     . * **::****

BGC0000400_AGM16414.1_2358_mod3_ile      TTGKPKGNLATHRNIVRVVQGTSYIDFSERDNVLQLSNYAFDGSTFDMYGALLNGAKLVL
O68006_A5_ile                            STGTPKGVVIPHYSAARVVKNTNYIDITGNDVILQLSNYSFDGSVFDIFGALLNGASLVL
O66071_A1_7__ile                         TTGKPKGNLTTHANITRVVKETNYISLSEKDTLLSLSNYAFDGFTFDVYGALLNGAKLVV
O68008_A1_8__ile                         STGMPKGVVTPHYSAARVVKNTNYIDITEDDAILQLSNYSFDGSVFDIFGALLNGASLVL
AGM16414.1_2358_mod3_ile                 TTGKPKGNLATHRNIVRVVQGTSYIDFSERDNVLQLSNYAFDGSTFDMYGALLNGAKLVL
AGM16413.1_4358_mod4_ile                 TTGKPKGNLTMHRNIVRVVQGADYIDIGEQDNVLQLSSYAFDGSTFDMYGALLNGARLVL
BGC0000400_AGM16413.1_4358_mod4_ile      TTGKPKGNLTMHRNIVRVVQGADYIDIGEQDNVLQLSSYAFDGSTFDMYGALLNGARLVL
O68006_A1_ile                            STGTPKGVITPHYSVIRVVQNTNYIDITEDNVILQLSNYSFDGSVFDIFGALLNGASLVM
                                         :** *** :  * .  ***: :.**.:   : :*.**.*:*** .**::******* **:

BGC0000400_AGM16414.1_2358_mod3_ile      IPQETLLEVGKLAGLIERERISVMFITTAYFNILIDMKADCLRHIRTILFGGERVSISHV
O68006_A5_ile                            IEKETVLNTHELAEVIKKEQVSVMFITTALFNTLADINIGCLAKLRKILFGGERASIPHV
O66071_A1_7__ile                         ADQATILHIGKLTETIQKENITVMFVTTALFNLLVDAGTEWMKGIRKVLFGGERSSVSHV
O68008_A1_8__ile                         IEKETVLNTHELAEVIKKEQVSVMFITTALFNTLADINIGCLAKLRKIFLGGERASIPHV
AGM16414.1_2358_mod3_ile                 IPQETLLEVGKLAGLIERERISVMFITTAYFNILIDMKADCLRHIRTILFGGERVSISHV
AGM16413.1_4358_mod4_ile                 IPQETLLDVERLAELIERERISVMFITTAFFNVLVDVKADCLRHIRAILFGGERVSVSHV
BGC0000400_AGM16413.1_4358_mod4_ile      IPQETLLDVERLAELIERERISVMFITTAFFNVLVDVKADCLRHIRAILFGGERVSVSHV
O68006_A1_ile                            IEKEALLNINRLGSAINEEKVSVMFITTALFNMIADIHVDCLSNLRKILFGGERASIPHV
                                           : ::*.  .*   *:.*.::***:*** ** : *     :  :* :::**** *:.**

BGC0000400_AGM16414.1_2358_mod3_ile      RKALYQLGPGKIKHVYGPTESTVFATCHDVNEVAEDAVTVPIGRPISNTTIYIVNAQNDL
O68006_A5_ile                            RKVLDHVGRDKLIHVYGPTESTVYATYYFINEIDDEAETIPIGSPLANTSVLIMDEAGKL
O66071_A1_7__ile                         KKAFAAMGPDRIIHVYGPTETTVFATFYPVNRIEDNAVSIPIGKPINETNAYILTENNRL
O68008_A1_8__ile                         RKVLNHVGRDKLIHVYGPTESTVYATYYFINEIDDEAETIPIGSPLANTSVLIMDEAGKL
AGM16414.1_2358_mod3_ile                 RKALYQLGPGKIKHVYGPTESTVFATCHDVNEVAEDAVTVPIGRPISNTTIYIVNAQNDL
AGM16413.1_4358_mod4_ile                 RKALRHLGPGKIKHVYGPTESTVFATCHDVNEVAADALNVPIGRPISNTTIYIVNEENGL
BGC0000400_AGM16413.1_4358_mod4_ile      RKALRHLGPGKIKHVYGPTESTVFATCHDVNEVAADALNVPIGRPISNTTIYIVNEENGL
O68006_A1_ile                            RKVLNHVGRDKLIHVYGPTESTVYATYYFINEIDDEAETIPIGSPLANTSVLIMDEAGKL
                                         :*.:  :* .:: *******:**:** : :*.:  :* .:*** *: :*.  *:   . *

BGC0000400_AGM16414.1_2358_mod3_ile      QPIGVAGELCIAGDGLARGYLNRPELTAAKFVDNPFAPRERMYRTGDLARWLPDGTIEYV
O68006_A5_ile                            LPIGVPGELCIAGDGLSKGYLNREELTAEKFIPHPFIPGERLYKTGDLAKWLPDGNIEFI
O66071_A1_7__ile                         QPIGAVGELCLSGTGVSRGYLNRPELTAEKFVPHPFNSGETMYRTGDLARWLPDGNIDFI
O68008_A1_8__ile                         LPIGVPGELCIAGDGLSKGYLNREELTAEKFIPHPFIPGERLYKTGDLAKWLPDGNIEFI
AGM16414.1_2358_mod3_ile                 QPIGVAGELCIAGDGLARGYLNRPELTAAKFVDNPFAPRERMYRTGDLARWLPDGTIEYV
AGM16413.1_4358_mod4_ile                 QPIGVAGELCVAGDGLARGYLNRPELTAEKFVDNPFVPGERMYRTGDLARWLPDGSIEYV
BGC0000400_AGM16413.1_4358_mod4_ile      QPIGVAGELCVAGDGLARGYLNRPELTAEKFVDNPFVPGERMYRTGDLARWLPDGSIEYV
O68006_A1_ile                            VPIGVPGELCIAGDGLSKGYLNREELTAEKFIPHPFIPGERLYKTGDLAKWLPDGNIEFI
                                          ***. ****::* *:::***** **** **: :** . * :*:*****:*****.*:::

BGC0000400_AGM16414.1_2358_mod3_ile      GRIDDQVKIRGYRIELGEVETHLLRVEPIQEATVIARESDSGEKRLCAYYVADR-PLPAN
O68006_A5_ile                            GRIDHQVKIRGFRIELGEIESRLEMHEDINETIVTVREDEESRPYICAYITANR-EISLD
O66071_A1_7__ile                         GRIDDQVKIRGHRIELGEIEEELMRCQGVKEAVVIAKKRGNGDAALTAYVVPVRGAVVSN
O68008_A1_8__ile                         GRIDHQVKIRGFRIELGEIESRLEMHEDINETIVTVREDEESRPYICAYITANR-EISLD
AGM16414.1_2358_mod3_ile                 GRIDDQVKIRGYRIELGEVETHLLRVEPIQEATVIARESDSGEKRLCAYYVADR-PLPAN
AGM16413.1_4358_mod4_ile                 GRIDHQVKIRGYRIELGEVEAHLLKVQPVQEGTVVARETGSGEKQLCAYFVAES-TLSAS
BGC0000400_AGM16413.1_4358_mod4_ile      GRIDHQVKIRGYRIELGEVEAHLLKVQPVQEGTVVARETGSGEKQLCAYFVAES-TLSAS
O68006_A1_ile                            GRIDHQVKIRGFRIELGEIESRLEMHEDINETIVTVREDEESRPYICAYITANR-EISLD
                                         ****.******.******:* .*   : ::*  * .::  ..   : ** ..    :  .

BGC0000400_AGM16414.1_2358_mod3_ile      E-
O68006_A5_ile                            E-
O66071_A1_7__ile                         EE
O68008_A1_8__ile                         E-
AGM16414.1_2358_mod3_ile                 E-
AGM16413.1_4358_mod4_ile                 E-
BGC0000400_AGM16413.1_4358_mod4_ile      E-
O68006_A1_ile                            E-
                                         * 
