CLUSTAL W multiple sequence alignment


Q84BQ4_A4_10__ile                        CQAAALLTLSREDIDYAAPRIDLDRLILSGQPTHNPNLLQSSEALAYIMYTSGSTGTPKG
BGC0000425_AFH75322.1_2740_mod3_ile      SGARWLLTTSAHQAPEGGERLDLDSLDLSDAPVHDPAIEQSAESVAYIMYTSGSTGVPKG
AFZ61526.1_2645_mod3_ile                 SGAAWLLTHSDRAVDYAVQRLDLDTLALDPQPSHNPDLSQSSDSVAYIMYTSGSTGTPKG
Q84BQ4_A3_9__ile                         SRAVALLTLSSEAIDYAAPRIDLDRLKLSGQSTHNPNLAQSSDALAYIMYTSGSTGTPKG
                                         . *  *** * .    .  *:*** * *.  . *:* : **::::***********.***

Q84BQ4_A4_10__ile                        VMVPHRAIGRLVLNNGYADFNAQDRVVFASNPAFDASTMDIWGPLLNGGRVVVIDHQTLL
BGC0000425_AFH75322.1_2740_mod3_ile      VLVPHRGITRLVINGGYADFNTHDRIAFASNPAFDASTMDVWGALLNGGQVVVIDHDTLL
AFZ61526.1_2645_mod3_ile                 VLVPHRGITRLVINNGYADFNASDRVAFASNPAFDASTMDVWGPLLNGGQVQVIDHATLL
Q84BQ4_A3_9__ile                         VMVPHRGIARLVLNNGYADFNRQDRVAFASNPAFDASTMDIWGPLLNGGRVVVIDHQTLL
                                         *:****.* ***:*.******  **:.*************:**.*****:* **** ***

Q84BQ4_A4_10__ile                        DPNAFGHELSASRATVLFVTTALFNQYVQLIPQALKGLRILLCGGERGDPAAFRRLLAEA
BGC0000425_AFH75322.1_2740_mod3_ile      DPLRFGAVLSESAVTILFTTTALFNQYVQLIPDALKGLRMLLCGGERADPAAFRSLLEHA
AFZ61526.1_2645_mod3_ile                 DPAAFG--VALADVTVLFVTTALFNQYVQLIPQALAGLRILLCGGERADPAAFRSLLHQA
Q84BQ4_A3_9__ile                         DPNAFGRELSASGATILFVTTALFNQYVQLIPQALKGLRMVLCGGERGDPTSFRRLRAEA
                                         **  **  :: : .*:**.*************:** ***::******.**::** *  .*

Q84BQ4_A4_10__ile                        PKLRIVHCYGPTETTTYATTFEVREVAENAESVPIGGPISNTQVYVLDAHQQPVPMGVTG
BGC0000425_AFH75322.1_2740_mod3_ile      PKLRLVHCYGPTESTTYATTFEVRALADDAESVPIGGPISNTRIYLLDQRQQPVPLGVVG
AFZ61526.1_2645_mod3_ile                 PALRLVHCYGPTETTTYATTYEVRALAEAADSVPIGRPISNTQVHVLDAHLQPVPVGVTG
Q84BQ4_A3_9__ile                         PQLRIVHCYGPTETTTYATTFEVHEVAENAESVPIGAPISNTQVYVLDAHQQPVPMGVTG
                                         * **:********:******:**: :*: *:***** *****::::** : ****:**.*

Q84BQ4_A4_10__ile                        ELYIGGQGVALGYLNRADLTAEKFLRDPFSDQPGALLYRTGDLARWLAPGQLDCIGRNDD
BGC0000425_AFH75322.1_2740_mod3_ile      EIYIGGKGVAKGYLNRPELTAEKFILDPFSHEPGALMYRTGDLGRWLAKGELDCLGRNDD
AFZ61526.1_2645_mod3_ile                 EICIGGDGVALGYLNRPDLTAEKFVRDPLSE--GALMYRTGDLGRWTADGLLDCIGRNDD
Q84BQ4_A3_9__ile                         ELYIGGQGVALGYLNRADLTAEKFLPDPFSDRPGALLYRTGDLVRWLAPGQLDCIGRNDD
                                         *: ***.*** *****.:******: **:*.  ***:****** ** * * ***:*****

Q84BQ4_A4_10__ile                        QVKIRGFRIELGEIENRLLNCQGIKEAVVLARRDGQDITRLVAYYTAHAGRLDSADL
BGC0000425_AFH75322.1_2740_mod3_ile      QVKIRGFRIELGEIENRLGEHPQINEVVVLAREDEPGSKRLVAYFTEH-QALDIQAL
AFZ61526.1_2645_mod3_ile                 QVKIRGFRIELGEIEARLATFAGIQDVVVLAREDAPGDKRLAAYFTWADQPDDIDSV
Q84BQ4_A3_9__ile                         QVKIRGFRIELGEIENRLLSYPGINEAVVLARRDGQEPLRLVAYYTAHDGTLELAGL
                                         *************** **     *::.*****.*     **.**:*      :   :
