CLUSTAL W multiple sequence alignment


AHH53508.1_1559_mod2_kyn                 AAPVLALATTDTAESVAGTPRVVLDGTTTVAELREHADVDVTDAERHRPLSVRDAAYVIF
BGC0000439_AHH53508.1_1559_mod2_kyn      AAPVLALATTDTAESVAGTPRVVLDGTTTVAELREHADVDVTDAERHRPLSVRDAAYVIF
                                         ************************************************************

AHH53508.1_1559_mod2_kyn                 TSGSTGRPKGVIIEHEGLADLHAAQAELLAPTEGDRVLQLVSAGFDASIWDFSTALLTGA
BGC0000439_AHH53508.1_1559_mod2_kyn      TSGSTGRPKGVIIEHEGLADLHAAQAELLAPTEGDRVLQLVSAGFDASIWDFSTALLTGA
                                         ************************************************************

AHH53508.1_1559_mod2_kyn                 TLVFAPADRLLGPELPELVREFGITHLTLPPPALATVEEGSMPGSVTLTVTGDVLPAPLA
BGC0000439_AHH53508.1_1559_mod2_kyn      TLVFAPADRLLGPELPELVREFGITHLTLPPPALATVEEGSMPGSVTLTVTGDVLPAPLA
                                         ************************************************************

AHH53508.1_1559_mod2_kyn                 ARWAGGGRRVLNGYGPTEATVAATYWVCGPDETGAVPIGGPLRNKRIYVLDERLRLVPDG
BGC0000439_AHH53508.1_1559_mod2_kyn      ARWAGGGRRVLNGYGPTEATVAATYWVCGPDETGAVPIGGPLRNKRIYVLDERLRLVPDG
                                         ************************************************************

AHH53508.1_1559_mod2_kyn                 VVGDLYIAGAGLARGYFTRPGETADHFVADPYGAPGERMYRTGDRGRRRPDGALMFAGRV
BGC0000439_AHH53508.1_1559_mod2_kyn      VVGDLYIAGAGLARGYFTRPGETADHFVADPYGAPGERMYRTGDRGRRRPDGALMFAGRV
                                         ************************************************************

AHH53508.1_1559_mod2_kyn                 DDQVKIRGFRIELGEIEAALSAHHDIRQCAVVVDGTGAEDKRIIGYVVPATEGDELTASD
BGC0000439_AHH53508.1_1559_mod2_kyn      DDQVKIRGFRIELGEIEAALSAHHDIRQCAVVVDGTGAEDKRIIGYVVPATEGDELTASD
                                         ************************************************************
