CLUSTAL W multiple sequence alignment


Q84BQ6v2_A1_leu                          SAPIAVLTQRALRGHLPALSVPVIELDQPSWSAGRVDAPKVPGLTPANLAYVIYTSGSTG
AFZ61501.1_498_mod1_leu                  SDPVVVLTQHDLLSRLPALEVPVIQLDRPTF--HLGTNPRVA-VSPSNLAYVIYTSGSTG
Q84BQ4_A1_7__leu                         SAPVAVLTQSHLRERLPALNVPVLDLDHCNWPLTVTQNPQVPGLSTANLAYVIYTSGSTG
AFZ61526.1_575_mod1_leu                  SAPVAVLTQQALLERLPALDVPVINLDRFTWQHHSASNPKVV-VTPFNLAYVIYTSGSTG
AFZ61525.1_2683_mod3_leu                 SAPVAVLAEASTRDLLGA--VATLDLHDPRVQQQAVSNPQLSALTPAHLAYVIYTSGSTG
Q84BQ6v1_A1_leu                          SAPIAVLTQRALRGHLPALSVPVIELDQPSWSAGRVDAPKVPGLTPANLAYVIYTSGSTG
Q84BQ5_A3_5__leu                         SDPVAVLAQGATRELLGR--VPVIDLDNALWQHLPETNPQLPTLTPAHLAYVIYTSGSTG
                                         * *:.**::      *    *..::*.           *::  ::. :************

Q84BQ6v2_A1_leu                          LPKGVMVEHRTLCNLVDWHADVFDLHAGSHTSSLAGFGFDAMAWEVWPALCVGATLHLAP
AFZ61501.1_498_mod1_leu                  LPKGVMVEHHTVANLVDWHCQAFDLQAGSHTASVAGFGFDAMAWEIWPALCVGATVHLPP
Q84BQ4_A1_7__leu                         LPKGVMVEHHTLSNLVDWHCTAFDLCAGRHTSSLAGFGFDAMAWEVWPALCAGATLHLAP
AFZ61526.1_575_mod1_leu                  LPKGVMVEHHTVANLVDWHCNAFDLCAGRHTASVAGFGFDAMAWEVWPALCVGATLHLPP
AFZ61525.1_2683_mod3_leu                 QPKGVMVEHRTVENLVHWHCEAFGLDATGHTSSVAGFGFDAMAWEVWPALCVGATLHLPP
Q84BQ6v1_A1_leu                          LPKGVMVEHRTLCNLVDWHADVFDLHAGSHTSSLAGFGFDAMAWEVWPALCVGATLHLAP
Q84BQ5_A3_5__leu                         QPKGVVVEHATLENLVHWHCEAFDLRAGSHTASVAGCGFDAMAWEVWPALCVGATLHLPP
                                          ****:*** *: ***.**. .*.* *  **:*:** ********:*****.***:**.*

Q84BQ6v2_A1_leu                          ASEGSEDIDALLDWWRAQPLDVSFLPTPIAEYAFSRQLDHPTLRTLLIGGDRLRQFPRQP
AFZ61501.1_498_mod1_leu                  AHDGAEDIDALLRWWQAQPLQVCFLPTPVAEYAFSQSLQHPTLRTLLIGGDRLRSFTQAQ
Q84BQ4_A1_7__leu                         THEGGEDIDALLAWWCAQPLDVSFLPTPVAEYAFSQNLEHPTLRTLLIGGDRLRQFNRNQ
AFZ61526.1_575_mod1_leu                  AHDGAEDIDALLAWWCAQPLDVCFLPTPVAEYAFSQQIEHPTLRTLLIGGDRLRQFGRAQ
AFZ61525.1_2683_mod3_leu                 ADVGNENIDELLAWWLAQPLDVSFLPTPVAEYAFSQNLQHPTLRILLIGGDRLRQFTQER
Q84BQ6v1_A1_leu                          ASEGSEDIDALLDWWRAQPLDVSFLPTPIAEYAFSRQLDHPTLRTLLIGGDRLRQFPRQP
Q84BQ5_A3_5__leu                         PSISNEHLDELLDWWRAQPLQVSFLPTPIAEYAFSRELGHPTLRTLLIGGDKLRQFSRGQ
                                         .  . *.:* ** ** ****:*.*****:******:.: ***** ******:**.* :  

Q84BQ6v2_A1_leu                          SFEVINNYGPTEATVVATSGRIDAGQALHIGKPVSNATVYLLDEQQQPVPLGVTGELYVG
AFZ61501.1_498_mod1_leu                  SFAVINNYGPTEATVVATSGCMEVGQLLHIGAPIANATVYLLDEQQRPVPIGVAGELYVG
Q84BQ4_A1_7__leu                         HFDVINNYGPTEATVVATSGLVQSGDALHIGKPLSNATVYLLDEQQRPVPLGVAGELYVG
AFZ61526.1_575_mod1_leu                  RFDLINNYGPTEATVVATSGKVEAGQPLHIGKPIANATVYLLDEQQRPVPLGVAGELYVG
AFZ61525.1_2683_mod3_leu                 RFAVINNYGPTEATVVATSGRVRAGQVLHIGRPIANASVYLLDAHLRPVPVGVAGELYVG
Q84BQ6v1_A1_leu                          SFEVINNYGPTEATVVATSGRIDAGQALHIGKPVSNATVYLLDEQQQPVPLGVTGELYVG
Q84BQ5_A3_5__leu                         TFDVINNYGPTEATVVATSGSIHAGQLLHIGRPISNARIYLLDEQQRPVPVGVAGELYVG
                                          * :**************** :  *: **** *::** :**** : :***:**:******

Q84BQ6v2_A1_leu                          GAGVARGYLNRAELSAERFLRDPFSAEPGARLYRTGDLARWRADGNLEYLGRNDDQVKIR
AFZ61501.1_498_mod1_leu                  GKGVARGYLNRPELSAERFLDDPFI---EGRMYRTGDLARWLPEGSLEYLGRNDDQVKIR
Q84BQ4_A1_7__leu                         GAGVARGYLNRPDMTAERFLRDPFSRAPNARMYRTGDLARWREDGNIEYLGRNDDQVKIR
AFZ61526.1_575_mod1_leu                  GNGVARGYLNRPELTAERFLQDPFN---TGRMYRTGDLARWLPDGNIEYLGRNDDQVKIR
AFZ61525.1_2683_mod3_leu                 GSGVARGYLNRPDLSAGRFLHDPFN---EGRMYRTGDLARWLPDGNIEYLGRNDDQVKVR
Q84BQ6v1_A1_leu                          GAGVARGYLNRAELSAERFLRDPFSAEPGARLYRTGDLARWRADGNLEYLGRNDDQVKIR
Q84BQ5_A3_5__leu                         GAGVARGYLNRPELTAERFLEDPFSDRPQARMYRTGDLARWLADGNIEYLGRNDDQVKLR
                                         * *********.:::* *** ***     .*:*********  :*.:***********:*

Q84BQ6v2_A1_leu                          GIRIEPGEIESALASHSAVREAVVLVRDG-----QLLAWFT--EQAPLDINE
AFZ61501.1_498_mod1_leu                  GMRIELGEIESALATHPHVQDAVVQSRDG-----QLLAWFVPREALQIEA--
Q84BQ4_A1_7__leu                         GVRIELGEIETCLNQLPGIQEAVLLAREDQPGQPRLVAYFT--EQPQVEA--
AFZ61526.1_575_mod1_leu                  GMRIELGEIETQLNQVAGIQEAVVLVREE-----RLVAYFT--ENRQLDP--
AFZ61525.1_2683_mod3_leu                 GVRVELGEIESRLAALDGVAEAVVLVREG-----RLIAWFT--EQQPLDIDT
Q84BQ6v1_A1_leu                          GIRIEPGEIESALASHSAVREAVVLVRDG-----QLLAWFT--EQAPLDINE
Q84BQ5_A3_5__leu                         GVRVELGEIEAALSSHPAVQDAVVLVREA-----RLIAWFT--ARTTVDNED
                                         *:*:* ****: *     : :**:  *:      :*:*:*.      ::   
