CLUSTAL W multiple sequence alignment


Q70LM5_A6_12__leu                        TGMPFVLTQERLLETLPAGDAAFICLDADWEVIAEESTQAPELAVTTDQLAYVIYTSGST
Q70LM6_A2_4__leu                         AGMSLVLTQERLLDALPQEAAALLCLDRDWQEIAAESTAAPAIKTNADQLAYVIYTSGST
Q70LM4_A2_14__leu                        ASMAIVLTQAKLRQKLPADTSRLICLDADWETIAQEPTAALVNTTAASDLAYVIYTSGST
Q9S1A8_A1_8__leu                         SGVSLVLTQESLGDFLPQTGAELLCLDRDWEKIATYSPENPFNLTTPENLAYVIYTSGST
Q9RAH2_A1_leu                            AQVSVLLTQQKLIDRLPEHTAQRVCLDADWQVISQLSQDNLIPETQATNLAYVIYTSGST
Q70LM5_A4_10__leu                        AEMPVVLTQEHLLAQLPEARATFLCLDRDWSLIAEESDVAPVIATNRDNLAYVIYTSGST
Q9RAH4_A4_leu                            AQVSVLLTQQKLLDRLAQHQAKLVCLDTDWQLISQSSQDNLITETQAANLAYVIYTSGST
                                         : :..:***  *   *.   :  :*** **. *:  .       .   :***********

Q70LM5_A6_12__leu                        GTPKGVEIEHRALLNLIYWHQHAYTITPDDRASQIAGTAFDAAVWEIWPYMTAGATLYLP
Q70LM6_A2_4__leu                         GTPKGVEIEHGSLLNLVNWHQRAYSVSAEDRASQIAGTAFDASVWETWPYLTAGATICQP
Q70LM4_A2_14__leu                        GTPKGVEIEHAALLNLIFWHQRAYDVTATDRASQIAGTAFDASVWEIWPYVTKGATLYLP
Q9S1A8_A1_8__leu                         GKPKGVLISHRGLMNLICWHQDAFEITPLDKITQLARSAFDAAVWELWPCLTAGASLVLV
Q9RAH2_A1_leu                            GQPKGVLIAHQGLLNLVFWHQRTFKITTLDKATQLAGTAFDAAVWELWPYLTAGASIYLV
Q70LM5_A4_10__leu                        GTPKGVEIEHAALLNLVSWHQRAYEVGAEDRATQIAGTAFDASVWEIWPYLTKGATLYLP
Q9RAH4_A4_leu                            GQPKGVLIAHQGLLNLVFWHQNTFKITTLDKATQLAGTAFDAAVWELWPYLTAGASIYLV
                                         * **** * * .*:**: *** :: : . *: :*:* :****:*** ** :* **::   

Q70LM5_A6_12__leu                        QEEIRLIPEKLRDWLVAEGITISFLPTPLAESMLSVDWP-SHAALRYVLTGGDKLHHYPA
Q70LM6_A2_4__leu                         REEIRLSPEKLRDWLVETGITISFLPTPLAENLLPLPWP-TGAALRYMLTGGDTLHQYPT
Q70LM4_A2_14__leu                        EEEIRLVPEKLRDWLVASNITVSFLPTPLTESMLALEWP-GDTALRYMLTGGDKLHHYPS
Q9S1A8_A1_8__leu                         KPEIMQSPPDLRDWLIAQEITVSFLPTPLVEKILSLKWD-ENIALRIILTGGDKLHHYPS
Q9RAH2_A1_leu                            KPEILLSPVDLQDWLESKKITISFLPTPMAEQLLSLEWP-ESTTLRTMLTGGDKLHRYPS
Q70LM5_A4_10__leu                        SEEIRLVPEQLRDWLVASGITISFLPTPLAERLLTLEWP-SDAKLRYMLTGGDKLHDYPP
Q9RAH4_A4_leu                            KSEFLSSLVKLRDWLISKKITISFLPTPLAQELLSLEWPTESLALRTILTGGDKLHQYPS
                                           *:     .*:***    **:******:.: :*.: *      ** :*****.** **.

Q70LM5_A6_12__leu                        EHVPFTLVNQYGPTENAVVATAGIVAVQAGQ-VTPPSIGRPIDNVQVYILDEQRQPVPIG
Q70LM6_A2_4__leu                         ADVPFTLVNQYGPTENTVVATAGAVPVLGER-ESAPTIGRPIDNVSVYVLDENRQPVPVG
Q70LM4_A2_14__leu                        EKIPFTLVNQYGPTENTVVATAGIVPKEAGQ-TAAPTIGRPIDNVQVYILDAHRQPVPVG
Q9S1A8_A1_8__leu                         VSMPFKLINNYGPTENTVVTTSGLVPDYEEGNSSSPSIGKPISNTKIYILDQNLQPLPIG
Q9RAH2_A1_leu                            GLLPFQVVNNYGPTENTVVSTSGLVVSNGRDNNISPPIGRPIANVEIYILDSYLQPVPVG
Q70LM5_A4_10__leu                        ATLPFVLANQYGPTENAVVATAGIVPAAAGQ-VSAPSIGRPIDNVQVYVLDEKLQPVPIG
Q9RAH4_A4_leu                            DLVPSQLVNNYGPTENTVVTTSGLVVAKEQD-QISPSIGRAIANTQIYILDNNLQLVPIG
                                           :*  : *:******:**:*:* *         .*.**:.* *..:*:**   * :*:*

Q70LM5_A6_12__leu                        VTGELYIAGSSLARGYYKRPDLTQERFVDNPFTANRGA---------------------K
Q70LM6_A2_4__leu                         VVGELYIGGKSLARGYRNRPDLTEASFVPNPFSPIEGA---------------------R
Q70LM4_A2_14__leu                        VSGELYIGGSSLARGYLNRPDLTQERFVAHPFTEKAGA---------------------R
Q9S1A8_A1_8__leu                         VPGELHISSVGLARGYLNRLELTQEKFISNPFNSG------------------------I
Q9RAH2_A1_leu                            VPGELHIGGAGLARGYLNRPQLTQEKFISNPFKRSRGAGEQRSRGETFNSN--------R
Q70LM5_A4_10__leu                        VAGELYIAGDSLARGYLHRPDLTRERFIANPYGQKAGA---------------------R
Q9RAH4_A4_leu                            IPGELHIAGVGLAKGYLNRPELTTEKFIPNPFKRSREAGEQGSRGAKILPNSQSLVPSPR
                                         : ***:*.. .**:** :* :**   *: :*:                            

Q70LM5_A6_12__leu                        MYRTGDLVRYLPDGQIEFIGRSDDQVSIRGFRVELGEIESVLYQHPAVKEAIVLAREDM-
Q70LM6_A2_4__leu                         MYRTGDLVRYAADGSIEFIGRADDQVSIRGFRVELGEIESALYAHPAVAESVVIVREDVT
Q70LM4_A2_14__leu                        LYRTGDLVRSLPDGSIEFIGRADDQTSIRGFRVELGEVETAIVALPAVKEAVVTVCTDK-
Q9S1A8_A1_8__leu                         LYKTGDLVRYLPEGNIEFLGRIDNQVKLRGLRIELGEIEAVLETHSEVEKAVVILREDT-
Q9RAH2_A1_leu                            LYKTGDLARYLPDGTIEYLGRIDNQVKIRGFRIELSEIEAVLSQHSDVQLSCVIAREDT-
Q70LM5_A4_10__leu                        MYKTGDLVRYLPDGNIEFIGRADDQVSIRGFRVELGEIETALYSHPAVKETIVLVREDM-
Q9RAH4_A4_leu                            LYKTGDLARYLPDGNIEYLGRIDNQVKIRGFRIELAEIEALLGQHDDVQICCVIAREET-
                                         :*:****.*  .:* **::** *:*..:**:*:**.*:*: :     *    *    :  

Q70LM5_A6_12__leu                        PGVKRLAAYVVV---AEDDAEQADD
Q70LM6_A2_4__leu                         PGVKRLVAYAVL---HEGEERQTSE
Q70LM4_A2_14__leu                        QGTKRLAAYLVL---EEGAALATGD
Q9S1A8_A1_8__leu                         SDNQRLVAYIV----RKYPSLGIGE
Q9RAH2_A1_leu                            PGDKRLVAYVVA---HQDCKPAISE
Q70LM5_A4_10__leu                        PGMKRLVAYIVQREGQEGQAVQAGD
Q9RAH4_A4_leu                            PGNKRLVAYVVP---QKEVTPTTDE
                                          . :**.** *     :      .:
