CLUSTAL W multiple sequence alignment


Q04747_A3_6__leu                         SGAKLLLKQEGISVPDSYTGDVILLDGSRTILSLPLDENDE---GNPETAVTAENLAYMI
P27206_A3_leu                            SGAKLLLKQEGISVPDSYTGDVILLDGSRTILSLPLDENDEENPENPETAVTAENLAYMI
Q70KJ6_A3_6__leu                         SGAKLLLTQEALDVPESYNGETILLDGRRSILSLPLDENDE---ANPQTETTADHLAYMI
O69246_A3_6__leu                         SGAELLLTQSGLTVPDTFTGDVIDLNREGSILDGELYPEDD---MNPNAQAQSDNLAYLI
Q70KJ7_A3_leu                            SGAKLLLTQEALGVPESYKGETILLDGSRSILSLPLDENDE---ANPQTETTADHLAYMI
Q65NK5_A3_leu                            SGAELLLTQTNLAVPEEFSGETLLLD---SMLSEEITNDDE---VNPQAGTQPNNLAYLI
Q45295_A3_leu                            SGAELLLTQTNLAAPEEFSGETLLLD---SMLSEEITKVDE---VNPQAGTQSDNLAYLI
O68006_A3_leu                            SEVKVIISDVPLA--EELTAESIELI---HMDDERIAGQDR---SDIDNVNQSGDLAYVI
                                         * .::::.:  :   :  ..: : *     : .  :   *     : :    . .***:*

Q04747_A3_6__leu                         YTSGTTGQPKGVMVEHHALVNLCFWHHDAFSMTAEDRSAKYAGFGFDASIWEMFPTWTIG
P27206_A3_leu                            YTSGTTGQPKGVMVEHHALVNLCFWHHDAFSMTAEDRSAKYAGFGFDASIWEMFPTWSIG
Q70KJ6_A3_6__leu                         YTSGTTGQPKGVMVEHHALVNLCFWHHDAFAMTADDKSAKYAGFGFDASIWEMFPTWTIG
O69246_A3_6__leu                         YTSGTTGQPKGVMVEHRSLVNLCYWHNDAFKVTEHDKSAKYAGFGFDASVWEMFPYWIAG
Q70KJ7_A3_leu                            YTSGTTGQPKGVMVEHHALVNLCFWHHDAFAMTADDKSAKYAGFGFDASIWEMFPTWTIG
Q65NK5_A3_leu                            YTSGTTGQPKGVMVEHQSLVNLCYWHNDAFAVTEQDKSAKYAGFGFDASVWEMFPYWIAG
Q45295_A3_leu                            YTSGTTGQPKGVMVEHRSLVNLCYWHNDAFKVTEQDKSAKYAGFGFDASVWEMFPYWIAG
O68006_A3_leu                            YTSGSTGKPKGVMIEHQSLINLCSWHQSCFEVGQNDNSSIYASISFDAFVWELFPYITAG
                                         ****:**:*****:**::*:*** **:..* :  .*.*: **.:.*** :**:**    *

Q04747_A3_6__leu                         AELHVIDEAIRLDIVRLNDYFETNGVTITFLPTQLAEQFMELENTSLRVLLTGGDKLKRA
P27206_A3_leu                            AELHVIEEAIRLDIVRLNDYFETNGVTITFLPTQLAEQFMELENTSLRVLLTGGDKLKRA
Q70KJ6_A3_6__leu                         AELHVIDEAIRLDITRLNHYFEENGVTITFLPTQLAEQFMELENTSLRMLLVGGDKLKRA
O69246_A3_6__leu                         AELHIIDEAIRMDITRLNQYFEENKITITFLPTQLCEQFMELDNQSLRVLLTGGDKLKRI
Q70KJ7_A3_leu                            AELHVIDEAIRLDITRLNHYFEEHGVTITFLPTQLAEQFMDLENTSLRMLLVGGDKLKRA
Q65NK5_A3_leu                            AELHIIDEAIRMDITRLNEYFEENGITITFLPTQLCEQFMELDNQSLRVLLTGGDKLKRI
Q45295_A3_leu                            AELHIIDESIRMDITRLNQYFEENTITITFLPTQLCEQFMELDNQSLRVLLTGGDKLKRI
O68006_A3_leu                            ATVHVLNQETRLDVEKLNRYFHDHHITISFLPTPVCEQFTALDNHSLRTLLTGGDKLNVF
                                         * :*::::  *:*: :** **. : :**:**** :.***  *:* *** **.*****:  

Q04747_A3_6__leu                         VKKPYTLVNNYGPTENTVVATSAEIHPEEGSLSIGRAIANTRVYILGEGNQVQPEGVAGE
P27206_A3_leu                            VKKPYTLVNNYGPTENTVVATSAEIHPEEGSLSIGRAIANTRVYILGEGNQVQPEGVAGE
Q70KJ6_A3_6__leu                         VKQPYTIINNYGPTENTVVATSGVINPEEGSLSIGRAIANTRVYILGDGDQVQPEGIAGE
O69246_A3_6__leu                         AKRSYTLVNNYGPTENTVVATSAAIDLDEGMLSIGKPIANTRVYVLGQNNEVQPVGVAGE
Q70KJ7_A3_leu                            VKQPYTIINNYGPTENTVVATSGVINPEEGSLSIGRAIANTRVYILGDGDQVQPEGIAGE
Q65NK5_A3_leu                            EKRNYTLVNNYGPTENTVVATSTAIDPDEGMLSIGKPIANTRAYVLGQNNEVQPVGVAGE
Q45295_A3_leu                            AQRSYTLVNNYGPTENTVVATSTAIDPDEGMLSIGKPIANTRAYVLGHNNEVQPVGVAGE
O68006_A3_leu                            KEKSYQIVNNYGPTENTVVATSFPIDKSHQNIPIGKPIDNVKVYILNKDLQLCPLGASGE
                                          :: * ::**************  *. ..  :.**:.* *.:.*:*... :: * * :**

Q04747_A3_6__leu                         LCVAGRGLARGYLNREDETAKRFVADPFVPGERMYRTGDLVKW-VNGGIEYIGRIDQQVK
P27206_A3_leu                            LCVAGRGLARGYLNREDETAKRFVADPFVPGERMYRTGDLVKW-TGGGIEYIGRIDQQVK
Q70KJ6_A3_6__leu                         LCVAGRGLARGYLNREEETAKRFTADPFVPGERMYRTGDLVKWNAQCGIEYIGRIDQQVK
O69246_A3_6__leu                         LCIAGRGLARGYLNKPEETAKRFTEDPFVPGERMYRTGDAVKWLEDGRLEYIGRIDQQVK
Q70KJ7_A3_leu                            LCVAGRGLARGYLNREEETAKRFTADPFVPGERMYRTGDLVKWNAQCGIEYIGRIDQQVK
Q65NK5_A3_leu                            LCIAGRGLARGYLNKPEETAKRFTEDPFVPGERMYRTGDAVKWLEDGRLEYIGRIDQQVK
Q45295_A3_leu                            LCIAGRGLARGYLNKPEETAKRFTEDPFVPGERMYRTGDAVKWLEDGRLEYIGRIDQQVK
O68006_A3_leu                            LCIAGEGLARGYVNRPELTREKFIGNPFVPGERMYRTGDLAKMLPDGNIQFLGRVDQQVK
                                         **:**.******:*: : * ::*  :************* .*      ::::**:*****

Q04747_A3_6__leu                         VRGYRIELSEIEVQLAQLSEVQDAAVTAVKDKGGNTAIAAY-VTPETADIEA
P27206_A3_leu                            VRGYRIELSEIEVQLAQLSEVQDAAVTAVKDKGGNTAIAAY-VTPESADIEA
Q70KJ6_A3_6__leu                         VRGYRIELSEIEVRLAQLADVHDAAVTAVEDKAGNTALCAY-VAPQQDDIEA
O69246_A3_6__leu                         IRGFRIELSEIEVQLARLSEVQEAVVTDIEDACGNKALCGYVVANEQLDTES
Q70KJ7_A3_leu                            VRGYRIELSEIEVRLAQLADVHDAAVTAVEDKAGNTALCAY-VAPQQDDIEA
Q65NK5_A3_leu                            IRGFRIELSEIEVQLARLSEVQEAVVTDIEDAYGNKALCGYVVADEQLDTES
Q45295_A3_leu                            IRGFRIELSEIEVQLARLSEVQEAVVTDIEDAYGNKALCSYVVANEQLDTES
O68006_A3_leu                            IRGYRIEPGEIENRLLKYEKIEEAAVIAREDGDHDPYLCAYVTVKKEVEPEK
                                         :**:*** .*** :* :  .:.:*.*   :*   :  :..* .. :  : * 
