CLUSTAL W multiple sequence alignment


Q65NK5_A2_leu                            SGAAVLLTQKAMKPLAEAAEFGGDILFVEDENLYMGDASDLRLPISPEAMANLTYTSGTT
Q45295_A2_leu                            SGAAVLLTQKAMKPFAEAAEFGGDILFLEDEHLYLGDASDLRLPISPEAMANLTYTSGTT
Q70KJ7_A2_leu                            SGANVLLTQQSLKPLAEKAGFQGVIVLADDEASYEKDSRNPALPFDSKTIANLTYTSGTT
P27206_A2_leu                            SGAKVLLTQRKLKALAEEAEFKGVIVLADEEESYHADARNLALPLDSAAMANLTYTSGTT
                                         *** *****: :*.:** * * * *:: ::*  *  *: :  **:.. ::**********

Q65NK5_A2_leu                            GTPKGNMVSHRNILRTVKNANYLEVMESDIVLSISNYVFDAFMFDVFGSLLNGAKLVIAP
Q45295_A2_leu                            GTPKGNMVSHRNILRTVKNTNYLDVMTSDIVLSISNYVFDAFMFDVFGSLLNGAKLVIAP
Q70KJ7_A2_leu                            GTPKGNIVTHANILRTVKNTNYLTVSEEDTVLGLSNYVFDAFMFDMFGSLLNGAKLVIVP
P27206_A2_leu                            GTPKGNIVTHANILRTVKETNYLSITEQDTILGLSNYVFDAFMFDMFGSLLNGAKLVLIP
                                         ******:*:* *******::*** :  .* :*.:***********:***********: *

Q65NK5_A2_leu                            KDTILDMSRLAHVLEKEKITILMITTALFNLLTDMRPDSLKGLRRVLFGGERASVDHVRR
Q45295_A2_leu                            KDTILDMSRLAHVLEKEKVTVLMITTALFNLLTDMRPDSLKGLRRVLFGGERASVDHVRR
Q70KJ7_A2_leu                            KDTVLDMSRLSRVIKRENVSILMITTALFHLLVDMEPSCLTTLRKIMFGGERASVEHVKK
P27206_A2_leu                            KETVLDMARLSRVIERENISILMITTALFHLLVDLNPACLSTLRKIMFGGERASVEHVRK
                                         *:*:***:**::*:::*::::********:**.*:.* .*. **:::********:**::

Q65NK5_A2_leu                            ALKTVGRGRLLHMYGPSESTVFTTYHPVNEVPDDAQAIPIGKPVSNTEVLILDSFGNVQP
Q45295_A2_leu                            ALNTVGKGRLLHMYGPSESTVFTTYYPVNEVPDDAQAIPIGKPVSNTEVLILDSFGNVQP
Q70KJ7_A2_leu                            ALAAVGKGRLLHMYGPSESTVFATYHPVDVIEEDTLSVPIGKPVSNTEVFIMNSAGRIQP
P27206_A2_leu                            ALQTVGKGKLLHMYGPSESTVFATYHPVDELEEHTLSVPIGKPVSNTEVYILDRTGHVQP
                                         ** :**:*:*************:**:**: : :.: ::*********** *::  *.:**

Q65NK5_A2_leu                            AGVAGELCVGGDGLVRGYFNRPELTAEKFTAHPFKTGEKIYRTGDMARWLA-DGCLEFIG
Q45295_A2_leu                            AGVAGELCVGGDGLVRGYFNRPELTAEKFTEHPFKTGEKIYRTGDMARWLADDGCLEFIG
Q70KJ7_A2_leu                            AGIAGELCVSGEGLVEGYYNRPELTEEKFVKHPFKEGERMYKTGDLARWLP-NGDIEFIG
P27206_A2_leu                            AGIAGELCVTGEGLVKGYYNRPELTEEKFVPHPFTSGERMYKTGDLARWLP-NGTIEFIG
                                         **:****** *:***.**:****** ***. ***. **::*:***:****. :* :****

Q65NK5_A2_leu                            RIDHQVKIRGQRIELGEIEHHLLTHDMVQEAAVLAVDTGAGDQMICAYFTADQELSSQE
Q45295_A2_leu                            RIDHQVKIRGQRIELGEIEHHLLTHEMVQEAAVLAVDTGKRDQMICAYFTADQELSSEE
Q70KJ7_A2_leu                            RIDHQVKIRGQRIELGEIEHQLQSHDQIQECIVLAVDQGAGDKLLCAYVVGLREISSRE
P27206_A2_leu                            RIDHQVKIRGQAIELGEIEHQLQTHDRVQESVVLAVDQGAGDKLLCAYYVGEGDISSQE
                                         *********** ********:* :*: :**. ***** *  *:::*** ..  ::**.*
