CLUSTAL W multiple sequence alignment


AFZ61525.1_2683_mod3_leu                 SAPVAVLAEASTRDLLGA--VATLDLHDPRVQQQAVSNPQLSALTPAHLAYVIYTSGSTG
Q84BQ6v1_A1_leu                          SAPIAVLTQRALRGHLPALSVPVIELDQPSWSAGRVDAPKVPGLTPANLAYVIYTSGSTG
Q84BQ5_A3_5__leu                         SDPVAVLAQGATRELLGR--VPVIDLDNALWQHLPETNPQLPTLTPAHLAYVIYTSGSTG
AFZ61501.1_498_mod1_leu                  SDPVVVLTQHDLLSRLPALEVPVIQLDRPTF--HLGTNPRVA-VSPSNLAYVIYTSGSTG
Q84BQ4_A1_7__leu                         SAPVAVLTQSHLRERLPALNVPVLDLDHCNWPLTVTQNPQVPGLSTANLAYVIYTSGSTG
Q84BQ6v2_A1_leu                          SAPIAVLTQRALRGHLPALSVPVIELDQPSWSAGRVDAPKVPGLTPANLAYVIYTSGSTG
AFZ61526.1_575_mod1_leu                  SAPVAVLTQQALLERLPALDVPVINLDRFTWQHHSASNPKVV-VTPFNLAYVIYTSGSTG
Q84BQ5_A2_4__leu                         CAPVAVVAQASTRDLLGG--VQVIDLDNDLWQHLSDANPQVPALTPKHLAYVIYTSGSTG
                                         . *:.*:::      *    * .::*.           *::  ::. :************

AFZ61525.1_2683_mod3_leu                 QPKGVMVEHRTVENLVHWHCEAFGLDATGHTSSVAGFGFDAMAWEVWPALCVGATLHLPP
Q84BQ6v1_A1_leu                          LPKGVMVEHRTLCNLVDWHADVFDLHAGSHTSSLAGFGFDAMAWEVWPALCVGATLHLAP
Q84BQ5_A3_5__leu                         QPKGVVVEHATLENLVHWHCEAFDLRAGSHTASVAGCGFDAMAWEVWPALCVGATLHLPP
AFZ61501.1_498_mod1_leu                  LPKGVMVEHHTVANLVDWHCQAFDLQAGSHTASVAGFGFDAMAWEIWPALCVGATVHLPP
Q84BQ4_A1_7__leu                         LPKGVMVEHHTLSNLVDWHCTAFDLCAGRHTSSLAGFGFDAMAWEVWPALCAGATLHLAP
Q84BQ6v2_A1_leu                          LPKGVMVEHRTLCNLVDWHADVFDLHAGSHTSSLAGFGFDAMAWEVWPALCVGATLHLAP
AFZ61526.1_575_mod1_leu                  LPKGVMVEHHTVANLVDWHCNAFDLCAGRHTASVAGFGFDAMAWEVWPALCVGATLHLPP
Q84BQ5_A2_4__leu                         QPKGVMVEHATLENLVHWHAEAFDLQAGSQTASVAGFGFDAMAWEVWPALCVGATLHLPP
                                          ****:*** *: ***.**. .*.* *  :*:*:** ********:*****.***:**.*

AFZ61525.1_2683_mod3_leu                 ADVGNENIDELLAWWLAQPLDVSFLPTPVAEYAFSQNLQHPTLRILLIGGDRLRQFTQER
Q84BQ6v1_A1_leu                          ASEGSEDIDALLDWWRAQPLDVSFLPTPIAEYAFSRQLDHPTLRTLLIGGDRLRQFPRQP
Q84BQ5_A3_5__leu                         PSISNEHLDELLDWWRAQPLQVSFLPTPIAEYAFSRELGHPTLRTLLIGGDKLRQFSRGQ
AFZ61501.1_498_mod1_leu                  AHDGAEDIDALLRWWQAQPLQVCFLPTPVAEYAFSQSLQHPTLRTLLIGGDRLRSFTQAQ
Q84BQ4_A1_7__leu                         THEGGEDIDALLAWWCAQPLDVSFLPTPVAEYAFSQNLEHPTLRTLLIGGDRLRQFNRNQ
Q84BQ6v2_A1_leu                          ASEGSEDIDALLDWWRAQPLDVSFLPTPIAEYAFSRQLDHPTLRTLLIGGDRLRQFPRQP
AFZ61526.1_575_mod1_leu                  AHDGAEDIDALLAWWCAQPLDVCFLPTPVAEYAFSQQIEHPTLRTLLIGGDRLRQFGRAQ
Q84BQ5_A2_4__leu                         PSIRNEHLDEMLDWWCAQPLQVSFLPTPVAEYAFSRQLQHPTLRTLLIGGDRLRQFSRQQ
                                         .    *.:* :* ** ****:*.*****:******:.: ***** ******:**.* :  

AFZ61525.1_2683_mod3_leu                 RFAVINNYGPTEATVVATSGRVRAGQVLHIGRPIANASVYLLDAHLRPVPVGVAGELYVG
Q84BQ6v1_A1_leu                          SFEVINNYGPTEATVVATSGRIDAGQALHIGKPVSNATVYLLDEQQQPVPLGVTGELYVG
Q84BQ5_A3_5__leu                         TFDVINNYGPTEATVVATSGSIHAGQLLHIGRPISNARIYLLDEQQRPVPVGVAGELYVG
AFZ61501.1_498_mod1_leu                  SFAVINNYGPTEATVVATSGCMEVGQLLHIGAPIANATVYLLDEQQRPVPIGVAGELYVG
Q84BQ4_A1_7__leu                         HFDVINNYGPTEATVVATSGLVQSGDALHIGKPLSNATVYLLDEQQRPVPLGVAGELYVG
Q84BQ6v2_A1_leu                          SFEVINNYGPTEATVVATSGRIDAGQALHIGKPVSNATVYLLDEQQQPVPLGVTGELYVG
AFZ61526.1_575_mod1_leu                  RFDLINNYGPTEATVVATSGKVEAGQPLHIGKPIANATVYLLDEQQRPVPLGVAGELYVG
Q84BQ5_A2_4__leu                         TFEVINNYGPTEATVVATSGPVELDQPLHIGRPIANVRIYVLDAEQRPVPVGVAGELYVG
                                          * :**************** :  .: **** *::*. :*:** . :***:**:******

AFZ61525.1_2683_mod3_leu                 GSGVARGYLNRPDLSAGRFLHDPFN---EGRMYRTGDLARWLPDGNIEYLGRNDDQVKVR
Q84BQ6v1_A1_leu                          GAGVARGYLNRAELSAERFLRDPFSAEPGARLYRTGDLARWRADGNLEYLGRNDDQVKIR
Q84BQ5_A3_5__leu                         GAGVARGYLNRPELTAERFLEDPFSDRPQARMYRTGDLARWLADGNIEYLGRNDDQVKLR
AFZ61501.1_498_mod1_leu                  GKGVARGYLNRPELSAERFLDDPFI---EGRMYRTGDLARWLPEGSLEYLGRNDDQVKIR
Q84BQ4_A1_7__leu                         GAGVARGYLNRPDMTAERFLRDPFSRAPNARMYRTGDLARWREDGNIEYLGRNDDQVKIR
Q84BQ6v2_A1_leu                          GAGVARGYLNRAELSAERFLRDPFSAEPGARLYRTGDLARWRADGNLEYLGRNDDQVKIR
AFZ61526.1_575_mod1_leu                  GNGVARGYLNRPELTAERFLQDPFN---TGRMYRTGDLARWLPDGNIEYLGRNDDQVKIR
Q84BQ5_A2_4__leu                         GAGVARGYLNRPELSAAQFLFDPFSDEPQARMYRTGDQARWLADGNIEYLGRNDDQVKLR
                                         * *********.:::* :** ***     .*:***** ***  :*.:***********:*

AFZ61525.1_2683_mod3_leu                 GVRVELGEIESRLAALDGVAEAVVLVREG-----RLIAWFT--EQQPLDIDT
Q84BQ6v1_A1_leu                          GIRIEPGEIESALASHSAVREAVVLVRDG-----QLLAWFT--EQAPLDINE
Q84BQ5_A3_5__leu                         GVRVELGEIEAALSSHPAVQDAVVLVREA-----RLIAWFT--ARTTVDNED
AFZ61501.1_498_mod1_leu                  GMRIELGEIESALATHPHVQDAVVQSRDG-----QLLAWFVPREALQIEA--
Q84BQ4_A1_7__leu                         GVRIELGEIETCLNQLPGIQEAVLLAREDQPGQPRLVAYFT--EQPQVEA--
Q84BQ6v2_A1_leu                          GIRIEPGEIESALASHSAVREAVVLVRDG-----QLLAWFT--EQAPLDINE
AFZ61526.1_575_mod1_leu                  GMRIELGEIETQLNQVAGIQEAVVLVREE-----RLVAYFT--ENRQLDP--
Q84BQ5_A2_4__leu                         GVRIELGEIEAALGSHVALQEAVVLVRDG-----RLIAWFT--ERTAVDIQQ
                                         *:*:* ****: *     : :**:  *:      :*:*:*.      ::   
