CLUSTAL W multiple sequence alignment


Q7WRQ4_A2_9__me-asp                      TSPTMIVVDSENLDIIKPRLALLPKPPQILVINAHEIQQYYQWDGTNYQCLLVEANHDKK
Q9S1A8_A2_9__me-asp                      TSPEIILVAAENLEGIKPQLSALEKPPHILVVKAHKIQQYHQWNGMDYQEFPCQLSKLQP
Q8G982_A2_9__me-asp                      TSPAIILIAAENLEMIKPRLLVLAKPPNLLVVNHQEIQQYYEWNGTNYQEFSIVENNNRK
Q847C7_A2_7__me-asp                      TSPSIVVTAAEYLDVVKSRLAALSKPPHILVITANEITQRYEWNGTNYQSFSVVESENPK
                                         *** :::  :* *: :*.:*  * ***::**:. ::* * ::*:* :** :    ..   

Q7WRQ4_A2_9__me-asp                      VLIMPDADDSNYIMFTSGSTGEPKAILGSHGSLRHFINWEKLEFGINSNWRCLQIAQINF
Q9S1A8_A2_9__me-asp                      LLAMPDADDSNYIMFTSGSTGEPKAILGSHGSLRHFIDWEKREFGINESWHCLQIAQINF
Q8G982_A2_9__me-asp                      DLLMPDADDANYIIFTSGSTGEPKAILGSHGSLRHFINWEKIEFGINHNWRCLQIAQINF
Q847C7_A2_7__me-asp                      TLLLPDADDSNYIMFTSGSTGEPKAILGSHGSLRHFINWEKIEFGINQNWRCLQIAQINF
                                          * :*****:***:***********************:*** ***** .*:*********

Q7WRQ4_A2_9__me-asp                      DAYLRETLVTLCSGGTLYIPDSTDREDLEKLLLRLGEWQINLLHTVPSVMRLFLKIGRNL
Q9S1A8_A2_9__me-asp                      DAYLRETCVTLCSGGTLYIPESTEREDLELLLLRIGEWEINLLHTVPSVMRLFLKIGRGL
Q8G982_A2_9__me-asp                      DPYLRETLVTLCSGGTLYIPDSIDREDLERLLLRLGEWQINLLHTVPSVMRLFLNIGRNL
Q847C7_A2_7__me-asp                      DAYLRETLVTLCSGGTLYIPDSTDREDLEGLLLRLGEWQINLLHTVPSVMRLFLKIGENL
                                         *.***** ************:* :***** ****:***:***************:**..*

Q7WRQ4_A2_9__me-asp                      TNADQLLKNLRVLVLGGEPLFVKELREWHQVFGSQTEFVNIYGASETTFVKHFHRIPDPN
Q9S1A8_A2_9__me-asp                      VNAHNLLKSLRIFVLGGEPLFVKELAEWHQIFGSQTEFVNIYGASETTFVKHFYRIPNPN
Q8G982_A2_9__me-asp                      PNANQLLKNLQVLVLGGEPLFVKELCEWHEVFGNQTEFVNIYGASETTFIKHFHRIPKPN
Q847C7_A2_7__me-asp                      AHADQLLKNLQVLVLGGEPLFVKELCEWHKVFGEQTEFVNIYGASETTFVKHFYRIPDPS
                                          :*.:***.*:::************ ***::**.***************:***:***.*.

Q7WRQ4_A2_9__me-asp                      KITYARVPGGKTLPEAAFAVIDGTRPCAVGEVGEIFVKSPYLTKGYYQDQRLTNSVFIPN
Q9S1A8_A2_9__me-asp                      NIPYERVPGGQTLPDAAYAVVDGNRARAIGEVGEVFVKSPYLTKGYYQDESLTHSVFVPN
Q8G982_A2_9__me-asp                      NISYARVPGGKTLPDAAFAVIDENRPCAIGEVGEIFVKSPYLTKGYYQDEILTNSVFVPN
Q847C7_A2_7__me-asp                      KITYARVPAGKTLSDAAFAVINGTRPCAVGEVGEIFVKSPYLTKGYYQDQKLTNLVFVPN
                                         :*.* ***.*:**.:**:**:: .*. *:*****:**************: **: **:**

Q7WRQ4_A2_9__me-asp                      PLNHGADIVYCTGDLGRLLPDLTVEVIG-RSDKQVKLNGVRIELGEIEDALAAIDGVEKA
Q9S1A8_A2_9__me-asp                      PLNGGRDIVYRTGDLGRLLPDLTLEVIG-RSDNQIKLNGVRIELGEIEDVLSGIEGVEKA
Q8G982_A2_9__me-asp                      PLNNGNDLVYRTGDLGRLLPDLTLEVIGRRSDNQIKLNGVRIELGEIEDAVAAIDGVQKA
Q847C7_A2_7__me-asp                      PLNNGSDLVYRTGDLGRLLPDMSLEVVG-RSDNQIKLNGVRIELGEIENAIYAIDGVEKT
                                         *** * *:** **********:::**:* ***:*:*************:.: .*:**:*:

Q7WRQ4_A2_9__me-asp                      LVIAEEKEELVTVIAYYQAKNAINHQH
Q9S1A8_A2_9__me-asp                      LVMANKKEELVTVIAYYQAEDTVHQEY
Q8G982_A2_9__me-asp                      LVIADKKEELVTVIAYYQGNNTVNREQ
Q847C7_A2_7__me-asp                      LVVAEKKEELVTVIAYYQGNDTANQED
                                         **:*::************.::: ::: 
