CLUSTAL W multiple sequence alignment


Q50E73_A1_6__orn                         AHPTVVLTTTTATPLP-HPGRTLVLDSPTTARALAAAPAHNLTDADRRTPLNARNAAYII
AHH53507.1_475_mod1_orn                  ARPTLVL-TTTANHLPDHPAPTLALDDAPARAELLAAPTRTPRDVDRVVPAHPAHPAYVI
BGC0000439_AHH53507.1_475_mod1_orn       ARPTLVL-TTTANHLPDHPAPTLALDDAPARAELLAAPTRTPRDVDRVVPAHPAHPAYVI
                                         *:**:** ****. ** **. **.**...:   * ***::.  *.** .* :. :.**:*

Q50E73_A1_6__orn                         HTSGSTGRPKGVVIEHRSLANLFHDHRRALIEPHAAGGSRLKAGLTASLSFDTSWEGLIC
AHH53507.1_475_mod1_orn                  YTSGSTGRPKGVVLTHEGLRNLYHDHATGLIEPHAPRTRRLRAGLSAALSFDTSWECLLS
BGC0000439_AHH53507.1_475_mod1_orn       YTSGSTGRPKGVVLTHEGLRNLYHDHATGLIEPHAPRTRRLRAGLSAALSFDTSWECLLS
                                         :************: *..* **:***  .******.   **:***:*:******** *:.

Q50E73_A1_6__orn                         LAAGHELHLIDDDTRRDAERVAELIDRQRIDVIDVTPSFAQQLVETGILDEGRHHPAAFM
AHH53507.1_475_mod1_orn                  LAAGHELHLVDDDTRRDAELLVRYVEHHRLDLLDLTPSHAQQLVETGLLAEDAHHPTVLM
BGC0000439_AHH53507.1_475_mod1_orn       LAAGHELHLVDDDTRRDAELLVRYVEHHRLDLLDLTPSHAQQLVETGLLAEDAHHPTVLM
                                         *********:********* :.. ::::*:*::*:***.********:* *. ***:.:*

Q50E73_A1_6__orn                         LGGEGVDAKLWTRLSDVPGVTSYNYYGPTEFTVDALACTVGIAPRPVIGHPLDNTAAYIL
AHH53507.1_475_mod1_orn                  LGGEAVPPALWSRLRAAPHTRCYNYYGPTEFTVDAVACALDESEHPIVGRPLDNTRAYVL
BGC0000439_AHH53507.1_475_mod1_orn       LGGEAVPPALWSRLRAAPHTRCYNYYGPTEFTVDAVACALDESEHPIVGRPLDNTRAYVL
                                         ****.* . **:**  .* . .*************:**::. : :*::*:***** **:*

Q50E73_A1_6__orn                         DGFLRPVPEGVAGELYLAGTQLARGYAGRPGLTAERFVACPFGAPGERMYRTGDLVRRSP
AHH53507.1_475_mod1_orn                  NAALLPVAPGVPGELYLAGPQLARGYLGRAALTADRFVACPFGTPGERMYRTGDLAAWTE
BGC0000439_AHH53507.1_475_mod1_orn       NAALLPVAPGVPGELYLAGPQLARGYLGRAALTADRFVACPFGTPGERMYRTGDLAAWTE
                                         :. * **. **.*******.****** **..***:********:***********.  : 

Q50E73_A1_6__orn                         GGVVEYLGRVDDQIKLRGFRIEPAEIELALAGHPAVAQNVVLLHRSATGEARLVAYVVP-
AHH53507.1_475_mod1_orn                  HGTLRFLGRADGQVKIRGFRVELGEVEHALLTHPSVGQCAVVAARTEPAGTRLVAYLVPR
BGC0000439_AHH53507.1_475_mod1_orn       HGTLRFLGRADGQVKIRGFRVELGEVEHALLTHPSVGQCAVVAARTEPAGTRLVAYLVPR
                                          *.:.:***.*.*:*:****:* .*:* **  **:*.* .*:  *: .. :*****:** 

Q50E73_A1_6__orn                         -------GTPVDPRE
AHH53507.1_475_mod1_orn                  ASHPGAVDTGV----
BGC0000439_AHH53507.1_475_mod1_orn       ASHPGAVDTGV----
                                                .* *    
