CLUSTAL W multiple sequence alignment


AGM16412.1_4054_mod4_orn                 SHAQVLLAQRHMQASVAFAGTWVILDEEAFYHEDGTNLEPLNEPMHLSYVIYTSGTTGNP
P0C064_A3_4__orn                         SGAALLLTQQKLTQQIAFSGDILYLDQEEWLHEEASNLEPIARPQDIAYIIYTSGTTGKP
BGC0000400_AGM16412.1_4054_mod4_orn      SHAQVLLAQRHMQASVAFAGTWVILDEEAFYHEDGTNLEPLNEPMHLSYVIYTSGTTGNP
O33743_A5_9__orn                         SEAKLLLTLQKMNSQVAFPYETFYLDTETVDQEETGNLEHVAQPENVAYIIYTSGTTGKP
P0C063_A3_orn                            SGAALLLTQQKLTQQIAFSGDILYLDQEEWLHEEASNLEPIARPHYIAYIIYTSGTTGKP
                                         * * :**: :::  .:**.   . ** *   :*:  *** : .*  ::*:********:*

AGM16412.1_4054_mod4_orn                 KGVMIEHRQLVAIADAWKREYRLEEEGIRWLQWAS--FSFDVFSGDMVRTLLYGGELILC
P0C064_A3_4__orn                         KGVMIEHQSYVNVAMAWKDAYRLDTFPVRLLQMAS--FAFDVSAGDFARALLTGGQLIVC
BGC0000400_AGM16412.1_4054_mod4_orn      KGVMIEHRQLVAIADAWKREYRLEEEGIRWLQWAS--FSFDVFSGDMVRTLLYGGELILC
O33743_A5_9__orn                         KGVVIEHRSYANVAFAWKDEYHLDSFPVRLLQMAS--FAFDVSTGDFARALLTGGQLVIC
P0C063_A3_orn                            KGVMIEHQSYVNVAMAWKDAYRLDTFPVRLLQMASFAFAFDVSAGDFARALLTGGQLIVC
                                         ***:***:. . :* ***  *:*:   :* ** **  *:*** :**:.*:** **:*::*

AGM16412.1_4054_mod4_orn                 PEQARANPAAISELIRKHQIQMFESTPALVIPFMDYVYDNNLDISSLKMLIVGSDHCPTA
P0C064_A3_4__orn                         PNEVKMDPASLYAIIKKYDITIFEATPALVIPLMEYIYEQKLDISQLQILIVGSDSCSME
BGC0000400_AGM16412.1_4054_mod4_orn      PEQARANPAAISELIRKHQIQMFESTPALVIPFMDYVYDNNLDISSLKMLIVGSDHCPTA
O33743_A5_9__orn                         PNGVKMDPASLYETIRRHEITIFEATPALIMPLMHYVYENELDMSQMKLLILGADSCPAE
P0C063_A3_orn                            PNEVKMDPASLYAIIKKYDITIFEATPALVIPLMEYIYEQKLDISQLQILIVGSDSCSME
                                         *: .: :**::   *::::* :**:****::*:*.*:*:::**:*.:::**:*:* *.  

AGM16412.1_4054_mod4_orn                 EFDKLTERCGSHMRILNSYGVTEACVDACYYERTTPDALR--TLPIGKPLPAVTMYILDD
P0C064_A3_4__orn                         DFKTLVSRFGSTIRIVNSYGVTEACIDSSYYEQPLSSLHVTGTVPIGKPYANMKMYIMNQ
BGC0000400_AGM16412.1_4054_mod4_orn      EFDKLTERCGSHMRILNSYGVTEACVDACYYERTTPDALR--TLPIGKPLPAVTMYILDD
O33743_A5_9__orn                         DFKTLLARFGQKMRIINSYGVTEACIDTSYYEETDVTAIRSGTVPIGKPLPNMTMYVVDA
P0C063_A3_orn                            DFKTLVSRFGSTIRIVNSYGVTEAALILAIMNQPLSSLHVTGTVPIGKPYANMKMYIMNQ
                                         :*..*  * *. :**:********.:  .  :..        *:***** . :.**::: 

AGM16412.1_4054_mod4_orn                 NRSLQPIGHTGELYIGGAGVGRGYLNRPDLTVEKFVDNPFMPGARMYRTGDLARWLPDGN
P0C064_A3_4__orn                         YLQIQPVGVIGELCIGGAGVARGYLNRPDLTAEKFVPNPFVPGEKLYRTGDLARWMPDGN
BGC0000400_AGM16412.1_4054_mod4_orn      NRSLQPIGHTGELYIGGAGVGRGYLNRPDLTVEKFVDNPFMPGARMYRTGDLARWLPDGN
O33743_A5_9__orn                         HLNLQPVGVVGELCIGGAGVARGYLNRPELTEEKFVPNPFAPGERLYRTGDLAKWRADGN
P0C063_A3_orn                            YLQIQPVGVIGELCIGGAGVARGYLNRPDLTAEKFVPNPFVPGEKLYRTGDLARWMPDGN
                                           .:**:*  *** ******.*******:** **** *** ** ::*******:* .***

AGM16412.1_4054_mod4_orn                 IEYAGRIDHQVKIRGYRIEIGEVESQLLAAAGVREAAVVAREDGSGQKVLCAYFVADSAL
P0C064_A3_4__orn                         VEFLGRNDHQVKIRGIRIELGEIEAQLRKHDSIKEATVIAREDHMKEKYLCAYMVTEGEV
BGC0000400_AGM16412.1_4054_mod4_orn      IEYAGRIDHQVKIRGYRIEIGEVESQLLAAAGVREAAVVAREDGSGQKVLCAYFVADSAL
O33743_A5_9__orn                         VEFLGRNDHQVKIRGVRIELGEIETQLRKLDGITEAVVVAREDRGQEKELCAYVVADHKL
P0C063_A3_orn                            VEFLGRNDHQVKIRGIRIELGEIEAQLRKHDSIKEATVIAREDHMKEKYLCAYMVTEGEV
                                         :*: ** ******** ***:**:*:**    .: **.*:****   :* ****.*::  :

AGM16412.1_4054_mod4_orn                 TVGE
P0C064_A3_4__orn                         NVAE
BGC0000400_AGM16412.1_4054_mod4_orn      TVGE
O33743_A5_9__orn                         DTAE
P0C063_A3_orn                            NVAE
                                          ..*
