CLUSTAL W multiple sequence alignment


O68007_A2_7__orn                         SGADLLLTQHQLIGSISFAGEIIQIDQADAYDTDGSNLEHLNSPGDLAYVIYTSGTTGNP
AGM16412.1_4054_mod4_orn                 SHAQVLLAQRHMQASVAFAGTWVILDEEAFYHEDGTNLEPLNEPMHLSYVIYTSGTTGNP
P0C064_A3_4__orn                         SGAALLLTQQKLTQQIAFSGDILYLDQEEWLHEEASNLEPIARPQDIAYIIYTSGTTGKP
BGC0000400_AGM16412.1_4054_mod4_orn      SHAQVLLAQRHMQASVAFAGTWVILDEEAFYHEDGTNLEPLNEPMHLSYVIYTSGTTGNP
O33743_A5_9__orn                         SEAKLLLTLQKMNSQVAFPYETFYLDTETVDQEETGNLEHVAQPENVAYIIYTSGTTGKP
P0C063_A3_orn                            SGAALLLTQQKLTQQIAFSGDILYLDQEEWLHEEASNLEPIARPHYIAYIIYTSGTTGKP
                                         * * :**: :::  .::*.   . :*     . :  *** :  *  ::*:********:*

O68007_A2_7__orn                         KGVMVEHRNIIHAHYTWRKHYELASFSVNLLQLAS--MSFDVFAGDLCRSLLNGGTMYIV
AGM16412.1_4054_mod4_orn                 KGVMIEHRQLVAIADAWKREYRLEEEGIRWLQWAS--FSFDVFSGDMVRTLLYGGELILC
P0C064_A3_4__orn                         KGVMIEHQSYVNVAMAWKDAYRLDTFPVRLLQMAS--FAFDVSAGDFARALLTGGQLIVC
BGC0000400_AGM16412.1_4054_mod4_orn      KGVMIEHRQLVAIADAWKREYRLEEEGIRWLQWAS--FSFDVFSGDMVRTLLYGGELILC
O33743_A5_9__orn                         KGVVIEHRSYANVAFAWKDEYHLDSFPVRLLQMAS--FAFDVSTGDFARALLTGGQLVIC
P0C063_A3_orn                            KGVMIEHQSYVNVAMAWKDAYRLDTFPVRLLQMASFAFAFDVSAGDFARALLTGGQLIVC
                                         ***::**:.      :*:  *.*    :. ** **  ::*** :**: *:** ** : : 

O68007_A2_7__orn                         PDDVKLEMNLLYDMINKYGIHMLESTPSLIIPLMKYIDHHKLDFSSMKLLIMGSDTCTIK
AGM16412.1_4054_mod4_orn                 PEQARANPAAISELIRKHQIQMFESTPALVIPFMDYVYDNNLDISSLKMLIVGSDHCPTA
P0C064_A3_4__orn                         PNEVKMDPASLYAIIKKYDITIFEATPALVIPLMEYIYEQKLDISQLQILIVGSDSCSME
BGC0000400_AGM16412.1_4054_mod4_orn      PEQARANPAAISELIRKHQIQMFESTPALVIPFMDYVYDNNLDISSLKMLIVGSDHCPTA
O33743_A5_9__orn                         PNGVKMDPASLYETIRRHEITIFEATPALIMPLMHYVYENELDMSQMKLLILGADSCPAE
P0C063_A3_orn                            PNEVKMDPASLYAIIKKYDITIFEATPALVIPLMEYIYEQKLDISQLQILIVGSDSCSME
                                         *: .: :   :   *.:: * ::*:**:*::*:*.*: .::**:*.:::**:*:* *.  

O68007_A2_7__orn                         DYKWLVERFGQRMRIINSYGVTEASVDSGYYEEALDRIPEIANTPIGKPLDNTAFYILDP
AGM16412.1_4054_mod4_orn                 EFDKLTERCGSHMRILNSYGVTEACVDACYYERTTPDALR--TLPIGKPLPAVTMYILDD
P0C064_A3_4__orn                         DFKTLVSRFGSTIRIVNSYGVTEACIDSSYYEQPLSSLHVTGTVPIGKPYANMKMYIMNQ
BGC0000400_AGM16412.1_4054_mod4_orn      EFDKLTERCGSHMRILNSYGVTEACVDACYYERTTPDALR--TLPIGKPLPAVTMYILDD
O33743_A5_9__orn                         DFKTLLARFGQKMRIINSYGVTEACIDTSYYEETDVTAIRSGTVPIGKPLPNMTMYVVDA
P0C063_A3_orn                            DFKTLVSRFGSTIRIVNSYGVTEAALILAIMNQPLSSLHVTGTVPIGKPYANMKMYIMNQ
                                         ::. *  * *. :**:********.:     :..        . *****     :*::: 

O68007_A2_7__orn                         SLNPQPVGVYGELYIGGEGIARGYLNKPELTKERFVPNRFAAGGNMYKTGDLARWLPDGN
AGM16412.1_4054_mod4_orn                 NRSLQPIGHTGELYIGGAGVGRGYLNRPDLTVEKFVDNPFMPGARMYRTGDLARWLPDGN
P0C064_A3_4__orn                         YLQIQPVGVIGELCIGGAGVARGYLNRPDLTAEKFVPNPFVPGEKLYRTGDLARWMPDGN
BGC0000400_AGM16412.1_4054_mod4_orn      NRSLQPIGHTGELYIGGAGVGRGYLNRPDLTVEKFVDNPFMPGARMYRTGDLARWLPDGN
O33743_A5_9__orn                         HLNLQPVGVVGELCIGGAGVARGYLNRPELTEEKFVPNPFAPGERLYRTGDLAKWRADGN
P0C063_A3_orn                            YLQIQPVGVIGELCIGGAGVARGYLNRPDLTAEKFVPNPFVPGEKLYRTGDLARWMPDGN
                                           . **:*  *** *** *:.*****:*:** *:** * * .* .:*:*****:* .***

O68007_A2_7__orn                         VEFLGRIDHQVKIRGFRIETGEIETKLLENQNISEAVVIDREDKKGHKYLCAYIVARAKT
AGM16412.1_4054_mod4_orn                 IEYAGRIDHQVKIRGYRIEIGEVESQLLAAAGVREAAVVAREDGSGQKVLCAYFVADSAL
P0C064_A3_4__orn                         VEFLGRNDHQVKIRGIRIELGEIEAQLRKHDSIKEATVIAREDHMKEKYLCAYMVTEGEV
BGC0000400_AGM16412.1_4054_mod4_orn      IEYAGRIDHQVKIRGYRIEIGEVESQLLAAAGVREAAVVAREDGSGQKVLCAYFVADSAL
O33743_A5_9__orn                         VEFLGRNDHQVKIRGVRIELGEIETQLRKLDGITEAVVVAREDRGQEKELCAYVVADHKL
P0C063_A3_orn                            VEFLGRNDHQVKIRGIRIELGEIEAQLRKHDSIKEATVIAREDHMKEKYLCAYMVTEGEV
                                         :*: ** ******** *** **:*::*    .: **.*: ***   .* ****.*:    

O68007_A2_7__orn                         NTNE
AGM16412.1_4054_mod4_orn                 TVGE
P0C064_A3_4__orn                         NVAE
BGC0000400_AGM16412.1_4054_mod4_orn      TVGE
O33743_A5_9__orn                         DTAE
P0C063_A3_orn                            NVAE
                                          . *
