CLUSTAL W multiple sequence alignment


CBG75492_4248_mod4_orn                   AAPLCVLSTAELAAKLPEGAPVVLIDDLVPDEGEAPAVVPPAPSGTAYVIFTSGSTGTPK
BGC0000423_CBG75492.1_4248_mod4_orn      AAPLCVLSTAELAAKLPEGAPVVLIDDLVPDEGEAPAVVPPAPSGTAYVIFTSGSTGTPK
                                         ************************************************************

CBG75492_4248_mod4_orn                   GVVGTHRGLSNLFAAHRDDLIRPAERSLGRDRLRAVHAASFSFDGSWEPLLWLLAGHEVQ
BGC0000423_CBG75492.1_4248_mod4_orn      GVVGTHRGLSNLFAAHRDDLIRPAERSLGRDRLRAVHAASFSFDGSWEPLLWLLAGHEVQ
                                         ************************************************************

CBG75492_4248_mod4_orn                   VVEEAVMADPAALLAHLCREDIDFLDVTPTYLRELIHHGFLEPGTPLPGVIAVGGEATPA
BGC0000423_CBG75492.1_4248_mod4_orn      VVEEAVMADPAALLAHLCREDIDFLDVTPTYLRELIHHGFLEPGTPLPGVIAVGGEATPA
                                         ************************************************************

CBG75492_4248_mod4_orn                   PLWERLCALPGVQVHDLYGPTESAVDAYGWHSDATGRWAAPLDNIRAHVLDELLRPVPAG
BGC0000423_CBG75492.1_4248_mod4_orn      PLWERLCALPGVQVHDLYGPTESAVDAYGWHSDATGRWAAPLDNIRAHVLDELLRPVPAG
                                         ************************************************************

CBG75492_4248_mod4_orn                   VTGELYLAGEGLARGYLNRPGLTAERFTADPFGAPGSRMYRTGDLVRRRRDGSLEFLGRA
BGC0000423_CBG75492.1_4248_mod4_orn      VTGELYLAGEGLARGYLNRPGLTAERFTADPFGAPGSRMYRTGDLVRRRRDGSLEFLGRA
                                         ************************************************************

CBG75492_4248_mod4_orn                   DGQVKLRGFRIEPGEIEALLARHPDVATAAVVVREDTPGVRRLVAYVLPAAGRTPDPAE
BGC0000423_CBG75492.1_4248_mod4_orn      DGQVKLRGFRIEPGEIEALLARHPDVATAAVVVREDTPGVRRLVAYVLPAAGRTPDPAE
                                         ***********************************************************
