CLUSTAL W multiple sequence alignment


Q70JX1_A2_orn                            SAASVLMVQSEYKELASQLTDHNLFLIQLDLEDQYDICAKNIQPSASPDDTAYIIYTSGT
P0C064_A3_4__orn                         SGAALLLTQQKLTQQIAFSGD----ILYLDQEEWLHEEASNLEPIARPQDIAYIIYTSGT
O87606_A2_orn                            SGAEILLLQNEVKHLIAGSDIGDISRVCLDDESFYESKKMHLSSSPAPEDSAYIIYTSGT
P39845_A2_orn                            SGADILLLQRELKHLISNSPESEMSHIFLDDEGSFEESNCNLNLSPAPEEPVYIIYTSGT
O33743_A5_9__orn                         SEAKLLLTLQKMNSQVAFPYE----TFYLDTETVDQEETGNLEHVAQPENVAYIIYTSGT
                                         * * :*:   : .   :         . ** *   .    ::.  . *:: .********

Q70JX1_A2_orn                            TGTPKGVEVRNRSFTHAALAWRRIYELDLIPVRVLQMASFSFDVFSGDLARALLNGGTLV
P0C064_A3_4__orn                         TGKPKGVMIEHQSYVNVAMAWKDAYRLDTFPVRLLQMASFAFDVSAGDFARALLTGGQLI
O87606_A2_orn                            TGAPKGVIVTHRNFAHAVLAWRRIYQLDQMPVRLLQMASFSFDVFSGDLARTLANGGTLV
P39845_A2_orn                            TGAPKGVIVTYQNFTHAALAWRQIYELDRKPVRLLQIASFSFDVFSGDLARTLTNGGTLI
O33743_A5_9__orn                         TGKPKGVVIEHRSYANVAFAWKDEYHLDSFPVRLLQMASFAFDVSTGDFARALLTGGQLV
                                         ** **** :  :.:.:..:**:  *.**  ***:**:***:*** :**:**:* .** *:

Q70JX1_A2_orn                            ICPDDVRLEPQQLYRLIDQHRITFMESTPALVVPFMEYIYRRKLALQSVKILVLGSDMIK
P0C064_A3_4__orn                         VCPNEVKMDPASLYAIIKKYDITIFEATPALVIPLMEYIYEQKLDISQLQILIVGSDSCS
O87606_A2_orn                            ICPDETRLEPAELYALMNRQRITIMESTPALIVPFMEYVYRNQLSLPDLDILILGSDMVK
P39845_A2_orn                            VCPDETRLEPAEIYKIIKSQRITVMESTPALIIPVMEYVYRNQFKLPDLDILILGSDMVK
O33743_A5_9__orn                         ICPNGVKMDPASLYETIRRHEITIFEATPALIMPLMHYVYENELDMSQMKLLILGADSCP
                                         :**: .:::* .:*  :    **.:*:****::*.*.*:*..:: : .:.:*::*:*   

Q70JX1_A2_orn                            SQDFYTLHERFGKEMRIINSYGVTEATIDSSYYEAEMSEEPREDDVPIGVPLPNVQMYVL
P0C064_A3_4__orn                         MEDFKTLVSRFGSTIRIVNSYGVTEACIDSSYYEQPLSSLHVTGTVPIGKPYANMKMYIM
O87606_A2_orn                            AHDFKTLADRFGNKMRLINSYGVTEATIDSSYYEMNMGEEYSGDSVPIGIPLPNVKLCVL
P39845_A2_orn                            AQDFKTLTDRFGQSMRIINSYGVTEATIDSSFYETSMGGECTGDNVPIGSPLPNVHMYVL
O33743_A5_9__orn                         AEDFKTLLARFGQKMRIINSYGVTEACIDTSYYEETDVTAIRSGTVPIGKPLPNMTMYVV
                                          .** **  ***. :*::******** **:*:**         . **** * .*: : ::

Q70JX1_A2_orn                            NKDKQVQPIGVFGELYIGGAGVAKGYWGQPELTEGAFS-DPLQMGETLYRTGDQACWLPD
P0C064_A3_4__orn                         NQYLQIQPVGVIGELCIGGAGVARGYLNRPDLTAEKFVPNPFVPGEKLYRTGDLARWMPD
O87606_A2_orn                            SQTDQIQPIGIAGELCIAGAGVAKGYHGKFELTEKKFTENPFVPGERLYRTGDLACWLPN
P39845_A2_orn                            SQTDQIQPIGVAGELCIGGAGVAKGYHHKPDLTQMKFTENPFVSGERLYRTGDRACWLPN
O33743_A5_9__orn                         DAHLNLQPVGVVGELCIGGAGVARGYLNRPELTEEKFVPNPFAPGERLYRTGDLAKWRAD
                                         .   ::**:*: *** *.*****:**  : :**   *  :*:  ** ****** * * .:

Q70JX1_A2_orn                            GTLRFQGRIDKQVKIRGYRIETGEIESVLLKHDQVKEAAVTVIKDAEGQARLAAYIVPK-
P0C064_A3_4__orn                         GNVEFLGRNDHQVKIRGIRIELGEIEAQLRKHDSIKEATVIAREDHMKEKYLCAYMVTEG
O87606_A2_orn                            GTLRLLGRIDHQVKINGYRIETEEIESVLLQTGLVNEAVVAVQNDTNGQARLAAYILPS-
P39845_A2_orn                            GTIRLLGRMDYQVKINGYRIETEEIESVLLQTGLVREAAVAVQHDKNGQAGLAAYIVPS-
O33743_A5_9__orn                         GNVEFLGRNDHQVKIRGVRIELGEIETQLRKLDGITEAVVVAREDRGQEKELCAYVVADH
                                         *.:.: ** * ****.* ***  ***: * : . : **.* . .*   :  *.**::.. 

Q70JX1_A2_orn                            EADTSS
P0C064_A3_4__orn                         EVNVAE
O87606_A2_orn                            DADTTA
P39845_A2_orn                            DVNTNA
O33743_A5_9__orn                         KLDTAE
                                         . :.  
