CLUSTAL W multiple sequence alignment


Q7WRJ0/31616733_ALod_phe-ac              CELISKIEKLTTQSHLKELRVVSIDKLRSNQSLSNQL------SAHELPHLTPLDPALLL
Q8G985/24744795_ALod_phe-ac              NELITEIQKLETQSHLKGLQVVSIDYLRSIESQSNSQPDKTSKKCYSLPDLTPENQALLL
Q9FDT8_ALod_phe-ac                       SELITEIEKLGTYSHLEGWQVISVNELR-----------KAPSKIEQLPILDPQDAALLL
                                          ***::*:** * ***:  :*:*:: **               .  .** * * : ****

Q7WRJ0/31616733_ALod_phe-ac              FTSGSTGLPKGVMLHHRNLLSMSVGTVRMNNFTRQEVTLNWMPLDHVGAIVFLGIMAVDL
Q8G985/24744795_ALod_phe-ac              FTSGSTGMPKGVMLTHNNLLSMSAGTVAMNNFSQQEVTLNWMPLDHAGAIVFLGIMAVDL
Q9FDT8_ALod_phe-ac                       FTSGSTGMPKGVILTHHNILSMTAGTVVMNHFTQQEVTLNWMPLDHVGAIVFLGIMAVDL
                                         *******:****:* *.*:***:.*** **:*::************.*************

Q7WRJ0/31616733_ALod_phe-ac              ACHQIHVPIELILRQPLKWLGLIQKYQATISWSPNFAFSLINQHTEELNQSCYDLSSIKF
Q8G985/24744795_ALod_phe-ac              ACDQIHVPMELILRQPLKWLELIQNHQATISWAPNFAFSLINQQSEQLNQSSYNLSSMKF
Q9FDT8_ALod_phe-ac                       ACDQIHVPMELVLRQPLQWLELIQKHQVSISWSPNFAFSLINQQAEELKHVSYNLSSMKF
                                         **.*****:**:*****:** ***::*.:***:**********::*:*:: .*:***:**

Q7WRJ0/31616733_ALod_phe-ac              LVNAGEQVSVKTIRLFLEILEKHKLRDRVIKPAFGMTESCSGITWSAGLSKDELIEENSF
Q8G985/24744795_ALod_phe-ac              LVNAGEQVSIKTIRLFLEILEKHQLPDRAIKPAFGMTESCSGITWSVGLSQDKLTEENII
Q9FDT8_ALod_phe-ac                       LVNAGEQVSVKTIRLFLEILEKHQLQERAIKPAFGMTESCSGITWSAGLSKNELTEENSF
                                         *********:*************:* :*.*****************.***:::* *** :

Q7WRJ0/31616733_ALod_phe-ac              VSLGRPIPGATIRIIDQENNILPENEVGRLQIKGPSVTEGYYNNPDLNQEVFQDGGWFTT
Q8G985/24744795_ALod_phe-ac              ISLGKPIPGATIRIVDQENNVLPEAEIGRLQIKGKSVTKEYYHNPELNQEVFQDEGWFTT
Q9FDT8_ALod_phe-ac                       VSLGKPIPGATIRIVDQENNPLPEREIGRLQIQGNSVTKGYYNNNELNQEVFQ-EGWFTT
                                         :***:*********:***** *** *:*****:* ***: **:* :*******  *****

Q7WRJ0/31616733_ALod_phe-ac              GDLGYLHNGELVITGREKQEIIINGINYFAHEIETAIEELDGVAISYTAAFAVFDQNRET
Q8G985/24744795_ALod_phe-ac              GDLAYLLDGELFITGREKQEIIINGINYFAHEIETVIEELEGVNVSYTAAFALFDQIQET
Q9FDT8_ALod_phe-ac                       GDLGYLSKGELFITGREKQEIIINGVNYFAHELETTIEELEGVKVSYTAAFAVFDQSRET
                                         ***.** .***.*************:******:**.****:** :*******:*** :**

Q7WRJ0/31616733_ALod_phe-ac              DLLVITFNPESNN
Q8G985/24744795_ALod_phe-ac              DLLIIIFSPESEH
Q9FDT8_ALod_phe-ac                       DLLIITFSPESEQ
                                         ***:* *.***::
