CLUSTAL W multiple sequence alignment


AHF21228.1_11933_mod9_phe                SEAELLLTQSHLVDKVAFDGNMLVLDGAQGVYHEDGSNLEPLSGPNDLAYVIYTSGTTGQ
BGC0000449_AHF21228.1_11933_mod9_phe     SEAELLLTQSHLVDKVAFDGNMLVLDGAQGVYHEDGSNLEPLSGPNDLAYVIYTSGTTGQ
                                         ************************************************************

AHF21228.1_11933_mod9_phe                PKGVMLEHHGLCNLKTYFDQTLRISTSDHALLFASYSFDAACWEIFQALFCGATLYVPTS
BGC0000449_AHF21228.1_11933_mod9_phe     PKGVMLEHHGLCNLKTYFDQTLRISTSDHALLFASYSFDAACWEIFQALFCGATLYVPTS
                                         ************************************************************

AHF21228.1_11933_mod9_phe                ETILDYERFEHYMTEHQITVATLPPTYAVYLEPEHMPNLRTLFTAGSASSTELVHKWKDQ
BGC0000449_AHF21228.1_11933_mod9_phe     ETILDYERFEHYMTEHQITVATLPPTYAVYLEPEHMPNLRTLFTAGSASSTELVHKWKDQ
                                         ************************************************************

AHF21228.1_11933_mod9_phe                VAYYNGYGPTENSVATSVWSVSEDERAGQLISIGRPIPNHRVYMVDVHGHLAPIGVAGEL
BGC0000449_AHF21228.1_11933_mod9_phe     VAYYNGYGPTENSVATSVWSVSEDERAGQLISIGRPIPNHRVYMVDVHGHLAPIGVAGEL
                                         ************************************************************

AHF21228.1_11933_mod9_phe                CVSGPGLARGYLDRPEMTAEKFVPNPFAAGEAGYERMYRTGDLARWMPDGNIEYLGRIDH
BGC0000449_AHF21228.1_11933_mod9_phe     CVSGPGLARGYLDRPEMTAEKFVPNPFAAGEAGYERMYRTGDLARWMPDGNIEYLGRIDH
                                         ************************************************************

AHF21228.1_11933_mod9_phe                QVKIRGYRIELGEVEAQMLKVEDVQEVIVLAQADEQGQNQLVAYYVAEREVNAGE
BGC0000449_AHF21228.1_11933_mod9_phe     QVKIRGYRIELGEVEAQMLKVEDVQEVIVLAQADEQGQNQLVAYYVAEREVNAGE
                                         *******************************************************
