CLUSTAL W multiple sequence alignment


BGC0000426_AGZ03650.1_37_mod1_phe        SQAKILITTKEISQ---NIRFEGEHVLLYDDSIWHFPKENPNVKIQVTDLAYVIYTSGTT
P0C062_A1_1__phe                         SQARMLLTQKHLVHLIHNIQFNGQVEIFEEDTIKIREGTNLHVPSKSTDLAYVIYTSGTT
O30408_A3_4__phe                         SQAKLVVTH---AHLLHKVSSQSEVVDVDDPGSYATQTDNLPCANTPSDLAYIIYTSGTT
P09095_A1_phe                            SQTKIVLTQKSVSQLVHDVGYSGEVVVLDEEQLDARETANLHQPSKPTDLAYVIYTSGTT
                                         **:::::*     :   .:  ..:   . :         *       :****:*******

BGC0000426_AGZ03650.1_37_mod1_phe        GQPKGVMVEHKGIANLKVVWEESFGISPRDRIGFFASISFDASVWEIFMALLNGATLYVL
P0C062_A1_1__phe                         GNPKGTMLEHKGISNLKVFFENSLNVTEKDRIGQFASISFDASVWEMFMALLTGASLYII
O30408_A3_4__phe                         GKPKGVMLEHKGVANLQAVFAHHLGVTPQDRAGHFASISFDASVWDMFGPLLSGATLYVL
P09095_A1_phe                            GKPKGTMLEHKGIANLQSFFQNSFGVTEQDRIGLFASMSFDASVWEMFMALLSGASLYIL
                                         *:***.*:****::**: .: . :.:: :** * ***:*******::* .**.**:**::

BGC0000426_AGZ03650.1_37_mod1_phe        SKELLSNLCEFQNYLGENSITVMTLPPSYAQYLDPVSLFDLRLLITAGSAPSQSLVNKWN
P0C062_A1_1__phe                         LKDTINDFVKFEQYINQKEITVITLPPTYVVHLDPERILSIQTLITAGSATSPSLVNKWK
O30408_A3_4__phe                         SRDVINDFQRFAEYVRDNAITFLTLPPTYAIYLEPEQVPSLRTLITAGSASSVALVDKWK
P09095_A1_phe                            SKQTIHDFAAFEHYLSENELTIITLPPTYLTHLTPERITSLRIMITAGSASSAPLVNKWK
                                          :: : ::  * .*: :: :*.:****:*  :* *  : .:: :******.* .**:**:

BGC0000426_AGZ03650.1_37_mod1_phe        QIVTYVNAYGPTETSICATNWIAPREWCNASHIPIGTPIRNTQVYILDDNLQPVATGESG
P0C062_A1_1__phe                         EKVTYINAYGPTETTICATTWVA-TKETTGHSVPIGAPIQNTQIYIVDENLQLKSVGEAG
O30408_A3_4__phe                         EKVTYVNGYGPTESTVCATLWKA-KPDEPVETITIGKPIQNTKLYIVDDQLQLKAPGQMG
P09095_A1_phe                            DKLRYINAYGPTETSICATIWEAPSNQLSVQSVPIGKPIQNTHIYIVNEDLQLLPTGSEG
                                         : : *:*.*****:::*** * *         :.** **:**::**::::**  . *. *

BGC0000426_AGZ03650.1_37_mod1_phe        QLWVGGVGLARGYLNRPELTAEKFIDNPFIPGEKLYCTGDYARWLSDGNIEYRGRMDHQV
P0C062_A1_1__phe                         ELCIGGEGLARGYWKRPELTSQKFVDNPFVPGEKLYKTGDQARWLPDGNIEYLGRIDNQV
O30408_A3_4__phe                         ELCISGLSLARGYWNRPELTAEKFVDNPFVPGTKMYRTGDLARWLPDGTIEYLGRIDHQV
P09095_A1_phe                            ELCIGGVGLARGYWNRPDLTAEKFVDNPFVPGEKMYRTGDLAKWLTDGTIEFLGRIDHQV
                                         :* :.* .***** :**:**::**:****:** *:* *** *:**.**.**: **:*:**

BGC0000426_AGZ03650.1_37_mod1_phe        KIRGYRIELGEIEAVLQKHSGISEAAVLVKKDKLGNPFLSAYYVAEKEIPGHL
P0C062_A1_1__phe                         KIRGHRVELEEVESILLKHMYISETAVSVHKDHQEQPYLCAIFVSEKHIPLEQ
O30408_A3_4__phe                         KIRGHRVELGEVESVLLRYDTVKEAAAITHEDDRGQAYLCAYYVAEGEATPAQ
P09095_A1_phe                            KIRGHRIELGEIESVLLAHEHITEAVVIAREDQHAGQYLCAYYISQQEATPAQ
                                         ****:*:** *:*::*  :  :.*:.. .::*.    :*.* :::: . .   
