CLUSTAL W multiple sequence alignment


Q9KID8v1_A1_pip                          VAHEVYRSRFPDVPHVVALDDPELDRQPDDTAPDVELDRDSLAYAIYTSGSTGRPKAVLM
Q9KID8v2_A1_pip                          VAHEVYRSRFPDVPHVVALDDPELDRQPDDTAPDVELDRDSLAYAIYTSGSTGRPKAVLM
Q54298_A1_pip                            IAQETYRTRFPDVRDIILPDDPGLENQP-ASPPDVTTDRNSLAYAIYTSGSTGRPKAVLM
Q9ZGA6_A1_11__pip                        VAHETYRHRFSGVPHVVTPDDPDLGRQP-DTAPHLTLGRDSLAYAIYTSGSTGKPKAVLM
                                         :*:*.** **..* .::  *** * .**  :.*.:  .*:*************:******

Q9KID8v1_A1_pip                          PGVSAVNLLLWQERTMGREPASRTVQFVTPTFDYSVQEIFSALLGGTLVIPPDEVRFDPP
Q9KID8v2_A1_pip                          PGVSAVNLLLWQERTMGREPASRTVQFVTPTFDYSVQEIFSALLGGTLVIPPDEVRFDPP
Q54298_A1_pip                            PGICVVNLLLWQERTMGREPASRTAQFITATFDYSVQEIFSALLGGTLVIPPDDIRLDPA
Q9ZGA6_A1_11__pip                        PGVSAVNLLLWQERTMGREPASRTVQFVTATFDYSVQEIFSALLGGTLVIPPDEARFDPP
                                         **:..*******************.**:*.***********************: *:**.

Q9KID8v1_A1_pip                          GLARWMDEQAITRIYAPTAVLRALIEHVDPHSDQLAALRHLCQGGEALILDARLRELCRH
Q9KID8v2_A1_pip                          GLARWMDEQAITRIYAPTAVLRALIEHVDPHSDQLAALRHLCQGGEALILDARLRELCRH
Q54298_A1_pip                            RLAQWIDDSRITRIYAPTTVLRALVEHVDPHGHGLVDIASPLPGGESLVLDGKLRECALH
Q9ZGA6_A1_11__pip                        GLARWMDEQAITRIYAPTAVLRALVEHVDPHSDQLSALRHLCQGGEALALDARLRELCRH
                                          **:*:*:. ********:*****:******.. *  :     ***:* **.:*** . *

Q9KID8v1_A1_pip                          RPHLRVHNHYGPAESQLITGYTLPADPDAWPATAPIGPPIDNTRIHLLDEAMRPVPDGMP
Q9KID8v2_A1_pip                          RPHLRVHNHYGPAESQLITGYTLPADPDAWPATAPIGPPIDNTRIHLLDEAMRPVPDGMP
Q54298_A1_pip                            RPHLRVHNHYGPAESQLVTGYTLPEDVSAWPSTTPIGKPIDNTRIHLLDDALRPYPTAYA
Q9ZGA6_A1_11__pip                        RPHLRVHNHYGPAESQLITGYTLPADPDTWPAAAPIGRPIDNTRIHLLDDALRPVPDGMP
                                         *****************:****** * .:**:::*** ***********:*:** * . .

Q9KID8v1_A1_pip                          GQLCVAGVGLARGYLARPELTAERWVPGDAVGEERMYLTGDLARRAPDGDLEFLGRIDDQ
Q9KID8v2_A1_pip                          GQLCVAGVGLARGYLARPELTAERWVPGDAVGEERMYLTGDLARRAPDGDLEFLGRIDDQ
Q54298_A1_pip                            AQVCISGIGLARGYLARPELTRQRFITEGTGSEPRMYLSGDLARRLPDGNLEFLGRIDDQ
Q9ZGA6_A1_11__pip                        GQLCVAGIGLARGYLARPELTAERWVSGGATGEERMYLTGDLARRAPGGDLDFLGRIDDQ
                                         .*:*::*:************* :*::. .: .* ****:****** *.*:*:********

Q9KID8v1_A1_pip                          VKIRGIRVEPGEIESLLAEDARVTQAAVSVREDRRGEKFLAAYVVPVAGRHGDDF--
Q9KID8v2_A1_pip                          VKIRGIRVEPGEIESLLAEDARVTQAAVSVREDRRGEKFLAAYVVPVAGRHGDDF--
Q54298_A1_pip                            VKIRGIRIELGEIETALSEHAAITQAAVTVREDDRGDKRLVAYVVP----HSDAGDL
Q9ZGA6_A1_11__pip                        VKIRGIRIEPGEVENVLAEDARVAHAAVSVREDPRGEKFLAAYVVPTAGPHGDGL--
                                         *******:* **:*. *:*.* :::***:**** **:* *.*****    *.*    
