CLUSTAL W multiple sequence alignment


Q01886v2_A1_pro                          ATIALVGAGKTAALFKSADTAVQTIDITKDIPHGLSDTVVQSNTKIDDPAFGLFTSGSTG
BGC0001166_AGQ43600.1_228_mod1_pro       AKIALVGAGKTAALFESADAAIRTIDITKDIPSGLSNMVALSKTKIEDPAFGLFTSGSTG
Q01886v1_A1_pro                          ATIALVGAGKTAALFKSADTAVQTIDITKDIPHGLSDTVVQSNTKIDDPAFGLFTSGSTG
                                         *.*************:***:*::********* ***: *. *:***:*************

Q01886v2_A1_pro                          VPKCIVVTHSQICTAVQAYKDRFGVTSETRVLQFSSYTFDISIADTFTALFYGGTLCIPS
BGC0001166_AGQ43600.1_228_mod1_pro       VPKCIVVTHSQICTGVQAYRDRFGVTAETRVLQFSSYTFDISIADTFAALFYGGTLCIPS
Q01886v1_A1_pro                          VPKCIVVTHSQICTAVQAYKDRFGVTSETRVLQFSSYTFDISIADTFTALFYGGTLCIPS
                                         **************.****:******:********************:************

Q01886v2_A1_pro                          EEDRMSNLQDYMVSVRPNWAVLTPTVSRFLDPGVVKDFISTLIFTGEASREADTVPWIEA
BGC0001166_AGQ43600.1_228_mod1_pro       EEDRMSNLQEYMVSVRPNWAVLTPTVSRFLDPAVVKDFVSTLIFTGEASRESDTAPWIEA
Q01886v1_A1_pro                          EEDRMSNLQDYMVSVRPNWAVLTPTVSRFLDPGVVKDFISTLIFTGEASREADTVPWIEA
                                         *********:**********************.*****:************:**.*****

Q01886v2_A1_pro                          GVNLYNVYGPAENTLITTATRIRKGKSSNIGYGVNTRTWVTDVSGACLVPVGSIGELLIE
BGC0001166_AGQ43600.1_228_mod1_pro       GVNLYNVYGPAENTLITTATRVRKGESSNIGYGVNTRTWVTDVSSACLVPVGRIGELLIE
Q01886v1_A1_pro                          GVNLYNVYGPAENTLITTATRIRKGKSSNIGYGVNTRTWVTDVSGACLVPVGSIGELLIE
                                         *********************:***:******************.******* *******

Q01886v2_A1_pro                          SGHLADKYLNRPDRTEAAFLSDLPWIPNYEGDSVRRGRRFYRTGDLVRYCDDGSLICVGR
BGC0001166_AGQ43600.1_228_mod1_pro       SGHLADKYLNNPDKTEAAFLSDVSWIPNCDGDSVHRGRRFYRTGDLVRYCDDGSLICVGR
Q01886v1_A1_pro                          SGHLADKYLNRPDRTEAAFLSDLPWIPNYEGDSVRRGRRFYRTGDLVRYCDDGSLICVGR
                                         **********.**:********:.**** :****:*************************

Q01886v2_A1_pro                          SDTQIKLAGQRVELGDVEAHLQSDPTTSQAAVVFPRSGPLEARLIALLVTGNKDGTPHNQ
BGC0001166_AGQ43600.1_228_mod1_pro       SDTQIKLAGQRVELGDVEAHLQSDPATSQAAVFFPTSGTLKARLTALLVVRGKDGTHHNK
Q01886v1_A1_pro                          SDTQIKLAGQRVELGDVEAHLQSDPTTSQAAVVFPRSGPLEARLIALLVTGNKDGTPHNQ
                                         *************************:******.** **.*:*** ****. .**** **:

Q01886v2_A1_pro                          QSLPKPAFAQCPPD
BGC0001166_AGQ43600.1_228_mod1_pro       QHPPKPFFTQCPPD
Q01886v1_A1_pro                          QSLPKPAFAQCPPD
                                         *  *** *:*****
