CLUSTAL W multiple sequence alignment


Q9R9J0_A4_pro                            SGADVLVTCVEHTVPPSFEGSVVLLDDPLVYQGDASNLNLSYAENHLLYVIYTSGTTGKP
Q93I55_A4_pro                            SGADVLLTCAGHAIPPLFEGEVLLLDDPLLYQGRTDNLNLSCSENDLMYVIYTSGTTGQP
BGC0000400_AGM16413.1_5398_mod5_pro      SGAKLALTELAWFEVIPPEVEKVDIHDASLYQGHDENVPNESEPSNLLYIIYTSGTTGNP
AGM16413.1_5398_mod5_pro                 SGAKLALTELAWFEVIPPEVEKVDIHDASLYQGHDENVPNESEPSNLLYIIYTSGTTGNP
O30408_A1_2__pro                         SRVPLVVTQNHLRAKVTTPTETIDINTAVIGEESRAPIESLNQPHDLFYIIYTSGTTGQP
P0C063_A1_pro                            DSVRLVLTQRHLKDKFAFTKETIVIEDPSISHELTEEIDYINESEDLFYIIYTSGTTGKP
P94459_A1_pro                            CGCSHVVSQAHLPSSLEDNYIITHPEDIES-KVDGSNIKSVNNADDLLYMIYTSGTTGKP
O30980_A1_pro                            CGCSHVVSQAHFAPLLETGLNVIYMEDIQI-E-DGSCLHSVNSADDLLYMIYTSGTTGKP
P0C064/68845359_A1_2__pro                DSVRLVLTQRHLKDKFAFTKETIVIEDPSISHELTEEIDYINESEDLFYIIYTSGTTGKP
Q6YK40_A3_pro                            SSCTHLVTEKDRSVPEAATQIVTFIEEAET-EPDGSNVQTINTAEDLLYVIYTSGTTGKP
O30980_A1_7__pro                         CGCSHVVSQAHFAPLLETGLNVIYMEDIQI-E-DGSCLHSVNSADDLLYMIYTSGTTGKP
Q70JZ9_A3_pro                            SSCTHVVTEKDRSVPEAATQIVTFIEEAET-EPDGSNVQTINTAEDLLYVIYTSGTTGKP
                                               ::                 .     .     :       .*:*:********:*

Q9R9J0_A4_pro                            KGVQLEHKTMLNLLAYEREYTQLRF-DRVLQFAAMSFDVCYQEIFSTILSGGTLYIIDNE
Q93I55_A4_pro                            KGVQLEHKTMTNLLAYEQDHTQLRF-DRVLQFAAMSFDVCYQEMFSALSSGGTLFIIGNE
BGC0000400_AGM16413.1_5398_mod5_pro      KGVMLEQRNLINLLHYEQVGTSIPLPSRILQYASNSFDVCYQEMFSALLFGGCLFLIPNE
AGM16413.1_5398_mod5_pro                 KGVMLEQRNLINLLHYEQVGTSIPLPSRILQYASNSFDVCYQEMFSALLFGGCLFLIPNE
O30408_A1_2__pro                         KGVMLEHRNMANLMHFTFDQTNIAFHEKVLQYTTCSFDVCYQEIFSTLLSGGQLYLITNE
P0C063_A1_pro                            KGVMLEHKNIVNLLHFTFEKTNINFSDKVLQYTNAVLTCVTKKFFSTLLSGGQLYLIRKE
P94459_A1_pro                            KGVQFEHRNMANLLKFEYTHSGIDFEADVLQFATPSFDVCYQEIFSALLKGGTLHIVPEA
O30980_A1_pro                            KGVQFEHRNMANLLQFEFTRSGIDFENDVLQFATPAFDVCYQEIFSTLLGGGTLHIVPEA
P0C064/68845359_A1_2__pro                KGVMLEHKNIVNLLHFTFEKTNINFSDKVLQYTTCSFDVCYQEIFSTLLSGGQLYLIRKE
Q6YK40_A3_pro                            KGVLLEHRNMANLLYDQFTNSGIDFKTNVLQYASPAFDVCYQELFSALLSGGTLHIVPES
O30980_A1_7__pro                         KGVQFEHRNMANLLQFEFTRSGIDFENDVLQFATPAFDVCYQEIFSTLLGGGTLHIVPEA
Q70JZ9_A3_pro                            KGVLLEHRNMANLLYDQFTNSGIDFKTNVLQYASPAFDVCYQELFSALLSGGTLHIVPES
                                         *** :*::.: **:      : : :   :**::   :    :::**::  ** *.:: : 

Q9R9J0_A4_pro                            AKREIRELNEFVKTHRIQTAFLPTAFLKLLASEKQYFEPFAECVDHIITAGEQLIMTNTL
Q93I55_A4_pro                            AKRDIRQLNDFVRTHGIQTAFLPTAFLKLLASEKHYFEPFAECVDHIIAAGEQLIATRML
BGC0000400_AGM16413.1_5398_mod5_pro      ARKDPAQLFTWIQDNGIEVLYLPVAFLKFIFAEPEWAERFPDCVTHIITAGEQLVVTPQI
AGM16413.1_5398_mod5_pro                 ARKDPAQLFTWIQDNGIEVLYLPVAFLKFIFAEPEWAERFPDCVTHIITAGEQLVVTPQI
O30408_A1_2__pro                         LRRHVEKLFAFIQEKQISILSLPVSFLKFIFNEQDYAQSFPRCVKHIITAGEQLVVTHEL
P0C063_A1_pro                            TQRDVEQLFDLVKRENIEVLSFPVAFLKFIFNEREFINRFPTCVKHIITAGEQLVVNNEF
P94459_A1_pro                            IKRDVPQLFAFINKHQTNIVFLPTAFIKMIFSERELANSFPDGVKHLIAAGEQLMISDLF
O30980_A1_pro                            IKRDVPQLFAFIKEHQTTISVSPTAFIKMIFSEQEFANAFPHDVKHLITAGEQLIVSSLL
P0C064/68845359_A1_2__pro                TQRDVEQLFDLVKRENIEVLSFPVAFLKFIFNEREFINRFPTCVKHIITAGEQLVVNNEF
Q6YK40_A3_pro                            IKRDAAQLFSFINKHQTDIVFFPTAFAKMLFNEESYAYSFPRCVKHLITAGEQLTVSRLF
O30980_A1_7__pro                         IKRDVPQLFAFIKEHQTTISVSPTAFIKMIFSEQEFANAFPHDVKHLITAGEQLIVSSLL
Q70JZ9_A3_pro                            IKRDAAQLFSFINKHQTDIVFFPTAFAKMLFNEESYAYSFPRCVKHLITAGEQLTVSRLF
                                          ::.  :*   :. .       *.:* *::  *      *.  * *:*:*****  .  :

Q9R9J0_A4_pro                            REMMMRHQVSLHNHYGPSETHVVTMCTVDP-EIHQEMPPIGKPISNTEILILNEAGTLQP
Q93I55_A4_pro                            RDMLARHQVTLHNHYGPSETHVVTMYTVDP-DTDQELQPIGKPISNTEIFILNEAGTLQP
BGC0000400_AGM16413.1_5398_mod5_pro      QACLQRLRISLHNHYGPSETHVVTAYTMEPDDIAVGLPPIGAPIANTAIYILNDRLELQP
AGM16413.1_5398_mod5_pro                 QACLQRLRISLHNHYGPSETHVVTAYTMEPDDIAVGLPPIGAPIANTAIYILNDRLELQP
O30408_A1_2__pro                         QKYLRQHRVFLHNHYGPSETHVVTTCTMDPGQAIPELPPIGKPISNTGIYILDEGLQLKP
P0C063_A1_pro                            KRYLHEHNVHLHNHYGPSETHVVTTYTINPEAEIPELPPIGKPISNTWIYILDQEQQLQP
P94459_A1_pro                            QDVLRKRGIHLHNHYGPSETHVVSTYTIHPGDPIPELPPIGKPIGCTDLYILNHQKQLQP
O30980_A1_pro                            QDVLRQRSMYLHNHYGPSETHVVSAYTIHPGNQIPEFPPIGKPIDCTDLYILNRQKQLQP
P0C064/68845359_A1_2__pro                KRYLHEHNVHLHNHYGPSETHVVTTYTINPEAEIPELPPIGKPISNTWIYILDQEQQLQP
Q6YK40_A3_pro                            QQMLRTHGLHLHNHYGPSETHVVSTYTIQPGDDIPEYPPIGKPICHNNMYVINKNKQLQP
O30980_A1_7__pro                         QDVLRQRSMYLHNHYGPSETHVVSAYTIHPGNQIPEFPPIGKPIDCTDLYILNRQKQLQP
Q70JZ9_A3_pro                            QQVLRTHGLHLHNHYGPSETHVVSTYTIQPGDDIPEYPPIGKPICHNNMYVINKNKQLQP
                                         :  :    : *************:  *:.*        *** **  . : :::    *:*

Q9R9J0_A4_pro                            IGIVGELCIAGISLARGYHNRESLTHEKFVPHPYDANKRMYKTGDLARYLPDGNIEYAGR
Q93I55_A4_pro                            VGIVGELCISGVSLARGYHNRESLTLETFVPHPYDSNQRMYKTGDLARYLPEGNIEYAGR
BGC0000400_AGM16413.1_5398_mod5_pro      IGIAGELYVSGDCVGRGYWGRQELTDEKFIANPFAPGDLMYKTGDVARWLPDGTIEYVGR
AGM16413.1_5398_mod5_pro                 IGIAGELYVSGDCVGRGYWGRQELTDEKFIANPFAPGDLMYKTGDVARWLPDGTIEYVGR
O30408_A1_2__pro                         EGIVGELYISGANVGRGYLHQPELTAEKFLDNPYQPGERMYRTGDLALWLPDGQLEFLGR
P0C063_A1_pro                            QGIVGELYISGANVGRGYLNNQELTAEKFFADPFRPNERMYRTGDLARWLPDGNIEFLGR
P94459_A1_pro                            CGVPGELYISGASVARGYVNHDKLTSDKFSSDPFKPDVIMYRTGDLARRLEDGNIEYIGR
O30980_A1_pro                            RGVSGELYISGSSVARGYINNDKLTREKFLPDPFRSGAVMYRTGDVARIREDGSFEYIGR
P0C064/68845359_A1_2__pro                QGIVGELYISGANVGRGYLNNQELTAEKFFADPFRPNERMYRTGDLARWLPDGNIEFLGR
Q6YK40_A3_pro                            LGIAGELYISGANTGRGYVNNPALTGEKFLPDLFREGAVMYRTGDLARLREDGQIEYLGR
O30980_A1_7__pro                         RGVSGELYISGSSVARGYINNDKLTREKFLPDPFRSGAVMYRTGDVARIREDGSFEYIGR
Q70JZ9_A3_pro                            FGIAGELYISGANTGRGYVNNPALTGEKFLPDPFREGAVMYRTGDLARLREDGQIEYIGR
                                          *: *** ::*   .***  .  ** :.*  . :  .  **:***:*    :* :*: **

Q9R9J0_A4_pro                            MDHQVKIRGYRIELNEVEAALLNIEHVQEAVVLARENTEGQSDLYA-YFVAEQALPISQ-
Q93I55_A4_pro                            RDHQVKIRGYRVELGEVEAALL--KHVQEAVVLAKENTDGQSDLYA-YFTAEQSLSISQ-
BGC0000400_AGM16413.1_5398_mod5_pro      SDHQVKIRGFRIELGEVESQLLSVEFVQEATVMAREDDGGQKQLCA-YFVAERPLSAAEL
AGM16413.1_5398_mod5_pro                 SDHQVKIRGFRIELGEVESQLLSVEFVQEATVMAREDDGGQKQLCA-YFVAERPLSAAEL
O30408_A1_2__pro                         IDHQVKIRGHRIELGEIESRLLNHPAIKEAVVIDRADETGGKFLCA-YVVLQKALSDEEM
P0C063_A1_pro                            ADHQVKIRGHRIELGEIEAQLLNCKGVKEAVVIDKADDKGGKYLCA-YVVMEVEVNDSEL
P94459_A1_pro                            ADNQVKIRGYRIEPQEIEVTLMNHPDISEAAILIWQDQNGEHELCAYYCSVQK-LNTIDL
O30980_A1_pro                            ADDQVKIRGYRIEPQEIEIALMNHPEVKEAAILIRQNQGEEHELCAYYCSMHR-LDSSAL
P0C064/68845359_A1_2__pro                ADHQVKIRGHRIELGEIEAQLLNCKGVKEAVVIDKADDKGGKYLCA-YVVMEVEVNDSEL
Q6YK40_A3_pro                            IDDQAKIRGYRIEPKEVEVILANHPAVREAAVLIQKNALGENELCA-YCSVSKATDPSAL
O30980_A1_7__pro                         ADDQVKIRGYRIEPQEIEIALMNHPEVKEAAILIRQNQGEEHELCAYYCSMHR-LDSSAL
Q70JZ9_A3_pro                            IDDQAKIRGYRIEPKEVEVILANHPAVREAAVLIQKNALGENELCA-YCSVSKATDPSAL
                                          *.*.****.*:*  *:*  *     : **.::   :      * * *            
