CLUSTAL W multiple sequence alignment


EFE73312.1_2615_mod3_ser                 -AQPALVVTSRATEGAVPE-GADIPA--RVQVDGADVLAQLKALSGEPVSS---VEVLPS
CCA29203.1_542_mod1_ser                  TRAPVLLTQER----HLPSWRDRQPSAHVFAIDSASTRATLAQH----PRDNPASVIDGE
Q50E73_A6_11__ser                        -AAPVAVLTRGDV--ELP--G-SVP---RIGLDDTEIRATLATA----PGTNPGTPVTEA
Q9Z4X6_A1_ser                            -AGAMLVLTTRDTAERLP--GDGTP---RLLLDEPAAAGTTAAGAPAPPGTLPRALPAPG
                                            .  :         :*      *    . :* .   .                     

EFE73312.1_2615_mod3_ser                 HVAYVIYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFF
CCA29203.1_542_mod1_ser                  ALAYVIYTSGTTGKPKGVMSEHTGLVNRLQWMNKQYPLQATDKILQKTTYVFDVSVWELL
Q50E73_A6_11__ser                        HPAYMIYTSGSTGRPKGVVVSHGAIVNRLAWMQAEYRLDATDRVLQKTPAGFDVSVWEFF
Q9Z4X6_A1_ser                            HPAYVIYTSGSTGRPKGVVISHRAIVNRLAWMQDTYGLEPSDRVLQKTPSGFDVSVWEFF
                                           **:*****:**:****   * .:**** **:  : *: :*:::***.  *******::

EFE73312.1_2615_mod3_ser                 WPLITGAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG----
CCA29203.1_542_mod1_ser                  WANWYGACVVFAEPEGHKDVDYLLGLMERESISVVHFVPSMFGVFLDSLRARATPSHLSS
Q50E73_A6_11__ser                        WPLLEGAVLVFARPGGHRDAAYLAGLIERERITTAHFVPSMLRVFLEEPGAALCTG----
Q9Z4X6_A1_ser                            WPLVQGATLVVARPGGHTDPAYLAGTVRREGVTTLHFVPSMLDVFLREPAAAALGGA-TP
                                         *.   ** :*.*.* ** *  **   :.:* ::. ******: *** .  *    .    

EFE73312.1_2615_mod3_ser                 LRWVVCSGEALPPELRDQFFDVLEDVELHNLYGPTEASVDVTAWPCTPDEGPA-VPIGHP
CCA29203.1_542_mod1_ser                  LRYIFCSGEALPLNQVRDTHALLPAVRLHNLYGPTEASIDVLHFDCTDRALDS-VPIGKP
Q50E73_A6_11__ser                        LRRVICSGEALGTDLAVDFRAKL-PVPLHNLYGPTEAAVDVTHHAYEPATGTATVPIGRP
Q9Z4X6_A1_ser                            VRRVFCSGEALPAELRARFRAVS-DVPLHNLYGPTEAAVDVTYWPCAEDTGDGPVPIGRP
                                         :* :.******  :           * **********::**           . ****:*

EFE73312.1_2615_mod3_ser                 VWNTRTYVLDTGLHPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFGTTGE----
CCA29203.1_542_mod1_ser                  IDNTQVYVLNEALRPLPIHAIGELFLGGVGLARGYLNRPELTAQRFIPNPFAAPSERDAS
Q50E73_A6_11__ser                        IWNIRTYVLDAALRPVPPGVPGELYLAGAGLARGYHGRPALTAERFVACPFGVPGE----
Q9Z4X6_A1_ser                            VWNTRMYVLDAALRPVPAGVPGELYIAGVQLARGYLGRPALSAERFTADPHGAPGS----
                                         : * : ***: .*:*:*  . *:*::.*  ***** .** *:*:** . *......    

EFE73312.1_2615_mod3_ser                 --RMYRTGDVVRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALMSHAAVAQAAVLVRE
CCA29203.1_542_mod1_ser                  RSRLYRTGDLVRWLPDGNLEYLGRNDFQVKIRGQRVELGEIEAALARFPGVKQGLALVRT
Q50E73_A6_11__ser                        --RMYRTGDLVRWRVDGTLEFVGRADDQVKVRGFRVELGEVEGAVAAHPDVVRAVVVVRE
Q9Z4X6_A1_ser                            --RMYRTGDLARWNHDGSLDYLGRADHQVKLRGFRIELGEIEAALVRQPEIAQAAVVLRE
                                           *:*****:.**  **.*:::** * ***:** *:****:*.*:   . : :. .::* 

EFE73312.1_2615_mod3_ser                 ---DVPGDKRLVAYVVPAV-----------------PGGTVDTTT
CCA29203.1_542_mod1_ser                  PTGDPDAAQVLVGYYVSAH-----------------P---LD---
Q50E73_A6_11__ser                        ---DRPGDHRLVAYVT-----------------------------
Q9Z4X6_A1_ser                            ---DRPGDQRLVAYTVPARDADTLTGPPAEAGTHPGPGAAPDTDP
                                            *  . : **.* .                             
