CLUSTAL W multiple sequence alignment


Q50E73_A6_11__ser                        -----AAPVAVLTRGDV--ELP-G-SVP-RIGLDDTEIRATLATA----PGTNPGTPVTE
Q9Z4X6_A1_ser                            -----AGAMLVLTTRDTAERLP-GDGTP-RLLLDEPAAAGTTAAGAPAPPGTLPRALPAP
AGC65516.1_2153_mod2_ser                 AAGATAFP------ADR------------SVWVDA---------ADGTAAATPPPLPSDP
EFE73312.1_2615_mod3_ser                 -----AQPALVVTSRATEGAVPEGADIPARVQVDGADVLAQLKALSGEPVSS---VEVLP
AGC65514.1_1579_mod2_ser                 ----LGYPR-VITTADL------------ADLFDANNVL----IIDGSEDADIPDAINAP
                                              . .                        .*                .         

Q50E73_A6_11__ser                        AHPAYMIYTSGSTGRPKGVVVSHGAIVNRLAWMQAEYRLDATDRVLQKTPAGFDVSVWEF
Q9Z4X6_A1_ser                            GHPAYVIYTSGSTGRPKGVVISHRAIVNRLAWMQDTYGLEPSDRVLQKTPSGFDVSVWEF
AGC65516.1_2153_mod2_ser                 DALAYVLFTSGSTGRPKGVEIAHHSVLNRILWMQATFPIGPGDVILQKTPAGFDVSVWEL
EFE73312.1_2615_mod3_ser                 SHVAYVIYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEF
AGC65514.1_1579_mod2_ser                 DDLAYVLFTSGSTGRPKGVEIAHRGVLNRILWMQDAFPIGPDDVILQKTPITFDVSVWEL
                                            **:::*********** :.* .::**: ***  : :   * ::****  *******:

Q50E73_A6_11__ser                        FWPLLEGAVLVFARPGGHRDAAYLAGLIERERITTAHFVPSMLRVFLEE-----PGAALC
Q9Z4X6_A1_ser                            FWPLVQGATLVVARPGGHTDPAYLAGTVRREGVTTLHFVPSMLDVFLRE-----PAAAAL
AGC65516.1_2153_mod2_ser                 LWWSWTGAAVAMPPPGVERDPQALADAIAGHGVTVIHFVPAMLRAFLNAIEDGIVDAGRL
EFE73312.1_2615_mod3_ser                 FWPLITGAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLRE-----PDAAAC
AGC65514.1_1579_mod2_ser                 FWWSWTGARVVLPDPGVERDPQQLAQAIRDHSVTTMHFVPSMLASFLFSVEHGLVDIEHL
                                         :*    ** :... ** . *.  *:  :  . :*. ****:**  **             

Q50E73_A6_11__ser                        TG---LRRVICSGEALGTDLAVDFRAKL----PVPLHNLYGPTEAAVDVTHHAYEP-ATG
Q9Z4X6_A1_ser                            GGATPVRRVFCSGEALPAELRARFRAVS----DVPLHNLYGPTEAAVDVTYWPCAE-DTG
AGC65516.1_2153_mod2_ser                 AG---LRLVFASGEALDAATVRRFNHLLHARFGTMLHNLYGPTEATVDVTWQPCTPWAAD
EFE73312.1_2615_mod3_ser                 TG---LRWVVCSGEALPPELRDQFFDVLE---DVELHNLYGPTEASVDVTAWPCTP-DEG
AGC65514.1_1579_mod2_ser                 GS---LKRVFASGEALDPALVKRFNDLLFDRFGTELHNLYGPTEATVDVTWHACSP-LEN
                                          .   :: *..***** .     *         . **********:****  .      .

Q50E73_A6_11__ser                        TATVPIGRPIWNIRTYVLDAALRPVPPGVPGELYLAGAGLARGYHGRPALTAERFVACP-
Q9Z4X6_A1_ser                            DGPVPIGRPVWNTRMYVLDAALRPVPAGVPGELYIAGVQLARGYLGRPALSAERFTADP-
AGC65516.1_2153_mod2_ser                 SQIVPIGRPVANTRVLILDDAGRPVPPGGVGEIVLAGPQVARGYRGRPGLTAERFRPDPD
EFE73312.1_2615_mod3_ser                 PA-VPIGHPVWNTRTYVLDTGLHPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANP-
AGC65514.1_1579_mod2_ser                 PDIVPIGKPIANTTIRILDDRLGDMPIGIAGEIVLGGPQIACGYRNRPELTAEKFPDDP-
                                            ****:*: *    :**     :* *  *:: :.*  :* ** .** *:**:*   * 

Q50E73_A6_11__ser                        FGVPGERMYRTGDLVRWRVDGTLEFVGRADDQVKVRGFRVELGEVEGAVAAHPDVVRAVV
Q9Z4X6_A1_ser                            HGAPGSRMYRTGDLARWNHDGSLDYLGRADHQVKLRGFRIELGEIEAALVRQPEIAQAAV
AGC65516.1_2153_mod2_ser                 ADHPGARVYHTGDLGRWTADGAVAYLGRADDQVKIGGVRLELAEVETALDACPGVVRGLA
EFE73312.1_2615_mod3_ser                 FGTTGERMYRTGDVVRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALMSHAAVAQAAV
AGC65514.1_1579_mod2_ser                 -RKPGHKLYRTGDLGRFLAGGSVEYLGRIDHQVKIRGFRIECGEVETTIESHDLVERALV
                                            .* ::*:***: *:  .* : ::** *.***: *.*:* .*:* ::     : :. .

Q50E73_A6_11__ser                        VVREDRPGDHRLVAYVT-----------------------------
Q9Z4X6_A1_ser                            VLREDRPGDQRLVAYTVPARDADTLTGPPAEAGTHPGPGAAPDTDP
AGC65516.1_2153_mod2_ser                 RVAT-RDGLTELHAYVLGADD---LT-----------PQA------
EFE73312.1_2615_mod3_ser                 LVREDVPGDKRLVAYVVPAV-----------------PGGTVDTTT
AGC65514.1_1579_mod2_ser                 KAVR-VGDLDELHAFVLGEGD---LT-----------IGV------
                                                .  .* *:.                              
