CLUSTAL W multiple sequence alignment


Q84BQ4_A2_8__ser                         SAPLAVLVQGTTRSLLGEVSVPVIDLDQSQWQSLPADNLSVAELTPQHTAYVIYTSGSTG
Q84BQ5_A4_6__ser                         SAPLAVLVQGTTRSLLGEVSVPVVDLDQPHWQSLPADNLSVAELTPQHTAYVIYTSGSTG
AFZ61526.1_1614_mod2_ser                 SAPVAVLAQGGTRGLLGD--VPVVDLDRPTWQHPREDNPAVQGI----SAYVIYTSGSTG
AFZ61525.1_3733_mod4_ser                 SAPVAVLAQGATRGLLGD--APVIDLDRPTWQHQSIDNPQVQAF----SAYVIYTSGSTG
                                         ***:***.** **.***:  .**:***:. **    **  *  :    :***********

Q84BQ4_A2_8__ser                         QPKGVINEHSGVVNRLLWMQDAYQLTSSDTVLQKTPFSFDVSVWEFFWSLMTGARLVMAR
Q84BQ5_A4_6__ser                         QPKGVINEHSGVVNRLLWMQDAYQLTSSDTVLQKTPFSFDVSVWEFFWPLMTGARLVMAR
AFZ61526.1_1614_mod2_ser                 QPKGVINDHPGVVNRLLWMQDAYGLQAHDRVLQKTPFSFDVSVWEFFWPLFTGACLVMAR
AFZ61525.1_3733_mod4_ser                 QPKGVINDHPGVVNRLLWMQDAYGLQAHDRVLQKTPFSFDVSVWEFFWPLFTGACLVMAR
                                         *******:*.************* * : * ******************.*:*** *****

Q84BQ4_A2_8__ser                         PEGHKDPLYLSEIIEREHITTLHFVPSMLDVFLAHADTARCASLRQVMCSGEALPGSVVR
Q84BQ5_A4_6__ser                         PEGHKDPQYLSEIIEREQITTLHFVPSMLDVFLAHADTARCSSLRQVMCSGEALPGSVVR
AFZ61526.1_1614_mod2_ser                 PGGHKDPAYLCEVIAAEQITTLHFVPSMLDVFLAHGDVSQAAGLVRVMCSGEALPGSLVR
AFZ61525.1_3733_mod4_ser                 PGGHKDPAYLCEVIANEQITTLHFVPSMLDVFLAHGDVSQAAGLQRVMCSGEALPGSLVR
                                         * ***** **.*:*  *:*****************.*.::.:.* :***********:**

Q84BQ4_A2_8__ser                         RFKQQLPGSQLHNLYGPTEAAVDVTAWNCAGPLESTPDNTPIGKPIANTRMYILDAQQQP
Q84BQ5_A4_6__ser                         RFKQQLPASQLHNLYGPTEAAVDVTAWNCAGPLEQTPDNTPIGKPIANTRMYILDAQQQP
AFZ61526.1_1614_mod2_ser                 RFKQQLPGSELHNLYGPTEAAVDVTAWNCAGP--VTPDNTPIGKPIANTRMYVLDAQMQP
AFZ61525.1_3733_mod4_ser                 RFKQQLPGIGLYNLYGPTEAAVDVTAWNCARP--DVPDNTPIGKPIANTRMYVLDGQMQP
                                         *******.  *:****************** *   .****************:**.* **

Q84BQ4_A2_8__ser                         VPHGVVGELYIGGVQVARGYLNRPELNAERFLNDPFQSNGRMYRTGDVARYLPDGNIEYL
Q84BQ5_A4_6__ser                         VPHGVVGELYIGGVQVARGYLNRPELNAERFLNDPFQANGRMYRTGDVARYLPDGNIEYL
AFZ61526.1_1614_mod2_ser                 VPLGVVGELFIGGVQVARGYLNRPELTAERFLKDPF-TDGRLYRTGDVGRYLADGTIEYL
AFZ61525.1_3733_mod4_ser                 VPLGVVGELFIGGVQVARGYLNRPELTAERFLKDPF-TDGRLYRTGDLGRYLLDGTIEYL
                                         ** ******:****************.*****:*** ::**:*****:.*** **.****

Q84BQ4_A2_8__ser                         GRNDDQVKIRGLRIELGEIQARLTQIDGIQEVAVLAREDVPGDKRLVAYYTGA-PLEIET
Q84BQ5_A4_6__ser                         GRNDDQVKIRGLRIELGEIQARLTQIDGVQEAAVLAREDASGDKRLVAYYTGA-RLEIDV
AFZ61526.1_1614_mod2_ser                 GRNDDQVKIRGLRIELGEIQSRLTEYPPVNEAAVIAR-----DNRLIAYYTGA-FSEIDG
AFZ61525.1_3733_mod4_ser                 GRNDDQVKIRGLRIELGEIQARLLEHPQVNEAAVVAR-----DDRLVAYYTGVRATDL--
                                         ********************:** :   ::*.**:**     *.**:*****.   ::  
