CLUSTAL W multiple sequence alignment


Q5DIP4_A3_6__ser                         SGVQLLLSQSHL--KLPLAQGVQRIDLDQADAWLENHAENNPGVELNGENLAYVIYTSGS
Q5DIV7_A3_ser                            SGVELLLSQSHL--KLPLAQGVQRIDLDRGAPWFEDYSEANPDIHLDGENLAYVIYTSGS
Q5DIV7_A1_ser                            SGVQLLLSQSHL--KLPLAQGVQRIDLDQADAWLENHAENNPGVELNGENLAYVIYTSGS
Q884E4_A2_ser                            SGIGLLLTQTSLLERLPV--QVQSMCLDQDGDWLEGYSTANPVNLSHPQNLAYVIYTSGS
Q884E3_A2_ser                            SGIGLLLTQTSLLECLPVPEHVQSICLDQDGDWLAGYSTANPVNLSHPQNLAYVIYTSGS
Q5DIS7_A1_ser                            SGVRLLLTQAHLLDGLPVSAEVQPLMLAADSEWLEGFDASDPEVAVTGENLAYVIYTSGS
Q5DIP3_A1_ser                            SGVQLLLSQSHL--KLPLAQGVQRIDLDQADAWLENHAENNPGVELNGENLAYVIYTSGS
                                         **: ***:*: *   **:   ** : *     *: ..   :*      :***********

Q5DIP4_A3_6__ser                         TGKPKGAGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVV
Q5DIV7_A3_ser                            TGKPKGAGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVV
Q5DIV7_A1_ser                            TGKPKGAGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVV
Q884E4_A2_ser                            TGKPKGAGNSHRALVNRLHWMQKAYALDDSDTVLQKTPFSFDVSVWEFFWPLLTGARLAV
Q884E3_A2_ser                            TGKPKGAGNSHRALVNRLHWMQKAYALDGSDTVLQKTPFSFDVSVWEFFWPLLTGARLAV
Q5DIS7_A1_ser                            TGRPKGAGNRHSALTNRLCWMQDAYQLDGSDAVMQKTPFSFDVSVWEFFWPLMVGARLVL
Q5DIP3_A1_ser                            TGKPKGAGNRHSALSNRLCWMQQAYGLGVGDTVLQKTPFSFDVSVWEFFWPLMSGARLVV
                                         **:****** * ** *** ***.** *. .*:*:******************: ****.:

Q5DIP4_A3_6__ser                         AAPGDHRDPAKLVALINREGVDTLHFVPSMLQAFLQDEDVASCTSLKRIVCSGEALPADA
Q5DIV7_A3_ser                            AAPGDHRDPAKLVALINREGVDTLHFVPSMLQAFLQDEDVVSCTSLKRIVCSGEALPADA
Q5DIV7_A1_ser                            AAPGDHRDPAKLVELINREGVDTLHFVPSMLQAFLQDEDVASCTSLKRIVCSGEALPADA
Q884E4_A2_ser                            ALPGDHRDPERLVQTIRQHEVTTLHFVPSMLQAFMTHPQVESCNSLSRVMCSGEALPAEL
Q884E3_A2_ser                            ALPGDHRDPERLVQTIQEHQIRTLHFVPSMLQAFLTHPQVESCNSLRRVVCSGEALPAEL
Q5DIS7_A1_ser                            AQPGDHRDPSRLMDLIGRESISTLHFVPSMLQAFLQAPGVSACTSLKRIVCSGEALPVDA
Q5DIP3_A1_ser                            AAPGDHRDPAKLVKLINREGVDTLHFVPSMLQAFLQDEDVASCTSLKRIVCSGEALPADA
                                         * ******* :*:  * .. : ************:    * :*.** *::*******.: 

Q5DIP4_A3_6__ser                         QQQVFAKLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLEPV
Q5DIV7_A3_ser                            QQQVFAKLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLEPV
Q5DIV7_A1_ser                            QQQVFAKLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLEPV
Q884E4_A2_ser                            VGQVLKRLPQVGLFNLYGPTEAAIDVTHWTCTTDDVLSVPIGRPIDNLKTHILDDGLLPA
Q884E3_A2_ser                            AGQVLKRLPQASLYNLYGPTEAAIDVTHWTCTTDDVLSVPIGRPIDNLKTHILDDGLLPA
Q5DIS7_A1_ser                            QQRVLAELPGVRLYNLYGPTEAAIDVTHWDCREEGRDTVPIGRPIANLRCYVLDDALEPV
Q5DIP3_A1_ser                            QQQVFAKLPQAGLYNLYGPTEAAIDVTHWTCVEEGKDAVPIGRPIANLACYILDGNLEPV
                                           :*: .** . *:*************** *  :.  :******* **  ::**. * *.

Q5DIP4_A3_6__ser                         PVGVLGELYLAGRGLARGYHQRPGLTAERFVASPF-VAGERMYRTGDLARYRADGVIEYA
Q5DIV7_A3_ser                            PVGVLGELYLAGQGLARGYHQRPGLTAERFVASPF-VAGERMYRTGDLARYRADGVIEYA
Q5DIV7_A1_ser                            PVGVLGELYLAGQGLARGYHQRPGLTAERFVASPF-VAGERMYRTGDLARYRADGVIEYA
Q884E4_A2_ser                            AQGVAAELYLGGVGLARGYHNRAALTAERFVPDPFDGQGGRLYRTGDLARYRDEGVIEYA
Q884E3_A2_ser                            AQGVAAELYLGGVGLARGYHNRAALTAERFVPDPFDEQGGRLYRTGDLARYRNEGVIEYA
Q5DIS7_A1_ser                            PVGALGELYLAGAGLARGYHLRPALSAERFLADPF-ATGERMYRTGDLARYRADGVIEYA
Q5DIP3_A1_ser                            PVGVLGELYLAGRGLARGYHQRPGLTAERFVASPF-VAGERMYRTGDLARYRADGVIEYA
                                         . *. .****.* ******* *..*:****:..**   * *:********** :******

Q5DIP4_A3_6__ser                         GRIDHQVKLRGLRIELGEIEARLLEHPWVREAAVLAVD---GKQLVGYVV---LESEGGD
Q5DIV7_A3_ser                            GRIDHQVKLRGLRIELGEIEARLLEHPWVREAAVLAVD---GKQLVGYVV---LESESGD
Q5DIV7_A1_ser                            GRIDHQVKLRGLRIELGEIEARLLEHPRVREAAVLAVD---GRQLVGYVV---LESEGGD
Q884E4_A2_ser                            GRIDHQVKIRGLRIELGEIEACLLEHDSVQEAVVIDVDGPSGKQLAAYLV---VEQRSDH
Q884E3_A2_ser                            GRIDHQVKIRGLRIELGEIEARLHEHAGVREANVIDIDGPSGKQLVAYLVLADLDQGPDV
Q5DIS7_A1_ser                            GRIDHQVKLRGLRIELGEIETRLLEHHAVREAAVLVVD---GKQLVGYVT---LAAEPDE
Q5DIP3_A1_ser                            GRIDHQVKLRGLRIELGEIEARLLEHPRVREAAVLAVD---GRQLVGYVV---LESEGGD
                                         ********:***********: * **  *:** *: :*   *:**..*:.   :    . 
