CLUSTAL W multiple sequence alignment


Q50E73_A6_11__ser                        AAPVAVLTRGDV--ELP-G--SVPRIGLDDTEIRATLATA----PGTNPGTPVTEAHPAY
BGC0000371_BAH31686.1_1984_mod2_ser      ADPVCVVVSEDS--SLDSG--SVPRVTVSES------AQFPAEPLS----VPGSPADAAY
Q9Z4X6_A1_ser                            AGAMLVLTTRDTAERLP-G-DGTPRLLLDEPAAAGTTAAGAPAPPGTLPRALPAPGHPAY
EFE73312.1_2615_mod3_ser                 AQPALVVTSRATEGAVPEGADIPARVQVDGADVLAQLKALSGEPVSS---VEVLPSHVAY
EFE73313.1_484_mod1_ser                  AQPALVLTSESVRSVVP-GVEGLERVVVDAAQTVSALADLSGEPVSS---VEVLPSHVAY
BGC0000431_EFE73313.1_484_mod1_ser       AQPALVLTSESVRSVVP-GVEGLERVVVDAAQTVSALADLSGEPVSS---VEVLPSHVAY
                                         * .  *:.       :  *     *: :. .              .    .    .. **

Q50E73_A6_11__ser                        MIYTSGSTGRPKGVVVSHGAIVNRLAWMQAEYRLDATDRVLQKTPAGFDVSVWEFFWPLL
BGC0000371_BAH31686.1_1984_mod2_ser      MIYTSGSTGRPKGVVVTNEGVVNRLLWAQQIRPLDFSDRMLQKTPSSFDVSVPEFFWPFL
Q9Z4X6_A1_ser                            VIYTSGSTGRPKGVVISHRAIVNRLAWMQDTYGLEPSDRVLQKTPSGFDVSVWEFFWPLV
EFE73312.1_2615_mod3_ser                 VIYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFFWPLI
EFE73313.1_484_mod1_ser                  VIYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFFWPLI
BGC0000431_EFE73313.1_484_mod1_ser       VIYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFGFDVSVWEFFWPLI
                                         :*************.:.: .:**** * *    *: :**::**** .***** *****::

Q50E73_A6_11__ser                        EGAVLVFARPGGHRDAAYLAGLIERERITTAHFVPSMLRVFLEEPGAALCTG---LRRVI
BGC0000371_BAH31686.1_1984_mod2_ser      VGATLVMAEPDGHKDPGYLADVIVEHSVTRVHFVPSMLEVFLAEPKAALCTS---LEIVN
Q9Z4X6_A1_ser                            QGATLVVARPGGHTDPAYLAGTVRREGVTTLHFVPSMLDVFLREPAAAALGGATPVRRVF
EFE73312.1_2615_mod3_ser                 TGAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG---LRWVV
EFE73313.1_484_mod1_ser                  TGAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG---LRWVV
BGC0000431_EFE73313.1_484_mod1_ser       TGAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFLREPDAAACTG---LRWVV
                                          ** **.*.*.** *..**:  : .. :*  ******* *** ** **   .   :. * 

Q50E73_A6_11__ser                        CSGEALGTDLAVDFRAKL-PVPLHNLYGPTEAAVDVTHHAY---EPATGTATVPIGRPIW
BGC0000371_BAH31686.1_1984_mod2_ser      CSGEALPVHVARKVAEILPNVLVDNLYGPTEAAVDVSWQPSVQETPADAVS-VPIGEPAA
Q9Z4X6_A1_ser                            CSGEALPAELRARFRAVS-DVPLHNLYGPTEAAVDVTYWPC---AEDTGDGPVPIGRPVW
EFE73312.1_2615_mod3_ser                 CSGEALPPELRDQFFDVLEDVELHNLYGPTEASVDVTAWPC---TPDEGPA-VPIGHPVW
EFE73313.1_484_mod1_ser                  CSGEALPPELRDQFFDVLEGVELHNLYGPTEASVDVTAWPC---TPDEGPA-VPIGRPVW
BGC0000431_EFE73313.1_484_mod1_ser       CSGEALPPELRDQFFDVLEGVELHNLYGPTEASVDVTAWPC---TPDEGPA-VPIGRPVW
                                         ******  .:   .      * :.********:***:  .        . . ****.*  

Q50E73_A6_11__ser                        NIRTYVLDAALRPVPPGVPGELYLAGAGLARGYHGRPALTAERFVACPFGVPGERMYRTG
BGC0000371_BAH31686.1_1984_mod2_ser      NTGLFVLDPYLQNVPAGATGELYLAGPQLARGYHGRGGLTSERFVANPYSDGGSRMYRTG
Q9Z4X6_A1_ser                            NTRMYVLDAALRPVPAGVPGELYIAGVQLARGYLGRPALSAERFTADPHGAPGSRMYRTG
EFE73312.1_2615_mod3_ser                 NTRTYVLDTGLHPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFGTTGERMYRTG
EFE73313.1_484_mod1_ser                  NTRTYVLDTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFGTAGERMYRTG
BGC0000431_EFE73313.1_484_mod1_ser       NTRTYVLDTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAERFVANPFGTAGERMYRTG
                                         *   :***. *: ** *..*:**:**  ***** ** .*::***.* *..  *.******

Q50E73_A6_11__ser                        DLVRWRVDGTLEFVGRADDQVKVRGFRVELGEVEGAVAAHPDVVRAVVVVREDRPGDH-R
BGC0000371_BAH31686.1_1984_mod2_ser      DIVRWNGDGVLEYLGRVDEQVKVRGFRIELGEIEAQLALCPGVSASAVIVRTDGPSDRAQ
Q9Z4X6_A1_ser                            DLARWNHDGSLDYLGRADHQVKLRGFRIELGEIEAALVRQPEIAQAAVVLREDRPGDQ-R
EFE73312.1_2615_mod3_ser                 DVVRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALMSHAAVAQAAVLVREDVPGDK-R
EFE73313.1_484_mod1_ser                  DVVRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALTSHATVAQTAVLVREDVPGDK-R
BGC0000431_EFE73313.1_484_mod1_ser       DVVRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALTSHATVAQTAVLVREDVPGDK-R
                                         *:.**. ** *:::**.*.***:****:****:*. :   . :  :.*::* * *.*: :

Q50E73_A6_11__ser                        LVAYVT-----------------------------
BGC0000371_BAH31686.1_1984_mod2_ser      VVAYLV---------------------GDADDAA-
Q9Z4X6_A1_ser                            LVAYTVPARDADTLTGPPAEAGTHPGPGAAPDTDP
EFE73312.1_2615_mod3_ser                 LVAYVVPAVPGGTV-----------------DTTT
EFE73313.1_484_mod1_ser                  LVAYVIPTRSTGTV-----------------DTAA
BGC0000431_EFE73313.1_484_mod1_ser       LVAYVIPTRSTGTV-----------------DTAA
                                         :***                               
