CLUSTAL W multiple sequence alignment


Q50E73_A6_11__ser                        AAPVAVLTRGDV--ELP-G--SVPRIGL-------------DDTEIRATLATA----PGT
CBG75492_1712_mod2_ser                   SGATTVVTLSATADRLP-G-QALPSVLLLDTPDTPDTHDASDTHDGLDDLDGLGGEPPAG
Q9Z4X6_A1_ser                            AGAMLVLTTRDTAERLP-G-DGTPRLLL-------------DEPAAAGTTAAGAPAPPGT
EFE73313.1_484_mod1_ser                  AQPALVLTSESVRSVVP-GVEGLERVVV-------------DAAQTVSALADLSGEPVSS
EFE73312.1_2615_mod3_ser                 AQPALVVTSRATEGAVPEGADIPARVQV-------------DGADVLAQLKALSGEPVSS
BGC0000431_EFE73313.1_484_mod1_ser       AQPALVLTSESVRSVVP-GVEGLERVVV-------------DAAQTVSALADLSGEPVSS
BGC0000423_CBG75492.1_1712_mod2_ser      SGATTVVTLSATADRLP-G-QALPSVLLLDTPDTPDTHDASDTHDGLDDLDGLGGEPPAG
                                         : .  *:*   .   :* *      : :             *                . 

Q50E73_A6_11__ser                        NPGTPVTEAHPAYMIYTSGSTGRPKGVVVSHGAIVNRLAWMQAEYRLDATDRVLQKTPAG
CBG75492_1712_mod2_ser                   RSADPARPDDPAYLIYTSGSTGVPKGVVVTHRAIVNRLAWMQAAYGLASDDRVLQKTPSS
Q9Z4X6_A1_ser                            LPRALPAPGHPAYVIYTSGSTGRPKGVVISHRAIVNRLAWMQDTYGLEPSDRVLQKTPSG
EFE73313.1_484_mod1_ser                  ---VEVLPSHVAYVIYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFG
EFE73312.1_2615_mod3_ser                 ---VEVLPSHVAYVIYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFG
BGC0000431_EFE73313.1_484_mod1_ser       ---VEVLPSHVAYVIYTSGSTGRPKGVAVPHQGVVNRLLWMQDTFPLDGSDRVVQKTPFG
BGC0000423_CBG75492.1_1712_mod2_ser      RSADPARPDDPAYLIYTSGSTGVPKGVVVTHRAIVNRLAWMQAAYGLASDDRVLQKTPSS
                                                  . **:******** ****.:.* .:**** ***  : *   ***:**** .

Q50E73_A6_11__ser                        FDVSVWEFFWPLLEGAVLVFARPGGHRDAAYLAGLIERERITTAHFVPSMLRVFL-----
CBG75492_1712_mod2_ser                   FDVSVWEFFWPLLEGASVVLARPDGHRDPAYLAGLVREQAVTTMHFVPSMLEAFLGHDEV
Q9Z4X6_A1_ser                            FDVSVWEFFWPLVQGATLVVARPGGHTDPAYLAGTVRREGVTTLHFVPSMLDVFL-----
EFE73313.1_484_mod1_ser                  FDVSVWEFFWPLITGAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFL-----
EFE73312.1_2615_mod3_ser                 FDVSVWEFFWPLITGAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFL-----
BGC0000431_EFE73313.1_484_mod1_ser       FDVSVWEFFWPLITGAGLVVARPGGHRDAGYLTELIRHEKVTVAHFVPSMLRVFL-----
BGC0000423_CBG75492.1_1712_mod2_ser      FDVSVWEFFWPLLEGASVVLARPDGHRDPAYLAGLVREQAVTTMHFVPSMLEAFLGHDEV
                                         ************: ** :*.***.** *..**:  :..: :*. ******* .**     

Q50E73_A6_11__ser                        -EEPGAALCTG---LRRVICSGEALGTDLAVDFRAKL-PVPLHNLYGPTEAAVDVTHHAY
CBG75492_1712_mod2_ser                   TGDPAWSAS-----LRRVLSSGEALPATAASRWHALT-GVPLHNLYGPTEAAVDVTYHPY
Q9Z4X6_A1_ser                            -REPAAAALGGATPVRRVFCSGEALPAELRARFRAVS-DVPLHNLYGPTEAAVDVTYWPC
EFE73313.1_484_mod1_ser                  -REPDAAACTG---LRWVVCSGEALPPELRDQFFDVLEGVELHNLYGPTEASVDVTAWPC
EFE73312.1_2615_mod3_ser                 -REPDAAACTG---LRWVVCSGEALPPELRDQFFDVLEDVELHNLYGPTEASVDVTAWPC
BGC0000431_EFE73313.1_484_mod1_ser       -REPDAAACTG---LRWVVCSGEALPPELRDQFFDVLEGVELHNLYGPTEASVDVTAWPC
BGC0000423_CBG75492.1_1712_mod2_ser      TGDPAWSAS-----LRRVLSSGEALPATAASRWHALT-GVPLHNLYGPTEAAVDVTYHPY
                                           :*  :       :* *..***** .     :      * **********:****  . 

Q50E73_A6_11__ser                        EPAT--GTATVPIGRPIWNIRTYVLDAALRPVPPGVPGELYLAGAGLARGYHGRPALTAE
CBG75492_1712_mod2_ser                   APDEDRGTA-VPIGRPVWNTGLRVLDACLRPVPDGVPGELYLTGVQLARGYHARPALTAE
Q9Z4X6_A1_ser                            AEDT--GDGPVPIGRPVWNTRMYVLDAALRPVPAGVPGELYIAGVQLARGYLGRPALSAE
EFE73313.1_484_mod1_ser                  TPDE--GPA-VPIGRPVWNTRTYVLDTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAE
EFE73312.1_2615_mod3_ser                 TPDE--GPA-VPIGHPVWNTRTYVLDTGLHPVPVGVAGDLYLAGDQLARGYLGRPGLTAE
BGC0000431_EFE73313.1_484_mod1_ser       TPDE--GPA-VPIGRPVWNTRTYVLDTGLRPVPVGVAGDLYLAGDQLARGYLGRPGLTAE
BGC0000423_CBG75492.1_1712_mod2_ser      APDEDRGTA-VPIGRPVWNTGLRVLDACLRPVPDGVPGELYLTGVQLARGYHARPALTAE
                                               * . ****:*:**    ***: *:*** **.*:**::*  ***** .**.*:**

Q50E73_A6_11__ser                        RFVACPFGVPGERMYRTGDLVRWRVDGTLEFVGRADDQVKVRGFRVELGEVEGAVAAHPD
CBG75492_1712_mod2_ser                   RFTADPYGRPGSRMYRTGDLVRRRADGVIEYLGRTDRQVKLRGNRIELGEVEAALVRLPE
Q9Z4X6_A1_ser                            RFTADPHGAPGSRMYRTGDLARWNHDGSLDYLGRADHQVKLRGFRIELGEIEAALVRQPE
EFE73313.1_484_mod1_ser                  RFVANPFGTAGERMYRTGDVVRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALTSHAT
EFE73312.1_2615_mod3_ser                 RFVANPFGTTGERMYRTGDVVRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALMSHAA
BGC0000431_EFE73313.1_484_mod1_ser       RFVANPFGTAGERMYRTGDVVRWRTDGNLEFLGRADDQVKVRGFRIELGEIEAALTSHAT
BGC0000423_CBG75492.1_1712_mod2_ser      RFTADPYGRPGSRMYRTGDLVRRRADGVIEYLGRTDRQVKLRGNRIELGEVEAALVRLPE
                                         **.* *.* .*.*******:.* . ** ::::**:* ***:** *:****:*.*:   . 

Q50E73_A6_11__ser                        VVRAVVVVREDRPGDHRLVAYVT-----------------------------
CBG75492_1712_mod2_ser                   VAQAAVTVRDDA-----LVAYVVPA------------------PGAAAEADD
Q9Z4X6_A1_ser                            IAQAAVVLREDRPGDQRLVAYTVPARDADTLTGPPAEAGTHPGPGAAPDTDP
EFE73313.1_484_mod1_ser                  VAQTAVLVREDVPGDKRLVAYVIPTRSTGTV-----------------DTAA
EFE73312.1_2615_mod3_ser                 VAQAAVLVREDVPGDKRLVAYVVPAVPGGTV-----------------DTTT
BGC0000431_EFE73313.1_484_mod1_ser       VAQTAVLVREDVPGDKRLVAYVIPTRSTGTV-----------------DTAA
BGC0000423_CBG75492.1_1712_mod2_ser      VAQAAVTVRDDA-----LVAYVVPA------------------PGAAAEADD
                                         :.::.* :*:*      ****.                              
