CLUSTAL W multiple sequence alignment


O85168_A2_ser                            SAPRAVLTSHELLADLPDLGVPALVLDGRDDSALLKKQPTGNPDAKALDLQPNHLAYVLY
Q2N3S9_A1_9__ser                         AGVAVLLTQSSFSGVLAGFTGTRLCLDT--EASRLSSYSADSP---RVEVRPEHLAYVIY
Q50E73_A6_11__ser                        AAPVAVLTRGDVE--LPG-SVPRIGLDDTEIRATLATAPGTNP---GTPVTEAHPAYMIY
BGC0000398_AFH75330.1_2671_mod3_ser      SAPLAVLAQGATLGLLGDPDVPVVDL----EQSVWSRQPRINP--RIAGLTPRHLAYVIY
BGC0000398_AFH75329.1_3793_mod4_ser      SAPLAVLVQGATRHLAQASGLALLDL----DQPQWAGQSRDNP--QLPHLTPRHLAYVIY
O85168_A1_ser                            SSPQAVLTTRDLSDNLPASDLPVLVLDGHNDRAQLARQQSVNPDAKALGLQPNHLAYVLY
Q84BQ5_A4_6__ser                         SAPLAVLVQGTTRSLLGEVSVPVVDL----DQPHWQSLPADNL--SVAELTPQHTAYVIY
YP_631961.1_1173_mod1_ser                TGASVLLTHEKWKTVLPPSAARVVCLDS--AAGEVAKQPVTKP---AVQVGPQALAYVIF
                                         :.  .:*.               : *               .       :     **:::

O85168_A2_ser                            TSGSTGTPKGVMNEHLGVVNRLLWARDAYQVNSQDRVLQKTPFGFDVSVWEFFLPLLTGA
Q2N3S9_A1_9__ser                         TSGSTGMPKGCMLSHRAICNRLHWMQEAYALTPLDRVLQKTPFTFDVSVWEFFWPLITGA
Q50E73_A6_11__ser                        TSGSTGRPKGVVVSHGAIVNRLAWMQAEYRLDATDRVLQKTPAGFDVSVWEFFWPLLEGA
BGC0000398_AFH75330.1_2671_mod3_ser      TSGSTGQPKGAMNEHRAVVNRLLWMQEQYRLTSCDAVLQKTPFSFDVSVWEFFWPLFTGA
BGC0000398_AFH75329.1_3793_mod4_ser      TSGSTGQPKGAMNEHRAVVNRLLWMQEQYRLDVDDAVLQKTPFSFDVSVWEFFWPLFTGA
O85168_A1_ser                            TSGSTGTPKGVMNEHLGVVNRLLWARDAYQVNSQDRVLQKTPCGFDLSVWEFFLPLLTGA
Q84BQ5_A4_6__ser                         TSGSTGQPKGVINEHSGVVNRLLWMQDAYQLTSSDTVLQKTPFSFDVSVWEFFWPLMTGA
YP_631961.1_1173_mod1_ser                TSGSTGRPKGAMNAHEGVVNRLKWMQEEYGLSGTDVVLQKTPFSFDVSVWEFFWPLLAGA
                                         ****** *** :  * .: *** * :  * :   * ******  **:****** **: **

O85168_A2_ser                            ELVMARPSGHQDPDYLAQVISDAGITLLHFVPSMLDVFLEHRSTRDFPQLRRVLCSGEAL
Q2N3S9_A1_9__ser                         RIVLAAPGAERDPAALAGLIQEHGVTACHFVPSMLRLFLDEPRAAGCASLRHVFFSGEAL
Q50E73_A6_11__ser                        VLVFARPGGHRDAAYLAGLIERERITTAHFVPSMLRVFLEEPGAALCTGLRRVICSGEAL
BGC0000398_AFH75330.1_2671_mod3_ser      RLVMARPEGHKDPAYLRQVIARENITTLHFVPSMLDVFLAYGETRECASLRQVMCSGEAL
BGC0000398_AFH75329.1_3793_mod4_ser      RLVMARPEGHKDPAYLRQLIREQGISTLHFVPSMLDVFLAHDATPDDLGLRQVMCSGEAL
O85168_A1_ser                            ELVMAPPGGHQDPDYLAQVMSDAGITLLHFVPSMLDVFLEHRSTRDFPQLRRVLCSGEAL
Q84BQ5_A4_6__ser                         RLVMARPEGHKDPQYLSEIIEREQITTLHFVPSMLDVFLAHADTARCSSLRQVMCSGEAL
YP_631961.1_1173_mod1_ser                KLVVARPGGHQEPAYLVKLMKAEGVTTVHFVPSMLRAFVEEPGLEGLGSLRRVVCSGEAL
                                          :*.* * ..::.  *  ::    ::  *******  *:          **:*. *****

O85168_A2_ser                            PRALQRRFEQHLKG-VELHNLYGPTEAAIDVTAWECR-PTDPG-DSVPIGRPIANIQMHV
Q2N3S9_A1_9__ser                         PYPLMERALSTFSA--QLHNLYGPTEAAVDVSFWKC--NLRDD-RKVPIGRPIANIRLYI
Q50E73_A6_11__ser                        GTDLAVDFRAKLP--VPLHNLYGPTEAAVDVTHHAYE-PATGT-ATVPIGRPIWNIRTYV
BGC0000398_AFH75330.1_2671_mod3_ser      PGSLVRRFKQQLPN-VGLHNLYGPTEAAVDVTAWDCTGPLETTPDNTPIGKPIANTRLYL
BGC0000398_AFH75329.1_3793_mod4_ser      PGSLVRRFKQQLPN-VALHNLYGPTEAAVDVTAWDCTGPLDATPDNTPIGKPIANTRLYL
O85168_A1_ser                            PRALQRRFEQQLKG-VELHNLYGPTEAAIDVTAWECR-PTDPG-DSVPIGRPIANIQMHV
Q84BQ5_A4_6__ser                         PGSVVRRFKQQLPA-SQLHNLYGPTEAAVDVTAWNCAGPLEQTPDNTPIGKPIANTRMYI
YP_631961.1_1173_mod1_ser                SAELVKKAYARLPAPVRVHNLYGPTEAAVDVTYWPC--PRGEDFHRVPIGRPVANTVLYV
                                            :       :     :**********:**:              .***:*: *   ::

O85168_A2_ser                            LDALGQLQPMGVAGELHIGGIGVARGYLNQPQLSAERFIADPFSNDPQARLYKTGDVGRW
Q2N3S9_A1_9__ser                         LDEQQRPVRPDQTGELYIAGVGLARGYLNRPELTAERFVRDPFDPSPGARMYKTGDRAAW
Q50E73_A6_11__ser                        LDAALRPVPPGVPGELYLAGAGLARGYHGRPALTAERFVACPFGV-PGERMYRTGDLVRW
BGC0000398_AFH75330.1_2671_mod3_ser      LDAQLQPVPLGVVGELFIAGVQVARGYLNREQLTAERFVDDPFSAEPDARMYRTGDLGRY
BGC0000398_AFH75329.1_3793_mod4_ser      LDAQLQPVPLGVVGELFIAGVQVARGYLNREQLTAERFVDDPFSAEPGARMYRTGDLGRY
O85168_A1_ser                            LDALGQLQPMGVAGELHIGGIGVARGYLNQPQLSAERFIADPFSNDPQARLYKTGDVGRW
Q84BQ5_A4_6__ser                         LDAQQQPVPHGVVGELYIGGVQVARGYLNRPELNAERFLNDPFQA--NGRMYRTGDVARY
YP_631961.1_1173_mod1_ser                LDVHGQPAPVGIPGELHIGGVQVGRGYWQRPQLTAERFIPDAFSGIPGARLYRTGDVARW
                                         **   :    .  ***.:.*  :.***  :  *.****:  .*      *:*:***   :

O85168_A2_ser                            LANGALEYLGRNDFQVKIRGLRIEIGEIEAALAKHPAVHEAVVTAREDIPGDKRLVAYYT
Q2N3S9_A1_9__ser                         LPDGNIDFLGRMDGQIKLRGLRIELGEIEAALLGHEAVREAAVAVRDADSGDPRLVAYVV
Q50E73_A6_11__ser                        RVDGTLEFVGRADDQVKVRGFRVELGEVEGAVAAHPDVVRAVVVVREDRPGDHRLVAYVT
BGC0000398_AFH75330.1_2671_mod3_ser      LADGNIEYLGRNDDQVKIRGLRIELGEIQARLTQLEGIKEAVVLAREDVPGDKRLVAYYT
BGC0000398_AFH75329.1_3793_mod4_ser      LTDGNIEYLGRNDDQVKIRGLRIELGEIQARLTQLEGIKEAVVLAREDVPGDKRLVAYYT
O85168_A1_ser                            LANGALEYLGRNDFQVKIRGLRIEIGEIEAALAKHPAVHEAVVTAREDIPGDKRLVAYYT
Q84BQ5_A4_6__ser                         LPDGNIEYLGRNDDQVKIRGLRIELGEIQARLTQIDGVQEAAVLAREDASGDKRLVAYYT
YP_631961.1_1173_mod1_ser                LPDGTLEYLGRADFQVKLRGFRIELGEIEAALAADPAVHDSVVLAREDSTGDQRLVAYVV
                                           :* ::::** * *:*:**:*:*:**::. :     :  :.* .*:  .** ***** .

O85168_A2_ser                            QTA---------
Q2N3S9_A1_9__ser                         LR----------
Q50E73_A6_11__ser                        ------------
BGC0000398_AFH75330.1_2671_mod3_ser      SDAGHGKLPVEQ
BGC0000398_AFH75329.1_3793_mod4_ser      SDAGHGKLPVEQ
O85168_A1_ser                            QSA---------
Q84BQ5_A4_6__ser                         G----ARLEIDV
YP_631961.1_1173_mod1_ser                ------------
                                                     
