CLUSTAL W multiple sequence alignment


BGC0000398_AFH75329.1_3793_mod4_ser      SAPLAVLVQGATRHLAQASGLALLDLD----QPQWAGQSRDNP--QLPHLTPRHLAYVIY
Q83VS0_A6_16__ser                        SSPQAVLTTRDLSDNLPASDLPVLVLDGHDDRAQLARQQSVNPDAKALGLQPNHLAYVLY
BGC0001149_CDF96614.1_480_mod1_ser       SAPSALLTTRVLLSSLPAVTMPVLCLD--SDLEQLSRQPQHNPDPVAQGLTPRHLAYVIY
BGC0000398_AFH75330.1_2671_mod3_ser      SAPLAVLAQGATLGLLGDPDVPVVDLE----QSVWSRQPRINP--RIAGLTPRHLAYVIY
O85168_A1_ser                            SSPQAVLTTRDLSDNLPASDLPVLVLDGHNDRAQLARQQSVNPDAKALGLQPNHLAYVLY
Q84BQ5_A4_6__ser                         SAPLAVLVQGTTRSLLGEVSVPVVDLD----QPHWQSLPADNL--SVAELTPQHTAYVIY
O85168_A2_ser                            SAPRAVLTSHELLADLPDLGVPALVLDGRDDSALLKKQPTGNPDAKALDLQPNHLAYVLY
                                         *:* *:*.            :. : *:              *       * *.* ***:*

BGC0000398_AFH75329.1_3793_mod4_ser      TSGSTGQPKGAMNEHRAVVNRLLWMQEQYRLDVDDAVLQKTPFSFDVSVWEFFWPLFTGA
Q83VS0_A6_16__ser                        TSGSTGTPKGVMNEHLGVVNRLLWARDAYQVNSQDRVLQKTPFGFDVSVWEFFLPLLTGA
BGC0001149_CDF96614.1_480_mod1_ser       TSGSTGLPKGVMNQHDGVVNRLLWARDAYQVDEHSRVLQKTPFSFDVSVWEFFLPLLSGA
BGC0000398_AFH75330.1_2671_mod3_ser      TSGSTGQPKGAMNEHRAVVNRLLWMQEQYRLTSCDAVLQKTPFSFDVSVWEFFWPLFTGA
O85168_A1_ser                            TSGSTGTPKGVMNEHLGVVNRLLWARDAYQVNSQDRVLQKTPCGFDLSVWEFFLPLLTGA
Q84BQ5_A4_6__ser                         TSGSTGQPKGVINEHSGVVNRLLWMQDAYQLTSSDTVLQKTPFSFDVSVWEFFWPLMTGA
O85168_A2_ser                            TSGSTGTPKGVMNEHLGVVNRLLWARDAYQVNSQDRVLQKTPFGFDVSVWEFFLPLLTGA
                                         ****** ***.:*:* .******* :: *::   . ****** .**:****** **::**

BGC0000398_AFH75329.1_3793_mod4_ser      RLVMARPEGHKDPAYLRQLIREQGISTLHFVPSMLDVFLAHDATPDDLGLRQVMCSGEAL
Q83VS0_A6_16__ser                        ELVMARPGGHQDPDYLAQVMSDAGITLLHFVPSMLDVFLEHRSTRDFPQLRRVLCSGEAL
BGC0001149_CDF96614.1_480_mod1_ser       QLVVAAPGGHQDPRYLLDIMASAGITLLHFVPSMLQVFLDQVTAQPLPALKKVLCSGEAL
BGC0000398_AFH75330.1_2671_mod3_ser      RLVMARPEGHKDPAYLRQVIARENITTLHFVPSMLDVFLAYGETRECASLRQVMCSGEAL
O85168_A1_ser                            ELVMAPPGGHQDPDYLAQVMSDAGITLLHFVPSMLDVFLEHRSTRDFPQLRRVLCSGEAL
Q84BQ5_A4_6__ser                         RLVMARPEGHKDPQYLSEIIEREQITTLHFVPSMLDVFLAHADTARCSSLRQVMCSGEAL
O85168_A2_ser                            ELVMARPSGHQDPDYLAQVISDAGITLLHFVPSMLDVFLEHRSTRDFPQLRRVLCSGEAL
                                         .**:* * **:** ** :::    *: ********:***    :     *::*:******

BGC0000398_AFH75329.1_3793_mod4_ser      PGSLVRRFKQQLPNVALHNLYGPTEAAVDVTAWDCTGPLDATPDNTPIGKPIANTRLYLL
Q83VS0_A6_16__ser                        PRALQRRFEQQLKGVELHNLYGPTEAAIDVTAWECR-P-TDPGDSVPIGRPIANIQMHVL
BGC0001149_CDF96614.1_480_mod1_ser       PYALQTRFFERLPGVQLHNLYGPTEAAIDVTAWQCR-PDVHPG-IVPIGRPIANTQLYIL
BGC0000398_AFH75330.1_2671_mod3_ser      PGSLVRRFKQQLPNVGLHNLYGPTEAAVDVTAWDCTGPLETTPDNTPIGKPIANTRLYLL
O85168_A1_ser                            PRALQRRFEQQLKGVELHNLYGPTEAAIDVTAWECR-P-TDPGDSVPIGRPIANIQMHVL
Q84BQ5_A4_6__ser                         PGSVVRRFKQQLPASQLHNLYGPTEAAVDVTAWNCAGPLEQTPDNTPIGKPIANTRMYIL
O85168_A2_ser                            PRALQRRFEQHLKGVELHNLYGPTEAAIDVTAWECR-P-TDPGDSVPIGRPIANIQMHVL
                                         * ::  ** ::*    ***********:*****:*  *   .   .***:**** ::::*

BGC0000398_AFH75329.1_3793_mod4_ser      DAQLQPVPLGVVGELFIAGVQVARGYLNREQLTAERFVDDPFSAEPGARMYRTGDLGRYL
Q83VS0_A6_16__ser                        DALGQLQPLGVAGELHIGGIGVARGYLNQPDLSAERFIADPFSEDRQARLYKTGDVGRWL
BGC0001149_CDF96614.1_480_mod1_ser       DANLQLLPPGIAGELHIGGIGVARGYLNREQLTAERFIRDPFQADPQARLYKTGDLGRWL
BGC0000398_AFH75330.1_2671_mod3_ser      DAQLQPVPLGVVGELFIAGVQVARGYLNREQLTAERFVDDPFSAEPDARMYRTGDLGRYL
O85168_A1_ser                            DALGQLQPMGVAGELHIGGIGVARGYLNQPQLSAERFIADPFSNDPQARLYKTGDVGRWL
Q84BQ5_A4_6__ser                         DAQQQPVPHGVVGELYIGGVQVARGYLNRPELNAERFLNDPFQA--NGRMYRTGDVARYL
O85168_A2_ser                            DALGQLQPMGVAGELHIGGIGVARGYLNQPQLSAERFIADPFSNDPQARLYKTGDVGRWL
                                         **  *  * *:.***.*.*: *******: :*.****: ***.    .*:*:***:.*:*

BGC0000398_AFH75329.1_3793_mod4_ser      TDGNIEYLGRNDDQVKIRGLRIELGEIQARLTQLEGIKEAVVLAREDVPGDKRLVAYYTS
Q83VS0_A6_16__ser                        ANGALEYLGRNDFQVKIRGLRIEIGEIEAALAKHPAVHEAVVTAREDIPGDKRLVAYYTQ
BGC0001149_CDF96614.1_480_mod1_ser       PDGSIEYLGRNDFQVKIRGLRIELGEIEARLAACAGVKEVVVIARQETEGDACLSAYLVG
BGC0000398_AFH75330.1_2671_mod3_ser      ADGNIEYLGRNDDQVKIRGLRIELGEIQARLTQLEGIKEAVVLAREDVPGDKRLVAYYTS
O85168_A1_ser                            ANGALEYLGRNDFQVKIRGLRIEIGEIEAALAKHPAVHEAVVTAREDIPGDKRLVAYYTQ
Q84BQ5_A4_6__ser                         PDGNIEYLGRNDDQVKIRGLRIELGEIQARLTQIDGVQEAAVLAREDASGDKRLVAYYTG
O85168_A2_ser                            ANGALEYLGRNDFQVKIRGLRIEIGEIEAALAKHPAVHEAVVTAREDIPGDKRLVAYYTQ
                                         .:* :******* **********:***:* *:   .::*..* **::  **  * ** . 

BGC0000398_AFH75329.1_3793_mod4_ser      DAGHGKLPVEQ
Q83VS0_A6_16__ser                        SA---------
BGC0001149_CDF96614.1_480_mod1_ser       EPG-CVLSPQA
BGC0000398_AFH75330.1_2671_mod3_ser      DAGHGKLPVEQ
O85168_A1_ser                            SA---------
Q84BQ5_A4_6__ser                         ----ARLEIDV
O85168_A2_ser                            TA---------
                                                    
