CLUSTAL W multiple sequence alignment


BGC0000439_AHH53506.1_4093_mod4_thr      AEPVLLVATAETVTPLTGSL-PERKVLLVDDPDVRARIAATPGHPLGEHERPAPPSPAHP
AHH53506.1_4093_mod4_thr                 AEPVLLVATAETVTPLTGSL-PERKVLLVDDPDVRARIAATPGHPLGEHERPAPPSPAHP
AEF33078.1_463_mod1_thr                  AAPALVLTDTDGADRVRGAVHP----LLLDDPALAAELTGLPGTDPTAAERPAAAGPDSL
                                         * *.*::: :: .  : *:: *    **:*** : *.::. **      ****...*   

BGC0000439_AHH53506.1_4093_mod4_thr      AYAIYTSGSTGMPKGVVVTHDNVTRLFAAAAELFDFGPADVWSLFHSSAFDFSVWELWGA
AHH53506.1_4093_mod4_thr                 AYAIYTSGSTGMPKGVVVTHDNVTRLFAAAAELFDFGPADVWSLFHSSAFDFSVWELWGA
AEF33078.1_463_mod1_thr                  AYVIYTSGSTGRPKGVAVTHHNVLRLFRQTDHWFGFGADDVWTLFHSYAFDFSVWEIWGP
                                         **.******** ****.***.** ***  : . *.**. ***:**** ********:**.

BGC0000439_AHH53506.1_4093_mod4_thr      LLHGGRAVVVPFEVSRSPEDLLRLLTEHRVTVLNQTPSAFYQLAQALAER---QAEFAPR
AHH53506.1_4093_mod4_thr                 LLHGGRAVVVPFEVSRSPEDLLRLLTEHRVTVLNQTPSAFYQLAQALAER---QAEFAPR
AEF33078.1_463_mod1_thr                  LLHGGRLVVVPFDTSRSPADFLRLLVRERVTVLNQTPSAFYQLIAAERERPDLAGRLTLR
                                         ****** *****:.**** *:****...***************  *  **    ..:: *

BGC0000439_AHH53506.1_4093_mod4_thr      YVIFGGEALDPSRLAAWF-DHGSAGTELVNMYGITETTVHVTFRKLDERSTRRA-NSVIG
AHH53506.1_4093_mod4_thr                 YVIFGGEALDPSRLAAWF-DHGSAGTELVNMYGITETTVHVTFRKLDERSTRRA-NSVIG
AEF33078.1_463_mod1_thr                  HVVFGGEALETHRLEDWYARHGDDAPRLVNMYGITETTVHVTYAALDRETVRAARGSVIG
                                         :*:******:. **  *:  **. ...***************:  **..:.* * .****

BGC0000439_AHH53506.1_4093_mod4_thr      APLADLGGYVLDELLRPVPTGVPGELYVSGAGLARGYLGRAGLTATRFVANPFSPSGQRL
AHH53506.1_4093_mod4_thr                 APLADLGGYVLDELLRPVPTGVPGELYVSGAGLARGYLGRAGLTATRFVANPFSPSGQRL
AEF33078.1_463_mod1_thr                  EPIPDLDVYVLDGELRPVPEGATGELYVAGPGLARGYLGRPGLTAERFVADPFGAPGGRM
                                          *:.**. ****  ***** *..*****:*.*********.**** ****:**...* *:

BGC0000439_AHH53506.1_4093_mod4_thr      YRTGDLVRSTVDGELEYLGRADRQVQLRGFRVELGEIEARLVDHTAVSQAAVVAREDTPA
AHH53506.1_4093_mod4_thr                 YRTGDLVRSTVDGELEYLGRADRQVQLRGFRVELGEIEARLVDHTAVSQAAVVAREDTPA
AEF33078.1_463_mod1_thr                  YRTGDLACVLDDGSLGYLGRADSQVKIRGFRIELGEIEAALERHPGVERAAVVVREDRPG
                                         ******.    **.* ****** **::****:******* *  *..*.:****.*** *.

BGC0000439_AHH53506.1_4093_mod4_thr      DVRLVAYLVPATGARPSAAE
AHH53506.1_4093_mod4_thr                 DVRLVAYLVPATGARPSAAE
AEF33078.1_463_mod1_thr                  DQRLVAYAVPAAGTAPDTTG
                                         * ***** ***:*: *.:: 
