CLUSTAL W multiple sequence alignment


O87704_A2_4__thr                         SGARILLTEHGHNKPADYHGQILYLND----AENELISPDLKAQETLADQP---AYVIYT
BGC0000400_AGM16412.1_3015_mod3_thr      SGAQVLLLPHDLRDKVGFDGTVVMLDDEQSYVEDSSNPA-------TASKPSDLAYVIYT
AGM16412.1_3015_mod3_thr                 SGAQVLLLPHDLRDKVGFDGTVVMLDDEQSYVEDSSNPA-------TASKPSDLAYVIYT
P39846_A2_thr                            SGAKLLLTERGLNKPADYTGHILYIDE----CENNSIPADVNIEEIVTDQP---AYVIYT
                                         ***::**  :. .. ..: * :: :::     *:.  ..        :.:*   ******

O87704_A2_4__thr                         SGTTGQPKGVVVEHRNVISLLKHQDLPFDFGSEDVWTLFHSYCFDFSVWEMFGALLNGST
BGC0000400_AGM16412.1_3015_mod3_thr      SGTTGKPKGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGR
AGM16412.1_3015_mod3_thr                 SGTTGKPKGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGR
P39846_A2_thr                            SGTTGQPKGVIVEHRNVISLLKHQNLPFEFNHEDVWTLFHSYCFDFSVWEMFGALLNGST
                                         *****:***.::**:**: ** :..  *:*.  *.******:*********:**** *. 

O87704_A2_4__thr                         LVVVSRETARDPNAFRLLLKNEGVTVLNQTPTAFYGLIHEE-ENHTDRLHVRYVIFGGEA
BGC0000400_AGM16412.1_3015_mod3_thr      LVVVPQLTAKNPAQFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEA
AGM16412.1_3015_mod3_thr                 LVVVPQLTAKNPAQFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEA
P39846_A2_thr                            LVVVSKETARDPQAFRLLLKKERVTVLNQTPTAFYGLMLED-QNHTDHLNIRYVIFGGEA
                                         ****.: **::*  *  **::: **:****** ** *: *   :  :.*::* *******

O87704_A2_4__thr                         LQPGMLVTWNEKYPDTDLINMYGITETTVHVTYKKLSSADIEKNKSNIGKPLATLQAYVM
BGC0000400_AGM16412.1_3015_mod3_thr      LNPQLLKDWKTKYPHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKVYVL
AGM16412.1_3015_mod3_thr                 LNPQLLKDWKTKYPHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKVYVL
P39846_A2_thr                            LQPGLLQSWNEKYPHTDLINMYGITETTVHVTFKKLSAADIAKNKSNIGRPLSTLQAHVM
                                         *:* :*  *: ***.*:***************:*::: .:* : *****:*:.**:.:*:

O87704_A2_4__thr                         DAHMNLQPTGVPGELYIGGEGVARGYLNRDDLTAARFVPNPYLPGDRLYRTGDLAKRLAS
BGC0000400_AGM16412.1_3015_mod3_thr      DANRQCVPVGVAGEMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARWLPD
AGM16412.1_3015_mod3_thr                 DANRQCVPVGVAGEMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARWLPD
P39846_A2_thr                            DAHMNLQPTGVPGELYIGGEGVARGYLNRDELTADRFVSNPYLPGDRLYRTGDLAKRLSN
                                         **: :  *.**.**:*:.*:*:*****:* :*** :** .*: .*.*:*******: *..

O87704_A2_4__thr                         GDLEYMGRIDDQVKVRGHRIELGEIQASLLQLPIIKEAAVITRDDEQGQSAVYAYLVAED
BGC0000400_AGM16412.1_3015_mod3_thr      GNIEYLGRIDHQVKIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCAYFVAAR
AGM16412.1_3015_mod3_thr                 GNIEYLGRIDHQVKIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCAYFVAAR
P39846_A2_thr                            GELEYLGRIDEQVKVRGHRIELGEIQAALLQYPMIKEAAVITRADEQGQTAIYAYMVIKD
                                         *::**:****.***:**:******::* * :   ::** **:* * :*:. : **:*   

O87704_A2_4__thr                         GQVVNEAD
BGC0000400_AGM16412.1_3015_mod3_thr      ELTVGE--
AGM16412.1_3015_mod3_thr                 ELTVGE--
P39846_A2_thr                            QQAANISD
                                           ...   
