CLUSTAL W multiple sequence alignment


AEI70245.1_1510_mod2_thr                 ARPVYVVTSEAGAQGLPDTGSLPRLVLDAPDTAERLRAYSPDNPGDGDRRGPLSPLSPAY
AEA30272.1_474_mod1_thr                  AAPVLLLTDSASAAGLPDPGTAAPLLLDDPGIVAELARQADGDLTEAERTAALDPRHAAY
AEF33078.1_463_mod1_thr                  AAPALVLTDTDGADRV--RGAVHPLLLDDPALAAELTGLPGTDPTAAERPAAAGPDSLAY
                                         * *. ::*.  .*  :   *:   *:** *  . .*   .  :   .:* .. .*   **

AEI70245.1_1510_mod2_thr                 MIYTSGSTGKPKGVVIPHQNVIRLFASTQHWFGFGSEDVWTLFHSYAFDFSVWEIWGPLL
AEA30272.1_474_mod1_thr                  MIYTSGSTGRPKGVVVPHRNVVRLFTATEPWFGFDADDVWTLFHSYAFDFSVWEIWGPLL
AEF33078.1_463_mod1_thr                  VIYTSGSTGRPKGVAVTHHNVLRLFRQTDHWFGFGADDVWTLFHSYAFDFSVWEIWGPLL
                                         :********:****.:.*:**:***  *: ****.::***********************

AEI70245.1_1510_mod2_thr                 HGSRLVVVSHTVSRSPAEFLQLLVRERVTVLNQTPSAFYQLMQADREHPSLGGELALRYV
AEA30272.1_474_mod1_thr                  HGGTLVVVPHEVNRSPEEFLRLLARERVTVLNQTPSAFYQLMRADRETSDAGALPALRRV
AEF33078.1_463_mod1_thr                  HGGRLVVVPFDTSRSPADFLRLLVRERVTVLNQTPSAFYQLIAAERERPDLAGRLTLRHV
                                         **. ****.. ..*** :**:**.*****************: *:** .. ..  :** *

AEI70245.1_1510_mod2_thr                 VFGGEALELGRLEEWYARHPDDAPRLINMYGITETTVHVSYKELDRSSAASGAGSLIGEA
AEA30272.1_474_mod1_thr                  VFGGEALDLWRLEPWYDSHPDDAPVLVNMYGITETTVHVSHVALDATSVGAERGSVIGTP
AEF33078.1_463_mod1_thr                  VFGGEALETHRLEDWYARHGDDAPRLVNMYGITETTVHVTYAALDRETVRAARGSVIGEP
                                         *******:  *** **  * **** *:************::  **  :. :  **:** .

AEI70245.1_1510_mod2_thr                 IPDLRVYVLDEALQPVPPGVAGEMYVAGAGLARGYWGRPGLTAERFVADPFGAPGSRMYR
AEA30272.1_474_mod1_thr                  IPDLGVHLLDDALRPVPSGVAAEMYVSGEGLARGYHGRPDLTSHRFVADPFGAPGSRMYR
AEF33078.1_463_mod1_thr                  IPDLDVYVLDGELRPVPEGATGELYVAGPGLARGYLGRPGLTAERFVADPFGAPGGRMYR
                                         **** *::**  *:*** *.:.*:**:* ****** ***.**:.***********.****

AEI70245.1_1510_mod2_thr                 TGDLARRFADGSLDYLGRADHQVKIRGFRIEPGEIEAVLAKHPGVAQVAVVVREDQPGDK
AEA30272.1_474_mod1_thr                  TGDVARRTADGELEFVGRADHQVKIRGFRIELGEIEAVVEGLAEVAQAAVVVREDQPGDK
AEF33078.1_463_mod1_thr                  TGDLACVLDDGSLGYLGRADSQVKIRGFRIELGEIEAALERHPGVERAAVVVREDRPGDQ
                                         ***:*    **.* ::**** ********** *****.:   . * :.*******:***:

AEI70245.1_1510_mod2_thr                 RLVAYVVP-----APDSLAEPAE
AEA30272.1_474_mod1_thr                  RLVAYVTPVGGREGVDLAA----
AEF33078.1_463_mod1_thr                  RLVAYAVPAAG-TAPDTTG----
                                         *****..*     . *  .    
