CLUSTAL W multiple sequence alignment


AEC14346.1_19_mod1_thr                   --SELKLLIGDKGRINGIDCNYVTLDE----VIENSNDITGENFHSLIDPKDPAYIIFTS
BGC0000400_AGM16412.1_3015_mod3_thr      SGAQVLLLPHDLRDKVGFDGTVVMLDDEQSYVEDSSNPATASK------PSDLAYVIYTS
AGM16412.1_3015_mod3_thr                 SGAQVLLLPHDLRDKVGFDGTVVMLDDEQSYVEDSSNPATASK------PSDLAYVIYTS
                                           ::: **  *     *:* . * **:    * :.**  *..:      *.* **:*:**

AEC14346.1_19_mod1_thr                   GSTGKPKGVCVSHENVMNLFLGCDGLFEFNNKDIWTFFHSYAFDFSVWEMWGAWIYGGEV
BGC0000400_AGM16412.1_3015_mod3_thr      GTTGKPKGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGRL
AGM16412.1_3015_mod3_thr                 GTTGKPKGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGRL
                                         *:******. :.*:**:.*::....**:**. * **:***:.********:** :***.:

AEC14346.1_19_mod1_thr                   VVVSFEESRNPISFVDLLISTQTTVFNCTPSAFFEVIGE-LINRQNELSLKYIIFGGEAL
BGC0000400_AGM16412.1_3015_mod3_thr      VVVPQLTAKNPAQFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEAL
AGM16412.1_3015_mod3_thr                 VVVPQLTAKNPAQFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEAL
                                         ***.   ::** .*::** . *.*::* **: *:::: * * :  :**.:: :*******

AEC14346.1_19_mod1_thr                   NFKKLTQWFSPENDRLP--KLINMYGITETTVHVTYKQITKSDVEKGITNIGKVLPHLGF
BGC0000400_AGM16412.1_3015_mod3_thr      NPQLLKDW----KTKYPHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKV
AGM16412.1_3015_mod3_thr                 NPQLLKDW----KTKYPHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKV
                                         * : *.:*    : : *  :*****************:**: ::*:. :***: :* * .

AEC14346.1_19_mod1_thr                   KVMNQNEEEVTGDEEGELYVSGKGVSLGYYKNTMMNKMKFTDI---DNVRYYKSGDVVKV
BGC0000400_AGM16412.1_3015_mod3_thr      YVLDANRQCVPVGVAGEMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARW
AGM16412.1_3015_mod3_thr                 YVLDANRQCVPVGVAGEMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARW
                                          *:: *.: *. .  **:**:*.*:: ** :.. :.  **.*    .. * *::**:.: 

AEC14346.1_19_mod1_thr                   LDDGDLQYIARNDEQVQLRGFRIELGEIESSYNDLKNIKNAVVTMDKAFNDDMHLFLYYV
BGC0000400_AGM16412.1_3015_mod3_thr      LPDGNIEYLGRIDHQVKIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCAYFV
AGM16412.1_3015_mod3_thr                 LPDGNIEYLGRIDHQVKIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCAYFV
                                         * **:::*:.* *.**::**:******:*:. ..:. :::*:*   :  :.: :*  *:*

AEC14346.1_19_mod1_thr                   ADEE-----
BGC0000400_AGM16412.1_3015_mod3_thr      AARELTVGE
AGM16412.1_3015_mod3_thr                 AARELTVGE
                                         * .*     
