CLUSTAL W multiple sequence alignment


BGC0001125_AIW82285.1_488_mod1_thr       AQVSVLLTQSQWLNSLTEVSAQTVCLDTDWEAISAFSQENPVNQATPNNLAYVIYTSGST
BAH22763.1_488_mod1_thr                  AQLSVLLTQQKLGETLPQHQAQIIYLDTDWEKIAENSHSNPENTVTPDNLAYVIYTSGST
Q847C7_A1_6__thr                         AAVPILLTQKSLLPSLPENQAIVMCLDRDWGVIAACSQENIVSHAQPQNLAYVIYTSGST
Q9K5M1_A3_5__thr                         AQVSVLLIQQHLVEKLQQHQAHIVCLDSDGEKIAQNSNSNPLNIATPSNLAYVIYTSGST
                                         * :.:** *.    .* : .*  : ** *   *:  *:.*  . . *.************

BGC0001125_AIW82285.1_488_mod1_thr       GKPKGVLVNHANVTRLFTATQSWFNFNESDVWTLFHSYAFDFSVWELWGALLYGGRLVIV
BAH22763.1_488_mod1_thr                  GKPKGVLVNHSNVVRLFAATDAWYNFSSQDVWSLFHSYAFDFSVWEMWGALLYGGRLVVV
Q847C7_A1_6__thr                         GKPKGVLINHQNVIRLFAATQAWYHFGASDVFTLFHSIAFDFSVWELWGALLYGGSLVIV
Q9K5M1_A3_5__thr                         GKPKGVLVNHSHVVRLFAATDSWYNFNSQDVWTMFHSYAFDFSVWEVWGALLYGGRLVVV
                                         *******:** :* ***:**::*::*. .**:::*** ********:******** **:*

BGC0001125_AIW82285.1_488_mod1_thr       PFWISRDPQAFYQLLCQEKVTVLNQTPSAFRQLIWVEEQAE------------VTVAKLY
BAH22763.1_488_mod1_thr                  PYLITRSPEAFYQLLCQEKVTILNQTPTAFRQLIQAEKSLKGSFPLSRGDRSSTTDNDLS
Q847C7_A1_6__thr                         PYWVSRDPSAFHTLLRQEQVTVLNQTPSAFRQLIRVEELAK------------TGESQLS
Q9K5M1_A3_5__thr                         GYLVTRSPKSFYELLCQEKVTILNQTPSAFRQLIPAEQSI-------------ATVGDLN
                                          : ::*.*.:*: ** **:**:*****:****** .*:               .   .* 

BGC0001125_AIW82285.1_488_mod1_thr       LRWVIFGGESLDPSSLMPWFERHGDGTPQLVNMYGITETTVHVTFRPLTIEDAHSRGSVI
BAH22763.1_488_mod1_thr                  LRLVIFGGEALEINSLQPWFQRHGDQCPQLVNMYGITETTVHVTYRPLSMTDLDSTASVI
Q847C7_A1_6__thr                         LRLVIFGGEALEPQSLQPWFEGYKDQSPQLVNMYGITETTVHVTYRPLSIADVNNSKSLI
Q9K5M1_A3_5__thr                         LRLVIFGGETLELNSLQPWFDRHGDQSPQLVNMYGITETTVHVTYRPLSKADLHGKASVI
                                         ** ******:*: .** ***: : *  *****************:***:  * ..  *:*

BGC0001125_AIW82285.1_488_mod1_thr       GLPIPDLQLYILDESLQPVPIGVRGQMFVGGAGVARGYLNRPELTADRFIQNPFS-----
BAH22763.1_488_mod1_thr                  GRPIPDLQVYLLDQYLQLVPVGVPGEMYVGGAGVTKGYLNRPELTTERFISSPFEKDEVI
Q847C7_A1_6__thr                         GVPIPDLQLYILDEQLKPLPIGIKGEMYIGGAGLARGYLNRPELTAERFIPNPFS-----
Q9K5M1_A3_5__thr                         GRPIGDLQVYVLDEHLQPVPIGVAGEMYVGGAGVTRGYLNRAELTAQRFISNPFN-----
                                         * ** ***:*:**: *: :*:*: *:*::****:::*****.***::*** .**.     

BGC0001125_AIW82285.1_488_mod1_thr       --------EQLGDKLYKTGDLARYRSDGNIEYLGRIDYQVKIRGFRIELGEIEAALSQHP
BAH22763.1_488_mod1_thr                  PPTPLNKGGNEPSKLYKTGDLARYLPKGELEYLGRIDNQVKIRGFRIELGEIEALLASHP
Q847C7_A1_6__thr                         --------DAPEARLYKTGDLARYLENGDIEYLDRIDNQVKIRGFRIELGEIEAALLKYP
Q9K5M1_A3_5__thr                         --------GNSEQLLYKSGDLARYLPNGELEYLGRIDNQVKIRGFRIELGEIEAALSQLR
                                                       ***:******  .*::***.*** **************** * .  

BGC0001125_AIW82285.1_488_mod1_thr       VVKEAVVIDREGKAGDKRLVAYIVSESQSDTLMG
BAH22763.1_488_mod1_thr                  QIWETVVIVRDDATGDKRLVAYIVPQSEKIITIN
Q847C7_A1_6__thr                         EVQEAVVMARTDQPGDKRLVAYIVAKSSNPASEN
Q9K5M1_A3_5__thr                         EVREVVVVARSDQPDNKRLVAYVVPQQKNLESSK
                                          : *.**: * . ..:******:*.:...     
