CLUSTAL W multiple sequence alignment


Q70K00_A2_thr                            SNVSILLLQHHLLEGTDYQSHTVFLDDPSSYGAEASNLKLNVMPNQLAYVIYTSGTTGNP
BGC0000400_AGM16412.1_3015_mod3_thr      SGAQVLLLPHDLRDKVGFDGTVVMLDDEQSYVEDSSNPATASKPSDLAYVIYTSGTTGKP
AGM16412.1_3015_mod3_thr                 SGAQVLLLPHDLRDKVGFDGTVVMLDDEQSYVEDSSNPATASKPSDLAYVIYTSGTTGKP
Q6YK39_A2_thr                            SNVSILLLQHHLLEGTDYQSHTVFLDDPSSYGAETSNLNLNVMPNQLAYVIYTSGTTGNP
                                         *...:*** *.* : ..::. .*:*** .**  ::**      *.:************:*

Q70K00_A2_thr                            KGTLIEHKNVVRLLFNNKNVFDFNASDTWTLFHSFCFDFSVWEMYGALLYGGKLVIIPKQ
BGC0000400_AGM16412.1_3015_mod3_thr      KGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGRLVVVPQL
AGM16412.1_3015_mod3_thr                 KGTLIEHKNVVRLLFNSKNLFDFNSADTWTLFHSFCFDFSVWEMYGALLYGGRLVVVPQL
Q6YK39_A2_thr                            KGTLIEHKNVVRLLFNNKNVFDFNASDTWTLFHSFCFDFSVWEMYGALLYGGKLVIVPKQ
                                         ****************.**:****::**************************:**::*: 

Q70K00_A2_thr                            IAKNPERYLQLLKSEAVTILNQTPSYFYQLMQEERADPESNLNIRKIIFGGEALNPSFLK
BGC0000400_AGM16412.1_3015_mod3_thr      TAKNPAQFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEALNPQLLK
AGM16412.1_3015_mod3_thr                 TAKNPAQFLELLHEQQVTILNQTPTYFYQLLREALAEPGQELKVRKVIFGGEALNPQLLK
Q6YK39_A2_thr                            IAKNPERYLQLLKSEAVTILNQTPSYFYQLMQEERADPESNLNIRKIIFGGEALNPSFLK
                                          **** ::*:**:.: ********:*****::*  *:* .:*::**:*********.:**

Q70K00_A2_thr                            DWKLKYPLTQLINMYGITETTVHVTYKEITEREIDEGRSNIGQPIPTLQAYILDEYQRIQ
BGC0000400_AGM16412.1_3015_mod3_thr      DWKTKYPHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKVYVLDANRQCV
AGM16412.1_3015_mod3_thr                 DWKTKYPHTQLINMYGITETTVHVTYKEITQVEIEQAKSNIGRPIPTLKVYVLDANRQCV
Q6YK39_A2_thr                            DWKLKYPLTQLINMYGITETTVHVTYKEITEREIDEGRSNIGQPIPTLQAYILDEYQHIQ
                                         *** *** **********************: **::.:****:*****:.*:**  ::  

Q70K00_A2_thr                            VMGIPGELYVAGEGLARGYLNRPELTGEKFVEHPFAAGEKMYKTGDVARWLPDGNIEYLG
BGC0000400_AGM16412.1_3015_mod3_thr      PVGVAGEMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARWLPDGNIEYLG
AGM16412.1_3015_mod3_thr                 PVGVAGEMYVAGDGLARGYLHRPELTADKFVDSPFESGGRMYRTGDLARWLPDGNIEYLG
Q6YK39_A2_thr                            VMGIPGELYVAGEGLARGYLNRPELTAEKFVEHPFAAGEKMYKTGDVARWLPDGNIEYLG
                                          :*:.**:****:*******:*****.:***: ** :* :**:***:*************

Q70K00_A2_thr                            RIDHQVKIRGYRIEIGEVEAALLQLESVKEAVVIAIEE-EGSKQLCAYLSGDDSLNTAQ
BGC0000400_AGM16412.1_3015_mod3_thr      RIDHQVKIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCAYFVAARELTVGE
AGM16412.1_3015_mod3_thr                 RIDHQVKIRGYRIELGEVEAQLTKVDPVREAIVIAREDGHGEKQLCAYFVAARELTVGE
Q6YK39_A2_thr                            RIDHQVKIRGYRIEIGEVEAALLQSESVKEAVVIAIEE-EGSKQLCAYLSGDDSLNTAQ
                                         **************:***** * : :.*:**:*** *: .*.******: .  .*...:
