CLUSTAL W multiple sequence alignment


AHH53506.1_475_mod1_trp                  ARPLFVVTDRDRVRAAEADPARACPVLAVDEVTSAGPPSPPPPPPPRDAWPDEMAYLVYT
BGC0000439_AHH53506.1_475_mod1_trp       ARPLFVVTDRDRVRAAEADPARACPVLAVDEVTSAGPPSPPPPPPPRDAWPDEMAYLVYT
                                         ************************************************************

AHH53506.1_475_mod1_trp                  SGSTGTPKAVVVTHRGIPTLTTDQREKYGTGPGSRVLQYISLGFDVSLSELCLALLSGGC
BGC0000439_AHH53506.1_475_mod1_trp       SGSTGTPKAVVVTHRGIPTLTTDQREKYGTGPGSRVLQYISLGFDVSLSELCLALLSGGC
                                         ************************************************************

AHH53506.1_475_mod1_trp                  LVIPETRFAGADLADFLTRERITVANIPPSVLATMPDRELPYLRTLVTGGEPAAPELVAR
BGC0000439_AHH53506.1_475_mod1_trp       LVIPETRFAGADLADFLTRERITVANIPPSVLATMPDRELPYLRTLVTGGEPAAPELVAR
                                         ************************************************************

AHH53506.1_475_mod1_trp                  WARGRVMFNAYGPSETTVEVTAGRCRPDATAPVLLGGLITNHRGYVLDAALEPVSPGMVG
BGC0000439_AHH53506.1_475_mod1_trp       WARGRVMFNAYGPSETTVEVTAGRCRPDATAPVLLGGLITNHRGYVLDAALEPVSPGMVG
                                         ************************************************************

AHH53506.1_475_mod1_trp                  ELYLAGPGVARGYLNQPARTAERFVADPFGPAGERLYRTGDLVRWHSEGQLEYVGRADGQ
BGC0000439_AHH53506.1_475_mod1_trp       ELYLAGPGVARGYLNQPARTAERFVADPFGPAGERLYRTGDLVRWHSEGQLEYVGRADGQ
                                         ************************************************************

AHH53506.1_475_mod1_trp                  VKIRGVRVELGEVEAALMALPDVAAAVAVARDDAADRVLVAYVVATEGATLDPDA
BGC0000439_AHH53506.1_475_mod1_trp       VKIRGVRVELGEVEAALMALPDVAAAVAVARDDAADRVLVAYVVATEGATLDPDA
                                         *******************************************************
