CLUSTAL W multiple sequence alignment


BGC0001019_AHB82071.1_2004_mod2_trp      SRAPVVLTERQLADHLP-SRCDVVLIDEDRGPGRAA--AGRARPPATPDNLAYVIYTSGS
Q70LM4_A1_13__trp                        SQASALLTQQSLLEILPVTAAHVICLDSDLLADEP---VDNASSEVTEQNLAYVIYTSGS
Q70LM4_A3_15__trp                        SQAVVVLTQAGLADKFTQAAAPVICLGEKLFADRAHVDVDNIQTDVASTNLAYVIYTSGT
Q70LM5_A5_11__trp                        SQASVLLTQASLTDRLPASSRQVICLDSDELANEP---VTNAETSVGEHNLAYVIYTSGS
Q70LM5_A3_9__trp                         SQASILLTQQSLAELLPKTQARVICLDGDSLANEP---VANPASEVTEQNLAYVMYTSGS
                                         *:*  :**:  * : :. :   *: :. .  ....   . .  . .   *****:****:

BGC0001019_AHB82071.1_2004_mod2_trp      TGRPKGVGVSHRAICSLAWDHIAQYGIDARSRILQFVSLSFDVATSDVVMALLSGATLCV
Q70LM4_A1_13__trp                        TGLPKGVMIEHHSAINLAYALIDAFDIQPTSRVLQFTSFSFDVSVSEVVMALLAGATLVI
Q70LM4_A3_15__trp                        TGLPKGVAVEHRSAMNMVQAYIAYFGLDESSRVLQFTSFSFDVSVSEIWQALLSGGTLVI
Q70LM5_A5_11__trp                        TGLPKGVMIEHRSVINLAYDLIRHFQIDATSRVLQFISFSFDVSVSEIVMSLLAGATLVI
Q70LM5_A3_9__trp                         TGLPKGVMVEHHSVVNLAHALIEAFRIQPSSRVLQFTSFSFDVSVSEIVMALLAGAALVI
                                         ** **** :.*::  .:.   *  : ::  **:*** *:****:.*::  :**:*.:* :

BGC0001019_AHB82071.1_2004_mod2_trp      CSAEERSPGAALVERLAERGITHLQIPASLLAGLPARALPELRAIIVGGEACAMDVLQRW
Q70LM4_A1_13__trp                        EDRESLLPGPELIQVLQEQRITTVSMVSSVLAALPDADLPDLHTLIVGGEAPSRELVARY
Q70LM4_A3_15__trp                        EDRESLLPGPDLVRTLRERRISKVSMASSLLASLPVAEYPDLAVLEVGGDACSRELVARY
Q70LM5_A5_11__trp                        EDRESLLPGPELIRVLQEQRITTFAMVSSVLAALPEADLPDLRTIIVGGEAPSRELVARY
Q70LM5_A3_9__trp                         EDREVLLPGPELISVLQQKRITTVSMVSSVLAALPAADLPDLQTLIVGGEAPSRELVARY
                                          . *   **. *:  * :: *: . : :*:**.**    *:* .: ***:* : ::: *:

BGC0001019_AHB82071.1_2004_mod2_trp      RSGRRLFNAYGPTETTVCATIGEIGPDDAVTHIGRPIANARVYILDPHLEPAPTGVAGEI
Q70LM4_A1_13__trp                        APGRQFFNCYGPTEATVCSTMMLCQAGMNNPPIGRPIANATVYVLDANLNPVPVGVPGEL
Q70LM4_A3_15__trp                        ATGRKFFNCYGPTEATVGTVIKQLTLDDDTPTIGRPFPNTKLYVLDQNRKPVPVGVPGEL
Q70LM5_A5_11__trp                        ATGRQFINCYGPTETTVTATLKHCQDDGKNPPIGRPIANTTVYVLDAHLQPVPIGVPGEL
Q70LM5_A3_9__trp                         ADRRQFFNCYGPTEATVCSTMMLCNAGMKSAPIGRPLANATLYVLDANQKPVPVGVPGEL
                                            *:::*.*****:** :.:     .   . ****:.*: :*:** : :*.* **.**:

BGC0001019_AHB82071.1_2004_mod2_trp      YVGGAHLARGYLGQPGLTAERFLPDPHAPEPGARMYRTGDLALHREDGRIEFLGRTDQQV
Q70LM4_A1_13__trp                        YIGGKGLARGYWNRPELTAESFIPHPFG-TAGERLYRTGDLVRYRQDGNLEFLGRIDHQV
Q70LM4_A3_15__trp                        YIGGECLARGYWNRPELTAERFVANPFG-QPGERLYRTGDLVRYLPDGNVDYLGRFDDQV
Q70LM5_A5_11__trp                        YIGGKGVARGYWNRPELTAERFIADPFG-QADERLYRTGDLVRYLENGELEFLGRIDDQV
Q70LM5_A3_9__trp                         YIGGKGLARGYWNRPELTAERFIAHPFG-AKGERLYRTGDLVRYLPDGNLEFLGRIDTQV
                                         *:**  :**** .:* **** *:..*..   . *:******. :  :*.:::*** * **

BGC0001019_AHB82071.1_2004_mod2_trp      KLHGNRIELGEIEAALSGHPDVAQAVVLLREDRPGQRRLVAYAARAEGRTVDG--
Q70LM4_A1_13__trp                        KIRGYRIELGEIENAIRQHPAVQEAVVIAREEKAGDKRLAAYLVAAGKAQPPAEE
Q70LM4_A3_15__trp                        KIRGYRIELGEIAEALRQHAAIREAVVLAREVRPGDKRLAAYLTSAAEQELSVDE
Q70LM5_A5_11__trp                        KIRGYRIELGEIENALRQHPAVQNVVVIARQEGAGDKRLAAYLVAATGQQPDEAE
Q70LM5_A3_9__trp                         KIRGYRIELGEIESALSQHPAIQEAVVIAWEQ-----RLAAYMVAAGEAQPAAEE
                                         *::* *******  *:  *. : :.**:  :      **.** . *         
