CLUSTAL W multiple sequence alignment


BGC0001178_AGS77307.1_1045_mod2_tyr      ADPVSVICVGKTREAVPAEFADRLIVVDEVEPAAGPDGKLPRVGPDDAAYVIYTSGSTGT
Q70AZ9_A2_tyr                            ADPALVVCAGKTREAVPAAFADRLLVVDEMDLTGGSAARLPRVRPGDAAYVIYTSGSTGR
Q8KLL3_A2_tyr                            ADPVLVVCDGKARDAVPEEFADRSLVIDEVDLSAVPDAELPRVGPDDVAYVIYTSGSTGT
                                         ***. *:* **:*:***  **** :*:**:: :. . ..**** *.*.*********** 

BGC0001178_AGS77307.1_1045_mod2_tyr      PKGVVVTHAGLGNLAAAQIDRFGVSPSSRVLQFAALGFDAVVSETLMALLSGARLVLAPP
Q70AZ9_A2_tyr                            PKGVVVPHAGLGNLALAQIDRFGVSPSSRVLQFAALGFDAMVSEVLMALLSGARLVMAPE
Q8KLL3_A2_tyr                            PKGVVVTHAGLGNLAAAQIDRFAVSPSSRVLQFAALGFDATVSEALMALLSGATLVMAPK
                                         ******.******** ******.***************** ***.******** **:** 

BGC0001178_AGS77307.1_1045_mod2_tyr      QDMPPRVSLAEALERWDVTHVTVPPSVLATADALPAKLETVVVAGEACPPSLVDRWSAGR
Q70AZ9_A2_tyr                            HQLPPRVSLAEALQRWDVTHVTVPPSVLATAEALPARLETVVVAGEACPPSLADRWSAGL
Q8KLL3_A2_tyr                            QDLPPRVSLAEALERWDVTHVTVPPSVLATADVLPESLETVVVAGEACPPGLADRWSEGR
                                         :::**********:*****************:.**  *************.*.**** * 

BGC0001178_AGS77307.1_1045_mod2_tyr      RLVNAYGPTEATVCAAMSMPLAASRDVVPIGTPIAGGRCYVLDAFLRPLPPGIIGELYVA
Q70AZ9_A2_tyr                            RLVNAYGPTEATVCAAMSMPLVASRPVVPIGTPIAGGRCYVLDAFLRPLPPGLTGELYVA
Q8KLL3_A2_tyr                            RLINAYGPTEATVCAAMSMPLTAGRDVVPIGEPIAGSRCHVLDAFLRPLPPGVTGELYVS
                                         **:******************.*.* ***** ****.**:************: *****:

BGC0001178_AGS77307.1_1045_mod2_tyr      GIGLARGYLGRAALTAERFVADPFVPVERMYRTGDLAYWTDRSELVFAGRADDQMKIRGF
Q70AZ9_A2_tyr                            GIGLARGYLGRAALTAERFVADPFVPGERMYRTGDLAYRTGEGELVFAGRADDQVKVRGF
Q8KLL3_A2_tyr                            GIGLARGYLGRAALTAERFVADPFVPGERMYRTGDLAHLTSSGELVFAGRADDQVKLRGF
                                         ************************** **********: *. .***********:*:***

BGC0001178_AGS77307.1_1045_mod2_tyr      RVEPGEIESALSGHPGVAQAAVTVREDRLLAYVSPGDVDPQAV
Q70AZ9_A2_tyr                            RIEPGEVESALSGHPGVAQAAVIVRGDRLLAYVSPAGVDPQAV
Q8KLL3_A2_tyr                            RIEPGEIESVLSGHPQVAQAAVTVRDDRLLAHVSPTEVDPHAV
                                         *:****:**.***** ****** ** *****:***  ***:**
