CLUSTAL W multiple sequence alignment


P39846_A1_tyr                            SQAAQLLIEEDLISLIPPSYEGNTITIEHTESY-QTEAPNMP-PGDLAYLIYTSGTTGRP
P94459_A3_tyr                            SGTKLLMTINEADLGVLADFEGEILTIESVEEDDKSPLPQMSSAHHLAYIIYTSGTTGRP
O30980_A3_9__tyr                         SRTKLLITLPAADQEALEDFEGEIFAIENAETYDGSPLPQVSRPQHLAYIIYTSGTTGQP
O30980_A3_tyr                            SRTKLLITLPAADQEALEDFEGEIFAIENAETYDGSPLPQVSRPQHLAYIIYTSGTTGQP
O87704_A1_3__tyr                         SQAALLLTEEELISSIPSGYEGSIVTSGHTTHY-RTDSPDAS-IGELAYLIYTSGTTGRP
                                         * :  *:           .:**. .:   .     :  *: .   .***:********:*

P39846_A1_tyr                            KGVLVDHHGIANTLQWRREEYSMTEQDISLHLFSYVFDGCVTSLFTPLLSGACVLLTTDD
P94459_A3_tyr                            KGVMVEHKGIANTLQWRRNAYAFNETDTILQLFSFSFDGFITSMFTPLLSGAKAVLLHEE
O30980_A3_9__tyr                         KGVMVEHKGIANTLQWRRNAYTLNETDTVLQLFSFSFDGFLTSMFTPLLSGAKTVLPDEN
O30980_A3_tyr                            KGVMVEHKGIANTLQWRRNAYTLNETDTVLQLFSFSFDGFLTSMFTPLLSGAKTVLPDEN
O87704_A1_3__tyr                         KGVLVDHQGIANTLQWRREEYGMSEGDTALHLFSYVFDGCVTSLFTPLLSGACVLLTTDN
                                         ***:*:*:**********: * :.* *  *:***: *** :**:******** .:*  ::

P39846_A1_tyr                            EAKDVLALKRKIARYKVSHMIIVPSLYRVLLEVMTADDAKSLRIVTFAGEAVTPDLLELN
P94459_A3_tyr                            EAKDILAIKHQLSRQRITHMIIVPVLYRALLDVVQPEDVKTLRVVTLAGEAADRELIARS
O30980_A3_9__tyr                         EAKDILSIKHDLSHHRITHMIIVPVLYRALLDVIQPEDAKTLRVVTLAGEAADRELIDRS
O30980_A3_tyr                            EAKDILSIKHDLSHHRITHMIIVPVLYRALLDVIQPEDAKTLRVVTLAGEAADRELIDRS
O87704_A1_3__tyr                         EAKDVLALRRKIAQYKVSHMLIVPSLYRVLLEVLTAEDAKSLRIVTFAGEAVTPDLLETS
                                         ****:*::::.::: :::**:*** ***.**:*: .:*.*:**:**:****.  :*:  .

P39846_A1_tyr                            QIICPSAELANEYGPTENSVATTILRHLNKKERITIGHPIRNTKVFVLHGN-QMQPIGAA
P94459_A3_tyr                            LAICPHTELANEYGPTENSVATTVMRHMEKQAYVSIGQPIDGTQVLILNSNHQLQPIGVA
O30980_A3_9__tyr                         MAICPNTELANEYGPTENSVATTAMRHMERQKNVCIGRPIDNTEVLILNGD-QLQPIGVA
O30980_A3_tyr                            MAICPNTELANEYGPTENSVATTAMRHMERQKNVCIGRPIDNTEVLILNGD-QLQPIGVA
O87704_A1_3__tyr                         RKICPSAELANEYGPTENSVATTILRHLNEEERITIGHPIANTKVYILQGE-QLQPIGAA
                                           *** :**************** :**::.:  : **:** .*:* :*:.: *:****.*

P39846_A1_tyr                            GELCISGAGLARGYYKQQELTQKAFSDHPFLEGERLYRTGDAGRFLPDGTIEYIGRFDDQ
P94459_A3_tyr                            GELCIAGTGLARGYVNLPELTERAFTQNPFKPEARMYRTGDAARWMADGTLEYLGRIDDQ
O30980_A3_9__tyr                         GELCIAGTGLARGYVNLPELTAKTFVQHPYQPEKRMYRTGDAARWMADGTIEYLGRMDDQ
O30980_A3_tyr                            GELCIAGTGLARGYVNLPELTAKTFVQHPYQPEKRMYRTGDAARWMADGTIEYLGRMDDQ
O87704_A1_3__tyr                         GELCISGAGLARGYYKRTELTEKAFTDHPFLKGERLYRTGDAGRFLPDGTIEYIGRFDDQ
                                         *****:*:****** :  *** ::* ::*:    *:******.*::.***:**:**:***

P39846_A1_tyr                            VKIRGYRIELREIETVLRQAPGVKEAAVLARDVSAEEKELVAYIVPEKGNSLPD
P94459_A3_tyr                            VKIRGYRVETKEIESVIRCIKGVKDAAVVAHVTASGQTELSAYVVTKPGLSTNA
O30980_A3_9__tyr                         VKIRGHRVETKEIESVIRRISGVKEAVVLARETAPAQTELCAYIVAEQDFNTEM
O30980_A3_tyr                            VKIRGHRVETKEIESVIRRISGVKEAVVLARETAPAQTELCAYIVAEQDFNTEM
O87704_A1_3__tyr                         VKIRGYRIELSEIETVLRQASGVKEAAVLARDVSDEEKELVAYIVPEKGNGLPN
                                         *****:*:*  ***:*:*   ***:*.*:*: .:  :.** **:*.: . .   
