CLUSTAL W multiple sequence alignment


BGC0001178_AGS77307.1_1045_mod2_tyr      ADPVSVICVGKTREAVPAEFADRLIVVDEVEPAAGPDGKLPR--VGPDDAAYVIYTSGST
Q93N87_A3_tyr                            AAPPVLLCTARTRAAVPADYPGRNVVLDELDDSALPAEPFTATPVPPDQAAYVIYTSGST
Q70AZ9_A2_tyr                            ADPALVVCAGKTREAVPAAFADRLLVVDEMDLTGGSAARLPR--VRPGDAAYVIYTSGST
Q93N87_A3_6__tyr                         AAPPVLLCTARTRAAVPADYPGRNVVLDELDDSALPAEPFTATPVPPDQAAYVIYTSGST
Q8KLL3_A2_tyr                            ADPVLVVCDGKARDAVPEEFADRSLVIDEVDLSAVPDAELPR--VGPDDVAYVIYTSGST
                                         * *  ::* .::* ***  :..* :*:**:: :. .   :.   * *.:.**********

BGC0001178_AGS77307.1_1045_mod2_tyr      GTPKGVVVTHAGLGNLAAAQIDRFGVSPSSRVLQFAALGFDAVVSETLMALLSGARLVLA
Q93N87_A3_tyr                            GAPKGVVVPHAGLGNLAAAQIDRFAVGPDARVLQLASLGFDAAVSELLMALLSGAAAIVA
Q70AZ9_A2_tyr                            GRPKGVVVPHAGLGNLALAQIDRFGVSPSSRVLQFAALGFDAMVSEVLMALLSGARLVMA
Q93N87_A3_6__tyr                         GAPKGVVVPHAGLGNLAAAQIDRFAVGPDARVLQLASLGFDAAVSELLMALLSGAAAIVA
Q8KLL3_A2_tyr                            GTPKGVVVTHAGLGNLAAAQIDRFAVSPSSRVLQFAALGFDATVSEALMALLSGATLVMA
                                         * ******.******** ******.*.*.:****:*:***** *** ********  ::*

BGC0001178_AGS77307.1_1045_mod2_tyr      PPQDMPPRVSLAEALERWDVTHVTVPPSVLATADALPAKLETVVVAGEACPPSLVDRWSA
Q93N87_A3_tyr                            PAETLPPLVSLTEALRHWDVTHVTVPPSALATADELPDGLRTLVVAGEACPPALADRWAG
Q70AZ9_A2_tyr                            PEHQLPPRVSLAEALQRWDVTHVTVPPSVLATAEALPARLETVVVAGEACPPSLADRWSA
Q93N87_A3_6__tyr                         PAETLPPLVSLTEALRHWDVTHVTVPPSALATADELPDGLRTLVVAGEACPPALADRWAG
Q8KLL3_A2_tyr                            PKQDLPPRVSLAEALERWDVTHVTVPPSVLATADVLPESLETVVVAGEACPPGLADRWSE
                                         * . :** ***:***.:***********.****: **  *.*:*********.*.***: 

BGC0001178_AGS77307.1_1045_mod2_tyr      GRRLVNAYGPTEATVCAAMSMPLAASRDVVPIGTPIAGGRCYVLDAFLRPLPPGIIGELY
Q93N87_A3_tyr                            GRRMINAYGPTETTVCASMSPPLAPGADVVPVGRPIANGRTYVLDPFLRPVPPGVTGELY
Q70AZ9_A2_tyr                            GLRLVNAYGPTEATVCAAMSMPLVASRPVVPIGTPIAGGRCYVLDAFLRPLPPGLTGELY
Q93N87_A3_6__tyr                         GRRMINAYGPTETTVCASMSPPLAPGADVVPVGRPIANGRTYVLDPFLRPVPPGVTGELY
Q8KLL3_A2_tyr                            GRRLINAYGPTEATVCAAMSMPLTAGRDVVPIGEPIAGSRCHVLDAFLRPLPPGVTGELY
                                         * *::*******:****:** **...  ***:* ***..* :***.****:***: ****

BGC0001178_AGS77307.1_1045_mod2_tyr      VAGIGLARGYLGRAALTAERFVADPFVPVERMYRTGDLAYWTDRSELVFAGRADDQMKIR
Q93N87_A3_tyr                            VAGAGLARGYLGQGGLTATRFVPDPFTPGERMYRTGDLARWTHDGLLVFAGRADAQVKVR
Q70AZ9_A2_tyr                            VAGIGLARGYLGRAALTAERFVADPFVPGERMYRTGDLAYRTGEGELVFAGRADDQVKVR
Q93N87_A3_6__tyr                         VAGAGLARGYLGQGGLTATRFVPDPFTPGERMYRTGDLARWTHDGLLVFAGRADAQVKVR
Q8KLL3_A2_tyr                            VSGIGLARGYLGRAALTAERFVADPFVPGERMYRTGDLAHLTSSGELVFAGRADDQVKLR
                                         *:* ********:..*** ***.***.* **********  *  . ******** *:*:*

BGC0001178_AGS77307.1_1045_mod2_tyr      GFRVEPGEIESALSGHPGVAQAAVTVRED-----RLLAYVSPGDVDPQAV-
Q93N87_A3_tyr                            GHRIEPGEVEAVLAEHPGVAQAAVVAREDTPGERRLIGYVVPDAADRGRDE
Q70AZ9_A2_tyr                            GFRIEPGEVESALSGHPGVAQAAVIVRGD-----RLLAYVSPAGVDPQAV-
Q93N87_A3_6__tyr                         GHRIEPGEVEAVLAEHPGVAQAAVVAREDTPGERRLIGYVVPDAADRGRDE
Q8KLL3_A2_tyr                            GFRIEPGEIESVLSGHPQVAQAAVTVRDD-----RLLAHVSPTEVDPHAV-
                                         *.*:****:*:.*: ** ****** .* *     **:.:* *  .*     
