CLUSTAL W multiple sequence alignment


Q70JZ9_A1_tyr                            ADADVLLVQHHLKNSLAFDGPVIDLNDETSYHADCSLLSPVAGHSHLAYVIYTSGTTGKP
Q93I55_A1_tyr                            ADADVLLVQHHLKNSLAFDGPVIDLNDETSYHADCSLLSPVAGHSHLAYVIYTSGTTGKP
Q6YK40_A1_tyr                            ADADVLLVQHHLKNSLAFDGPVIDLNDETSYHADCSLLSPVAGHSHLAYVIYTSGTTGKP
Q9R9J0_A1_tyr                            ANADVLVVQRHFKNSLVFDGPMIDLNDETSYHADCSLLSPIAEHSHLAYVIYTSGTTGKP
                                         *:****:**:*:****.****:******************:* *****************

Q70JZ9_A1_tyr                            KGVMVEHGGIVNSLQWKKAFFKHSPADRVLVLYPYVFDAFILNFFGPLISGATLHLLPNE
Q93I55_A1_tyr                            KGVMVEHGGIVNSLQWKKAFFRHSPADRVLVLYPYVFDAFILNFFGPLISGATLHLLPNK
Q6YK40_A1_tyr                            KGVMVEHSGIVNSLQWKKAFFKHSPADRVLVLYPYVFDAFILNFFGPLISGATLHLLPNE
Q9R9J0_A1_tyr                            KGVMVEHGGIVNSLQWKKAFFKHSAEDRVLVLYPYVFDAFILNFFGPLISGAALYLLPNE
                                         *******.*************:**. **************************:*:****:

Q70JZ9_A1_tyr                            ENKETFAIQNAIKQERITHFSTSPRLLKTMIEQMNREDFIHVQHVVVGGEQLEADTVEKL
Q93I55_A1_tyr                            ENKETFAIQNAIKQERITHFSTSPRLLKTMIEQMNREDFIHVQHVVVGGEQLEADTVEKL
Q6YK40_A1_tyr                            ENKETFAIQNAIKQERITHFSTSPRLLKTMIEQMNREDFIHVQHVVVGGEQLETDTVEKL
Q9R9J0_A1_tyr                            DNKDLFAIQNVLKLERITHFSTSPRLLQAMTEQMNAEDFYHVQHVVVGGEKLEPDTVERL
                                         :**: *****.:* *************::* **** *** **********:**.****:*

Q70JZ9_A1_tyr                            HSLQPRIRINNEYGPTENSVVSTFHPVQSADEQITIGSPVANHQAYILGAHHQIQPIGVP
Q93I55_A1_tyr                            HSLQPRIRINNEYGPTENSVVSTFHPVQSADEQITIGSPVANHQAYILGAHHQIQPIGVP
Q6YK40_A1_tyr                            HSLQPRIRINNEYGPTENSVVSTFHPVQSADEQITIGSPVANHQAYILGAHHQIQPIGVP
Q9R9J0_A1_tyr                            FSLQPQIRINNEYGPTENSVVSTFQPVYSADEQITIGKPVANHQAYILGAHRQIQPIGVP
                                         .****:******************:** *********.*************:********

Q70JZ9_A1_tyr                            GELYVGGAGVARGYLNRPELTEEKFVEHLHVPGQKMYKTGDLARWLPDGRIEYLGRIDHQ
Q93I55_A1_tyr                            GELYVGGAGVARGYLNRPELTEEKFVEHLHVPGQKMYKTGDLARWLPDGRIEYLGRIDHQ
Q6YK40_A1_tyr                            GELYVGGAGVARGYLNRPELTEEKFVEHLHVPGQKMYKTGDLARWLPDGRIEYLGRIDHQ
Q9R9J0_A1_tyr                            GELYVGGSGVARGYLNQPDLTEEKFVDHLLIPRRKMYKTGDLARWLPDGRIEYLGRIDHQ
                                         *******:********:*:*******:** :* :**************************

Q70JZ9_A1_tyr                            VKIRGYRIEIGEVEAAMFNLENVREAAVVAREDADGAKQLYAYYVGEPSLTAAQ
Q93I55_A1_tyr                            VKIRGYRIEIGEVEAAMFNLENVREAAVVAREDADGAKQLYAYYVGEPSLTAAQ
Q6YK40_A1_tyr                            VKIRGYRIEIGEVEAAMFNLENVREAAVVAREDADGAKQLYAYYVGEPSLTAAQ
Q9R9J0_A1_tyr                            VKIRGYRIELGEVEAALSNLEEVRETTVESREGIDGTKQLYAYYVGEPSLSAGQ
                                         *********:******: ***:***::* :**. **:*************:*.*
