CLUSTAL W multiple sequence alignment


Q83VS0_A1_11__val                        CGARQVLTLSRHDLPDGIQRIDLDLL---ELQSDAPNPVHSASAESVAYIMYTSGSTGMP
Q83VS1_A3_8__val                         SQASVLLTLSQMSLTTSTQRVDLDRLMLNGLDNDDLAL--AQSSESVAYIMYTSGSTGTP
Q9FDB3_A3_3__val                         SQAHVLLTLSRMSLTASTQRIDLDGLTLDGLKDTDLTL--PQSSESVAYIMYTSGSTGVP
Q83VS1_A2_7__val                         SRARVLLTHSQVSLTTSAQRIDLDGLTLERLKGTDLAL-PPQSSESVAYIMYTSGSTGTP
AFZ61525.1_1627_mod2_val                 SGAHRVLN-------------NLADLNLDAQSPRNPEL--PQSAESVAYILYTSGSTGAP
BGC0000425_AFH75321.1_5900_mod6_val      SQATLLLSHAGLGKALQVQRLDLDQAHLGQLPDDQPAV--VVSSEAAAYIMYTSGSTGTP
Q9FDB3_A4_4__val                         SQAVLVLTYSTETLDPGTQRLDLDTRPASTVPADNPNP--EACADSVAYIMYTSGSTGTP
Q83VS1_A2_val                            SRARVLLTHSQVSLTTSAQRIDLDGLTLERLKGTDLAL-PPQSSESVAYIMYTSGSTGTP
Q83VS1_A3_val                            SQASVLLTLSQMSLTTSTQRVDLDRLMLNGLDNDDLAL--AQSSESVAYIMYTSGSTGTP
                                         . *  :*.             :*                   .:::.***:******* *

Q83VS0_A1_11__val                        KGVLVPHRAVSRLVLNNGYADFNAGDRVAFASNPAFDASTLDVWAPLLNGGCVVVVEQSV
Q83VS1_A3_8__val                         KGVLVPHRAISRLVINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHD
Q9FDB3_A3_3__val                         KGVLVPHRAISRLVINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHD
Q83VS1_A2_7__val                         KGVLVPHRAISRLAINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHD
AFZ61525.1_1627_mod2_val                 KGVQVPHRAISRLVLNNGYAEFNARDRVAFASNPAFDASTLDVWAPLLNGGCVVVVEHGV
BGC0000425_AFH75321.1_5900_mod6_val      KGVRVPHRAITRLVINNGYADFNQHDRVAFASNPAFDASTLEVWAPLLNGGAVVVIDQDT
Q9FDB3_A4_4__val                         KGVLVPHRAISRLVIDNGYADFNGQDRVAFASNPAFDASTLDVWAPLLNGGCVIVVEQSV
Q83VS1_A2_val                            KGVLVPHRAISRLAINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHD
Q83VS1_A3_val                            KGVLVPHRAISRLVINNGYADFNAQDRVAFASNPAFDASTLDVWAPLLNGGCVVVIGQHD
                                         *** *****::**.::****:**  ****************:*********.*:*: :  

Q83VS0_A1_11__val                        LLSLDEFRALLLSQSVSVLWMTAGLFHQYASGLMEALARLRYLIVGGDVLDPAVIARVLA
Q83VS1_A3_8__val                         LLSPLNFQRLLLEQSVTVLWMTAGLFHQYASGLGEAFSRLRYLIVGGDVLDPAVIARVLA
Q9FDB3_A3_3__val                         LLSPLNFQRLLLEQSVSVLWMTAGLFHQYATGLGEAFSRLRYLIVGGDVLDPAVIARVLA
Q83VS1_A2_7__val                         LLSPLNFQRLLLEQSVSVLWMTAGLFHQYASGLGEAFSRLRYLIVGGDVLDPAVIGRVLA
AFZ61525.1_1627_mod2_val                 LLSQAAFASLLQEQSVSVLWMTAGLFHQYADALMPVFRQLRYLIVGGDVLDPQVIGRVLE
BGC0000425_AFH75321.1_5900_mod6_val      LLTQHAFAALLQQQDVSVVWMTAGLFHQYAEGLLEAFARLRYLIVGGDVLDPSVIARVLK
Q9FDB3_A4_4__val                         LLSQEAFRALLLAQSISVLWLTAGLFHQYADGLMEVFAGLRYLIVGGDVLDPAVIARVLA
Q83VS1_A2_val                            LLSPLNFQRLLLEQSVSVLWMTAGLFHQYASGLGEAFSRLRYLIVGGDVLDPAVIGRVLA
Q83VS1_A3_val                            LLSPLNFQRLLLEQSVTVLWMTAGLFHQYASGLGEAFSRLRYLIVGGDVLDPAVIARVLA
                                         **:   *  **  *.::*:*:********* .*  .:  ************* **.*** 

Q83VS0_A1_11__val                        EGAPQHLLNGYGPTEATTFSTTHEITSVGSGGIPIGRPIGNSQVYVLDTLRQPVAVGVAG
Q83VS1_A3_8__val                         NNAPQHLLNGYGPTEATTFSATYEIVSVDNGSIPIGKPVGNTRLYVLDSQGQPVPLGVPG
Q9FDB3_A3_3__val                         NNAPQHLLNGYGPTEATTFSATYEITSVDNGSIPIGKPVGNTRLYVLDSQGQPAPLGVAG
Q83VS1_A2_7__val                         NNPPQHLLNGYGPTEATTFSATYEIVSVGNGSIPIGKPVGNSRLYVLDNQGQPVPLGVPG
AFZ61525.1_1627_mod2_val                 HGKPQHLLNGYGPTEATTFSTTFEITSVGEGGIPIGRPIANAQAYVLDPRQQPVPLGVVG
BGC0000425_AFH75321.1_5900_mod6_val      GGAPRHLLNGYGPTEATTFSTTHEITRADEGSIPIGKPVGNSRAYVLDAHQQPVPVGVTG
Q9FDB3_A4_4__val                         QGAPQHLLNGYGPTEATTFSTTYEITAADHGGIPIGRPIANSQVYVLDALRQPVAVGVPG
Q83VS1_A2_val                            NNPPQHLLNGYGPTEATTFSATYEIVSVGNGSIPIGKPVGNSRLYVLDNQGQPVPLGVPG
Q83VS1_A3_val                            NNAPQHLLNGYGPTEATTFSATYEIVSVDNGSIPIGKPVGNTRLYVLDSQGQPVPLGVPG
                                          . *:***************:*.**. .. *.****:*:.*:: ****   **..:** *

Q83VS0_A1_11__val                        ELYIGGQGVAKGYLNRPELNATQFVANPFSDDAGALLYRTGDLGRWNADGIVEYLGRNDD
Q83VS1_A3_8__val                         ELYIGGQGVAKGYLNRDELSTTQFVVDPFSEQIDALMYRTGDLVRWRADGNLEYLGRNDD
Q9FDB3_A3_3__val                         ELYIGGQGVARGYLHRDELTLEKFLADPFDSDPQARLYRTGDLVRWRADGNLEYLGRNDD
Q83VS1_A2_7__val                         ELYIGGQGVARGYLHRDELTLERFVADPFDSDPQARLYRTGDLVRWRADGNLEYLGRNDE
AFZ61525.1_1627_mod2_val                 ELYIGGAGVAKGYLNQPQLTAEKFIPNPFGE---GVLYRTGDLACWQVDGTLVYQGRNDL
BGC0000425_AFH75321.1_5900_mod6_val      ELYIGGQGVALGYLNRPELTAEKFLVDPFSD--GGLMYRTGDLVAWRADGTLQYQGRNDQ
Q9FDB3_A4_4__val                         ELYIGGQGVAKGYLNRDELSTTQFVADPFSGHDGALMYRTGDLGRWRADGNLEYLGRNDG
Q83VS1_A2_val                            ELYIGGQGVARGYLHRDELTLERFVADPFDSDPQARLYRTGDLVRWRADGNLEYLGRNDE
Q83VS1_A3_val                            ELYIGGQGVAKGYLNRDELSTTQFVVDPFSEQIDALMYRTGDLVRWRADGNLEYLGRNDD
                                         ****** *** ***:: :*.  :*: :**.    . :******  *..** : * **** 

Q83VS0_A1_11__val                        QVKIRGFRIELGEIEARLVECPGVREAVVLARQDESAHKRLVAYVVGEENSALSAVEL
Q83VS1_A3_8__val                         QVKIRGFRVELGEIEARLAEHADVREAVVLCRQDVPGDKRLVAYVTAQQSENALDIEH
Q9FDB3_A3_3__val                         QVKIRGFRVELGEIEARLAEHVDVREAVVLCRQDVPGDKRLVAYVTAQQAETALDIEH
Q83VS1_A2_7__val                         QVKIRGFRVELGEIEARLAEHAEVREAVVLCRQDAPGDKRLVAYVTAQQPETALDIEH
AFZ61525.1_1627_mod2_val                 QVKIRGFRIEPGEIETCLASFTGVKDAVVLAREDEPGDKRLVAYYTASEP---LDIET
BGC0000425_AFH75321.1_5900_mod6_val      QVKIRGFRIELGEIETRLAGCPGVKDAVVLARQDEPGHKRLVAYFTERES---LDIEA
Q9FDB3_A4_4__val                         QVKIRGFRIELSEIEAALATHPAVHEAVLLARQD-TGEKRLVAYFTLREPQQTLEIET
Q83VS1_A2_val                            QVKIRGFRVELGEIEARLAEHAEVREAVVLCRQDAPGDKRLVAYVTAQQPETALDIEH
Q83VS1_A3_val                            QVKIRGFRVELGEIEARLAEHADVREAVVLCRQDVPGDKRLVAYVTAQQSENALDIEH
                                         ********:* .***: *.    *::**:*.*:* ...****** .  :      :* 
