CLUSTAL W multiple sequence alignment


P0C064_A2_3__val                         CGVRIMLT-QQHLLSLVHDEFDCVILDEDSLYKGDSSNLAPVNQA---GDLAYIMYTSGS
P39847_A2_val                            SRAALLLQSEKTEKRLLGIECEQIIIEDIQ-KQGEAKNVESSAGP---HSLAYIIYTSGS
Q70KJ6_A1_4__val                         SSIRLVLTVQDYQEQAGALQV-PVVMLDES--ADETVSGTDLNLPAGGNDLAYIMYTSGS
O33743_A4_8__val                         GGVKVVLV-QKHLLPLVGEGLMPIVLEEESLRPEDCGNPAIVNGA---SDLAYVMYTSGS
Q04747_A1_4__val                         SSVRMVLIGNSYTGQAHQLQV-PVLTLDIG--FEESEAADNLNLPSAPSDLAYIMYTSGS
P0C063_A2_val                            CGVRIMLT-QQHLLSLVHDEFDCVILDEDSLYKGDSSNLAPVNQA---GDLAYIMYTSGS
O69246_A1_4__val                         SGSKIVLTKDGTQISLEGYEVLAVNAMDAE--KEDAANLEHVNKP---EDLAYYIYTSGS
                                             ::*  :             :   :      :         .    .*** :*****

P0C064_A2_3__val                         TGKPKGVMVEHRNVIRLVKNTNYVQVREDDRIIQTGAIGFDALTFEVFGSLLHGAELYPV
P39847_A2_val                            TGKPKGVMIEQRSVIRLVKNSNYITFTPEDRLLMTSSIGFDVGSFEIFGPLLNGAALHLS
Q70KJ6_A1_4__val                         TGKPKGVMIEHRNIIRLVKHSNYVPVHEEDRMAQTGAVSFDAGTFEVFGALLNGASLHPV
O33743_A4_8__val                         TGKPKGVMVEHRNVTRLVMHTNYVQVRESDRMIQTGAIGFDAMTFEIFGALLHGASLYLV
Q04747_A1_4__val                         TGKPKGVMIEHKSILRLVKNAGYVPVTEEDRMAQTGAVSFDAGTFEVFGALLNGAALYPV
P0C063_A2_val                            TGKPKGVMVEHRNVIRLVKNTNYVQVREDDRIIQTGAIGFDALTFEVFGSLLHGAELYPV
O69246_A1_4__val                         TGRPKGVMVEHRNIVRLVKNAGCIPLKSGVKMAQTGAVSFDASTFEVFGALLNGGTLYPV
                                         **:*****:*::.: *** ::. : .    ::  *.::.**. :**:**.**:*. *:  

P0C064_A2_3__val                         TKDVLLDAEKLHKFLQANQITIMWLTSPLFNQLSQGTEEMFAGLRSLIVGGDALSPKHIN
P39847_A2_val                            DQQTFLDSHQLKRYIEHQGITTIWLTSSLFNHLTEQNEQTFSQLKHLIIGGEALSPSHVN
Q70KJ6_A1_4__val                         KKETLLDAGQFAQFLKEQRITTMWLTSPLFNQLAQKDAGMFNTLRHLIIGGDALVPHIVS
O33743_A4_8__val                         SKDVLLDAEKLGDFLRTNQITTMWLTSPLFNQLSQDNPAMFDSLRALIVGGEALSPKHIN
Q04747_A1_4__val                         KKETLLDAKQFAAFLREQSITTMWLTSPLFNQLAAKDAGMFGTLRHLIIGGDALVPHIVS
P0C063_A2_val                            TKDVLLDAEKLHKFLQANQITIMWLTSPLFNQLSQGTEEMFAGLRSLIVGGDALSPKHIN
O69246_A1_4__val                         PKETLLDGKRFNMFLKETGITTMWLTSPLFNQIAQQDPGMFATLNDLIIGGDALVPGIVN
                                          ::.:**. ::  ::.   ** :****.***:::      *  *. **:**:** *  :.

P0C064_A2_3__val                         NVKRKCPNLTMWNGYGPTENTTFSTCFLIDKEYDDNIPIGKAISNSTVYIMDRYGQLQPV
P39847_A2_val                            RIRNVCPEVSIWNGYGPTENTTFSTCLHIQKTYELSIPIGRPVGNSTAFILNQWGVLQPV
Q70KJ6_A1_4__val                         KVRKASPELSLWNGYGPTENTTFSTSFLIDQDYDGSVPIGKPIGNSTAYIMDENRNLQPI
O33743_A4_8__val                         RVKSALPDLEIWNGYGPTENTTFSTCYLIEQHFEEQIPIGKPIANSTAYIVDGNNQPQPI
Q04747_A1_4__val                         KVKQASPSLSLWNGYGPTENTTFSTSFLIDREYGGSIPIGKPIGNSTAYIMDEQQCLQPI
P0C063_A2_val                            NVKRKCPNLTMWNGYGPTENTTFSTCFLIDKEYDDNIPIGKAISNSTVYIMDRYGQLQPV
O69246_A1_4__val                         RVKRESPELSLWNGYGPTENTTFSTCFLIDQAYERTIPIGKPIGNSTAYIVDEHGSLQPI
                                         .::   *.: :**************.  *:: :   :***:.:.***.:*::     **:

P0C064_A2_3__val                         GVPGELCVGGDGVARGYMNQPALTEEKFVPNPFAPGERMYRTGDLARWLPDGTIEYLGRI
P39847_A2_val                            GAVGELCVGGDGVARGYLGRPDLTKEKFVPHPFAPGDRLYRTGDLARWLSDGTIEYVGRI
Q70KJ6_A1_4__val                         GAPGELCVGGSGVARGYVNLPELTEKQFVRDPFRPDEMIYRTGDLAKWLPDGTIEFLGRI
O33743_A4_8__val                         GVPGELCVGGDGVARGYVNKPELTAEKFVPNPFAPGETMYRTGDLARWLPDGTIEYLGRI
Q04747_A1_4__val                         GAPGELCVGGIGVARGYVNLPELTEKQFLEDPFRPGERIYRTGDLARWLPDGNIEFLGRI
P0C063_A2_val                            GVPGELCVGGDGVARGYMNQPALTEEKFVPNPFAPGERMYRTGDLARWLPDGTIEYLGRI
O69246_A1_4__val                         GVPGELCVGGDGVARGYLNQPELTDEKFVGDPFAEGKRMYRTGDLAKWLPDGNIEFLGRI
                                         *. ******* ******:. * ** ::*: .**  .. :*******:**.**.**::***

P0C064_A2_3__val                         DQQVKIRGYRIEPGEIETLLVKHKKVKESVIMVVEDNNGQKALCAYYVPEEEVTVSE
P39847_A2_val                            DDQVKVRGYRVELGEIETALRQIDGVKEAAVLARTAQTGSKELFGYISVKAGTNAEQ
Q70KJ6_A1_4__val                         DNQVKVRGFRIELGEIEAKISQAENVTESAAVIRKNKADENEICAYFTADQALSPED
O33743_A4_8__val                         DQQVKIRGYRIELGEIETVLSQQAQVKEAVVAVIEEANGQKALCAYFVPEQAVDAAE
Q04747_A1_4__val                         DNQVKVRGFRIELGEIETKLNMAEHVTEAAVIIRKNKADENEICAYFTADREVAVSE
P0C063_A2_val                            DQQVKIRGYRIEPGEIETLLVKHKKVKESVIMVVEDNNGQKALCAYYVPEEEVTVSE
O69246_A1_4__val                         DHQVKVRGFRIELGEVEAALARLEGISEAAAVIRENNAGENEICVYYTAVGARPAAQ
                                         *.***:**:*:* **:*: :     :.*:.        ..: :  *          :
