CLUSTAL W multiple sequence alignment


P26046_A3_val                            IKAKAVLVHSSHASKCER----HGAKVIAV---DSPAIETAV--SQQSAADLPTIASL-G
P94873_A3_val                            TGARAVIADEASYPRISALAGHAARPVLNVHAHASASASELL-----PA--PASAAGG-D
P19787_A3_val                            IKAKAVLVHSSHASKCER----HGAKVIAV---DSPAIETAV--SQQSAADLPTIASL-G
P27743_A3_val                            TGAKLVLAGEAHGSRVRGL---TSGDVLDL---------EQLDLTGEPAENPVTETTS-T
Q9C1G0v2_A3_val                          TAAKALITTSKHETGMMCI---PGINLISI---DDPEVQKEL--QKQSLENFTSRSSAPS
Q9C1G0v1_A3_val                          TAAKALITTSKHETGMMCI---PGINLISI---DDPEVQKEL--QKQSLENFTSRSSAPS
P27742_A3_val                            VQAKILITESRYASAWGS----QTSTILAI---DSPKVSNMV--NNQATHNLPNIAGI-K
P25464_A3_val                            SSARTLITTRKHTPRGGTV---ANVPSVVL---DSPETLACL--NQQSKENPTTSTQKPS
                                           *: ::.     .             : :           :     .     . :    

P26046_A3_val                            NLAYIIFTSGTSGKPKGVLVEQKAVLLLRDALRERYFGRDCTKHHGVLFLSNYVFDFSVE
P94873_A3_val                            DFAYAIYTSGTTGRPKAVLVRHRNVLSFSAGLAQRYFGDAGAARQAILFLSSYVFDFSVE
P19787_A3_val                            NLAYIIFTSGTSGKPKGVLVEQKAVLLLRDALRERYFGRDCTKHHGVLFLSNYVFDFSVE
P27743_A3_val                            ELAYAIYTSGTTGKPKAVLVSHGSVDSFRAQLSGRYFGSPDESAEAVLFLANYVFDFSVE
Q9C1G0v2_A3_val                          NPAYIIFTSGTTGKPKGVLVEHSSVAKLRDSLVGRYFG-DTNGSHAVLFLSNYVFDFSLE
Q9C1G0v1_A3_val                          NPAYIIFTSGTTGKPKGVLVEHSSVAKLRDSLVGRYFG-DTNGSHAVLFLSNYVFDFSLE
P27742_A3_val                            NLAYIIFTSGTSGKPKGVLVEQGGVLHLRDALRKRYFGIECNEYHAVLFLSNYVFDFSIE
P25464_A3_val                            DLAYVIFTSGTTGKPKGVLVEHQSVVQLRNSLIERYFG-ETNGSHAVLFLSNYVFDFSLE
                                         : ** *:****:*:**.*** :  *  :   *  ****      ..:***:.******:*

P26046_A3_val                            QLVLSVLSGHKLIVPPAEFVADDEFYRMASTHGLSYLSGTPSLLQKIDLARLDHLQVVTA
P94873_A3_val                            QLALSILSGNALLIPESSLLFDDAFYQRMNQERLSYISGTPTQLQLFDLARLDHLHAVLV
P19787_A3_val                            QLVLSVLSGHKLIVPPAEFVADDEFYRMASTHGLSYLSGTPSLLQKIDLARLDHLQVVTA
P27743_A3_val                            QLALSVLGGHKLLVPPPSAADDPAFYELANREGLSYLSGTPTQVERFDLARLSHLRCVLV
Q9C1G0v2_A3_val                          QLCLSIFSGNKLVIPPEEGLTHEFFYAVAEAEKLSYISGTPSTLQQIQLSRLNHLQMVTA
Q9C1G0v1_A3_val                          QLCLSIFSGNKLVIPPEEGLTHEFFYAVAEAEKLSYISGTPSTLQQIQLSRLNHLQMVTA
P27742_A3_val                            QLVLSIMSGHKLIIPEGEFVADDEFYITANGQRLSYLSGTPSLLQQIDLARLNHLQVVTA
P25464_A3_val                            QLCLSVLGGNKLIIPPEEGLTHEAFYDIGRREKLSYLSGTPSVLQQIELSRLPHLHMVTA
                                         ** **::.*: *::*  .   .  **     . ***:****: :: ::*:** **: * .

P26046_A3_val                            AGEELHATQYEKMRRRFNGPIYNAYGVTETTVYNIIAEFTTNSIFENALREVLPGTRAYV
P94873_A3_val                            AGEAFRAHHFDKIRAEYRGPLYNAYGTTETTVYNLVKRFAPDAPYRNDLGHAIANTELHI
P19787_A3_val                            AGEELHATQYEKMRRRFNGPIYNAYGVTETTVYNIIAEFTTNSIFENALREVLPGTRAYV
P27743_A3_val                            AGEAFQPQHFEKMRGEFAGPILNAYGTTETTVYNTVHRFEPGDAYRNTLGAPLGNTRLYV
Q9C1G0v2_A3_val                          AGEEFHSSHYDSMRGQFKGPINNAYGITETSVYNIVTTFDADMPFTKALCEELPGTLAYV
Q9C1G0v1_A3_val                          AGEEFHSSHYDSMRGQFKGPINNAYGITETSVYNIVTTFDADMPFTKALCEELPGTLAYV
P27742_A3_val                            AGEQLHAAQFNKLRSGFRGPIYNAYGITETTVYNIVSEFSAQSQFENALRELLPGTRAYL
P25464_A3_val                            AGEEFHASQFEKMRSQFAGQINNAYGITETTVYNIITTFKGDAPFTKALCHGIPGSHVYV
                                         *** ::. :::.:*  : * : **** ***:*** :  *     : : *   : .:  ::

P26046_A3_val                            LNAALQPVPFDAVGELYLAGDSVTRGYLNQPLLTDQRFIPNPFCKEEDIAMGRFARLYKT
P94873_A3_val                            LDGELRELPPGGLGEIYMAGDCVGAGYLNRDELSRERFVANPFRSEDDRRLGRNDTLYKT
P19787_A3_val                            LNAALQPVPFDAVGELYLAGDSVTRGYLNQPLLTDQRFIPNPFCKEEDIAMGRFARLYKT
P27743_A3_val                            LGDGMKLLPTGAVGELYLAGDCVTEGYLHRPELTRERFLPNPFAAES----GRFPMIYRT
Q9C1G0v2_A3_val                          LNDNLQRVPPNAVGELYIGGECLSLGYLNQKALTEERFIPNPF-----TCDAE-QRLYKT
Q9C1G0v1_A3_val                          LNDNLQRVPPNAVGELYIGGECLSLGYLNQKALTEERFIPNPF-----TCDAE-QRLYKT
P27742_A3_val                            LNHATQPVPMNAVGELYLAGDCVARGYLNQPVLTGDRFIQNPFQTEQDIACGSYPRLYRT
P25464_A3_val                            LNDRLQRVPFNAVGELYLGGDCLARGYLNQDALTNERFIPNPFYEPKQASDSRPQRLYKT
                                         *.   : :* ..:**:*:.*:.:  ***::  *: :**: ***        .    :*:*

P26046_A3_val                            GDLVRSRFNRQQQPQLEYLGRGDLQIKMRGYRIEISEVQNVLTSSPGVREGAVVAKYENN
P94873_A3_val                            GDLVRRRHSGE----LEFFGRNDHQVKINGVRIELGEIEAVAAAFPGVAQCAVVARHDGE
P19787_A3_val                            GDLVRSRFNRQQQPQLEYLGRGDLQIKMRGYRIEISEVQNVLTSSPGVREGAVVAKYENN
P27743_A3_val                            GDVVRRGPDGE----LQYLGRNDAQVKINGLRIEPGEVEAALAGCSGVRQCAVVAGADPQ
Q9C1G0v2_A3_val                          GDMVRSLGSRG----IEFIGRRDQQVKLRGFRIELSEIRDAVLSSSGVKEAVVFPRYDET
Q9C1G0v1_A3_val                          GDMVRSLGSRG----IEFIGRRDQQVKLRGFRIELSEIRDAVLSSSGVKEAVVFPRYDET
P27742_A3_val                            GDLFRCRLDRQHQPYLEYLGRADLQVKIRGYRIEPSEVQNVLASCPGVRECAVVAKYENT
P25464_A3_val                            GDLVRFRGPHH----LEYLGRKDQQVKLRGFRIELSEVRDAVLAISAVKEAAVIPKYDED
                                         **:.*          ::::** * *:*:.* *** .*:. .  . ..* : .*..  :  

P26046_A3_val                            DTYSRTAHSLVGYYTT---DNETVSEAD
P94873_A3_val                            RSGGSR---LVCYYV----AAHNVSESA
P19787_A3_val                            DTYSRTAHSLVGYYTT---DNETVSEAD
P27743_A3_val                            APERKR---LVGYYLPEPGAA--VDEAD
Q9C1G0v2_A3_val                          KSSAGNVTALVCCYVA---EDRTECPST
Q9C1G0v1_A3_val                          KSSAGNVTALVCCYVA---EDRTECPST
P27742_A3_val                            DAYSRIAKFLVGYYTP---DTETVSDSS
P25464_A3_val                            GSDSRRVSAIVCYYTL---NAGTVCEAS
                                          .       :*  *            : 
